"""
Wide Source Synthesis — Romans chapter 9
bookId: romans
Run: python3 scripts/ws-synthesis-romans-9.py

Sources used: calvin, ellicott, clarke, wesley, barnes, rwp
  (mhcc not found for Romans; jfb file contains Acts content — both omitted)
Chapter range: 9  (33 verses)

Key synthesis decisions:
- v5 "God blessed for ever": Trinitarian reading — Calvin, Ellicott, RWP all take as affirming Christ's
  deity. Consensus: affirm.
- vv. 10-13 (Jacob/Esau): Calvin = unconditional individual predestination; Wesley/Clarke = corporate/
  national election about nations not individuals' eternal states. Consensus: divided.
- vv. 14-18 (Moses/Pharaoh hardening): Calvin = direct sovereign act; Wesley/Clarke = judicial
  permission after self-hardening; Barnes/Ellicott = middle course. Consensus: divided.
- vv. 19-24 (potter/clay, vessels of wrath): Calvin/Barnes = God's sovereign decree fits vessels for
  wrath; Wesley/Clarke = vessels fitted themselves by their own sin. Consensus: mixed.
- vv. 25-33: Hosea/Isaiah OT quotations and the stumbling stone — consensus affirm across all sources.
- ellicott missing v2,v10,v11,v13,v19,v23; clarke missing v2,v13; wesley missing v1,v11,v31;
  rwp missing v7 — use closest section-entry key for synthesis.
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_synthesis(book):
    p = ROOT / 'data' / 'commentary' / 'synthesis' / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_synthesis(book, data):
    p = ROOT / 'data' / 'commentary' / 'synthesis' / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_synthesis(existing, new_data):
    """Merge new chapter/verse entries without overwriting existing ones."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, entry in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = entry

DIVIDED_ELECTION = (
    "Calvin reads the election of Jacob over Esau as unconditional individual predestination to "
    "covenant blessing; Wesley and Clarke read it as corporate or national election — about the "
    "peoples descended from each, not the eternal destinies of the individuals themselves."
)

DIVIDED_HARDENING = (
    "Calvin treats divine hardening as a direct sovereign act flowing from God's freedom to show "
    "mercy or withhold it as he wills; Wesley and Clarke interpret it as judicial permission — God "
    "withdrawing his grace from those who had repeatedly hardened themselves; Barnes and Ellicott "
    "steer a middle course, affirming sovereignty while noting human agency in self-hardening."
)

MIXED_VESSELS = (
    "Calvin and Barnes read the vessels of wrath as prepared by God's sovereign decree for the "
    "display of his justice; Wesley and Clarke emphasize that the vessels fitted themselves for "
    "destruction through their own obstinate unbelief, placing the agency of destruction in human "
    "sin rather than divine ordination."
)

ROMANS = {
    "9": {
        "1": {
            "synthesis": "<p>Paul opens with a triple oath: he speaks in Christ, he does not lie, and his conscience bears him witness in the Holy Spirit. The three-fold asseveration signals that what follows might otherwise seem incredible — that a man as devoted to the gospel as Paul could feel such anguish over the very nation most hostile to it. Ellicott explains the phrase \"in Christ\" as the deepest level of the Christian's being: the most sacred interior space where union with Christ makes falsehood impossible. RWP notes the structural triple: a positive affirmation (\"I speak truth in Christ\"), a negative disclaimer (\"I lie not\"), and the appeal to conscience as co-witness in the Holy Spirit. Barnes adds that the solemn form of the oath is entirely warranted — Paul knows his anguish will be disbelieved by some Jews who suppose him indifferent to their nation, and by some Gentile Christians who suppose Jewish unbelief is a matter of unconcern to him. The double assurance of oath and conscience sets up the depth of grief Paul is about to confess.</p>",
            "voices": [
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>\"I say the truth in Christ\" — from the bottom of my soul, in the most sacred part of my being, as a Christian man united to Christ, I make this solemn asseveration. My conscience also bears witness — here, as in 2:15, the introspective faculty which sits in judgment upon actions and assigns them their moral quality.</p>"},
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>Paul really takes a triple oath here, so strongly is he stirred. He makes a positive affirmation in Christ, a negative one (not lying), and the appeal to his conscience as co-witness (<em>συνμαρτυρούσης</em>, genitive absolute as in 2:15) \"in the Holy Spirit.\"</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>The solemn form of assurance here is entirely warranted. Paul knows his anguish will be disbelieved by Jews who suppose him an enemy to his nation, and by Gentile Christians to whom Jewish unbelief seems remote. The triple form — truth in Christ, no lie, conscience as witness — meets both objections at once.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "2": {
            "synthesis": "<p>The grief itself: great sorrow and unceasing anguish in Paul's heart. The two words — λύπη (sorrow, grief) and ὀδύνη (anguish, consuming pain) — are not synonyms but complementary. Clarke distinguishes them: λύπη is the settled sorrow of grief; ὀδύνη is the sharper, more acute sensation of pain. Barnes notes that the word \"unceasing\" (ἀδιάλειπτος) is striking — this is not an occasional pang but a chronic condition that follows Paul even in his highest joys. Wesley's note is brief but pointed: the very depth of Paul's joy in the gospel (see chs. 5-8) makes the counterpoint of grief sharper — the more vividly he sees what Israel is missing, the more acutely it pains him. Calvin observes that Paul's grief over Israel is itself an evidence of the sincerity of his devotion to Christ — a man who hated his nation could not grieve thus for it.</p>",
            "voices": [
                {"src": "clarke", "attr": "Adam Clarke's Commentary", "html": "<p>Great heaviness and continual sorrow — <em>λύπη</em> and <em>ὀδύνη</em> are not exact synonyms: the first describes settled grief, the weight of sorrow; the second, the sharper, more acute pain of anguish. Both together convey the full depth of Paul's distress over his countrymen's rejection of the Messiah.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>Unceasing — this word (<em>ἀδιάλειπτος</em>) is remarkable. Paul does not describe an occasional pang but a chronic condition — a sorrow that persists through all other circumstances, never lifting. The joy of chapters 5-8 does not cancel it but runs alongside it.</p>"},
                {"src": "wesley", "attr": "John Wesley's Notes", "html": "<p>Paul's grief is real and continuous — the very clarity with which he sees Israel's privileges (vv. 4-5) and the full salvation available in Christ sharpens the pain of their missing it. The greater his joy in the gospel, the more acute his anguish for those who reject it.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "3": {
            "synthesis": "<p>The startling hypothetical: Paul could wish himself accursed (ἀνάθεμα) and cut off from Christ for the sake of his brothers, his kinsmen according to the flesh. Calvin immediately signals the rhetorical function: this is a godly ardor that carries a man beyond himself, an expression of love so intense that Paul can hardly form it into a coherent wish — for of course no one can be cut off from Christ for another's benefit, and Paul does not claim this is possible. RWP traces the background: Moses made a similar intercessory offer in Exodus 32:32 (\"blot me out of your book\"), and here Paul goes further still. Barnes explains the grammar: \"I could wish\" (ηὐχόμην, the imperfect) conveys that this is a present wish, not a realized one — he would be willing for this if it were possible and if it would accomplish Israel's salvation. Clarke sees this as the strongest possible evidence that Paul's opposition to Jewish exclusivism came from love of Jews, not indifference to them.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>It is a godly ardor which carries a man, as it were, beyond himself, and exceeds what might be reasonably expected. It is an expression of love so intense that Paul cannot quite contain it — knowing it is impossible to be accursed for another's salvation, yet feeling a desire so strong that it rises to the form of a wish.</p>"},
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>Anathema from Christ (<em>ἀνάθεμα ἀπὸ τοῦ Χριστοῦ</em>). Paul makes a conditional wish, not an actual one. Moses made a similar imprecation in Ex 32:32. The imperfect (<em>ηὐχόμην</em>) softens the statement — \"I was on the point of wishing,\" or \"I could wish.\"</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>\"I could wish\" — the imperfect tense conveys a present wish, not one realized. He would be willing if it were possible and would accomplish the purpose. Clarke notes this is the strongest possible demonstration that Paul's rebuke of Jewish exclusivism arose from love of his nation, not contempt for it.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "4": {
            "synthesis": "<p>The enumerated privileges of Israel unfold across this verse with increasing solemnity: adoption as sons, the divine glory (shekinah), the covenants (plural — Abrahamic, Mosaic, Davidic), the giving of the law, the temple service (λατρεία), and the promises (Messianic and general). Calvin notes that Paul is not simply listing benefits — he is showing that the more gifts God lavished on Israel, the more inexplicable their rejection of Christ becomes. Ellicott takes the adoption language as equivalent to 2 Samuel 7:14 and Hosea 11:1 — Israel was God's son corporately, called out of Egypt as a nation. Clarke identifies the glory as the Shekinah, the visible manifestation of God in the tabernacle and temple. Barnes emphasizes that each of these gifts was given to prepare Israel for the Messiah — making their rejection of him the more paradoxical. Wesley sees the list as a statement of indebtedness: what nation ever had such advantages and was thus accountable for what they did with them?</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>Paul is not listing benefits simply to honor Israel but to show the inexplicableness of their rejection of the Messiah — the more gifts God lavished, the more astonishing the refusal. \"The adoption\" refers to the special covenant by which God claimed Israel as his firstborn son (Ex 4:22).</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>The adoption: cf. 2 Samuel 7:14, Hosea 11:1 — Israel was God's son corporately, called out of Egypt as a nation-child. The glory: the <em>Shekinah</em>, the visible symbol of the divine presence in the tabernacle and temple. The covenants: plural, covering Abrahamic, Mosaic, and Davidic.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>Each of these gifts was given in order to prepare Israel for the Messiah — adoption, glory, covenants, law, worship, promises all pointed toward him. Their rejection of him is therefore the greater paradox: every privilege they possessed was a preparation for what they refused.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "5": {
            "synthesis": "<p>Paul crowns the list with the supreme privilege: from the patriarchs came Christ, according to the flesh — and then the famous doxological clause. The phrase \"who is over all, God blessed for ever\" (ὁ ὢν ἐπὶ πάντων θεὸς εὐλογητὸς εἰς τοὺς αἰῶνας) is one of the most discussed in the Pauline letters. RWP calls it \"a clear statement of Paul's view of Christ as θεός\" — the participial phrase ὁ ὢν (the one who is, present active participle of εἰμί) is the same construction used for the eternal God in Revelation. Calvin, Ellicott, and Wesley all read it as an attribution of supreme divine nature to Christ himself, with Wesley adding the words convey \"self-existent, independent Being, who was, is, and is to come.\" Socinian and some German interpreters since the Reformation have proposed a stop after \"flesh\" to make the doxology refer to God the Father, but the overwhelming grammatical and theological weight of the text, and the consensus of these commentators, supports the Trinitarian reading.</p>",
            "voices": [
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>Who is over all, God blessed for ever (<em>ὁ ὢν ἐπὶ πάντων θεὸς εὐλογητός</em>). A clear statement of Paul's view of Christ as θεός. The participial phrase (<em>ὁ ὢν</em>, \"the one who is\") is the same construction used of the eternal God. Most scholars take this as referring to Christ; Socinian interpreters punctuate it otherwise, but the grammar strongly resists them.</p>"},
                {"src": "wesley", "attr": "John Wesley's Notes", "html": "<p>Who is over all, God blessed for ever — the original words imply the self-existent, independent Being, who was, is, and is to come. Over all — the supreme; as being God, and consequently blessed for ever. No words can more clearly express his divine, supreme nature.</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>\"Who is over all, God blessed for ever\" — a well-known subject of controversy. Trinitarian and English interpreters take them (with the A.V. punctuation) as referring to Christ. Socinian interpreters, with some eminent Germans, put a full stop after \"came.\" The grammar and context, however, strongly favor the Trinitarian reading.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "6": {
            "synthesis": "<p>Paul turns to the problem the chapter exists to address: does the mass unbelief of Israel mean God's word has failed? He denies this firmly. The key distinction is that \"not all who are of Israel are Israel\" — physical descent from Jacob does not constitute membership in the true Israel of promise. Calvin explains that Paul is qualifying the extravagance of his grief (v. 2-3) without contradicting it: it was not as though all Israel is lost — some are enjoying the promise even now. Ellicott observes that Paul is not so much defending God's faithfulness as clarifying what the word of promise actually said — it never promised salvation to every biological descendant of Jacob without qualification. RWP is crisp: \"For they are not all Israel, which are of Israel\" — the outer circle of physical Israel always enclosed a smaller inner circle of the true seed. Barnes notes this distinction carries forward the point already made in chs. 2-3: a Jew is not merely outwardly so; the promise belongs to faith, not flesh.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>Paul is qualifying the extravagance of his grief without contradicting it. He was not affirming that all Israel is lost — some are enjoying the promise even now, and the covenant promise was never guaranteed to every biological descendant without qualification. The outer Israel always contained an inner, elected Israel.</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>\"Not as though the word of God hath taken none effect\" — Paul is not so much defending God's faithfulness as clarifying what the word of promise actually said. It was given to Israel, but Israel was always understood to be the true spiritual Israel, not every descendant of Jacob indiscriminately.</p>"},
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>\"For they are not all Israel, which are of Israel\" (<em>οὐ γὰρ πάντες οἱ ἐξ Ἰσραὴλ οὗτοι Ἰσραήλ</em>). The outer circle of physical Israel always enclosed a smaller inner circle — those who were Israel in the full sense of covenant membership.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "7": {
            "synthesis": "<p>The first scriptural proof of the inner/outer distinction: not all of Abraham's children are \"the seed\" — \"In Isaac shall your seed be called\" (Genesis 21:12). Ishmael was Abraham's son as surely as Isaac, yet the promise passed through Isaac alone. Calvin observes this illustrates that hidden election overrules and yet confirms outward calling — the external covenant sign (circumcision) applied to Ishmael too, but the effective promise did not. Barnes notes the argument is particularly pointed for Jewish readers: the very Scripture they revere most makes this distinction from the beginning of the covenant story. Clarke sees Paul choosing this example deliberately — no Jew could dispute the precedent, since the differentiation of Isaac from Ishmael was foundational to Jewish self-understanding. The principle established here runs forward through vv. 8-13 and beyond: natural descent is not the ground of the promise.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>Paul mentions this to show that hidden election overrules the outward calling — and yet that it is by no means inconsistent with it, but tends to its confirmation. The covenant sign of circumcision applied to Ishmael, but the effective promise did not. Divine election narrows within the formal covenant from the very beginning.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>\"In Isaac shall thy seed be called\" — this example is particularly pointed for Jewish readers: the very Scripture they revere most makes the inner/outer distinction from the beginning of Abraham's covenant story. No Jew could dispute the precedent; it was foundational to Jewish self-understanding.</p>"},
                {"src": "clarke", "attr": "Adam Clarke's Commentary", "html": "<p>Paul chose this example deliberately — the differentiation of Isaac from Ishmael was the founding act of God's covenant election. No objection could be raised against it. If God distinguished within Abraham's own household from the start, the principle of distinction within the covenant family is established from the beginning.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "8": {
            "synthesis": "<p>The principle is now stated explicitly: it is not the children of the flesh who are children of God, but the children of the promise who are reckoned as the seed. This is the governing proposition of the chapter's first argument. Calvin notes Paul \"gathers from God's answer a proposition, which includes the whole of what he had in view\" — the entire Ishmael/Isaac narrative was to establish this principle. RWP points to the sharp contrast: τέκνα τῆς σαρκός (children of the flesh) vs. τέκνα τῆς ἐπαγγελίας (children of the promise). Ellicott clarifies the logic: mere natural birth within the covenant family does not automatically confer the covenant promise — what constitutes one a true child of God is divine calling and promise, not biological lineage. Barnes draws the application: the same principle that excluded Ishmael also holds under the gospel — the true seed of Abraham is those who share his faith (Galatians 3:29).</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>He now gathers from God's answer a proposition which includes the whole of what he had in view: that the promise of God is not effectual among all the descendants of Abraham, but that the election of God overrules natural descent. The children of the flesh are those born of Abraham naturally; the children of the promise are those to whom the promise was directed.</p>"},
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>Children of the flesh (<em>τέκνα τῆς σαρκός</em>) vs. children of the promise (<em>τέκνα τῆς ἐπαγγελίας</em>). The sharp contrast is between two kinds of descent — natural birth within the covenant family, and divine calling through promise. Only the latter constitutes one a true child of God.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>The principle that excluded Ishmael holds under the gospel. The true seed of Abraham is those who share his faith — as Galatians 3:29 makes explicit: \"If ye be Christ's, then are ye Abraham's seed, and heirs according to the promise.\" Flesh does not produce children of God; promise does.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "9": {
            "synthesis": "<p>The proof text for the promise-not-flesh principle: God's word to Abraham and Sarah, \"At this time I will come and Sarah shall have a son\" (Genesis 18:10). Calvin explains that the divine visit — \"I will come\" — and the specification of Sarah as the mother both show that the birth of Isaac was not the natural fruit of Abraham's house but a fresh sovereign act of promise. RWP notes that Paul is not quoting Genesis verbatim but reconstructing the substance: the significant point is that God's initiative, not human fertility, produced the child of promise. Barnes observes that the particularity of the promise (\"At this time,\" \"Sarah\") makes Paul's argument more forceful than a general appeal to Isaac could be — the very precision of the divine word confirms that this birth was being specially decreed, not merely foreseen. Ellicott adds: the fact that Paul cites this word proves that for him, Israel's true identity was always grounded in divine promise, not natural generation.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>The divine visit — \"I will come\" — and the specification of Sarah as the mother both show that the birth of Isaac was not the natural fruit of Abraham's house but a fresh sovereign act of promise. The promise did not follow the child; the child followed the promise.</p>"},
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>Paul reconstructs the substance of Genesis 18:10 rather than quoting verbatim. The significant point is that God's initiative, not human fertility, produced the child of promise. The divine word precedes, and generates, the birth it announces.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>The particularity of the promise — \"at this time,\" \"Sarah\" — makes Paul's argument more forceful. The precision of the divine word confirms that this birth was being specially decreed. Not merely foreseen but freely determined: thus the promise-principle, not flesh, is primary from the start.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "10": {
            "synthesis": "<p>A second, stronger example: Rebecca's two sons by the same father, Isaac. Calvin describes the sentence as \"broken\" — the Greek has an anacoluthon, leaving off before the principal verb — but the meaning is unmistakable: the distinction between Jacob and Esau is even more pointed than that between Isaac and Ishmael, because they share both parents and womb. Ishmael was the son of a different mother (Hagar); Jacob and Esau shared everything in human terms — the same father, the same mother, the same conception. Clarke sees Paul selecting this example precisely because it removes the last natural explanation for the distinction (different maternity, as with Ishmael). Barnes notes that this example climaxes the two-step argument: if God distinguished even among children of the same womb, before either had acted, then the distinction is irreducibly divine, not human. RWP: \"Having, even Rebecca, her conception by one, by our father Isaac\" — the single act of conception intensifies the point.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>The second example is more pointed: Jacob and Esau share both parents and womb. Ishmael had a different mother — Hagar — which could have explained the distinction. But Jacob and Esau shared everything in human terms, so the distinction between them can only be traced to the electing purpose of God, not to any human cause.</p>"},
                {"src": "clarke", "attr": "Adam Clarke's Commentary", "html": "<p>Paul selects this example precisely because it removes the last natural explanation. Ishmael's different maternity could have suggested a natural ground for the distinction between him and Isaac. No such natural explanation remains in the case of Jacob and Esau — same father, same mother, same act of conception.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>This example climaxes the two-step argument: if God distinguished even among children of the same womb, before either had acted, then the distinction is irreducibly divine and not human. The argument moves from Ishmael/Isaac (different mothers) to Jacob/Esau (same mother) to exclude every natural explanation.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "11": {
            "synthesis": "<p>\"The children being not yet born, neither having done anything good or evil\" — the divine purpose was declared before the twins had any personal history, so that it might stand on the basis of God's calling rather than human works. This is the pivot of the predestination argument. Calvin reads this as election operating at the level of individuals, prior to any personal merit or demerit. Clarke dissents: \"as the word children is not in the text, the word nations would be more proper; for it is of nations that the apostle speaks.\" Wesley similarly reads the election as pertaining to the nations/peoples descended from Jacob and Esau respectively, not to the eternal destinies of the two men themselves. Barnes reads more in line with Calvin: the pre-birth timing shows the election was prior to works, and therefore based in God's sovereign purpose alone. The argument from pre-birth timing functions both as evidence of God's freedom (Calvin/Barnes) and as evidence that this was about corporate destinies, not individual eternal fates (Wesley/Clarke).</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>He ascends higher, to show the cause of the difference, which can nowhere be found except in the election of God. Since the distinction was made before their birth, it cannot be founded in works or merit of any kind — it must rest in the sovereign purpose of God alone, the only ground left standing.</p>"},
                {"src": "clarke", "attr": "Adam Clarke's Commentary", "html": "<p>\"For the children being not yet born\" — as the word <em>children</em> is not in the text, <em>nations</em> would be more proper; it is of nations that the apostle speaks, as the following verses show. \"Neither having done any good\" — to merit the distinction of being made God's peculiar people; nor evil, to deserve to be left out of it.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>\"Not yet born, neither having done anything good or evil\" — this removes the election from any basis in human works. It was laid back of any character they had formed, and therefore had its foundation in the purpose or plan of God. The pre-birth timing is Paul's proof that the distinction is grounded in divine calling, not human merit.</p>"}
            ],
            "consensus": "divided",
            "key_tension": DIVIDED_ELECTION
        },
        "12": {
            "synthesis": "<p>\"The elder will serve the younger\" — the divine oracle given to Rebecca before the twins' birth (Genesis 25:23). Calvin sees this as the symbol of a deeper spiritual truth: the earthly servitude of Esau's descendants to Jacob's prefigures the rejection of Esau's line from the special covenant blessing. Wesley is more restrictive: \"The elder nation\" — the prophecy is about nations and their relative standing, not about the eternal states of the two individuals. Ellicott notes that in its original context the prophecy referred to national relationships, though Paul is drawing a principle from it about the priority of divine purpose over natural order. Barnes: though the literal reference is to nations, the principle Paul derives is larger — even within the covenant family, the order of blessing can be reversed by divine calling, independent of human priority (the firstborn right). RWP: \"The elder shall serve the younger\" — proleptic of the Edom-Israel history, and illustrative of the general principle of election by purpose.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>The heavenly answer given to Rebecca — \"the elder shall serve the younger\" — shows that God designed to show the younger peculiar favor denied to the elder. Though this had reference first to the right of primogeniture, yet in this, as a symbol, the spiritual condition of both was intimated: covenant blessing does not follow natural birth-order.</p>"},
                {"src": "wesley", "attr": "John Wesley's Notes", "html": "<p>The elder nation shall serve the younger — the prophecy is primarily about nations and their relative standing before God and in history. Paul uses it to illustrate that God's purpose in election overrides natural human priority — the first-born right of Esau did not bind God's freedom to choose Jacob.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>Though the literal reference is national, the principle Paul derives is larger — even within the covenant family, the order of blessing can be reversed by divine calling, independent of human natural priority. The firstborn right was the highest human claim; God overrode it by sovereign choice.</p>"}
            ],
            "consensus": "divided",
            "key_tension": DIVIDED_ELECTION
        },
        "13": {
            "synthesis": "<p>\"Jacob I loved, but Esau I hated\" — from Malachi 1:2-3, written centuries after the twins' death, concerning the fates of their nations. RWP observes that the word μισέω here may not carry the full weight of what modern readers mean by \"hate\" — as in Luke 14:26 (hating father and mother for Christ's sake) and Matthew 6:24 (cannot serve two masters), \"hate\" can mean comparatively lesser love or positive disinclination. Wesley is explicit: \"This does not relate to the person of Jacob or Esau, nor does it relate to the eternal state either of them or their posterity.\" Clarke similarly reads the prophecy as about national histories — the Edomites' desolation and the Israelites' restoration. Calvin takes it more broadly: the spiritual condition of both lines was prefigured in the historical difference, and this difference traces ultimately to divine election rather than national merit. Barnes reads it as God's sovereign disposition of nations, acknowledging the corporate dimension without entirely excluding the principle of individual election that the prior verses established.</p>",
            "voices": [
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>\"Esau I hated\" (<em>τὸν δὲ Ἠσαῦ ἐμίσησα</em>). This language sounds harsh. It is possible that <em>μισέω</em> did not always carry the full modern force of \"hate\" — as in Luke 14:26 and Mt 6:24, where the same verb expresses comparatively lesser love. Paul quotes Malachi 1:2-3, which concerns the national histories of Edom and Israel, not the eternal destinies of the two individuals.</p>"},
                {"src": "wesley", "attr": "John Wesley's Notes", "html": "<p>\"Jacob I loved, Esau I hated\" — observe: this does not relate to the person of Jacob or Esau, nor to the eternal state of either of them or their posterity. It speaks of God's purpose in giving the elder nation to serve the younger — a national, historical reference, consistent with Malachi's own context.</p>"},
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>The prophet confirms, by a later testimony, what the earlier oracle already implied: the spiritual condition of both lines was prefigured in their historical difference. This difference traces to divine election, not national merit. Jacob obtained favor through God's kindness — not his own merit — and this is what the prophet affirms.</p>"}
            ],
            "consensus": "divided",
            "key_tension": DIVIDED_ELECTION
        },
        "14": {
            "synthesis": "<p>Is there unrighteousness with God? Paul raises and immediately rejects the most natural objection to the election argument. The Greek question uses μή, expecting the answer \"No\" — but the urgency with which Paul raises it shows how live the charge was. Calvin observes that the flesh, whenever it hears of divine election, immediately murmurs and attempts to call God to account. Ellicott frames the objection sharply: does not this apparently arbitrary choice of one and rejection of another imply injustice in the one who exercises it? Clarke reads the objection straightforwardly: it is unjust for God to bestow peculiar privileges in this unequal manner on those otherwise in equal circumstances. Wesley's answer points forward: it is not unjust, because God has a right to fix the terms on which he will show mercy — and the terms he has fixed are faith, not works or birth. Barnes adds that the very fact Paul raises this objection shows that the doctrine he has stated is the full-weight doctrine of unconditional election — not some weaker view that would not generate this objection.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>The flesh, whenever it hears anything of what Scripture teaches respecting predestination, instantly boils up with numberless questions — it attempts to call God to account. Paul obviates this by raising the objection himself, so as to meet it head-on with the full authority of Scripture rather than leaving it to fester.</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>Is there unrighteousness with God? — Does not this apparently arbitrary choice of one and rejection of another imply injustice in him who exercises it? The thought is not to be entertained. Paul meets the objection not with a philosophical refutation but with the testimony of Scripture itself.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>The fact that Paul raises this objection shows that the doctrine he has stated generates this objection — which means it is the full-weight doctrine of unconditional election, not some weaker view that would not provoke the charge. Only real unconditional election raises this question forcefully.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "15": {
            "synthesis": "<p>The first answer: God's word to Moses in Exodus 33:19 — \"I will have mercy on whom I have mercy, and I will have compassion on whom I have compassion.\" Calvin notes the verb ἐλεέω here is better rendered as showing favor than as showing mercy in the narrow sense — but in either case, the decisive point is the repeated indefinite pronoun: \"on whom I will.\" The repetition emphasizes not the abstract freedom of God but its concrete application — the freedom is not merely asserted but exercised. Ellicott: in the most characteristic period of the Old Testament, when Moses interceded for Israel after the golden calf, God's favor was promised in this way — freely, sovereignly, not contingent on Israel's merit. RWP explains the Greek construction: ὃν ἄν with the subjunctive = \"on whomsoever I have mercy\" — the indefinite relative makes the statement perfectly general. Wesley and Clarke both read this as God declaring his right to set the terms of mercy, not as predetermining which individuals will believe.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>The quotation is from Ex 33:19. The repeated \"on whom I will\" is the decisive point: God's freedom in showing mercy is not merely asserted in principle but concretely exercised — he does not explain why he shows mercy to one rather than another, but asserts his sovereign right to do so.</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>In the most characteristic period of the Old Testament — when Moses interceded after the golden calf, the supreme crisis of Sinai — God's favor was promised in this way: freely, sovereignly, not contingent on Israel's merit. The most intimate moment of revealed grace is also the moment of most sovereign freedom.</p>"},
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>On whom I have mercy (<em>ὃν ἄν ἐλεῶ</em>). Indefinite relative with <em>ἄν</em> and present active subjunctive — \"on whomsoever I have mercy.\" The same construction in the parallel clause. The indefinite relative makes the statement perfectly general — it excludes every qualification except the divine will itself.</p>"}
            ],
            "consensus": "divided",
            "key_tension": DIVIDED_HARDENING
        },
        "16": {
            "synthesis": "<p>\"So then it is not of him that wills, nor of him that runs, but of God that shows mercy.\" The conclusion from the Moses quotation: the origin of the mercy shown is entirely in God, not in the recipient's willing or striving. Calvin sees this as the clearest possible statement that salvation is from God alone — it is not that willing and running are evil or forbidden, but that they are not the ground of mercy. Ellicott reads \"wills\" and \"runs\" as references to human effort in any form — religious striving, moral achievement, race-running in the Pauline athletic metaphor. Clarke acknowledges the verse's force but resists its extension to individual eternal election: God's sovereignty in setting the terms of mercy does not predetermine which individuals will respond. Wesley is consistent: mercy is sovereignly given according to God's terms (faith, not works), but those terms are open to all — the verse establishes the source of mercy, not the predestination of specific persons to receive it. Barnes: the running and willing are not excluded as acts, but as grounds — mercy depends on God's decision, not the creature's effort.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>It is the clearest possible statement that salvation originates in God alone. Willing and running are not condemned as evil — but they are not the ground of the mercy received. The mercy comes from God's sovereign choice to extend it; human effort follows, it does not produce.</p>"},
                {"src": "wesley", "attr": "John Wesley's Notes", "html": "<p>The verse establishes the source of mercy: not human will or effort, but God's free gift. But this is consistent with God's terms being open to all — faith, not works or birth, is the condition he has freely chosen. The sovereignty established here is over the terms of mercy, not over which individuals will respond to those terms.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>The willing and running are not excluded as acts — Paul does not say human effort is worthless. What the verse excludes is effort as the ground of mercy. Mercy depends on God's sovereign decision to extend it; it is not earned by any intensity of striving.</p>"}
            ],
            "consensus": "divided",
            "key_tension": DIVIDED_HARDENING
        },
        "17": {
            "synthesis": "<p>The counter-example to Moses: Pharaoh. God says to Pharaoh in Exodus 9:16, \"For this very purpose I have raised you up, that I might show my power in you, and that my name might be proclaimed in all the earth.\" Calvin reads ἐξήγειρά σε (I raised you up) as referring to God's providential appointment of Pharaoh to his position — he was brought to this place in history specifically to be the theater on which divine power would be displayed through judgment. RWP confirms: ἐξεγείρω means to wake up or stir up, here to raise up providentially. Ellicott connects this verse to the sovereignty argument of vv. 14-18 as a whole: it was not merely that God foreknew Pharaoh's hardness, but that Pharaoh was positioned by divine purpose for this demonstration. Barnes carefully qualifies: God did not make Pharaoh wicked, but he determined that in Pharaoh's case — rather than some other — the display of power through judgment would be made. Clarke and Wesley stress the prior self-hardening: Pharaoh had hardened himself repeatedly before God hardened him.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>God says he raised up Pharaoh — brought him to his position by providential purpose — specifically for this: that divine power might be displayed through judgment on him, and God's name proclaimed through the whole earth. Pharaoh was providentially appointed to be the theater of that display, not accidentally placed in it.</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>This verse is the counterpart to the Moses quotation. Moses illustrates sovereign mercy; Pharaoh illustrates sovereign severity. God declares his purpose in Pharaoh's position and career: the display of power and the proclamation of his name. The two cases together bound the range of divine sovereignty.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>God did not make Pharaoh wicked, but he determined that in Pharaoh's case — rather than some other — the display of power through judgment would be made. Pharaoh's position in history was sovereignly appointed; his wickedness was his own. The appointment and the wickedness must be distinguished.</p>"}
            ],
            "consensus": "divided",
            "key_tension": DIVIDED_HARDENING
        },
        "18": {
            "synthesis": "<p>The double conclusion: \"He has mercy on whom he will, and he hardens whom he will.\" This is the most direct statement of the hardening doctrine in Paul. Ellicott notes it is a summary conclusion from both cases (Moses and Pharaoh) and that God's decrees include human free-will without destroying it — Pharaoh hardened his own heart in Exodus 8-9 before the language of God's hardening appears. RWP confirms: \"Pharaoh hardened his own heart also (Ex 8:15, 32; 9:34), but God gives men up also (1:24, 26, 28).\" Calvin accepts both dimensions but insists on the sovereignty: God, according to his own will, withholds the mercy from some that he grants to others, and this withholding is itself an act of his will. Wesley is precise: \"Whom he willeth he hardeneth — leaves to the hardness of their hearts\" — the hardening is a judicial permission, a withdrawal of grace from those who have persistently rejected it. Clarke similarly: God suffers some to be hardened through the abuse of his mercies. Barnes: hardening \"does not mean to exert a positive influence\" but to act as Pharaoh's case illustrates — leaving one to the consequences of his own rejection of repeated grace.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>The conclusion of both parts: God, according to his own will and wisdom, in perfect righteousness, shows mercy to some and hardens others. He does not render a reason why this man rather than that man — it is not meet that the hidden things of his counsel should be subjected to human reason. It is enough that his will is the highest rule of righteousness.</p>"},
                {"src": "wesley", "attr": "John Wesley's Notes", "html": "<p>\"Whom he willeth he hardeneth — leaves to the hardness of their hearts.\" The hardening is a judicial act — a withdrawal of grace from those who have persistently refused it. God does not make them hard; he leaves them to what they have chosen. His will is executed in permitting what they have insisted on.</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>In Exodus 8:32; 9:34; 13:15, the hardening of Pharaoh's heart is attributed to his own act. That act may, however, be regarded as a part of the design of Providence. God's decrees include human free-will without destroying it. The sovereignty and the human agency are both real; neither cancels the other.</p>"}
            ],
            "consensus": "divided",
            "key_tension": DIVIDED_HARDENING
        },
        "19": {
            "synthesis": "<p>The objector returns: \"Why does he still find fault? For who can resist his will?\" If God's will determines who hardens and who receives mercy, and no one can resist that will, then how can God justly hold anyone accountable? This is the precise logical difficulty that any strong doctrine of divine sovereignty generates. Calvin notes that Paul does not answer this directly but first rebukes the presumption of the question. Ellicott: the answer is \"not so much a solution of the intellectual difficulty, as an appeal to the religious sense to prevent it from being raised\" — the real answer is that questioning God's right to act is itself the breach of reverence. Barnes identifies two answers Paul gives in sequence: first (vv. 20-21), the sovereignty argument — God has the right as Creator; second (vv. 22-24), the justice argument — what he actually does is just. Clarke reads the objector as anyone confronting the Calvinist conclusion and finding it morally untenable: if the will that determines all is irresistible, blame becomes incoherent. RWP: the objector assumes that moral responsibility requires the ability to have done otherwise.</p>",
            "voices": [
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>The answer is not so much a solution of the intellectual difficulty, as an appeal to the religious sense to prevent it from being raised. That God's dealings should be questioned at all is itself a breach of the reverence due to him. The question assumes a standard above God by which his acts could be judged — that is where the error lies.</p>"},
                {"src": "clarke", "attr": "Adam Clarke's Commentary", "html": "<p>If God's will is irresistible and yet he still finds fault, the objector says moral accountability becomes incoherent. This is the precise logical difficulty generated by strong predestination: if no one can resist God's will, blame loses its footing. Paul addresses it — but not by conceding the objection's premise.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>Paul answers in two stages: first (vv. 20-21), the sovereignty argument — God as Creator has an inherent right to dispose of his creatures; second (vv. 22-24), the justice argument — what he actually does is consistent with justice and mercy. The two answers address the right and the practice of divine sovereignty separately.</p>"}
            ],
            "consensus": "mixed",
            "key_tension": MIXED_VESSELS
        },
        "20": {
            "synthesis": "<p>\"Nay but, O man, who are you to answer back to God? Will the thing molded say to its molder, 'Why have you made me like this?'\" Paul's first answer is not a philosophical resolution but a rebuke of the presumption of the question. RWP highlights the emphatic word order: \"O man, but surely thou — who art thou?\" The prolepsis of σύ before τίς is unusual and forceful. Calvin and Ellicott both note that Paul is not evading the question but addressing its root error — the assumption that the creature has standing to evaluate and criticize the Creator's decisions. Clarke and Wesley stress the implied humility required: before a creature accuses God of injustice, it should reflect on its own corruption and abuse of grace. Barnes: the force is not to silence inquiry but to point out the disproportion between the creature's limited wisdom and the divine wisdom that governs all things. The Isaiah 29:16 / 45:9 background (the clay-potter image) shows this is not a Pauline novelty but part of Israel's own prophetic tradition.</p>",
            "voices": [
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>\"Nay, but, O man, who art thou?\" (<em>ὦ ἄνθρωπε, μὲν οὖν γε σύ τίς εἶ</em>). Unusual and emphatic order — prolepsis of σύ (thou) before τίς (who). Triple particle (<em>μέν, οὖν, γε</em>) at the beginning, as in Rom 10:18. Paul confronts the questioner's presumption head-on.</p>"},
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>Paul is not evading the question but addressing its root error: the assumption that the creature has standing to judge the Creator. The creature's ability to frame questions about God does not give it standing to judge God. The finite cannot measure the infinite — and the corrupt cannot evaluate the holy.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>The force is not to silence all inquiry but to point out the disproportion between human wisdom and divine wisdom. Paul is not saying God cannot be asked about — but that the posture of the question (\"Why have you made me thus?\" implying a grievance) reveals a misunderstanding of the creature's position before its Creator.</p>"}
            ],
            "consensus": "mixed",
            "key_tension": MIXED_VESSELS
        },
        "21": {
            "synthesis": "<p>\"Or does the potter not have authority over the clay, to make from the same lump one vessel for honored use and another for dishonored use?\" The potter-clay metaphor establishes the Creator's inherent right to differentiate. Calvin identifies four laws or types of relationship involved in ch. 9: the law of God (rule of righteousness), the law of the mind (conscience), the law of the members (sinful impulse), and the law of sin (its mastery). But here the operative relationship is simpler: Creator and creature. Barnes notes that the analogy is limited: clay is passive, humans are active moral agents — but the point of the analogy is not the clay's passivity but the potter's inherent right to form as he sees fit. Clarke and Wesley add a crucial distinction: the potter does not make the clay bad — the clay's qualities are its own. The potter works with what he finds. So God's exercise of sovereignty over human beings does not make him the author of their sin; he works with the moral character they have formed. Ellicott: the right asserted here is not arbitrary but creatorial — the authority of the one who made the material.</p>",
            "voices": [
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>The analogy is limited — clay is passive, humans are active moral agents. But the point is not the clay's passivity but the potter's inherent creatorial right to form as he sees fit. Paul uses the analogy to establish the right, not to deny human responsibility. The right being established does not cancel the responsibility.</p>"},
                {"src": "clarke", "attr": "Adam Clarke's Commentary", "html": "<p>The potter does not make the clay bad — the clay's qualities are its own. The potter works with what he finds. So God's exercise of sovereignty over human beings does not make him the author of their sin; he works with the moral character they have formed. The metaphor establishes sovereignty, not causation of sin.</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>The right asserted here is creatorial, not arbitrary — the authority of the one who made the material. The potter is not exercising a capricious preference; he is exercising the right that belongs to the maker over what he has made. The analogy concerns right, not whim.</p>"}
            ],
            "consensus": "mixed",
            "key_tension": MIXED_VESSELS
        },
        "22": {
            "synthesis": "<p>\"What if God, willing to show his wrath and to make his power known, bore with much longsuffering the vessels of wrath fitted for destruction?\" The sentence is grammatically incomplete in Greek — Paul leaves the apodosis unstated, letting the implied answer stand on its own. Calvin: this is the second answer to the objector — divine justice shines forth in the perdition of the reprobate no less than in the salvation of the elect. Ellicott notes the key participle θέλων (willing): RWP takes it as concessive — \"although willing,\" not causal — meaning God endured these vessels with much longsuffering even while they were ripening for destruction. This \"much longsuffering\" is the central detail that Wesley and Clarke seize on: God bore patiently with Pharaoh through plague after plague, giving repeated opportunity for repentance. Barnes identifies the phrase \"fitted for destruction\" (κατηρτισμένα εἰς ἀπώλειαν) as in the perfect passive — they had been fitted, stood as fitted — but does not specify by whom, leaving open the question of divine or human agency. Wesley and Clarke: they fitted themselves.</p>",
            "voices": [
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>Willing (<em>θέλων</em>). Concessive use of the participle — \"although willing,\" not causal, \"because willing.\" This is shown by \"with much longsuffering\" (<em>ἐν πολλῇ μακροθυμίᾳ</em>). God endured the vessels of wrath with patience even while willing to show his power through them. The longsuffering softens the sovereignty.</p>"},
                {"src": "wesley", "attr": "John Wesley's Notes", "html": "<p>Although willing to show his wrath — which necessarily presupposes sin. Yet endured with much longsuffering — as he did Pharaoh through plague after plague, giving repeated opportunity for repentance. The vessels of wrath are those who had made themselves such by their own persistent obstinacy.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>\"Fitted for destruction\" (<em>κατηρτισμένα εἰς ἀπώλειαν</em>) — perfect passive, indicating a state of readiness: they stood fitted. Paul does not specify the agent of fitting. The passive leaves open whether God or their own sin produced the state. Wesley and Clarke read their own sin as the agent; Calvin reads God's sovereign decree.</p>"}
            ],
            "consensus": "mixed",
            "key_tension": MIXED_VESSELS
        },
        "23": {
            "synthesis": "<p>The counterpart: the vessels of mercy prepared beforehand for glory. Where the vessels of wrath were described as \"fitted\" (passive perfect), the vessels of mercy are explicitly said to have been \"prepared beforehand\" (προητοίμασεν) by God — a more active and definite verb. Calvin uses this asymmetry to argue the difference in God's relationship to wrath and mercy: mercy is positively prepared by God's foreordination; the fitting of the vessels of wrath comes through their own sin, which God permits rather than causes. Ellicott observes the contrast between the two passives and the active verb here: the prepared-beforehand of the mercy vessels is God's direct act; the fitted-for-destruction of the wrath vessels is more ambiguous. Barnes notes that προητοίμασεν (prepared beforehand, aorist active) places the initiative firmly with God: these vessels were prepared in God's purpose before they appeared in history. Wesley reads this in terms of God's foreknowledge-based election — those who would believe were prepared beforehand for the glory that awaited their faith.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>The asymmetry is meaningful: the vessels of wrath are \"fitted\" (passive, agent unspecified); the vessels of mercy are \"prepared beforehand\" by God (active verb, God the agent). Calvin reads this as deliberate — God's positive preparation of mercy is direct; the fitting for wrath comes through sin God permits rather than decrees.</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>The contrast between the two verbs is important: the passive perfect \"fitted\" of the wrath vessels is ambiguous as to agent; the active \"prepared beforehand\" of the mercy vessels is not. Here God is clearly the active agent. The grammar encodes a distinction in God's relationship to wrath and to mercy.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>\"Prepared beforehand\" (<em>προητοίμασεν</em>) — aorist active — places the initiative firmly with God: these vessels were prepared in his purpose before they appeared in history. Wesley reads this in terms of foreknowledge-based election; Calvin reads it as unconditional predestination; both agree God is the active agent of the preparation.</p>"}
            ],
            "consensus": "mixed",
            "key_tension": MIXED_VESSELS
        },
        "24": {
            "synthesis": "<p>\"Even us whom he has called, not from the Jews only, but also from the Gentiles.\" The vessels of mercy are identified: the called-out community of believers, drawn from both Jews and Gentiles. This verse is the hinge between the election argument and the scriptural confirmation from the prophets. Calvin notes that Paul specifies \"us\" before proving from Scripture that this mixed calling was foreseen — so the OT quotations in vv. 25-29 are confirmations, not foundations, of the point already made. Barnes sees this as the practical conclusion of the entire predestination argument: God's sovereign purpose in election results in a community that crosses the ethnic boundary — Gentiles included not as an afterthought but as part of the pre-ordained plan. Wesley and Clarke are united here: the calling of Gentiles as God's people is the glorious outcome of the argument, and it was foretold. RWP: the aorist ἐκάλεσεν (he called) is the effective divine call, not merely an invitation — those called are those actually gathered into the community.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>Paul specifies \"us\" before proving from Scripture that this calling was foreseen — so the OT quotations in vv. 25-29 are confirmations, not foundations, of the point. He first identifies who the vessels of mercy are (us, called from Jews and Gentiles), then proves from the prophets that this was always God's plan.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>The practical conclusion of the predestination argument: God's sovereign purpose results in a community that crosses the ethnic boundary. Gentiles are included not as an afterthought but as part of the pre-ordained plan — as the quotations from Hosea and Isaiah in vv. 25-29 will confirm from Israel's own prophets.</p>"},
                {"src": "wesley", "attr": "John Wesley's Notes", "html": "<p>Even us whom he hath called — through the gospel. Not of the Jews only, but also of the Gentiles. The calling of Gentiles as God's people is the glorious outcome of the sovereignty argument. God's freedom to show mercy as he will turns out to result in a worldwide community, not a narrower one.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "25": {
            "synthesis": "<p>Paul quotes Hosea 2:23: \"I will call her 'my people' who was not my people, and her 'beloved' who was not beloved.\" In its original context, the oracle spoke of the restoration of the northern kingdom of Israel — Hosea's wife and children bore names signifying rejection (Lo-Ruhamah = not loved; Lo-Ammi = not my people), and God's promise was to reverse this judgment. RWP notes that Paul applies the principle stated for apostate Israel to the Gentiles: \"Those who had ceased to belong to the chosen people, and those who had never belonged to it, were to all intents and purposes in the same position\" (Ellicott). Calvin reads the application as typological: Hosea speaks of Israelites who had forfeited their standing and were restored — the principle applies to Gentiles who never had that standing and are now incorporated. Wesley reads the application as pointing directly to Israel's future restoration: \"This relates directly to the final restoration of the Jews.\" Barnes provides the exegetical justification for the dual application: the principle God announces in Hosea is general enough to cover both cases.</p>",
            "voices": [
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>The original prophecy in Hosea relates to the pardon of the apostate northern kingdom. It is here typically applied to the Gentiles: those who had ceased to belong to the chosen people and those who had never belonged to it were in the same position before God — equally needy of his sovereign grace to name them as his own.</p>"},
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>The application is typological: Hosea speaks of Israelites who had forfeited their covenant standing and were restored by pure grace. Paul applies the principle to Gentiles who never had that standing. The logic is: if God can restore those who forfeited, he can include those who never possessed. Grace is not bounded by prior covenant membership.</p>"},
                {"src": "wesley", "attr": "John Wesley's Notes", "html": "<p>\"Beloved — as a spouse. Who once was not beloved.\" Wesley notes: \"consequently, not unconditionally elected\" — the verse describes those formerly outside grace who become the objects of God's love. Wesley reads this as pointing ultimately to the final restoration of Israel (Hosea's original subject), with Gentile inclusion as the intermediate fulfillment.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "26": {
            "synthesis": "<p>A second Hosea quotation (1:10): \"And in the very place where it was said to them, 'You are not my people,' there they will be called 'sons of the living God.'\" The phrase \"sons of the living God\" (υἱοὶ θεοῦ ζῶντος) is the culmination: not merely \"my people\" but \"sons\" — filial relationship, not merely political belonging. Barnes notes the irony of place: the very location of rejection becomes the place of adoption — as though to emphasize that the reversal is total. Calvin connects the use of \"living God\" to the contrast between the God of Israel and the dead idols of the nations: the Gentiles, called away from gods that could not speak or act, are made sons of the one who is truly alive. Clarke reads both Hosea quotations together as establishing that God's purpose was always to extend the family of faith beyond ethnic Israel — the prophets bore witness to the Gentile calling centuries before Paul preached it. Wesley again notes the quotation's primary reference to Israel's restoration while acknowledging the secondary application to Gentiles.</p>",
            "voices": [
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>The irony of place: the very location of rejection becomes the place of adoption. Not merely \"my people\" but \"sons\" — filial relationship, the highest degree of belonging. Where the name \"not my people\" was spoken, there the name \"sons of the living God\" will be pronounced over them. The reversal is total and publicly declared.</p>"},
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>\"Sons of the living God\" — the use of \"living\" contrasts the God of Israel with the dead idols of the nations. The Gentiles, called away from gods that could not speak or act, are made sons of the one who truly lives and acts. The title marks both the dignity of the new relationship and the worthlessness of what was left behind.</p>"},
                {"src": "clarke", "attr": "Adam Clarke's Commentary", "html": "<p>Both Hosea quotations establish that God's purpose was always to extend the family of faith beyond ethnic Israel — the prophets bore witness to the Gentile calling centuries before Paul preached it. The fact that Paul quotes from Israel's own prophets is his strongest argument against Jewish exclusivism.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "27": {
            "synthesis": "<p>Isaiah cries concerning Israel (10:22-23): \"Though the number of the sons of Israel be as the sand of the sea, only a remnant will be saved.\" The Isaiah quotation introduces the other side of the argument: if Hosea showed Gentile inclusion, Isaiah shows Jewish limitation — even among Abraham's physical descendants, the majority are not saved. Barnes notes the starkness of the illustration: the sand of the sea was the very metaphor God used in his promise to Abraham (Genesis 22:17), and now the same language is turned: though they be as the sand, only a remnant. Calvin reads this as Paul's proof that mass Jewish unbelief does not falsify God's promise — the promise was never to the whole mass but to the remnant within it. Ellicott: the remnant doctrine, far from being a Pauline invention, was embedded in the heart of Israel's own prophetic tradition. RWP: the word κατάλειμμα (remnant) appears only here in the NT — the residue that remains after subtraction. Wesley finds in this both warning (most of ethnic Israel will not be saved) and comfort (some will — the faithful remnant).</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>Paul's proof that mass Jewish unbelief does not falsify God's promise: the promise was never to the whole mass but to the remnant within it. Isaiah's remnant doctrine, found in Israel's own Scripture, shows that God always worked through a faithful minority within the covenant people — the smaller, elected Israel within the larger, formal Israel.</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>The remnant doctrine is not Paul's invention — it is embedded in Israel's own prophetic tradition. Isaiah announced it in the darkest period of Assyrian threat. The continuity between Isaiah's remnant and the believing Jews of Paul's day is itself evidence that God's word to Israel has not failed.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>The starkness of the illustration: the sand of the sea was the very metaphor God used in his promise to Abraham (Genesis 22:17). Now the same language is turned: though they be as the sand, only a remnant. The promise made using the sand image is fulfilled through the remnant image — abundance of descendants, but salvation through the few.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "28": {
            "synthesis": "<p>\"For the Lord will carry out his sentence upon the earth fully and without delay\" — the Isaiah quotation continues (10:23). God's word is being executed decisively and quickly: the judgment that narrows Israel to a remnant is not a hesitant partial act but a complete, determined work. RWP notes the Greek: λόγον συντελῶν καὶ συντέμνων — \"finishing and cutting short,\" possibly a hendiadys for \"completing quickly.\" Calvin reads the urgency as double-edged: terrible for those who fall under the cutting short, but hopeful for those who are preserved as the remnant. Barnes explains ἐπὶ τῆς γῆς (upon the earth) as emphasizing that this judgment is real and visible — not merely spiritual but enacted in historical events. Clarke connects this to the Roman destruction of Jerusalem: God's word was carried out fully and with speed in the events of A.D. 70. Wesley notes the verse as confirmation that the mass of Israel's rejection of Christ was not a failure of God's plan but an execution of it — the plan had always included the trimming of the tree to a remnant.</p>",
            "voices": [
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>Finishing and cutting short (<em>λόγον συντελῶν καὶ συντέμνων</em>). The two participles together may form a hendiadys meaning \"completing quickly.\" God's word of judgment is not carried out hesitatingly or partially — it is executed fully, decisively, and without lingering.</p>"},
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>The urgency is double-edged: terrible for those who fall under the cutting short, but hopeful for those preserved as the remnant. God's decisive execution of his word means both that judgment is real and that the remnant is certain. The same speed that destroys the many preserves the few.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>\"Upon the earth\" (<em>ἐπὶ τῆς γῆς</em>) emphasizes that this judgment is real and visible — enacted in historical events. The sentence of God is not a theoretical verdict; it is carried out fully in the affairs of nations and peoples, as the whole history of Israel demonstrates.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "29": {
            "synthesis": "<p>A final Isaiah quotation (1:9): \"Unless the Lord of Sabaoth had left us offspring, we would have been like Sodom, and become like Gomorrah.\" The title \"Lord of Sabaoth\" (Lord of Hosts, Lord of armies) emphasizes the power of the one who preserves the remnant — it is no small thing to be preserved from the fate of Sodom. RWP notes that σπέρμα (seed, offspring) here means the remnant itself — the small surviving fraction. Calvin draws the contrast with stark simplicity: without the divine preservation of a remnant, Israel would have been as utterly and finally destroyed as Sodom — no name, no descendants, no hope. Barnes: the quotation is the climax of the OT evidence — Isaiah himself, in the darkest hour, acknowledged that Israel survived only by divine mercy and would otherwise have been indistinguishable from Sodom. Ellicott adds: the survival of even a seed within Israel confirms that God's word has not failed — the remnant is not a concession or a consolation prize but the fulfillment of the promise. Wesley: the Lord of Sabaoth preserved us — it was his power alone that prevented total destruction.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>Without the divine preservation of a remnant, Israel would have been as utterly and finally destroyed as Sodom — no name, no descendants, no future. The fact that even a seed remains is entirely owing to sovereign mercy, not to any quality in Israel that merited preservation.</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>The survival of a seed within Israel confirms that God's word has not failed — the remnant is not a concession or consolation prize, but the fulfillment of the promise that was always directed to the true Israel within Israel. Isaiah's own testimony vindicates Paul's argument from Israel's own prophets.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>The quotation is the climax of the OT evidence: Isaiah himself, in Israel's darkest hour, acknowledged that the nation survived only by divine mercy and would otherwise have been indistinguishable from Sodom. The remnant owes its existence entirely to the Lord of Hosts — the one mighty enough to preserve it.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "30": {
            "synthesis": "<p>\"What shall we say then?\" — Paul's summary conclusion from the entire argument. The paradox: Gentiles who did not pursue righteousness have attained it — the righteousness that is by faith. Israel, pursuing a law of righteousness, did not attain to the law. This is the great reversal that concludes the chapter. Calvin reads it as cutting off all Jewish grounds for complaint about God: the causes that account for their rejection are comprehensible at the human level — they sought righteousness by works rather than faith. But he is careful to qualify: this human-level explanation does not supersede the divine predestination established earlier — it is not the first cause but a secondary, comprehensible cause. Wesley: the Gentiles attained righteousness by accepting the gospel offer of Christ — not because they were seeking it, but because when it was offered, they received it by faith. Barnes: the Gentiles' success and Israel's failure are not mysterious — they are traceable to the method pursued. RWP captures the paradox with a single verb: the Gentiles \"seized\" (κατέλαβεν) what Israel ran toward and missed.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>Paul cuts off every occasion of murmuring against God by showing causes comprehensible at the human level: Israel was rejected for inverting the right order — they sought righteousness by works rather than by faith. But this human-level cause does not supersede the divine predestination established earlier; it is a secondary cause placed within the primary one.</p>"},
                {"src": "wesley", "attr": "John Wesley's Notes", "html": "<p>The Gentiles who followed not after righteousness — who a while ago had no knowledge of, no care about it — have attained to righteousness, even the righteousness which is by faith. They received the gospel offer when it came; Israel, running in the wrong direction, missed what was right in front of them.</p>"},
                {"src": "rwp", "attr": "Robertson's Word Pictures", "html": "<p>Attained (<em>κατέλαβεν</em>). Second aorist active of <em>καταλαμβάνω</em> — to grasp, to seize, to overtake (carrying out the figure in <em>διώκω</em>, to pursue). It was a curious paradox: those not running toward righteousness seized it; those running hard toward it fell short. The only difference was the method — faith vs. works.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "31": {
            "synthesis": "<p>\"But Israel, pursuing a law of righteousness, did not attain to the law.\" The statement is tightly paradoxical in the Greek: pursuing νόμον δικαιοσύνης (a law of righteousness), they did not arrive at νόμον (the law itself). Barnes reads this as saying Israel pursued righteousness as a matter of law-keeping, and even at that, failed to reach what the law demanded. Ellicott: \"pursuing\" (διώκων) is the same athletic metaphor as in Paul's self-description of ch. 3 — running hard in the race. The tragedy is not that they ran carelessly but that they ran toward the wrong goal. Calvin explains the contrast with the Gentiles: Israel had light and law; the Gentiles had neither. And yet Israel, with all its advantages, missed what the ignorant Gentiles found. Wesley notes that Israel's problem was not effort but method — they pursued with great energy a system that could not deliver what they were pursuing: righteousness before God. Clarke: they sought justification by the works of the Mosaic law, not understanding that the law itself pointed beyond itself to the Christ who alone could make them righteous.</p>",
            "voices": [
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>\"Pursuing\" (<em>διώκων</em>) — the athletic metaphor: running hard in the race. The tragedy is not carelessness but misdirection. Israel was running hard — with great energy and great advantages — but running toward the wrong goal. The law as an external system could not produce the righteousness it described.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>Israel pursued righteousness as a matter of law-keeping and even failed at that — the law's demands exceeded their performance. But the deeper failure was the method: they pursued as law what God intended to give as promise, and sought as wages what was available only as gift.</p>"},
                {"src": "clarke", "attr": "Adam Clarke's Commentary", "html": "<p>They sought justification by the works of the Mosaic law, not understanding that the law itself pointed beyond itself to Christ — who alone could make them righteous. The law was designed to lead them to faith; they made it a system of self-justification, and so missed both the law's purpose and the righteousness it promised.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "32": {
            "synthesis": "<p>\"Why? Because they did not pursue it by faith, but as if it were by works.\" The diagnosis of Israel's failure is stated baldly: the method was wrong. They pursued righteousness as though it could be obtained by law-works, when the only path to it was faith. RWP cites the parallel with the athletic imagery: they stumbled over the stumbling stone (v. 33) because they were looking at their feet (their works) rather than at the stone. Calvin is precise: faith lays hold of Christ, who is righteousness; works-pursuit bypasses Christ and seeks to establish its own righteousness before God. The contrast is not between active and passive, as though faith does nothing — but between the right object (Christ by faith) and the wrong method (works as self-justification). Barnes: Israel's reliance on works produced not merely failure but an obstinate rejection of the Christ who was the stone of stumbling — because accepting him would have required abandoning the righteousness they had been building. Wesley and Clarke are united: the error was not zeal but direction; not effort but foundation.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>Faith lays hold of Christ, who is righteousness; works-pursuit bypasses Christ and seeks to establish its own righteousness before God. The contrast is not between active and passive — faith is not passive — but between the right object (Christ by faith) and the wrong method (works as ground of self-justification).</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>Israel's reliance on works produced not merely failure but an obstinate rejection of Christ, who was the stone they stumbled over. Accepting him would have required abandoning the righteousness they had been building by works — and that price they were unwilling to pay. The method produced the stumble.</p>"},
                {"src": "wesley", "attr": "John Wesley's Notes", "html": "<p>Their error was not zeal but direction; not effort but foundation. They pursued with great earnestness — but on the ground of their own works, not on the foundation of faith in Christ. The same energy, directed toward faith, would have attained what effort alone could never reach.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        },
        "33": {
            "synthesis": "<p>Paul closes with a composite quotation from Isaiah 8:14 and 28:16: \"Behold, I am laying in Zion a stone of stumbling and a rock of offense, and whoever believes in him will not be put to shame.\" The stone is Christ — simultaneously the sure foundation for faith and the occasion of ruinous stumbling for unbelief. RWP notes that this same combination of Isaiah texts appears in 1 Peter 2:6-8, confirming it was a well-established testimonia (proof-text collection) in the early church. Calvin reads the closing affirmation — \"whoever believes will not be put to shame\" — as comfort for the godly: Christ is appointed for ruin to the unbelieving, but for life and resurrection to the godly. The same stone that trips one person supports another. Ellicott traces the original contexts: Isaiah 28:16 speaks of the foundation stone in Zion; Isaiah 8:14 speaks of God himself as a stone of stumbling to both houses of Israel. Barnes notes that the universal \"whoever believes\" (πᾶς ὁ πιστεύων) throws the door open to both Jew and Gentile — the conclusion that ch. 10 will develop.</p>",
            "voices": [
                {"src": "calvin", "attr": "Calvin's Commentaries", "html": "<p>Christ is appointed for ruin to the unbelieving, but for life and resurrection to the godly. The same stone that trips one person supports another — the difference lies not in the stone but in the person's posture toward it. Faith receives the foundation; unbelief strikes the stumbling block.</p>"},
                {"src": "ellicott", "attr": "Ellicott's Commentary", "html": "<p>A free combination of Isaiah 28:16 (\"a foundation stone... he that believeth shall not make haste\") and Isaiah 8:14 (\"a stone of stumbling... for both the houses of Israel\"). The first text establishes the stone as a sure foundation; the second establishes it as a stumbling block. Christ fulfills both simultaneously.</p>"},
                {"src": "barnes", "attr": "Barnes' Notes", "html": "<p>\"Whosoever believeth on him shall not be ashamed\" — the universal \"whosoever\" (<em>πᾶς ὁ πιστεύων</em>) throws the door open to Jew and Gentile alike. The chapter that opened with Paul's grief over Israel closes with the promise that faith — from any source — reaches the stone and finds it a foundation, not an obstacle.</p>"}
            ],
            "consensus": "affirm",
            "key_tension": None
        }
    }
}

def main():
    existing = load_synthesis('romans')
    merge_synthesis(existing, ROMANS)
    save_synthesis('romans', existing)
    print('Romans 9 synthesis complete.')

if __name__ == '__main__':
    main()
