"""
MKT Christ Commentary — Job chapters 12–14
Run: python3 scripts/zc-christ-job-12-14.py

Ch 12: Job's ironic hymn to God's sovereign reversals — every verse connects to the
    God of reversals revealed supremely in Christ: the righteous mocked (v4 → Matt 27),
    the deep things brought to light (v22 → Eph 3:9), sovereign power over creation
    and nations (v10 → Rev 1:18; v13 → Isa 9:6).
Ch 13: Job's demand to speak to God directly — v15 ("though he kills me, yet I will
    hope") as the OT peak of faith under trial; v24 anticipates the cry of abandonment
    (Ps 22:1 / Matt 27:46); v19 anticipates Rom 8:33.
Ch 14: The resurrection question — v1 ("born of woman," Gal 4:4); vv7-9 the
    tree-resurrection type (Isa 11:1; 1 Cor 15:20); v14 ("if a man dies, will he live
    again?") answered definitively by Christ's resurrection; vv13-15 the longing for
    post-Sheol existence that Christ fulfills.
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

CHRIST = {
  "12": {
    "1": "<p>Job&rsquo;s formula &mdash; &ldquo;Then Job answered&rdquo; &mdash; marks the human sufferer who speaks back to those who claim to speak for God. Christ is the ultimate answerer: where Job could only respond to human misrepresentations of God, Christ is the Word himself who answers definitively (John 1:1&ndash;14). The entire exchange between Job and his friends &mdash; which Christ resolves by providing the true mediator Job longed for &mdash; is set in motion by this recurring formula of human speech.</p>",
    "2": "<p>Job&rsquo;s bitter sarcasm toward the friends&rsquo; monopoly on wisdom &mdash; &ldquo;wisdom itself will die when you do&rdquo; &mdash; exposes the pretension of human wisdom clubs. Christ is the true end of that pretension: &ldquo;the wisdom of God&rdquo; in person (1 Cor 1:24), the one &ldquo;in whom are hidden all the treasures of wisdom and knowledge&rdquo; (Col 2:3). Human wisdom traditions do die with their bearers; Christ&rsquo;s wisdom is eternal and accessible to all who ask in faith (Jas 1:5).</p>",
    "3": "<p>Job&rsquo;s assertion &mdash; &ldquo;I am not less than you&rdquo; &mdash; defends his standing as a thinking, reasoning person before the friends who presume superiority. Christ &ldquo;did not count equality with God a thing to be grasped&rdquo; (Phil 2:6) yet chose to stand in solidarity with those whom human wisdom systems regard as lesser &mdash; the poor, the sick, the suffering. His incarnation is the supreme act of taking the place of those who have been condescended to.</p>",
    "4": "<p>A shadow: &ldquo;I am a laughingstock to my friends &mdash; I who called to God and he answered me &mdash; the just and blameless man is a laughingstock.&rdquo; Job&rsquo;s description of the righteous sufferer mocked by those around him is a structural anticipation of the passion narrative. The &ldquo;just and blameless&rdquo; one who called to God and received answer became, in his suffering, a target of derision &mdash; precisely the scene at Golgotha (Matt 27:39&ndash;44: &ldquo;those who passed by hurled insults at him... those crucified with him also heaped insults on him&rdquo;). Ps 22:6&ndash;8 maps the same pattern onto the Servant who trusted and called.</p>",
    "5": "<p>The comfortable person who despises the afflicted and &ldquo;stands ready to condemn those whose feet slip&rdquo; anticipates the world&rsquo;s response to the cross: &ldquo;the message of the cross is foolishness to those who are perishing&rdquo; (1 Cor 1:18). The lamp of the afflicted is despised from a place of comfortable security &mdash; precisely the security that the cross exposes as illusory. Christ identified with the afflicted (Matt 25:35&ndash;40: &ldquo;as you did it to one of the least of these my brothers, you did it to me&rdquo;), so that despising the afflicted is despising him.</p>",
    "6": "<p>Job&rsquo;s observation that robbers are undisturbed while the righteous suffer anticipates the scene at Golgotha: the robbers/thieves crucified alongside the sinless Jesus (Luke 23:32&ndash;33; Matt 27:38). The paradox that &ldquo;God himself puts things into their hand&rdquo; &mdash; that even wicked prosperity is within divine permission &mdash; is the theology of the passion: God&rsquo;s &ldquo;deliberate plan and foreknowledge&rdquo; (Acts 2:23) used the wicked hands of Pilate, Judas, and the crowd to accomplish the world&rsquo;s redemption.</p>",
    "7": "<p>The animals and birds as teachers of divine truth anticipate Paul&rsquo;s argument in Rom 1:20: &ldquo;since the creation of the world God&rsquo;s invisible qualities &mdash; his eternal power and divine nature &mdash; have been clearly seen, being understood from what has been made.&rdquo; Christ himself drew on animal and natural observation in his parables (the birds of the air, Matt 6:26; the lilies, Matt 6:28&ndash;30) as teachers of God&rsquo;s care. What creation teaches in natural revelation, Christ embodies and clarifies.</p>",
    "8": "<p>The earth itself teaches divine truth; the fish of the sea declare it. Christ&rsquo;s dominion over creation &mdash; demonstrated in the calming of the storm (Matt 8:26&ndash;27: &ldquo;even the winds and the waves obey him&rdquo;), the miraculous catch of fish (Luke 5:4&ndash;7; John 21:6), and walking on water (Matt 14:25&ndash;27) &mdash; reveals him as the one about whom earth and sea testify. The creation that Job calls as witness against the friends is the creation that Christ rules and will restore (Rev 21:1).</p>",
    "9": "<p>A revelation of the name: &ldquo;who among all these does not know that the <strong>hand of the LORD</strong> has done this?&rdquo; This verse contains the only occurrence of the divine name YHWH in Job&rsquo;s recorded speeches (outside the prologue), suggesting the intensity of Job&rsquo;s recognition. The &ldquo;hand of the LORD&rdquo; most fully revealed in the NT is the hand that was pierced (John 20:25,27) &mdash; the hand of the LORD seen on the cross and confirmed in the resurrection. Isa 53:1 asks the same question: &ldquo;to whom has the arm of the LORD been revealed?&rdquo;</p>",
    "10": "<p>A direct revelation: &ldquo;in his hand is the life of every living creature and the breath of all human flesh.&rdquo; Christ is the one in whose hand all life is held &mdash; explicitly identified as the risen Lord who holds the keys of death and Hades (Rev 1:18: &ldquo;I hold the keys of death and Hades&rdquo;). John 1:4 identifies the same reality: &ldquo;in him was life, and that life was the light of all mankind.&rdquo; The cosmic scope of Job&rsquo;s affirmation &mdash; every living creature, all human flesh &mdash; is the scope of Christ&rsquo;s lordship (Col 1:17: &ldquo;in him all things hold together&rdquo;).</p>",
    "11": "<p>The ear that tests words as the tongue tastes food is the discernment faculty that Job calls his friends to use. Christ&rsquo;s words require the same active testing &mdash; and pass it definitively. The crowd recognized a qualitative difference: &ldquo;he taught as one who had authority, not as their teachers of the law&rdquo; (Matt 7:29). John 6:68 (Peter&rsquo;s response to Christ&rsquo;s hard teaching): &ldquo;Lord, to whom shall we go? You have the words of eternal life&rdquo; &mdash; the ultimate verdict of the palate that tests words.</p>",
    "12": "<p>The attribution of wisdom to the aged (&ldquo;wisdom belongs to the aged, and understanding comes with long years&rdquo;) points forward to Christ as the Ancient of Days (Dan 7:9,13) &mdash; the one who is both fully human-in-time and eternally pre-existent. The twelve-year-old Jesus astonished the teachers in the temple with his understanding (Luke 2:47), embodying in a single scene both human youth and divine wisdom that exceeds the aged.</p>",
    "13": "<p>A direct revelation: &ldquo;with God are wisdom and strength; he has counsel and understanding.&rdquo; The four divine attributes Job names here &mdash; wisdom (<em>ḥokhmāh</em>), strength (<em>gᵉbûrāh</em>), counsel (<em>ʿēṣāh</em>), and understanding (<em>tᵉbûnāh</em>) &mdash; are exactly the four attributes attributed to the promised Messiah in Isa 9:6: &ldquo;Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.&rdquo; Paul identifies Christ as the one &ldquo;in whom are hidden all the treasures of wisdom and knowledge&rdquo; (Col 2:3). Job names what Christ embodies.</p>",
    "14": "<p>The divine power to imprison without release and to tear down without rebuilding is answered in Christ by its precise inversion: he has the authority both to bind and to loose (Matt 16:19; 18:18), and what he opens no one can shut, what he shuts no one can open (Rev 3:7). More fundamentally, he tore down the dividing wall of hostility (Eph 2:14) and tore the temple curtain in two (Matt 27:51), making the formerly locked-off divine presence accessible to all.</p>",
    "15": "<p>Divine sovereignty over waters &mdash; withholding and releasing &mdash; points to Christ who stilled the storm (Matt 8:26) and walked on the sea (Matt 14:25). But the flood imagery also anticipates Christ&rsquo;s baptism (the waters of judgment that he entered voluntarily) and the cross where &ldquo;all your waves and breakers have swept over me&rdquo; (Ps 69:2; 42:7). He entered the waters of divine judgment on humanity&rsquo;s behalf so that the flood he endured would not drown us.</p>",
    "16": "<p>&ldquo;Those who deceive and those who are deceived both belong to him&rdquo; states divine sovereignty even over deception. The betrayal of Christ &mdash; the supreme human deception &mdash; was within divine sovereignty: &ldquo;handed over by God&rsquo;s deliberate plan and foreknowledge&rdquo; (Acts 2:23). Judas was the deceiver; the religious leaders were in some ways the deceived; yet both served, unknowingly, the plan of the God &ldquo;who works out everything in conformity with the purpose of his will&rdquo; (Eph 1:11).</p>",
    "17": "<p>He leads counselors away stripped of dignity and turns judges into fools &mdash; the divine reversal of human wisdom structures. Christ &ldquo;made foolish the wisdom of this world&rdquo; (1 Cor 1:20) precisely by being crucified &mdash; the act that the wise of his day judged to be the end of his movement. Paul&rsquo;s extended argument in 1 Cor 1:18&ndash;2:16 is a commentary on this verse: the cross is God&rsquo;s stripping of all human counsel.</p>",
    "18": "<p>He strips kings of their authority and &ldquo;wraps a servant&rsquo;s cloth around their loins&rdquo; &mdash; the great reversal that Christ enacted literally and spiritually. The King of kings (Rev 19:16) &ldquo;took off his outer clothing, and wrapped a towel around his waist&rdquo; and washed his disciples&rsquo; feet (John 13:4&ndash;5). Christ performed this clothing-reversal on himself voluntarily, as the preeminent example of the divine pattern Job describes: the greatest becomes the servant of all.</p>",
    "19": "<p>He leads priests away stripped and overturns those who seemed unassailable. Christ is the high priest who supersedes and renders obsolete the Levitical priesthood (Heb 7:12,18&ndash;19; 8:6&ndash;7). The &ldquo;unassailable&rdquo; priestly institution that condemned Jesus to death was simultaneously being stripped of its ultimate function: his death abolished the need for ongoing sacrifice (Heb 10:11&ndash;14: &ldquo;he offered for all time one sacrifice for sins and sat down&rdquo;).</p>",
    "20": "<p>He silences those who are trusted and strips judgment from the aged. Christ taught &ldquo;as one who had authority&rdquo; (Matt 7:29), and the wisdom establishment of his day was repeatedly silenced before him: &ldquo;no one could say a word in reply, and from that day on no one dared to ask him any more questions&rdquo; (Matt 22:46). The pattern Job describes &mdash; God stripping conventional wisdom authority &mdash; is the pattern the incarnate Son enacted in his ministry.</p>",
    "21": "<p>He pours contempt on princes and loosens the strength of the mighty. Mary&rsquo;s Magnificat (Luke 1:51&ndash;52) echoes this exactly: &ldquo;he has performed mighty deeds with his arm; he has scattered those who are proud in their inmost thoughts; he has brought down rulers from their thrones but has lifted up the humble.&rdquo; The incarnation itself is the supreme act of emptying princely status: Christ &ldquo;did not count equality with God a thing to be grasped, but emptied himself&rdquo; (Phil 2:6&ndash;7).</p>",
    "22": "<p>A direct revelation: &ldquo;he brings to light the deep things hidden in darkness and brings the shadow of death into the open.&rdquo; Paul uses nearly identical language for the gospel: God who reveals &ldquo;the mystery hidden for long ages past&rdquo; (Rom 16:25; Eph 3:9: &ldquo;the mystery hidden for ages in God... made plain through the church&rdquo;). Christ &ldquo;brought life and immortality to light through the gospel&rdquo; (2 Tim 1:10), turning the shadow of death into a threshold crossed and illumined.</p>",
    "23": "<p>He makes nations great then destroys them; he expands them then scatters them. Christ is identified as the ruler of the kings of the earth (Rev 1:5) and the one before whom all nations will be gathered for judgment (Matt 25:32). The pattern of divine sovereignty over nations that Job describes becomes, in the NT, the eschatological drama in which Christ is the appointed judge: &ldquo;the Father judges no one, but has entrusted all judgment to the Son&rdquo; (John 5:22).</p>",
    "24": "<p>He strips understanding from the leaders of the peoples and makes them wander in trackless wasteland. Paul quotes the divine disabling of human understanding from Isa 29:14 (&ldquo;I will destroy the wisdom of the wise&rdquo;, cited in 1 Cor 1:19) in his argument that Christ crucified overturns the wisdom of the world&rsquo;s leaders (1 Cor 2:8: &ldquo;none of the rulers of this age understood it, for if they had, they would not have crucified the Lord of glory&rdquo;). The leaders&rsquo; incomprehension is both a divine act and a precondition of the cross.</p>",
    "25": "<p>They grope in the dark without light, staggering like drunkards. Christ is the light who came precisely for those groping in darkness: &ldquo;the people walking in darkness have seen a great light&rdquo; (Isa 9:2; Matt 4:16); &ldquo;I am the light of the world; whoever follows me will never walk in darkness&rdquo; (John 8:12). The divine pattern Job describes &mdash; leaders disoriented, groping without light &mdash; is what Christ reverses in his mission: he came to give sight to the blind (Luke 4:18; John 9:39).</p>"
  },
  "13": {
    "1": "<p>Job&rsquo;s declaration that his own eye has seen and his ear has heard positions him as a direct witness &mdash; the testimonial posture required for legal credibility. Christ is the ultimate faithful witness: &ldquo;Jesus Christ, the faithful witness, the firstborn from the dead, the ruler of the kings of the earth&rdquo; (Rev 1:5). In John 3:11&ndash;12 he says &ldquo;we speak of what we know, and we testify to what we have seen.&rdquo; His witness is authoritative because he has seen what Job has only guessed at &mdash; the divine council, the Father&rsquo;s face, the purposes of creation.</p>",
    "2": "<p>&ldquo;What you know, I know as well &mdash; I am not less than you&rdquo; is Job&rsquo;s assertion of intellectual equality with his friends. Christ&rsquo;s knowledge exceeds all human knowing: &ldquo;you know all things&rdquo; (John 21:17); &ldquo;in him are hidden all the treasures of wisdom and knowledge&rdquo; (Col 2:3). Yet he entered human limitations in the incarnation (Mark 13:32: &ldquo;no one knows the day or the hour, not even the Son&rdquo;), experiencing human epistemological vulnerability in order to redeem human knowing from the inside.</p>",
    "3": "<p>&ldquo;I want to speak directly to the Almighty; I long to argue my case before God.&rdquo; Job&rsquo;s longing for direct access to the Almighty is precisely what Christ provides: &ldquo;I am the way and the truth and the life; no one comes to the Father except through me&rdquo; (John 14:6). The direct speech with God that Job agonizes over throughout the dialogues is made universally available through Christ&rsquo;s mediation (Eph 2:18: &ldquo;through him we both have access to the Father by one Spirit&rdquo;; Heb 4:16: &ldquo;let us then approach the throne of grace with confidence&rdquo;).</p>",
    "4": "<p>The friends as &ldquo;fabricators of lies&rdquo; and &ldquo;doctors who prescribe worthless remedies&rdquo; contrasts with the True Physician whom Christ is. Matt 9:12 (&ldquo;it is not the healthy who need a doctor, but the sick&rdquo;) identifies Christ&rsquo;s mission as precisely the healing that the friends could not provide. Where Job&rsquo;s friends offered theological diagnoses that missed the real condition, Christ comes to the actual wound: &ldquo;he heals the brokenhearted and binds up their wounds&rdquo; (Ps 147:3).</p>",
    "5": "<p>&ldquo;If only you would keep completely silent &mdash; that itself would be wisdom.&rdquo; Christ&rsquo;s silence before his accusers is the supreme instance of wisdom in silence: &ldquo;he was oppressed and afflicted, yet he did not open his mouth; he was led like a lamb to the slaughter, and as a sheep before its shearers is silent, so he did not open his mouth&rdquo; (Isa 53:7). Before Pilate (Matt 27:14: &ldquo;he gave him no answer, not even to a single charge&rdquo;) and before the high priest (Matt 26:63), Christ demonstrated that silence can be the most profound speech.</p>",
    "6": "<p>Job&rsquo;s call &mdash; &ldquo;hear my argument now, and listen carefully to the pleadings of my lips&rdquo; &mdash; anticipates Christ&rsquo;s advocacy on behalf of believers. 1 John 2:1: &ldquo;if anybody sins, we have an advocate (<em>paraklētos</em>) with the Father &mdash; Jesus Christ, the Righteous One.&rdquo; Job pleaded his own case; believers have an advocate who pleads their case in the divine court &mdash; and whose righteousness, not theirs, grounds the plea. The Advocate whose cause is just cannot be overruled.</p>",
    "7": "<p>&ldquo;Will you speak falsehood on God&rsquo;s behalf?&rdquo; Job exposes the theological problem of defending God through dishonest argument. Christ spoke only what the Father gave him: &ldquo;I do nothing on my own but speak just what the Father has taught me&rdquo; (John 8:28); &ldquo;the word you hear is not my own; it belongs to the Father who sent me&rdquo; (John 14:24). The Son is the embodiment of truth-speaking about God &mdash; the antithesis of the falsehood Job&rsquo;s friends commit by defending God with wrong theology.</p>",
    "8": "<p>&ldquo;Will you act as God&rsquo;s lawyer?&rdquo; The irony is that the friends&rsquo; defense of God was theologically false; Christ&rsquo;s advocacy on behalf of sinners before God is theologically perfect. He is both defendant (crucified for our sins) and advocate (interceding for us, Heb 7:25: &ldquo;he always lives to intercede for them&rdquo;). In the divine court, the only valid advocate is the one who has satisfied the divine justice that the charges require.</p>",
    "9": "<p>&ldquo;Will it go well when he examines you?&rdquo; The divine examination that the friends should fear is the same examination before which Christ&rsquo;s work declares believers righteous. Rev 2:23: &ldquo;I am he who searches hearts and minds, and I will repay each of you according to your deeds.&rdquo; Because Christ has borne the judgment of divine examination in our place (2 Cor 5:21), those who are in him need not fear the examination &mdash; not because the examination is waived but because his righteousness covers them.</p>",
    "10": "<p>&ldquo;He will certainly call you out if you show favoritism in secret.&rdquo; God&rsquo;s impartiality in judgment applies universally; Christ&rsquo;s judgment will be equally impartial: &ldquo;the Father judges no one, but has entrusted all judgment to the Son&rdquo; (John 5:22); &ldquo;he commanded us to preach to the people and to testify that he is the one whom God appointed as judge of the living and the dead&rdquo; (Acts 10:42). The favoritism the friends show &mdash; condemning Job to defend their theological system &mdash; will itself be judged.</p>",
    "11": "<p>&ldquo;Will not his majesty strike terror into you, and his dread overwhelm you?&rdquo; The divine majesty (<em>śēʾēt</em>) is the theophanic attribute that overwhelms human capacity. At the transfiguration, the disciples &ldquo;fell facedown to the ground, terrified&rdquo; (Matt 17:6) &mdash; the glimpse of Christ&rsquo;s uncloaked divine majesty. At his resurrection appearance, the guards &ldquo;shook and became like dead men&rdquo; (Matt 28:4). John in Rev 1:17 &ldquo;fell at his feet as though dead&rdquo; when he saw the risen Christ. The majesty that Job invokes is the majesty that Christ bears in his glorified state.</p>",
    "12": "<p>&ldquo;Your wise maxims are proverbs of ash; your arguments are arguments of clay.&rdquo; Paul&rsquo;s entire argument in 1 Cor 1:18&ndash;2:16 develops the same verdict on human wisdom when confronted with the cross: &ldquo;I will destroy the wisdom of the wise; the intelligence of the intelligent I will frustrate&rdquo; (1 Cor 1:19, quoting Isa 29:14). Clay and ash are both materials that crumble; human theological systems built on the clay of conventional retributionism crumble before the revelation of the cross.</p>",
    "13": "<p>&ldquo;Be silent and leave me alone so I can speak; let whatever comes, come.&rdquo; Job&rsquo;s desperate courage to speak to God regardless of consequences anticipates Christ&rsquo;s Gethsemane prayer: &ldquo;Father, if you are willing, take this cup from me; yet not my will, but yours be done&rdquo; (Luke 22:42). Both speak in the face of potential divine wrath; both express anguish; both ultimately subordinate themselves to the divine purpose. The difference is that Christ&rsquo;s surrender accomplishes the redemption that Job could only cry out for.</p>",
    "14": "<p>&ldquo;Why do I risk my flesh in my teeth and put my life in my own hands?&rdquo; is Job&rsquo;s expression of reckless vulnerability in speaking boldly to God. Christ&rsquo;s voluntary self-giving is the supreme answer: &ldquo;no one takes my life from me, but I lay it down of my own accord&rdquo; (John 10:18). Where Job risks his life in speaking, Christ gives his life deliberately &mdash; the proactive self-offering that makes Job&rsquo;s risk-taking possible for all who approach God through him.</p>",
    "15": "<p>A direct revelation: &ldquo;though he kills me, yet I will hope in him.&rdquo; This is arguably the single greatest statement of faith in the Old Testament &mdash; absolute trust in God that persists even through the possibility of divine killing. It anticipates the NT theology of perseverance: Christ himself &ldquo;for the joy set before him endured the cross, scorning its shame&rdquo; (Heb 12:2), trusting the Father through death. And his followers are called to the same radical faith: &ldquo;whoever loses their life for my sake will find it&rdquo; (Matt 16:25). Job&rsquo;s statement is the Old Testament&rsquo;s clearest anticipation of resurrection-hope faith.</p>",
    "16": "<p>&ldquo;This itself will be my deliverance &mdash; no godless man can stand in his presence.&rdquo; Job&rsquo;s boldness to approach God &mdash; the very thing that will vindicate him &mdash; is what Christ makes universally possible. Rom 5:2: &ldquo;through him we have gained access by faith into this grace in which we now stand.&rdquo; Eph 2:18: &ldquo;through him we both have access to the Father by one Spirit.&rdquo; The godless cannot stand before God; but those clothed in Christ&rsquo;s righteousness can approach with confidence (Heb 10:19&ndash;22).</p>",
    "17": "<p>&ldquo;Listen carefully to my words; let my declaration reach your ears.&rdquo; The words that Job pleads for a hearing demand the same attention Christ requires: &ldquo;whoever hears my word and believes him who sent me has eternal life&rdquo; (John 5:24). Christ&rsquo;s words are &ldquo;spirit and life&rdquo; (John 6:63); they will &ldquo;not pass away&rdquo; when heaven and earth do (Matt 24:35). The urgency Job feels about his declaration being heard is the urgency of the gospel itself.</p>",
    "18": "<p>&ldquo;I know that I will be vindicated.&rdquo; Job&rsquo;s confident hope of divine vindication is realized in Christ&rsquo;s resurrection &mdash; God&rsquo;s definitive vindication of the righteous sufferer. 1 Tim 3:16: &ldquo;vindicated by the Spirit&rdquo; &mdash; the resurrection is the Spirit&rsquo;s declaration that Christ was righteous and that his claims were true. And Christ&rsquo;s vindication guarantees the vindication of all who are in him: &ldquo;therefore, there is now no condemnation for those who are in Christ Jesus&rdquo; (Rom 8:1).</p>",
    "19": "<p>A direct revelation: &ldquo;who is there who will bring a charge against me?&rdquo; Paul echoes this exactly in Rom 8:33&ndash;34: &ldquo;who will bring any charge against those whom God has chosen? It is God who justifies. Who then is the one who condemns? No one &mdash; Christ Jesus who died &mdash; more than that, who was raised to life &mdash; is at the right hand of God and is also interceding for us.&rdquo; Job&rsquo;s rhetorical challenge to any accuser is answered definitively in Christ: the only one with standing to condemn is the one who intercedes instead.</p>",
    "20": "<p>Job&rsquo;s petition for God to withdraw his two actions &mdash; terrifying hand and overwhelming dread &mdash; is the mirror image of Christ&rsquo;s Gethsemane prayer (Luke 22:42: &ldquo;Father, if you are willing, take this cup from me&rdquo;). But where Job petitions for removal before his ordeal, Christ accepts the cup. The &ldquo;two things&rdquo; that Job cannot bear &mdash; God&rsquo;s hand and God&rsquo;s terror &mdash; are precisely what Christ bore on the cross, so that those in him would not need to bear them (Isa 53:10: &ldquo;yet it was the LORD&rsquo;s will to crush him&rdquo;).</p>",
    "21": "<p>&ldquo;Take your hand off me, and do not let terror of you overwhelm me.&rdquo; Christ&rsquo;s experience of divine abandonment on the cross (&ldquo;My God, my God, why have you forsaken me?&rdquo; Matt 27:46) is the opposite of Job&rsquo;s request &mdash; the hand of God was not removed; it was pressed down fully. He bore the weight of divine wrath that Job feared, so that for those in him the terror of divine judgment is replaced by &ldquo;perfect love that drives out fear&rdquo; (1 John 4:18).</p>",
    "22": "<p>&ldquo;Then call, and I will answer; or let me speak first, and you answer me.&rdquo; The two-way responsiveness Job longs for &mdash; God calling and human answering; human speaking and God responding &mdash; is fully realized in the prayer relationship Christ opens. &ldquo;Ask and it will be given to you; seek and you will find; knock and the door will be opened&rdquo; (Matt 7:7). The Servant in Isa 50:4&ndash;5 models this: &ldquo;he wakens me morning by morning, wakens my ear to listen... I have not been rebellious; I have not drawn back.&rdquo;</p>",
    "23": "<p>&ldquo;How many are my iniquities and sins? Tell me my transgression and my sin.&rdquo; Job&rsquo;s challenge is that there is no proportionate sin to justify his suffering &mdash; a claim God confirms in 42:7. Christ, who had no iniquity or sin (Heb 4:15; 1 Pet 2:22), nonetheless &ldquo;bore our sins in his body on the tree&rdquo; (1 Pet 2:24). He became the answer to both questions simultaneously: he knew exactly how many our iniquities were &mdash; because he bore them. &ldquo;He made him who knew no sin to be sin for us&rdquo; (2 Cor 5:21).</p>",
    "24": "<p>A direct anticipation: &ldquo;why do you hide your face from me and treat me as your enemy?&rdquo; This is the same question at the heart of the cry of abandonment from the cross: &ldquo;My God, my God, why have you forsaken me?&rdquo; (Matt 27:46 / Ps 22:1). Christ did not merely quote Ps 22 as a theological statement; he experienced the reality Job feared. The hidden face of God that Job complains about, Jesus experienced in full at Calvary &mdash; the nadir of the divine-human relationship that his resurrection then reverses permanently.</p>",
    "25": "<p>&ldquo;Will you pursue a leaf tossed in the wind? Will you hunt down dry stubble?&rdquo; Job&rsquo;s protest at the disproportionate divine attention to his frailty is answered in the incarnation: God chose not merely to attend to the frail leaf but to become it. &ldquo;He was despised and rejected by mankind, a man of suffering and familiar with pain; like one from whom people hide their faces he was despised&rdquo; (Isa 53:3). The fragile, wind-tossed leaf is the one whose form Christ voluntarily took (Phil 2:7: &ldquo;taking the form of a servant, being born in the likeness of men&rdquo;).</p>",
    "26": "<p>&ldquo;You write bitter charges against me and saddle me with the sins of my youth.&rdquo; The charges written against a condemned person anticipate the titulus crucis: &ldquo;this is the King of the Jews&rdquo; (Luke 23:38) &mdash; the charge written over Christ&rsquo;s cross. But the deeper resonance is the &ldquo;record of debt that stood against us&rdquo; which Christ canceled by nailing it to the cross (Col 2:14). He was saddled not with his own sins of youth but with the accumulated transgressions of all humanity.</p>",
    "27": "<p>&ldquo;You put my feet in stocks, you keep watch over all my paths, you mark the very prints of my feet.&rdquo; The surveillance and restraint Job describes are the conditions of the condemned under divine judicial wrath. Christ entered precisely these conditions: arrested, bound (John 18:12), and executed under the gaze of the divine judgment he was bearing. Yet his feet were marked &mdash; the prints of the nails became the marks of identification and verification in his resurrection appearances (John 20:25,27; Luke 24:40).</p>",
    "28": "<p>&ldquo;And I waste away like something rotten, like a garment eaten through by moths.&rdquo; The wasting of the human body under sustained suffering is the condition of Isa 53:2&ndash;3: &ldquo;he had no beauty or majesty to attract us to him, nothing in his appearance that we should desire him; he was despised and rejected by mankind, a man of suffering.&rdquo; Christ bore the full degradation of human wasting, not preserved from it: &ldquo;by his wounds we are healed&rdquo; (Isa 53:5; 1 Pet 2:24).</p>"
  },
  "14": {
    "1": "<p>A direct revelation: &ldquo;man born of woman is short-lived and full of turmoil.&rdquo; Paul uses this exact phrase &mdash; &ldquo;born of woman&rdquo; (<em>genomenon ek gynaikos</em>) &mdash; for Christ&rsquo;s incarnation in Gal 4:4&ndash;5: &ldquo;God sent his Son, born of woman, born under the law, to redeem those under the law.&rdquo; Christ is the &ldquo;man born of woman&rdquo; who, being short-lived and full of turmoil in his humanity, redeems precisely the human condition Job describes &mdash; not by escaping it but by entering and bearing it to its depths.</p>",
    "2": "<p>Man comes up like a flower that wilts and passes like a shadow that does not endure &mdash; the poetic statement of human transience that Christ entered fully. Heb 2:14&ndash;15: &ldquo;since the children have flesh and blood, he too shared in their humanity so that by his death he might break the power of him who holds the power of death.&rdquo; Christ did not bypass the withering and the shadow-passing; he went through it &mdash; and by going through it he reversed the outcome, flowering again in resurrection (1 Cor 15:20).</p>",
    "3": "<p>&ldquo;Yet on such a creature do you fix your eyes, and bring him into court before you?&rdquo; Job&rsquo;s amazement that God fixes his eyes on frail humanity echoes Ps 8:4: &ldquo;what is man that you are mindful of him, the son of man that you care for him?&rdquo; Heb 2:6&ndash;9 applies Ps 8 to Christ, who &ldquo;for a little while was made lower than the angels&rdquo; specifically to identify with this fragile creature &mdash; but &ldquo;now crowned with glory and honor because he suffered death.&rdquo; God&rsquo;s fixed gaze on frail humanity finds its fullest expression in the incarnation.</p>",
    "4": "<p>&ldquo;Who can bring something pure from something impure? No one can.&rdquo; This impossibility statement is the theological problem that Christ&rsquo;s virgin birth and sinless humanity address. He was &ldquo;born of woman&rdquo; (v1; Gal 4:4) yet was the pure from the impure lineage: &ldquo;without sin&rdquo; (Heb 4:15; 1 Pet 2:22). The one born of sinful human stock who was yet without sin is the necessary condition of the incarnation&rsquo;s redemptive purpose &mdash; only the pure can make the impure pure (1 John 1:7).</p>",
    "5": "<p>&ldquo;Since his days are fixed, the number of his months determined by you, the limit set that he cannot cross.&rdquo; Christ came &ldquo;in the fullness of time&rdquo; (Gal 4:4) &mdash; the divinely fixed moment. The &ldquo;hour&rdquo; of Christ&rsquo;s death was specifically predetermined: &ldquo;no one could seize him, because his hour had not yet come&rdquo; (John 7:30; 8:20); &ldquo;now the Son of Man is glorified&rdquo; (John 13:31 when the hour arrives). The fixed number of his months was precisely three decades of earthly life before the appointed hour of his death.</p>",
    "6": "<p>&ldquo;Look away from him so he can rest, until he has completed his time like a hired worker.&rdquo; Christ is the one who calls the weary to rest: &ldquo;come to me, all you who are weary and burdened, and I will give you rest&rdquo; (Matt 11:28&ndash;30). He himself rested in the tomb on the Sabbath after completing the work of redemption &mdash; &ldquo;it is finished&rdquo; (John 19:30; Heb 4:10: &ldquo;anyone who enters God&rsquo;s rest also rests from their works, just as God did from his&rdquo;). The completion of the hired servant&rsquo;s time anticipates the completed work.</p>",
    "7": "<p>A type: &ldquo;there is hope for a tree: if it is cut down, it will sprout again, and its new growth will not stop.&rdquo; This tree-hope is the structural type underlying Isa 11:1: &ldquo;a shoot will come up from the stump of Jesse; from his roots a Branch will bear fruit.&rdquo; The Davidic dynasty was cut down in exile; Christ is the shoot from the stump. The cross appears to cut down the tree finally; the resurrection is the sprout from the cut stump. 1 Cor 15:37: &ldquo;what you sow does not come to life unless it dies&rdquo; &mdash; the grain of wheat must fall into the ground (John 12:24).</p>",
    "8": "<p>&ldquo;Though its root grows old in the earth and its stump dies in the soil.&rdquo; The dying of the root in the earth is the death and burial stage of the type: the Tree of Jesse apparently extinguished, the Davidic line apparently ended. The three days in the tomb correspond to the seed in the ground: &ldquo;unless a kernel of wheat falls to the ground and dies, it remains only a single seed; but if it dies, it produces many seeds&rdquo; (John 12:24). Death is not the end of the tree &mdash; it is the necessary precondition of its renewal.</p>",
    "9": "<p>A direct type: &ldquo;yet at the smell of water it will bud and put out branches like a new plant.&rdquo; The resurrection of the cut tree at the touch of water is the resurrection type that Job 14 offers the OT. The resurrection of Christ is the fulfillment: &ldquo;Christ has indeed been raised from the dead, the firstfruits of those who have fallen asleep&rdquo; (1 Cor 15:20). The &ldquo;new plant&rdquo; that sprouts from the old stump is the new creation that emerges from Christ&rsquo;s death &mdash; &ldquo;if anyone is in Christ, the new creation has come&rdquo; (2 Cor 5:17).</p>",
    "10": "<p>&ldquo;But man dies and lies helpless; he breathes his last &mdash; and where is he?&rdquo; This is the theological problem that the entire NT answers. Christ&rsquo;s resurrection is the definitive response to &ldquo;where is he?&rdquo; &mdash; the empty tomb is the answer: he is not here, he is risen (Luke 24:6). John 11:25: &ldquo;I am the resurrection and the life; the one who believes in me will live, even though they die.&rdquo; The &ldquo;where is he?&rdquo; of death becomes the &ldquo;he is here&rdquo; of the resurrection appearances (John 20:19&ndash;29).</p>",
    "11": "<p>As water vanishes from a lake and a river wastes away and dries up &mdash; so Job describes the irreversible disappearance of the dead. Christ reversed irreversibility: &ldquo;I am the resurrection and the life; whoever lives by believing in me will never die&rdquo; (John 11:26). The water that vanishes from the lake is the same element Christ uses to describe eternal life: &ldquo;a spring of water welling up to eternal life&rdquo; (John 4:14) &mdash; the water that does not vanish but rises eternally.</p>",
    "12": "<p>&ldquo;So man lies down and does not rise; until the heavens are no more, they will not wake or be roused from their sleep.&rdquo; Job&rsquo;s &ldquo;until the heavens are no more&rdquo; is the eschatological limit: the moment when the heavens pass away. Rev 21:1: &ldquo;I saw a new heaven and a new earth, for the first heaven and the first earth had passed away.&rdquo; Christ is the one who brings this &ldquo;until&rdquo; to pass and raises the dead in connection with it (1 Thess 4:16: &ldquo;the dead in Christ will rise first&rdquo;; 1 Cor 15:23&ndash;26).</p>",
    "13": "<p>&ldquo;O that you would hide me in Sheol until your anger passes, set a fixed time for me, and then remember me.&rdquo; Job&rsquo;s longing to be hidden in Sheol and then remembered is the deepest OT prayer for post-death divine remembrance. Christ entered Sheol &mdash; &ldquo;you will not abandon me to the realm of the dead&rdquo; (Acts 2:27, quoting Ps 16:10); &ldquo;he was put to death in the body but made alive in the Spirit&rdquo; (1 Pet 3:18). He was remembered by the Father and raised &mdash; the enacted answer to Job&rsquo;s desperate wish.</p>",
    "14": "<p>A direct revelation: &ldquo;if a man dies, will he live again? Through all my days of hard service I will wait until my release comes.&rdquo; This is the central question of the book of Job and of all human existence. Christ&rsquo;s resurrection is the definitive answer. 1 Cor 15:12&ndash;22: &ldquo;if Christ has not been raised, your faith is futile&rdquo; &mdash; and since Christ has been raised, the answer to Job&rsquo;s &ldquo;will he live again?&rdquo; is an unreserved yes. The &ldquo;release&rdquo; Job waits for is the resurrection release that Christ obtained first and now shares (Heb 2:14&ndash;15).</p>",
    "15": "<p>A direct revelation: &ldquo;you will call out to me, and I will answer; you will long for the work of your hands.&rdquo; The divine longing for the creature &mdash; &ldquo;you will long for the work of your hands&rdquo; &mdash; is one of the most tender statements of divine love in Job. It finds its ultimate expression in the resurrection: Jesus calling Mary&rsquo;s name (&ldquo;Mary!&rdquo; John 20:16) and her turning to him is the enacted fulfillment &mdash; the Creator calling, the creature answering. The resurrection of the dead is God longing for and reclaiming the work of his hands.</p>",
    "16": "<p>&ldquo;But now you count my every step and watch over my sin without fail.&rdquo; The divine surveillance that condemns is what Christ bore for us: &ldquo;the LORD has laid on him the iniquity of us all&rdquo; (Isa 53:6). His steps were counted, his path was watched &mdash; and declared perfectly righteous. For those in Christ, the divine surveillance no longer condemns because he was &ldquo;delivered over to death for our sins and was raised to life for our justification&rdquo; (Rom 4:25). The count of every step now yields acquittal, not condemnation.</p>",
    "17": "<p>&ldquo;My transgression is sealed in a bag; you have stitched up my guilt.&rdquo; The sin sealed in a bag is the image of the permanent record held against the accused. Christ unsealed and emptied that bag: &ldquo;he forgave us all our sins, having canceled the charge of our legal indebtedness, which stood against us and condemned us; he has taken it away, nailing it to the cross&rdquo; (Col 2:13&ndash;14). The bag that was sealed is now empty; the stitched guilt is now torn open and forgiven.</p>",
    "18": "<p>A mountain eroding comes to nothing; a rock dislodged from its place &mdash; all human stability eventually crumbles. Christ is the Rock that does not crumble: 1 Cor 10:4 (&ldquo;they drank from the spiritual rock that accompanied them, and that rock was Christ&rdquo;); Matt 16:18 (&ldquo;on this rock I will build my church, and the gates of Hades will not overcome it&rdquo;). The erosion that Job describes as characteristic of all earthly things is precisely what Christ does not undergo: &ldquo;he who is built on this rock will not fall&rdquo; (Matt 7:25).</p>",
    "19": "<p>&ldquo;Water wears down the stones; floods wash away the soil of the earth &mdash; and so you wash away the hope of man.&rdquo; Job&rsquo;s conclusion that all human hope is eroded by the waters of death and time is the verdict that Christ&rsquo;s resurrection overturns. He is &ldquo;the hope of glory&rdquo; (Col 1:27: &ldquo;Christ in you, the hope of glory&rdquo;). The hope of man is not washed away in Christ &mdash; rather, he provides an &ldquo;anchor for the soul, firm and secure&rdquo; (Heb 6:19&ndash;20) that no flood of suffering or death can erode.</p>",
    "20": "<p>&ldquo;You overpower him completely and he is gone; you alter his countenance and send him away.&rdquo; Death&rsquo;s overpowering is the condition Christ entered and reversed. He was overpowered by death (Mark 15:37: &ldquo;and with a loud cry, Jesus breathed his last&rdquo;); his countenance was altered beyond recognition (Isa 52:14: &ldquo;his appearance was so disfigured beyond that of any human being&rdquo;). But then: &ldquo;I am the Living One; I was dead, and now look, I am alive for ever and ever! And I hold the keys of death and Hades&rdquo; (Rev 1:18). He was overpowered and he overpowered death.</p>",
    "21": "<p>&ldquo;His sons rise to honor but he does not know it; they are brought low but he is not aware.&rdquo; Job describes the isolation of the dead from their descendants. Christ&rsquo;s resurrection broke this isolation: as the &ldquo;firstborn among many brothers&rdquo; (Rom 8:29) he lives and participates in the honor of his brothers and sisters who believe. Heb 2:11&ndash;12: &ldquo;he is not ashamed to call them brothers and sisters&rdquo; &mdash; the risen Christ is aware of and invested in the honor and lowliness of those who are his, unlike the dead in Sheol who know nothing.</p>",
    "22": "<p>&ldquo;He feels only the pain within him and mourns only over himself.&rdquo; The dead man&rsquo;s self-absorbed pain is the final picture of death&rsquo;s isolation &mdash; the ultimate loneliness. Christ&rsquo;s death was the radical opposite: even on the cross he turned outward (&ldquo;Father, forgive them,&rdquo; Luke 23:34; &ldquo;today you will be with me in paradise,&rdquo; Luke 23:43; caring for his mother, John 19:26&ndash;27). His resurrection ends the isolation of death and opens the community of the new creation. The self-mourning of Job 14 is the condition Christ entered; the self-giving of the cross is the condition he enacted; the community of the resurrection is the condition he opens.</p>"
  }
}

def main():
    c = load_comm('mkt-christ', 'job')
    merge_comm(c, CHRIST)
    save_comm('mkt-christ', 'job', c)
    total = sum(len(vs) for vs in CHRIST.values())
    print(f'job mkt-christ: {total} entries written (ch12-14)')

if __name__ == '__main__':
    main()
