"""
MKT Christ Commentary — 1 Samuel chapters 4–8
Run: python3 scripts/zc-christ-1samuel-4-8.py

Source data used:
- data/interlinear/1samuel.json
- data/translation/draft/mediating/1samuel.json

Key Christological decisions:
- The Ark narrative (chs 4-7) is read as shadow/type: the ark represents YHWH's dwelling
  presence, pointing to the Incarnation (John 1:14) and the indwelling Spirit (John 14:17);
  the departure and return of the Ark traces the same trajectory as the death and resurrection
- Dagon's prostration (5:3-4): shadow of Phil 2:9-11 — every knee bowing before YHWH
- "Who can stand before this holy God?" (6:20): the unanswered question resolved only in Christ
  as mediator (Heb 12:18-24)
- Samuel as mediator-prophet-priest (ch7) is the fullest pre-monarchic type of the Messiah's
  threefold office
- The rejection of YHWH's kingship (ch8) is the culminating covenant failure that requires the
  eschatological King; Jesus's proclamation "the kingdom of God has come near" addresses this
  specific deficit
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

SAMUEL1 = {
  "4": {
    "1": '<p>The Ark narrative begins here with Israel engaging the Philistines at Ebenezer — "stone of help" (the name anticipates 7:12). The theme of this arc is the withdrawal and return of YHWH\'s presence. The NT counterpart is the death and resurrection of Christ, in whom the dwelling of God among his people is both withdrawn and finally, definitively restored.</p>',
    "2": '<p>Israel\'s defeat establishes that the covenant people cannot overcome their enemies in their current state of apostasy — the Eli household\'s corruption (2:12-17) has hollowed out the priestly mediation. This inability to prevail prefigures the state of humanity apart from the atoning work of Christ; defeat before spiritual enemies is the default condition of covenant unfaithfulness.</p>',
    "3": '<p>The elders\' proposal — "Let us bring the ark of the covenant here that it may save us" — is sincere but mistaken. They treat the Ark as a talisman rather than as the dwelling of YHWH who responds to covenant faithfulness. The error is the same as any attempt to use the forms of religion (sacrament, prayer, temple) as magic without the underlying covenant relationship. The NT parallel: Jesus warns that "Lord, Lord" without obedience is insufficient (Matt 7:21-23).</p>',
    "4": '<p>The Ark is identified as "the ark of the covenant of YHWH of hosts, who is enthroned between the cherubim" — the fullest divine-presence title in 1 Samuel. The cherubim-throne connects to Eden (Gen 3:24), the Tabernacle (Exod 25:18-22), and ultimately to Revelation\'s throne-vision (Rev 4:6-8). Hophni and Phinehas accompanying it — the corrupt priests carrying the holy ark — foreshadows the way human sin operates within and around the things of God while those things retain their own holiness.</p>',
    "5": '<p>The great shout at the Ark\'s arrival — the ground shaking — is the response of faith anticipating YHWH\'s warrior intervention. The shout is premature and misplaced; the victory has not yet been won. It anticipates the messianic expectation that greeted Jesus\'s entry to Jerusalem (Luke 19:37-38: the shout of the crowd) — likewise premature in its assumption that triumphant liberation was immediately at hand.</p>',
    "6": '<p>The Philistines\' fear at hearing about the Ark — "a god has come into the camp" — mirrors the response of pagan nations throughout the OT and NT when divine power is present. Their fear is accurate in substance but misidentified in nature: this is not "gods" (plural) but YHWH. The same misidentification appears in Acts 14:11-12 (Paul and Barnabas taken for Zeus and Hermes) — the nations sense the divine but miscategorize it.</p>',
    "7": '<p>The Philistines cry "Woe to us!" (<em>ʾôy lānû</em>) — the cry of those facing divine judgment. The same exclamation governs prophetic woe-oracles (Isa 6:5; Jer 4:31). Their fear of YHWH is, paradoxically, more theologically attuned than Israel\'s presumption; the nations sometimes recognize the weight of divine holiness that the covenant people take for granted.</p>',
    "8": '<p>The Philistines recall the Exodus plagues as evidence of Israel\'s God\'s power. The Exodus is the paradigmatic act of divine rescue that the entire OT references when accounting for YHWH\'s power. Jesus is presented in the NT as the one who accomplishes a new and greater Exodus (Luke 9:31 — Moses and Elijah speak of Jesus\'s "departure" which he was about to accomplish at Jerusalem).</p>',
    "9": '<p>The Philistine officers call their troops to fight or become slaves — the fear of reversal (they have enslaved Israel, now Israel might enslave them). This theme of enslavement-reversal runs through the biblical narrative and reaches its climax in Christ\'s redemption from slavery to sin (Gal 4:4-7; Rom 8:15).</p>',
    "10": '<p>Israel is defeated and the people flee "each to his own tent/home" — the scattering of the covenant community under judgment. The same scattering language appears when Jesus is arrested: "each one scattered to his own home" (John 16:32, quoting Zech 13:7). The sheep scattered when the shepherd is struck — the Ark\'s capture is the OT type of the cross\'s scandal.</p>',
    "11": '<p>"The ark of God was captured" — the most catastrophic sentence in early Israelite history. God\'s dwelling among his people is taken into enemy hands; the throne of Israel\'s king is in enemy territory. The theological parallel to Christ\'s death is direct: the one in whom God dwelled fully (Col 1:19) was handed over to his enemies and placed under their authority. In both cases, what looks like the defeat of YHWH\'s purpose is the instrument of its fulfillment.</p>',
    "12": '<p>The messenger with torn garments and dust on his head is the conventional messenger of catastrophic defeat throughout ANE and OT literature (cf. 2 Sam 1:2). The torn garments represent mourning; the news he carries — Ark captured, priests dead — is the death of the covenant mediation system in its current form.</p>',
    "13": '<p>Eli\'s trembling anxiety over the Ark — not over his sons — is the one redeeming quality in his portrait: he understood what mattered. The theme of covenant figures whose heart is with YHWH even when their administration has failed points to the need for a priest whose entire office is uncorrupted — Hebrews\' "better covenant" (Heb 8:6) administered by a priest who "always lives to intercede" (Heb 7:25).</p>',
    "14": '<p>The outcry from the city — the communal mourning — is the response of a people whose identity has been stripped away. The Ark was not a piece of furniture but the visible center of YHWH\'s covenantal presence. Its loss is an existential crisis. This is the typological background to the disciples\' desolation after the crucifixion: "we had hoped that he was the one who would redeem Israel" (Luke 24:21).</p>',
    "15": '<p>Eli\'s blindness — physical and spiritual — marks the end of his capacity to judge. The high priest who cannot see embodies the failure of covenant leadership in this era. The contrast is the "author and perfecter of faith" (Heb 12:2) whose vision is total and whose judgment is true.</p>',
    "16": '<p>The messenger\'s report is delivered in stages — the delay before "the ark" is mentioned allows the narrative to register each blow separately. Eli\'s first question — "How did it go?" — reflects pastoral concern; the answer will kill him when it reaches the final item.</p>',
    "17": '<p>The complete disaster: army fled, great slaughter, both sons dead, Ark captured. The fourfold catastrophe echoes the fourfold judgment of Deuteronomy covenant curses. The covenant failure that began with Eli\'s failure to restrain his sons (2:29) has produced the full covenant curse. Every generation\'s corruption has consequences for the entire community.</p>',
    "18": '<p>Eli\'s death at the news of the Ark\'s capture — falling backward from his seat — ends the forty-year judgeship. His death at the loss of the Ark and his sons is a fitting close: his house was promised extinction (2:31-34), and the cause of it all — the capture of the Ark — is what finally kills him. The priestly dynasty that failed to guard the covenant ends here, making way for Samuel\'s prophetic ministry.</p>',
    "19": '<p>The wife of Phinehas, going into labor at the combined news of Ark-capture and her husband\'s death, gives birth in dying. The moment is one of extreme inversion: new life emerging in the context of total loss. The Christological resonance is with John 16:21 — the woman in labor whose sorrow becomes joy — and with the cross-to-resurrection pattern: birth through death.</p>',
    "20": '<p>The attending women try to comfort her — "you have given birth to a son" (the good news of new life) — but she "did not answer or take notice." Her grief for the Ark and the covenant has overwhelmed even the natural joy of motherhood. Her one-pointed grief for what belongs to YHWH makes her a tragic figure of covenant passion that the system she was part of could not sustain.</p>',
    "21": '<p><strong>Ichabod</strong> — "no glory" or "where is the glory?" (<em>ʾî kāḇôd</em>) — is the name that functions as a theological verdict on this moment. The departure of YHWH\'s glory (<em>kāḇôd</em>) from Israel reverses the Sinai and Tabernacle narrative where YHWH\'s glory came to dwell among the people. The trajectory of the glory\'s departure (here, ch4), absence (chs 5-7), and eventual restoration is the template for the Incarnation: John 1:14 uses the exact same vocabulary: "the Word tabernacled among us, and we saw his glory (<em>doxa</em>)." The glory that departed at Ichabod returns in Christ.</p>',
    "22": '<p>The repetition of "the glory has departed from Israel" closes the chapter with double emphasis. The theological weight is carried forward to Ezekiel (Ezek 10-11, the glory departing from the temple before Babylon) and reversed definitively in Revelation 21:3 — "the dwelling of God is with humans." The Ichabod-to-Revelation trajectory is one of the deepest structural arcs of biblical theology.</p>'
  },
  "5": {
    "1": '<p>The Ark\'s journey to Philistia — from Ebenezer to Ashdod — traces the captivity of YHWH\'s presence among the nations. The narrative parallels the exile tradition (Israel and YHWH\'s instruments going into enemy territory) and points forward to Christ\'s own journey into the enemy\'s domain: "he descended into the lower regions of the earth" (Eph 4:9); and the harrowing of hell tradition, where Christ\'s presence penetrates even death\'s territory.</p>',
    "2": '<p>Dagon\'s temple in Ashdod — the Philistines place the Ark "beside Dagon" as a trophy of their god\'s victory. The presumption is that YHWH is just another defeated deity. The theme of YHWH\'s apparent defeat being the mechanism of his victory runs from the Ark narrative through the cross: what the powers of this age regarded as their victory (1 Cor 2:8) was in fact YHWH\'s definitive act.</p>',
    "3": '<p>Dagon prostrates himself before the Ark — falls on his face (<em>nāpal ʿal pānāyw</em>). The first time: the idol is set back up. The involuntary prostration of the false god before YHWH\'s Ark anticipates Philippians 2:9-11 — "at the name of Jesus every knee will bow, in heaven and on earth and under the earth." The nations\' gods cannot stand before the living God even when they appear to hold him captive.</p>',
    "4": '<p>The second fall of Dagon — this time the head and hands cut off, lying on the threshold. The detail is theological: head (authority/sovereignty) and hands (power/action) removed, only the torso left. The destruction of Dagon\'s sovereignty and power before YHWH\'s Ark enacts what Colossians 2:15 says Christ accomplished: "having disarmed the rulers and authorities, he made a public spectacle of them, triumphing over them in the cross."</p>',
    "5": '<p>The continuing taboo at Dagon\'s threshold is a monument to YHWH\'s victory preserved in Philistine religious practice — the enemy community unwittingly maintaining a memorial of their god\'s defeat. The theme: even where YHWH appears to have been captured, evidence of his supremacy remains embedded in the surrounding culture.</p>',
    "6": '<p>"The hand of the LORD was heavy against the people of Ashdod" — <em>yad YHWH</em> (hand of YHWH), the same divine-warrior formula as the Exodus plagues. The judgment on the nations that hold YHWH\'s presence captive is a theme that runs through the prophets (Isa 10, 46; Jer 50-51) and reaches its climax in Revelation\'s plagues on Babylon — the great power that holds God\'s people in bondage.</p>',
    "7": '<p>"The ark of the God of Israel must not stay with us" — the nations cannot hold YHWH captive. The Philistines\' recognition that YHWH\'s presence is intolerable for them parallels the Gerasene demoniac\'s response to Jesus: "I beg you, do not torment me" (Luke 8:28). The presence of the holy is unbearable for those in rebellion against God.</p>',
    "8": '<p>The Philistine lords consult about what to do with the Ark — passing it from Ashdod to Gath. Each city suffers the same judgment. YHWH\'s presence cannot be localized, quarantined, or managed by human administration; the attempt to "solve the problem" by moving it simply spreads the judgment. The pattern anticipates attempts in every age to contain or relativize Christ\'s claims.</p>',
    "9": '<p>Gath struck as well — "a very great panic" (<em>məhûmāh gədôlāh məʾōd</em>). The same vocabulary governs Sinai-type encounters with the divine (Exod 14:24). YHWH\'s presence among the nations is disruptive wherever it goes because it confronts the disordered order of human society with divine holiness.</p>',
    "10": '<p>The Ark\'s arrival at Ekron generates immediate terror: "They have brought the ark of the God of Israel to kill us!" The nations see only threat; they cannot perceive the gift that the presence of God could be for those who receive it rightly. This is the pattern of Revelation 6:15-17 — the kings and rulers of the earth fleeing from the Lamb\'s wrath — and contrasted with the covenant people who receive the Lamb as Shepherd (Rev 7:17).</p>',
    "11": '<p>The lords of the Philistines gather again — "send away the ark of the God of Israel, let it return to its own place." The nations\' desire to expel divine presence rather than receive it recurs throughout the NT: the Gerasenes ask Jesus to leave their territory (Matt 8:34); the religious leadership demands his execution. The nations consistently prefer life without the disruption of holiness.</p>',
    "12": '<p>"The cry of the city went up to heaven" — the lament of those suffering under divine judgment. The same formula governs the cry of the oppressed throughout the OT (Exod 2:23 — Israel\'s cry under Egypt). The Philistines now experience what their predecessors in Egypt experienced. The pattern of oppressor-becoming-oppressed under divine judgment runs from Egypt to Babylon to Rome and beyond.</p>'
  },
  "6": {
    "1": '<p>Seven months in Philistia — the Ark in the domain of the enemy for a complete period. The number seven signals completeness; the exile of YHWH\'s presence is bounded and purposeful. The parallel to Christ\'s three days in the tomb — a bounded, complete period of apparent defeat before return — makes this a shadow of the resurrection pattern.</p>',
    "2": '<p>The Philistines\' priests and diviners are consulted about how to return the Ark — the nations\' religious leaders serving as inadvertent mediators of YHWH\'s return. The involvement of pagan religious officials in preparing the way for YHWH\'s presence echoes the use of Gentile actors in the NT narrative (Magi, Roman centurion, Pilate\'s declaration of innocence). YHWH works through and despite the institutions of the nations.</p>',
    "3": '<p>"Do not send it empty-handed, but send a guilt offering with it." The Philistine priests understand instinctively that approaching the holy requires atonement — even those outside the covenant grasp the moral logic of holiness requiring restitution. Their guilt offering (<em>ʾāšām</em>) uses the same term as the "guilt offering" of Isaiah 53:10 (the Servant\'s life as ʾāšām). The nations\' own intuition points toward the shape of what Christ will accomplish.</p>',
    "4": '<p>Five golden tumors and five golden mice — a guilt offering corresponding to the afflictions brought. The principle of the guilt offering matching the damage caused is the same logic underlying the atonement: the offering must correspond to the trespass. Christ\'s atonement is qualitatively proportionate — the Son of God for the sins of the world.</p>',
    "5": '<p>"Give glory to the God of Israel" (<em>tənû kāḇôd lēʾlōhê yiśrāʾēl</em>) — the Philistine priests urge attributing honor to YHWH as the prerequisite for relief. The same call governs the NT proclamation: "repent and believe the good news" (Mark 1:15) is the call to re-attribute glory to the God one had dishonored.</p>',
    "6": '<p>"Why harden your hearts as Pharaoh hardened his heart?" — the Philistine priests invoke the Exodus as a warning. The pattern of Pharaoh is the paradigmatic case of resisting YHWH\'s evident power to the point of self-destruction. Hebrews 3:8, citing Psalm 95:8, warns the covenant community against the same pattern: "do not harden your hearts as in the rebellion." The Exodus pattern is the permanent template of what happens when humans resist divine grace.</p>',
    "7": '<p>The test design — milk cows that have never been yoked, separated from their calves — removes the natural explanation for the cows\' behavior. If the cows go straight to Beth-shemesh against every natural instinct (the pull toward calves, the unfamiliarity with the yoke), it proves divine compulsion. The design is apologetically sophisticated: the Philistine priests create conditions that rule out coincidence. This mirrors the design of the resurrection testimony — the women, the empty tomb, multiple appearances — structured to rule out natural explanation.</p>',
    "8": '<p>The guilt offering placed beside the Ark on the cart — atonement accompanying the presence. The two are not separated: YHWH\'s presence returns with the guilt offering alongside it. The pattern structures the entire OT sacrificial system and reaches its fulfillment in Christ: the one in whom divine presence fully dwells (Col 2:9) is also the guilt offering (Isa 53:10). Presence and atonement are never separate in the biblical narrative.</p>',
    "9": '<p>The test criterion: if the cows go straight to Beth-shemesh, YHWH did it; if they wander, it was coincidence. The criterion for verifying divine versus natural action is directed purposefulness — going straight against all instinct. The resurrection appearances similarly demanded explanation: the empty tomb plus the appearances in multiple locations plus the changed disciples exceeded natural explanation.</p>',
    "10": '<p>The men do as instructed — the obedience of the Philistines to their own priests\' design is noted. They are instruments of YHWH\'s self-return without knowing it fully. The theme of unwitting agents serving YHWH\'s purposes runs through the Passion narrative: Caiaphas prophesied "without knowing what he was saying" (John 11:51); Pilate\'s "what is truth?" occurred within YHWH\'s sovereign plan.</p>',
    "11": '<p>Ark placed on the cart with the guilt offering alongside — the visual image of holiness and atonement traveling together toward restoration. The single cart carrying both is the OT material picture of what the Incarnation accomplishes: in one person, divine presence and the sacrificial offering travel together toward the restoration of the covenant relationship.</p>',
    "12": '<p>"The cows went straight in the direction of Beth-shemesh along one road, lowing as they went" — the cows proceed against nature (away from their calves) by divine compulsion, lowing in protest but not deviating. The image captures the tension between natural resistance and divine purpose. Christ\'s Gethsemane prayer — "not my will but yours be done" (Luke 22:42) — expresses the same tension: the human will protests but the divine purpose prevails.</p>',
    "13": '<p>The people of Beth-shemesh "looked up and saw the ark" and "rejoiced at the sight" (<em>wayyiśmḥû lirʾôt</em>). The return of YHWH\'s presence produces spontaneous joy in those who had mourned its absence. John 16:22 — "your hearts will rejoice, and no one will take your joy from you" — describes the same quality of joy at the Resurrection that the disciples will experience: the return of the one whose presence had seemed permanently lost.</p>',
    "14": '<p>The cart stops at the field of Joshua of Beth-shemesh beside a large stone — the Ark resting at a natural altar site. The wood of the cart becomes the fuel for the sacrifice of the cows. The instruments of the Ark\'s return become the material of worship. This economy — where the vehicle of restoration becomes the material of sacrifice — anticipates the cross: the very means of Christ\'s suffering becomes the instrument of worship.</p>',
    "15": '<p>The Levites take down the Ark and the chest of gold figures, placing them on the large stone. The proper handling of holy things by the appropriate priestly office — after the crisis period in which YHWH\'s presence traveled without proper priestly escort — marks the restoration of covenant order. The pattern: the return of YHWH\'s presence requires and enables proper worship.</p>',
    "16": '<p>The five Philistine lords witness the restoration and return to Ekron. They have seen what YHWH\'s power looks like when it returns to its own territory. Hebrews 1:6 applies Deuteronomy 32:43 (LXX) — "let all God\'s angels worship him" — to Christ\'s resurrection and exaltation: even the heavenly powers witness and acknowledge the return of the Son to his rightful place.</p>',
    "17": '<p>The list of five golden tumors corresponding to the five Philistine lords — Ashdod, Gaza, Ashkelon, Gath, Ekron — is administrative bookkeeping for the guilt offering. The completeness of the offering (five for five) mirrors the completeness of atonement: nothing is owed, nothing remains uncovered. The guilt offering corresponds exactly to the guilt incurred.</p>',
    "18": '<p>The large stone as a permanent witness — the memorial marker of YHWH\'s return. The practice of memorial stones throughout the OT (Ebenezer in 7:12; the twelve stones of Joshua 4) establishes a pattern of covenant memory: the past act of divine faithfulness becomes the ground of future confidence. The resurrection is the NT\'s permanent Ebenezer — the historical event that grounds all subsequent faith.</p>',
    "19": '<p>"He struck down seventy of the men of Beth-shemesh because they looked into the ark of the LORD" — the holiness of YHWH\'s presence is not diminished by the return narrative\'s joyful tone. Those who presume on the accessibility of the divine — who look into what is restricted — encounter judgment. Hebrews 12:18-24 contrasts the terrifying holiness of Sinai with the accessible holiness of Christ\'s blood: the same God, but now mediated through the one who has opened the way into the Most Holy Place (Heb 10:19-20).</p>',
    "20": '<p>"Who is able to stand before the LORD, this holy God? To whom shall he go up from us?" — the question of Beth-shemesh is the existential question of the entire OT. Every encounter with YHWH\'s holiness produces the same response: Isaiah\'s "woe is me" (Isa 6:5), Peter\'s "depart from me" (Luke 5:8), John\'s falling as dead (Rev 1:17). The answer the NT gives is Christ, who is both the holy presence and the mediator who makes it possible to stand (Rom 5:1-2: "we have peace with God through our Lord Jesus Christ... and we have obtained access by faith").</p>',
    "21": '<p>The people of Beth-shemesh send to Kiriath-jearim to take the Ark — passing on both the privilege and the danger of custody. The Ark will remain at Kiriath-jearim for twenty years (7:2). The provisional housing of YHWH\'s presence in a series of imperfect arrangements — Tabernacle, Shiloh, Philistia, Beth-shemesh, Kiriath-jearim, then eventually Jerusalem — is the OT\'s persistent search for the permanent dwelling place. Revelation 21:22 resolves it: "I saw no temple in the city, for its temple is the Lord God Almighty and the Lamb."</p>'
  },
  "7": {
    "1": '<p>Eleazar consecrated to guard the Ark at Kiriath-jearim — a private household arrangement for YHWH\'s dwelling. The dwelling of divine presence in imperfect, unofficial, provisional arrangements is a recurring pattern: YHWH meets with Moses at a burning bush, makes a covenant under the stars with Abraham, speaks in a still small voice to Elijah in a cave. The Son of God is born in a stable. Divine presence is not dependent on architecture.</p>',
    "2": '<p>Twenty years of the Ark at Kiriath-jearim, and "all the house of Israel mourned and yearned after the LORD." The long period of absence — presence nearby but inaccessible for regular worship — is the experience of exile: YHWH near but not accessible in the usual ways. The mourning and yearning describe the condition of the people before Samuel\'s revival. They map onto the condition of human longing for God that the Incarnation addresses: the Word making his dwelling among us (John 1:14) ends the long exile.</p>',
    "3": '<p>Samuel\'s call to return — "If you are returning to the LORD with all your heart, then remove the foreign gods" — is the covenant-renewal formula: full covenant loyalty requires the removal of competing allegiances. Jesus\'s formulation "you cannot serve God and mammon" (Matt 6:24) is the same exclusive demand. The kingdom of God requires entire reorientation, not merely the addition of YHWH to an existing portfolio of loyalties.</p>',
    "4": '<p>Israel removes the Baals and Ashtaroth and "served the LORD alone" (<em>wayyaʿaḇdû ʾet YHWH ləḇaddô</em>) — the <em>ləḇaddô</em> (alone/only) formulation is the Deuteronomic summary of covenant faithfulness (Deut 6:4-5: "YHWH our God, YHWH alone"). The moment of singular loyalty to YHWH is the covenant precondition for the deliverance that follows (vv9-11). Faith that removes competing allegiances enables the divine warrior to act.</p>',
    "5": '<p>Samuel\'s intercession at Mizpah — "I will intercede for you before the LORD" (<em>wəʾetpallel baʿadḵem ʾel YHWH</em>). The priestly-prophetic role of intercessor is Samuel\'s most Christ-like function in these chapters. Hebrews 7:25 — "he always lives to make intercession for them" — describes Christ\'s permanent high-priestly function. Samuel\'s gathering and interceding for the people who had strayed from YHWH is a type of Christ gathering and interceding for the scattered covenant community.</p>',
    "6": '<p>The water-pouring before YHWH, fasting, and confession — "we have sinned against the LORD" — is the full penitential response. The water-pouring is not explained (a unique ritual here) and may symbolize the pouring out of the self before YHWH (cf. Ps 22:14; Lam 2:19). The pouring out of self before God as the condition for receiving grace anticipates Philippians 2:7 — Christ "poured himself out" (ekened) in the Incarnation — and the NT\'s repeated call to self-offering (Rom 12:1).</p>',
    "7": '<p>The Philistines advance against the assembly at Mizpah — the covenant people gathered in penitence are immediately threatened. The pattern of the enemy attacking at the moment of covenant renewal is consistent throughout the OT (Exod 14: Pharaoh pursues the just-released Israel) and NT (the devil tempts Jesus immediately after his baptism, Matt 4:1). Covenant commitment attracts opposition.</p>',
    "8": '<p>Israel asks Samuel: "Do not stop crying out to the LORD our God for us." The request for unceasing intercession reflects the community\'s recognition of their need for a mediator who can stand where they cannot. The appeal to Samuel reflects the same need addressed by Hebrews 4:16 ("we may with confidence approach the throne of grace") — access through a mediator rather than direct approach to the holy.</p>',
    "9": '<p>Samuel\'s burnt offering of a nursing lamb and his crying out to YHWH while under threat — the intercessor-priest combining sacrifice and prayer in the moment of crisis. The combination of sacrifice and intercession in a single figure performing both simultaneously is the fullest type of Christ\'s high-priestly work. Hebrews 9:24 — "he entered heaven itself, now to appear in the presence of God for us" — is the antetype: the sacrificial act and the ongoing intercession united in one person.</p>',
    "10": '<p>"The LORD thundered with great thunder against the Philistines that day" (<em>wayyarʿem YHWH bəqôl gādôl bayyôm hahûʾ</em>). The divine-warrior thunder is the weapon that routs the enemy while Samuel\'s sacrifice is still in progress. The simultaneity — Samuel offering, YHWH fighting — demonstrates that intercession is the mechanism by which the divine warrior engages on behalf of the covenant people. The same structure governs Revelation 8:3-5: the prayers of the saints, offered before God with incense, return as fire cast on the earth.</p>',
    "11": '<p>Israel pursues and strikes down the Philistines following the divine intervention — human action as the follow-through after YHWH\'s decisive act. The pattern of divine initiative followed by human participation in the victory appears throughout the conquest narratives and reaches its eschatological form in Revelation 19:11-21 (Christ rides out to battle; the armies of heaven follow).</p>',
    "12": '<p><strong>Ebenezer</strong> — "Thus far the LORD has helped us" (<em>ʿad hēnnāh ʿăzāranû YHWH</em>). The stone of remembrance marks a specific point in covenant history at which YHWH\'s faithfulness is attested. The phrase "thus far" implies there is more to come. The resurrection is the NT\'s Ebenezer: the definitive historical act of divine help that grounds all subsequent trust (Rom 8:32: "He who did not spare his own Son... how will he not also with him graciously give us all things?").</p>',
    "13": '<p>The Philistines subdued throughout Samuel\'s lifetime — the result of the covenant renewed at Mizpah. Samuel\'s tenure is a period of relative covenant faithfulness and divine protection. The pattern: covenant faithfulness brings covenant protection; covenant rebellion brings covenant curse. The entire DtrH is organized around this principle, which the NT reframes in Christ: the one who fulfilled the covenant perfectly secures the inheritance for those who are in him.</p>',
    "14": '<p>Territorial restoration — towns taken by the Philistines returned to Israel, peace with the Amorites. The scope of restoration following covenant renewal demonstrates that YHWH\'s faithfulness extends to political and territorial realities, not only to inner spiritual states. The eschatological restoration of "all things" (Acts 3:21) is the ultimate fulfillment of this pattern.</p>',
    "15": '<p>Samuel judged Israel throughout his lifetime — the faithfulness of a single covenant-faithful leader providing stable covenant administration for an entire generation. The longevity of Samuel\'s impact is a shadow of what Christ provides: a permanent mediator whose work does not expire with his mortality (Heb 7:23-24: Jesus holds his priesthood permanently because he lives forever).</p>',
    "16": '<p>Samuel\'s circuit ministry — Bethel, Gilgal, Mizpah — reaching the entire covenant community. The itinerant ministry of the covenant mediator, going out to where the people are, anticipates Jesus\'s Galilean circuit ministry (Matt 4:23; 9:35). The shepherd does not wait for the sheep to come to a fixed location but goes to where they are.</p>',
    "17": '<p>Samuel\'s base at Ramah, where he built an altar — the covenant mediator establishing a permanent worship site at his home. The altar at Ramah is his last piece of covenant infrastructure, connecting his prophetic ministry to the sacrificial system. The NT closes the era of specific altar sites: Jesus tells the Samaritan woman "neither on this mountain nor in Jerusalem will you worship the Father" (John 4:21), because the true worship of God in Spirit and truth transcends every geographic center.</p>'
  },
  "8": {
    "1": '<p>Samuel appoints his sons as judges when he grows old — repeating the pattern of Eli appointing his corrupt sons. The recurrence of the problem — covenant leaders whose successors fail — is the structural demonstration of why the human lineage cannot sustain covenant faithfulness across generations. The need for a priest and king whose office does not pass to fallible successors (Heb 7:23-24) is established by the repeated failure of every human dynasty.</p>',
    "2": '<p>Joel and Abijah at Beersheba — Samuel\'s sons serving at the southern boundary of Israelite territory. The naming of the sons (Joel = "YHWH is God"; Abijah = "YHWH is my father") signals the intended covenant continuity; the names, however, cannot guarantee the faithfulness of the men who bear them. The NT parallel: not everyone who says "Lord, Lord" will enter the kingdom (Matt 7:21).</p>',
    "3": '<p>"His sons did not follow his example — they turned to greed, accepted bribes, and twisted justice." The corruption of justice — taking bribes, perverting judgment — is the most serious failure of covenant leadership after idolatry, because the king and judge were to be the extension of YHWH\'s own justice. The NT promise is of a ruler "who judges justly" (1 Pet 2:23; cf. Isa 11:3-4: the shoot from Jesse will "judge with righteousness").</p>',
    "4": '<p>The elders of Israel assembling to confront Samuel — the covenant community exercising its right to address covenant leadership failure. The structured delegation to the prophet is the proper covenantal process (contrast the Korah rebellion\'s unauthorized challenge). The fact that the community identifies the problem clearly (Samuel\'s sons\' corruption) but proposes the wrong solution (a king) is the chapter\'s central tension.</p>',
    "5": '<p>"Appoint a king for us to rule us, as all the other nations" — the demand for assimilation to the nations\' form of governance. The desire to be "like all the other nations" (<em>kəkol haggôyim</em>) is the anti-covenant aspiration: Israel was constituted to be different from the nations, a "kingdom of priests and a holy nation" (Exod 19:6). The demand for assimilation is a demand for the abdication of covenant identity — and it is also the seed of the eventual coming of the true King who will rule all nations, making Israel\'s distinctiveness universally available.</p>',
    "6": '<p>Samuel\'s displeasure — "the request displeased Samuel" — and his prayer establish the prophet as the mediator of the covenant community\'s requests before YHWH. Samuel prays rather than deciding alone. The mediatorial prayer pattern is consistent with the intercessory role throughout Samuel\'s ministry and is the type of Christ\'s high-priestly prayer (John 17).</p>',
    "7": '<p><strong>"They have not rejected you, but they have rejected me from reigning over them."</strong> This verse is the theological center of the kingship narrative and arguably of the entire DtrH. The request for a human king is a rejection of YHWH\'s direct kingship. The implication for the entire subsequent narrative: every human king is a concession to the covenant community\'s failure, and the eventual coming of the messianic king must reverse this rejection by establishing YHWH\'s kingship definitively. Jesus\'s proclamation "the kingdom of God has come near" (Mark 1:15) directly addresses this deficit: YHWH\'s kingship, rejected here, is being reestablished in the Son.</p>',
    "8": '<p>The pattern of covenant rejection from the Exodus onward — "forsaking me and serving other gods." YHWH situates the request for a king within the larger pattern of Israel\'s covenant faithlessness rather than treating it as a unique failure. The rejection of YHWH\'s kingship is continuous with the idolatry of the wilderness generation; it is not a new departure but the latest expression of a persistent orientation. The entire covenant history is the demonstration of human inability to maintain covenant faithfulness — the backdrop against which Christ\'s active obedience is the necessary and sufficient response.</p>',
    "9": '<p>YHWH\'s command: comply with the request but warn them. The granting of the king is not endorsement but concession — YHWH accommodating the community\'s choice while clearly articulating its consequences. The pattern of YHWH working within and despite human failure rather than overriding human agency is the consistent divine pattern, reaching its apex in the cross: the worst human act (executing the Son of God) becomes the instrument of the best divine act (the redemption of the world).</p>',
    "10": '<p>Samuel faithfully reports YHWH\'s words — the prophet\'s role is transmission, not editorializing. The distinction between Samuel\'s own displeasure (v6) and his faithful proclamation of YHWH\'s word is important: the covenant mediator\'s personal reactions do not alter the message. The same pattern governs the NT prophetic and apostolic tradition: what was received is what is transmitted, not the messenger\'s preferences (1 Cor 15:3: "I handed on to you what I also received").</p>',
    "11": '<p>The "practice of the king" (<em>mišpaṭ hammelek</em>) — "he will take your sons." The king\'s first act is conscription. The pattern of human rulership is extraction: taking what belongs to the people for the ruler\'s purposes. This is the systematic inversion of YHWH\'s covenant generosity. The contrast is with the true King who "came not to be served but to serve, and to give his life as a ransom for many" (Mark 10:45) — the one who gives rather than takes.</p>',
    "12": '<p>Military conscription and agricultural labor for the king\'s benefit — the king becomes the greatest landlord and labor-exploiter in Israel. The warning is that human kingship reproduces Egypt: the corvée labor system (forced labor for state projects) that Israel escaped in the Exodus is reinstalled under their own king. The Christ who "sets the captives free" (Luke 4:18, citing Isa 61:1) addresses this structural bondage.</p>',
    "13": '<p>"He will take your daughters" — the king\'s household requires domestic labor. The appropriation of daughters for palace service (perfumers, cooks, bakers) is the feminization of the same extraction pattern described in vv11-12. Human kingship is totalizing; it colonizes every domain of life. The true King who "came to serve" gives; the human king takes.</p>',
    "14": '<p>The king seizes the best agricultural land and distributes it to his officials — the patron-client system of redistribution that benefits the royal network at the expense of the original covenant holders. Land in Israel was YHWH\'s gift to each tribe and family; its seizure by a king is the reversal of the covenant inheritance. Naboth\'s vineyard (1 Kgs 21) is the paradigmatic case of what Samuel warns about here.</p>',
    "15": '<p>Tithing of grain and vineyards for the king\'s court — a royal tithe that mirrors and competes with YHWH\'s tithe. The king positions himself as a second YHWH, claiming a tenth of the people\'s produce. The multiplication of claims on Israel\'s resources (YHWH\'s tithe, the king\'s tithe, the Levitical tithe) creates the layered burden that the prophets will later address (Amos 4:1; Mic 3:1-4).</p>',
    "16": '<p>Taking servants, the finest young men, and donkeys — comprehensive extraction from all domains of life. "You will become his subjects" (<em>wahayyîtem lô laʿăḇādîm</em>, literally "you will be his slaves") — the final destination: Israel enslaved to their own king, replicating their status in Egypt. The liberation from Egypt\'s bondage has traveled full circle. The gospel is the new Exodus from this bondage (Gal 5:1: "For freedom Christ has set us free; stand firm therefore and do not submit again to a yoke of slavery").</p>',
    "17": '<p>"You will cry out because of the king you have chosen, but the LORD will not answer you" — the deferred judgment. YHWH\'s silence in response to suffering under a self-chosen king is the opposite of his response to suffering under an imposed oppressor (Exod 2:23-24). Chosen bondage is its own kind of judgment. The NT addresses this: "you have not because you ask not" (Jas 4:2) — the alienation from YHWH\'s provision that results from choosing alternatives to him.</p>',
    "18": '<p>The silence of YHWH under the self-chosen king\'s oppression is the covenant consequence of the rejection of v7. The people will cry out — the same verb (<em>zāʿaq</em>) as Israel\'s cry under Egypt — but now without the covenant basis for divine response. This contrast will eventually drive the prophetic hope: a day when YHWH will act definitively to restore his kingship and end the bondage that the people\'s own choices created.</p>',
    "19": '<p>"We will have a king over us" — the flat refusal to hear the warning. The covenant community\'s determination to proceed despite full disclosure of the consequences is one of the clearest illustrations of the human heart\'s self-destructive tendency. Paul\'s analysis in Romans 1:18-32 — "they knew God but did not honor him as God" — applies structurally here: the people know the cost and insist anyway.</p>',
    "20": '<p>"So that we may be like all the other nations, with our king to lead us out and fight our battles" — the three demands: national normalization, military leadership, and external security. The desire for a human king to fight battles is precisely the relinquishment of YHWH as divine warrior. The people who saw the sea split, the walls of Jericho fall, and Midian routed by 300 men want a human general instead. Jesus\'s refusal of the crowd\'s attempt to make him king (John 6:15) is the mirror-image rejection: he will not be the kind of warrior king the people want, but the king who wins through sacrifice rather than force.</p>',
    "21": '<p>Samuel brings all the people\'s words before YHWH — the covenant mediator faithfully presenting the people\'s request to the divine sovereign. The priestly role of bearing the community\'s concerns before YHWH, even when those concerns are self-harmful, is continuous with the intercessory tradition. Christ\'s high-priestly intercession similarly brings the community\'s needs and failures before the Father — not editing out the failures but presenting them in the context of the Mediator\'s own standing.</p>',
    "22": '<p>"Listen to their voice and give them a king" — YHWH\'s concession that sets in motion the entire royal narrative of Samuel and Kings. The concession is not defeat; it is the activation of a longer plan. Every human king who fails (Saul, Solomon, the divided monarchy) becomes evidence that YHWH\'s original design — divine kingship mediated through a perfectly faithful human representative — cannot be achieved by ordinary men. The evidence accumulates until the promised Son of David appears who can fulfill what every previous king failed to accomplish (2 Sam 7:12-16; fulfilled in Christ: Luke 1:32-33).</p>'
  }
}

def main():
    existing = load_comm('mkt-christ', '1samuel')
    merge_comm(existing, SAMUEL1)
    save_comm('mkt-christ', '1samuel', existing)

    import json as _json
    il = _json.load(open(ROOT / 'data' / 'interlinear' / '1samuel.json'))
    all_ok = True
    for ch in [4, 5, 6, 7, 8]:
        ck = str(ch)
        missing = set(il.get(ck, {}).keys()) - set(existing.get(ck, {}).keys())
        if missing:
            print(f'ch {ch} STILL MISSING: {sorted(missing, key=int)}')
            all_ok = False
        else:
            print(f'ch {ch}: complete ({len(existing.get(ck, {}))} verses)')
    if all_ok:
        print('All verses present ✓')
    print(f'Total chapters in file: {len(existing)}')

if __name__ == '__main__':
    main()
