"""
MKT Christ — Mark all 16 chapters
Output: data/commentary/mkt-christ/mark.json

Mark\'s Christology is Son of God (1:1) framed by the baptism (1:11) and
the centurion (15:39). The Messianic Secret creates a pattern:
Jesus\'s identity is progressively revealed through suffering, not power.
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

DATA = {
  "1": {
    "1": '<p>A direct revelation: the beginning of the gospel of Jesus Christ, Son of God. Mark\'s opening declaration is the entire Gospel in one sentence: the subject of all that follows is Jesus (personal name, human historical identity), Christ (the Messiah, the anointed one of Israel\'s hope), and Son of God (the divine identity that gives the Messiah infinite worth). The gospel (euangelion) is not a teaching but a person — the announcement that this person has come, has acted, has died, has risen. Everything in Mark\'s 16 chapters is the unpacking of this opening declaration.</p>',
    "11": '<p>A direct revelation: you are my beloved Son; with you I am well pleased. The Father\'s declaration at the baptism identifies Jesus publicly as the royal Son (Ps 2:7) and the Servant-figure (Isa 42:1) simultaneously. Mark\'s Christology holds these two together without harmonizing them: the royal Son is the Suffering Servant; the one destined for universal dominion is the one who will give his life as a ransom for many. Every subsequent event in Mark unfolds the content of this dual identity — the exorcisms and healings demonstrate the Son\'s authority; the cross demonstrates the Servant\'s self-giving.</p>',
    "15": '<p>A direct revelation: the kingdom of God has come near — repent and believe in the good news. Christ is not merely the herald of the kingdom but its embodiment: wherever Jesus is, the kingdom is present. His exorcisms are kingdom-conflict (plundering the strong man\'s house, 3:27); his healings are the kingdom\'s compassion reversing the curse; his teaching is the kingdom\'s wisdom clarifying God\'s intention. The announcement that the time is fulfilled names Jesus\'s arrival as the fulfillment of the Danielic kairos — the appointed eschatological moment has come in his person.</p>'
  },
  "2": {
    "10": '<p>A direct revelation: the Son of Man has authority on earth to forgive sins. The Christological claim here is the most audacious of the Galilean ministry: Jesus exercises the divine prerogative of forgiveness not as a priestly representative applying a mechanism but in his own name, on his own authority, on earth. The Danielic Son of Man who received universal authority from the Ancient of Days is present in Capernaum, forgiving a paralytic, demonstrating that the eschatological reign has broken into the present through his person. The healing that follows makes the invisible forgiveness visible — the one who can do the harder thing (forgive) has demonstrated it by doing the visible thing (heal).</p>'
  },
  "3": {
    "27": '<p>A direct revelation: no one can enter a strong man\'s house and plunder his goods unless he first binds the strong man. The exorcisms are not individual humanitarian interventions but the systematic dismantling of the enemy\'s empire. Christ enters the strong man\'s house (the present age under demonic dominion) as the stronger one (the divine Son, anointed by the Spirit), binds the strong man (defeats Satan through the cross/resurrection), and plunders his goods (liberates those enslaved to demonic power). Every exorcism is an installment of this larger liberation — the kingdom\'s invasion of occupied territory.</p>'
  },
  "4": {
    "39": '<p>A direct revelation: he awoke and rebuked the wind and said to the sea, Peace! Be still. The calming of the storm is the exercise of the divine sovereignty over the waters that the OT declares belongs to YHWH alone (Ps 107:29, Job 9:8). Jesus exercises this sovereignty in his own person, not by prayer or petition to God, but by command: his word silences the storm. The disciples\' terrified question (who is this that even the wind and sea obey him?) is the question that Ps 107 answers — YHWH, who stills the storm. Mark presents Jesus as the one doing what the Psalm says only YHWH does.</p>'
  },
  "5": {
    "41": '<p>A direct revelation: Talitha koum — little girl, I say to you, arise. The resurrection of Jairus\'s daughter is the first explicit raising-from-death in Mark, performed with a simple Aramaic command. The contrast with later resurrection narratives (the elaborate prayer of Elijah in 1 Kgs 17:21, the stretching of Elisha over the boy in 2 Kgs 4:34-35) is stark: Jesus does not pray, does not invoke God, does not perform a ritual — he speaks to the dead girl as to a sleeping child. The command-authority over death revealed here is the authority that will be exercised in his own resurrection and in the final resurrection.</p>'
  },
  "8": {
    "29": '<p>A direct revelation: Peter answered him, You are the Christ. The Petrine confession at Caesarea Philippi is the structural center of Mark\'s Gospel. The immediate sequence that follows is theologically decisive: the Messianic Secret (silence commanded), the passion prediction (the Christ will suffer and die), and the call to cross-bearing. Mark\'s Christological argument is that the Messiah is only correctly understood as the Suffering Servant — to confess the Christ without the cross is to confess a misunderstood Christ. Peter\'s rebuke (v.32) and Jesus\'s sharp response (get behind me, Satan) demonstrate that Messiahship divorced from suffering is a Satanic distortion, not a divine truth.</p>',
    "34": '<p>A direct revelation: if anyone wishes to come after me, let him deny himself and take up his cross and follow me. The cross is not a Markan metaphor for general difficulty but a specific path: the path Christ himself walked. Discipleship in Mark is defined by cross-bearing — sharing the master\'s path of self-denial, rejection, suffering, and death in the confidence of resurrection. The cross-bearing community is the community shaped by the Christology: the Son of God who died reveals what it means to follow the Son of God who died. Mark\'s suffering community (addressed in the Roman persecution context) is being told that their cross-bearing is not a contradiction of the gospel but its confirmation.</p>'
  },
  "10": {
    "45": '<p>A direct revelation: the Son of Man came not to be served but to serve and to give his life as a ransom for many. Mark\'s version of the ransom saying is the definitive self-interpretation of the cross in this Gospel. The movement is from the Danielic Son of Man (who receives universal service, Dan 7:14) to the Isaianic Servant (who gives his life for the many, Isa 53:12) — Jesus holds both identities and describes their synthesis: the one who deserves all service gives himself for others\' ransom. The cross is not the defeat of the Son of Man but the specific form in which the Son of Man\'s authority is exercised.</p>'
  },
  "11": {
    "17": '<p>A direct revelation: is it not written, My house shall be called a house of prayer for all the nations? Jesus\'s temple action is a Christological claim: he acts with the authority of the temple\'s owner and designer (the divine author of Isa 56:7), overturning what has violated its purpose and restoring its universal-prayer function. The cursing of the fig tree (11:12-14) and the withering confirmed (11:20-21) frame the temple action, suggesting that the temple institution itself is under the same judgment as the fruitless tree. Christ is both fulfilling the temple\'s purpose and announcing its coming replacement by the community gathered around himself.</p>'
  },
  "14": {
    "22": '<p>A direct revelation: take; this is my body. The Last Supper words are the most concentrated Christological claim in Mark: Jesus identifies the bread with his body and the cup with the blood of the covenant poured out for many. He interprets his own impending death through the Passover and Sinai covenant frameworks — his body is the Passover lamb whose blood protects from judgment, and his blood is the covenant blood of Sinai that ratifies the relationship between God and people. The Lord\'s Supper instituted here is the permanent memorial of the one historical event on which the new covenant community is founded.</p>',
    "62": '<p>A direct revelation: I am; and you will see the Son of Man seated at the right hand of Power and coming with the clouds of heaven. Jesus\'s response before the high priest is the most explicit Christological self-disclosure in Mark. At the moment of maximum vulnerability (arrested, tried, abandoned), Jesus speaks the most comprehensive claim: he is the I AM (the divine self-identification), the enthroned Son of Man at God\'s right hand (Ps 110:1), and the coming one with divine glory (Dan 7:13). The humiliation does not diminish the claim; it is the form in which the claim reaches its fullest expression — the Son of God who dies is the Son of God who reigns.</p>'
  },
  "15": {
    "34": '<p>A direct revelation: my God, my God, why have you forsaken me? The cry of dereliction is a Christological statement about substitutionary atonement: the Son of God genuinely experiences God-forsakenness as the penalty of sin he bears for others. This is not theatrical or only apparent — the spiritual weight of bearing what separates humanity from God is real, and Jesus bears it in his own person. The darkness (v.33), the cry, and the death together constitute the atonement: at Golgotha, God in Christ is in the place of the God-forsaken, absorbing the wrath that sin deserves, so that those who trust him never need to experience that forsakenness themselves.</p>',
    "39": '<p>A direct revelation: truly this man was Son of God. The centurion\'s confession at the cross is Mark\'s Christological climax. The Gospel that opened with the declaration Jesus Christ, Son of God (1:1) and that the demons recognized throughout (1:24, 3:11, 5:7) now receives its human confession — from a Roman soldier, not a Jewish disciple, at the moment of death, not of triumph. Mark argues that the cross is not the refutation of the divine sonship but its revelation: it is precisely the manner of his death (v.39 — how he died) that leads the centurion to the confession. The Son of God is most clearly seen at the cross.</p>'
  },
  "16": {
    "6": '<p>A direct revelation: he has been raised; he is not here. The resurrection announcement by the young man (angel) in the empty tomb is the counterpart to the Father\'s declaration at the baptism: the one identified as the beloved Son (1:11) is the one raised from the dead (16:6). Mark does not narrate resurrection appearances (in the original ending) but declares the resurrection and points forward to Galilee — the community is to follow the risen Lord as they followed the living Lord through Mark\'s Gospel. The resurrection vindicates everything Jesus claimed and fulfills every passion prediction; it is the Father\'s endorsement of the Son\'s entire Messianic-Servant mission.'
  }
}

# Full gap-fill for ch 9 — all 50 verses (no prior entries to skip)
# Key themes: Transfiguration (divine glory unveiled), Elijah/John the Baptist typology,
# second passion prediction, healing as mini-resurrection, greatness-through-service,
# judgment sayings (Gehenna, salt/fire)
FILL_CH9 = {
  "9": {
    "1": "<p>&#8220;Truly I tell you, some who are standing here will not taste death before they see the kingdom of God come with power&#8221; — the immediate fulfillment is the Transfiguration six days later (v.2), where the three disciples see the kingdom&#8217;s power in Jesus&#8217;s unveiled glory. The final fulfillment is the Parousia. Jesus speaks as the one who controls the timing of the kingdom&#8217;s disclosure, linking his own visible glorification to the coming of the eternal reign.</p>",
    "2": "<p>&#8220;After six days Jesus took Peter, James and John with him and led them up a high mountain&#8221; — the six-day interval echoes Exodus 24:16 (Moses waited six days before YHWH spoke from the cloud on Sinai). Jesus brings the inner three to the mountain as Moses brought Aaron, Nadab, and Abihu (Exod 24:1). The high mountain is the site of divine disclosure; what is hidden in the valley is revealed on the summit.</p>",
    "3": "<p>His clothes became dazzling white — the whiteness of Jesus&#8217;s garments is the standard OT image for heavenly and divine glory (Dan 7:9 — the Ancient of Days clothed in white; Rev 1:14 — the Son of Man with white hair). The incarnation has temporarily veiled this glory; the Transfiguration is not a new event but a momentary unveiling of what was always present in Jesus&#8217;s person. The divine radiance of the Son of God is the ground of the incarnate Jesus&#8217;s existence.</p>",
    "4": "<p>Elijah and Moses appeared, talking with Jesus — the order (Elijah before Moses) is significant: the Prophets before the Law, or perhaps the one who did not die (Elijah, taken in a chariot) before the one who did (Moses). Both represent the entire prior revelation that converges on Jesus: Moses the Torah (Deut 18:15 — the prophet like me) and Elijah the Prophets (Mal 4:5 — Elijah before the great day). Their conversation with Jesus (Luke 9:31 says they spoke of his &#8220;exodus&#8221;) frames the cross as the fulfillment of all they represent.</p>",
    "5": "<p>Peter: &#8220;Rabbi, it is good for us to be here. Let us put up three shelters&#8221; — the proposal of equal shelters for Jesus, Moses, and Elijah reveals the category confusion: Peter places Jesus alongside the greatest figures of Israel&#8217;s redemptive history rather than recognizing him as their fulfillment and superior. The Feast of Tabernacles background (sukkot shelters) suggests Peter wants to dwell permanently in the glory moment; the cross must come first.</p>",
    "6": "<p>&#8220;He did not know what to say, they were so frightened&#8221; — Mark&#8217;s characteristic honest notation of the disciples&#8217; incomprehension. Theophanic fear is the appropriate initial response to divine presence (cf. Isaiah 6:5; Ezek 1:28); the disciples&#8217; terror before the unveiled glory of Jesus is the same terror that will eventually be transformed into worship at the resurrection appearances.</p>",
    "7": "<p>A cloud appeared and covered them, and a voice came from the cloud: &#8220;This is my Son, whom I love. Listen to him&#8221; — the cloud is the Shekinah, the visible form of divine presence (Exod 40:34-35; 1 Kgs 8:10-11). The Father&#8217;s declaration echoes the baptism (1:11) with one addition: &#8220;Listen to him&#8221; — a direct citation of Deuteronomy 18:15 (&#8220;to him you shall listen&#8221;), identifying Jesus as the prophet like Moses whom Israel was promised and commanded to obey. The Transfiguration is the divine authentication of Jesus&#8217;s entire teaching and mission.</p>",
    "8": "<p>&#8220;When they looked around, they no longer saw anyone with them except Jesus&#8221; — Moses and Elijah have departed; Jesus alone remains. The Law and the Prophets have been witnesses to him and now step aside. He is not one figure among many in the history of revelation but the one to whom all others pointed and from whom all now take their meaning. &#8220;Jesus alone&#8221; is Mark&#8217;s visual summary of his entire Christology.</p>",
    "9": "<p>Jesus orders them not to tell anyone what they had seen &#8220;until the Son of Man had risen from the dead&#8221; — this is the first explicit forward reference to the resurrection as the personal future event of Jesus himself. The Transfiguration cannot be properly understood until Easter: the unveiled glory seen on the mountain makes sense only as the glory of the one who dies and rises. Resurrection is the hermeneutical key to transfiguration.</p>",
    "10": "<p>They kept the matter to themselves, discussing what &#8220;rising from the dead&#8221; meant — the disciples&#8217; confusion reveals that resurrection was not a transparent concept; they knew the general resurrection at the end of the age (Dan 12:2) but not an individual resurrection in the middle of history, before the end. Jesus&#8217;s personal resurrection is a genuinely new event that the disciples&#8217; prior categories cannot accommodate.</p>",
    "11": "<p>&#8220;Why do the teachers of the law say that Elijah must come first?&#8221; — the disciples, having just seen Elijah on the mountain, now ask about the scribal expectation (Mal 4:5-6). The question is the right one: if the Messiah is present (they have just seen his glory), why has Elijah not yet come to prepare the way?</p>",
    "12": "<p>&#8220;To be sure, Elijah does come first, and restores all things. Why then is it written that the Son of Man must suffer much and be rejected?&#8221; — Jesus confirms the Elijah prophecy and then redirects: the scribal expectation of a triumphant Elijah-preceded Messiah must be held alongside the prophetic pattern of the suffering Son of Man (Isa 53; Ps 22). Both are written; both are true; the restoration and the suffering are not alternatives but sequence.</p>",
    "13": "<p>&#8220;But I tell you, Elijah has come, and they have done to him everything they wished, just as it is written about him&#8221; — John the Baptist is the Elijah who came; his rejection and execution by Herod (6:14-29) is the pattern that Jesus will fulfill at the hands of the chief priests and Pilate. The rejection of the forerunner anticipates and guarantees the rejection of the one he announced.</p>",
    "14": "<p>Returning to the other disciples, they find them surrounded by a crowd and arguing with teachers of the law — the contrast with the mountain scene is abrupt and deliberate: from unveiled divine glory to the failure of the disciples in the valley below. The disciples&#8217; failure in the exorcism (v.18) immediately follows the Transfiguration, exposing the gap between proximity to glory and operative faith.</p>",
    "15": "<p>&#8220;As soon as all the people saw Jesus, they were overwhelmed with wonder and ran to greet him&#8221; — the crowd&#8217;s wonder at his approach may reflect a residual glow from the Transfiguration (as Moses&#8217;s face shone after Sinai, Exod 34:29-30) or simply the authority that radiates from his person. The crowd&#8217;s instinct is to run toward him; this is the correct response to the presence of the Son of God.</p>",
    "16": "<p>&#8220;What are you arguing with them about?&#8221; — Jesus&#8217;s question to the scribes and his disciples cuts to the center: argument about Jesus (or about the kingdom, or about authority to cast out demons) is always resolved by recourse to Jesus himself. The one who is the answer to the argument has arrived.</p>",
    "17": "<p>&#8220;Teacher, I brought you my son, who is possessed by a spirit that has robbed him of speech&#8221; — the father brings his son to Jesus because the disciples have failed. The movement from failed human agents to Jesus himself is the narrative structure of faith: every human resource having been exhausted, the sufferer comes to the one who can actually help. The spirit&#8217;s specific effect (robbing the boy of speech) inverts Jesus&#8217;s ministry of giving voice to the voiceless.</p>",
    "18": "<p>&#8220;I asked your disciples to drive it out, but they could not&#8221; — the disciples&#8217; failure is not an embarrassment to be minimized but an honest disclosure of the limits of authority exercised apart from the prayerful dependence that Jesus will identify in v.29. The disciples had been given authority (3:15, 6:7); its failure shows that authority must be actively maintained through communion with Jesus.</p>",
    "19": "<p>&#8220;You unbelieving generation, how long shall I stay with you? How long shall I put up with you?&#8221; — the lament echoes Moses&#8217;s frustration with Israel in the wilderness (Deut 32:20 — &#8220;a perverse generation, children in whom is no faithfulness&#8221;; Num 14:27). Jesus as the new Moses encounters the same structural unbelief; his patience with the disciples is itself an act of grace. The question &#8220;how long?&#8221; also gestures toward the cross: his time is limited, and the disciples have not yet understood.</p>",
    "20": "<p>&#8220;When the spirit saw Jesus, it immediately threw the boy into a convulsion&#8221; — even before Jesus speaks, the demonic presence reacts to his proximity with violent resistance. This confirms the pattern from 1:24 and 3:11: the demonic realm recognizes the Son of God before humans do. The convulsion is a last violent assertion of dominion that the stronger one is about to end.</p>",
    "21": "<p>&#8220;How long has he been like this?&#8221; &#8216;From childhood&#8217; — Jesus&#8217;s pastoral question is not diagnostic (he already knows) but an act of personal attention to the father&#8217;s suffering. The answer &#8220;from childhood&#8221; emphasizes the depth of the bondage: the boy has never known freedom from this spirit. The longer the bondage, the more complete the liberation that Jesus&#8217;s healing represents.</p>",
    "22": "<p>&#8220;But if you can do anything, take pity on us and help us&#8221; — the father&#8217;s &#8220;if you can&#8221; reflects a faith weakened by the disciples&#8217; failure. He has begun to doubt not merely the disciples but the one who sent them. The &#8220;if&#8221; is honest rather than cynical; it is the prayer of a desperate person whose hope has been partially extinguished. Jesus&#8217;s response does not rebuke the honesty but redirects the doubt.</p>",
    "23": "<p>&#8220;&#8216;If you can&#8217;?&#8221; said Jesus. &#8220;Everything is possible for one who believes&#8221; — Jesus reverses the conditional: not &#8220;if I can&#8221; (as though the limitation were in him) but &#8220;if you believe&#8221; (faith as the channel of divine power). This is not a transactional prosperity formula but a Christological statement: the one who believes lays hold of the infinite capacity of the Son of God; unbelief is the only constraint on what the Son of God does through his servants.</p>",
    "24": "<p>&#8220;I do believe; help me overcome my unbelief!&#8221; — this is one of the most theologically honest statements in the Gospels. The father&#8217;s mixed faith — genuine but incomplete — is met with Jesus&#8217;s healing. Perfect faith is not the condition for Jesus&#8217;s action; the willingness to bring imperfect faith to him is. The prayer &#8220;help my unbelief&#8221; is itself an act of faith: trusting Jesus with the very lack of trust. He heals on the basis of this honest partial faith.</p>",
    "25": "<p>Jesus rebukes the spirit: &#8220;You deaf and mute spirit, I command you, come out of him and never enter him again&#8221; — the command is direct, unqualified, and permanent (&#8220;never enter him again&#8221;). Unlike the disciples, who presumably attempted the exorcism in Jesus&#8217;s name and failed, Jesus commands in his own authority. The spirit cannot resist; its resistance ends immediately. The finality of &#8220;never enter him again&#8221; anticipates the final binding of Satan at the cross.</p>",
    "26": "<p>The spirit shrieked, convulsed him violently and came out — the violent exit mimics death: &#8220;the boy looked so much like a corpse that many said, &#8216;He is dead.&#8217;&#8221; Mark deliberately frames the healing as a death-and-resurrection: the possessed boy dies (appearance of death), and Jesus will raise him. This is the structural pattern of Jesus&#8217;s own death and resurrection in miniature.</p>",
    "27": "<p>&#8220;But Jesus took him by the hand and lifted him to his feet, and he stood up&#8221; — the verb &#8220;lifted him&#8221; (<em>ēgeiren</em>, aorist of <em>egeirō</em>) is the standard NT word for resurrection: Jesus &#8220;raised&#8221; the boy. The physical gesture of taking the hand and lifting anticipates the angel&#8217;s message at the empty tomb: &#8220;He has been raised&#8221; (16:6). Every raising in Mark is a preview of the resurrection; Jesus is rehearsing his own resurrection through the healings he performs.</p>",
    "28": "<p>&#8220;After Jesus had gone indoors, his disciples asked him privately, &#8216;Why couldn&#8217;t we drive it out?&#8217;&#8221; — the private question shows the disciples know that something has gone fundamentally wrong; they had the same commission (3:15, 6:7) and had exercised it successfully before (6:13). Their honest inquiry is the beginning of understanding; they bring the failure to Jesus rather than rationalizing it.</p>",
    "29": "<p>&#8220;This kind can come out only by prayer&#8221; — prayer is not a technique but a posture of dependence: the disciples who fail are those who operate in their own authority, however divinely delegated; successful exorcism requires living communion with the Father through prayer. The authority to cast out demons is not a possession but a gift renewed through ongoing relationship. Prayer is the means by which proximity to the source of authority is maintained.</p>",
    "30": "<p>Jesus and the disciples pass through Galilee secretly, because he was teaching them — the private journey creates the conditions for the second passion prediction. The withdrawal from the crowd for intensive instruction with the inner circle is the pedagogical pattern of the passion section: Jesus is preparing the disciples for what is coming, knowing they are not yet ready.</p>",
    "31": "<p>&#8220;The Son of Man is going to be delivered into the hands of men. They will kill him, and after three days he will rise&#8221; — the second passion prediction is the clearest in Mark. &#8220;Delivered&#8221; (<em>paradidōmi</em>) is a divine passive: the handing over is ultimately God&#8217;s act, not merely human treachery (cf. Isa 53:6 — &#8220;the LORD has laid on him the iniquity of us all&#8221;). The prediction contains both the death and the resurrection as equally certain: the Son of Man who is handed over is the same Son of Man who will rise.</p>",
    "32": "<p>&#8220;They did not understand what he meant and were afraid to ask him about it&#8221; — the disciples&#8217; double failure: incomprehension and fear of pursuing understanding. Their fear to ask reveals a deeper fear of what understanding might require. Mark does not excuse the disciples but records their failure honestly as a warning to readers who are also tempted to avoid the implications of the cross-resurrection pattern.</p>",
    "33": "<p>&#8220;When he was in the house, he asked them, &#8216;What were you arguing about on the way?&#8217;&#8221; — Jesus&#8217;s question exposes the gap between the second passion prediction (just given) and the disciples&#8217; actual preoccupations. While Jesus was speaking of his death, they were debating status. The juxtaposition is not coincidental: the inability to hear the passion prediction and the preoccupation with greatness are the same failure.</p>",
    "34": "<p>&#8220;But they kept quiet because on the way they had argued about who was the greatest&#8221; — the silence is guilty; they know the question is incompatible with what Jesus has just taught. The argument about greatness is the disciples&#8217; version of the Beelzebul controversy: they have understood enough to be embarrassed but not enough to be changed. This silence also anticipates Gethsemane, where they will be unable to watch and pray.</p>",
    "35": "<p>&#8220;Sitting down, Jesus called the Twelve and said, &#8216;Anyone who wants to be first must be the very last, and the servant of all&#8217;&#8221; — the formal seated position signals a solemn teaching. The inversion of the honor-shame hierarchy is not merely ethical advice but a Christological statement: Jesus, who is first in all things (Col 1:18), became last — the servant of all — in the incarnation and especially at the cross. Discipleship is conformed to the shape of the master&#8217;s self-giving.</p>",
    "36": "<p>He took a little child whom he placed among them, taking the child in his arms — the physical action is the visual parable: Jesus embodies the teaching by holding the child, the social nonentity. The child is the least significant member of the ancient Mediterranean household, with no status and no resources to reciprocate hospitality. To receive and serve such a person is to embody the kingdom&#8217;s values.</p>",
    "37": "<p>&#8220;Whoever welcomes one of these little children in my name welcomes me; and whoever welcomes me does not welcome me but the one who sent me&#8221; — the vertical chain of reception: to welcome the child = to welcome Jesus = to welcome the Father. Jesus identifies himself as the one through whom all human encounter with God is mediated; to receive him (even in his most unlikely representatives) is to receive the Father. This is the &#8220;in my name&#8221; principle: all reception and service that is done in relation to Jesus reaches God himself.</p>",
    "38": "<p>&#8220;Teacher, we saw someone driving out demons in your name and we told him to stop, because he was not one of us&#8221; — John&#8217;s report exposes the disciples&#8217; proprietary attitude toward Jesus&#8217;s name and power. Their objection is institutional (&#8220;not one of us&#8221;) rather than theological (not acting against the kingdom). The man is doing Jesus&#8217;s work in Jesus&#8217;s name; the disciples&#8217; boundary-drawing is the wrong response.</p>",
    "39": "<p>&#8220;Do not stop him, for no one who does a miracle in my name can in the next moment say anything bad about me&#8221; — Jesus&#8217;s name has power that works beyond the formal disciple community; those who invoke it genuinely align themselves with Jesus even if they are not part of the Twelve. The kingdom is not coextensive with the institutional community; Jesus&#8217;s authority is not confined by the boundaries the disciples draw.</p>",
    "40": "<p>&#8220;For whoever is not against us is for us&#8221; — the reverse of 3:25 (a divided house cannot stand); there the warning is against false neutrality; here the principle is generous inclusion of those who work in the same cause. The kingdom&#8217;s boundaries are wider than the disciples&#8217; sectarian instincts, though not infinitely so; the criterion is orientation toward Jesus.</p>",
    "41": "<p>&#8220;Truly I tell you, anyone who gives you a cup of water in my name because you belong to the Messiah will certainly not lose their reward&#8221; — &#8220;because you belong to the Messiah&#8221; (<em>hoti Christou este</em>) is a remarkable phrase: the disciples&#8217; identity is defined by their belonging to Christ. Even the smallest act of hospitality extended to those who are Christ&#8217;s — on the basis of that relationship — is permanently recorded. The Messiah values his community to the degree that service to them is service to him.</p>",
    "42": "<p>&#8220;If anyone causes one of these little ones who believe in me to stumble, it would be better for him to have a large millstone hung around his neck and to be thrown into the sea&#8221; — &#8220;the little ones who believe in me&#8221; extends the child image to all who trust in Jesus despite their social or spiritual smallness. Their faith makes them precious to Christ; to destroy their faith is to attack what Christ values most. The severity of the judgment announced reflects the infinite worth Jesus places on even the weakest believer.</p>",
    "43": "<p>&#8220;If your hand causes you to stumble, cut it off&#8221; — hyperbolic rhetoric in the prophetic tradition (cf. Matt 5:29-30 where the same logic applies to the eye). The point is not literal self-mutilation but the radical priority of entering life with Jesus over preserving anything that obstructs that entry. The hand, foot, and eye represent the instruments of action, movement, and desire — every avenue through which sin can enter must be brought under radical discipline.</p>",
    "44": "<p>&#8220;Where the worms that eat them do not die, and the fire is not quenched&#8221; — citing Isaiah 66:24, the final verse of Isaiah where the redeemed look upon the corpses of those who rebelled against God. Gehenna (the Valley of Hinnom, south of Jerusalem, historically the site of child sacrifice and later Jerusalem&#8217;s refuse fire) becomes Jesus&#8217;s image for the permanent consequence of choosing sin over life with God. The unquenchable fire and undying worm symbolize an irreversible condition.</p>",
    "45": "<p>&#8220;If your foot causes you to stumble, cut it off. It is better for you to enter life crippled than to have two feet and be thrown into hell&#8221; — the foot represents movement and direction; where one walks determines where one ends up. The radical surgery demanded is not ascetic suffering but the willingness to remove any habitual pattern of life that leads away from the kingdom. Life with Christ — even diminished — infinitely exceeds death without him.</p>",
    "46": "<p>&#8220;Where the worms that eat them do not die, and the fire is not quenched&#8221; — the repetition of the Isaiah 66:24 refrain reinforces the seriousness of the warning. Each member (hand, foot, eye) that causes stumbling receives the same terrible alternative. Jesus&#8217;s willingness to repeat this warning three times shows that he does not soften the reality of judgment; the love that died for sinners is the same love that warns about the consequences of rejecting him.</p>",
    "47": "<p>&#8220;If your eye causes you to stumble, pluck it out. It is better for you to enter the kingdom of God with one eye than to have two eyes and be thrown into hell&#8221; — the eye represents desire and aspiration; what one sees and covets shapes what one pursues. The eye that looks at the wrong things leads to Gehenna; the eye trained on the kingdom leads to life. The kingdom of God and Gehenna are not symmetrical options — the kingdom is the presence of the living God; Gehenna is the absence of everything good.</p>",
    "48": "<p>&#8220;Where the worms that eat them do not die, and the fire is not quenched&#8221; — the threefold refrain concludes the judgment series. That Jesus cites Isaiah 66:24 at the very end of Isaiah is theologically significant: Isaiah closes with the vision of new creation and the warning of permanent judgment standing side by side. Jesus inherits and intensifies this dual ending: the kingdom he brings offers life; the rejection of the kingdom has permanent consequences.</p>",
    "49": "<p>&#8220;Everyone will be salted with fire&#8221; — the salt and fire image is dense with OT resonance. Covenant sacrifices required salt (Lev 2:13 — the covenant of salt); fire was the medium of divine presence and purification (Mal 3:2 — he will be like a refiner&#8217;s fire). The disciples who go through the fire of discipleship (persecution, suffering, cross-bearing) are being preserved and purified, not merely consumed. The fire of judgment (Gehenna) and the fire of purification (discipleship) are related: those who are refined by the latter are spared the former.</p>",
    "50": "<p>&#8220;Salt is good, but if it loses its saltiness, how can you make it salty again? Have salt among yourselves, and be at peace with each other&#8221; — the final word of the chapter is &#8220;peace&#8221; (<em>eirēneue</em>). The disciples who have been arguing about greatness (v.33-34) and excluding unauthorized workers (v.38-39) are called to be salt among themselves — to preserve the community through the covenant-integrity that salt represents. The peace Jesus commands is not mere affability but the covenant-relationship that the disciples&#8217; competitive ambition has disrupted. It is ultimately the peace that flows from being at peace with the Prince of Peace.</p>"
  }
}

def main():
    existing = load_comm('mkt-christ', 'mark')
    merge_comm(existing, DATA)
    merge_comm(existing, FILL_CH9)
    save_comm('mkt-christ', 'mark', existing)
    total = sum(len(v) for v in existing.values())
    print(f"Mark mkt-christ: {len(existing)} chapters, {total} verses written.")

if __name__ == '__main__':
    main()
