"""
MKT Context Commentary — 1 Chronicles chapters 7–8 (fill)
Run: python3 scripts/zc-context-1chronicles-7-8-fill.py

Fills 78 missing verses (ch7 all except v24; ch8 all except v29).
Context layer = historical, geographic, social, and archaeological background.

Key decisions:
- Ch7 covers five distinct tribal genealogies (Issachar, Benjamin-A, Naphtali,
  Manasseh, Ephraim, Asher) with geographic and social context for each
- Ch8 is Benjamin's extended genealogy focused on the Saul dynasty territory
- Genealogies function as social-memory documents encoding territorial claims,
  military muster-rolls, and post-exilic community legitimacy
- v12: Dan is absent from both ch7 and the main genealogy (ch2-9); noted in context
- v13: Naphtali's brevity reflects the northern-tribe minimal treatment
- v24: Sheerah already covered (context note already present)
- v29: Gibeon already covered (context note already present)
"""

import json, os

def load_comm(layer, book):
    path = f'data/commentary/mkt-{layer}/{book}.json'
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {}

def save_comm(layer, book, data):
    path = f'data/commentary/mkt-{layer}/{book}.json'
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=None)
    print(f'wrote {path}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, text in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = text

CHRONICLES = {
  "7": {
    "1": "<p>Issachar&rsquo;s territory lay in the Jezreel valley and the lower Galilee slopes &mdash; the most fertile agricultural land in Canaan. The valley floor (modern Marj Ibn Amir) was renowned in antiquity for its grain production. Issachar&rsquo;s four sons match the Numbers 26:23&ndash;25 census tradition; their position in the tribal genealogy between the northern group and the Joseph tribes reflects their central geographical position between Galilee and Manasseh&rsquo;s highland territory.</p>",
    "2": "<p>The figure of 22,600 warriors in David&rsquo;s day (from Tola&rsquo;s line alone) reflects the Chronicler&rsquo;s use of tribal census data. The Jezreel valley&rsquo;s agricultural wealth would have supported a dense population: the valley received reliable winter rainfall and was easily worked. Egyptian records from the New Kingdom period list Jezreel settlements as major administrative centres under Pharaonic control, confirming the region&rsquo;s economic and demographic significance before and during the early Israelite monarchy.</p>",
    "3": "<p>Izrahiah&rsquo;s five sons all designated &ldquo;leaders&rdquo; suggests the Issacharite aristocracy of David&rsquo;s period was organized around multiple clan-heads of equal standing rather than a single paramount chief. This collegial leadership structure is attested in the Amarna letters (14th century BCE), where Canaanite city-states in the Jezreel valley were governed by councils of local leaders alongside Pharaonic representatives.</p>",
    "4": "<p>The 36,000-troop figure for Izrahiah&rsquo;s line, attributed to large households (&ldquo;many wives and sons&rdquo;), reflects the ancient Near Eastern connection between polygyny and political power. In pre-monarchic and early monarchic Canaan, having multiple wives was a marker of elite status that also produced the large male offspring needed to sustain military and administrative networks. The genealogy here functions as a militia registration: tribal muster-lists were kept for the same purposes as modern census and military draft records.</p>",
    "5": "<p>The 87,000 total Issacharite warriors makes Issachar one of the largest tribal contingents in the Davidic military system. This contrasts with the Numbers 26 census (54,400) and may reflect a different administrative moment or a different counting methodology (by households vs. by individuals). Issachar&rsquo;s military prominence is consistent with the tribe&rsquo;s position at the crossroads of the north-south and east-west routes through Canaan &mdash; a strategic location requiring substantial defensive capacity.</p>",
    "6": "<p>The three-son list for Benjamin (Bela, Becher, Jediael) represents a different Benjaminite tribal tradition from chapter 8&rsquo;s extended list. Benjamin occupied the narrow highland strip between Jerusalem and the Jordan valley, a strategically critical corridor that controlled access to the ford at Jericho. The tribe&rsquo;s position on the border between Judah and Ephraim gave it significance both in the united monarchy (Saul) and in the divided kingdom (Benjamin straddled the line between northern and southern territories).</p>",
    "7": "<p>Bela&rsquo;s five sons and the 22,034-warrior count situate this genealogy in the administrative apparatus of the Davidic kingdom. Archaeological surveys of the Benjaminite highlands show relatively dense settlement patterns in the Iron Age I&ndash;II period, consistent with a substantial tribal population capable of fielding this size force. The term &ldquo;mighty warriors&rdquo; (gibbôrê ḥayil) is used in administrative texts from this period to designate professional soldiers or military reservists distinguishable from levied farmers.</p>",
    "8": "<p>Becher&rsquo;s nine sons include Anathoth, the place-name later associated with Jeremiah&rsquo;s priestly family (Jer 1:1). Anathoth (modern Ras el-Kharrubeh, about 3 miles northeast of Jerusalem) was a Benjaminite Levitical city (Josh 21:18). The embedding of place-names as personal names in genealogies is a common West Semitic practice; it records which family first settled and controlled a particular site. Anathoth&rsquo;s appearance here as Becher&rsquo;s son establishes the Benjaminite genealogical claim to that locality.</p>",
    "9": "<p>The 20,200 warriors enrolled for Becher&rsquo;s line, alongside the technical term for genealogical registration, reflects the administrative reality of the post-exilic period: families returning from Babylonian exile needed documented tribal affiliation to claim land, temple participation rights, and community standing. The Chronicler&rsquo;s preservation of these enrollment figures served a living community function for the returnees, not merely historical interest.</p>",
    "10": "<p>Jediael&rsquo;s son Bilhan produces seven military sub-commanders. The name Bilhan appears also in an Edomite context (Gen 36:27), reflecting the naming overlap between early Israelite and Edomite tribal groups along the southern corridor. The seven-son list follows the common West Semitic pattern of organizing hereditary offices into a symmetrical numerical group, representing the full complement of military leadership for a major clan.</p>",
    "11": "<p>Jediael&rsquo;s 17,200 warriors &ldquo;fit for military service&rdquo; is the smallest of the three Benjaminite sub-lists in ch7, but the formal conscription language (&ldquo;those fit for going out to battle&rdquo;) indicates this was a real administrative classification. In the ancient Near East, military fitness assessments distinguished between those able to serve as active combatants and those assigned to logistics or garrison duty; this enrollment category appears to cover the active combat pool.</p>",
    "12": "<p>The cryptic verse about Shuppim, Huppim, and Hushim son of Aher has long been recognized as a Dan fragment. Dan&rsquo;s son is named Hushim in Gen 46:23 (also called Shuham in Num 26:42). The near-total omission of Dan from 1 Chronicles&rsquo; genealogies (ch2&ndash;9) is striking. Some scholars connect it to Dan&rsquo;s association with illegitimate cult centers (Judg 18; 1 Kgs 12:29&ndash;30); others see it as a coincidence of damaged source material. The same silence about Dan appears in Rev 7:4&ndash;8, where Dan is omitted from the 144,000. The deliberate or incidental suppression of Dan&rsquo;s genealogy reflects the tribe&rsquo;s complex and controversial history.</p>",
    "13": "<p>Naphtali&rsquo;s four-name list (with the single note &ldquo;from Bilhah&rdquo;) receives minimal treatment compared to the extended genealogies of Issachar, Benjamin, and Ephraim. Naphtali occupied the northern Galilee highlands and the western shore of the Sea of Galilee. The region was heavily Canaanite and later Aramaean in cultural influence; Isaiah&rsquo;s &ldquo;Galilee of the nations&rdquo; (Isa 9:1) reflects this mixed character. Naphtali&rsquo;s role in the Deborah coalition was significant (Judg 4:6; 5:18), but the tribe receives less Chronicler attention than the southern and central tribes whose descendants formed the core of the post-exilic community.</p>",
    "14": "<p>Manasseh&rsquo;s Transjordanian territory (Gilead) through Machir reflects the historical reality of Israelite settlement east of the Jordan. Gilead was a contested border zone: the region passed between Israelite, Moabite, Ammonite, and Aramaean control across the centuries. The Aramean concubine in Machir&rsquo;s household reflects the intermarriage pattern documented in the Tell Dan stele and other Aramaean inscriptions, where the boundaries between Israelite and Aramaean populations in this region were porous.</p>",
    "15": "<p>The reference to Zelophehad (&ldquo;who had only daughters&rdquo;) connects this genealogy to one of the most significant legal precedents in the Pentateuch. The daughters of Zelophehad (Mahlah, Noah, Hoglah, Milcah, Tirzah) petitioned Moses for the right to inherit their father&rsquo;s portion when he died without male heirs (Num 27:1&ndash;11). YHWH&rsquo;s ruling in their favour established a permanent inheritance statute (Num 27:8&ndash;11) that allowed daughters to inherit when there were no sons. The genealogical note here grounds that legal case in the specific family history of Manassite Machir&rsquo;s line.</p>",
    "16": "<p>Maachah as Machir&rsquo;s wife (the same name as the Aramean kingdom north of Dan) confirms the cultural overlap between northern Manasseh and Aramean groups. The kingdom of Maachah (2 Sam 10:6, 8) was one of several small Aramaean polities in the Transjordan-Hauran region whose relationship with Israel alternated between alliance and conflict. The personal name Maachah crossing ethnic boundaries mirrors the historical reality of intermarriage along these borders.</p>",
    "17": "<p>The Bedan mentioned here as a descendant of Gilead appears in 1 Sam 12:11 in Samuel&rsquo;s historical review as one of the judges sent to deliver Israel. Some manuscripts read &ldquo;Barak&rdquo; in 1 Sam 12:11 instead of Bedan; the variation may reflect a judge from Manassite Gilead who was less prominent in the Ephraimite-centered judge traditions but preserved in the Transjordanian genealogical memory. Gilead produced several distinctive leaders (Jephthah, Elijah the Tishbite) who operated at the margins of the main Cisjordanian tribal narrative.</p>",
    "18": "<p>Hammoleketh (&ldquo;the queen&rdquo;) is one of several women in 1 Chronicles&rsquo; genealogies who appear as founders of lineages or places. Her descendants include Abiezer, the ancestor of Gideon (Judg 6:11). The Abiezrite clan whose land included the great oak of Ophrah was situated in the western portion of Manasseh. The association of a woman-founder with Gideon&rsquo;s clan may preserve a pre-patriarchal memory of female leadership in the Manassite highlands, consistent with matrilineal inheritance traditions in some adjacent cultures.</p>",
    "19": "<p>Shemida and his four sons are attested in the Samaria Ostraca (8th century BCE administrative pottery sherds from the city of Samaria), where Shemida appears as a clan name associated with wine-production districts. The Samaria Ostraca are among the most important epigraphic finds from the northern kingdom and demonstrate that the clan names in Numbers 26 and 1 Chronicles reflect genuine administrative units still functional centuries after the initial settlement period.</p>",
    "20": "<p>Ephraim&rsquo;s linear genealogy through Shuthelah begins the longest tribal section in ch7 (vv20&ndash;29). Ephraim occupied the central highland ridge between the Jezreel valley and the Shephelah &mdash; the strategic heart of the northern kingdom. The highlands of Ephraim (modern West Bank hill country around Nablus and Ramallah) were well-forested and defensible; the tribe&rsquo;s central position made it dominant in the pre-monarchic period and the tribal nucleus of the northern kingdom after 931 BCE.</p>",
    "21": "<p>The Ephraimite cattle raid on Gath reflects the historical proximity of Ephraimite settlers to Philistine territories during the early Iron Age. Gath (Tell es-Safi) was the largest Philistine city and lay at the edge of the Shephelah, accessible from the Ephraimite highlands through the Vale of Elah. Archaeological excavations at Gath have revealed destruction layers consistent with repeated conflicts with neighbouring populations in the Iron Age I period (12th&ndash;10th centuries BCE), the era when this episode likely occurred.</p>",
    "22": "<p>Ephraim&rsquo;s extended mourning for his sons killed in the Gath raid places the patriarch in a position analogous to Jacob grieving for Joseph. The grief narrative embedded in a genealogy is a literary technique for humanizing an otherwise administrative register. Ancient Near Eastern funerary practices included extended mourning periods; Egyptian and Ugaritic texts describe multi-day mourning rituals for fallen warriors. The brothers&rsquo; consolation visit reflects the kinship-solidarity system that organized Israelite clan life.</p>",
    "23": "<p>The birth of Beriah as consolation after loss is a pattern in biblical genealogy: Isaac born to Abraham and Sarah after years of barrenness; Benjamin born to Jacob after Rachel&rsquo;s death; Samuel born to Hannah after her humiliation. The Ephraimite Beriah tradition may have been preserved because Beriah&rsquo;s line became important in the later Ephraimite community &mdash; his name, encoding the memory of family tragedy, served as a constant reminder of the tribe&rsquo;s founding grief.</p>",
    "25": "<p>The linear descent from Rephah and Resheph toward Joshua spans approximately six to eight generations, placing the genealogy in the pre-conquest period. The transition from the personal-narrative elements (vv21&ndash;24) back to the linear descent sequence signals the return to official tribal documentation. These names (Rephah, Resheph, Tahan) are otherwise unknown but function to bridge the genealogy between the Beriah story and the theologically crucial name of Joshua at v27.</p>",
    "26": "<p>Ladan and Ammihud are intermediate ancestors between the Ephraimite clans and Elishama, who appears in Numbers as the tribal prince of Ephraim (Num 1:10; 2:18; 7:48&ndash;53). Elishama led the Ephraimite division of the wilderness camp, marshalled for the tribal march, and offered the Ephraimite dedication gifts for the tabernacle. His position in this genealogy confirms the Chronicler&rsquo;s use of a source that connected the Numbers tribal leaders to the extended Ephraimite family tree.</p>",
    "27": "<p>Joshua son of Nun (here: Non) was not only Israel&rsquo;s military leader in the conquest but the first leader to bear a name formed with the YHWH prefix (Num 13:16; Moses renamed Hoshea to Yehoshua). His Ephraimite lineage is historically significant: the tribal affiliation of Israel&rsquo;s military saviour in the conquest was the same tribe that would later become the dominant tribe of the northern kingdom. The Joshua genealogy grounds the conquest narrative in a specific Ephraimite family, not a mythologized hero figure.</p>",
    "28": "<p>The Ephraimite territorial catalogue (Bethel, Naaran, Gezer, Shechem, Ayyah) preserves the pre-Solomonic Ephraimite land-claims. Shechem was Israel&rsquo;s first capital under Jeroboam (1 Kgs 12:25) and a major cultic and administrative centre before Jerusalem; its inclusion in the Ephraimite territorial list confirms the tribe&rsquo;s attachment to this ancient covenant site (Gen 34; Josh 24). Gezer, at the foothills of the Shephelah, was the last major Canaanite city-state to fall to Israelite control, eventually given to Solomon as Egyptian royal dowry (1 Kgs 9:16&ndash;17).</p>",
    "29": "<p>Manassite border cities along the Jezreel corridor (Beth-shean, Taanach, Megiddo, Dor) were the most heavily fortified urban centres in Canaan during the Late Bronze Age. Egyptian pharaohs used this corridor as the primary route for military campaigns into Syria; the Battle of Megiddo (ca. 1457 BCE under Thutmose III) took place at this location. The Israelite failure to displace these Canaanite city-states (Judg 1:27&ndash;28) was a persistent military weakness; the cities eventually came under Israelite control during the Solomonic period through administrative reorganization rather than conquest (1 Kgs 9:15&ndash;19).</p>",
    "30": "<p>Asher&rsquo;s coastal territory stretched from the Carmel promontory northward through the Akko plain and into the region of Tyre and Sidon. The tribe was positioned along one of the most commercially active coastlines in the ancient world: Phoenician cities (Tyre, Sidon, Byblos) were Asher&rsquo;s northern neighbours, and Asher&rsquo;s genealogy reflects the cultural contact between Israelite and Phoenician populations. The failure to displace the coastal cities (Judg 1:31&ndash;32) meant Asher remained in a semi-integrated relationship with Canaanite coastal culture throughout the Judges period.</p>",
    "31": "<p>Beriah and Malchiel of Asher&rsquo;s tribe appear in Genesis 46:17 and Numbers 26:44&ndash;45; the genealogy here extends their lines. Malchiel&rsquo;s son Birzaith (from a root possibly meaning &ldquo;olive/olive-related&rdquo;) points to Asher&rsquo;s olive-oil economy: the coastal slopes of the Carmel range and the Galilee hills were among the most productive olive-growing zones in ancient Palestine. Asher is blessed in Deut 33:24 with oil from rock (&ldquo;let him dip his foot in oil&rdquo;), reflecting the tribe&rsquo;s agricultural specialization.</p>",
    "32": "<p>Heber&rsquo;s three sons and sister Shua illustrate the bilateral kinship system that preserved female names alongside male in certain genealogical traditions. A non-Israelite Heber of the same name appears in Judges 4:11&ndash;22 (Jael&rsquo;s husband, a Kenite), reflecting the name&rsquo;s broader West Semitic distribution. The Asherite Heber&rsquo;s line receives the most extended genealogical treatment in the chapter (vv32&ndash;39), indicating this sub-clan retained historical prominence in the traditions the Chronicler compiled.</p>",
    "33": "<p>Japhlet&rsquo;s three sons and the territorial association with Josh 16:3 suggest the Japhletite clan held land on the Ephraimite-Asherite border. The Japhlet&rsquo;s border in Joshua is described as the boundary between Ephraim&rsquo;s allotment and the descent toward the coast &mdash; positioning this clan as controllers of the transition zone between highland agriculture and coastal commerce. Such border clans often had mixed ethnic and economic profiles in the ancient Near East.</p>",
    "34": "<p>The sub-names within Heber&rsquo;s genealogy (Rohgah, Jehubbah, Aram) include Aram as a personal name, consistent with Asher&rsquo;s northern position near Aramean-influenced territory. The Aramaean cultural sphere extended well into northern Galilee; personal names reflecting Aramean cultural contact are unsurprising in an Asherite context. The name Aram in an Israelite tribal genealogy does not indicate Aramean ethnicity but rather the cultural borrowing common in border zones.</p>",
    "35": "<p>The identification of Helem with Hotham (v32) is textually plausible: the Hebrew letters of Hotham and Helem are sufficiently similar to account for scribal variation (ḥôṯām / ḥêlem). Scribal confusion between similar letter-forms is a recognized source of textual variation in Hebrew manuscripts; the Masoretic Text preserves the variant spellings without harmonizing them. Zophah heads the next sub-list, providing the next level of Asherite descent.</p>",
    "36": "<p>Zophah&rsquo;s six sons include names with non-Semitic or mixed linguistic backgrounds (Harnepher, Shual), reflecting the cultural mixing in Asher&rsquo;s coastal zone. Archaeological evidence from the Akko plain (Asher&rsquo;s heartland) shows substantial Egyptian administrative presence in the Late Bronze Age and Sea People/Phoenician cultural influence in Iron Age I. Israelite tribal populations in this region would have interacted with a diverse cultural matrix not reflected in the more homogenous central highland groups.</p>",
    "37": "<p>Jether&rsquo;s sons and Ulla&rsquo;s sons close the Asherite sub-lists. The 26,000-warrior total for Asher is the smallest in ch7, reflecting either demographic reality (a smaller Asherite population) or the tribe&rsquo;s maritime/commercial rather than military orientation. Asher&rsquo;s position on the coast meant that military service was more relevant for defence against coastal raids than for the highland tribal conflicts that shaped the warrior culture of Issachar, Benjamin, and Ephraim.</p>",
    "38": "<p>Jether&rsquo;s three sons appear without further comment. Jephunneh as an Asherite name (also the name of Caleb&rsquo;s father) illustrates the circulation of prestige names across tribal boundaries. Caleb&rsquo;s father Jephunneh was a Kenizzite (non-Israelite), and his son Caleb was nonetheless a Judahite hero; names did not mark fixed ethnic or tribal identity but could cross those lines through adoption, marriage, or migration.</p>",
    "39": "<p>Ulla&rsquo;s three sons (Arah, Hanniel, Rizia) close the Asherite genealogy. Arah appears in the post-exilic returnee list (Ezra 2:5; Neh 7:10) as a family with 775 members, confirming that Asherite clan names survived into the Babylonian exile community and returned under Zerubbabel. The Chronicler&rsquo;s preservation of Asherite genealogical detail served this returning community&rsquo;s need to verify tribal credentials for land reallocation in the Persian period.</p>",
    "40": "<p>The closing formula for Asher (&ldquo;heads of ancestral houses, chosen men, mighty warriors, outstanding leaders; 26,000 enrolled for military service&rdquo;) is the most elaborated of the ch7 tribal summaries. The elevated language compensates for the tribe&rsquo;s small warrior count by emphasizing the quality of its leadership. Post-exilic Persian province administration required documented tribal affiliations for tax assessment, land allocation, and temple-service duty; the genealogical records the Chronicler compiled served as the constitutional foundation for the restored community.</p>"
  },
  "8": {
    "1": "<p>Benjamin&rsquo;s second extended genealogy in 1 Chronicles (the first was ch7:6&ndash;12) reflects the tribe&rsquo;s exceptional importance to the Chronicler. Benjamin&rsquo;s territory included Jerusalem (the capital), Gibeon (the pre-temple high place), Bethel (major cult site), Jericho (gateway to the Jordan), and Gibeah (Saul&rsquo;s hometown). No other tribe outside Judah had comparable significance for the post-exilic community, which explains why Benjaminite genealogy receives two separate treatments in these chapters.</p>",
    "2": "<p>Benjamin&rsquo;s five-son list here differs from Numbers 26:38&ndash;40 (also five sons, but different names) and Genesis 46:21 (ten sons). The discrepancies have generated extensive scholarly discussion. The most likely explanation is that the Chronicler and the Pentateuchal sources drew on different phases of a fluid genealogical tradition: the actual Benjaminite clan structure evolved over time, and different administrative moments produced different snapshots of the tribal record.</p>",
    "3": "<p>Bela&rsquo;s first-generation descendants (Addar, Gera, Abihud) begin the most extended Benjaminite sub-genealogy. The Benjaminite Gera name recurs across generations (v3, v5, v7) and in narrative contexts (Ehud son of Gera, Shimei son of Gera). In ancient societies, prestigious clan-ancestor names were recycled through generations as a way of claiming genealogical connection to a founding figure &mdash; a practice of name-memory that encoded social hierarchy in naming conventions.</p>",
    "4": "<p>Naaman, Ahoah, and Abishua continue Bela&rsquo;s descendants. The Benjaminite Naaman appears in Num 26:40; the same name was borne by the Syrian military commander healed by Elisha (2 Kgs 5). In the ancient Near East, Semitic personal names crossed ethnic and political boundaries freely; Naaman was an Israelite clan name, an Aramean general&rsquo;s name, and likely a common personal name in the wider Levantine population, not an identifier of a specific ethnic group.</p>",
    "5": "<p>The second Gera in Bela&rsquo;s list (v5 after v3) may represent a second son named in honor of an ancestor, the tribal practice of name-recycling noted above. Shephuphan is a variant of the Shupham/Muppim of the Pentateuchal lists (Num 26:39; Gen 46:21), confirming the lists&rsquo; partial overlap with shared sources.</p>",
    "6": "<p>The exile of Ehud&rsquo;s descendants to Manahath is otherwise unattested and has no Pentateuchal parallel. Manahath (modern Manahat, southwest of Jerusalem) was in Calebite-Judahite territory (2:52, 54); an intra-Israelite forced relocation of a Benjaminite sub-clan to Judahite territory could reflect political punishment after Saul&rsquo;s dynasty fell or an administrative reorganization under David. Geba, the origin point, was a border fortress between Benjamin and Ephraim (1 Sam 13:3); its population would have been strategically significant to monitor.</p>",
    "7": "<p>The syntactically difficult verse about Naaman, Ahijah, and Gera being &ldquo;removed&rdquo; may preserve a memory of internal displacement within Benjaminite territory &mdash; perhaps connected to the population movements that followed the Philistine wars of Saul&rsquo;s period. Archaeological surveys of the Benjaminite highlands show evidence of significant settlement disruption and rebuilding in the late Iron Age I period (early 10th century BCE), consistent with a period of population movement in this region.</p>",
    "8": "<p>Shaharaim&rsquo;s settlement in Moab and his Moabite second family is unique to Chronicles and has no parallel in the other biblical sources. Israelite diaspora communities in Moab are known from the Ruth narrative and from extra-biblical evidence: Moab&rsquo;s relatively stable agricultural conditions made it a refuge zone for Israelites during famines and political disruptions (Ruth 1:1). The Moabite Plateau east of the Dead Sea lay only a day&rsquo;s journey from the Benjaminite heartland via the Jericho ford.</p>",
    "9": "<p>Hodesh&rsquo;s seven sons reflect the social reality of polygamous households in the ancient Near East, where multiple wives from different regions produced children with diverse cultural backgrounds. A man who settled in Moab and took a Moabite wife would raise children with bilingual and bicultural formation. The sons&rsquo; elevation to &ldquo;heads of ancestral houses&rdquo; despite their mixed-diaspora origins reflects the genealogical pragmatism of the post-exilic period, when many returning families had acquired foreign spouses during the exile.</p>",
    "10": "<p>Jeuz, Sachia, and Mirmah close the Moabite-born line of Shaharaim. Post-exilic Ezra-Nehemiah controversies over foreign marriages (Ezra 9&ndash;10; Neh 13:23&ndash;27) make this genealogy of Moabite-born Benjaminite sons historically resonant: the Chronicler preserves the foreign-born line without editorial disapproval, whereas Ezra would have required these sons to divorce their foreign wives. The Chronicler&rsquo;s silence here may reflect a more inclusive attitude toward diaspora genealogies.</p>",
    "11": "<p>Elpaal, born to Hushim (Shaharaim&rsquo;s first wife, divorced before the Moabite period), becomes the main genealogical line in the following section. The detail that Shaharaim had pre-existing children by Hushim before the divorce and his Moabite period ensures that Elpaal&rsquo;s line is unambiguously Israelite by both parents, contrasting with the half-Moabite line of Hodesh&rsquo;s children. The genealogy preserves both lines without prioritizing either, reflecting the Chronicler&rsquo;s comprehensive archival approach.</p>",
    "12": "<p>Shemed building Ono and Lod places these post-exilic Benjaminite settlement towns in a deep genealogical tradition. Ono (modern Kafr Ana, near Lod/Ben Gurion Airport) and Lod (ancient Lydda, modern Lod) appear in Ezra 2:33 and Neh 7:37 as towns whose populations returned from Babylon under Zerubbabel. The &ldquo;valley of craftsmen&rdquo; (<em>Gê-hāḥarāšîm</em>) near these towns (Neh 11:35) suggests they became craft-production centres in the Persian period. Shemed&rsquo;s city-founding genealogy gave the returning settlers legitimate ancestral claims to these towns.</p>",
    "13": "<p>Beriah and Shema&rsquo;s expulsion of Gath&rsquo;s inhabitants at Aijalon points to ongoing conflict between Benjaminite groups and Philistine outposts in the Shephelah transition zone. The Aijalon valley (site of Joshua&rsquo;s famous sun-standing miracle, Josh 10:12) was a contested corridor between the Benjaminite highlands and the Philistine coastal plain. Archaeological evidence from Iron Age I sites in this valley shows destruction layers and evidence of shifting population control consistent with the kinds of local skirmishes recorded here.</p>",
    "14": "<p>Ahio, Shashak, and Jeremoth head the next Benjaminite cluster. The lists in vv14&ndash;27 register Benjaminite families who were &ldquo;leading men who lived in Jerusalem&rdquo; (v28). In the Persian-period context, Jerusalem&rsquo;s population was small (Neh 7:4: &ldquo;the city was wide and large, but the people within it were few&rdquo;), and the genealogical legitimation of Benjaminite residence in Jerusalem was socially important for the community that had settled there under Persian authorization.</p>",
    "15": "<p>Zebadiah, Arad, and Eder are sons of Beriah. Arad as a personal name in this Benjaminite list is geographically incongruous with Arad the southern Negev town (Num 21:1; Josh 12:14), suggesting the name was a common personal name independent of the geographic reference. Names from distant geographic locations circulated as personal names throughout the ancient Levant through trade contacts, prestige associations, and simple naming fashion.</p>",
    "16": "<p>Michael, Ishpah, and Joha are identified as sons of Beriah. The list of Berachiah&rsquo;s Benjaminite sons in these verses parallels the structure of similar lists from Ugaritic and Phoenician administrative texts, where clan organizations were registered with a chief name followed by sub-clan members. The Chronicler is reproducing a type of document well-attested in the ancient Near East: the household census of an elite family for administrative and inheritance purposes.</p>",
    "17": "<p>Zebadiah, Meshullam, Hizki, and Heber as sons of Elpaal continue the genealogical registration. Meshullam (&ldquo;rewarded/at peace with God&rdquo;) is one of the most common names in Ezra-Nehemiah: at least eleven different individuals bear this name in those books, reflecting the name&rsquo;s popularity in the post-exilic Persian-period community. Its appearance here in a pre-exilic Benjaminite genealogy shows the name had a history in Benjamin before the exile, making it a plausible post-exilic choice for honouring ancestors.</p>",
    "18": "<p>Ishmerai, Izliah, and Jobab close Elpaal&rsquo;s sons. Jobab appears twice in ch8 (also v9), consistent with the recycling of clan-names discussed earlier. The gathering of these Elpaalite and Shimei-descended names (vv17&ndash;21) into a dense register reflects the Chronicler&rsquo;s access to a comprehensive Benjaminite genealogical archive, possibly housed in the temple administration or in the family records of Jerusalem&rsquo;s leading families.</p>",
    "19": "<p>Jakim, Zichri, and Zabdi as sons of Shimei. The name Zichri (&ldquo;my memorial/remembrance&rdquo;) appears at least twelve times in the Hebrew Bible for different individuals, reflecting its widespread popularity as a name expressing the hope that a child would be remembered. In genealogical registers designed precisely to perpetuate family memory, a name meaning &ldquo;memorial&rdquo; is particularly apt &mdash; a self-referential choice that encodes the purpose of the document in a personal name.</p>",
    "20": "<p>Elienai, Zillethai, and Eliel are sons of Shimei. The density of El-compound names in this section (Elienai = &ldquo;my eyes to El/God&rdquo;; Eliel = &ldquo;El is my God&rdquo;; also Elishama and Elpelet nearby) reflects the naming fashion of the late monarchic and early post-exilic periods, when theophoric names using El rather than Yah became more prominent. This may reflect the influence of Babylonian El-compound names (Babylonian El = god) during the exile period.</p>",
    "21": "<p>Adaiah, Beraiah, and Shimrath close Shimei&rsquo;s line. The appearance of Adaiah in this Benjaminite list alongside its frequency in Ezra-Nehemiah contexts (Ezra 10:29, 39; Neh 11:5, 12) illustrates how the same names circulated in both the priestly-Levitical community and in the lay tribal registers. The shared naming pool of the post-exilic community reduced the social distance between priestly and lay families, reflecting the more egalitarian tendencies of the Persian-period Yehud community.</p>",
    "22": "<p>Ishpan, Eber, and Eliel are sons of Shashak. Eber appears twice in ch8 (also v12 as a son of Elpaal), illustrating the name recycling within this register. Eber as a clan name carries the association with the &ldquo;Hebrews&rdquo; (ʿiḇrî), the ethnic designation derived from Eber in Gen 10:21&ndash;25; its use in a Benjaminite administrative list anchors the tribe in the deep Semitic genealogical tradition.</p>",
    "23": "<p>Abdon, Zichri, and Hanan are sons of Shashak (continuing the list). The Abdon here shares a name with the judge of Pirathon in Ephraim (Judg 12:13&ndash;15). Judge names circulated across tribal boundaries because judges were charismatic leaders whose names gained prestige even outside their home territories. The Benjaminite Abdon&rsquo;s position in Jerusalem (v28) gives the name a royal-capital association alongside its northern-judge tradition.</p>",
    "24": "<p>Hananiah, Elam, and Antothijah as sons of Shashak. Elam as a personal name carries the association with Elam the ancient civilization east of Mesopotamia (Gen 10:22); Elamite mercenaries and traders were present in the ancient Near Eastern world, and the name Elam circulated in Hebrew usage as a memorial to that geopolitical awareness. Antothijah connects to Anathoth, the Benjaminite priestly town, providing another link between this Jerusalem Benjaminite register and the priestly tradition of that locality.</p>",
    "25": "<p>Iphedeiah and Penuel close Shashak&rsquo;s sub-list of eleven sons (vv22&ndash;25). Penuel (&ldquo;face of God&rdquo; &mdash; the name Jacob gave the site of his wrestling match, Gen 32:30) was also the name of a city in Transjordanian Gad (Judg 8:8&ndash;9, 17; 1 Kgs 12:25). Its use as a personal name in a Benjaminite Jerusalem family gives the theophanic site-name a domestic application: the child&rsquo;s name memorializes the divine encounter that marked Israel&rsquo;s national identity.</p>",
    "26": "<p>Shamsherai, Shehariah, and Athaliah are sons of Jeroham. The name Athaliah as a Benjaminite male personal name illuminates the gender-ambiguity of some Hebrew names: the same name was borne by Judah&rsquo;s queen (2 Kgs 11), who used a masculine name. This kind of gender-crossing in personal names was common in the ancient Levant, where a name&rsquo;s prestige or meaning could override gender conventions, especially in noble families seeking to honour an ancestor.</p>",
    "27": "<p>Jaareshiah, Elijah, and Zichri close Jeroham&rsquo;s line. Jeroham appears as a common name in both priestly (1 Chr 9:12; Neh 11:12) and lay Benjaminite contexts, illustrating the porous boundary between priestly families (who lived in Benjaminite cities like Anathoth and Gibeah) and lay tribal families in this region. The name Elijah (&ldquo;YHWH is my God&rdquo;) honours the Tishbite prophet&rsquo;s memory or reflects the same devotional declaration the prophet himself made (1 Kgs 18:36).</p>",
    "28": "<p>The summary designation of these families as &ldquo;heads of ancestral houses, leading men who lived in Jerusalem&rdquo; stakes a genealogical claim to the capital. In the Persian period, Jerusalem had a small but symbolically significant population; Nehemiah had to conduct a special registration (Neh 7:5&ndash;73) and then populate Jerusalem by lot (Neh 11:1&ndash;2) because the city was under-populated after the return from exile. The Chronicler&rsquo;s pre-exilic genealogy of Benjaminite Jerusalem residents provided the historical charter for this community&rsquo;s post-exilic residence claims.</p>",
    "30": "<p>The Gibeon patriarch&rsquo;s sons include Kish, who will become Saul&rsquo;s father (v33), along with Baal, Zur, Nadab, and Abdon. Gibeon (modern el-Jib, about 6 miles northwest of Jerusalem) was the largest of the Hivite-Gibeonite cities that tricked Joshua into a treaty (Josh 9). Its association with the Saul family grounds the first dynasty of Israel in the Gibeonite heartland &mdash; a connection that explains Saul&rsquo;s violent breach of the Gibeonite treaty (2 Sam 21:1) as a family-territorial conflict rather than purely a religious violation.</p>",
    "31": "<p>Gedor, Ahio, and Zacher are additional sons of the Gibeon patriarch. Gibeon&rsquo;s prominence as a religious centre before Jerusalem&rsquo;s temple was built is reflected in the &ldquo;great high place&rdquo; at Gibeon (1 Chr 16:39&ndash;40; 21:29; 1 Kgs 3:4) where the Mosaic tabernacle and altar were housed after the ark moved to Jerusalem. The Chronicler&rsquo;s attention to the Gibeonite genealogy here connects to the theological importance Gibeon holds in his narrative of the pre-temple cult.</p>",
    "32": "<p>Mikloth and his son Shimeah living in Jerusalem &ldquo;across from their kinsmen&rdquo; records the split residence of the Gibeonite-Saul family between Gibeon (the ancestral home) and Jerusalem (the capital). This dual-city attachment reflects the social reality of elite families in ancient capitals: maintaining a presence in both the ancestral hometown and the capital was a strategy for preserving both local clan authority and central political access. The Saulide line maintained Jerusalem connections even after the dynasty&rsquo;s fall.</p>",
    "33": "<p>Saul&rsquo;s family genealogy (Ner &rarr; Kish &rarr; Saul &rarr; Jonathan, Malchishua, Abinadab, Eshbaal) grounds Israel&rsquo;s first king in the Gibeonite-Benjaminite territory detailed in the preceding verses. The Chronicler&rsquo;s inclusion of the full Saulide genealogy despite Solomon&rsquo;s Davidic succession reflects the historical reality that Saulide descendants remained a significant Benjaminite family in the post-exilic period; denying their genealogy would have alienated a portion of the community the Chronicler sought to include in his all-Israel vision.</p>",
    "34": "<p>Jonathan&rsquo;s son Meribbaal (known in Samuel as Mephibosheth) and his son Micah represent the continuation of the Saulide line into the post-Davidic period. Jonathan&rsquo;s covenant of friendship with David (1 Sam 18:3&ndash;4; 20:16&ndash;17) created a special protected relationship between his descendants and the Davidic court; David honoured this covenant by restoring Meribbaal&rsquo;s family property and giving him a place at the royal table (2 Sam 9). The continuation of this line into multiple subsequent generations (vv35&ndash;40) demonstrates the covenant&rsquo;s durability.</p>",
    "35": "<p>Micah&rsquo;s sons (Pithon, Melech, Tarea, Ahaz) represent the first post-Jonathan generation of the surviving Saulide family. Their continued residence in Benjamin and their genealogical inclusion in the Chronicler&rsquo;s register suggests that by the post-exilic period, Saulide descendants had successfully integrated into the Benjaminite community without claiming political rights that would have made them threatening to the Davidic dynasty or the Persian administration.</p>",
    "36": "<p>The genealogy proceeds six generations beyond Jonathan to Azel&rsquo;s sons, placing the extended Saulide line in the Persian period or earlier. The name Azmaveth (&ldquo;death is strong&rdquo;) appears as a Davidic warrior (2 Sam 23:31) and as a town name near Jerusalem (Neh 12:29); the Saulide family&rsquo;s use of this name alongside the Davidic military tradition suggests the two families shared a common cultural naming pool even while representing different dynastic lines.</p>",
    "37": "<p>Rapha, Eleasah, and Azel continue the deep Saulide genealogy. The name Eleasah (&ldquo;God has acted/made&rdquo;) is a theophoric assertion of divine agency &mdash; the child&rsquo;s birth is attributed to God&rsquo;s intervention. In contexts where genealogical continuity was uncertain (as it must have been for a royal family stripped of political power), naming a child &ldquo;God has acted&rdquo; encoded hope for continued family survival under divine protection.</p>",
    "38": "<p>Azel&rsquo;s six sons include Obadiah (&ldquo;servant of YHWH&rdquo;) and Ishmael (&ldquo;God hears&rdquo;), reflecting the theophoric naming tradition of a family maintaining its YHWH-devotional identity despite political marginalisation. The assertion that all six are &ldquo;sons of Azel&rdquo; protects against genealogical challenges; in a period when genealogical records determined social standing and property rights, the legitimacy of each son required formal documentation.</p>",
    "39": "<p>Azel&rsquo;s brother Eshek and his three sons (Ulam, Jeush, Eliphelet) extend the genealogy to another branch of the post-Saulide family. The ordinal designations (firstborn, second, third) for Eshek&rsquo;s sons at this genealogical depth &mdash; many generations after Saul &mdash; suggests that inheritance order within the family was still formally tracked, perhaps because residual property rights or clan-head status attached to birth order even for non-royal families.</p>",
    "40": "<p>The closing note that Ulam&rsquo;s sons were &ldquo;mighty warriors and skilled archers with 150 sons and grandsons&rdquo; anchors the Saulide genealogy&rsquo;s conclusion in the tribe of Benjamin&rsquo;s most celebrated military tradition: archery. Benjamin&rsquo;s elite archers appear in the Deborah song (Judg 5:14: implied), the Gibeah war (Judg 20:16: 700 left-handed slingers), the Davidic service list (1 Chr 12:2: ambidextrous archers), and in Paul&rsquo;s own self-identification as a Benjaminite (Phil 3:5). The genealogy ends with 150 military descendants from Saul&rsquo;s line &mdash; a dynasty without a throne but with a continuing warrior tradition.</p>"
  }
}

def main():
    existing = load_comm('context', '1chronicles')
    merge_comm(existing, CHRONICLES)
    save_comm('context', '1chronicles', existing)
    total = sum(len(v) for v in CHRONICLES.values())
    print(f'1 Chronicles 7-8 context fill: {total} verses written.')

if __name__ == '__main__':
    main()
