"""
MKT Context Commentary — John chapters 1–2
Run: python3 scripts/zc-context-john-1-2.py

Source data used:
- data/interlinear/john.json
- data/translation/draft/mediating/john.json (MKT text for quoting)
- data/commentary/ellicott/john.json (philological notes, historical detail)

Key decisions in this range:
- "The Jews" (Ioudaioi) in John refers to the Jerusalem leadership/Sanhedrin throughout,
  not the Jewish people generally — this is standard Johannine usage
- The Logos concept is treated as having both Jewish (Targum memra, Wisdom literature)
  and Hellenistic (Stoic logos) resonance; John uses the convergence deliberately
- "Hour" language (2:4) is identified as Johannine shorthand for the Passion
- Temple cleansing dated c. AD 26–28 using the 46-year construction reference (Josephus)
- "Woman" as an address (2:4) is noted as honorific, not dismissive — same form used
  at 19:26 from the cross
- Mary's "do whatever he tells you" is flagged against the LXX of Gen 41:55 (Pharaoh/Joseph)
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

JOHN = {
  "1": {
    "1": '<p>The opening words <em>ἐν ἀρχῇ</em> — "in the beginning" — are a deliberate echo of Gen 1:1. A Jewish reader would hear Bereshit, the Hebrew name for the book of Genesis itself. The Evangelist is placing the Logos within the creation narrative familiar to every synagogue-goer.</p><p>The Logos concept carried dual resonance. In Jewish tradition, the divine Word (Heb. <em>dāvār</em>; Aram. <em>memrā</em>) was the agent through which God acted in the world — the Targums (Aramaic paraphrases of the Torah) regularly substitute "the Memra of the LORD" where the Hebrew has God acting directly. In Hellenistic philosophy, the Logos was the rational principle ordering the cosmos. John uses the convergence, but grounds the Word in Jewish creation, not Stoic cosmology.</p>',
    "2": '<p>The summary assertion — "He was with God in the beginning" — closes the prologue\'s opening triad by re-anchoring the Word\'s pre-incarnate existence. In Second Temple Wisdom literature (Prov 8:22–30; Wis 9:9), Wisdom is personified as present beside God before creation. John writes in conscious dialogue with this tradition, but now identifies the personal pre-incarnate Word rather than an abstract divine attribute.</p>',
    "3": '<p>Creation through the Word echoes Ps 33:6 — "By the word of the LORD the heavens were made" — and the wisdom tradition of Prov 8:30 and Wis 7:21, where Wisdom is "the fashioner of all things." The rabbinic concept of Torah as the blueprint of creation (b.Shabbat 88b) parallels the idea: God spoke the world into existence; that speaking was the divine Word. John\'s claim is not philosophical novelty but the identification of the pre-existent Logos with the God who created at Sinai and spoke through the prophets.</p>',
    "4": '<p>Light (φῶς) carried immediate resonance in Jewish thought. Torah was "a lamp to my feet and a light to my path" (Ps 119:105); Wisdom shone "more brightly than the sun" (Wis 7:29). The Temple Menorah — the seven-branched lampstand — symbolized God\'s light dwelling among Israel. By calling the Word "the light of men," the Evangelist signals that the one in whom Torah, Wisdom, and the Temple\'s light converge has now appeared in person.</p>',
    "5": '<p>The Greek <em>κατέλαβεν</em> carries two senses: "comprehended/grasped" (intellectually) and "overcome/seized" (physically). Both readings are intentional — the darkness neither understood nor overpowered the light. The imagery of cosmic conflict between light and darkness was vivid in Second Temple Judaism: the Dead Sea Scrolls (1QM, the War Scroll) describe history as the battle of the Sons of Light against the Sons of Darkness. John\'s audience would hear an eschatological register: the darkness has been pressing against the light throughout history and has failed.</p>',
    "6": '<p>The name Yōḥānān ("YHWH is gracious") was common in first-century Judaism. More significant is the formula <em>ἀπεσταλμένος παρὰ θεοῦ</em> — "sent from God" — which echoes the commissioning language of the prophets (Isa 6:8; Jer 1:7; Ezek 2:3). By this phrase the Evangelist places John the Baptist squarely in the prophetic tradition that Israel had been waiting to see renewed after four centuries of silence.</p>',
    "7": '<p>Jewish legal tradition required two witnesses to establish a fact in court (Deut 17:6; 19:15). The Evangelist introduces John explicitly as a witness (<em>μάρτυς</em>), deploying legal vocabulary that would alert Jewish readers: this testimony is being given under covenantal-legal conditions. John\'s Gospel will continue to marshal witnesses — the Father, the scriptures, the signs — in what amounts to a formal legal case for Jesus\'s identity.</p>',
    "8": '<p>The sharp denial that John was the Light reflects a live historical tension. John the Baptist attracted enormous followings; some of his disciples apparently venerated him with near-messianic status (Acts 18:24–19:7). A tradition preserved in the Pseudo-Clementines shows the Baptist sect persisted for generations. The Evangelist is writing to clarify the Baptist\'s own self-understanding: witness, not protagonist.</p>',
    "9": '<p>The adjective <em>ἀληθινόν</em> — "true/genuine" — distinguishes the real from the merely symbolic or anticipatory. In Second Temple Judaism, the Menorah was the true light in the Temple; Torah was the true light for the path. John\'s point is that these were genuine but preparatory. The one who gives light to every person — not just Israel — exceeds every prior anticipation in scope and substance.</p>',
    "10": '<p>The irony the Evangelist constructs here is deliberate and carries weight in Jewish wisdom tradition. In 1 Enoch 42:2, Wisdom sought a dwelling among the children of men but "found no dwelling-place," so she returned to her place in heaven. John shapes this motif around the incarnate Word: the Wisdom/Word who made the world came to the world and was not recognized. The "world" here begins to narrow toward its Johannine meaning of the human order organized in opposition to God.</p>',
    "11": '<p>The double use of <em>ἴδιος</em> distinguishes "his own domain" (the created world, especially Israel) from "his own people" (Israel specifically). Israel was God\'s <em>segullāh</em> — special possession (Ex 19:5; Deut 14:2). The covenant framework makes the rejection doubly significant: it is not random unbelief but the covenant people refusing their covenant Lord. The Evangelist does not linger on blame but will return to this theme throughout the Gospel.</p>',
    "12": '<p>In the OT, Israel collectively was called God\'s son (Ex 4:22; Hos 11:1; Deut 14:1). Individual Israelites shared in this corporate sonship. The Qumran community called themselves "sons of light" and "sons of God." John now opens this status to individuals who believe — not by descent or community membership but by receiving the Word. The term <em>τέκνα θεοῦ</em> (children of God) uses the relational word for children rather than the formal-legal word for sons (<em>υἱοί</em>), emphasizing genuine birth rather than adoption.</p>',
    "13": '<p>The contrast "not of blood, nor of the will of the flesh, nor of the will of man, but of God" targets the Jewish priority given to genealogical descent. Priestly families traced lineage meticulously; the Davidic line was preserved. The claim that divine birth transcends all three human channels of descent — racial, physical, and patriarchal will — was a cultural provocation. Spiritual rebirth cannot be inherited or decided; it is God\'s act.</p>',
    "14": '<p>The verb <em>ἐσκήνωσεν</em> — "tabernacled/pitched his tent" — directly evokes the Tabernacle (Heb. <em>mishkān</em>, from <em>shākan</em>, "to dwell"). The Shekinah glory dwelt in the Tabernacle and later in Solomon\'s Temple. When the disciples "beheld his glory" (<em>ἐθεασάμεθα τὴν δόξαν</em>), the vocabulary is that of the divine <em>kāvôd</em> — the glory-cloud that filled the Tabernacle at its dedication (Ex 40:34–35) and the Temple (1 Kgs 8:10–11). The Evangelist\'s claim is precise: the dwelling of God with his people, which the Tabernacle and Temple enacted as anticipation, has now occurred in flesh.</p>',
    "15": '<p>The paradox "he who comes after me existed before me" inverts the Jewish honor code: age and chronological priority conveyed authority and status. A younger man deferring to an older was expected; the reverse required extraordinary justification. John the Baptist publicly subordinates himself to a figure who entered public ministry after him, on the grounds of the younger figure\'s pre-existence. This claim would have struck first-century hearers as extraordinary rather than natural piety.</p>',
    "16": '<p>The phrase <em>χάριν ἀντὶ χάριτος</em> — "grace upon grace" or "grace in place of grace" — is dense. The preposition <em>ἀντί</em> can mean "in exchange for" or "on top of." Some read this as the new covenant\'s grace replacing the Mosaic covenant\'s grace; others as an accumulation. The Targum tradition used <em>ḥesed</em> (covenant-loyalty, typically rendered "grace/mercy") in accumulating patterns. The Evangelist\'s point is that the fullness of the Word overflows into his people without exhaustion.</p>',
    "17": '<p>The contrast Moses/Law vs. Christ/grace-and-truth is not abolition but fulfillment. Torah was the supreme framework of Jewish identity and life. The Law-Moses axis organized synagogue worship, festivals, purity, ethics, and eschatology. To say that grace and truth "came through Jesus Christ" — the only place in the Prologue where the full name appears — is to place the incarnate Word as the telos toward which Mosaic revelation was pointing. The gift of the Law was real; the fullness of what it signified is the gift of the Son.</p>',
    "18": '<p>The tradition that no one can see God and live (Ex 33:20–23; Isa 6:5) was axiomatic in Judaism. Moses was the supreme mediator who saw God "face to face" (Ex 33:11), yet even he was shown only God\'s back (Ex 33:23). Isaiah saw God\'s throne and was undone (Isa 6:1–5). The "only-begotten God" (the better-attested reading, <em>μονογενὴς θεός</em>) who is "in the bosom of the Father" — the place of supreme intimacy at a reclining meal — has now <em>ἐξηγήσατο</em> (exegeted/narrated) the Father. John claims: what Moses could not fully receive, what Isaiah glimpsed from a distance, the Son has directly communicated.</p>',
    "19": '<p>The term "the Jews" (<em>Ἰουδαῖοι</em>) in John\'s Gospel typically refers to the Jerusalem religious leadership rather than the Jewish people broadly. The dispatch of priests and Levites from Jerusalem signals official institutional inquiry: this is not grassroots curiosity but a formal Sanhedrin investigation of a religious phenomenon in their jurisdiction. The priestly and Levitical classes were the institutional guardians of Temple worship and Torah interpretation.</p>',
    "20": '<p>John\'s emphatic denial is stylistically striking: "He confessed, and did not deny, but confessed" — the triple structure mirrors Jewish legal affirmation. Messianic expectation was running at high pitch in the first century: the Roman occupation, apocalyptic literature (4 Ezra, 2 Baruch, 1 Enoch), and Qumran scrolls all evidence intense hope for a deliverer. That the delegation needed to ask — and that John needed to deny forcefully — shows how credible the attribution of messianic status to the Baptist had become in his own lifetime.</p>',
    "21": '<p>The two questions reflect specific Second Temple messianic typologies. Elijah\'s return was promised in Mal 4:5 and anticipated in Sirach (48:10); many expected a literal reappearance. "The Prophet" (<em>ὁ προφήτης</em>) refers to the eschatological prophet like Moses promised in Deut 18:15–18. The Qumran community expected both a priestly Messiah and a prophetic Messiah alongside a royal one (1QS 9:11). John\'s three denials exhaust the standard messianic-figure categories of the day.</p>',
    "22": '<p>The delegation\'s insistence reflects institutional accountability: they were official envoys who could not return to the Sanhedrin empty-handed. In Jewish legal and social custom, a messenger who failed to obtain the required answer had failed his commission. Their pressure on John to produce a definitive self-identification is procedurally appropriate.</p>',
    "23": '<p>John applies Isa 40:3 to himself: "A voice of one calling in the wilderness: Make straight the way of the Lord." The Qumran community had applied the same verse to their own desert withdrawal (1QS 8:12–14), understanding their life of Torah study in the desert as "preparing the way." John\'s use of the text claims the same prophetic vocation but points away from himself toward the Coming One. His self-description — not a person but a voice — radically de-centers his own identity.</p>',
    "24": '<p>The Pharisees were one of the major Second Temple sects, distinguished by their oral tradition (the "traditions of the elders") as a fence around Torah, their belief in resurrection, and their concern for purity in everyday life. Their involvement in the investigation signals that the Baptist\'s practice raised not just political but halakic (legal-religious) concerns: what authority permitted him to baptize?</p>',
    "25": '<p>Jewish proselyte baptism (ritual immersion for Gentile converts to Judaism) likely predates John, though its pre-Christian attestation is debated. The Baptist\'s innovation was applying a purification ritual normally reserved for Gentile entry into the covenant to Jews already within it — an implied judgment that Israel had become spiritually estranged from God and required re-entry. This was not merely unusual; it was a prophetic statement about Israel\'s condition.</p>',
    "26": '<p>The idea of a hidden or unknown Messiah was alive in Second Temple thought. Some traditions held the Messiah would be concealed until his appointed time (4 Ezra 13:52; 1 Enoch 62:7). John\'s statement — "among you stands one you do not know" — activates this register deliberately: the One for whom Israel has been waiting is already present, unrecognized, standing in their midst at this very moment of official inquiry.</p>',
    "27": '<p>Rabbinic tradition held that a student should not perform the most servile tasks even for his own teacher — specifically, that untying sandals was beneath a disciple\'s duty (b.Ketubbot 96a: "Every service that a slave performs for his master, a student should perform for his teacher, except for removing his shoe"). John claims he is not worthy of even this forbidden threshold of humility. The honor-shame logic is inverted: the greater the Baptist\'s public standing, the more complete his self-subordination signals the magnitude of the one to come.</p>',
    "28": '<p>The location "Bethany beyond Jordan" (not the Bethany near Jerusalem) places John\'s baptizing ministry on the east side of the Jordan River, in the region of Perea. Geographically and typologically, this evokes Joshua\'s crossing of the Jordan into the Promised Land (Josh 3–4). That John baptizes in the Jordan — the entry point of Israel into the land — gives his ministry the character of a new-exodus preparation.</p>',
    "29": '<p>The title "Lamb of God" (<em>ὁ ἀμνὸς τοῦ θεοῦ</em>) activates a cluster of Jewish sacrificial registers simultaneously. The Passover lamb (Ex 12:3–13) whose blood averted judgment; the daily <em>tāmîd</em> sacrifice (Ex 29:38–42; Num 28:1–8) offered morning and evening for Israel\'s sins; and the Suffering Servant of Isa 53:7 "led like a lamb to the slaughter" — all converge in the Baptist\'s cry. John is not making an abstract theological claim but identifying Jesus within the sacrificial vocabulary that structured Jewish worship. The phrase "takes away the sin of the world" (<em>αἴρων τὴν ἁμαρτίαν τοῦ κόσμου</em>) extends Isa 53\'s servant-substitution to a scope beyond Israel.</p>',
    "30": '<p>The statement "a man who comes after me surpassed me because he existed before me" deploys the honor-shame logic of chronological priority. In Jewish culture, the one who came first in time had precedence; a younger person deferring to a younger was culturally anomalous. John publicly grants priority to Jesus on the grounds of preexistence — a claim about ontological status, not chronological sequence, that would have required explanation even for a sympathetic Jewish audience.</p>',
    "31": '<p>The Baptist\'s claim "I did not know him" is striking because John and Jesus were relatives (Lk 1:36). The statement clarifies that the identification of Jesus as the Coming One came through divine revelation — specifically the sign of the descending Spirit — not through family acquaintance. This matters for Jewish legal purposes: the Baptist\'s testimony is that of a Spirit-designated witness, not a kinsman testifying on behalf of a relative.</p>',
    "32": '<p>The dove imagery carries a specific resonance: the rabbinic tradition saw the Spirit hovering over the waters in Gen 1:2 as like a dove brooding over its young (b.Hagigah 15a; Gen. Rab. 2:4). John\'s testimony that the Spirit "descended like a dove and remained" (ἔμεινεν) on Jesus is theologically loaded. A temporary prophetic anointing was common in the OT; the Spirit would come upon and depart from figures like Saul (1 Sam 10:10; 16:14). Permanent indwelling — the Spirit remaining — signals the anointing of the eschatological Messiah, the one on whom the Spirit rests without departure (Isa 11:2; 61:1).</p>',
    "33": '<p>The contrast "baptizing with water" vs. "baptizing with the Holy Spirit" corresponds to the eschatological expectation of Ezek 36:25–27, where God promises to sprinkle clean water on Israel and put his Spirit within them as the sign of the new covenant. John\'s water baptism is explicitly preparatory, pointing toward the Spirit-baptism that the Messiah would bring — the fulfillment of the prophetic promise that distinguishes the new covenant from Sinai.</p>',
    "34": '<p>"Son of God" was a title with layered meanings in Second Temple Judaism. Applied to Israel collectively (Ex 4:22), to the Davidic king at his coronation (Ps 2:7; 2 Sam 7:14), and to heavenly beings (Job 1:6; Dan 3:25), it designated a relationship of special appointment or nature. John\'s testimony applies the title to Jesus as the one the Spirit has permanently anointed — carrying all the prior registers but exceeding them in kind.</p>',
    "35": '<p>The scene of John standing with two disciples recalls the rabbinic pattern of a teacher surrounded by his disciples (talmidim). Disciples attached themselves to a teacher to learn his way of life (halakah), not merely his teachings. The transfer that follows — disciples leaving one teacher for another — was unusual and required the outgoing teacher\'s implicit permission, which the Baptist gives by pointing rather than retaining.</p>',
    "36": '<p>John\'s fixed, intent gaze (<em>ἐμβλέψας</em>) upon Jesus as he walks, and then his reiteration of "the Lamb of God," functions as a rabbinic pointing-gesture: the teacher redirects the student\'s attention to the one who surpasses him. The repetition of the Lamb title from v.29 underscores that this is not spontaneous but deliberate re-direction: the students should follow the Lamb, not the voice.</p>',
    "37": '<p>The disciples\' silent movement after Jesus, without a word being recorded, is consistent with the rabbinic convention of discipleship: a talmid followed his teacher\'s movements and absorbed his way of life through proximity, not only through formal instruction. The shift from John to Jesus is effected without drama precisely because John has already assigned the proper direction.</p>',
    "38": '<p>The form of address <em>Ῥαββί</em> — preserved in its Aramaic form — means "my great one" or "master," the standard honorific for a recognized teacher. The Evangelist translates it for his Greek-reading audience, indicating distance from the Galilean context. The disciples\' question "where are you staying?" (<em>μένεις</em>) uses the Johannine keyword for "abiding" — a term John will develop as the central metaphor of union with Christ in chapters 15–17. The question is simple but the word choice is already charged.</p>',
    "39": '<p>The note that it was "about the tenth hour" — roughly 4 p.m. in Jewish timekeeping — is the kind of eyewitness detail that would not be invented. Late afternoon visits typically extended into the evening meal; spending the day with Jesus would have included shared hospitality, the marker of covenant friendship in Jewish culture.</p>',
    "40": '<p>Andrew\'s Greek name among a Galilean Jewish family reflects the pervasive Hellenistic influence on Galilee. The region\'s mixed population — "Galilee of the Gentiles" (Isa 9:1; Matt 4:15) — made Greek a common second language alongside Aramaic. Jewish families in Galilee often gave children both a Hebrew and a Greek name, or simply Greek names. This cultural detail grounds the narrative in a real social world.</p>',
    "41": '<p>The word <em>Μεσσίαν</em> — preserved in its Hebrew/Aramaic form — means "the Anointed One." Anointing consecrated priests (Ex 29:7), kings (1 Sam 16:13), and occasionally prophets (1 Kgs 19:16) in the OT. By the Second Temple period, "the Messiah" had become the expected figure who would anoint all three offices in himself, deliver Israel, and usher in the age of God\'s reign. Andrew\'s announcement to his brother carries the weight of fulfilled longing: the one for whom Israel has been waiting is found.</p>',
    "42": '<p>Name changes in the OT marked covenantal transitions and new identities: Abram became Abraham (Gen 17:5), Sarai became Sarah (Gen 17:15), Jacob became Israel (Gen 32:28). Jesus\'s renaming of Simon as Cephas (Aram.) / Petros (Gk.) — "Rock" — follows this pattern. The renaming is not merely a nickname but a prophetic act establishing Simon\'s future identity and role in the community that will be built on this "rock" (Matt 16:18).</p>',
    "43": '<p>Philip\'s Greek name in a Jewish Galilean setting again reflects Hellenistic influence. The command "Follow me" (<em>ἀκολούθει μοι</em>) was the standard formula by which a rabbi recruited a disciple in the rabbinic tradition. The difference between Jesus and other rabbis is significant: typically disciples chose their rabbi; here the rabbi chooses his disciples, initiating the relationship from above.</p>',
    "44": '<p>Bethsaida ("house of fishing") was on the northeastern shore of the Sea of Galilee, near the tetrarchy of Philip (son of Herod the Great). Its location made it a border town between Jewish and Gentile territories — a detail consistent with the Greek-named disciples (Andrew, Philip) coming from there. The geographic note is Ellicott\'s kind of eyewitness detail — the sort of specific place-memory that does not travel well in legend.</p>',
    "45": '<p>Philip\'s announcement echoes Andrew\'s in v.41 but with an important addition: "the one Moses wrote about in the Law, and the prophets also wrote about." The standard Jewish canon reference — Torah and Prophets (Neviim) — stakes the broadest possible claim: the entire scriptural tradition pointed toward this person. The reference to Moses writing about Jesus would be heard by Jewish readers against Deut 18:15–18 (the prophet like Moses) and perhaps the entire sacrificial/exodus typology embedded in the Pentateuch.</p>',
    "46": '<p>Nazareth\'s reputation was shaped by its obscurity: the town appears nowhere in the OT, the Apocrypha, or Josephus, suggesting it was a recent or unremarkable settlement. Galilee generally was looked down upon by Jerusalem — regarded as less observant, more Gentile-influenced, and therefore less authoritative (Jn 7:52). Nathanael\'s skepticism reflects genuine regional prejudice: no prophet was expected to arise from an unknown Galilean village (Jn 7:41–42). Philip\'s answer — "Come and see" — is the only appropriate response to evidence rather than argument.</p>',
    "47": '<p>Jesus\'s description of Nathanael as "a true Israelite in whom there is nothing false" plays on the double meaning of Israel. The patriarch Jacob/Israel was known for cunning and deception (Gen 27; 30:37–43); his wrestling with God and transformation into Israel represented the complex character of the covenant people. Jesus calls Nathanael the genuine Israel — one without <em>δόλος</em> (guile/deceit) — implicitly contrasting him with the patriarch\'s original character. The compliment is simultaneously a theological point about authentic covenant membership.</p>',
    "48": '<p>Sitting or resting under a fig tree was a common image of peace, security, and Torah study in Jewish life (1 Kgs 4:25; Zech 3:10; Mic 4:4). The phrase carried connotations of a contemplative, studious piety — the ideal of the observant Jew at rest in God\'s provision. Jesus\'s supernatural knowledge of Nathanael\'s location before Philip called him — before any human communication — demonstrates omniscience in a context where that attribute was reserved exclusively for God (1 Kgs 8:39; Ps 7:9; Jer 17:10).</p>',
    "49": '<p>Nathanael\'s double confession — "Son of God" and "King of Israel" — assembles the two primary streams of messianic expectation. "Son of God" echoes Ps 2:7 (the royal enthronement psalm) and 2 Sam 7:14 (the Davidic covenant). "King of Israel" was the political messianic title — the expected Davidic restorer who would re-establish Israel\'s sovereignty. Both titles appear together in Second Temple expectation (4Q246; Ps Sol 17:32) but are usually applied sequentially or in separate strands; Nathanael\'s immediate juxtaposition of them signals that Jesus has collapsed the distance between these figures.</p>',
    "50": '<p>Jesus\'s reply sets up the promise of "greater things" by implying that seeing him under the fig tree was only the beginning of a divine knowledge that will be progressively disclosed. In the rabbinic tradition, the greater always displaces and fulfills the lesser; a student who surpasses his teacher is a sign that the teaching was sound. Here the pattern runs in reverse: the teacher promises the student will see more than what convinced him, drawing him into deeper revelation.</p>',
    "51": '<p>The vision of angels ascending and descending recalls Jacob\'s dream at Bethel (Gen 28:10–17), where a ladder (<em>sullām</em> — possibly a ramp or staircase) connected heaven and earth, and angels moved upon it. Jacob awoke and declared "This is the gate of heaven." Jesus applies the vision to himself: he is the point of contact between heaven and earth, the true Bethel ("house of God"). The "Son of Man" title invokes Dan 7:13 — the heavenly figure who receives universal dominion — making this the first appearance of John\'s favorite christological title. The double <em>ἀμήν</em> formula ("verily, verily") is unique to John\'s Gospel and always introduces a solemn declaration from Jesus himself.</p>'
  },
  "2": {
    "1": '<p>"On the third day" carries resonance in Jewish idiom. The third day was the day of theophany at Sinai (Ex 19:16), of divine action after mourning (Hos 6:2), and would become the day of resurrection. Weddings in Galilee typically lasted seven days and were the central community celebration of the village — a public event requiring extensive hospitality. Cana was a small Galilean village close to Nazareth.</p>',
    "2": '<p>That Jesus and his disciples were invited situates them within normal village social networks. In an honor-shame culture, receiving an invitation to a wedding was a mark of respect; accepting obligated the guests to appropriate honor-giving behavior toward the host. The presence of Jesus\'s disciples as a group (not just himself) underscores that the early community around Jesus was treated as a social unit in Galilean village life.</p>',
    "3": '<p>Running out of wine at a wedding was a serious social crisis in the ancient Mediterranean honor-shame world. The host\'s reputation — and the reputation of the entire family — was at stake in providing adequate hospitality for the full duration of the feast. Hospitality failure was not merely embarrassing; it could damage family honor for a generation. Mary\'s intervention reflects both her knowledge of Jesus\'s capacity and her role as a respected figure in the household.</p>',
    "4": '<p>The address <em>γύναι</em> ("woman") is often misread in English as cold or dismissive. It is, in fact, an honorific form — the same word Jesus uses from the cross to commend his mother to the Beloved Disciple (Jn 19:26). In Greek formal address it carries dignity, not distance. The phrase "my hour has not yet come" (<em>οὔπω ἥκει ἡ ὥρα μου</em>) introduces a Johannine keyword: "the hour" consistently refers to Jesus\'s Passion, death, and glorification (7:30; 8:20; 12:23; 17:1). Every use of this phrase until chapter 12 reminds the reader that each earlier act of revelation is not yet the culminating moment.</p>',
    "5": '<p>Mary\'s instruction to the servants — "Do whatever he tells you" — echoes the LXX of Gen 41:55, where Pharaoh tells the Egyptians in the famine: "Go to Joseph; do whatever he tells you." The verbal parallel positions Jesus as a new Joseph, the provider of what is lacking when human resources fail. Mary\'s confidence that Jesus will act, despite his apparent deflection, reflects an understanding of his capacity that surpasses what his public ministry has yet shown.</p>',
    "6": '<p>Six stone water jars for Jewish purification rites: Levitical law required ritual hand-washing before meals and between courses (Mk 7:3–4). Stone vessels were preferred because, unlike clay vessels, they could not contract ritual impurity under Levitical law (Lev 11:33). Their large capacity (20–30 gallons each, totaling 120–180 gallons) signals a household prepared for extended Passover-season hospitality. Six — one less than the symbolic complete number seven — may carry significance: the vessels of the old order, full but not yet complete.</p>',
    "7": '<p>The command to fill the jars to the brim (<em>ἕως ἄνω</em> — "up to the top") leaves no space for adding wine later — a detail that demonstrates the miracle\'s integrity. The servants\' willing obedience creates the material basis for the sign. In John\'s narrative economy, obedient action precedes manifestation: those who obey see; those who demand signs before obedience do not (cf. 2:18–19).</p>',
    "8": '<p>The <em>ἀρχιτρίκλινος</em> — "master of the banquet" (literally "ruler of the three couches" or "head of the dining room") — was a recognized official at Greco-Roman meals, responsible for arranging the seating, ordering the courses, and ensuring wine quality. His role at a Galilean Jewish wedding reflects the cultural fusion of the region: Hellenistic banquet customs adopted into Jewish village life. His ignorance of the miracle\'s source is part of the Evangelist\'s characteristic irony.</p>',
    "9": '<p>The knowledge asymmetry between the servants and the master of the banquet is a Johannine irony pattern: those at the social margins (the servants) know what the official overseer does not. This pattern will repeat throughout the Gospel — the blind man who was healed knows what the Pharisees cannot see (ch.9); the disciples who were present understand what the authorities miss. Divine action is disclosed to those who are present and obedient, not necessarily to those with institutional authority.</p>',
    "10": '<p>The master\'s observation about wine-serving protocol — good wine first, inferior wine after the guests have drunk freely — reflects actual Greco-Roman banquet practice attested in ancient sources (Pliny, Plautus). It was common knowledge. His puzzlement at the reversal implies that Cana has broken the expected order: the best wine, the wine of abundance, has come last. Rabbinic tradition sometimes described the messianic age as a banquet with the finest aged wines (Isa 25:6; b.Berakhot 34b). The sign encodes this expectation without announcing it.</p>',
    "11": '<p>John uses <em>σημεῖον</em> (sign) rather than <em>δύναμις</em> (power/miracle) throughout his Gospel. Signs point beyond themselves — they are revelatory events that disclose who Jesus is. The disciples\' belief (<em>ἐπίστευσαν</em>) is the intended response. The note that this was "the first of the signs" makes explicit what the Prologue has prepared: the ministry of Jesus is the unfolding of the Word\'s self-disclosure, each sign adding another dimension of revelation.</p>',
    "12": '<p>Capernaum on the Sea of Galilee became Jesus\'s base of operations in Galilee (Matt 4:13 calls it "his own city"). The brief stay "a few days" before the Passover pilgrimage is a narrative hinge. The mention of Jesus\'s brothers alongside his disciples and mother reflects the household structure of the early community — a family-and-followers unit that would remain somewhat intact until at least John 7:3–5, when the brothers are still unbelieving.</p>',
    "13": '<p>The Passover (<em>πάσχα</em>) was one of the three pilgrimage festivals (along with Pentecost and Tabernacles) requiring all adult male Jews within reasonable distance to appear in Jerusalem (Ex 23:17; Deut 16:16). During Passover week, Jerusalem\'s population swelled from perhaps 40,000–60,000 to hundreds of thousands. Josephus (War 2.14.3) gives an exaggerated figure, but the density was genuine. The festival commemorated the Exodus and carried intense national and eschatological significance — expectations of a new exodus or divine intervention ran highest at Passover.</p>',
    "14": '<p>The commercial activities Jesus found in the Temple courts — specifically the Court of the Gentiles, the outermost enclosure accessible to non-Jews — were practically necessary: pilgrims who traveled from outside Judea could not bring large animals; certified sacrificial animals had to be sold on-site. Roman coinage bore the image of Caesar (graven image) and was considered unsuitable for the Temple tax, which required Tyrian shekels; money-changers provided the exchange at a fee. The trade was dominated by the family of Annas, the former high priest, whose control of Temple commerce was a known source of corruption (cf. Josephus, <em>Ant.</em> 20.9.2).</p>',
    "15": '<p>Jesus\'s action — driving out the animals, scattering coins, overturning tables — follows the form of a prophetic symbolic act. The OT prophets performed dramatic public acts of judgment: Jeremiah smashed a pot in the Valley of Hinnom (Jer 19), Ezekiel lay on his side for 390 days (Ezek 4). Such acts were recognized as prophetic speech-acts, not merely personal protests. The whip of cords is not punitive toward persons but coercive toward animals — a shepherd\'s or farmer\'s implement used to move livestock.</p>',
    "16": '<p>The claim "my Father\'s house" (<em>τοῦ οἴκου τοῦ πατρός μου</em>) asserts Jesus\'s unique relationship to God and his authority over the Temple. This is not the language of general piety ("our Father\'s house") but of unique sonship. Those present at the Passover twelve years earlier — when the twelve-year-old Jesus claimed God as his "Father" in the Temple (Lk 2:49) — would recognize the recurring assertion. The Temple authorities certainly would not have missed the claim\'s implication.</p>',
    "17": '<p>The disciples\' recollection of Ps 69:9 — "Zeal for your house will consume me" — is the Gospel\'s first explicit use of OT scripture in connection with Jesus\'s actions. Psalm 69 is one of the most frequently cited psalms in the NT passion narratives (Jn 19:28–29; Matt 27:34; Rom 15:3). The disciples connect the Temple action not merely to prophetic zeal but to the cost at which that zeal will be paid — the future tense of the LXX ("will consume me") pointing forward to Jesus\'s death as the consequence of his challenge to the Temple establishment.</p>',
    "18": '<p>The demand for a sign (<em>σημεῖον</em>) from the religious authorities follows the procedure established in Deut 18:21–22 for evaluating prophetic claims: if a prophet gives a sign that comes true, he may be from God. Pharisaic theology placed particular weight on signs as authentication (1 Cor 1:22 — "Jews demand signs"). The request is not unreasonable within its framework, but it misses the nature of Jesus\'s authority: he does not require their validation because his authority precedes their institution.</p>',
    "19": '<p>The Temple (<em>ναός</em> — the inner sanctuary, not the whole complex) Jesus refers to is the building Herod began reconstructing around 20/19 BC. His enigmatic saying "Destroy this temple and in three days I will raise it" would have been heard as a blasphemous claim against the supreme sacred site of Judaism — and would be used as evidence against him at his trial (Matt 26:61; Mk 14:58). The saying functions as a Johannine sign-in-advance: what seems like a ridiculous claim will be understood only after the resurrection.</p>',
    "20": '<p>The forty-six years of construction gives a chronological anchor. Josephus (<em>Ant.</em> 15.11.1) dates Herod\'s commencement of the Temple project to his eighteenth regnal year (c. 20/19 BC). Forty-six years later places the scene around AD 27–28, consistent with a ministry beginning near the start of Pontius Pilate\'s prefecture (AD 26–36). The building was not completed until AD 64 — just six years before its destruction. The authorities\' bewilderment is legitimate: what Jesus describes is architecturally inconceivable.</p>',
    "21": '<p>The Evangelist\'s interpretive aside — "the temple he spoke of was his body" — is offered with the full hindsight of post-resurrection faith. This identification is not an isolated metaphor: it connects to the Prologue\'s claim that the Word "tabernacled among us" (1:14), to Jesus\'s later declaration that he is the true temple replacing the Jerusalem sanctuary (4:21–24), and to the Pauline language of the church as temple (1 Cor 3:16; 2 Cor 6:16). The locus of divine presence has shifted from stone to flesh.</p>',
    "22": '<p>The pattern of "not understanding now, understanding after the resurrection" is characteristic of John\'s narrative method. It reflects actual early Christian experience: the resurrection was the hermeneutical key that unlocked everything Jesus had said and done. The early church\'s interpretive practice — applying scriptures to Jesus in light of the resurrection — is made explicit here as the Evangelist lets readers see how the disciples\' faith was formed.</p>',
    "23": '<p>The Passover crowd\'s response to Jesus\'s signs represents a faith that is real but shallow — belief generated by spectacle rather than by hearing and understanding. In Jewish tradition, Passover was the festival most charged with expectation of divine intervention: the original Passover was the paradigm of redemption, and every subsequent Passover was a renewal of hope. The crowds are primed to see signs, but their belief does not penetrate to the level of personal commitment to Jesus\'s person and teaching.</p>',
    "24": '<p>Jesus\'s refusal to "entrust himself" to the crowd mirrors wisdom-tradition caution about the fickleness of popular approval. Sirach 37:1–6 warns against the unreliability of those who profess friendship but abandon in crisis. More significantly, the Evangelist attributes to Jesus the divine prerogative of knowing human hearts — an attribute reserved for God alone in the OT (1 Kgs 8:39; Ps 7:9; Jer 17:10). No human testimony about character is needed because Jesus possesses this knowledge directly.</p>',
    "25": '<p>The final verse of the chapter functions as a narrative hinge connecting the Passover crowd (vv. 23–24) to the Nicodemus encounter that opens chapter 3. Jesus\'s knowledge of "what is in each person" (<em>τί ἦν ἐν τῷ ἀνθρώπῳ</em>) sets up the encounter with a man who comes by night — representing the kind of person whose inner state Jesus sees through from the outset. The divine omniscience that authenticated prophets (1 Sam 9:19; 2 Kgs 6:12) is here an attribute of Jesus that requires no endorsement from human witnesses.</p>'
  }
}

def main():
    existing = load_comm('mkt-context', 'john')
    merge_comm(existing, JOHN)
    save_comm('mkt-context', 'john', existing)
    print('John 1–2 mkt-context written.')

if __name__ == '__main__':
    main()
