"""
MKT Context Commentary — Matthew chapters 5–6
Run: python3 scripts/zc-context-matthew-5-6.py

Source data used:
- data/interlinear/matthew.json
- data/translation/glossary-greek.json (makarios, dikaiosynē, ptōchos, teleios, mamōnas, epiousios)
- data/translation/draft/mediating/matthew.json (MKT text for quoting)
- scripts/zc-echo-matthew-5-6.py (key OT echo connections absorbed for context grounding)

Key decisions in this range:
- "Blessed" (makarios) treated as a status-declaration following Psalms beatitude form, not an imperative
- "Righteousness" (dikaiosynē) read as both personal ethical character and God's covenantal justice
- "Perfect" (teleios 5:48) = teleological completeness/wholeness, not sinless perfection
- "Hypocrites" (hypokritai) = Greek theatrical term; not automatically equated with all Pharisees
- "Mammon" (mamōnas) = Aramaic loan-word carrying theological weight of what one trusts in
- Lord's Prayer rooted in Aramaic synagogue prayer forms (Kaddish, Avinu Malkeinu)
- Honor-shame social dynamics primary lens for ch.6 (alms, prayer, fasting all operate in this frame)
- Rabbinic school debates (Hillel vs. Shammai on divorce) noted without anachronism
- Lex talionis (5:38) read as a judicial limit on vengeance, not a personal revenge permission
- Angareia (5:41) — Roman forced-service right; provided the social context for the extra-mile command
- Note: entries for 5:1, 5:17, 6:1, 6:9 already exist in JSON from prior broad-coverage run;
  merge_comm will skip those and add all remaining verses
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

MATTHEW = {
  "5": {
    "1": '<p>The mountain setting deliberately mirrors Sinai. Moses ascended to receive the Torah (Exod 19:3); now Jesus ascends to give the Torah of the kingdom from his own authority rather than citing prior tradition. Matthew structures the Gospel around five great discourses (chs. 5–7, 10, 13, 18, 24–25), a pattern that echoes the Pentateuch and frames Jesus as the new Moses who gives the definitive interpretation of Israel\'s covenant.</p><p>The seated posture was the recognized rabbinic teaching position: a rabbi stood to read scripture in the synagogue (Lk 4:20) but sat to interpret it authoritatively — the seat of Moses (Mt 23:2) conveyed teaching authority. The disciples (<em>mathētai</em>) gathered around the seated teacher mirrors the talmid–rabbi relationship of discipleship as apprenticed life, not classroom instruction.</p>',
    "2": '<p>The formal opening formula "he opened his mouth and taught them" signals a solemn authoritative discourse — a phrase that marks weighty speech in the LXX (Job 3:1; Ps 78:2). Matthew frames the Sermon as a unified address, not a loose collection of sayings, and this opening marks it as the primary statement of kingdom ethics.</p>',
    "3": '<p>The beatitude form (<em>makarios</em>) appears across Psalms and Wisdom literature as a declaration of someone\'s favored status before God (Ps 1:1; 32:1–2; 119:1–2). It is not a command ("be poor in spirit") but a pronouncement — these people are already in God\'s favor regardless of social standing. The beatitudes function as an inverted honor roll: those the world regards as pitiable are announced as the kingdom\'s heirs.</p><p>"Poor in spirit" draws on the Hebrew <em>anawim</em> — the humble poor whose only resource is trust in God (Ps 34:6; 69:32–33; Isa 61:1). This is not a personal virtue to cultivate but a position of total God-dependence that the kingdom recognizes and vindicates.</p>',
    "4": '<p>Mourning in Second Temple Judaism carried multiple registers: grief over personal loss, communal mourning over Israel\'s ongoing exile condition, and penitential mourning over sin (Joel 2:12–13). The recognized category of "those who mourn for Zion" (Isa 66:10) — those who had not made peace with the present broken order — was embedded in Jewish spirituality. The Isaianic comfort-motif (Isa 40:1; 61:2–3) is the prophetic ground of this beatitude: the comforter who comes to those who mourn is arriving in Jesus.</p>',
    "5": '<p>The beatitude quotes Ps 37:11 nearly verbatim ("the meek shall inherit the land/earth"). Psalm 37 addresses exactly the situation of first-century Galilean peasants: watching the wicked prosper while the faithful suffer, urged to trust in God\'s coming reversal rather than retaliate. In the psalm\'s original Hebrew context <em>erets</em> was the Promised Land; Jesus broadens the promise to the whole earth at the eschatological reversal.</p><p>The social inversion is pointed: meekness (<em>praütēs</em>) was not a virtue in Greco-Roman honor culture, which valued strength and dominance. Roman occupation enforced a brutal land-dispossession system through debt slavery and tax burden. Jesus names the meek as the true heirs of the very territory imperial force claimed to control.</p>',
    "6": '<p>In an agrarian subsistence economy where food insecurity was a lived daily reality for most of the audience, hunger and thirst carried visceral urgency. Righteousness (<em>dikaiosynē</em>) is desired with the same desperation — this is not a polite aspiration but a gut-level craving. Isa 55:1–2 uses identical hunger-and-thirst language for the eschatological covenant invitation: come without cost and receive what truly satisfies.</p><p><em>Dikaiosynē</em> carries both personal character (ethical integrity) and covenantal-eschatological content (God\'s justice vindicated, the world put right). The promise that they "will be filled" draws on the eschatological banquet imagery (Isa 25:6) where the covenant people are fully satisfied at God\'s table.</p>',
    "7": '<p>Mercy (<em>eleos</em>) translates the Hebrew <em>hesed</em> — covenant loyalty-love, the faithfulness a covenant partner owes another. The beatitude operates on covenant-reciprocity logic: those who extend <em>hesed</em> receive God\'s <em>hesed</em> in return (Prov 11:17; 21:21). This is not commercial exchange but the covenant pattern: those shaped by God\'s mercy become mercy-extenders and are thereby in alignment with the mercy they themselves need.</p>',
    "8": '<p>Ps 24:3–4 posed the entrance-psalm question for Temple worship: "Who may ascend the hill of the LORD? He who has clean hands and a pure heart." Temple access required ritual purity. The prophets consistently insisted that ritual without inner transformation was empty worship (Isa 1:10–17; Jer 7:21–23; Amos 5:21–24). The beatitude aligns with the prophetic critique: the God who may be "seen" — who becomes knowable and present — is encountered by the inwardly transformed, not merely the ritually clean.</p>',
    "9": '<p>The Mishnaic category of <em>rodfey shalom</em> (pursuers of peace) was a recognized virtue — the tradition records that Hillel said "be of the disciples of Aaron, loving peace and pursuing peace" (m. Avot 1:12). The beatitude elevates peacemaking from a virtue to a marker of divine family resemblance.</p><p>"Sons of God" (<em>huioi theou</em>) — in Second Temple thought, those who imitate God\'s ways bear the family likeness (Wis 2:17–18; Sir 4:10). Peacemaking imitates the God who reconciles Israel to himself; those who make it are recognized as bearing the divine character. In a patronage culture where one\'s family name determined social status, being called "son of God" was the ultimate honor elevation.</p>',
    "10": '<p>The persecution beatitude closes the series by returning to "the kingdom of heaven" — the same promise as v.3, forming a bracket around all eight. This is deliberate structure: the kingdom belongs both to the spiritually destitute (v.3) and to those who suffer for covenant faithfulness. The entire beatitude series presents an alternative social world where the crucified community is named as the true Israel.</p><p>Persecution "because of righteousness" (<em>dikaiosynēs heneken</em>) — suffering specifically for living in alignment with God\'s covenant will — had precedents in the Maccabean martyrs (1 Macc 1–2), Daniel\'s friends in the furnace, and the persecuted psalmists (Ps 34; 37; 44). The community is being placed in this recognizable lineage.</p>',
    "11": '<p>The beatitude shifts from third-person to second-person — "blessed are you" — making the community the direct subject. "Falsely say all kinds of evil against you" (<em>pseudomenoi</em>) points to the specific mechanism: public slander was the primary tool of honor-shame culture for managing deviant behavior. Being identified as a follower of Jesus could trigger social exclusion, reputational destruction, and the economic consequences that followed from both in an ancient community.</p>',
    "12": '<p>"Rejoice and be glad" (<em>chairete kai agalliasrthe</em>) — exultation as the response to public shaming was socially unintelligible in honor culture. The normal responses were withdrawal, retaliation, or despair. The kingdom response re-frames the situation by reorienting toward eschatological reward and prophetic solidarity.</p><p>The tradition of persecuted prophets was embedded in Israel\'s historiography: Jeremiah imprisoned and thrown in a cistern, Isaiah (by tradition) sawn in two, Elijah hunted by Jezebel, the 100 prophets hidden in caves (1 Kgs 18:4). The disciples are being placed in this lineage — their suffering is prophetic identification, not evidence of divine abandonment.</p>',
    "13": '<p>Salt carried several overlapping meanings. As a preservative it prevented decay — essential in a world without refrigeration. As a covenant symbol it appeared in every Levitical grain offering ("every offering shall be seasoned with salt" — Lev 2:13) and in the "covenant of salt" (Num 18:19), signifying permanence and binding obligation. Its economic value was such that Roman soldiers received part of their pay in salt (<em>salarium</em>).</p><p>The threat of losing saltiness reflects ancient chemistry: salt from the Dead Sea region and mineral deposits was often mixed with impurities; when the sodium chloride component leached out or was diluted, what remained was tasteless powder. The social consequence — "trampled underfoot by men" — is a shame image: utter public worthlessness, the opposite of the community\'s calling.</p>',
    "14": '<p>"Light of the world" (<em>phōs tou kosmou</em>) applies to the community the Servant vocation Israel was given in Isa 42:6 and 49:6: "I will make you a light for the Gentiles." The Servant mission was corporate — Israel as a priestly kingdom mediating God\'s presence to the nations. Jesus applies it to the new community he is forming without abandoning the Isaianic frame.</p><p>"A city set on a hill" evokes Zion theology: Jerusalem on Mount Zion was the eschatological gathering point to which the nations would stream (Isa 2:2–3; Mic 4:1–2). The community is cast as the visible, magnetic center that Zion was always designed to be.</p>',
    "15": '<p>The lamp-on-a-stand image is domestic context: Palestinian first-century houses were small, often single-room or two-room structures where one lamp on a stand could illuminate the entire space. The modius (measuring vessel) placed over a lamp would smother it — possibly a reference to hiding a lamp when enemy soldiers searched the house, or simply a reductio ad absurdum: one does not light a lamp in order to hide it. The image satirizes self-concealing discipleship.</p>',
    "16": '<p>"Good works" (<em>erga kala</em>) visible to others, from which they glorify the Father — the stated purpose of public visibility is not self-promotion but divine glorification. The apparent tension with chapter 6 (where public religious performance is condemned) is resolved by motive and audience: good works that direct attention to the Father vs. religious performance designed to direct attention to the practitioner. The difference is the direction of the pointing.</p>',
    "17": '<p>"Abolish" (<em>katalysai</em>) and "fulfill" (<em>plērōsai</em>) are legal and architectural terms: to demolish vs. to bring to completion. In rabbinic usage, a teacher who gave an incorrect Torah interpretation "abolished" it; the correct authoritative interpretation "established" or "fulfilled" it. Jesus claims not to be an iconoclast but the authoritative interpreter who brings the Torah to its intended fullness — a claim that simultaneously affirmed the Torah\'s authority and claimed a higher interpretive position.</p><p>"The Law or the Prophets" is the standard Jewish bi-partite designation for the scriptural corpus (Torah + Nevi\'im). Jesus\'s claim encompasses the full authoritative tradition of Israel, not just the Pentateuch.</p>',
    "18": '<p>"Iota" (<em>iōta</em>) is the Greek equivalent of the Hebrew <em>yod</em> — the smallest letter of the alphabet, a mark barely larger than an apostrophe. "Tittle" (<em>keraia</em>) — the decorative flourish added to Hebrew letters in scribal tradition that distinguished similar-looking characters. The hyperbole makes a maximal claim about Torah\'s inviolability even at the level of orthographic detail.</p><p>"Until everything is accomplished" (<em>heos an panta genētai</em>) — the eschatological horizon: the Torah stands until the purposes for which God gave it are fully realized. This clause is the key to Matthew\'s Christology of fulfillment — not the abolition of the law but its completion in the one who embodies its fullest intention.</p>',
    "19": '<p>The rabbinic distinction between "heavy" (<em>chamur</em>) and "light" (<em>kal</em>) commandments was established in Second Temple Judaism; the Mishnah warns against treating any commandment as light (m. Avot 2:1). The scribal tradition had developed a ranking of commandments, with some treated as minimal. Jesus inverts the academic status-hierarchy of the scribal world: the kingdom\'s social ordering is based not on which commandments one emphasizes but on whether one practices and teaches them in their fullness.</p>',
    "20": '<p>The Pharisees and scribes were the recognized guardians of Torah precision. Their <em>dikaiosynē</em> was public and legible: they had systematized Torah into 613 commandments and built a "fence around the Torah" (additional protective halakhot to prevent accidental transgression). To exceed this was a provocative standard that set up the six antitheses following.</p><p>The antitheses (5:21–48) demonstrate what exceeding Pharisaic righteousness looks like: not less rigorous but more so, in a different direction — going into the interior of the command rather than specifying its external boundaries.</p>',
    "21": '<p>"You have heard that it was said to those of old" introduces a Torah citation or its standard interpretation. "Those of old" refers to the original Sinai recipients, not a later scribal tradition being corrected. The contrast is between the law\'s external formulation and its deeper intention, not between a corrupt scribal tradition and an authentic Torah.</p><p>The murder prohibition is the sixth commandment (Exod 20:13; Deut 5:17). "Liable to judgment" (<em>enochos tē krisei</em>) refers to the local Sanhedrin of 23 elders that handled capital cases under Jewish law (m. Sanhedrin 1:4). The judicial system referenced is the actual first-century Jewish court structure.</p>',
    "22": '<p>"Raca" (<em>rhaka</em>) is an Aramaic term of contempt meaning roughly "empty-head" or "blockhead" — attacking the addressee\'s intelligence and worth. "The council" (<em>synedrion</em>) is the Jerusalem Sanhedrin, the supreme court of 71 elders. "Fool" (<em>mōros</em>) was more severe than Raca — attacking not just intelligence but moral and spiritual standing.</p><p>"Gehenna" (<em>geenna</em>) — the Valley of Hinnom (<em>Gê Hinnōm</em>) southwest of Jerusalem, site of child sacrifice to Molech under wicked Judahite kings (Jer 7:31–32; 2 Chr 28:3). After its defilement by Josiah (2 Kgs 23:10), it became Jerusalem\'s refuse dump where fires burned perpetually. By the first century it had become the standard Jewish image for the place of final divine judgment — a real, recognizable geography pressed into eschatological service.</p>',
    "23": '<p>The Temple altar (<em>thysiastērion</em>) is the sacrificial altar in the Jerusalem Temple. Gift-offerings (<em>dōron</em>) were brought for thanksgiving, purification, and vow fulfillment. The scenario assumes the worshipper is physically en route to the Temple — a realistic situation for Galilean pilgrims traveling to Jerusalem, and probably for Matthew\'s Jerusalem-oriented community as well.</p>',
    "24": '<p>The instruction to leave the gift before the altar and first go reconcile inverts expected religious priority. Abandoning a gift mid-presentation would normally be religiously problematic; completing the offering was a serious obligation. The prophetic tradition that God desires mercy rather than sacrifice (Hos 6:6; Mic 6:6–8; Isa 1:11–17) underlies the inversion: the relational act takes precedence over the ritual one.</p>',
    "25": '<p>The scenario assumes the Roman-era legal context: the <em>antidikos</em> (adversary/plaintiff) takes someone to court; the <em>kritēs</em> (judge) hands the case to the <em>hypēretēs</em> (court officer) who enforces imprisonment. Debtor\'s prison was a real institution in the Greco-Roman world — imprisonment continued until the debt was paid by family or released by the creditor. The urgency of settlement before the case reaches the judge reflects genuine material stakes, not merely rhetorical illustration.</p>',
    "26": '<p>The <em>kodrantes</em> was the smallest Roman copper coin — one-quarter of the <em>assarion</em>, itself tiny. Paying to the last kodrantes before release means there is no partial satisfaction, no early exit on credit. The image functions like a parable: unresolved enmity accumulates a debt that must be fully discharged. In the broader context, the urgency points toward eschatological judgment — an unpayable debt without prior reconciliation.</p>',
    "27": '<p>The seventh commandment (Exod 20:14; Deut 5:18) prohibited the act of adultery — sexual relations with a married or betrothed woman. In the ancient world adultery was primarily framed as an offense against the husband\'s honor and the social order of legitimate descent; it violated his standing in the community and the integrity of the lineage. Jesus\'s antithesis shifts the ground from the act that violates another\'s rights to the internal disposition that already violates covenant fidelity.</p>',
    "28": '<p>"Looks at a woman to lust after her" (<em>pros to epithymēsai autēn</em>) — the Greek construction indicates purposive or sustained looking, not an involuntary glance. The rabbinic literature addressed the guarding of the eyes as protection against the <em>yetzer hara</em> (evil inclination); the extension of adultery to the realm of intentional desire is Jesus\'s radicalization, moving from behavioral regulation to the intention of the will.</p><p>"In his heart" (<em>en tē kardia autou</em>) — in Hebrew psychology the heart (<em>lev</em>) was the seat of will, decision, and moral agency. Locating the failure at the level of directed desire makes the interior of the person the site of moral accountability, not just the observable action.</p>',
    "29": '<p>The hyperbolic instruction to remove the eye or hand that causes stumbling (<em>skandalizō</em> — to cause someone to fall into sin) deploys a rhetorical device found in Jewish moral discourse to emphasize maximum seriousness. No rabbi in the tradition would have read such language literally; it is an extreme expression of the absolute priority of moral integrity over any personal cost. The stakes — loss of one member vs. the whole person thrown into Gehenna — make the calculus clear.</p>',
    "30": '<p>The parallel instruction concerning the right hand reinforces the previous verse\'s hyperbole. The right hand was the hand of action, oath-swearing, and all socially significant gestures — its loss would be socially and economically catastrophic. The parallelism with the eye creates a bipartite statement that covers both the sphere of desire (the eye that looks) and the sphere of action (the hand that takes).</p>',
    "31": '<p>Deuteronomy 24:1–4 regulated divorce by requiring a formal written certificate (<em>gett</em>) — the legal document of separation that freed the woman to remarry. The Mosaic provision protected the woman by establishing her legal status; without the certificate she had no recourse. The rabbinic schools debated the grounds: Shammai\'s school restricted it to sexual infidelity; Hillel\'s school read "something indecent" broadly — even spoiling a meal was sufficient grounds for Hillel (m. Gittin 9:10). The laxity Jesus critiques is the use of legal process to dispose of a wife for any cause.</p>',
    "32": '<p>Jesus\'s position tightens around Shammai\'s more restrictive reading but reframes the argument: the certificate does not protect the woman — it enables her victimization. The dismissed woman in an ancient economy without independent income had no viable option other than remarriage. Jesus\'s statement that she is "made to commit adultery" (<em>moicheuthēnai</em> — passive: caused to be put in an adulterous situation) places the moral responsibility for the social consequences squarely on the divorcing husband.</p>',
    "33": '<p>The oath system in Second Temple Judaism had developed elaborate gradations of binding force. The Mishnah tractate <em>Shevuot</em> distinguishes categories of oaths; popular practice had developed the notion that oaths by heaven or Jerusalem were less binding than direct oaths by the divine name — a legal fiction enabling evasion. The Pharisaic discussion of which oaths were binding (Mt 23:16–22 critiques this system) shows how elaborated the casuistry had become. Notably, the Essene community at Qumran also avoided oaths (Josephus, <em>Jewish War</em> 2.8.6) as corrupting simple truthfulness.</p>',
    "34": '<p>"Do not swear at all" (<em>mē omosai holōs</em>) abolishes the gradation system entirely. The arguments that follow are not new observations but decisive applications: swearing by heaven invokes God\'s throne (Isa 66:1); by earth, his footstool (Isa 66:1); by Jerusalem, his royal city (Ps 48:2). There is no neutral oath-object — every supposed evasion-point is an expression of divine sovereignty. The system of oath-gradation was always theologically incoherent.</p>',
    "35": '<p>Jerusalem as "the city of the Great King" (<em>polis tou megalou basileōs</em>) is from Ps 48:2, the Zion psalm celebrating God\'s royal presence. The Great King is YHWH, not any earthly monarch. Every supposed evasion-oath ("by Jerusalem") invokes the divine presence that the swearer was trying to avoid directly invoking. The rhetoric closes all exits from the divine audience.</p>',
    "36": '<p>Swearing by the head was a common vernacular oath — "I stake my life on this." Jesus\'s point: even this is not under the swearer\'s actual control, since even the color of one\'s hair lies under divine sovereignty. The oath-system operates on a fiction of human self-possession and control that is theologically untenable. No zone of existence is outside God\'s oversight and therefore available as a neutral oath-foundation.</p>',
    "37": '<p>"Let your yes be yes and your no be no" (<em>estō de ho logos hymōn nai nai ou ou</em>) — simple truthfulness without oath-amplification. The rabbinic tradition later recorded the view that a trustworthy person has no need of oaths (b.Bava Metzia 49a). "Whatever is more than these is from the evil one" — the oath-system, as a mechanism for managing endemic untruthfulness, presupposes and institutionalizes it. Its existence is a concession to fallen communication, not a solution to it.</p>',
    "38": '<p>The <em>lex talionis</em> ("law of retaliation") appears in Exod 21:24, Lev 24:20, and Deut 19:21. Its original function was judicial and limiting: a court-administered restraint on the escalation of vendetta by proportioning penalty exactly to the injury. It was never intended as a guide for personal revenge but as a principle for courts to apply. By the first century, rabbinic interpretation had largely moved to monetary compensation rather than literal physical retaliation (m. Bava Kamma 8:1 debates this extensively). Jesus is engaging the principle at its institutional level.</p>',
    "39": '<p><em>Antistēnai</em> (resist) has a military register — to take a stand against in battle. Jesus may be addressing the impulse toward armed resistance that Zealot and Sicarii movements advocated as a religious duty against Roman occupation. "Do not resist an evil person" cuts against both personal retaliation and the political theology of violent resistance.</p><p>The slap on the right cheek: a right-handed person striking another\'s right cheek delivers a backhanded blow — the most deliberately insulting form of striking in antiquity, used by masters to demean slaves and by social superiors to dishonor inferiors. It is an act of honor-shame aggression rather than physical injury. Turning the other cheek forces the aggressor to either stop or use an open-handed blow — the method used between equals — thereby refusing to accept the subordination being imposed.</p>',
    "40": '<p>"Shirt" (<em>chitōn</em>) and "coat" (<em>himation</em>) — the inner tunic and the outer cloak. Jewish law explicitly protected the outer cloak: it could not be taken as a pledge overnight because it served as a poor person\'s bedding (Exod 22:26–27; Deut 24:12–13). The scenario is a court action for debt (<em>tō krinomenon</em>); the protected garment is being legally appropriated. Voluntarily surrendering even the legally protected cloak moves beyond legal compliance into radical generosity that simultaneously exposes the systemic injustice of the transaction to every observer.</p>',
    "41": '<p><em>Angareia</em> (forced service) was the Roman right of conscripting civilians or their pack animals to carry military equipment or messages for one Roman mile (approximately 1.5 km). It was exercised throughout Roman-occupied territories and was deeply resented as a symbol of subjugation. Simon of Cyrene\'s conscription to carry Jesus\'s cross (Mt 27:32) uses the same word. Going voluntarily the second mile transforms an act of coercive imposition into a voluntary act — subverting the power dynamic that angareia was designed to enforce.</p>',
    "42": '<p>The instruction to give to beggars and not refuse borrowers is set in an economy of widespread debt and poverty. The Torah commanded generous lending to the poor (Deut 15:7–11) and prohibited charging interest on loans to fellow Israelites (Lev 25:35–38). The command imposes no conditions on the worthiness of the asker. In the context of the surrounding antitheses, it extends the non-resistance and generosity logic into the economic sphere.</p>',
    "43": '<p>"Love your neighbor" is from Lev 19:18, where the command was contextually addressed to the covenant community of Israel ("love your neighbor as yourself" within the people of God). "And hate your enemy" has no direct Levitical basis — it reflects either popular inference from the command\'s community boundary, or possibly the Qumran community\'s explicit teaching to love all the sons of light and "hate all the sons of darkness" (Community Rule 1QS 1:9–10). Jesus addresses the assumed corollary, not a Levitical text.</p>',
    "44": '<p>In Greek moral philosophy, love (<em>philia</em> or <em>agapē</em>) was typically reserved for friends, benefactors, and family; enemies received proportional treatment. The Stoics counseled equanimity toward enemies but not active love. In Jewish tradition prayer for enemies was unusual (Job 42:8–10 provides the rare case); as a community practice it was exceptional. The combination of active love (<em>agapate</em>) and intercessory prayer constitutes a complete social reversal of normal relational categories.</p>',
    "45": '<p>The argument from divine character to human behavior is the standard <em>imitatio Dei</em> form of Jewish ethics: Lev 19:2 grounds the holiness commandments in God\'s own holiness. Here the divine model is God\'s non-discriminatory providence — the sun rises and rain falls on the righteous and unrighteous alike, without moral filtering. This providential indiscriminacy is presented as the pattern for the community\'s love.</p><p>"Sons of your Father in heaven" (<em>huioi tou patros hymōn</em>) — the family resemblance logic: those who act like the Father show they are children of the Father. In a culture where children were expected to embody the character and honor of their family, this was both a moral argument and a claim about identity.</p>',
    "46": '<p>Tax collectors (<em>telōnai</em>) — Jewish toll collectors who purchased the right to collect taxes in a district and profited from the margin. They were despised as collaborators with the occupying power, treated as ritually impure for regular contact with Gentiles and Gentile money, and excluded from full synagogue participation. They function here as the social minimum: even the most stigmatized collaborators manage reciprocal love within their own circle. The disciples are called to exceed even this baseline.</p>',
    "47": '<p>"Pagans" (<em>ethnikoi</em>, Gentiles) are the second example of the social minimum. The argument uses the rabbinic form of <em>qal va-homer</em> (from lighter to heavier, or a fortiori): if even those outside the covenant manage reciprocal greeting and friendship within their networks, the covenant community\'s calling must exceed the minimum it shares with those who have no access to Torah. The horizon of the community\'s love is not defined by its natural social bonds.</p>',
    "48": '<p>"Be perfect" (<em>teleios</em>) — from <em>telos</em> (purpose, end-goal), carrying the sense of completeness, maturity, or arrival at one\'s intended telos rather than sinless perfection in a later sense. The Hebrew equivalent <em>tamim</em> (blameless, whole-hearted) describes covenant-wholeness: walking before God without double-mindedness (Gen 17:1; Deut 18:13; Ps 119:1). In the immediate context the "perfection" is specifically the non-discriminatory love just commanded — the context of vv.43–47 makes clear that the teleios quality is indiscriminate love mirroring the Father\'s indiscriminate providence.</p><p>The formula "as your heavenly Father is perfect" applies the <em>imitatio Dei</em> of Lev 19:2 to the specific character revealed in the sun-and-rain saying (v.45). The standard is not abstract moral completeness but the Father\'s demonstrated character of universal providential care.</p>'
  },
  "6": {
    "1": '<p>Chapter 6 opens with the governing principle for the triad of Jewish piety (almsgiving, prayer, fasting) that follows. "To be seen" (<em>theathēnai</em>) is the Greek theatrical verb — performing for a watching audience. The <em>hypokritēs</em> (actor) who follows wore a mask and played a role; the theatrical frame makes the critique precise: the danger is performing religion rather than practicing it.</p><p>Almsgiving, prayer, and fasting were universally recognized as the three pillars of Jewish piety (Tobit 12:8; Sir 29:8–12; b.Yoma 86b). Matthew\'s Jesus addresses not their elimination but the honor-exchange economy into which they had been absorbed — the patron-client logic where public virtue generated social capital.</p>',
    "2": '<p>"Do not sound a trumpet" (<em>mē salpizeis</em>) — probably rhetorical hyperbole rather than a literal description. Trumpets were associated with solemn civic and religious announcements; the image satirizes the fanfare of conspicuous generosity. The stone trumpet-shaped receptacles in the Temple treasury (noted in m. Shekalim) into which coins were deposited made the sound of large donations visible and audible.</p><p>"Hypocrites" (<em>hypokritai</em>) — the Greek theatrical term for an actor playing a role behind a mask; in Aramaic the underlying word carried the sense of the profane or impure person maintaining a pious exterior. <em>Apechousin ton misthon autōn</em> ("they have received their reward in full") uses the commercial term found on papyrus receipts to indicate a debt settled — the public honor received is the complete payment; no heavenly account accrues.</p>',
    "3": '<p>"Do not let your left hand know what your right hand is doing" is a proverbial expression for acting without self-conscious calculation. The right hand performed socially significant acts; the left was associated with lesser or ritually impure functions. Complete dissociation of one hand from the other pictures not physical impossibility but the total absence of self-congratulation — the giver who is not tracking their own generosity.</p>',
    "4": '<p>"Your Father who sees in secret" (<em>ho patēr sou ho blepōn en tō kryptō</em>) — God as the discerner of the hidden heart is deep in the OT (1 Sam 16:7; Jer 17:10; Ps 139:1–4). The contrast with theatrical performance is total: the audience of true righteousness is God alone, whose complete knowledge requires no public performance to access. Performing for a human audience is simultaneously pointless and theologically backward — the only Audience who matters has already seen.</p>',
    "5": '<p>Standing to pray (<em>estōtes</em>) was the normal Jewish posture (prostration and kneeling were reserved for extreme penitence). Three daily prayer times — morning, afternoon, evening, drawn from Dan 6:10 and formalized in the <em>Amidah</em> prayers — meant that a pious Jew encountered prayer obligations at regular hours. The street corners (<em>goniai tōn plateiōn</em>) at major intersections at the prayer hour provided maximum public visibility for the standing pray-er. The practice need not have been insincere in every case — but the structure of the practice made conspicuousness available as a motive.</p>',
    "6": '<p>The "inner room" (<em>tameion</em>) was a storage room or pantry — the least public, most private space in a Palestinian house. First-century Palestinian houses were small, often single-room or two-room structures where family life occurred in the main room; the storage room was the only genuinely private space. The door-shutting (<em>kleis tēn thyran sou</em>) removes even the possibility of accidental observation. The instruction is a spatial enactment of the interior-first orientation that governs the entire chapter.</p>',
    "7": '<p>"Babbling" (<em>battalogēsēte</em>) — probably onomatopoeic, evoking empty repetition. The Greco-Roman magical papyri (<em>Papyri Graecae Magicae</em>) are filled with divine names and verbal formulas repeated scores of times to compel the deity to respond — the theory being that volume and persistence forced divine action. This was not limited to pagan practice; some forms of Jewish prayer incantation (especially in the magical tradition of the Cairo Geniza documents) used similar techniques. Jesus contrasts this with prayer based on a Father–child relationship where the child is already known.</p>',
    "8": '<p>"Your Father knows what you need before you ask him" — this is not an argument against prayer but against the magical theory of prayer as information-provision or deity-coercion. Prayer in the Jewish tradition was oriented toward alignment with God\'s will, expression of dependence, and personal communion. The morning service of the Jewish liturgy already expressed this: the prayer formulas did not assume God was ignorant of the need but that articulating dependence was itself the appropriate posture of the creature before the Creator.</p>',
    "9": '<p>"Our Father" (<em>Pater hēmōn</em>) — the Aramaic <em>Avinu</em>. The prayer <em>Avinu Malkeinu</em> ("Our Father, Our King") was a well-known Jewish liturgical prayer particularly associated with the High Holy Days. The Kaddish prayer ("May his great name be magnified and sanctified in the world he created according to his will; may his kingdom come") provides the closest structural parallel to the Lord\'s Prayer\'s first two petitions — the same petitions in the same order. Matthew\'s community likely knew the Kaddish from synagogue worship; the Lord\'s Prayer provides an alternative community prayer rooted in the same categories.</p><p>"Hallowed be your name" (<em>hagiasthētō to onoma sou</em>) — the first petition concerns God\'s reputation in the world. God\'s "name" encompassed his revealed character and active presence; to hallow it means to live in such a way that his character is honored and recognized. This echoes Ezek 36:23 ("I will vindicate the holiness of my great name, which has been profaned among the nations") — the eschatological sanctification of God\'s name was a prophetic hope the prayer now prays for.</p>',
    "10": '<p>"Your kingdom come" (<em>elthetō hē basileia sou</em>) — the Jewish eschatological hope for the decisive inauguration of God\'s direct rule, displacing all human and demonic powers. The Danielic vision of the kingdom given to the Son of Man (Dan 2:44; 7:14) provides the primary frame. This is not a prayer for gradual social improvement but for the eschatological act of divine sovereignty that would end the present age.</p><p>"Your will be done on earth as it is in heaven" — in Jewish cosmology, the angels in heaven do God\'s will without resistance or delay (Ps 103:20–21); the petition asks for that unimpeded obedience to become the earthly reality. The phrase encodes the eschatological hope for a creation fully aligned with its Creator.</p>',
    "11": '<p>"Daily bread" — the Greek <em>epiousios</em> is extremely rare; it appears nowhere in classical Greek literature before the Gospels. Possible meanings include "for the coming day," "for our subsistence," or "supernatural/supersubstantial" (a patristic reading). In an economy where most people lived at or near subsistence level, daily bread was a genuine daily uncertainty. The petition for <em>today\'s</em> provision echoes the manna wilderness pattern (Exod 16:4): one day\'s portion gathered each day, deliberately preventing stockpiling, to teach total dependence on divine provision day by day.</p>',
    "12": '<p>"Forgive us our debts" (<em>aphes hēmin ta opheilēmata hēmōn</em>) — the Aramaic word <em>hoba</em> meant both "debt" and "sin," and the prayer reflects this Aramaic linguistic world where sin is conceptualized as indebtedness to God. Luke\'s parallel (Lk 11:4) uses "sins" (<em>hamartias</em>), showing that the metaphor was understood as moral, not financial. The debt-language also connects to the Jubilee theme in Jewish covenant theology: the periodic release of debts was a covenant mechanism mirroring God\'s forgiveness.</p><p>"As we also have forgiven our debtors" (<em>hōs kai hēmeis aphēkamen</em>) — the aorist perfect indicates completed prior action; the community\'s prior forgiveness of others is presented as already having occurred. This is the only petition with a human-side parallel, and verses 14–15 isolate it for special emphasis — a signal that this petition carries particular structural weight in the prayer.</p>',
    "13": '<p>"Lead us not into temptation" (<em>mē eisenegkēs hēmas eis peirasmon</em>) — the prayer does not suggest God tempts; the Jewish morning liturgy included a parallel petition: "Do not bring me under the control of sin, transgression, iniquity, or trial" (b.Berakhot 60b). The petition acknowledges human vulnerability and requests that God not permit circumstances (<em>peirasmos</em> = trial, test, temptation) that would exceed the community\'s capacity to remain faithful.</p><p>"Deliver us from the evil one" (<em>rysai hēmas apo tou ponērou</em>) — <em>ponēros</em> can be either abstract ("evil") or personal ("the evil one/Satan"). The doxology ("for yours is the kingdom, the power, and the glory") appears in the Didache (8:2, ca. 100 CE) and later manuscripts; it was added liturgically to round off the prayer for corporate recitation, following the pattern of OT doxologies (1 Chr 29:11).</p>',
    "14": '<p>The commentary on the forgiveness petition (vv.14–15) is the only petition from the Lord\'s Prayer that Jesus singles out for explanation. Its isolation signals its structural centrality. The connection between received and extended forgiveness was recognized in Jewish wisdom (Sir 28:2–5: "Forgive your neighbor\'s injustice; then when you pray, your own sins will be forgiven"). Jesus makes this reciprocity non-negotiable — not as a commercial transaction but as a character argument: genuine recipients of forgiveness become forgiving.</p>',
    "15": '<p>The negative formulation ("your Father will not forgive your trespasses") is the starkest possible statement of the same truth. The logic recurs in the Parable of the Unmerciful Servant (Mt 18:21–35): the servant who received immense forgiveness and refused to extend a fraction of it is shown to have never truly received what was given. The issue is not transaction failure but character failure — forgiveness received without transformation into a forgiving person demonstrates that the gift was not actually taken in.</p>',
    "16": '<p>Jewish fasting in the first century: Yom Kippur (the Day of Atonement, Lev 23:27–32) was the one Levitically mandated fast. The Pharisaic tradition had developed voluntary fasts on Mondays and Thursdays — the market days when the most people congregated in towns (Lk 18:12; the Didache 8:1 critiques fasting on these days, commanding Wednesdays and Fridays instead). The visible signs of fasting (unwashed faces, disheveled hair, ash on the head) were borrowed from mourning practice (Neh 9:1; Dan 9:3; Joel 2:12). A faster displaying these signs in public was communicating piety through a recognized visual code.</p>',
    "17": '<p>"Anoint your head and wash your face" — normal daily grooming. Head anointing with olive oil was standard personal hygiene in the ancient Near East; face-washing was the morning routine. To maintain these normal appearances while fasting makes the fast invisible to human observers. The instruction is not about abstaining from grooming but about letting the fast remain between the practitioner and God, undisclosed to the social audience that would generate honor-capital from it.</p>',
    "18": '<p>The "Father who sees in secret" formula (also in 6:4 for almsgiving and 6:6 for prayer) governs all three pillars of Jewish piety. The triad of alms, prayer, and fasting is unified under a single principle: the orientation toward the divine audience rather than the human one. Matthew presents the three examples as variations on one theme, each making the same point with different social-practice content. The repetition is didactic: this is the rule, and it applies everywhere.</p>',
    "19": '<p>Wealth storage in the ancient Mediterranean world: there were no banks in the modern sense. Movable wealth existed as garments (a primary form of portable value — Jacob gives Joseph a special robe; Elisha\'s cloak carries his prophetic authority; the prodigal\'s father calls for the best robe), as metal coins and vessels, and as agricultural stores. All were vulnerable: garments to moth (<em>sēs</em>); grain and organic goods to rot and vermin (<em>brōsis</em>); buried coin-caches in mud-brick walls to thieves who could dig through (<em>dioryssousin</em> — literally "dig through"). The three vulnerabilities are the actual risks of ancient wealth-storage.</p>',
    "20": '<p>The concept of "treasures laid up in heaven" was not invented by Jesus; the rabbinic tradition spoke of this explicitly (b.Pesahim 119a; 4 Ezra 7:77), and Tobit 4:9–10 instructs: "Give alms from your possessions; you will be laying up a good treasure for yourself against the day of necessity." The novelty is making heavenly-treasure orientation not a noble religious practice for the especially devout but the governing principle of all economic existence for the kingdom community.</p>',
    "21": '<p>"Where your treasure is, there your heart will be also" (<em>hopou gar estin ho thēsauros sou, ekei estai kai hē kardia sou</em>) — the heart (<em>kardia</em> = Hebrew <em>lev</em>) was the center of will, attention, and fundamental loyalty in Hebrew anthropology, not merely the seat of emotion. The statement is psychological-theological: whatever receives the heart\'s investment and attention becomes the organizing center of the self. The choice of where to invest is simultaneously a choice about what to become.</p>',
    "22": '<p>The "evil eye" (<em>ophthalmos ponēros</em>) and "good eye" (<em>ophthalmos haplous</em>) carried specific cultural meaning in Jewish and Greco-Roman contexts. In Jewish idiom, "evil eye" (<em>ayin hara</em>) was a well-established metaphor for greed and stinginess; "good eye" (<em>ayin tovah</em>) meant generosity (m. Avot 2:9; Prov 22:9 — "a generous eye [LXX: haplous ophthalmos] will be blessed"). The lamp-of-the-body metaphor thus carries a moral-economic meaning: the generous eye (orientation toward giving rather than hoarding) fills the whole person with light; the stingy eye (orientation toward accumulation) fills it with darkness.</p>',
    "23": '<p>The escalation from physical sight-metaphor to moral darkness follows the evil-eye tradition\'s logic: if the generosity-orientation fills the whole person with light, a greed-orientation fills it with complete darkness — and darkness that mistakes itself for light is total blindness without self-diagnostic capacity. The person whose whole economy of desire is disordered toward accumulation has lost the ability to perceive the disorder.</p>',
    "24": '<p>"Mammon" (<em>mamōnas</em>) is an Aramaic loan-word from the root <em>aman</em> (to trust, entrust) — wealth conceived as what one relies upon and trusts in, not merely what one possesses. Personifying it as a master-figure (<em>kyrios</em>) is precise: in the Greco-Roman world a household slave (<em>oiketēs</em>) owed absolute, undivided service to one master; dual ownership was legally impossible (Roman law recognized this). The slavery metaphor communicates the totality of allegiance that either master demands.</p><p>"Hate" and "love" in this context are covenant terms for allegiance and commitment rather than emotional states (cf. Deut 7:9–10; the Shema\'s "love the LORD your God with all your heart"). The Shema established YHWH as the exclusive object of total loyalty (<em>ahavah</em>); Jesus applies the same exclusivity to the God-vs-Mammon choice. Mammon has become a rival covenant lord.</p>',
    "25": '<p><em>Merimnāō</em> (be anxious) carries the sense of the mind being pulled (<em>merizo</em> = divide) in multiple directions by competing concerns. In an agrarian subsistence economy, anxiety about food and clothing was a lived daily reality for most of the audience, not a psychological abstraction. The teaching addresses genuine material precarity, not affluent worry about comfortable provision.</p><p>The <em>qal va-homer</em> (a fortiori) reasoning form that follows — if God provides for lesser creatures, how much more for human beings — was formalized in the Talmudic period (one of Rabbi Ishmael\'s thirteen hermeneutical rules) but was clearly in use in first-century Jewish argumentation. Jesus uses the standard rabbinic logical form to argue from God\'s providential care for birds and flowers to his providential care for human beings made in his image.</p>',
    "26": '<p>Birds of the air are specifically cited in Job 38:41 and Ps 147:9 as creatures God feeds — and in the Levitical purity code ravens were unclean (Lev 11:15). Luke\'s parallel (Lk 12:24) specifies ravens, making the point even sharper: even the ritually impure bird receives divine provision. The argument from bird-provision to human provision uses the human\'s higher status in God\'s ordering — "Are you not of much more value than they?" — as the premise of the <em>qal va-homer</em> argument.</p>',
    "27": '<p>"Add a single cubit to his life" — <em>hēlikia</em> can mean either physical stature or lifespan; the cubit (<em>pēchys</em>) applied metaphorically to time yields "a cubit of time" or "a single hour." The argument is from futility: anxiety accomplishes nothing toward the very thing it worries about. This echoes Ecclesiastes\' sustained meditation on the futility of anxious striving (Eccl 2:18–26; 3:9–13): the one who grasps for control and security through effort ultimately secures nothing.</p>',
    "28": '<p>The "lilies of the field" (<em>krina tou agrou</em>) were probably the scarlet anemones that blanketed the Galilean hillsides in spring, not the cultivated lily of later Western iconography. Their vivid color and brief life — blooming today, cut and burned as fuel tomorrow — makes the contrast with human anxiety particularly sharp: these exert no effort toward their own provision or beauty and yet surpass in splendor the greatest human achievement.</p>',
    "29": '<p>Solomon\'s glory was proverbial in Jewish tradition (1 Kgs 10:1–29; the Queen of Sheba came from the ends of the earth to witness it). Solomon functioned as the paradigm of God-blessed human prosperity — his wisdom, wealth, and construction projects represented the pinnacle of covenant blessing. To say that a common wildflower surpasses Solomon\'s splendor in all its magnificence is a deliberately extreme statement about the limitation of humanly achieved glory compared with what God produces without human striving.</p>',
    "30": '<p>"You of little faith" (<em>oligopistoi</em>) is a distinctively Matthean category (also 8:26; 14:31; 16:8; 17:20). It describes disciples who have genuine faith but whose trust collapses under pressure or anxiety — not unbelief but insufficient faith. The community Jesus addresses is not accused of having no faith but of having faith that does not yet reach the confidence needed to rest in the Father\'s provision. <em>Oligopistia</em> is a curable condition addressed by teaching and experience, not a condemnation of non-discipleship.</p>',
    "31": '<p>The threefold anxiety-question — "What shall we eat? What shall we drink? What shall we wear?" — echoes the basic material categories of agrarian existence. These were the central preoccupations of households operating without insurance, savings, or reliable agricultural surplus. The repetitive form mirrors the repetitive character of daily worry: the same three questions arising every morning. Jesus does not dismiss the questions as trivial but redirects the orientation from which they are asked.</p>',
    "32": '<p>"The Gentiles (<em>ethnikoi</em>) run after all these things" — the contrast is between those who know the Father\'s provision and those who do not. Gentiles, without the covenant relationship and without knowledge of Israel\'s God, must secure their own provision through anxious effort — their anxiety is rational given their theological situation. The disciples, knowing the Father, have a ground for trust that the nations lack. This ground makes a different mode of existence possible — not indifference to material need but a different relationship to it.</p>',
    "33": '<p>"Seek first the kingdom of God and his righteousness" (<em>zēteite de prōton tēn basileian tou theou kai tēn dikaiosynēn autou</em>) — the integrating command for the entire anxiety section and, in many ways, for the Sermon as a whole. The kingdom and its righteousness (<em>dikaiosynē</em> — God\'s covenant justice, the order of the age to come) are the <em>telos</em> toward which all attention is to be directed; material provision is promised as a consequence of this orientation, not the goal toward which effort is directed.</p><p>"All these things will be added to you" (<em>prostetthēsetai hymin</em>) — the divine passive signals God as the agent. The promise is not prosperity theology but basic provision: the material needs that the anxious Gentiles pursue as a primary goal will be given as a by-product of kingdom-first orientation.</p>',
    "34": '<p>"Each day has enough trouble of its own" (<em>arketon tē hēmera hē kakia autēs</em>) — <em>kakia</em> here means the practical difficulty inherent in the day\'s circumstances, not moral evil. The aphoristic closing provides a practical temporal discipline: the horizon of faithful attention is today, not the aggregate of all anticipated future difficulties. This instruction mirrors the manna-pattern (Exod 16): one day\'s portion gathered one day at a time, teaching that the creature\'s appropriate scope is the present, and the future belongs to the Provider.</p>'
  }
}

def main():
    existing = load_comm('mkt-context', 'matthew')
    merge_comm(existing, MATTHEW)
    save_comm('mkt-context', 'matthew', existing)
    print('Matthew 5–6 mkt-context written.')

if __name__ == '__main__':
    main()
