"""
Fill script: mkt-context, Luke 23–24, missing verses.
Ch 23: vv 2-56 (55 missing — only v1 exists)
Ch 24: vv 1-12,14-53 (52 missing — only v13/Emmaus opening exists)

Luke 23: Passion narrative — trial, crucifixion, burial.
Luke 24: Resurrection — empty tomb, Emmaus road, appearances, ascension.

Luke's distinctive Passion/Resurrection contributions:
- Triple declaration of innocence by Pilate (23:4, 14, 22) — apologetic purpose
- Herod Antipas episode (23:7-12) — unique to Luke
- Daughters of Jerusalem lament (23:27-31) — unique, eschatological
- Repentant criminal and paradise promise (23:39-43) — unique
- Emmaus road (24:13-35) — most extended resurrection narrative in NT
- Physical proof of resurrection: fish-eating (24:41-43)
- Ascension from Bethany (24:50-51) — only Synoptic ascension narrative
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(layer, book):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    return json.loads(p.read_text()) if p.exists() else {}

def save_comm(layer, book, data):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

LUKE_FILL = {
  "23": {
    "2": "<p>The three charges brought before Pilate — subverting the nation, opposing payment of taxes to Caesar, and claiming to be the Messiah-king — are legally crafted to compel Roman judicial action. The first charge (sedition/subversion) was capital under Roman law. The tax charge was historically false: Luke 20:25 records Jesus saying 'give to Caesar what is Caesar's.' The third charge (claiming to be king) converted a religious dispute into a Roman treason charge (crimen maiestatis). The Sanhedrin could not execute without Roman authorization (John 18:31: 'We have no right to execute anyone'), hence the translation to Pilate's jurisdiction. Luke's three charges also parallel the three Pilate exonerations (vv4, 14, 22), creating a literary-legal symmetry unique to his Gospel.</p>",
    "3": "<p>'Are you the king of the Jews?' — Pilate's single direct question goes to the politically actionable charge. Jesus's response (sy legeis, 'you have said it/so you say') is a qualified affirmation: neither a full yes nor a denial. The formula appears in all four Gospels (Matt 27:11; Mark 15:2; John 18:37) and reflects a Semitic idiom of indirect confirmation. In John 18:36-37, the answer is extended: 'My kingdom is not of this world.' Pilate takes the answer as non-threatening — his immediate declaration of innocence (v4) shows he found no treasonous intent in Jesus's claim.</p>",
    "4": "<p>'I find no basis for a charge against this man' — Luke's first of three innocence declarations (vv4, 14, 22). This triple-declaration structure is the Lukan apologetic signature: Jesus was legally innocent by Roman judicial finding, not merely by moral innocence. The Roman legal term underlying Luke's Greek (aitia = basis/charge; Luke uses it here and in Acts 25:18, 27) is the formal declaration of non-guilt. Luke uses this pattern in Acts for Paul (Acts 23:9, 25:18, 26:31-32), establishing a structural parallel: the pattern of Roman innocence-declaration for Jesus is repeated for his apostle.</p>",
    "5": "<p>'He stirs up the people all over Judea by his teaching, starting from Galilee to this place' — the geographical catalog (Galilee → Jerusalem) triggers the Herod transfer. The charge 'all over Judea' (kath' holēs tēs Ioudaias) was an escalation from 'our nation' (v2) to a regional claim. The Galilee mention was likely strategic — implying Herod Antipas's jurisdictional interest. Luke alone records this exchange, which moves the trial to a second hearing before Herod (vv6-12). The accusers' persistence despite Pilate's exoneration reveals the political pressure: the Sanhedrin needed execution, not acquittal.</p>",
    "6": "<p>Pilate's jurisdictional question — 'Is the man a Galilean?' — reflects Roman provincial administration. Under the system of client kingdoms, Herod Antipas held tetrarchic authority over Galilee and Perea (not Judea, which was under direct Roman administration since 6 CE). The rule of forum domicilii (trial in the jurisdiction of residence) was a legal option, not an obligation. Pilate's referral to Herod was probably as much diplomatic courtesy — Herod was already in Jerusalem for the festival — as legal procedure. The move also transferred political risk: if Herod executed Jesus, Pilate was insulated from the Jewish reaction.</p>",
    "7": "<p>Herod Antipas was in Jerusalem for the Passover — a reasonable practice for the region's client-king to attend the major Jewish festival and maintain political relationships with the Jerusalem hierarchy. Herod had executed John the Baptist (3:19-20; 9:9) and feared Jesus as John's possible resurrection (9:9). He had been wanting to see Jesus 'for a long time' (9:9: 'I beheaded John — but who is this man about whom I hear such things?'). The Jerusalem Passover setting was theologically apt for the confrontation: Luke's geographical movement (Galilee → Jerusalem) now plays out in miniature within the passion itself.</p>",
    "8": "<p>'When Herod saw Jesus, he was greatly pleased' — Herod's attitude is curious entertainment, not judicial seriousness. He was 'hoping to see some miracle performed by him' (elpizōn ti sēmeion idein hyp' autou = hoping to see some sign performed by him). This expectation of miracle-on-demand parallels the devil's temptation (4:9-11: 'throw yourself down') and the mockers at the cross (v35: 'save yourself'). Jesus performs no signs for Herod, just as he performed none for testing (Matt 16:4). The Herod episode is Luke's exploration of the difference between curiosity/entertainment and genuine faith.</p>",
    "9": "<p>'He plied him with many questions, but Jesus gave him no answer' — Jesus's silence before Herod fulfills the Servant silence of Isaiah 53:7: 'as a sheep before her shearers is silent, so he did not open his mouth.' Luke does not cite Isaiah here, but the pattern is unmistakable. The contrast is with Jesus's response to Pilate (v3): he answered Pilate's substantive legal question but maintained silence before Herod's curiosity-driven interrogation. The distinction is between a legitimate judicial inquiry (Pilate) and entertainment-seeking from a compromised ruler who had already murdered John the Baptist.</p>",
    "10": "<p>'The chief priests and the teachers of the law were standing there, vehemently accusing him' — the Sanhedrin delegation's presence before Herod (not just Pilate) shows their determination to achieve execution through any available judicial channel. Their vehement accusation (eutonōs katēgoroun = intensely/strongly accused) before a client-king who had no independent power of execution reveals the political strategy: build a record of accusation across multiple hearings to create irresistible pressure on Pilate. The legal pressure mounted by multiple hearings with consistent accusations is a classic coercive legal tactic.</p>",
    "11": "<p>'Herod and his soldiers ridiculed and mocked him. Dressing him in an elegant robe (esthēta lampran = bright/gleaming clothing), they sent him back to Pilate' — the 'elegant robe' in Luke is white or gleaming, distinct from the purple/scarlet robe of Matthew 27:28 and Mark 15:17 (mock-royal color). The gleaming white may be the ceremonial white worn by candidates (Latin candidatus = white-robed) or simply a striking garment. The mockery is fundamentally theatrical: Herod stages a burlesque of royal presentation without the legal authority to do anything substantive. The robe functions as Herod's verdict: a joke, not a threat.</p>",
    "12": "<p>'That day Herod and Pilate became friends — before this they had been enemies' — Luke's parenthetical note on the reconciliation of political rivals through their shared handling of Jesus is historically plausible and unique to Luke. The prior enmity may relate to Pilate's massacre of Galileans whose blood he mixed with their sacrifices (13:1) — a jurisdictional overreach into Herod's subject population. The Jesus-trial becomes the diplomatic bridge: both declared him not guilty of a capital charge, both handled the case without commitment. Shared complicity in injustice sometimes creates unexpected political alliance.</p>",
    "13": "<p>'Pilate called together the chief priests, the rulers, and the people' — the summoning of the full assembly marks a formal resumption of the Roman hearing after the Herod interlude. 'The people' (ton laon) is significant: Luke has been careful to distinguish the Jerusalem crowd and leadership from Jesus's Galilean followers. Here the 'people' join the leaders in the final demand. Luke 23:35 will contrast 'the people standing watching' with 'the rulers who sneered' — the crowds' role is complex; they are present at the demand for crucifixion but do not mock at the cross.</p>",
    "14": "<p>'You brought me this man as one who was inciting the people to rebellion (apostrephos ton laon = turning the people away). I have examined him in your presence and have found no basis for your charges against him' — Pilate's second exoneration. The verb apostrephō (turn away) is the Greek for the Hebrew shûḇ (turn/return) used for covenant apostasy, making the charge theologically loaded in a Jewish context — Jesus as covenant subverter. Pilate's examination (anakrinō = thorough judicial investigation, the legal term for Roman preliminary hearing) finds no substance to the charge. This is Luke's careful legal vocabulary establishing the judicial record.</p>",
    "15": "<p>'Neither has Herod, for he sent him back to us; as you can see, he has done nothing to deserve death' — Pilate incorporates Herod's implicit finding into the formal Roman record. Herod's return of Jesus without execution or conviction constituted a de facto acquittal: a tetrarch who found genuine treasonous activity would have acted, as he had with John the Baptist. Pilate's statement 'he has done nothing to deserve death' (ouden axion thanatou = nothing worthy of death) is the precise Roman legal formula: capital punishment required a crime specifically punishable by death under Roman law, and none had been demonstrated.</p>",
    "16": "<p>'I will punish him (paideuō = discipline/correct, not execute) and then release him' — Pilate's compromise proposal involves flogging as a non-capital punishment to satisfy the accusers while stopping short of execution. Paideuō in Greek means discipline/educational correction, notably lighter than the Roman flagellatio (flogging that could itself cause death). This is a legal compromise: acknowledge some concern while refusing capital punishment. The offer reveals Pilate's actual assessment — the charge does not meet the Roman death threshold, but he is willing to inflict physical punishment as a concession to the political pressure.</p>",
    "17": "<p>The Passover amnesty custom — releasing one prisoner — is attested in Luke, Matthew 27:15, Mark 15:6, and John 18:39, but not in Roman legal sources outside the Gospels. The closest parallel is in Josephus's account of amnesty practices at festivals, and in papyri from Roman Egypt showing periodic prisoner releases. The practice, if historical, would have been a political safety valve: releasing a popular prisoner at Passover reduced tension in the crowded city. The custom gives the crowd a legal mechanism to demand Barabbas — working within the system while circumventing Pilate's declared verdict.</p>",
    "18": "<p>'The whole crowd shouted: Away with this man! Release Barabbas to us!' — Barabbas (bar = son; Abba = father) was an Aramaic name meaning 'son of the father,' a designation that has generated ironic interpretation: the crowd chose the literal 'son of the father' (a convicted murderer) over the metaphysical Son of the Father. Matthew 27:16-17 adds that Barabbas was a 'notable prisoner' (desmion episēmon). The crowds' unanimous voice (pas ho plēthos = the whole mass) shows the shift from the ambivalent Jerusalem crowd to full alignment with the Sanhedrin's demand.</p>",
    "19": "<p>Barabbas had been imprisoned for 'an insurrection (stasis = uprising/sedition) in the city, and for murder' — the charge for which Barabbas was convicted (sedition + murder) was precisely the charge for which Jesus was being tried but found innocent. The substitution is structurally precise: the actually guilty rebel/murderer goes free; the innocent man is condemned. Luke's specification of 'in the city' (en tē polei) — Jerusalem itself, not some remote incident — makes Barabbas's crimes locally notorious and the release politically dangerous. The crowd's choice inverts Roman justice in the most pointed way possible.</p>",
    "20": "<p>'Wanting to release Jesus, Pilate appealed to them again' — Luke shows Pilate making three separate attempts to release Jesus (vv16, 20, 22), each time facing escalating pressure. The verb prosephōnēsen (called out to, addressed publicly) suggests Pilate is making formal judicial pronouncements to the whole assembly, not private negotiations. The legal logic: having formally declared innocence twice (vv4, 15), Pilate is procedurally constrained — a third declaration followed by release would be legally coherent; capitulation to crowd pressure after three innocent-verdicts was a judicial travesty that Luke deliberately records.</p>",
    "21": "<p>'But they kept shouting: Crucify him! Crucify him!' — the repeated shouting (epephōnoun = kept crying out, imperfect tense indicating sustained crying) is the crowd as political mob. Crucifixion (staurō = crucify, from stauros = upright post/cross) was the Roman penalty for non-citizens convicted of capital crimes including sedition, rebellion, and piracy — precisely the charge the accusers were pressing. The mob's specific demand for crucifixion rather than beheading or another method reveals their knowledge of Roman penal procedures and their intent to achieve maximum legal disgrace for Jesus.</p>",
    "22": "<p>'For the third time he spoke to them: Why? What crime has this man committed? I have found in him no grounds for the death penalty' — the third and most explicit innocence declaration. Luke's triple pattern (3x Pilate exonerates) deliberately mirrors the triple denial (3x Peter denies). At the precise moment when Jesus's closest disciple is denying him three times, the Roman prefect is declaring his innocence three times — the literary-theological structure is Luke's signature craft. 'No grounds for the death penalty' (ouden aition thanatou) is the sharpest legal formulation yet.</p>",
    "23": "<p>'But with loud shouts they insistently demanded that he be crucified, and their shouts prevailed' — 'their shouts prevailed' (katischyon = overpowered, were dominant) is Luke's description of political coercion defeating judicial procedure. The verb katischyō implies force/might prevailing — the same word Jesus uses for the gates of Hades not prevailing against the church (Matt 16:18). Here it is used for the crowd's political power prevailing against Roman justice. Luke presents the legal framework as ultimately capitulating to sustained political pressure — a precise and unflattering portrait of provincial Roman justice.</p>",
    "24": "<p>'So Pilate decided (epekrinen = gave judgment, a judicial term) to grant their demand' — the vocabulary is deliberately juridical: Pilate does not simply yield; he formally 'gives judgment' (epekrinen), making a legal decision to grant what the crowd demanded. This makes the injustice more precise: Pilate knew the verdict was wrong (three declarations of innocence) but delivered it as a formal judgment anyway. Roman law distinguished between acquittal (absolvere), condemnation (damnare), and non liquet (case not proven) — Pilate effectively issues a condemnation after three acquittals, an unprecedented judicial contradiction.</p>",
    "25": "<p>'He released the man who had been thrown into prison for insurrection and murder, the one they asked for, and surrendered Jesus to their will' — Luke's formulation is stark: Jesus was 'surrendered to their will' (paredōken tō thelēmati autōn). The passive verb paradidōmi (hand over, surrender) is the Passion vocabulary word that runs through all four Gospels — Judas 'handed over' Jesus, Pilate 'handed over' Jesus, and ultimately Jesus 'handed himself over' (Gal 2:20). The transfer from Roman judicial authority to 'their will' (the Jewish leadership's political will) makes the crucifixion both Roman and Jewish, which is Luke's historically accurate presentation.</p>",
    "26": "<p>Simon of Cyrene — 'who was on his way in from the country (ap' agrou = from a field/farm)' — was likely a Jewish pilgrim from the diaspora coming into Jerusalem for Passover. Cyrene (modern Libya) had a large Jewish community; Josephus records its Jewish quarter (Antiquities 16.160). Acts 6:9 mentions a 'Synagogue of the Cyrenians' in Jerusalem. Simon's sons Alexander and Mark (named in Mark 15:21) were apparently known to the early church. The Romans pressed bystanders into service by right of angaria (compelled service), the same right invoked in Matt 5:41 ('if someone forces you to go one mile'). Luke alone notes the cross was carried 'behind Jesus' (opisthēn tou Iēsou), a discipleship image.</p>",
    "27": "<p>'A large number of people followed him, including women who mourned and wailed for him' — the mourning women are distinct from the disciples (who had fled, cf. Mark 14:50) and from the accusers. Public mourning for the condemned was a feature of Roman executions; Cicero describes it as a form of protest against unjust sentences. Luke's attention to women at the Passion (cf. 8:1-3; 23:49, 55; 24:1-11) is a distinctive feature — women provide the unbroken witness thread from Galilee through crucifixion to resurrection. Their public lamentation made them politically significant witnesses to the injustice of the execution.</p>",
    "28": "<p>'Daughters of Jerusalem, do not weep for me; weep for yourselves and for your children' — unique to Luke, this lament-reversal echoes OT mourning formulas (Jer 9:17-21; Ezek 24:16-17). 'Daughters of Jerusalem' is the OT title for the female inhabitants of the city (Isa 3:16-17; Zech 9:9; Song 3:10). The reversal — 'do not weep for me, weep for yourselves' — points forward to the 70 CE destruction, which Jesus had already predicted (21:20-24). The condemned man addresses his mourners not with gratitude but with prophetic warning: the disaster is not his alone but the city's.</p>",
    "29": "<p>'For the time will come when you will say: Blessed are the childless women, the wombs that never bore and the breasts that never nursed' — the reversal of the most fundamental female blessing (fertility/children; cf. Luke 1:42: 'blessed among women' and 1:48: 'blessed is the fruit of your womb') is the sharpest possible way to describe the coming horror. In the siege of Jerusalem (66-70 CE), Josephus records that mothers ate their children (War 6.199-219) — an atrocity that makes childlessness a mercy. The macarism (blessed are...) formula is here applied to barrenness, inverting the birth announcements of Luke 1-2.</p>",
    "30": "<p>'Then they will say to the mountains: Fall on us! and to the hills: Cover us!' — direct quotation of Hosea 10:8, which describes the terror of Israelite judgment at the Assyrian conquest. The preference for burial under mountains over enduring what is coming is the language of final judgment (cf. Rev 6:16, which also quotes this verse in the context of eschatological terror). Luke uses the Isaiah/Hosea prophetic tradition of judgment-on-Jerusalem to frame the Passion: the crucifixion is simultaneously Jesus's own judgment-bearing and the trigger for the coming judgment on those who demanded it.</p>",
    "31": "<p>'For if people do these things when the tree is green, what will happen when it is dry?' — a proverbial saying (appearing in Ezek 20:47 in a different form) that contrasts present and future conditions. The 'green tree' is Jesus — the living, righteous one — while the 'dry tree' is unrepentant Israel heading toward judgment. The proverb logic: if this (crucifixion of the innocent) happens under good conditions (the Messiah present, preaching repentance, performing miracles), the judgment that comes when conditions deteriorate will be incomparably worse. The 70 CE destruction is the referent; the saying prepares the Daughters of Jerusalem for what the mourning should anticipate.</p>",
    "32": "<p>'Two other men, both criminals (kakourgoi = evil workers, criminals), were also led out with him to be executed' — the two criminals crucified with Jesus are designated kakourgoi (Luke) rather than lēstai (bandits/rebels, Matthew and Mark). The distinction matters: lēstēs (Josephus's term for Zealot-type rebels) is what the crowd shouted at Jesus in the temple (Mark 11:17: 'den of robbers'), while kakourgia (evil-doing) is a more generic criminal designation. Luke's more general term allows the criminal-repentance episode of vv40-43 to apply universally: any sinner, not specifically a political rebel, can repent at the moment of death.</p>",
    "33": "<p>'When they came to the place called the Skull (to Kranion = the Skull, Latin: Calvaria/Calvary)' — the Hebrew Golgotha (Gulgolta = skull) was a site outside Jerusalem's walls at the time (crucifixions were public, outside the city, cf. Heb 13:12). The site is traditionally identified with the Church of the Holy Sepulchre, which was outside the second wall of Jerusalem in the first century (Gordon's Calvary/Garden Tomb is a 19th century alternative with less historical support). The 'Skull' toponym may derive from the skull-like appearance of the rock formation, or from it being a site of executions where bones were left. Both criminals were crucified alongside Jesus, fulfilling Isaiah 53:12 ('numbered with the transgressors').</p>",
    "34": "<p>'Father, forgive them, for they do not know what they are doing' — this prayer is absent from some significant manuscripts (P75, Codex Vaticanus, Codex Bezae), creating a textual debate about its originality. Those who argue for inclusion note its conformity to Lukan theology (cf. Acts 7:60: Stephen's 'Lord, do not hold this sin against them') and its stylistic fit with Luke's theme of repentance. Those who argue against note the manuscript evidence and the difficulty of explaining why scribes would omit it if original. Most critical editions include it with a note. The prayer's content — forgiveness for those acting in ignorance — is paralleled in 1 Corinthians 2:8 ('they would not have crucified the Lord of glory').</p>",
    "35": "<p>'The people stood watching, and the rulers even sneered at him' — Luke distinguishes three groups at the cross: the people watching (neutral bystanders), the rulers sneering (Jewish leadership), and the soldiers mocking (vv36-37). 'The rulers sneered' (exemyktērizon = turned up their nose at, a Greek idiom for contempt) with the taunt 'He saved others; let him save himself' — ironically true on two levels: Jesus did save others, and his refusing to save himself is precisely the mechanism of salvation. The mockery uses the language of salvation (sōzō = save/rescue) without understanding it.</p>",
    "36": "<p>'The soldiers also came up and mocked him. They offered him wine vinegar (oxos)' — the sour wine (oxos, posca in Latin) was the soldier's standard ration drink, not the wine mixed with myrrh of Mark 15:23 offered before crucifixion as a mild anesthetic. Psalm 69:21 ('they gave me vinegar for my drink') was read as messianic prophecy; John 19:28-30 makes the connection explicit. Luke's soldiers' mockery joins the ruler's mockery in echoing the devil's desert temptation structure: 'If you are the Son of God...' (4:3, 9) becomes 'If you are the king of the Jews...' (v37). The Passion is the final temptation test.</p>",
    "37": "<p>'If you are the king of the Jews, save yourself' — the soldiers' taunt repeats the formal charge from the titulus (v38) as a mocking challenge. The 'If you are...' (ei sy ei = if you are) is the conditional-challenge formula from the devil's temptation (4:3: 'If you are the Son of God, command these stones...') and from Satan at the high point of the desert temptation. Luke's passion theology identifies the cross as the culmination of the devil's strategy: the three desert temptations failed; the crucifixion is the final attempt to get Jesus to use divine power self-protectively rather than redemptively.</p>",
    "38": "<p>The titulus crucis — the written notice (epigraphē = inscription) stating the charge — was posted on the cross, typically placed over the condemned person's head. John 19:19-20 specifies it was written in Hebrew, Latin, and Greek. The three languages make it an inadvertent universal proclamation: the title 'King of the Jews' is announced in the three dominant languages of the ancient Mediterranean world. Pilate's insistence on keeping the wording despite Jewish objections (John 19:22: 'What I have written, I have written') made it a permanent judicial charge — and, for the Gospel writers, an accurate if ironic title.</p>",
    "39": "<p>'One of the criminals who hung there hurled insults at him: Aren't you the Messiah? Save yourself and us!' — the first criminal's mockery parallels the rulers (v35) and soldiers (v36-37) in using salvation-language as taunt: 'save yourself and us.' His contempt is that Jesus is failing to exercise messianic power. In Mark 15:32 both criminals mocked Jesus; Luke's differentiation — one mocking, one repenting — is unique to his Gospel. The differentiation serves Luke's consistent theme of division among those who encounter Jesus: some respond with repentance, others with contempt, even facing identical circumstances and the same dying proximity to Jesus.</p>",
    "40": "<p>'But the other criminal rebuked him: Don't you fear God, since you are under the same sentence?' — the second criminal's rebuke of the first introduces the fear of God (phobē ton theon) as the basis for appropriate human response. The phrase 'since you are under the same sentence (en tō autō krimati = in the same judgment)' acknowledges shared condemnation while differentiating moral character. The Talmudic tradition holds that deathbed repentance is valid; the Mishnah (Sanhedrin 6:2) records that the condemned were asked to confess before execution. The second criminal performs exactly this — a deathbed confession and intercession.</p>",
    "41": "<p>'We are punished justly, for we are getting what our deeds deserve. But this man has done nothing wrong' — the second criminal's confession has two movements: acknowledgment of personal guilt ('our deeds deserve this') and declaration of Jesus's innocence ('this man has done nothing wrong'). The innocence declaration (ouden atopon epraxen = he did nothing out of place/wrong) repeats Pilate's formal finding in popular language. The criminal becomes the final human witness to Jesus's innocence before death, extending Luke's apologetic pattern: Pilate (3x), Herod (implicitly), now a dying criminal — the three witnesses (Roman, Herodian, criminal) establish the legal record by any standard.</p>",
    "42": "<p>'Then he said: Jesus, remember me when you come into your kingdom' — the address 'Jesus' (the personal name, without title) is intimate and direct. The request 'remember me' (mnēsthēti mou) uses the OT vocabulary of divine remembrance — God 'remembered' Noah (Gen 8:1), Abraham (Gen 19:29), and covenant obligations. The 'when you come into your kingdom' (hotan elthēs en tē basileia sou) may imply the parousia-expectation, but the response ('today') shifts the timing dramatically. The criminal's faith is minimal theologically but maximally personal: he asks only to be remembered, not for salvation or paradise — yet receives more than he requested.</p>",
    "43": "<p>'Truly I tell you, today you will be with me in paradise (en tō paradeisō)' — the promise uses paradeisos, the Greek transliteration of the Persian pardess (walled garden/park), used in the LXX for the Garden of Eden (Gen 2:8-10) and in Jewish literature for the blessed afterlife realm of the righteous (1 Enoch 60:8; 2 Cor 12:4; Rev 2:7). The 'today' (sēmeron) is Luke's signature word for realized eschatology (2:11; 4:21; 19:9; 23:43) — the 'today of salvation.' The promise to be 'with me' (met' emou) is the relational core: paradise is not primarily a location but presence with Christ. The dying criminal receives what Luke's entire Gospel has proclaimed: salvation available to the outcast through faith.</p>",
    "44": "<p>'It was now about noon (hōra hektē = the sixth hour), and darkness came over the whole land until three in the afternoon (hōra enatē = the ninth hour)' — the three hours of darkness (noon to 3pm) cover the central hours of Jesus's crucifixion. The darkness echoes the plague of darkness over Egypt (Exod 10:21-23) and the Day of the Lord imagery (Amos 8:9: 'I will make the sun go down at noon and darken the earth in broad daylight'; Joel 2:31). The sixth hour was also the time of Jewish midday prayer. Ancient observers (Origen, Julius Africanus) debated whether this was a solar eclipse; a solar eclipse is astronomically impossible at Passover (full moon), so Luke likely intends a supernatural darkness on a cosmic/theological scale.</p>",
    "45": "<p>'For the sun stopped shining (tou hēliou eklipontos = the sun having failed/been eclipsed), and the curtain of the temple was torn in two' — the two simultaneous signs frame the theological meaning of the death: cosmic disruption (darkness/sun failure) and cultic disruption (the temple veil). The temple curtain (katapetasma = veil/curtain) separated the Holy Place from the Holy of Holies. In Hebrews 10:19-20, the tearing is interpreted as Jesus's body — his death opens the way into the divine presence. The High Priest entered the Holy of Holies only on Yom Kippur; now the barrier is eliminated. Josephus describes a similar curtain of great size and complexity (War 5.210-214) that would have made its tearing a dramatic public sign.</p>",
    "46": "<p>'Jesus called out with a loud voice: Father, into your hands I commit my spirit!' — the quotation of Psalm 31:5 (LXX 30:6) as a final prayer is unique to Luke. Mark and Matthew record the cry of dereliction (Ps 22:1: 'My God, my God, why have you forsaken me?'), while Luke substitutes the Psalms of Trust vocabulary. The 'loud voice' (phōnē megalē) indicates Jesus dies with full strength, not in physical weakness — an apologetic detail against docetic claims that Jesus merely appeared to die. The prayer 'into your hands I commit my spirit' (paratithēmai to pneuma mou) is the bedtime prayer of Jewish piety, recited before sleep — Jesus dies in trust, not despair.</p>",
    "47": "<p>'The centurion, seeing what had happened, praised God and said: Surely this was a righteous man (dikaios)' — Luke's centurion declares Jesus 'righteous' (dikaios), while Mark 15:39 and Matthew 27:54 record 'truly this man was the Son of God.' The difference is significant: Luke's formulation is the language of Jewish righteousness and innocence (dikaios = innocent/righteous) rather than divine sonship, consistent with his apologetic to a broader Greco-Roman audience. The centurion's response — 'praised God' (edoxazen ton theon) — uses the standard Lukan response to divine action (cf. 2:20; 5:25-26; 7:16; 13:13; 17:15). Even the Roman executioner responds to Jesus's death with the appropriate theological response.</p>",
    "48": "<p>'When all the people who had gathered to witness this sight saw what took place, they beat their breasts and went away' — 'beating the breast' (typtontes ta stēthē) is the gesture of grief and penitence (cf. Luke 18:13: the tax collector 'beat his breast' in the temple as he prayed for mercy). The crowd's response is not the mockers' contempt but grief-stricken departure. Luke's crowd is not uniformly guilty: they demanded crucifixion under leadership pressure (v23) but respond to the death itself with lamentation. This nuanced crowd portrayal allows Luke to later present Peter's Pentecost speech to 'the people' with genuine expectation of repentance (Acts 2:14-41).</p>",
    "49": "<p>'But all those who knew him, including the women who had followed him from Galilee, stood at a distance watching these things' — 'all those who knew him' (pantes hoi gnōstoi autō = all his acquaintances) includes the wider circle beyond the Twelve. The women from Galilee provide narrative continuity: they witness the death (v49), witness the burial (v55), prepare the spices (v56), and come to the empty tomb (24:1-10). Luke's resurrection-witness chain depends on this continuous female presence. 'Stood at a distance' (histēkeisan apo makrothen) echoes Psalm 38:11 (LXX 37:12): 'my friends and companions stand aloof from my plague.'</p>",
    "50": "<p>'Now there was a man named Joseph, a member of the Council (bouleutēs = councilor/senator), a good and upright man' — Joseph of Arimathea appears in all four Gospels. His social status (Sanhedrin member) and geographical origin (Arimathea, probably Ramathaim-Zophim in Ephraim, 1 Sam 1:1, Samuel's hometown) are consistent across accounts. 'Good and upright' (agathos kai dikaios) is Luke's double virtue-designation, echoing the centurion's dikaios verdict (v47): multiple witnesses certify Jesus's character through their own. Josephus describes the Sanhedrin as consisting of 71 members including chief priests, elders, and scribes — Joseph was among the elders.</p>",
    "51": "<p>'Who had not consented to their decision and action. He came from the Judean town of Arimathea, and he was waiting for the kingdom of God' — Luke clarifies that Joseph's Sanhedrin membership did not make him complicit: 'he had not agreed to their decision' (ouk ēn sygkatatetheimenos = not having given consent). This legal distinction matters for Luke's narrative: it prevents the false inference that the entire Sanhedrin condemned Jesus, and it introduces Joseph as a sympathizer within the leadership. His 'waiting for the kingdom of God' (prosedecheto tēn basileian tou theou) uses Luke's eschatological-hope vocabulary (cf. 2:25, 38 — Simeon and Anna).</p>",
    "52": "<p>'Going to Pilate, he asked for Jesus' body' — requesting the body from the Roman executioner required social standing and nerve. Roman law permitted the body of the condemned to remain on the cross as a deterrent (Petronius Satyricon 111-112: crucified corpses displayed publicly for extended periods). Jewish law required burial before sundown (Deut 21:22-23: 'do not leave his body on the tree overnight'), creating urgency before the Sabbath. Joseph's act was simultaneously an act of piety (proper burial) and a social risk — publicly identifying with a man just executed for sedition against Rome and blasphemy against the temple leadership.</p>",
    "53": "<p>'Then he took it down, wrapped it in linen cloth (sindoni = linen sheet) and placed it in a tomb cut in the rock (latomēton = hewn/cut from stone), one in which no one had yet been laid' — rock-cut tomb burial was standard for Jerusalem's wealthy in the Second Temple period. Archaeological excavations have found hundreds of such tombs in the Kidron Valley and on the Mount of Olives. The 'new tomb' (John 19:41) in which no one had been buried is Joseph's own prepared tomb. The unused tomb is theologically significant for the resurrection: no confusion with another occupant's resurrection is possible. The linen wrapping (John 19:40 adds burial spices with Nicodemus) began the standard Jewish burial preparation.</p>",
    "54": "<p>'It was Preparation Day (paraskeue = preparation), and the Sabbath was about to begin (epephoesken = was dawning, lit. beginning to shine)' — Preparation Day (Friday) was the standard Jewish term for the day before the Sabbath. The Sabbath began at sundown. The urgency of burial before sundown on Friday created the 'three days' chronology: buried Friday evening, in the tomb Saturday, risen before Sunday dawn — Friday, Saturday, Sunday — but Jewish reckoning could count parts of days as whole days, yielding 'three days' from Friday evening burial.</p>",
    "55": "<p>'The women who had come with Jesus from Galilee followed Joseph and saw the tomb and how his body was laid' — the women's witnessing of the burial location establishes the chain of identification that prevents the empty tomb from being explained by the 'wrong tomb' hypothesis (they could not mistake the location since they watched the burial). Luke names the Galilean women as the continuous witnesses linking crucifixion, burial, and empty tomb. Their role as primary resurrection witnesses was socially countercultural — Jewish law generally did not accept women's testimony in court, making their appointment as resurrection witnesses an unexpected choice that argues for historicity (a fabricated account would have used male witnesses).</p>",
    "56": "<p>'Then they went home and prepared spices and perfumes. But they rested on the Sabbath in obedience to the commandment' — the women's Torah-observance (resting on the Sabbath) creates the narrative gap before the resurrection. Luke emphasizes their obedience to the commandment (kata tēn entolēn) — they were faithful Jews who kept the Sabbath even in grief. This detail serves the Lukan portrait of the first disciples as Torah-observant Jews whose Easter faith was a continuation of, not departure from, their Jewish covenant practice. The spices and perfumes prepared Friday evening would be brought to the tomb Sunday morning (24:1) — the completed preparation bracketed by the Sabbath rest.</p>"
  },
  "24": {
    "1": "<p>'On the first day of the week (tē de mia tōn sabbatōn = on the one of the weeks/Sabbaths), very early in the morning (orthrou batheōs = at deep/early dawn), the women took the spices they had prepared and went to the tomb' — 'the first day of the week' became the Christian Sunday, distinguishing resurrection celebration from the Jewish Sabbath. 'Deep dawn' (orthros bathys) is the precise pre-sunrise period, the darkest and earliest part of morning. The women's initiative — going to the tomb with prepared spices — is an act of devotion, not expectation of resurrection: they expected to complete the burial rites interrupted by the Sabbath.</p>",
    "2": "<p>'They found the stone rolled away from the tomb' — the stone (lithos) covering the tomb entrance was a large rolling stone (golel) placed in a groove cut at the tomb entrance. Archaeological examples of such rolling stones survive at Herodian-period tombs (e.g., the tomb at Khirbet Midras). These stones could weigh over a ton, requiring multiple men to move — the women's concern about who would roll it away (Mark 16:3) was practically grounded. The stone already rolled away (apokekylistai = rolled away, perfect tense indicating prior completed action) removes the women's logistical obstacle and introduces the first anomaly.</p>",
    "3": "<p>'But when they entered, they did not find the body of the Lord Jesus' — Luke's explicit 'the body of the Lord Jesus' (to sōma tou kyriou Iēsou) uses the full post-resurrection title (Kyrios/Lord) to describe what they expected to find — a corpse. The non-finding (ouch heuron) is the foundational datum of the Easter narrative: the tomb is empty. The tomb's emptiness is a necessary but not sufficient condition for resurrection faith — it could be explained by body removal (John 20:15 records Mary's initial assumption). The angels (v4) provide the interpretive framework that transforms empty-tomb into resurrection-announcement.</p>",
    "4": "<p>'While they were wondering about this, suddenly two men in clothes that gleamed like lightning stood beside them' — 'two men' (andres dyo) in Luke/John versus one angel in Matthew and Mark. Two witnesses satisfy the Deuteronomic requirement for establishing truth (Deut 19:15). The gleaming appearance (en esthēti astraptousē = in lightning-flashing clothing) echoes the transfiguration (9:29: Jesus's clothing 'became as bright as a flash of lightning') and the standard OT theophany-appearance vocabulary for divine messengers. The sudden appearance (epestēsan autais = stood by them, same verb as Acts 1:10 for the ascension angels) is the standard Lukan angelic arrival formula.</p>",
    "5": "<p>'In their fright the women bowed down with their faces to the ground, but the men said to them: Why do you look for the living among the dead?' — the rhetorical question ('why do you look for the living among the dead?') is the interpretive pivot of the resurrection narrative. Zētein (seek/look for) among the dead (among the nekroi = corpses/dead ones) frames the error: they have come expecting death and found life. The living (ton zōnta) in contrast to the dead (meta tōn nekrōn) is the ontological reversal of the resurrection. Luke's angels ask a question rather than simply declare facts — the question format invites the women (and the reader) to reorient their expectations.</p>",
    "6": "<p>'He is not here; he has risen! Remember how he told you, while he was still with you in Galilee' — the announcement follows the pattern of OT angelic speech: declaration followed by grounds ('remember...'). The risen Jesus is connected to the Galilean Jesus through memory — the resurrection does not create a new person but vindicates and transforms the historical one. Luke alone emphasizes the Galilean location of the predictions ('while he was still in Galilee,' v6; cf. 9:22, 9:44) rather than meeting the disciples in Galilee (Matthew 28:7, 10). Luke's resurrection appearances remain in Jerusalem — his geographical theology (movement toward Jerusalem) continues through Acts (beginning in Jerusalem).</p>",
    "7": "<p>'The Son of Man must be delivered over to the hands of sinners, be crucified and on the third day be raised again' — the angels quote Jesus's passion predictions (9:22, 44; 18:31-33) back to the women. 'Must' (dei = it is necessary, divine necessity) frames the passion-resurrection as divinely ordained, not human accident. 'Delivered over' (paradothēnai = handed over, the Passion word) into 'the hands of sinful men' (cheiras anthrōpōn hamartōlōn) echoes Daniel 7:25 (the saints delivered into the hands of the enemy). The third-day prediction was stated before the crucifixion; its fulfillment authenticates Jesus's prophetic authority and the divine plan's reliability.</p>",
    "8": "<p>'Then they remembered his words' — anamnēsis (memory/recollection) is one of Luke's resurrection-epistemology concepts: the risen Jesus is recognized and understood through the recovery of prior words and promises. The disciples on the Emmaus road have their memories opened (v27, 44-45); the women at the tomb 'remember his words.' Memory activated by encounter with the risen Christ is the Lukan model of Easter faith: faith is not primarily new information but the correct interpretation of what had already been said and seen. The disciples had heard the predictions but not understood them (18:34); the resurrection makes understanding possible.</p>",
    "9": "<p>'When they came back from the tomb, they told all these things to the Eleven and to all the others' — the women become the primary resurrection witnesses by delivering the Easter announcement to the male disciples. Luke names the Eleven (not twelve — Judas has gone, leaving eleven) as the core group. 'All the others' (tois loipois pasin) indicates a broader community beyond the Eleven — Luke 24:33 will show a group in Jerusalem larger than the Eleven. The women's witness is delivered as announcement, not as private information: they reported (apēggeilan = announced, the word for public reporting) to all.</p>",
    "10": "<p>'It was Mary Magdalene, Joanna, Mary the mother of James, and the others with them who told this to the apostles' — Luke names three women and adds 'the others with them,' consistent with the group of women from Galilee mentioned throughout. Mary Magdalene appears in all four Gospels as the primary Easter witness. Joanna is uniquely Lukan (8:3 — wife of Chuza, Herod's steward), connecting the resurrection witness to the Herodian court. Mary of James is identified with 'the other Mary' (Matt 27:61; 28:1) and possibly with Mary the wife of Clopas (John 19:25). The named women function as identifiable, verifiable witnesses in Luke's historical framework.</p>",
    "11": "<p>'But they did not believe the women, because their words seemed to them like nonsense (lēros = idle talk, nonsense)' — lēros is a medical term used by Hippocrates for the delirium of fever, dismissed talk. The male disciples' response illustrates the cultural reality: women's testimony was discounted in first-century Jewish legal contexts (Josephus Antiquities 4.219: women not admitted as witnesses 'on account of the levity and boldness of their sex'). Luke records this dismissal without apologizing for it — the implausibility of women as invented resurrection witnesses is an argument for historical reliability: a fabricated account would have used men. The disciples' disbelief is the foil for Peter's investigation (v12).</p>",
    "12": "<p>'Peter, however, got up and ran to the tomb. Bending over, he saw the strips of linen lying by themselves, and he went away, wondering to himself what had happened' — Luke's Peter-at-the-tomb narrative (absent from some manuscripts but likely original) parallels John 20:3-10. Peter's response to women's testimony — action rather than dismissal — marks him as the investigator among the skeptics. The burial cloths lying alone (ta othonia keiamena = the linen wrappings lying) without the body are the physical evidence that the body was not simply removed: grave-robbers would not unwrap a corpse. Peter 'marveled' (thaumazōn = wondering) — curiosity not yet faith, but the first step beyond dismissal.</p>",
    "14": "<p>'They were talking with each other about everything that had happened' — the imperfect verb (hōmiloun = were conversing, an ongoing discussion) captures the extended nature of the Emmaus disciples' discussion. Homilein (to converse/talk) is the root of homily — the Emmaus road is the first Christian homily in the sense of extended theological discussion. The 'everything that had happened' (panta ta symbebēkota = all the things that had come together) frames the passion events as data requiring interpretation — which is exactly what the unrecognized Jesus will provide. They have the facts without the meaning; he will supply the hermeneutic.</p>",
    "15": "<p>'As they talked and discussed these things with each other, Jesus himself came up and walked along with them' — the risen Jesus's approach is gradual and physical ('came up and walked along' — the normal vocabulary of human walking). Luke's resurrection body theology is consistently physical: Jesus walks, eats, shows wounds. The unrecognized approach echoes the OT angelophany pattern (Gen 18:1-2 — three 'men' appear to Abraham) and the Servant of the LORD who 'had no form or majesty that we should look at him' (Isa 53:2). Recognition is delayed not by disguise but by a divinely imposed impediment (v16).</p>",
    "16": "<p>'But they were kept from recognizing him (hoi de ophthalmoi autōn ekratounton tou mē epignōnai auton = their eyes were being held/constrained not to recognize him)' — the verb kratein (to hold/constrain) is in the imperfect passive, indicating a sustained divine action: their eyes were being held back. The theological passive (God as implied agent) places the non-recognition under divine control: they needed to hear the Word before recognition could come. The narrative structure — delayed recognition followed by sudden opening (v31: 'their eyes were opened') — is Luke's resurrection epistemology: Scripture-interpretation precedes and enables visual recognition.</p>",
    "17": "<p>'He asked them: What are you discussing together as you walk along? They stood still, their faces downcast' — the question from the stranger is the teacher's Socratic technique: entering a conversation without revealing prior knowledge to let the questioner articulate their own understanding (or misunderstanding). The disciples' 'standing still, their faces downcast' (estathēsan skythrōpoi = stood still, looking gloomy) is the posture of grief and shattered hope. The Greek skythrōpos (gloomy-faced) appears only here and in Matt 6:16 (the face of hypocritical fasting). Their emotional state — despondence — will be explicitly named in v21: 'we had hoped that he was the one...'</p>",
    "18": "<p>'One of them, named Cleopas' — Cleopas is the only named Emmaus disciple; the other is unidentified (church tradition has suggested Luke himself, based on the detailed narration suggesting eyewitness perspective). Cleopas is mentioned only here in the NT; a Clopas appears in John 19:25 (Mary his wife stood at the cross), and patristic tradition identifies them. Cleopas's surprise at the stranger's ignorance ('Are you the only one visiting Jerusalem who does not know...?') is ironic: the one who knows most about these events acts as if he knows nothing, leading the disciples to tell the story they need to re-examine.</p>",
    "19": "<p>'About Jesus of Nazareth — he was a prophet, powerful in word and deed before God and all the people' — the disciples' Christology at this point is prophet-level: 'a prophet, powerful in word and deed' (prophētēs dynatos en ergō kai logō). This is the prophet-Christology of Deut 18:15-18 (the coming prophet like Moses) — a lower category than Messiah or Son of God. Luke 7:16 records the same response to Jesus from the crowd after the Nain resurrection: 'A great prophet has appeared among us.' The Emmaus disciples' inadequate Christology is precisely what Jesus will address: prophet is correct but insufficient; Messiah who suffers and rises is the full truth (v26).</p>",
    "20": "<p>'The chief priests and our rulers handed him over to be sentenced to death, and they crucified him' — the disciples' summary of the passion uses the technical vocabulary: 'handed over' (paredōkan = the Passion word paradidōmi), 'sentenced to death' (krima thanatou = judgment of death, the formal Roman condemnation), 'crucified' (estaurōsan). The attribution of agency is shared: 'our rulers' (Jewish leadership) plus the implied Roman execution. The disciples have the facts but interpret them as definitive defeat — the Messiah cannot have died like a criminal. Jesus will reinterpret the same facts through the prophetic lens (v27).</p>",
    "21": "<p>'But we had hoped (hēmeis de ēlpizomen = we were hoping) that he was the one who was going to redeem Israel (ho mellōn lytrousthai ton Israēl). And what is more, it is the third day since all this happened' — 'we had hoped' — the imperfect tense captures past hope now extinguished. Lytrousthai (to redeem/liberate) is the Exodus-redemption vocabulary: Israel's redemption from Egypt (Exod 6:6; Ps 77:15) is the paradigm. Their hope was a liberation Messiah — the restoration of David's kingdom (Acts 1:6: 'will you at this time restore the kingdom to Israel?'). 'The third day' — they know the timing from the predictions but cannot yet interpret it as confirmation. They have the timetable without the expectation it encoded.</p>",
    "22": "<p>'In addition, some of our women amazed us. They went to the tomb early this morning' — the disciples relay the women's testimony to the unrecognized Jesus. Their phrase 'amazed us' (exestēsan hēmas) indicates the women's report disrupted their settled framework of grief, but not enough to produce faith. They report the women's testimony as perplexing anomaly, not confirmed fact: the women's words were 'nonsense' (v11) to some, but Cleopas and his companion at least registered them as worth mentioning. The retelling shows the resurrection evidence circulating within the community before recognition.</p>",
    "23": "<p>'But they didn't find his body. They came and told us that they had seen a vision of angels, who said he was alive' — the reduction of 'he has risen' (v6) to 'a vision of angels who said he was alive' shows how the disciples processed the women's report: as a visionary experience with an angelic message, not a physical fact. The word horama (vision) in Luke typically refers to genuine divine visions (Acts 9:10-12; 10:3; 18:9), not hallucinations — but even a genuine angel-vision stops short of personal encounter. The disciples need the risen Jesus himself, not reports about angels, to transform information into faith.</p>",
    "24": "<p>'Then some of our companions went to the tomb and found it just as the women had said, but they did not see him' — the 'companions' who investigated (Peter in v12; John 20:3-8 adds the Beloved Disciple) confirmed the empty tomb and burial cloths but did not see Jesus. The empty tomb plus linen cloths plus angels' testimony to women plus investigating disciples — the cumulative evidence is substantial but produces only 'wondering' (v12: ethaumazen). The absent Jesus is the key datum: the empty tomb is explicable multiple ways; the risen Jesus requires encounter, not just evidence.</p>",
    "25": "<p>'He said to them: How foolish you are (anoētoi = without understanding, lacking comprehension), and how slow to believe all that the prophets have spoken!' — the rebuke uses anoētos (literally 'without nous/mind' — not stupid but not understanding), the word Paul uses for those who have not grasped spiritual truth (Rom 1:14; Gal 3:1). 'Slow to believe all that the prophets have spoken' (bradeis tē kardia tou pisteuein = slow of heart to believe) identifies the heart, not the intellect, as the locus of faith-failure. The hermeneutical problem is not lack of information (they know the facts) but wrong interpretive framework — they expected a different kind of Messiah than the prophets described.</p>",
    "26": "<p>'Did not the Messiah have to suffer these things and then enter his glory?' — the theological thesis of Jesus's Emmaus homily: Messianic suffering (the cross) and Messianic glory (resurrection/ascension) are not contradictory but sequential and necessary (dei = it was divinely necessary). The Messiah who suffers is attested throughout the Prophets and Writings; the disciples' error was selective reading — taking the glory texts and ignoring the suffering texts. Isaiah 53, Psalm 22, Psalm 69, Zechariah 9-13, and Daniel 9 all contain elements that, in retrospect, pointed to a suffering Messiah. The church's subsequent reading of these texts in light of Christ is grounded in this moment.</p>",
    "27": "<p>'And beginning with Moses and all the Prophets, he explained to them what was said in all the Scriptures concerning himself' — the Emmaus homily is the first systematic Christian biblical hermeneutic: the whole of Scripture (Moses = Torah; the Prophets = Nevi'im; together suggesting the full HB canon) interpreted as pointing to Christ. 'Explained' (diermēneusen = thoroughly interpreted/translated) is the thorough-translation word — the same root as hermēneias (hermeneutics). The phrase 'concerning himself' (peri heautou) is the hermeneutical key: Scripture's ultimate subject is the person of Christ, and the resurrection provides the lens for its correct interpretation.</p>",
    "28": "<p>'As they approached the village to which they were going, Jesus continued on as if he were going further' — the 'as if to go further' gesture is part of the host-guest protocol: the guest does not presume hospitality but makes the host offer it explicitly. The same dynamic appears in Gen 18:3 (Abraham urging the three visitors to stay) and in the Lot/angels episode (Gen 19:2). Jesus does not force himself into their hospitality; the disciples must actively invite him. The moment of invitation (v29) becomes the moment of eucharistic recognition (v30-31) — the breaking of bread reveals what the road conversation had prepared but not disclosed.</p>",
    "29": "<p>'But they urged him strongly: Stay with us, for it is nearly evening; the day is almost over. So he went in to stay with them' — the urgency of invitation ('urged strongly' = parebiasthēsan = they pressed him strongly) is the disciples' act of hospitality that creates the eucharistic space. Evening (hespera = evening) echoes the Last Supper setting (22:14: 'when the hour came') and daily prayer patterns (evening as the time of sacrifice and prayer in Judaism, Ps 55:17; Acts 3:1). The transition from road-walk to table-meal is Luke's resurrection geography: recognition comes at the table, not on the road — through broken bread, not through expounded Scripture alone.</p>",
    "30": "<p>'When he was at the table with them, he took bread, gave thanks, broke it and began to give it to them' — the four-action eucharistic formula (took, gave thanks, broke, gave) exactly mirrors the Last Supper (22:19) and the feeding of the five thousand (9:16). Luke uses this precise vocabulary (lambanō/eulogeō or eucharistō/eklasen/edidou) consistently to mark eucharistic events. The recognition that follows is not from the words of Scripture alone but from this physical, sacramental act. Luke's theology of the Eucharist and resurrection-recognition is inseparable: the risen Lord is encountered at the breaking of bread, consistent with 1 Corinthians 11:26 ('you proclaim the Lord's death until he comes').</p>",
    "31": "<p>'Then their eyes were opened and they recognized him, and he disappeared from their sight' — 'their eyes were opened' (diēnoichthēsan hoi ophthalmoi autōn) reverses v16: the divine holding-back is now replaced by divine opening. The vocabulary of opened eyes echoes Gen 3:7 (Adam and Eve's eyes 'were opened' after eating) and 2 Kings 6:17 (Elisha's servant's eyes opened to see the angelic army). Recognition (epegnōsan = fully knew/recognized, intensive form of ginōskō) is the goal of the whole Emmaus narrative. Immediately after recognition, he 'became invisible from them' (aphantos egeneto = became unseen/invisible) — the resurrection body is visible by the Spirit's gift, not by normal optics.</p>",
    "32": "<p>'They asked each other: Were not our hearts burning within us while he talked with us on the road and opened the Scriptures to us?' — the retrospective burning heart (kaiomenē hēn hē kardia hēmōn = our heart was burning) is the post-recognition awareness of presence that was felt but not identified. In OT theophany and prophetic experience, fire/burning is the sensory signature of divine presence (Exod 3:2; Jer 20:9: 'his word was in my heart like a burning fire'). The disciples' hearts knew what their eyes could not yet see: the Scriptures-opening and the road-conversation were encounters with the risen Lord before the eucharistic recognition made it explicit.</p>",
    "33": "<p>'They got up and returned at once to Jerusalem. There they found the Eleven and those with them, assembled together' — the Emmaus disciples' immediate return to Jerusalem (a 7-mile walk back, after an 11-km outward journey, likely arriving late evening) is the response of resurrection-witness: personal encounter creates urgent communal announcement. 'The Eleven and those with them, assembled together' is Luke's picture of the Jerusalem community awaiting reports. The community assembled (hēthroismenos = gathered together) is the pre-Pentecost community waiting for confirmation. Their gathering anticipates the ongoing assembly (synagōgē, ekklēsia) of the early church.</p>",
    "34": "<p>'And saying: It is true! The Lord has risen and has appeared to Simon' — the assembly announces the prior appearance to Simon (Peter): 'he has appeared to Simon' (ōphthē Simōni). This brief mention matches Paul's priority sequence: 'he appeared to Cephas, then to the Twelve' (1 Cor 15:5) — the Peter-appearance is the first resurrection appearance to any disciple, predating even the Emmaus disciples' recognition. Luke narrates this appearance only in retrospect (through the community's announcement); the Petrine appearance is not narrated in Luke but its historical primacy is affirmed. The community already has resurrection faith before the Emmaus disciples arrive.</p>",
    "35": "<p>'Then the two told what had happened on the way, and how Jesus was recognized by them when he broke the bread' — the Emmaus disciples' report focuses on two elements: the road (the Scriptures-opening) and the breaking of bread (the eucharistic recognition). Luke's summary of the Emmaus story centers on these two: word and sacrament. The early Christian pattern of gathering for 'the apostles' teaching and fellowship, the breaking of bread and the prayers' (Acts 2:42) is prefigured here — the resurrection encounter is mediated through Scripture-interpretation and eucharistic table-fellowship, establishing the ongoing form of post-Easter Christian community.</p>",
    "36": "<p>'While they were still talking about this, Jesus himself stood among them and said to them: Peace be with you (Eirēnē hymin = peace to you)' — the sudden appearance in the midst of the assembled group (Jesus simply appearing in a room that presumably had secured entrance — cf. John 20:19: 'doors were locked') is Luke's most direct statement of the resurrection body's new properties. The greeting 'Peace' (shalom/eirēnē) is the standard Jewish greeting, but in this context it is the risen Lord's fulfillment of his pre-crucifixion promise: 'Peace I leave with you; my peace I give you' (John 14:27). The peace given is not merely social courtesy but eschatological shalom.</p>",
    "37": "<p>'They were startled and frightened, thinking they saw a ghost (pneuma = spirit/ghost)' — the disciples' fear and the pneuma-hypothesis (they saw a spirit, not a bodily risen person) is precisely the docetic interpretation that Luke counters with the physical proofs of vv39-43. The word pneuma in Greek can mean 'wind,' 'breath,' 'spirit,' and (in popular belief) 'ghost.' The disciples' hypothesis was not theologically sophisticated docetism but the common folk-belief in the spirits of the dead as incorporeal shades. Luke's counter-evidence (flesh, bones, wounds, food) is directed against any non-physical resurrection interpretation.</p>",
    "38": "<p>'He said to them: Why are you troubled, and why do doubts rise in your minds?' — 'doubts' (dialogismoi = reasonings/questionings) are the internal debates that prevent faith. The same word is used in 2:35 (the sword that will pierce Mary's soul to reveal dialogismoi), 5:22 (Jesus knowing the Pharisees' reasonings), and 9:46 (disciples' argument about greatness). The risen Jesus addresses the cognitive dimension of unbelief: the 'troubled heart' (tarassō = to agitate, disturb) is the emotional state; the 'reasonings in your heart' are the intellectual obstacles. He addresses both: the emotional through his peaceful presence and the intellectual through physical evidence (vv39-43).</p>",
    "39": "<p>'Look at my hands and my feet. It is I myself! Touch me and see; a ghost does not have flesh and bones (sarx kai ostea), as you see that I have' — the invitation to touch (psēlaphēsate = handle/feel; cognate of psallo, the root of Psalm) is the most direct anti-docetic statement in Luke. 'Flesh and bones' (sarx kai ostea) rather than 'flesh and blood' (the normal OT phrase for mortal humanity; cf. 1 Cor 15:50: 'flesh and blood cannot inherit the kingdom') may be theologically intentional: the resurrection body has material continuity (bones) and physical presence (flesh) but is no longer limited by the mortal constraints of blood/death. The wounds in hands and feet confirm identity continuity: the risen Lord is the crucified Jesus.</p>",
    "40": "<p>'When he had said this, he showed them his hands and feet' — the physical display of the crucifixion wounds establishes identity continuity between the crucified Jesus and the risen Christ. John 20:27 adds 'put your finger here and see my hands; and put out your hand and place it in my side' — the same evidentiary offer. The wounds that caused death are carried into the resurrection body as identifying marks, not healed away: 1 Corinthians 15:44's 'spiritual body' (sōma pneumatikon) still bears the marks of the specific human life that was crucified. The resurrection transforms but does not erase; it glorifies but does not anonymize.</p>",
    "41": "<p>'And while they still did not believe it because of joy and amazement (apo tēs charas kai thaumazontōn autōn = from their joy and their marveling), he asked them: Do you have anything here to eat?' — 'did not believe because of joy' is a psychologically precise description: overwhelming positive emotion can produce a suspension of belief as much as grief can. The disciples were in the emotional equivalent of 'this is too good to be true.' The request for food is Jesus's own evidentiary move: eating is the most immediate proof of physical bodily presence. Ghosts and visions do not eat; a physical body with metabolism can and does.</p>",
    "42": "<p>'They gave him a piece of broiled fish' — the fish (ichthys) as resurrection-meal food connects to the Galilean post-resurrection meal of John 21:9-14 (fish on charcoal fire) and to the feeding of the five thousand (John 6:11, fish distributed). The ichthys acronym (Iēsous Christos Theou Yios Sōtēr = Jesus Christ Son of God Savior) became the earliest Christian symbol, with roots in this post-resurrection fish-eating. Luke's simple detail — 'broiled fish' (ichthyos optou = fish roasted/broiled) — locates the resurrection appearance in ordinary domestic life, not a supernatural setting: the risen Lord eats the same food as common Galilean meals.</p>",
    "43": "<p>'And he took it and ate it in their presence' — 'in their presence' (enōpion autōn = before/in front of them) emphasizes the public, witnessed character of the meal. The risen Jesus eats, demonstrating physical resurrection to multiple witnesses simultaneously. 1 Corinthians 15:6 (appeared to 500 at once) points to the communal witness dimension. The act of eating in the presence of witnesses is the final anti-docetic proof: this is not a vision, not a ghost, not a subjective experience — it is a bodily act witnessed by multiple people in a shared physical space. Luke's resurrection apologetic is complete: the body is real, continuous, touchable, and eating.</p>",
    "44": "<p>'He said to them: This is what I told you while I was still with you: everything must be fulfilled (plērōthēnai) that is written about me in the Law of Moses, the Prophets and the Psalms' — this is the only NT text that explicitly names all three sections of the Hebrew Bible (Torah/Law, Nevi'im/Prophets, Ketuvim/Writings — the last represented by its most prominent book, Psalms) as pointing to Christ. The three-part canon (TaNaK) was probably taking final form in the first century; Luke's explicit citation of all three sections gives the fullest NT statement of the hermeneutical unity of Scripture. 'Everything must be fulfilled' — the necessity-of-fulfillment principle governs the whole of Luke-Acts.</p>",
    "45": "<p>'Then he opened their minds so they could understand the Scriptures' — 'opened their minds' (diēnoixen autōn ton noun = opened their mind/intellect to understand) is the reverse of the closed-heart prophecy (Isa 6:9-10; Luke 8:10). The nous (mind/intellect) requires divine opening for scriptural comprehension, not merely intellectual effort. This moment is the foundation of all subsequent Christian biblical interpretation: the disciples' Scripture-reading after Easter is qualitatively different because their minds have been opened by the risen Christ himself. Acts 2-28 will demonstrate the results — Peter, Stephen, and Paul all interpret Scripture through this opened hermeneutic.</p>",
    "46": "<p>'He told them: This is what is written: The Messiah will suffer and rise from the dead on the third day' — the scriptural proof of Messiah's suffering and third-day resurrection is stated as summary without specific citation. The probable texts behind 'what is written' include: Hosea 6:2 ('on the third day he will restore us'), Isaiah 53 (the Servant's suffering and vindication), Psalm 16:10 (you will not abandon my soul to Sheol), and Jonah 1:17 (three days in the fish's belly, cited by Jesus in Matt 12:40). Luke presents the disciples as now possessing the hermeneutical key — the crucified and risen Messiah — to read these texts correctly.</p>",
    "47": "<p>'And repentance for the forgiveness of sins will be preached in his name to all nations, beginning at Jerusalem' — the commission summary has three elements: content (repentance for forgiveness of sins), authority (in his name), and geography (all nations, starting from Jerusalem). This is the summary statement of Acts' program: Acts 2 (Jerusalem), Acts 8 (Judea/Samaria), Acts 10-15 (Gentiles), Acts 16-28 (to the ends of the earth). 'In his name' (epi tō onomati autou = in/on the basis of his name) is the authority-claim: the name of Jesus carries the power of God (Acts 3:6; 4:12: 'There is no other name under heaven given to men by which we must be saved').</p>",
    "48": "<p>'You are witnesses (martyres) of these things' — the designation of the disciples as 'witnesses' formally commissions them as the authorized witnesses to the resurrection. Martys (witness) in Luke-Acts takes on its specialized meaning of one who testifies to personally observed events: Peter uses it of the Twelve's qualification ('someone who accompanied us from the beginning...and became with us a witness to his resurrection,' Acts 1:21-22). The witness-commission transforms the disciples' status from grief-stricken followers to legally constituted witnesses whose testimony will form the foundation of the church's proclamation.</p>",
    "49": "<p>'I am going to send you what my Father has promised; but stay in the city until you have been clothed with power from on high (dynamin ex hypsous = power from on high/above)' — 'what my Father has promised' (tēn epangelian tou patros mou) is the Holy Spirit, promised in Joel 2:28-29 (Acts 2:17) and in Jesus's farewell discourse (John 14:26; 16:7-13). 'Power from on high' (dynamis = power/miracle-power, ex hypsous = from the height, a divine-attribute designation) is the pre-Pentecost formulation. The disciples are commissioned for mission but not yet equipped: they must wait. Luke's theological sequencing — resurrection (24:46), commission (24:47-48), Pentecost (Acts 2:1-4) — structures the transition from Gospel to Acts.</p>",
    "50": "<p>'When he had led them out to the vicinity of Bethany (heōs pros Bēthanian = as far as toward Bethany), he lifted up his hands and blessed them' — the movement from Jerusalem toward Bethany (2 km east) on the Mount of Olives places the ascension in the Olivet area, consistent with Acts 1:12 ('they returned to Jerusalem from the Mount called Olivet'). Bethany was Jesus's base during Passion Week (Matt 21:17; Luke 21:37 — 'he spent the night on the Mount of Olives'). The lifted hands and blessing (eulogēsen autous = blessed them) is the Aaronic priestly gesture (Lev 9:22; Sirach 50:20-21): Jesus departs in the posture of the High Priest blessing the assembly. The priestly blessing is his final act before ascension.</p>",
    "51": "<p>'While he was blessing them, he left them and was taken up into heaven (anephereto eis ton ouranon = was carried up into heaven)' — the ascension is the unique Lukan contribution to the Synoptic tradition (only Luke and Acts narrate it; Matthew ends with the Galilean commission; Mark 16:19 adds a brief reference). The passive verb anephereto (was being carried/taken up) emphasizes divine initiative: the ascension is not Jesus's own effort but God's exaltation (cf. Phil 2:9: 'God highly exalted him'). The ascending blessing means the disciples receive the priestly benediction continuously as Jesus passes from earthly to heavenly existence — the blessing is his lasting gift to the church.</p>",
    "52": "<p>'Then they worshipped him and returned to Jerusalem with great joy' — 'they worshipped him' (proskynesantes auton = having bowed down before him/worshipped him) is the full proskynesid posture reserved in Luke for divine beings (4:7-8: Satan demands proskynesid; Jesus refuses to give it to anyone but God). The disciples give to the ascended Jesus what Jesus refused to give to Satan: worship. The joy (chara megalē = great joy) that fills them is the eschatological joy of the kingdom: the same phrase used at the angel's announcement to the shepherds (2:10: 'great joy for all the people'). Easter joy closes the Gospel as birth-joy opened it.</p>",
    "53": "<p>'And they stayed continually at the temple (diapantos en tō hierō = continually in the temple), praising God' — the Gospel ends where it began: in the temple at Jerusalem. Luke 1:5-22 opens in the temple with Zechariah; the Gospel closes with disciples in the temple praising God. The geographical and theological circle is complete: the story of Jesus that began with the announcement in the Jerusalem temple ends with the community, shaped by the resurrection, returning to the temple as the center of covenant worship. Acts 2 will show the Pentecost expansion from this Jerusalem base. The 'praising God' (ainountes ton theon) is the community's characteristic response to divine action throughout Luke (2:20; 19:37-38; 23:47).</p>"
  }
}

def main():
    c = load_comm('mkt-context', 'luke')
    merge_comm(c, LUKE_FILL)
    save_comm('mkt-context', 'luke', c)

    import json
    inter = json.load(open(ROOT / 'data' / 'interlinear' / 'luke.json'))
    total_miss = 0
    for ch in ['23', '24']:
        miss = [v for v in inter[ch] if v not in c.get(ch, {})]
        total = len(inter[ch])
        have = len(c.get(ch, {}))
        if miss:
            print(f'  ch {ch}: MISSING {sorted(miss, key=int)} ({have}/{total})')
            total_miss += len(miss)
        else:
            print(f'  ch {ch}: complete ({have}/{total})')

    overall_miss = sum(1 for ch in inter for v in inter[ch] if v not in c.get(ch, {}))
    total_vv = sum(len(inter[ch]) for ch in inter)
    print(f'  Overall luke/context: {total_vv - overall_miss}/{total_vv}')

if __name__ == '__main__':
    main()
