"""
MKT Context Commentary — Psalms chapters 134–139
Run: python3 scripts/zc-context-psalms-134-139.py

Key decisions in this range:
- Ps 134 closes the Psalms of Ascents (120-134) with a blessing exchange: upward then downward
- "Servants who minister by night" = Levitical night-watches in the temple
- Ps 135 is heavily anthological (Deut 7:6; Ps 115:3-8; 136:10-22) — documented at each verse
- Ps 136 Great Hallel: antiphonal refrain ki le'olam hasdo; sung at Passover (Matt 26:30 connection noted)
- Ps 137 explicitly exilic (Babylon); harps on willows (actually Euphrates poplars); imprecatory vv8-9
  treated with honest engagement — the dashing of infants is a lex talionis formula, not instruction
- Edom's role in Jerusalem's fall (Ps 137:7) — Obad 10-14; Lam 4:21-22
- Ps 138 "before the gods" (v1) = divine council setting
- Ps 139 four-movement structure; yasak (v13) = knit/weave; golem (v16) only OT occurrence;
  book-of-days pre-natal theology; imprecatory vv19-22 as circle response to opening scrutiny
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

PSALMS = {
  "134": {
    "1": '<p>Psalm 134 is the final Song of Ascents (Pss 120-134), and it functions as the closing liturgical exchange of the pilgrimage festival. The collection of Songs of Ascents begins in the distant journey (Ps 120: "I dwell in Meshech") and ends here in the temple courts at night. "Servants of the LORD who minister in the house of the LORD by night (<em>bĕlêlôt</em>)" — the overnight Levitical guard rotations (1 Chr 9:27-33; 23:30). The Mishnah (Middot 1:1-2) describes the night watchmen\'s circuit of the temple courts. This final Song of Ascents thus closes the pilgrimage journey where it arrives: in the sanctuary itself, calling those who serve there through the night to bless YHWH even when the pilgrims have returned home.</p>',
    "2": '<p>"Lift up your hands (<em>śĕʾû yĕdêkem</em>) in the holy place and bless the LORD" — the gesture of uplifted hands was the standard posture for blessing and prayer in ancient Israel (Ps 28:2; 63:4; 141:2; 1 Kgs 8:22; Lam 2:19). "Holy place (<em>qōḏeš</em>)" — the sanctuary; the priests and Levites ministering in the temple courts lift their hands in the direction of the Most Holy Place. The call to bless YHWH reverses the typical direction of blessing: usually YHWH blesses Israel (as in the Aaronic benediction, Num 6:24-26). Here Israel — specifically the Levites on night duty — bless YHWH. The exchange of blessing is the pulse of covenant relationship.</p>',
    "3": '<p>"May the LORD bless you from Zion, he who made heaven and earth" — the divine blessing in response (v. 3 answers the human blessing of vv. 1-2). The Zion location of divine blessing connects the particular (Jerusalem temple) with the universal (maker of heaven and earth). This exact combination — "maker of heaven and earth" as the one who blesses "from Zion" — also appears in Ps 121:2 and 124:8. The cosmic creator is the local covenant God, and his local sanctuary is the point from which cosmic blessing radiates. The blessing formula closes the pilgrimage collection: those who have come to Jerusalem (Pss 120-134) receive the blessing they came for.</p>'
  },
  "135": {
    "1": '<p>Psalm 135 is one of the most anthological psalms in the Psalter — it is woven together from phrases found throughout the Torah, Former Prophets, and other psalms (especially Ps 115 and 136). This intertextuality was probably intentional liturgical composition: by weaving together earlier sacred texts, the psalm creates a concentrated summary of covenant theology suitable for temple worship. The opening call "Praise the LORD; praise the name of the LORD" (<em>hallĕlû šēm-YHWH</em>) introduces the "name" (<em>šēm</em>) as the psalm\'s theological center — YHWH\'s self-disclosure and character, which the psalm will celebrate through his works in creation and history.</p>',
    "2": '<p>"You who stand in the house of the LORD, in the courts of the house of our God" — the address specifies the audience: the temple personnel serving in the courts. The "house of the LORD" and "courts of the house of our God" reflect the temple\'s spatial structure — outer courts accessible to all Israel, inner courts restricted to priests and Levites. The congregation standing in the outer courts and the Levites in the inner courts are all addressed. This liturgical specificity anchors the universal theology of the psalm (YHWH sovereign over all nations) in the concrete worship assembly of YHWH\'s particular people.</p>',
    "3": '<p>"Praise the LORD, for the LORD is good; sing praise to his name, for that is pleasant (<em>nāʿîm</em>)" — the double motivation for praise: YHWH\'s goodness (<em>ṭôb</em>) and the pleasantness (<em>nāʿîm</em>) of praising his name. <em>Nāʿîm</em> (pleasant, lovely, delightful) applies both to the experience of worship itself and to YHWH\'s character. The word also appears in Ps 133:1 ("How good and pleasant it is when God\'s people live together in unity") — the same root that describes covenantal community harmony now applied to covenantal praise. Worship is not merely obligatory but genuinely pleasant — an experience worth having for its own sake.</p>',
    "4": '<p>"For the LORD has chosen Jacob to be his own, Israel to be his treasured possession (<em>sĕgullāh</em>)" — Deut 7:6 almost verbatim: "the LORD your God has chosen you out of all the peoples on the face of the earth to be his people, his treasured possession." <em>Sĕgullāh</em> (treasured possession, special property) was an ANE term for the personal property of a king held separate from state treasury — a private treasure. Exod 19:5 uses it in YHWH\'s covenant address: "you will be my treasured possession (<em>sĕgullāh</em>) out of all nations." Israel is YHWH\'s personally held treasure — the basis of election, not a reward for merit.</p>',
    "5": '<p>"I know that the LORD is great, that our Lord is greater than all gods" — the henotheistic confession that moves toward monotheism. The formula "greater than all gods" acknowledges the existence of rival deities in the worldview of surrounding cultures while asserting YHWH\'s superiority over all of them. This formula appears also in Exod 18:11 (Jethro\'s confession), Ps 96:4-5, and Ps 97:9. The progression in the Psalter is from this henotheistic formula toward explicit monotheism (Isa 44:6-8; 45:5-6) — one God, not merely the greatest among many.</p>',
    "6": '<p>"The LORD does whatever pleases him (<em>kōl-ʾăšer-ḥāpēṣ ʿāśāh</em>), in the heavens and on the earth, in the seas and all their depths" — the formula of unrestricted divine sovereignty. No domain limits YHWH\'s action: heavens (the realm of the divine council and cosmic powers), earth (the historical realm of nations), seas (the chaos waters in ANE cosmology), and their depths (<em>kol-tĕhômôt</em> — the primordial abyss). This verse is almost exactly repeated in Ps 115:3 and echoed in Jonah 1:14 ("You, LORD, have done as it pleased you"). The freedom of divine action — doing "whatever pleases him" — is the foundation of the psalm\'s celebration of YHWH\'s historical acts.</p>',
    "7": '<p>"He makes clouds rise from the ends of the earth; he sends lightning with the rain and brings out the wind from his storehouses" — YHWH as controller of the weather cycle, a polemic against Baal (the storm-god) and Hadad (the rain-deity) of Canaanite religion. Jer 10:13 and 51:16 use nearly identical language ("He makes clouds rise from the ends of the earth"). The "storehouses (<em>ʾôṣĕrôt</em>)" of wind and rain are the divine treasury from which weather is dispensed (Job 38:22-23 — YHWH\'s storehouses of snow, hail, wind). By controlling the weather cycle, YHWH controls the agricultural calendar — the power Canaanite farmers attributed to Baal.</p>',
    "8": '<p>"He struck down the firstborn of Egypt, the firstborn of people and animals" — the tenth plague (Exod 12:29) cited as the premier example of YHWH\'s historical action. The psalm moves from creation sovereignty (vv. 6-7) to historical sovereignty (vv. 8-12), following the same pattern as Ps 136. The inclusion of "animals" alongside people specifies the totality of the plague (Exod 12:29 includes "firstborn of livestock"). In ANE theology, the firstborn of animals were also sacred — the Passover sacrifice of a firstborn lamb (Exod 12:3-5) was specifically the substitution of Israel\'s firstborn through the blood of a firstborn animal.</p>',
    "9": '<p>"He sent signs and wonders into your midst, Egypt, against Pharaoh and all his servants" — "signs and wonders (<em>ʾôtôt ûmôpĕtîm</em>)" is the technical formula for the Exodus miracles (Deut 4:34; 6:22; 7:19; 26:8). "Against Pharaoh and all his servants" — the wonders targeted the royal house specifically (as in Exod 11:5 — all the firstborn "from the firstborn of Pharaoh, who sits on the throne, to the firstborn of the female slave") because Pharaoh was the divine representative of Egyptian sovereignty, and YHWH\'s contest was with the Egyptian cosmic order, not merely its military power.</p>',
    "10": '<p>"He struck down many nations and killed mighty kings" — the transition from the Exodus plagues to the Transjordan and Canaanite battles. "Many nations" and "mighty kings" are summarizing language for the conquest narratives (Num 21; Josh 12 lists 31 defeated Canaanite kings). The movement in vv. 8-12 recapitulates the Pentateuch and Joshua: Egypt (v. 8-9) → Wilderness/Transjordan (vv. 10-11) → Canaan/inheritance (v. 12). The same sequence as the Exodus-to-Settlement narrative arc confirms that the land promise drove all of YHWH\'s historical acts.</p>',
    "11": '<p>"Sihon king of the Amorites and Og king of Bashan, and all the kingdoms of Canaan" — Sihon and Og became paradigmatic examples of divine victory (Num 21:21-35; Deut 2:26-3:11). They are cited together in at least twelve passages (Num 21; Deut 1, 2, 3, 4, 29, 31; Josh 2, 9, 12; Ps 136:19-20; Neh 9:22). Sihon ruled the fertile Transjordan plateau east of the Jordan; Og ruled Bashan (the modern Golan Heights), famous for its fortified cities and its king\'s enormous iron bed (Deut 3:11). Their defeat opened the land of Canaan for settlement. The pairing "Amorites and Bashan" would have been immediately recognizable to any Israelite worshiper.</p>',
    "12": '<p>"And gave their land as an inheritance (<em>naḥălāh</em>), an inheritance to his people Israel" — the land-as-inheritance theology (see Ps 105:11; Deut 12:9; Josh 11:23). <em>Naḥălāh</em> (inheritance, patrimony) emphasizes that the land is not simply conquered territory but a family estate given by divine gift through the covenant. The doubling of <em>naḥălāh</em> in this verse (inherited land given as inheritance) is emphatic: the whole point of the historical acts (vv. 8-11) was this — the gift of a place to belong, a homeland for the covenant people. The land as covenant gift underlies the NT theology of a new inheritance (1 Pet 1:4; Heb 9:15).</p>',
    "13": '<p>"Your name, O LORD, endures forever; your renown, O LORD, endures through all generations" — a reflection on YHWH\'s permanent reputation in history. The "name (<em>šēm</em>)" is YHWH\'s covenantal self-disclosure, his character as revealed in act; the "renown (<em>zēker</em>)" is the memorial by which he is known — the remembrance of his deeds. Exod 3:15 establishes the connection: the divine name "YHWH" is "my memorial (<em>zikrî</em>) for all generations." The permanence of the divine name means the permanent accessibility of covenant relationship across time — each generation encounters the same God who acted in Egypt and Canaan.</p>',
    "14": '<p>"For the LORD will vindicate (<em>yāḏîn</em>) his people and have compassion (<em>yitnĕḥam</em>) on his servants" — a covenant-legal promise. "Vindicate (<em>dîn</em>)" — YHWH will judge on behalf of his people, provide legal advocacy. This recalls Deut 32:36 (nearly verbatim), which is also quoted in Heb 10:30 in the context of the divine judgment that falls on those who spurn the covenant. "Have compassion" — <em>nāḥam</em> (comfort, relent, have compassion) is the same word as the divine "relenting" in Exod 32:14. The combination — legal vindication and compassionate relenting — describes the full character of the covenant Judge: rigorously just and deeply compassionate.</p>',
    "15": '<p>"The idols of the nations are silver and gold, made by human hands" — this verse begins an idol polemic (vv. 15-18) that is nearly verbatim from Ps 115:4-8. The reuse may be intentional: by repeating the well-known Ps 115 polemic, Ps 135 creates a liturgical echo within the temple worship context. The "silver and gold" of the idols (precious materials) contrasts with YHWH who "made heaven and earth" (v. 6) and "made clouds rise" (v. 7). The idols\' value is in their material; YHWH\'s value is in his acts. Made by human hands (<em>maʿăśēh yĕdê ʾādām</em>) — the critique: any god that can be manufactured is not ultimate.</p>',
    "16": '<p>"They have mouths, but cannot speak; eyes, but cannot see" — the idol polemic continues (Ps 115:5 verbatim). The six sense faculties listed (mouth, eyes, ears, nose in v. 17, hands, feet implied) demonstrate that the idols have the form of persons without the function of persons. In ANE belief, the ritual of "opening the mouth" (<em>pīt pî</em>) was performed on cult statues to animate them and make them capable of eating, speaking, and receiving worship. The psalm denies that any such animation is possible — the forms without function are permanently inert. Isa 44:9-20 develops this polemic most extensively.</p>',
    "17": '<p>"They have ears, but cannot hear; nor is there any breath (<em>rûaḥ</em>) in their mouths" — the breath-of-life test. <em>Rûaḥ</em> (breath, spirit, wind) is what distinguishes the living from the dead — Gen 2:7 (YHWH breathed the breath of life into Adam) and Ezek 37:1-14 (the valley of dry bones animated by the <em>rûaḥ</em>). The idols have no <em>rûaḥ</em> — they are as lifeless as the materials from which they were made. This is the decisive test in the contrast between YHWH and idols: YHWH is the source and giver of breath/spirit; idols can neither receive nor give it. The life-test reduces all idolatry to absurdity.</p>',
    "18": '<p>"Those who make them will be like them, and so will all who trust in them" — the climax of the idol polemic (identical to Ps 115:8). The makers and worshipers of idols become like what they worship — gradually losing the capacity for true perception, speech, and breath that the idols themselves lack. This is a principle of conformity in worship: we become what we worship. Paul develops this in Rom 1:21-25 (the idolater\'s "thinking became futile and their foolish hearts were darkened") and 2 Cor 3:18 (those who contemplate the glory of God "are being transformed into his image"). The inverse of idol-conformity is the transformation into divine likeness through worship of the living God.</p>',
    "19": '<p>"Praise the LORD, O house of Israel; praise the LORD, O house of Aaron" — the call-and-response liturgy that closes the psalm (vv. 19-20) mirrors Ps 115:9-11 and 118:2-4 almost verbatim. The three groups — house of Israel (all the people), house of Aaron (the high priests), house of Levi (the broader Levitical order in v. 20) — represent concentric circles of covenant obligation. The house of Israel constitutes the whole covenant assembly; the house of Aaron represents the priestly mediators; the house of Levi the larger serving class. The three-part structure mirrors the spatial organization of the temple (outer court, inner court, Levitical gatekeepers).</p>',
    "20": '<p>"Praise the LORD, O house of Levi; you who fear the LORD, praise the LORD" — the fourth group, "those who fear the LORD (<em>yirĕʾê YHWH</em>)," may refer to proselytes, God-fearers among the Gentiles, or simply all pious Israelites who do not fall into the priestly categories. The term appears in Ps 115:11 and 118:4 in the same liturgical position. In Second Temple Judaism, "those who fear the LORD" was applied to Gentile sympathizers who attached themselves to synagogue worship without full conversion (Acts 10:2 — Cornelius is described as "a devout man who feared God"). The psalm\'s inclusive ending hints at a universalizing direction for covenant worship.</p>',
    "21": '<p>"Blessed be the LORD from Zion, he who dwells in Jerusalem. Praise the LORD (<em>hallĕlû-yāh</em>)!" — the closing doxology matches the form of Ps 134:3: YHWH blessed "from Zion." The geographic specificity — "from Zion," "in Jerusalem" — grounds the psalm\'s cosmic theology (YHWH sovereign over heaven, earth, and seas) in the particular sanctuary where YHWH "dwells (<em>šōkēn</em>)." The <em>šōkēn</em> vocabulary (dwelling, tabernacling) is related to the Deuteronomic theology of YHWH "causing his name to dwell (<em>šākan</em>)" at the chosen place (Deut 12:11). The <em>Hallĕlû-yāh</em> closes the psalm as an echo of its opening.</p>'
  },
  "136": {
    "1": '<p>Psalm 136 is the Great Hallel — the psalm of antiphonal praise in which a leader declares each act of YHWH and the congregation responds with the refrain "for his steadfast love endures forever (<em>kî lĕʿôlām ḥasdô</em>)." The refrain appears 26 times, once per verse. This antiphonal structure is described in 2 Chr 7:3 (at Solomon\'s temple dedication) and Ezra 3:11 (at the laying of the Second Temple foundation) — the congregational response "<em>kî lĕʿôlām ḥasdô</em>" was the standard liturgical acclamation at major moments of covenant worship. By the Mishnaic period (m. Pesaḥim 10:6-7), Ps 136 was the Great Hallel sung at the Passover meal — making Matt 26:30 ("when they had sung a hymn") possibly a reference to this psalm after the Last Supper.</p>',
    "2": '<p>"Give thanks to the God of gods" — the superlative title in the refrain structure: YHWH is God above all other claimants to divinity. The same formula as Deut 10:17 ("the LORD your God is God of gods and Lord of lords"). The liturgical structure of the psalm means this verse was followed by the congregation\'s response "<em>kî lĕʿôlām ḥasdô</em>" — "for his steadfast love endures forever." This response grounds the theological claim (God of gods) in the relational quality that makes theology personal: <em>ḥeseḏ</em>, covenant loyalty. The greatest claim about God is answered by the most personal claim about his character.</p>',
    "3": '<p>"Give thanks to the Lord of lords" — the second superlative title, completing the triad with v. 1 (LORD) and v. 2 (God of gods). Deut 10:17 uses the same pair (God of gods / Lord of lords). Rev 17:14 and 19:16 apply this title to the risen Christ: "King of kings and Lord of lords." The psalm\'s liturgical repetition — each claim followed by the <em>ḥeseḏ</em> refrain — trains the congregation to associate divine greatness with covenant love rather than with power alone.</p>',
    "4": '<p>"To him who alone does great wonders" — the introduction of the creation and history sections (vv. 4-22). "Alone (<em>lĕbaḏdô</em>)" is the key word: no other being participates in the great wonders (<em>niplāʾôt gĕḏōlôt</em>). The divine works are singular — not the product of a pantheon\'s negotiation or a nature-cycle managed by competing deities, but the unilateral action of one God. "Great wonders" is the vocabulary of the Exodus traditions (Ps 72:18; 86:10; Job 5:9; 9:10) — establishing the theme that creation (vv. 5-9) and historical acts (vv. 10-22) are equally products of the one God\'s sole creative and saving power.</p>',
    "5": '<p>"Who made the heavens with wisdom (<em>bĕtĕbûnāh</em>)" — creation as an act of wisdom (<em>tĕbûnāh</em> — understanding, insight). Prov 3:19-20: "By wisdom the LORD laid the earth\'s foundations; by understanding he set the heavens in place; by his knowledge the watery depths were divided." Ps 104:24: "How many are your works, LORD! In wisdom you made them all." Creation is not arbitrary power but ordered intelligence — the cosmos reflects the divine wisdom that structured it. This theology becomes foundational for the Wisdom literature\'s claim that the same wisdom operating in creation is accessible to humans through Torah.</p>',
    "6": '<p>"Who spread out the earth above the waters (<em>ʿal-hammayim</em>)" — the creation cosmology: the flat earth resting on the primordial waters below (Gen 1:9-10; Ps 24:2: "he founded it on the seas and established it on the waters"). In the ANE cosmological picture, the earth was a disk floating on or resting above the cosmic underground waters (<em>tĕhôm rabbāh</em> — the great deep). The "spreading out (<em>rāqaʿ</em>)" of the earth echoes the "spreading out (<em>rāqîaʿ</em>)" of the heavens in Gen 1:6-8 — the same verb for the making of the visible firmament. YHWH\'s creative acts (vv. 5-9) mirror the first week of Gen 1.</p>',
    "7": '<p>"Who made the great lights" — the fourth day of creation (Gen 1:14-19): "God made two great lights." The psalm paraphrases the creation narrative, following its sequence. The "great lights (<em>ʾôrîm gĕḏōlîm</em>)" are distinguished only by their function (ruling day and night) rather than named as sun and moon — a deliberate avoidance of the Egyptian solar deity Ra and the Mesopotamian moon deity Sin, whose names the Hebrew words for sun (<em>šemeš</em>) and moon (<em>yārēaḥ</em>) might evoke in polemic context. The lights are demythologized: they are YHWH\'s creations, not deities.</p>',
    "8": '<p>"The sun to rule over the day" — the greater light (Gen 1:16). In Egyptian religion, the sun was Ra, the supreme deity whose daily journey across the sky was the central religious narrative. The psalm strips this mythological significance: the sun is YHWH\'s servant, its function is to "rule over the day" by providing light, not to be an object of worship. The antiphonal refrain that follows — "his steadfast love endures forever" — asserts that what motivates the sun\'s continued shining is YHWH\'s covenant love, not the sun deity\'s own nature or the demands of ritual. Creation is sustained by covenant love.</p>',
    "9": '<p>"The moon and stars to rule over the night" — the lesser light and the stars (Gen 1:16-18). In Mesopotamian religion, the moon (Sin/Nanna) and astral bodies (especially Venus/Ishtar) were major deities whose movements governed calendars, divination, and warfare decisions. Deut 4:19 explicitly warns Israel not to "look up to the sky and see the sun, the moon and the stars... and bow down to them." By placing moon and stars in the creation-by-divine-command sequence, Ps 136 strips all astral bodies of divine status — they are light-regulators for the night, serving the practical function of marking time. The same ḥeseḏ-refrain that follows the sun follows the moon: all creation alike serves under covenant love.</p>',
    "10": '<p>"Who struck down the firstborn of Egypt" — the pivot from creation (vv. 5-9) to history (vv. 10-22). The same God who made the sun and moon struck Egypt\'s firstborn. The continuity between cosmic creator and historical actor is the psalm\'s central theological claim: YHWH\'s ḥeseḏ operates at every scale, from cosmic structure to specific historical events. The transition is abrupt but intentional — Ps 136 is not a meditation on creation or history separately but on the single divine character (<em>ḥeseḏ</em>) that underlies both.</p>',
    "11": '<p>"And brought Israel out from among them" — Exod 12:51: "on that very day the LORD brought the Israelites out of Egypt." The language of Israel being "brought out (<em>wayyôṣēʾ</em>)" from among the Egyptians is the standard Exodus formula (Deut 5:6; 6:12; 13:5, 10; and dozens of occurrences). The Exodus is the paradigmatic act of divine <em>ḥeseḏ</em> in history — the event that defines YHWH as covenant-keeper, not merely as creator. Every subsequent use of "steadfast love" in the OT is colored by this defining act.</p>',
    "12": '<p>"With a mighty hand and an outstretched arm" — the standard anthropomorphic formula for the Exodus (Deut 4:34; 5:15; 7:19; 11:2; 26:8; Ps 44:3; Jer 32:21; Ezek 20:33-34). The "mighty hand (<em>yāḏ ḥăzāqāh</em>)" emphasizes irresistible divine power; the "outstretched arm (<em>zĕrôaʿ nĕṭûyāh</em>)" adds the spatial image of divine reach extending into history to rescue Israel. The formula became so standard that it functioned as a covenant-shorthand: to mention the "mighty hand and outstretched arm" was to invoke the entire Exodus tradition. The New Exodus prophets (Isa 40-55) would use the same imagery for the return from Babylon.</p>',
    "13": '<p>"Who divided the Red Sea (<em>gāzar yam-sûp</em>) in two" — the verb <em>gāzar</em> (to cut, divide, split) is unusually strong — not merely "parted" but cleaved in two, as a sword cuts. Ps 78:13 uses the same verb. The image of the sea being split into two halves emphasizes the completeness of the division — the people walked on dry ground between two walls of water (Exod 14:21-22). In Second Temple Judaism, the splitting of the sea was associated with the splitting of the Jordan (Josh 3-4) and later with Elijah\'s and Elisha\'s miracles with water — a typological series of covenant-defining sea-crossings.</p>',
    "14": '<p>"And brought Israel through the middle of it" — the crossing itself. The emphasis on "through the middle (<em>bĕtôkô</em>)" echoes Exod 14:22, 29 where Israel went "into the sea on dry ground, with a wall of water on their right and on their left." The geographic specificity — not around the sea, not carried over it, but through its middle — underlines the miraculous nature of the passage. In baptism theology (1 Cor 10:1-2 — "they were all baptized into Moses in the cloud and in the sea"), this passage through the waters became the pattern for covenant initiation through water.</p>',
    "15": '<p>"But swept Pharaoh and his army into the Red Sea" — Exod 14:27-28: "the water flowed back and covered the chariots and horsemen — the entire army of Pharaoh that had followed Israel into the sea. Not one of them survived." The specific mention of "Pharaoh (<em>parʿōh</em>) and his army" rather than merely "the Egyptians" emphasizes the defeat of the institutional power of Egyptian empire — not only soldiers but the royal military command itself was destroyed. The Song of Moses (Exod 15:4) celebrates: "Pharaoh\'s chariots and his army he has hurled into the sea."</p>',
    "16": '<p>"Who led his people through the wilderness" — the forty years of wilderness provision summarized in a single line. The guidance through the wilderness (<em>hammôlîk ʿammô bammidbar</em>) recalls the pillar of cloud and fire (Exod 13:21-22), the manna and quail (Exod 16), the water from the rock (Exod 17; Num 20), and the Sinai covenant (Exod 19-24). The brevity is liturgically appropriate — in the antiphonal structure, each act receives one line followed by the refrain. The wilderness period as a whole is a demonstration of sustained divine <em>ḥeseḏ</em>: forty years of daily provision in a humanly unlivable environment.</p>',
    "17": '<p>"Who struck down great kings" — the conquest narrative begins (vv. 17-22), parallel to Ps 135:10-12. "Great kings (<em>mĕlāḵîm gĕḏōlîm</em>)" — the same description as Deut 7:1; Josh 11:17 for the Canaanite city-states\' rulers. The word "great" is relative — compared to the Egyptian empire, Canaanite city-kings were minor — but their fortified cities were formidable obstacles for a nomadic people without siege equipment. The psalm\'s attribution of their defeat to YHWH\'s direct action (rather than Israelite military tactics) follows the theological interpretation of the conquest in Deut 7:17-24: "Do not be afraid of them; remember well what the LORD your God did to Pharaoh and to all Egypt."</p>',
    "18": '<p>"And killed mighty kings" — the repetition of the conquest theme intensifies the point: the same divine ḥeseḏ that sustained Israel through the wilderness now clears the land before them. "Killed (<em>wayyahărōg</em>) mighty kings" — the verb is direct and unambiguous. The conquest involved real military violence, and the psalm does not euphemize it. The theological framing is that YHWH\'s covenant love toward Israel required the removal of competing powers from the land YHWH had promised. The ethical difficulties of this theology have been engaged throughout Jewish and Christian interpretation history — the psalm presents it without apology as a fact of covenant history.</p>',
    "19": '<p>"Sihon king of the Amorites" — the paradigmatic Transjordan defeat (Num 21:21-31; Deut 2:26-37). Sihon refused Israel passage through his territory and attacked — and was decisively defeated. His capital Heshbon (modern Hesban, Jordan) was taken. The repeated pairing of Sihon and Og in liturgical texts (Ps 135:11; Neh 9:22; Deut 3:6; Josh 2:10) made them the canonical examples of YHWH\'s power over kings who opposed Israel\'s passage. The narrative of their defeat in Num 21 and Deut 2-3 functions as a paradigm: when kings resist YHWH\'s plan for Israel, they are defeated.</p>',
    "20": '<p>"And Og king of Bashan" — Og\'s defeat (Num 21:33-35; Deut 3:1-11). Og was the last of the Rephaim (Deut 3:11) — the legendary pre-Israelite giant-people of Canaan and Transjordan (Gen 14:5; 15:20; 2 Sam 21:16-22). The tradition of Og\'s extraordinary size (Deut 3:11 describes his iron bed as 9 cubits long, ~4.5m) gave him a legendary quality that amplified the significance of his defeat. If even the Rephaite king of fortified Bashan could not resist YHWH, no human power could. The two kings together (Sihon the Amorite + Og the Rephaite) represented different ancient threats — political and primordial — both overcome by the same ḥeseḏ.</p>',
    "21": '<p>"And gave their land as an inheritance (<em>naḥălāh</em>)" — as in Ps 135:12, the conquest is framed as a gift (<em>nātan</em>, gave) not a military achievement. The land already belonged to YHWH (Lev 25:23: "the land is mine; you are but aliens and strangers resident with me") — he gave it to Israel as <em>naḥălāh</em>, his own patrimony distributed to his people. The Jubilee land laws (Lev 25) were grounded in this theology: since YHWH gave the land, human ownership is always provisional and the land must periodically revert to its original distribution.</p>',
    "22": '<p>"An inheritance to his servant Israel" — the closing of the historical section (vv. 10-22). "His servant Israel" — <em>ʿabdô yiśrāʾēl</em> is the corporate servant title, applied to the nation as a whole (Isa 41:8; 44:1-2; 45:4). It is also the title for the Servant of YHWH in Isaiah\'s Servant Songs (Isa 42:1; 49:3: "you are my servant, Israel, in whom I will display my splendor"). The psalm\'s attribution of the "servant" title to Israel as a whole creates the background against which the Isaianic question of how the corporate servant Israel can perform what it has failed to do becomes the question that the individual Servant must answer.</p>',
    "23": '<p>"He remembered us in our low estate (<em>bĕšiplēnû</em>)" — the shift to first person ("us") marks the liturgical community\'s appropriation of the history. The "low estate" (<em>šiplēnû</em>) — the condition of being brought low, humiliated, stripped of status. The same word as Hannah\'s "humiliation" (<em>ʿānyî</em>, related root) in 1 Sam 1:11. The verse may have been composed in the exilic period: Israel in Babylon was literally in its lowest historical position since the Exodus. "He remembered us" — divine remembering (<em>zākar</em>) is always followed by divine acting (as in Exod 2:24-25). The congregation confesses that past divine remembering grounds present hope.</p>',
    "24": '<p>"And freed us from our enemies" — the liberation from the "low estate" of v. 23. The brevity leaves the specific enemies unspecified — making the verse applicable across multiple historical situations (Egypt, Philistia, Assyria, Babylon). The Psalter\'s liturgical genius is often precisely this typological openness: by not naming the specific enemy, the verse remains perpetually applicable to whatever "enemies" any generation faces. The pattern — low estate → divine remembering → liberation — is the recurring structure of covenant rescue throughout Israel\'s history.</p>',
    "25": '<p>"Who gives food (<em>nōtēn leḥem</em>) to every creature" — the expansion from Israel\'s particular history (vv. 10-24) to universal divine provision. The present tense ("gives") marks this as ongoing rather than historical. YHWH\'s provision of food for "every creature (<em>lĕkol-bāśār</em>)" — literally all flesh — echoes Ps 104:27-28 (all creatures look to YHWH for food in due season) and Gen 1:29-30 (YHWH provides food for all living things at creation). The closing before the final doxology (v. 26) places universal creation-care alongside Israel\'s particular covenant history — both are expressions of the same <em>ḥeseḏ</em>.</p>',
    "26": '<p>"Give thanks to the God of heaven (<em>ʾēl haššāmayim</em>)" — the title "God of heaven" is rare in the Psalms but common in the post-exilic period (Ezra 1:2; 5:11-12; 7:12, 21; Neh 1:4-5; 2:4, 20; Dan 2:18-19, 37, 44; Jonah 1:9). The prevalence of this title in post-exilic texts suggests Ps 136 may have its final form in that period — the period when "God of heaven" was the Persian imperial designation for the God of the Jews (Cyrus\'s decree in Ezra 1:2 uses the same title). The closing "<em>kî lĕʿôlām ḥasdô</em>" — "for his steadfast love endures forever" — is the 26th and final repetition, having covered creation, Exodus, wilderness, and conquest. Everything is grounded in and returns to <em>ḥeseḏ</em>.</p>'
  },
  "137": {
    "1": '<p>Psalm 137 is the most explicitly exilic text in the Psalter — it describes the experience of being in Babylon in historical present tense, almost certainly written during or immediately after the Babylonian captivity (587-539 BCE). "By the rivers of Babylon" — the two great rivers of Mesopotamia (Tigris and Euphrates) with their extensive canal systems made Babylon a water-rich landscape dramatically different from Judah\'s hills. Jewish exiles were settled in communities along these waterways (Ezek 1:1-3 — Ezekiel was by the Chebar river; Ezra 8:15 — exiles gathered by a canal). "We sat and wept (<em>gam-bākînû</em>)" — the weeping was ritualized mourning — perhaps at the river because ritual washing required water (cf. Ezek 1:1 — Ezekiel\'s visions came by the river).</p>',
    "2": '<p>"There on the poplars (<em>ʿărābîm</em>) we hung our harps" — the traditional translation "willows" is likely incorrect; the trees along the Euphrates and its canals were <em>ʿărābîm</em> (Euphrates poplars, <em>Populus euphratica</em>), which grow in rows along Mesopotamian waterways. Hanging the harps (<em>kinnôrôt</em>) on the trees was a symbolic act of musical suspension — the instruments silenced because Zion\'s worship could not continue in a foreign land. The harp was the primary instrument of the Levitical singers (1 Chr 25; 2 Chr 29:25). To hang up the harp was to stop being what they were: the singers of YHWH\'s praises.</p>',
    "3": '<p>"For there our captors asked us for songs, our tormentors demanded songs of joy (<em>śimḥāh</em>); they said, \'Sing us one of the songs of Zion!\'" — the request for performance entertainment from captors was a form of humiliation. The "songs of Zion (<em>šîrê ṣiyyôn</em>)" were the temple hymns — liturgical music tied to specific places, times, and purposes in the Jerusalem cult. To perform them as entertainment for captors was to desacralize them. The same "songs of Zion" are celebrated in Ps 87:7 and Pss 46, 48, 76, 84 — pilgrim songs tied to the physical experience of Zion. The exiles\' refusal to perform them as entertainment was an act of liturgical integrity.</p>',
    "4": '<p>"How can we sing the songs of the LORD while in a foreign land (<em>ʾereṣ nēḵār</em>)?" — the theological crisis of exile: the songs of YHWH were constitutively connected to the place of YHWH\'s presence. This was not merely cultural attachment but a profound theological question about whether YHWH\'s presence was portable. Deuteronomy had tied worship to "the place the LORD your God will choose" (Deut 12:5, 11, 14). Ezekiel would answer the question by having YHWH\'s <em>kābôd</em> depart from the temple before Babylon\'s destruction (Ezek 10-11) and then follow the exiles to Babylon — YHWH was present there too. But in this psalm, the theological problem is still raw: how does worship function without the sanctuary?</p>',
    "5": '<p>"If I forget you, Jerusalem, may my right hand forget its skill (<em>tiškāḥ yĕmînî</em>)" — the self-curse sworn by the professional musician: may my playing hand forget how to play. The harp player\'s right hand is his professional identity. The syntax in Hebrew is elliptical ("may my right hand forget") — the implied object is the skill/function of the hand. Some modern translations smooth this to "may my right hand wither," but the Hebrew simply omits the object, leaving the curse hauntingly incomplete. Jerusalem as the object of memory — the very city whose songs they refused to perform for entertainment — is what must never be forgotten.</p>',
    "6": '<p>"May my tongue cling to the roof of my mouth (<em>tiḏbaq-lĕšônî lĕḥikkî</em>) if I do not remember you, if I do not consider Jerusalem my highest joy (<em>ʾal rōʾš śimḥātî</em>)" — the second self-curse: may my voice fail if I fail to remember Jerusalem. The tongue-clinging-to-palate image appears in Lam 4:4 (the infants\' tongues cleave to the roof of their mouths for thirst — the siege condition). The phrase "highest joy (<em>ʾal rōʾš śimḥātî</em>)" — literally "at the head of my joy," the apex of all happiness. Jerusalem is not merely important but the organizing center of all joy for the psalmist. The professional singer whose highest joy should be music now places city above craft.</p>',
    "7": '<p>"Remember, LORD, what the Edomites did on the day Jerusalem fell. \'Tear it down,\' they cried, \'tear it down to its foundations!\'" — Edom\'s involvement in Jerusalem\'s destruction is documented in Obad 10-14 (the entire book condemns Edom for "standing aloof" and actively participating in Jerusalem\'s looting), Lam 4:21-22, and Ezek 25:12-14. Edom was Israel\'s closest kinship neighbor (descendants of Esau/Jacob\'s twin — Gen 36) — their participation in the sack was experienced as betrayal by a brother nation. The cry "tear it down (<em>ʿārû ʿārû</em>)" — strip it bare, raze it — was directed against the temple mount itself, demanding total destruction.</p>',
    "8": '<p>"Daughter Babylon, doomed to destruction (<em>bat bābel hašĕḏûḏāh</em>), happy is the one who repays you for what you have done to us" — the personification of Babylon as "daughter (<em>bat</em>)" follows the prophetic convention of personifying cities as women (Isa 47:1-15 — "Virgin Daughter Babylon"; Isa 37:22 — "Virgin Daughter Zion"). "Doomed to destruction (<em>hašĕḏûḏāh</em>)" — already-destined for destruction, a prophetic perfect (the destruction is so certain it is spoken of as already complete). This confidence was grounded in Isaiah\'s oracles (Isa 13-14; 47) against Babylon. The imprecation that follows is harsh — but its logic is lex talionis: what you did to us will happen to you.</p>',
    "9": '<p>"Happy is the one who seizes your infants and dashes them against the rocks" — the most disturbing verse in the Psalter, and one of the hardest passages in Scripture. Context essential: (1) This is lex talionis expressed as a beatitude — Babylon killed Judean infants during the sack of Jerusalem (Lam 2:20-21: "women have eaten their offspring... see, O LORD, those whom you have slaughtered... young men and young women"; Lam 4:4 — infants clinging to mothers dying). (2) The imprecation calls for what Babylon did to be done to Babylon — a precise mirror judgment. (3) Isa 13:16-18 prophesied exactly this for Babylon ("Their infants will be dashed to pieces before their eyes"). The psalm is not instruction but lament-prayer expressing the full horror of the exiles\' trauma and their reliance on divine justice. It is preserved in the canon as honest testimony to the depths of human suffering and the legitimacy of bringing even this pain to God.</p>'
  },
  "138": {
    "1": '<p>"I will praise you, LORD, with all my heart; before the gods (<em>nĕgeḏ ʾĕlōhîm</em>) I will sing your praise" — "before the gods" is one of the most discussed phrases in this psalm. Options: (1) the divine council / heavenly court (as in Ps 82:1; 89:7; Job 1-2) — YHWH is praised in the presence of the heavenly assembly; (2) before human judges and rulers (as in Exod 21:6; 22:8-9 where <em>ʾĕlōhîm</em> = judges); (3) at the temple where images of foreign gods might be present (less likely). The divine council reading fits best: the psalmist praises YHWH in the presence of the heavenly beings, asserting YHWH\'s superiority. This connects to v. 2 (YHWH\'s name above all) and v. 5 (the kings will sing when they hear YHWH\'s words).</p>',
    "2": '<p>"I will bow down toward your holy temple and will praise your name for your unfailing love and your faithfulness, for you have so exalted your solemn decree (<em>ʾimrātĕkā</em>) that it surpasses your fame (<em>šimkā</em>)" — a notoriously difficult verse. "You have exalted your word above all your name" — most natural reading: the divine word/promise has been fulfilled in a way that even exceeds YHWH\'s already great reputation. The fulfillment of the <em>ʾimrāh</em> (word, decree, promise) validates and magnifies the <em>šēm</em> (name, reputation). The word is the active expression of the name — when YHWH\'s spoken word is fulfilled, his name is glorified beyond what it was before the fulfillment.</p>',
    "3": '<p>"When I called, you answered me; you greatly emboldened me (<em>tarḥibēnî bĕnapšî ʿōz</em>)" — "you emboldened me" — literally "you enlarged my soul with strength/boldness." The spatial metaphor: <em>rāḥab</em> (enlarge, make wide) is the opposite of the narrow, constricted soul in distress (Ps 4:1: "give me relief from my distress; have mercy on me and hear my prayer"). YHWH\'s answer to prayer creates interior expansion — a courage and boldness that came from the experience of being heard and answered. This transformation through answered prayer is the experiential confirmation of the divine attributes celebrated in v. 2 (love and faithfulness).</p>',
    "4": '<p>"May all the kings of the earth praise you, LORD, when they hear what you have decreed" — the universal dimension: the divine word that emboldened the individual psalmist (v. 3) is also what will cause all kings of the earth to praise YHWH when they hear it. "What you have decreed (<em>ʾimrê-pîkā</em>)" — the words of your mouth, the divine oracles. The Zion pilgrimage eschatology again: kings come to Zion to hear YHWH\'s words (cf. Ps 68:29, 32; 72:10-11; Isa 2:2-4). The progression from individual prayer answered (v. 3) to universal royal praise (v. 4) is the psalm\'s trajectory: covenant experience of the one becomes the testimony that draws the many.</p>',
    "5": '<p>"May they sing of the ways of the LORD, for the glory of the LORD is great" — "the ways of the LORD (<em>darkê YHWH</em>)" — the patterns of divine action in history, the moral logic of YHWH\'s governance. Knowing YHWH\'s "ways" is deeper covenant knowledge than knowing his "acts" (Ps 103:7: "He made known his ways to Moses, his deeds to the people of Israel" — Moses knew the deeper pattern; the people saw only specific acts). The kings are invited to sing not just about specific divine acts but about the overarching pattern of YHWH\'s governance — the <em>ḥeseḏ</em> and <em>ʾĕmet</em> of v. 2 as the characteristic mode of divine engagement with history.</p>',
    "6": '<p>"Though the LORD is exalted, he looks kindly on the lowly (<em>šāpāl</em>); though lofty, he sees the arrogant (<em>gābōah</em>) from afar" — the fundamental reversal of normal social logic. In ANE royal ideology, the king on his throne sees only those presented to him — the powerful, the wealthy, the well-connected. YHWH, though supremely exalted (<em>rām</em>), attends specifically to the lowly (<em>šāpāl</em> — brought low, humbled). Mary\'s Magnificat (Luke 1:51-52) draws directly on this verse: "He has brought down rulers from their thrones but has lifted up the humble." The arrogant he "sees from afar" — not with the intimacy of personal engagement but with the cold distance of a sovereign who acknowledges their existence but grants them no access.</p>',
    "7": '<p>"Though I walk in the midst of trouble, you preserve my life; you stretch out your hand against the wrath of my foes; your right hand will save me" — the confidence based on the theological principle of v. 6. Because YHWH attends to the lowly, the psalmist can walk "in the midst of trouble (<em>bĕqereb ṣārāh</em>)" with confidence. "You preserve my life (<em>tĕḥayyênî</em>)" — the causative form of "to live" — YHWH actively keeps the psalmist alive. "Stretch out your hand against the wrath of my foes" — the same divine arm that reached into Egypt to rescue Israel (Exod 6:6 — "outstretched arm") reaches into personal crisis to rescue the individual. The cosmic rescue pattern applies at personal scale.</p>',
    "8": '<p>"The LORD will vindicate me (<em>yigmōr baʿăḏî YHWH</em>); your love, LORD, endures forever — do not abandon the works of your hands" — "vindicates me (<em>gāmar</em>)" — will complete or perfect on my behalf; will accomplish what he has started for me. The theological grounding: YHWH\'s "love (<em>ḥeseḏ</em>) endures forever" — the same <em>ḥeseḏ</em> refrain as Ps 136, here applied to the individual. "Works of your hands (<em>maʿăśēh yāḏêkā</em>)" — a creation image: as YHWH does not abandon what he has made in creation, he does not abandon what he has made in covenant relationship. The psalmist is YHWH\'s workmanship (Eph 2:10 uses the same logic: "we are God\'s handiwork") — the creator\'s investment ensures completion.</p>'
  },
  "139": {
    "1": '<p>Psalm 139 is one of the most theologically profound meditations in the Psalter, structured in four movements: divine omniscience (vv. 1-6), divine omnipresence (vv. 7-12), divine creativity in the womb (vv. 13-16), and the psalmist\'s response (vv. 17-24). The opening "You have searched me (<em>ḥāqar</em>) and you know me" — <em>ḥāqar</em> is the verb for thorough investigation, prospecting, mining (Job 28:3; Prov 25:2-3). YHWH\'s knowledge of the psalmist is not casual observation but deep, investigative knowing — a comprehensive examination of the psalmist\'s interior. The psalm begins with what YHWH knows about the human (vv. 1-18) before moving to what the human wishes to know about YHWH\'s action (vv. 19-24).</p>',
    "2": '<p>"You know when I sit and when I rise; you perceive my thoughts from afar (<em>mērāḥôq</em>)" — the totality of external behavior (sitting and rising = all activities) and internal states (thoughts) are known. "From afar" may mean before they are fully formed — before the thought has traveled from its origin to its expression, YHWH already knows it. The spatial paradox: YHWH who is "far" (transcendent, not physically present beside the psalmist) knows what is "near" (the psalmist\'s innermost thoughts) more completely than the psalmist knows them himself. Divine transcendence does not entail divine distance from personal experience.</p>',
    "3": '<p>"You discern my going out and my lying down (<em>wĕribʿî</em>); you are familiar with all my ways" — "lying down (<em>reba</em>)" — literally "my lying down/path" — all my movements. The movement in vv. 2-3 covers all opposites: sitting/rising, going out/lying down — the merismus (stating two extremes to mean the entire range). All activity is transparent to divine knowing. "Familiar with all my ways (<em>hiskantāh kol-dĕrāḵay</em>)" — <em>sākan</em> (be familiar with, be accustomed to) implies intimate, habitual acquaintance — not surveillance but deep knowing, like a parent who knows a child\'s characteristic ways of moving through the world.</p>',
    "4": '<p>"Before a word is on my tongue you, LORD, know it completely (<em>kullāh</em>)" — the pre-verbal moment of knowing. Before the thought becomes word, before the word is spoken, YHWH already knows it entirely. "Completely (<em>kullāh</em>)" — the whole of the would-be word is already known. This is the most intimate possible knowledge: knowing what someone will say before they say it, and knowing it more completely than the speaker knows it themselves. In ANE divination, reading the future was a valued skill performed through complex rituals (liver-omens, astrology). YHWH\'s knowledge of the human heart requires none of this — it is immediate and total.</p>',
    "5": '<p>"You hem me in behind and before (<em>ʾāḥôr wāqeḏem ṣartānî</em>), and you lay your hand upon me" — <em>ṣārar</em> (hem in, besiege, press on all sides) is the verb used for military siege. The image is initially alarming: being "besieged" suggests constraint and danger. But in this context the "besieging" is protective — YHWH surrounds the psalmist from behind and before, and lays his hand upon the psalmist. The encompassing presence is not imprisonment but accompaniment. Ps 125:2: "As the mountains surround Jerusalem, so the LORD surrounds his people." The same spatial completeness that could be experienced as a trap is experienced as security.</p>',
    "6": '<p>"Such knowledge is too wonderful for me (<em>pelîʾāh</em>), too lofty for me to attain" — the response to the description of divine knowing in vv. 1-5: the psalmist confesses that this knowledge exceeds his capacity to understand or process. <em>Pelîʾāh</em> (wonderful, beyond ordinary capacity) is the root of <em>pele</em> (wonder) — the term for divine acts that transcend human comprehension (Isa 9:6 — the Messiah\'s name includes <em>pele</em> = Wonderful Counselor). The psalmist does not attempt to fully grasp divine omniscience — only to acknowledge it, express wonder at it, and let the acknowledgment lead into the next movement (omnipresence, vv. 7-12).</p>',
    "7": '<p>"Where can I go from your Spirit (<em>rûḥekā</em>)? Where can I flee from your presence (<em>pānêkā</em>)?" — the pivot to omnipresence. The question is rhetorical: the answer is nowhere. <em>Rûaḥ</em> (Spirit) and <em>pānîm</em> (face/presence) are parallel — the Spirit is the mode of the divine presence\'s pervasiveness. The question "where can I flee?" echoes Jonah 1:3, 10 (Jonah trying to flee "from the LORD\'s presence" — the same Hebrew phrase). Jonah\'s futile flight demonstrates what the psalm states theoretically: the divine presence is inescapable. The psalm does not treat this as a threat but as a comfort — though the negative phrasing ("flee") acknowledges that the omnipresence can initially feel threatening.</p>',
    "8": '<p>"If I go up to the heavens, you are there; if I make my bed in the depths (<em>šĕʾôl</em>), you are there" — the vertical axis of the cosmos. Heavens above and Sheol below — the two extremes of the vertical universe. Amos 9:2-3 uses the same spatial logic for judgment: "Though they dig down to the depths of the grave, from there my hand will take them. Though they climb up to the heavens, from there I will bring them down." Ps 139 uses the same vertical merismus for comfort — YHWH is present at both extremes of the cosmos. The remarkable assertion about Sheol: the realm of the dead is not outside divine presence. For most of the OT, Sheol is a place of divine absence (Ps 6:5; 88:11-12). This verse pushes against that assumption.</p>',
    "9": '<p>"If I rise on the wings of the dawn (<em>kanpê-šāḥar</em>), if I settle on the far side of the sea" — the horizontal axis. "Wings of the dawn" — poetic for the extreme east, where the sun rises (cf. Mal 4:2 — "the sun of righteousness will rise with healing in its rays"). "Far side of the sea (<em>ʾaḥărît yām</em>)" — the extreme west, the Mediterranean horizon. Ps 103:12 uses the same directional pair (east/west) for the removal of sin: "as far as the east is from the west, so far has he removed our transgressions from us." The horizontal merismus (east to west) combined with the vertical merismus (heaven to Sheol) in vv. 8-9 establishes that the entire cosmos is within divine presence.</p>',
    "10": '<p>"Even there your hand will guide me, your right hand will hold me fast (<em>tōʾḥăzēnî</em>)" — the divine hands that were described in v. 5 as laying upon the psalmist now are described as guiding and holding. <em>Tōʾḥăzēnî</em> (hold me, grip me securely) is the verb of the divine grip that prevents falling (Ps 63:8: "your right hand upholds me"). Even at the farthest geographic extremes (vv. 8-9), the divine hand reaches. The omnipresence is not merely abstract "being there" but active engagement — guiding and holding. The presence is personal, not merely topographic.</p>',
    "11": '<p>"If I say, \'Surely the darkness will hide me and the light become night around me\'" — the psalmist entertains the hypothesis: can darkness provide concealment from divine presence? The thought is quickly dismissed in v. 12. The hypothesis of hiding in darkness reflects a natural human impulse — the assumption that what cannot be seen by human eyes cannot be seen at all. ANE prayers frequently used the darkness/night as a time when divine protection was most needed precisely because darkness was threatening. The psalms repeatedly petition God to be present "in the night" (Ps 63:6; 77:6; 119:55, 148).</p>',
    "12": '<p>"Even the darkness will not be dark to you; the night will shine like the day, for darkness is as light to you" — YHWH\'s omniscience is not dependent on physical light. "Darkness is as light to you" — the deepest darkness provides no concealment because divine knowing does not use photons. This is the reversal of the standard ANE assumption that the underworld and darkness were outside divine supervision. The radical assertion: even Sheol (v. 8) and even the darkest night are as bright as day to YHWH. There is nowhere — vertically, horizontally, or in terms of light — that human beings can escape divine knowing and presence.</p>',
    "13": '<p>"For you created my inmost being (<em>kilyōtay</em>); you knit me together (<em>wĕtisskēkēnî</em>) in my mother\'s womb" — the basis for divine omniscience: YHWH made the psalmist, therefore YHWH knows the psalmist from the inside. <em>Kilyōtay</em> (kidneys, inmost being) — the kidneys were the seat of the deepest interior life in Hebrew thought (Ps 7:9; 16:7; 73:21; Jer 17:10). <em>Wĕtisskēkēnî</em> (you knit/wove together) — from <em>sāḵaḵ</em> (to weave, to screen/cover): the intricate process of fetal development described as divine weaving in the womb. The theological implication: human life from its earliest formation is the direct work of the divine craftsman — which is why YHWH knows it so completely.</p>',
    "14": '<p>"I praise you because I am fearfully and wonderfully made (<em>nôrāʾôt niplêtî</em>); your works are wonderful, I know that full well" — <em>Nôrāʾôt</em> (fearful, awe-inspiring) and <em>niplêtî</em> (wonderfully made, set apart) — two superlatives applied to the psalmist\'s own creation. The fearful-wonder of self-existence: the psalmist, contemplating the divine work of formation in v. 13, responds with praise. "Wonderful (<em>pele</em>)" returns to the root of v. 6 (<em>pelîʾāh</em>) — the same awe at incomprehensibility, now directed at the mystery of one\'s own creation. This verse is not self-congratulation but worship — the recognition that one\'s own existence is a divine wonder worthy of praise.</p>',
    "15": '<p>"My frame (<em>ʿaṣmî</em>) was not hidden from you when I was made in the secret place (<em>bassēter</em>), when I was woven together (<em>ruqqamtî</em>) in the depths of the earth" — "my frame (<em>ʿaṣmî</em>)" — literally "my bones," used here for the bodily structure. "Depths of the earth" — a poetic expression for the womb, drawing on the ancient association between the earth as mother and the womb as the place of formation. <em>Ruqqamtî</em> (woven together) — from <em>rāqam</em> (to embroider, weave with colored thread) — the intricate complexity of human development described as multicolored embroidery. The biological process in the womb is described as hidden from human view but fully visible to YHWH.</p>',
    "16": '<p>"Your eyes saw my unformed body (<em>gālmî</em>); all the days ordained for me were written in your book before one of them came to be" — <em>Gālmî</em> (my unformed substance, embryo) — this is the only occurrence of <em>golem</em> in the OT (later rabbinic texts use <em>golem</em> for a shapeless, unformed being, and eventually for the legendary artificial being). YHWH "saw" the embryo in its earliest, unshaped state. "Written in your book" — the book of life / book of days (cf. Ps 69:28; Dan 12:1; Rev 20:12) — a divine register of each person\'s ordained days, written before any of them existed. The implication: human life has a divinely authored narrative from the point of conception, not merely from birth.</p>',
    "17": '<p>"How precious to me are your thoughts, God! How vast is the sum of them!" — the psalmist\'s response to the knowledge of divine attentiveness (vv. 1-16) is wonder at the divine thoughts directed toward the psalmist. "How precious (<em>mah-yāqĕrû</em>)" — how weighty, valuable, dear. The divine thoughts about the individual are a treasure. In ANE culture, the thought of a king toward a subject was significant — royal favor was a matter of survival. YHWH\'s thoughts toward the psalmist (not merely his general thoughts about the cosmos) are overwhelmingly many and precious.</p>',
    "18": '<p>"Were I to count them, they would outnumber the grains of sand — when I awake, I am still with you" — the uncountability of divine thoughts toward the individual (grains of sand = maximum quantity in ANE numerical hyperbole, cf. Gen 22:17; 32:12). "When I awake, I am still with you (<em>haqîṣōtî wĕʿôḏî ʿimmāḵ</em>)" — this closing line of the positive section (vv. 1-18) is intimate: waking up and finding oneself still in the presence of the one who has been thinking about you through the night. The divine omnipresence that was cosmic in scope (vv. 7-12) is personal in application: YHWH\'s presence is the first reality of each new morning.</p>',
    "19": '<p>"If only you, God, would slay the wicked! Away from me, you who are bloodthirsty!" — the imprecatory section (vv. 19-22) arrives suddenly. The structural logic: if YHWH knows everything (vv. 1-6), is present everywhere (vv. 7-12), and created the psalmist with intimacy (vv. 13-18), then the psalmist can bring the full weight of moral outrage against the wicked before the all-knowing God. The petition "slay the wicked" is not revenge-desire but a call on the divine Judge to act consistently with his own omniscient knowledge. "Away from me (<em>sûrû mimmennî</em>)" — dissociation from the enemies; the psalmist will not be in their company.</p>',
    "20": '<p>"They speak of you with evil intent; your adversaries misuse your name" — the enemies\' specific offense is theological: they use (<em>nāśāʾ lāšāw</em>) the divine name falsely/in vain. The second commandment prohibition (Exod 20:7) — "You shall not misuse the name of the LORD your God" — is what the wicked violate. In context, "misuse" may refer to false prophecy in YHWH\'s name (cf. Deut 18:20-22; Jer 23:25-40), using YHWH\'s name in false oaths (Lev 19:12), or attributing evil to YHWH. The imprecation against these specific people connects to the psalm\'s opening: YHWH who "searches" and "knows" (v. 1) knows their false use of his name.</p>',
    "21": '<p>"Do I not hate those who hate you, LORD, and abhor those who are in rebellion against you?" — the psalmist claims alignment with YHWH\'s own values: to hate what YHWH hates, to oppose what opposes YHWH. This is not celebration of hatred but a declaration of covenant loyalty — the same "zeal" vocabulary as Ps 69:9 (Phinehas and Jesus). The Hebrew concept of covenant love and hate (Mal 1:2-3; Rom 9:13) operates in a framework of covenant alignment: loving what is good and hating what is evil is the mark of the covenant community (Ps 97:10: "Let those who love the LORD hate evil"). The problem is human misapplication of this principle, not the principle itself.</p>',
    "22": '<p>"I have nothing but hatred for them (<em>tiklît śinʾāh śĕnēʾtîm</em>); I count them my enemies" — <em>Tiklît</em> (complete, total, whole) — the most intense form of the verb: utterly complete hatred. The language is absolute and uncomfortable to modern ears. The psalm does not soften the psalmist\'s emotional intensity. The hermeneutical question is whether this represents the ideal Christian disposition (cf. Matt 5:44 — "love your enemies") or whether it represents a legitimate OT expression of covenant loyalty that Christ transforms rather than simply endorses. Paul\'s citation of Ps 139:21 is notably absent from his NT letters, while Jesus explicitly reorients the "hate your enemy" tradition (Matt 5:43-48).</p>',
    "23": '<p>"Search me, God, and know my heart; test me and know my anxious thoughts (<em>śarʿappay</em>)" — the closing prayer returns to the opening: "search me (<em>ḥāqrēnî</em>)" echoes v. 1 "you have searched (<em>ḥāqartā</em>) me." The psalm is a circle: it began with YHWH\'s comprehensive knowing of the psalmist; it ends with the psalmist inviting that knowing as a prayer. <em>Śarʿappay</em> (anxious thoughts, conflicted thoughts) — a rare word appearing only here and Ps 94:19. The psalmist does not claim to be free from anxious or conflicted thoughts but brings them explicitly before the divine searcher.</p>',
    "24": '<p>"See if there is any offensive way (<em>derek ʿōṣeb</em>) in me, and lead me in the way everlasting (<em>derek ʿôlām</em>)" — "offensive way (<em>derek ʿōṣeb</em>)" — literally "way of pain/idol" (ʿōṣeb can mean both pain and idol). The psalmist asks YHWH to identify any hidden path of idolatry or pain-causing habit. "Lead me in the way everlasting (<em>derek ʿôlām</em>)" — the ancient/eternal path (cf. Jer 6:16: "ask for the ancient paths, where the good way is"). The closing petition is the natural response to the whole psalm: if YHWH knows the psalmist completely, searches all the psalmist\'s thoughts, and was present at the psalmist\'s formation — then the psalmist asks to be led by that omniscient companion on the right path forward.</p>'
  }
}

def main():
    existing = load_comm('mkt-context', 'psalms')
    merge_comm(existing, PSALMS)
    save_comm('mkt-context', 'psalms', existing)
    print('Psalms 134-139 mkt-context written.')

if __name__ == '__main__':
    main()
