"""
MKT Christ Commentary — Psalms chapters 37–40
Run: python3 scripts/zc-christ-psalms-37-40.py

Key decisions:
- Ps 37: dominant thread is 'inherit the earth/land' (vv 9,11,22,29,34) → Matt 5:5 direct
  citation in the Beatitudes; the acrostic Wisdom Psalm profile of the righteous man
  is the type fulfilled perfectly in Christ alone
- Ps 38: one of seven Penitential Psalms; typological reading — David bearing divine
  judgment for personal sin prefigures Christ bearing ours without personal sin;
  v13-14 silence before accusers → Isa 53:7 / Matt 26:63 type; v11 friends stand
  far off → Luke 23:49 fulfillment
- Ps 39: human mortality / hebel theme; v12 'stranger and alien' → Heb 11:13; 1 Pet 2:11;
  Christ's incarnation as voluntary solidarity with mortal transience (Heb 2:14-15)
- Ps 40: vv6-8 directly quoted in Heb 10:5-7 (LXX 'body prepared' vs. MT 'opened ears');
  v7 'written about me in the scroll' → Luke 24:44; v8 'delight to do your will' →
  Christ's perfect obedience (John 6:38; Phil 2:8); the whole psalm is Heb 10's proof
  that the old sacrifice-system is superseded by the obedient body of Christ
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

PSALMS = {
  "37": {
    "1": '<p>A theme: Psalm 37 is a Wisdom acrostic — each Hebrew stanza begins with successive letters of the alphabet, encoding the completeness of the instruction within its formal structure. "Do not let evildoers upset you" (<em>ʾal-titḥar bĕmĕrēʿîm</em>) is the command that the entire psalm elaborates: covenant fidelity despite appearances. Christ embodies the answer to this command — the one who did not lose faith or stability despite the apparent triumph of his executioners, who trusted the divine outcome through the darkest crisis (Heb 5:7-9).</p>',
    "2": '<p>A theme: "For like grass they will soon be cut down; like green plants they will wither away." The grass-withering image recurs across the Psalter and Isaiah (Isa 40:6-8: "All flesh is grass... but the word of our God stands forever"). 1 Peter 1:24-25 quotes Isaiah 40 in the context of proclaiming the gospel: "but the word of the Lord endures forever — and this is the word that was proclaimed to you." The withering of the wicked is the backdrop against which Christ\'s resurrection-victory stands; his life does not wither.</p>',
    "3": '<p>A theme: "Trust in the LORD and do good; live in the land and enjoy secure provision." The triple covenant command — trust, do good, dwell — is the pattern of faithful land-tenure that the Deuteronomic framework promised. Christ is the one who perfectly "trusts in the LORD and does good" (Matt 3:17: "This is my Son, whom I love; with him I am well pleased") — the validation of his total covenant fidelity. The "secure provision" (<em>ûrʿēh ʾĕmûnāh</em>, literally "pasture faithfulness/truth") is the New Covenant abundance Christ provides.</p>',
    "4": '<p>A revelation of God: "Find your delight in the LORD, and he will give you the desires of your heart." The divine responsiveness to delight — the promise that aligning one\'s desires with God produces fulfillment of those desires — is the covenant logic of John 15:7: "If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you." Christ as the one who mediates this promise makes it available to his people: delighting in the Father through the Son produces prayer that is in alignment with the Father\'s will (1 John 5:14-15).</p>',
    "5": '<p>A theme: "Commit your way to the LORD; trust in him, and he will bring it to pass." The act of committing or rolling (<em>gōl</em>) one\'s path onto YHWH is the posture of total dependence. 1 Peter 5:7 quotes the Psalm\'s framework: "Cast all your anxiety on him because he cares for you." Christ models this total commitment most fully in Gethsemane: "Not my will, but yours be done" (Luke 22:42) — rolling the entire burden of the passion and its outcome onto the Father. The Father "brings it to pass" in the resurrection.</p>',
    "6": '<p>A theme: "He will bring your righteousness to light and your cause bright as noon." The divine vindication of the righteous person — their righteousness emerging from obscurity into noon-light — is the eschatological pattern of the resurrection. Romans 1:4 states that Christ "was designated the Son of God in power according to the Spirit of holiness by his resurrection from the dead" — the resurrection is the divine bringing-to-light of Christ\'s righteousness, the noon-brightness after the darkness of the cross.</p>',
    "7": '<p>A revelation of God: "Be still before the LORD and wait patiently for him." The discipline of stillness and patient waiting (<em>hittḥōlēl lô</em>) before divine action is the anti-urgency that runs against every instinct of the flesh. Hebrews 10:36: "You need to persevere so that when you have done the will of God, you will receive what he has promised. For, \'In just a little while, he who is coming will come and will not delay.\'" The waiting posture of Psalm 37 is the posture Christ\'s people practice until his return — which the psalm itself anticipates (vv 9-11).</p>',
    "8": '<p>A revelation of God: "Let go of anger and abandon wrath; do not fret — it leads only to evil." The divine wisdom about emotional regulation in the face of injustice — the instruction not to let indignation produce reactive evil — is the countercultural logic of the Sermon on the Mount (Matt 5:43-45: "Love your enemies and pray for those who persecute you"). Christ embodies this perfectly at the cross: 1 Peter 2:23, "When they hurled their insults at him, he did not retaliate; when he suffered, he made no threats. Instead, he entrusted himself to him who judges justly."</p>',
    "9": '<p>A direct connection: "For the wicked will be cut off, but those who wait for the LORD will inherit the earth (<em>yîrĕšû-ʾāreṣ</em>)." The "inherit the earth" (<em>yāraš ʾereṣ</em>) formula appears five times in Psalm 37 (vv 9, 11, 22, 29, 34). Jesus lifts verse 11\'s wording directly into the Beatitudes (Matt 5:5), making this the bridge between the Psalm\'s Wisdom framework and the eschatological Kingdom. Those who "wait for the LORD" in Psalm 37\'s terms are those who trust in the Messiah — Christ is both the one waited for and the one through whom the inheritance comes.</p>',
    "10": '<p>A theme: "In just a little while the wicked will be gone; you will search for his place, but it will not be found." The sudden and total disappearance of the wicked — no trace remaining — is the Psalm\'s idiom for divine judgment. The NT uses this language eschatologically: Revelation 20:11 ("the earth and the heavens fled from his presence, and there was no place for them") and 21:4 ("the old order of things has passed away"). The wicked of Psalm 37:10 foreshadow the final disappearance of everything opposed to the reign of Christ.</p>',
    "11": '<p>A direct citation: "But the meek will inherit the earth and delight in abundant peace." Jesus quotes this verse verbatim in the third Beatitude (Matt 5:5: "Blessed are the meek, for they will inherit the earth"). This is one of the clearest cases of Jesus placing himself within the Psalter\'s eschatological framework: the "meek" of Psalm 37 who wait for YHWH\'s vindication are the "meek" of the Beatitudes who receive the Kingdom. Christ himself is the paradigmatic meek one — the one who "is gentle and humble in heart" (Matt 11:29) and who inherits the earth through resurrection and ascension (Eph 1:22).</p>',
    "12": '<p>A shadow: "The wicked man schemes against the righteous and grinds his teeth at him." The image of the wicked plotting and raging against the righteous is fulfilled most dramatically in the conspiracy against Jesus: Matthew 26:3-4 ("the chief priests and the elders of the people assembled in the palace of the high priest... and they schemed to arrest Jesus secretly and kill him"). The "grinding of teeth" at the righteous is the visceral hatred that the Passion narratives document — the opposition to the one who embodies righteousness.</p>',
    "13": '<p>A revelation of God: "The Lord laughs at the wicked, for he sees that their day is coming." The divine laugh at the schemes of those who oppose his anointed (cf. Ps 2:4: "He who sits in the heavens laughs; the Lord scoffs at them") is the perspective of absolute sovereignty. Acts 4:27-28 applies this divine sovereignty directly to the conspiracy against Jesus: "they did what your power and will had decided beforehand should happen." The day that is "coming" for the wicked who killed Jesus is the day of judgment and resurrection — already accomplished in the risen Christ.</p>',
    "14": '<p>A shadow: "The wicked draw the sword and bend their bow to bring down the poor and helpless, to kill those who walk uprightly." The armed violence of the wicked against the righteous poor is the Psalm\'s image of injustice at its worst. At the arrest of Jesus, swords and clubs are literally drawn (Matt 26:47-50). The "poor and helpless" (<em>ʿānî wĕʾebyôn</em>) whom they seek to "bring down" (<em>litpôl</em>) is the vocabulary of the Suffering Servant psalms; Jesus, voluntarily emptied and vulnerable, is the ultimate embodiment of the one targeted by the wicked\'s violence.</p>',
    "15": '<p>A shadow: "Their swords will pierce their own hearts, and their bows will be shattered." The reversal — the weapons of the violent turned against themselves — is the Wisdom pattern of evil self-defeating. At the cross, the apparent victory of the wicked over Jesus became their ultimate defeat: 1 Corinthians 2:8, "None of the rulers of this age understood it, for if they had, they would not have crucified the Lord of glory." The sword turned against the schemers; the cross became the instrument of their judgment, not of Christ\'s destruction.</p>',
    "16": '<p>A revelation of God: "Better is the little that the righteous has than the great wealth of many wicked." The Wisdom reversal of values — the little of the righteous > the abundance of the wicked — is the logic of the Kingdom that Christ announces in the Beatitudes and embodies in his own life. 2 Corinthians 8:9: "For you know the grace of our Lord Jesus Christ, that though he was rich, yet for your sake he became poor, so that you through his poverty might become rich." Christ is the paradigmatic "righteous who has little" — and in that poverty makes many rich.</p>',
    "17": '<p>A theme: "For the strength of the wicked will be shattered, but the LORD supports the righteous." The divine support of the righteous and the shattering of the wicked\'s power is the pattern of Christ\'s resurrection. Hebrews 2:14-15: "by his death he might break the power of him who holds the power of death — that is, the devil." The devil\'s strength is "shattered" at the cross; the LORD "supports the righteous" by raising Christ from the dead — the definitive demonstration that divine strength upholds those who trust in him.</p>',
    "18": '<p>A revelation of God: "The LORD knows the days of the upright, and their inheritance will last forever." The divine knowledge of the righteous person\'s "days" (<em>yôdēaʿ YHWH yĕmê tĕmîmîm</em>) — and the eternal duration of their inheritance — is the covenant security that grounds resurrection hope. The "forever" (<em>lĕʿôlām</em>) of the inheritance is not merely long duration but the eschatological age beyond death. John 10:28: "I give them eternal life, and they shall never perish; no one will snatch them out of my hand." Christ is the guarantee of the inheritance that is forever.</p>',
    "19": '<p>A theme: "They will not be disgraced in days of trouble; in times of famine they will be satisfied." The covenant promise of honor-preservation and sustenance through crisis echoes the manna tradition and the wilderness provision. Christ\'s feeding of the five thousand (John 6:1-15) and his identity as the "bread of life" (John 6:35: "Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty") fulfill the promise of Psalm 37:19 — the righteous, through union with Christ, are satisfied even in famine.</p>',
    "20": '<p>A shadow: "The wicked will perish; the enemies of the LORD will fade like green pastures — they will dissolve, consumed like smoke." The vivid images of fading and dissolving — the enemies of YHWH disappearing like morning mist — are the Psalm\'s eschatological imagery of judgment. 2 Peter 3:10 uses the same dissolving imagery for the final judgment: "the heavens will disappear with a roar; the elements will be destroyed by fire." The enemies of Christ who opposed him — and who continue to oppose his people — are under this same eschatological sentence.</p>',
    "21": '<p>A revelation of God: "The wicked borrows and does not repay, but the righteous is generous and gives." The contrast between covenant economic behavior — the wicked who take but do not return vs. the righteous who give freely — is the character portrait that Christ fulfills perfectly. 2 Corinthians 9:7 ("God loves a cheerful giver") and the entire theology of grace — God giving freely through Christ — reflects the "righteous is generous and gives" of Psalm 37. Christ gives his life freely (John 10:18: "No one takes it from me, but I lay it down of my own accord").</p>',
    "22": '<p>A theme: "Those blessed by the LORD will inherit the earth, but those he has cursed will be cut off." The dual eschatological outcome — blessing/inheritance vs. curse/cutting-off — is the judgment framework that Christ applies in the final judgment scene of Matthew 25:34-41: "Come, you who are blessed by my Father; take your inheritance... Depart from me, you who are cursed, into the eternal fire." The "blessed by the LORD who inherit the earth" of Psalm 37 becomes the "blessed by my Father" of Christ\'s eschatological pronouncement.</p>',
    "23": '<p>A type: "The LORD establishes the steps of a man and delights in his way." The divine establishment of the steps of the righteous — YHWH guiding each step and finding delight in the path — is fulfilled in Christ as the one whose steps are perfectly directed. John 8:29: "The one who sent me is with me; he has not left me alone, for I always do what pleases him." The divine delight in the man\'s way is the divine delight in Jesus ("This is my Son, whom I love; with him I am well pleased," Matt 3:17) — and through union with Christ, in all who walk in him.</p>',
    "24": '<p>A type: "Though he stumbles, he will not fall headlong, for the LORD holds his hand." The divine hand-holding of the righteous who stumble (but do not ultimately fall) is the covenant care imagery. Isaiah 42:6 applies exactly this hand-holding to the Servant: "I, the LORD, have called you in righteousness; I will take hold of your hand." The Servant of Isaiah 42 whom YHWH holds by the hand is the same figure who does not fall permanently even through the deepest valley — Christ stumbling under the cross (Luke 23:26) but not falling, risen by the hand of God.</p>',
    "25": '<p>A revelation of God: "I was young and now I am old, yet I have never seen the righteous abandoned or their children begging for food." The experiential testimony of the aged Psalmist — a lifetime of observation confirming that YHWH does not abandon his righteous — grounds resurrection hope. Hebrews 13:5 quotes YHWH\'s pledge: "Never will I leave you; never will I forsake you." Christ\'s resurrection is the ultimate vindication of this testimony: God did not abandon the righteous one to the grave (Acts 2:27, citing Ps 16:10). The righteous are never ultimately abandoned.</p>',
    "26": '<p>A revelation of God: "He is always generous and lending, and his children become a blessing." The generosity of the righteous man and the blessing transmitted through his children is the covenant-blessing pattern (Gen 12:2: "I will bless you... and you will be a blessing"). Christ is the one through whom the Abrahamic blessing flows to "all peoples on earth" (Gal 3:14: "so that the blessing given to Abraham might come to the Gentiles through Christ Jesus"). The "children" who become a blessing are those who are in Christ — Abraham\'s offspring (Gal 3:29).</p>',
    "27": '<p>A theme: "Turn away from evil and do good, so you will live in the land permanently." The conditional covenant form — turn, do, live — is the Deuteronomic framework at its most compressed. Christ fulfills this by being the one who permanently "turns away from evil and does good" (Acts 10:38: "he went around doing good") and who thereby secures the "permanent" dwelling — the New Jerusalem, the eternal inheritance. Through him, those who "live in him" (1 John 4:15) receive the permanence that no earthly land-tenure could provide.</p>',
    "28": '<p>A revelation of God: "For the LORD loves justice; he does not abandon his faithful people." The divine love of justice (<em>mišpāṭ</em>) as the ground of YHWH\'s faithfulness to his covenant people is the theological foundation of the atonement. Romans 3:25-26 frames the cross as the demonstration of God\'s justice: "he left the sins committed beforehand unpunished — he did it to demonstrate his justice at the present time, so as to be just and the one who justifies those who have faith in Jesus." The LORD who loves justice demonstrates that love supremely at the cross of Christ.</p>',
    "29": '<p>A theme: "The righteous will inherit the earth and make their home in it forever." The permanent dwelling (<em>yišĕkĕnû lāʿad</em>) of the righteous in the earth/land is the eschatological vision of a renewed creation. Revelation 21:3: "And I heard a loud voice from the throne saying, \'Look! God\'s dwelling place is now among the people, and he will dwell with them.\'" And 22:5: "they will reign for ever and ever." The "inherit the earth" of Psalm 37 is not replacement of the earth but its renewal — the inheritance Christ secures through the resurrection is the new earth (2 Pet 3:13).</p>',
    "30": '<p>A type: "The righteous speak wisdom, and their tongue talks of justice." The wisdom-speech and justice-talk of the righteous man is the profile fulfilled in Christ as the Wisdom of God (1 Cor 1:24, 30). Luke 4:22 records that people "spoke well of him and were amazed at the gracious words that came from his lips." His teaching with authority (Matt 7:28-29), his silencing of his opponents (Matt 22:46), and his declaration of the final judgment (John 5:27) are the fulfillment of "wisdom" and "justice" from the mouth of the righteous.</p>',
    "31": '<p>A type: "The law of his God is in his heart; his steps do not falter." The internalized Torah — law not merely observed but written on the heart — is what Jeremiah 31:33 promises as the New Covenant gift: "I will put my law in their minds and write it on their hearts." Christ is the first and perfect fulfillment of this: the one in whom the law is perfectly internalized, whose steps never falter because Torah is his delight (Ps 1:2; Matt 5:17). Through the Spirit, Christ writes this same internalized law on the hearts of those in the New Covenant.</p>',
    "32": '<p>A shadow: "The wicked lie in wait for the righteous, looking to kill them." The lethal ambush of the righteous by the wicked is the Psalm\'s idiom for the opposition to covenant faithfulness. The Gospel narratives are saturated with this imagery: John 5:18 ("the Jewish leaders tried all the more to kill him"), 7:1 ("the Jewish leaders were looking for a way to kill him"), 11:53 ("they plotted to take his life"). The righteous of Psalm 37:32 who is ambushed and sought for death is the type whose fullest expression is Christ, hunted by those who hated his righteousness.</p>',
    "33": '<p>A revelation of God: "The LORD will not leave the righteous at the mercy of the wicked or let them be condemned at trial." The divine protection from both power and legal condemnation — YHWH intervening in the juridical process — is the resurrection\'s meaning. Christ was condemned at trial by both Jewish and Roman authority. But YHWH did not "leave him at their mercy" — the resurrection is the divine reversal of the human verdict. Romans 8:33-34: "Who will bring any charge against those whom God has chosen? It is God who justifies. Who then is the one who condemns? No one."</p>',
    "34": '<p>A theme: "Wait for the LORD and keep his way; he will exalt you to inherit the earth." The waiting→exaltation→inheritance sequence is the eschatological pattern that Christ undergoes and then mediates. Philippians 2:8-9: "he humbled himself by becoming obedient to death — even death on a cross! Therefore God exalted him to the highest place." Christ waited (Gethsemane), kept the Father\'s way perfectly (total obedience), and was exalted to inherit "the earth" in the fullest sense — authority over all things (Matt 28:18: "all authority in heaven and on earth has been given to me").</p>',
    "35": '<p>A shadow: "I have seen a ruthless wicked man towering like a flourishing tree in its native ground." The towering wicked man — impressive, rooted, seemingly permanent — is the type of all worldly power that opposes the Messianic kingdom. Daniel 4\'s great tree cut down (Nebuchadnezzar) and Ezekiel 31\'s cedar of Lebanon (Pharaoh) use the same image. The Roman Empire, the Jewish establishment, all the powers that crucified Jesus appeared to be "flourishing trees in native ground" — permanent, irresistible.</p>',
    "36": '<p>A shadow: "But he passed away — gone; I looked for him and he could not be found." The sudden disappearance of the wicked who seemed permanent — the tree of v35 simply gone — is the Psalm\'s answer to the temporal flourishing of evil. Revelation 18:10, 17, 19 ("Woe! Woe to you, great city... in one hour your doom has come!") applies this to Babylon, the symbol of all worldly power opposed to Christ. The powers that crucified Jesus have passed away; Christ\'s kingdom remains (Heb 12:28: "we are receiving a kingdom that cannot be shaken").</p>',
    "37": '<p>A revelation of God: "Take note of the blameless person and look at the upright; the future (<em>ʾaḥărît</em>) of such a person is peace (<em>šālôm</em>)." The <em>ʾaḥărît</em> — the "end" or "future" of the blameless — is peace/wholeness. This is the Psalm\'s definitive answer to the theodicy question. Christ is the one who is perfectly "blameless and upright" (<em>tāmîm wĕyāšār</em>) — and his future is demonstrated in the resurrection: Romans 5:1, "since we have been justified through faith, we have peace (<em>eirēnēn</em>) with God through our Lord Jesus Christ." The future of the blameless one is peace — shalom — eternal life.</p>',
    "38": '<p>A shadow: "But rebels will all be destroyed together; the future of the wicked will be cut off." The contrast with v37 is stark: the future of rebels is cutting-off, not peace. The <em>ʾaḥărît</em> (future/end) of the wicked is destruction, in direct contrast to the peace of the blameless. Revelation 20:15: "Anyone whose name was not found written in the book of life was thrown into the lake of fire." The "cut off" of Psalm 37:38 is the ultimate language of covenant exclusion — those who reject the blameless Messiah are cut off from the inheritance he mediates.</p>',
    "39": '<p>A revelation of God: "The salvation of the righteous comes from the LORD; he is their stronghold in times of trouble." The source of salvation is YHWH alone — the righteous person\'s security comes not from their own righteousness but from the divine Savior. Acts 4:12: "Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved." Christ is the "stronghold in times of trouble" — the name above all names (Phil 2:9) who is the exclusive locus of the salvation that Psalm 37:39 attributes to YHWH.</p>',
    "40": '<p>A revelation of God: "The LORD helps and delivers them; he rescues them from the wicked and saves them, because they take shelter in him." The sequence — help, deliver, rescue, save — all grounded in the single act of sheltering in YHWH — is the comprehensive salvation vocabulary of the OT. 1 Thessalonians 1:10 frames Christ as "Jesus, who rescues us from the coming wrath." The comprehensive salvation work of Psalm 37:40 — performed by YHWH because his people take shelter in him — is performed by Christ and through Christ, in whom the community shelters.</p>',
  },
  "38": {
    "1": '<p>A type: Psalm 38 is one of seven Penitential Psalms (Pss 6, 32, 38, 51, 102, 130, 143) and is designated a memorial offering (<em>lĕhazkîr</em> — possibly the frankincense portion of the grain offering, Lev 2:2; or a memorial to bring a matter before God). "LORD, do not rebuke me in your anger" opens the psalm with an appeal for measured discipline rather than fierce wrath. The typological reading that Hebrews and the NT invite: what David experiences as divine discipline for personal sin, Christ undergoes for the sin of others — he takes the rebuke that was ours (Isa 53:5: "the punishment that brought us peace was on him").</p>',
    "2": '<p>A type: "Your arrows have pierced me deeply, and your hand has come down hard on me." The divine arrows and pressing hand are the imagery of YHWH\'s judicial wrath falling on the person. Isaiah 53:4 states: "We considered him punished by God, stricken by him, and afflicted." What David describes as his own experience of divine discipline under sin, the NT applies to Christ bearing the judgment that sin requires — the arrows of divine wrath directed at David\'s sin fall on the one who takes his place. 1 Peter 2:24: "He himself bore our sins in his body on the cross."</p>',
    "3": '<p>A type: "My body has no soundness because of your anger; my bones have no rest because of my sin." The physical disintegration produced by the divine anger over sin is the imagery of judgment impacting the body. At the crucifixion, the physical suffering of Christ — the body broken — fulfills this imagery not through personal sin but as the sin-bearer. Psalm 22:14-17 uses similar language for Christ\'s crucifixion experience. The "no soundness" (<em>ʾên-šālôm</em>) in David\'s body under divine anger over sin becomes the literally broken body of Christ under the sin of others.</p>',
    "4": '<p>A type: "My iniquities have overwhelmed me — they are a burden too heavy to carry." The crushing weight of accumulated sin — iniquities that overwhelm and cannot be borne — is the human condition under covenant judgment. Isaiah 53:6: "the LORD has laid on him the iniquity of us all." What the Psalmist describes as the unbearable weight of his own sin, the Servant song frames as the weight of collective human sin laid on the Servant. Christ is the one who actually carries what no individual can bear: the full weight of human iniquity.</p>',
    "5": '<p>A type: "My wounds stink and fester because of my own foolishness." The festering, malodorous wounds of the Psalmist under divine judgment for sin are the imagery of spiritual-physical degradation. The wounds of Christ at the crucifixion — the lash marks, the nail wounds, the spear — are in the NT the wounds of healing, not of personal sin: 1 Peter 2:24, "by his wounds you have been healed." The festering wound-imagery of Psalm 38:5 becomes, in Christ, the healing wound: the wound of the sin-bearer that heals those whose sin caused it.</p>',
    "6": '<p>A type: "I am bowed low and hunched over; I walk about mourning all day long." The physical posture of mourning under divine judgment — bowed, bent, unable to stand upright — is the image of the penitent under the weight of sin. Isaiah 53:3 describes the Servant as "a man of sorrows, and familiar with pain" who was "despised." Christ in Gethsemane "fell with his face to the ground" (Matt 26:39) — the same posture of the overwhelmed under the weight of what he was to bear. The hunched mourning of Psalm 38:6 is the incarnate Messiah\'s posture before his cross.</p>',
    "7": '<p>A type: "My loins are on fire with disease, and there is no health anywhere in my body." The comprehensive bodily affliction — fire, disease, no health — is the Psalm\'s extreme expression of being under divine judgment for sin. The physical totality of Christ\'s suffering at the crucifixion — the crown of thorns, the flogging, the cross — embodied this "no health anywhere." But more profoundly: 2 Corinthians 5:21, "God made him who had no sin to be sin for us." The one who had no personal "disease" was made to carry all of ours.</p>',
    "8": '<p>A type: "I am benumbed and utterly crushed; I cry out from the anguish of my heart." The numbness, crushing, and heart-anguish are the terminal point of the Psalm\'s emotional and physical description of the one under sin-judgment. In Gethsemane: "My soul is overwhelmed with sorrow to the point of death" (Matt 26:38). And on the cross: "My God, my God, why have you forsaken me?" (Matt 27:46, citing Ps 22:1). The "anguish of the heart" from which David cries is the type of the agony from which Christ cries — and the cry is heard (Heb 5:7).</p>',
    "9": '<p>A revelation of God: "Lord, all my longing is laid out before you; my groaning is not hidden from you." The divine omniscience of the sufferer\'s inner state — nothing hidden, all groaning known — is the ground of prayer\'s confidence. Hebrews 4:13: "Nothing in all creation is hidden from God\'s sight. Everything is uncovered and laid bare before the eyes of him to whom we must give account." Christ as the great high priest (Heb 4:14-16) brings the sufferer\'s groaning directly before the divine throne — the one who himself groaned (John 11:33, 38; Rom 8:23) now intercedes for those who groan.</p>',
    "10": '<p>A type: "My heart pounds; my strength has failed, and even the light of my eyes has deserted me." The catalogue of physical and vital-force failures — heart, strength, sight all giving way — describes the one who is at death\'s door under divine judgment. The Passion narratives record Christ\'s physical exhaustion (he could not carry the cross, Luke 23:26), his cry of dereliction (Matt 27:46), and his death (John 19:30: "It is finished. And he bowed his head and gave up his spirit"). The failing of all vital forces in Psalm 38:10 is the type of Christ\'s physical death on the cross.</p>',
    "11": '<p>A direct connection: "My friends and companions keep away from my affliction, and even my relatives stand at a distance." This verse finds a near-verbatim fulfillment in Luke 23:49: "But all those who knew him, including the women who had followed him from Galilee, stood at a distance, watching these things." The disciples fled at the arrest (Mark 14:50), and those who remained stood at a distance at the cross — exactly the scenario Psalm 38:11 describes. What David experienced in personal affliction, Christ experienced as the culminating moment of his Passion.</p>',
    "12": '<p>A shadow: "Those who want me dead set traps for me; those who seek to harm me speak of my destruction and scheme all day long." The constant scheming by those who seek the righteous person\'s death — traps set, destruction planned — is the Passion narrative\'s background. John 11:53 ("they plotted to take his life"), Matthew 26:3-5 (the assembly plotting to kill Jesus), and Psalm 2:1-2 (the nations conspiring against YHWH\'s anointed) all converge in the Sanhedrin\'s deliberate plan to execute the righteous Messiah.</p>',
    "13": '<p>A type: "But I am like someone who cannot hear — I do not listen; like someone mute who cannot speak." The deliberate silence of the Psalmist before his accusers — not engaging with their attacks — is the type of Christ\'s silence before the Sanhedrin and Pilate. Matthew 26:63: "But Jesus remained silent." Matthew 27:14: "he gave him no answer, not even to a single charge — to the great amazement of the governor." Isaiah 53:7: "He was oppressed and afflicted, yet he did not open his mouth; he was led like a lamb to the slaughter, and as a sheep before its shearers is silent, so he did not open his mouth." Psalm 38:13 is the type; Isaiah 53:7 is the prophecy; the Passion is the fulfillment.</p>',
    "14": '<p>A type: "I am like a man who does not hear, with no counter-arguments in his mouth." The complete absence of self-defense — no counter-arguments, no refutation — is the posture of the one who entrusts the verdict to God rather than human judgment. 1 Peter 2:23: "When they hurled their insults at him, he did not retaliate; when he suffered, he made no threats. Instead, he entrusted himself to him who judges justly." Christ\'s silence in the trial is not helplessness — it is the total entrusting of his cause to the Father who vindicated him in the resurrection (the divine counter-argument to the human verdict).</p>',
    "15": '<p>A revelation of God: "But in you, LORD, I place my hope; you will answer, O Lord my God." The turn from affliction to hope — the pivot of all the Penitential Psalms — is possible because YHWH is the answerer. Hebrews 5:7: "During the days of Jesus\'s life on earth, he offered up prayers and petitions with fervent cries and tears to the one who could save him from death, and he was heard because of his reverent submission." Christ\'s hope in the Father ("you will answer") was vindicated: the Father answered the crucified Son\'s prayer by raising him from the dead.</p>',
    "16": '<p>A theme: "For I thought: Do not let them gloat over me — those who triumph over me when I stumble." The concern about the enemy\'s gloating triumph is the honor dimension of the Psalm: the sufferer does not want his defeat to become the occasion for the wicked\'s celebration. The mockery at the cross (Matt 27:39-44: "Come down from the cross... He trusts in God. Let God rescue him now") is exactly the gloating triumph the Psalmist fears. The divine answer — the resurrection — vindicates the one who was mocked and ensures that the gloating is ultimately silenced.</p>',
    "17": '<p>A type: "For I am about to stumble and my pain is always with me." The constant pain and imminent stumbling — the sufferer at the edge of collapse — is the threshold state that the Passion pushes through. Isaiah 53:3-4 describes the Servant as "familiar with pain." In Gethsemane, the pain is so acute that Christ\'s sweat is like drops of blood (Luke 22:44). The "always with me" of constant pain is the Incarnation\'s acceptance of the full weight of human suffering, carried voluntarily by the one who "became flesh" (John 1:14).</p>',
    "18": '<p>A type: "I confess my wrongdoing; I am distressed by my sin." The Penitential Psalm\'s confession of sin — the Psalmist\'s own genuine guilt before God — is the framework within which the typological reading operates carefully: Christ has no wrongdoing to confess (2 Cor 5:21; Heb 4:15). Yet he enters fully into the position of the one under divine judgment for sin. 2 Corinthians 5:21: "God made him who had no sin to be sin for us, so that in him we might become the righteousness of God." The confessor of Psalm 38:18 and the sinless Christ of the NT are not identical — but one is the type and the other the antitype who takes the confession\'s burden.</p>',
    "19": '<p>A theme: "But my enemies are full of life and strong; those who hate me without cause have multiplied." The vitality of the enemies and the baselessness of their hatred ("without cause") is the injustice theme of the Passion. John 15:25 quotes Psalm 69:4 — "they hated me without reason" — as a direct reference to those who opposed Jesus. The "without cause" hatred of Psalm 38:19 is the hatred of those who oppose the righteous because they are righteous, not because of any offense — the condition Christ experienced throughout his ministry.</p>',
    "20": '<p>A type: "Those who repay good with evil oppose me, because I pursue what is right." The inversion of just recompense — evil returned for good — is the shape of the Passion. Christ "went around doing good" (Acts 10:38) and was executed for it. Romans 5:8: "God demonstrates his own love for us in this: While we were still sinners, Christ died for us." Those who repay the greatest good (Christ\'s redemptive mission) with the greatest evil (crucifixion) are the ultimate fulfillment of Psalm 38:20\'s picture of the one opposed for pursuing righteousness.</p>',
    "21": '<p>A theme: "Do not abandon me, LORD; my God, do not stay far away." The prayer against divine abandonment — the deepest fear of the covenant person under judgment — reaches its ultimate expression in Christ\'s cry on the cross: "My God, my God, why have you forsaken me?" (Matt 27:46, Ps 22:1). The prayer "do not abandon me" becomes the question "why have you forsaken me?" — not because the Father actually abandons the Son permanently, but because the sin-bearing Messiah enters the full experience of separation that sin produces. The resurrection is the Father\'s answer: "I have not abandoned you."</p>',
    "22": '<p>A revelation of God: "Come quickly to help me, O Lord, my salvation." The final urgent cry — speed of divine help, divine identity as "my salvation" (<em>yĕšûʿātî</em>) — completes the Penitential Psalm with a prayer rather than an answer. The prayer for quick divine rescue is answered definitively in the resurrection: "in just a little while, he who is coming will come and will not delay" (Heb 10:37). The "Lord, my salvation" (<em>YHWH yĕšûʿātî</em>) is the name that the NT gives to Jesus — <em>Yēšûaʿ</em> means "YHWH saves." The Lord who is salvation is the name given to the one who answers the Psalm\'s final cry.</p>',
  },
  "39": {
    "1": '<p>A theme: Psalm 39 is a meditation on human mortality and silence before God, assigned to Jeduthun (one of David\'s chief musicians, 1 Chr 25:1). "I said, \'I will keep watch over my ways so I will not sin with my tongue\'" — the self-imposed silence to prevent sinning in speech. The discipline of the tongue is the posture of the one who knows the human tendency to accuse God when suffering. James 1:19-20 ("be slow to speak and slow to become angry") and Christ\'s own silence before his accusers (Matt 26:63) reflect this discipline: restraint before God\'s providential governance of suffering.</p>',
    "2": '<p>A theme: "I was mute and utterly silent, holding back even from what was good, and my pain intensified." The silence that intensifies suffering — holding back even appropriate speech until the pressure builds — is the paradox of grief. Christ\'s silence before his accusers was not diminished suffering but absorbed it: 1 Peter 2:23, "when he suffered, he made no threats. Instead, he entrusted himself to him who judges justly." The silence of Psalm 39:2 and the silence of Christ before Pilate share the same quality: the restraint of the one who trusts the divine judge rather than the human verdict.</p>',
    "3": '<p>A revelation of God: "My heart grew hot within me; as I brooded, the fire blazed up; then I spoke with my tongue." The moment of breaking silence — the internal fire that finally demands expression — is the movement from repression to prayer. Jeremiah experiences a similar compulsion: "But if I say, \'I will not mention his word or speak anymore in his name,\' his word is in my heart like a fire, a fire shut up in my bones" (Jer 20:9). Christ "learned obedience from what he suffered" (Heb 5:8) — the fire of his own passion-experience shapes the prayer of Gethsemane (Matt 26:39: "Yet not as I will, but as you will").</p>',
    "4": '<p>A revelation of God: "\'LORD, show me my end — how long I have to live; let me grasp how short-lived I am.\'" The prayer for self-knowledge about mortality — to genuinely understand one\'s finitude — is the basis of wisdom (Ps 90:12: "Teach us to number our days, that we may gain a heart of wisdom"). Christ, in taking on flesh, entered this mortal finitude deliberately: Hebrews 2:14-15, "Since the children share in flesh and blood, he too shared in their humanity so that by his death he might break the power of him who holds the power of death." The one who asked for wisdom about mortality resolved mortality\'s tyranny from within.</p>',
    "5": '<p>A revelation of God: "You have made my days barely a handbreadth long; my lifetime is as nothing in your sight. Truly every person at their best is only a breath (<em>hebel</em>)." The <em>hebel</em> (breath/vapor) vocabulary of Ecclesiastes enters the Psalm here. James 4:14: "What is your life? You are a mist that appears for a little while and then vanishes." The NT framing of earthly life as transient grounds the hope of resurrection: 2 Corinthians 4:17-18, "our light and momentary troubles are achieving for us an eternal glory that far outweighs them all." Christ\'s incarnation entered the <em>hebel</em> of mortal existence to transform it into eternal life.</p>',
    "6": '<p>A revelation of God: "Surely everyone moves about like a shadow; they are in commotion for nothing; they pile up wealth and do not know who will collect it." The "shadow" (<em>ṣelem</em>) of human activity — movement without substance, accumulation without inheritor — is the Psalm\'s diagnosis of life under mortality. Luke 12:20: "You fool! This very night your life will be demanded from you. Then who will get what you have prepared for yourself?" Christ warns against the commotion of Psalm 39:6 in favor of being "rich toward God" (Luke 12:21). The resurrection reframes all accumulation: only what is done in Christ endures (1 Cor 3:13-14).</p>',
    "7": '<p>A revelation of God: "And now, Lord, what do I wait for? My hope is in you." The pivot from the despair of vv1-6 to the declaration of hope in YHWH alone is the theological turn of the Psalm. 1 Peter 1:3: "Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead." The "my hope is in you" of Psalm 39:7 becomes, in the NT, the living hope that the resurrection of Christ grounds. Christ is both the content of the hope (the risen Lord) and the means of its realization.</p>',
    "8": '<p>A theme: "Rescue me from all my transgressions; do not make me a disgrace before fools." The prayer for rescue from sin and from the shame of sin-exposure before the foolish is the Psalm\'s petition. Romans 5:1: "since we have been justified through faith, we have peace with God through our Lord Jesus Christ." The shame before fools that Psalm 39:8 dreads — the exposure of sin — is resolved not by personal improvement but by justification: the declaration of righteousness through Christ that removes the basis for shame (Rom 8:1: "no condemnation for those who are in Christ Jesus").</p>',
    "9": '<p>A type: "I am silent; I do not open my mouth, because this is your doing." The acceptance of divine sovereignty over suffering — "this is your doing" — is the deepest theological affirmation of the Psalm. It echoes Job 2:10 ("Shall we accept good from God, and not trouble?") and anticipates Christ\'s Gethsemane acceptance: "Not my will, but yours be done" (Luke 22:42). The "this is your doing" of Psalm 39:9 — the recognition that even unjust suffering is within divine governance — is the framework within which the Passion becomes comprehensible as the Father\'s own act of rescue.</p>',
    "10": '<p>A revelation of God: "Take away your affliction from me; I am worn down by the blow of your hand." The prayer for relief from the divine blow — the affliction that has exhausted the sufferer — models honest engagement with God in suffering. Hebrews 12:5-6 quotes Proverbs 3:11-12 ("the Lord disciplines the one he loves") in the context of suffering. Christ\'s cry "My God, my God, why have you forsaken me?" (Matt 27:46) is the ultimate prayer of the one worn down by what feels like divine abandonment — and the resurrection is the answer. Honest prayer under divine discipline is the pattern Christ establishes.</p>',
    "11": '<p>A revelation of God: "When you correct someone for their iniquity with rebukes, you consume like a moth everything they prize; truly every person is only a breath." The divine correction consuming what is valued — the moth of divine discipline destroying the fabric of human accumulation — is the Psalm\'s image of God\'s sovereignty over mortal life. Hebrews 12:11: "No discipline seems pleasant at the time, but painful. Later on, however, it produces a harvest of righteousness and peace for those who have been trained by it." The consuming correction of Psalm 39:11 is the discipline that produces the righteousness which Christ mediates and which those who share in his suffering also receive.</p>',
    "12": '<p>A direct connection: "Hear my prayer, LORD, and listen to my cry; do not stay silent at my tears. I am a stranger in your presence, a temporary traveler (<em>gēr</em> / <em>tôšāb</em>), as all my ancestors were." The self-identification as <em>gēr</em> (resident alien) and <em>tôšāb</em> (temporary settler) — Abraham and the patriarchs\' status in Canaan — is quoted in Hebrews 11:13 of the heroes of faith: "they admitted that they were foreigners and strangers on earth." 1 Peter 2:11 applies this to the Christian community: "Dear friends, I urge you, as foreigners and exiles..." Christ himself had "nowhere to lay his head" (Matt 8:20) — the Son of Man as the ultimate stranger and traveler whose permanent home is the Father\'s presence.</p>',
    "13": '<p>A revelation of God: "Turn your gaze from me, so that I may recover joy before I depart and am gone." The paradoxical prayer — asking God to look away so the mortal sufferer can breathe before death — is the raw honesty of one overwhelmed by divine presence in judgment. The "before I depart and am gone" is the Psalm\'s acknowledgment of death\'s imminence. Christ\'s resurrection transforms this: Psalm 23:4 ("Even though I walk through the darkest valley") and John 14:3 ("I will come back and take you to be with me") are the answer to Psalm 39:13. The departure the Psalmist dreads becomes, in Christ, the transition to the Father\'s house.</p>',
  },
  "40": {
    "1": '<p>A type: "I waited patiently for the LORD; he turned to me and listened to my cry." The patient waiting (<em>qāwōh qiwwîtî</em>, the intensive form: I waited with waiting) followed by divine attention and listening is the resurrection pattern. Hebrews 5:7: "he offered up prayers and petitions with fervent cries and tears to the one who could save him from death, and he was heard because of his reverent submission." The patient waiting of Psalm 40:1 and the divine turning-to-listen is the Gethsemane-to-resurrection movement: Jesus waited through the cross; the Father turned and listened in the resurrection.</p>',
    "2": '<p>A type: "He lifted me out of the pit of destruction, from the muddy bog; he set my feet on a rock and made my steps firm." The rescue from the pit (<em>bôr šĕʾôn</em>, pit of destruction — a Sheol term) and from the mud onto a rock is resurrection imagery. Acts 2:24: "God raised him from the dead, freeing him from the agony of death, because it was impossible for death to keep its hold on him." The "pit of destruction" = Sheol = death; the "rock" with firm steps = the resurrection ground on which Christ now stands. The mud-and-pit rescue of Psalm 40:2 is the type whose fulfillment is the first Easter morning.</p>',
    "3": '<p>A theme: "He put a new song in my mouth, praise to our God; many will see and be filled with awe and will put their trust in the LORD." The new song (<em>šîr ḥādāš</em>) placed by YHWH in the rescued person\'s mouth — and the public witness that produces awe and trust — is the pattern of the resurrection witness. Acts 2:47: "praising God and enjoying the favor of all the people. And the Lord added to their number daily those who were being saved." The "many will see... and will put their trust in the LORD" of Psalm 40:3 describes the apostolic proclamation: the new song of resurrection praise produces faith in those who hear it.</p>',
    "4": '<p>A revelation of God: "Blessed is the one who makes the LORD his trust and does not turn to the proud or to those who follow falsehood." The beatitude of trust in YHWH — exclusive, not divided with human power structures or false gods — is the wisdom foundation of faith. Romans 10:11, quoting Isaiah 28:16: "Anyone who trusts in him will never be put to shame." Christ is both the object of this trust and the demonstration of its reward: the one who trusted the Father absolutely through the cross received the vindication of the resurrection (Phil 2:9). Trust in Christ is the NT form of making "the LORD his trust."</p>',
    "5": '<p>A revelation of God: "You have multiplied your wonderful deeds and your thoughts toward us, O LORD my God; no one can compare to you." The divine incomparability — the accumulation of wondrous acts beyond counting — is the hymnic foundation of Psalm 40. In Christ, the incomparable wondrous deed is the cross and resurrection: 1 Corinthians 1:18, "the message of the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God." The "wonderful deeds" of the Exodus and the Psalter are multiplied and surpassed in Christ — the deed that could not be counted because it is inexhaustible in its effects.</p>',
    "6": '<p>A direct citation: "Sacrifice and grain offering you did not want; but you have given me opened ears; burnt offering and sin offering you have not asked for." Hebrews 10:5-7 quotes the LXX form of vv6-8 — "a body you prepared for me" (where MT has "opened ears") — as the very words of Christ entering the world: "Sacrifice and offering you did not desire, but a body you prepared for me; with burnt offerings and sin offerings you were not pleased. Then I said, \'Here I am — it is written about me in the scroll — I have come to do your will, my God.\'" Psalm 40:6 is the theological fulcrum of Hebrews 10\'s argument that the entire Levitical sacrifice system is superseded by Christ\'s one offering of his body.</p>',
    "7": '<p>A direct citation: "Then I said, \'Here I am; in the scroll of the book it is written about me.\'" This verse is the centerpiece of Hebrews 10\'s Christological reading: the whole OT scroll was written about Christ, and he comes to fulfill it. Luke 24:44: "Everything must be fulfilled that is written about me in the Law of Moses, the Prophets and the Psalms." John 5:39: "These are the very Scriptures that testify about me." The "Here I am" (<em>hinnēnî</em>) is the classic prophetic availability formula (Isa 6:8: "Here am I. Send me!") — Christ entering history as the one who fulfills the whole written anticipation of the OT.</p>',
    "8": '<p>A direct citation: "I delight to do your will, O my God; your instruction is within my heart." Hebrews 10:7 quotes this as Christ\'s words. John 6:38: "For I have come down from heaven not to do my will but to do the will of him who sent me." John 4:34: "My food is to do the will of him who sent me." Philippians 2:8: "he humbled himself by becoming obedient to death — even death on a cross." The "delight to do your will" of Psalm 40:8 is not mere compliance but joyful, interior alignment — and the law "within the heart" is the New Covenant promise of Jeremiah 31:33, embodied in Christ before being extended to his people through the Spirit.</p>',
    "9": '<p>A type: "I have announced righteousness in the great assembly; I have not held my lips back — LORD, you know it." The public proclamation of righteousness in the community\'s assembly — open, unrestrained — is the prophetic-priestly role of the Davidic king. Christ\'s public teaching in the temple courts (Luke 19:47; 20:1) and his bold proclamation of the gospel is the fulfillment: John 18:20, "I have spoken openly to the world. I always taught in synagogues or at the temple, where all the Jews come together. I said nothing in secret." The "great assembly" proclamation of Psalm 40:9 is the type of Christ\'s public Messianic declaration.</p>',
    "10": '<p>A type: "I have not hidden your righteousness in my heart; I have declared your faithfulness and your salvation; I have not concealed your steadfast love or your truth from the great assembly." The foursome of what has been declared — righteousness, faithfulness, salvation, steadfast love, truth — is the covenant-attribute catalogue. Titus 3:4-5: "But when the kindness and love of God our Savior appeared... he saved us." Christ\'s entire ministry is the unconcealedproclamation of the divine attributes of Psalm 40:10 — each one made visible in his person and work: righteousness (2 Cor 5:21), faithfulness (Heb 10:23), salvation (Luke 4:18), steadfast love (John 15:13), truth (John 14:6).</p>',
    "11": '<p>A revelation of God: "As for you, LORD, do not withhold your compassion from me; let your steadfast love and truth continually protect me." The prayer for the divine compassion and ḥesed-truth pair to be protection is the Psalm\'s personal petition after the public proclamation of vv9-10. John 1:14 describes Christ as "full of grace and truth" — the ḥesed-ʾĕmet (steadfast love and truth) of Psalm 40:11 is the divine pair that is embodied in the Word made flesh. The prayer for ḥesed-ʾĕmet as protection is answered when "grace and truth came through Jesus Christ" (John 1:17).</p>',
    "12": '<p>A type: "For countless evils have closed in around me; my iniquities have caught up with me until I cannot see clearly — they are more than the hairs of my head, and my courage fails." The return from the praise of vv1-11 to the crisis of personal sin — iniquities that blind and overwhelm — is the pastoral honesty of the Psalm. For Christ, who bears not his own iniquities but ours: Isaiah 53:6, "the LORD has laid on him the iniquity of us all." The "countless evils" and "iniquities more than hairs of my head" that overwhelm the Psalmist become, at Gethsemane and the cross, the full weight of human sin that Christ takes on voluntarily.</p>',
    "13": '<p>A type: "Please, LORD, come to rescue me; LORD, hurry to help me." The urgent cry for divine rescue — speed, urgency — is the Psalm\'s Gethsemane moment: the human vulnerability of the one who genuinely needs help. Hebrews 5:7: "he offered up prayers and petitions with fervent cries and tears." The urgency of "hurry to help me" is the cry of the incarnate Son in the Passion — not self-sufficient, not performing strength, but genuinely needing the Father\'s rescue. The Father\'s answer is the resurrection: the rescue comes, but through death, not avoiding it.</p>',
    "14": '<p>A shadow: "Let those who seek to take my life be put to shame and confounded; let those who wish me harm be turned back in disgrace." The imprecatory prayer against those seeking the Psalmist\'s life — shame and disgrace on the persecutors — is the Psalm\'s justice element. At the resurrection, the scheme of those who sought Christ\'s death is definitively "put to shame": 1 Corinthians 2:8, "None of the rulers of this age understood it, for if they had, they would not have crucified the Lord of glory." The cross appeared as their victory; the resurrection revealed it as their shame. The full disgrace awaits the final judgment (Rev 20:11-15).</p>',
    "15": '<p>A shadow: "Let those who mock me with \'Aha! Aha!\' be horrified by their own shame." The "Aha! Aha!" mockers — those who take pleasure in the Psalmist\'s distress — are the Passion crowd. Matthew 27:39-40: "Those who passed by hurled insults at him, shaking their heads... \'Come down from the cross, if you are the Son of God!\'" Mark 15:29 uses the same mocking gesture. The "Aha!" gloating of Psalm 40:15 is enacted at the crucifixion — and the promised reversal (their horror and shame) is the eschatological judgment that the resurrection initiates.</p>',
    "16": '<p>A revelation of God: "Let all who seek you rejoice and be glad in you; let those who love your salvation always say, \'Great is the LORD!\'" The communal rejoicing of the seekers — gladness in YHWH, constant praise of his salvation — is the eschatological community that the Psalm envisions as the answer to the Psalmist\'s crisis. Revelation 19:7: "Let us rejoice and be glad and give him glory! For the wedding of the Lamb has come." The "great is the LORD" of Psalm 40:16 becomes the great chorus of Revelation\'s heavenly worship — those who love his salvation praising the risen Christ throughout eternity.</p>',
    "17": '<p>A direct connection: "As for me, I am poor and needy; yet the Lord thinks of me. You are my help and my deliverer — do not be slow, my God." The closing declaration — "poor and needy" (<em>ʿānî wĕʾebyôn</em>) yet beloved and thought of by YHWH — is the Psalm\'s final Christological statement. 2 Corinthians 8:9: "For you know the grace of our Lord Jesus Christ, that though he was rich, yet for your sake he became poor, so that you through his poverty might become rich." Christ voluntarily entered the "poor and needy" condition of Psalm 40:17 — the incarnation is the divine Lord becoming the one who needs the Father\'s help and deliverance. And the Father is "not slow": the resurrection is the timely answer.</p>',
  }
}

# INTENT: mkt-christ for Psalms 37–40 — Wisdom acrostic on theodicy (Ps 37: direct
#   Beatitudes citation of v11 at Matt 5:5 for 'meek inherit the earth'); Penitential
#   Psalm type of sin-bearing Christ without personal sin (Ps 38: silence → Isa 53:7/Matt
#   26:63; v11 friends at distance → Luke 23:49); mortality meditation and stranger-alien
#   theology (Ps 39: v12 → Heb 11:13; 1 Pet 2:11); and the theological center of Hebrews
#   10 (Ps 40: vv6-8 LXX directly cited as Christ's words entering the world).
# CHANGE? If mkt-christ/psalms.json structure changes, update load_comm/save_comm source string.
# VERIFY: python3 -c "import json; d=json.load(open('data/commentary/mkt-christ/psalms.json'));
#   print('40 v6:', d.get('40',{}).get('6','MISSING')[:80])"

def main():
    existing = load_comm('mkt-christ', 'psalms')
    merge_comm(existing, PSALMS)
    save_comm('mkt-christ', 'psalms', existing)
    total = sum(len(v) for v in existing.values())
    print(f'Psalms mkt-christ: {len(existing)} chapters, {total} verse entries total')
    print('Psalms 37–40 mkt-christ written.')

if __name__ == '__main__':
    main()
