"""
MKT Context Commentary — Hosea chapters 13–14
Run: python3 scripts/zc-context-hosea-13-14.py

Ch13: Ephraim's self-destruction — from trembling-nations status to Assyrian annihilation.
      Core ANE contexts: Baal-Peor, Jeroboam's calves, predatory-animal imagery,
      the sealed-sin record, the birth-pang metaphor, v14 Sheol-ransom question
      (Paul's 1 Cor 15:55 taunt), Sargon II's destruction of Samaria 722 BCE.
Ch14: The return and restoration — shuv vocabulary, verbal sacrifice (parim sefateinu),
      three explicit renunciations, free-will love (nedavah), dew/lily/cedar/cypress imagery,
      sapiential epilogue as the book's hermeneutical key.
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(layer, book):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    return json.loads(p.read_text()) if p.exists() else {}

def save_comm(layer, book, data):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

HOSEA = {
  "13": {
    "1": "<p>Chapter 13 opens by recalling Ephraim's former greatness: when Ephraim spoke, the nations trembled. The tribe of Ephraim was the dominant force in the northern kingdom from Joshua's time (Josh 17–18); its name became virtually synonymous with the northern nation (Hosea uses 'Ephraim' 36 times). The pivot: <em>vayashem baBa'al vayyamot</em> — he became guilty through Baal and died. The Baal-Peor incident (Num 25:1–9, where Israel yoked itself to Baal and 24,000 died) or the Bethel and Dan golden calves of Jeroboam I (1 Kings 12:28–29) is the historical hinge. The 'death' is covenant death: the nation that once commanded the nations' fear is already, spiritually, a corpse.</p>",
    "2": "<p>V2 describes the escalating pattern: they sin more and more (<em>vayosifu lachato</em>). The molten images (<em>massekah</em>) made from silver echo the Jeroboam calves and the broader high-place cult. <em>Kimtivonatam</em> (according to their own devising) — the idols are projections of human imagination, self-crafted theology that mirrors the worshippers back to themselves rather than revealing YHWH. The kissing of calves (<em>noshequn 'agalim</em>) is a specific cultic affection ritual documented in ANE sources: devotees kissed divine statues and sacred animals as acts of worship. Hosea diagnoses this as the deepest irony — the more elaborate the worship, the deeper the apostasy.</p>",
    "3": "<p>V3 deploys four transience similes drawn from the Palestinian agricultural environment: morning mist (<em>anan boqer</em>), early dew (<em>tal mashkim holekh</em>) that evaporates by mid-morning in the summer heat, chaff swept from the threshing floor by the west wind (<em>motz yesuar migoren</em>), and smoke from a chimney opening (<em>ashan mearzubah</em>). These are not exotic metaphors but the daily visible evidence of transience in an agricultural society. Every farmer watching his dew-covered fields in early morning and seeing them dry by noon would understand: the blessing of Ephraim's security is as temporary as the morning moisture.</p>",
    "4": "<p>V4 returns to the covenant formula: <em>vaAnokhi YHWH Elohekha me'eretz Mitzrayim</em> — I am the LORD your God from the land of Egypt. This is the self-identification that opens the Decalogue (Exod 20:2). The political background is crucial: Israel was actively seeking salvation (<em>moshia</em>, savior) from Assyria (2 Kings 17:3: Hoshea sent tribute to Shalmaneser) and Egypt (Hosea 7:11: Ephraim is like a silly dove, calling to Egypt). YHWH insists: there is no savior except me (<em>uMoshia ayin zulati</em>). The same word <em>moshia</em> that Israel was seeking in foreign capitals belonged exclusively to YHWH.</p>",
    "5": "<p>V5: <em>Ani yeda'tikha bamidbar be'eretz talvaot</em> — I knew you in the wilderness, in a land of scorching heat (<em>talvaot</em>, H8437 — parched, scorching land). The verb <em>yada'</em> (to know) is the covenant-intimacy verb throughout Hosea — the same used for the marriage relationship (Hos 2:20: you will know YHWH). The wilderness period was the place of covenant formation: Deut 2:7 (YHWH your God has been with you; you lacked nothing); Jer 2:2 (I remember the devotion of your youth, how you followed me in the wilderness, in a land not sown). The burnt, cracked landscape of the Sinai/Negev wilderness was the setting for the most intimate covenant moment in Israel's history.</p>",
    "6": "<p>V6 is Deut 8:11–17 in four words: <em>keMar'itam vayyisba'u sabe'u vayyarom libbam</em> — when I fed them they were satisfied; when satisfied they became proud; therefore they forgot me. Deut 8:11–14: beware lest you forget YHWH your God ... when you have eaten and are full and have built good houses ... then your heart be lifted up and you forget YHWH. The Deuteronomic warning found its exact fulfillment in the northern kingdom's prosperity under Jeroboam II (ca. 793–753 BCE), the economic high-water mark of the northern kingdom that also generated the social injustice Amos condemned (Amos 6:4–6). Prosperity and forgetting are, in the OT's analysis, chronically linked.</p>",
    "7": "<p>V7: <em>Va'ehi lahem kemo shachal</em> — I will be to them like a lion; I will lurk like a leopard on the road. The predatory-animal imagery for YHWH's judgment is concentrated here and in v8 (cf. Lam 3:10–12 for the same imagery applied to Jerusalem's destruction; Amos 3:4–8 for the lion and prophecy). The lion and leopard are the apex predators of the Palestinian landscape — both were present in Israel's hill-country environment until relatively recently. The leopard lurking on the <em>darech</em> (road/way) is the ambush of judgment on the path Israel has chosen: the very route of their political machinations becomes the place of their destruction.</p>",
    "8": "<p>V8: <em>Efgesha'em kedov shakul veqera' seghor libbam</em> — I will attack them like a bear robbed of her cubs and tear open the enclosure of their heart. The bear robbed of cubs is the most dangerous ANE animal metaphor — a she-bear protecting young was the standard symbol for uncontrollable violent defense (2 Sam 17:8; Prov 17:12: better to meet a she-bear robbed of her cubs than a fool in his folly). The tearing open of the chest/heart-region is anatomically specific: lions kill by opening the thoracic cavity. V8b's wild animals (<em>chayat hasadeh</em>) consuming the remains describes precisely what happened to unburied corpses in the aftermath of the Assyrian destruction of Samaria (722 BCE).</p>",
    "9": "<p>V9: <em>Shichatekha Yisrael ki vi beezrekha</em> — your destruction is in yourself, O Israel; but your help (<em>ezer</em>) is in me alone. The reflexive self-destruction: the covenant violations are not merely rule-infractions but choices that structurally destroy the one who makes them. The positive reversal in the same verse is remarkable: <em>ki vi</em> (but in me). The divine helper (<em>ezer</em>) is the vocabulary of Ps 121:2 (my help comes from the LORD who made heaven and earth) and Deut 33:29 (there is none like the God of Jeshurun, who rides through the heavens to your help). Even at the announcement of destruction, the door of restoration is left open.</p>",
    "10": "<p>V10: <em>Ehi malkekha efo veyoshia'akha</em> — where is your king now that he may save you in all your cities? The question revisits 1 Sam 8:5–20 (give us a king to judge us like all the nations). The historical pressure: during the final two decades of the northern kingdom (735–722 BCE), six kings ruled in 20 years, four assassinated (2 Kings 15:10, 14, 25, 30). The monarchy that was demanded to save (<em>yoshia</em>) cannot save — the same verb YHWH claimed for himself in v4 (<em>uMoshia ayin zulati</em>). The polemic is etymological: Hoshea (the final king of Israel) shares the root — yet he cannot deliver.</p>",
    "11": "<p>V11: <em>Eten lekha melekh beappi va'eqqach bezza'ami</em> — I gave you a king in my anger, and I took him away in my wrath. The divine authorization and removal of monarchy is the theological interpretation of the entire monarchic history. The giving in anger: 1 Sam 8:22 (YHWH said to Samuel, obey their voice and make them a king). The taking in wrath spans the assassinations and deportations that ended the northern dynasty. The verse is not about one king but about the entire institution of monarchy as granted under conditions of divine displeasure — it was a concession, not a gift.</p>",
    "12": "<p>V12: <em>Tzarur avon Ephraim tzefunah chata'ato</em> — the iniquity of Ephraim is bound up (<em>tzarur</em>, H6887 — tied/bundled); his sin is stored up (<em>tzafun</em>, H6845 — hidden/kept in reserve). The imagery is of a sealed legal document: in Mesopotamian legal practice, clay tablets recording debts and crimes were bound and sealed in clay envelopes (bullae) for preservation and future reference. The sin-record cannot be denied when judgment comes — the evidence is legally preserved. This verse functions as the covenantal indictment document that will be opened at the time of Assyrian judgment.</p>",
    "13": "<p>V13: The birth-pang metaphor (<em>chevlei yoledah yavo'u lo</em>) for national crisis appears throughout the prophets (Isa 26:17–18; 66:7–9; Jer 30:6–7; John 16:21). The specific image: <em>hu ven lo chakham</em> — he is an unwise child, for at the time he should not stand at the mouth of the womb (<em>mishvar banim</em>). This is a breech birth: the child that does not turn at the critical moment makes delivery impossible, and both mother and child die. Israel has been given the birth pangs of judgment (the Assyrian threat) but refuses to turn in the right direction (repentance/teshuvah — the same root as <em>shuv</em>, return) to be born into the new age. The refusal of the turn kills the one who needs to be born.</p>",
    "14": "<p>V14 is the book's most theologically dense verse and its most disputed. <em>Miyyad she'ol efdem mimmavet eg'alem</em> — Shall I ransom them from the power of Sheol? Shall I redeem them from death? The verbs <em>padah</em> (ransom, H6299) and <em>ga'al</em> (redeem, H1350 go'el) are the strongest covenantal rescue vocabulary. The subsequent lines — <em>ehi devarikhah mavet ehi qovetikha she'ol</em> (Where are your plagues, O Death? Where is your destruction, O Sheol?) — can be read as threats against Israel (death's plagues are summoned against the nation) or as taunts against Death itself (death's power is challenged). The MT's rhetorical questions lean toward judgment; the LXX reads them affirmatively (I will rescue them). Paul in 1 Cor 15:54–55 cites this as the resurrection taunt, transforming Hosea's ambiguous question into the victory cry of the risen Christ over death.</p>",
    "15": "<p>V15: <em>Ki hu ben achim yafri yavo qadim ruach YHWH</em> — though he flourishes among his brothers (or: though he is fruitful among reeds), an east wind will come, a wind of YHWH rising from the wilderness. The pun on Ephraim's name is embedded: the name Ephraim (H669) sounds like <em>para</em> (H6509, to be fruitful); <em>yafri</em> = will be fruitful. The east wind (<em>qadim</em>) is the hot, desiccating sirocco that arrives from the eastern desert in late spring, destroying crops in hours. As the wind of YHWH (<em>ruach YHWH</em>), it is the Assyrian army sweeping from the east — the instrument that will dry up Ephraim's spring (<em>maqoro</em>) and seal up his fountain (<em>ma'yano</em>). The Assyrian annals confirm the systematic destruction of the agricultural infrastructure of conquered territories.</p>",
    "16": "<p>V16 (Hebrew 14:1): <em>Teshlam Shomeron ki marta biEloheyha</em> — Samaria will bear her guilt, for she rebelled against her God. The historical fulfillment: Sargon II of Assyria destroyed Samaria in 722 BCE (2 Kings 17:3–6), deporting 27,290 Israelites according to his own annals (Sargon II Nimrud Prism). The siege-violence against infants (<em>oleleihem yiruttashu</em>, their infants dashed) and pregnant women (<em>hariyotav tebuqa'enah</em>, their pregnant women ripped open) was standard ANE siege aftermath — documented also in 2 Kings 8:12 and Amos 1:13. Hosea's prophecy (delivered during the reign of Jeroboam II, ca. 750 BCE) preceded the historical fulfillment by almost 30 years.</p>"
  },
  "14": {
    "1": "<p>Chapter 14 opens with the climactic invitation of the entire book: <em>Shuv Yisrael ad YHWH Elohekha</em> — Return, O Israel, to the LORD your God. The verb <em>shuv</em> (to return, H7725) is the pivotal term of Hosea (2:7; 3:5; 5:4; 6:1; 7:10; 11:5; 12:6 — everywhere in the book). The preposition <em>ad</em> (return <em>as far as</em> YHWH) is stronger than <em>el</em> (toward): the return must go all the way to the God who is the source, not merely a directional movement. <em>Ki kashalta ba'avonekha</em> — you have stumbled because of your iniquity — uses the covenant-curse vocabulary of Lev 26:36–37 (they shall stumble over one another as if escaping a sword). The cause is identified honestly: the stumbling was self-caused by covenant violation.</p>",
    "2": "<p>V2: <em>Qechu imakhem devarim veshuvau el YHWH</em> — take words with you and return to YHWH. The instruction is precise: bring <em>words</em>, not livestock. The prescribed prayer formula that follows is one of the OT's most compact repentance liturgies: <em>kol tissa avon veqach tov</em> (forgive all iniquity and receive us graciously). The phrase <em>uneshalmah parim sefateinu</em> — we will offer the bulls of our lips (<em>parim sefateinu</em>) — is a stunning reinterpretation of the sacrificial system: the sacrifice is verbal confession and praise, not animal. Hebrews 13:15 cites this formula directly (through him then let us continually offer up a sacrifice of praise to God, that is, the fruit of lips that acknowledge his name), revealing that Hosea's invitation anticipated the new covenant's spiritualization of worship.</p>",
    "3": "<p>V3 contains three explicit renunciations that correspond to Hosea's three prosecutions throughout the book: (1) <em>lo yoshienu Ashur</em> — Assyria will not save us (rejecting foreign alliance, the sin of Hos 7:11; 8:9); (2) <em>lo nirkav al sus</em> — we will not ride on horses (rejecting military self-reliance, condemned in Isa 31:1: woe to those who rely on horses); (3) <em>velo nomar od Eloheinu lema'aseh yadenu</em> — we will not say 'Our God' to the work of our hands (rejecting idolatry). These three renunciations map onto the three-part diagnosis of Israel's failure: political apostasy (foreign alliances), military apostasy (independent military power), and religious apostasy (idols). The confession is specific and comprehensive — a surgical repudiation of each specific violation.</p>",
    "4": "<p>V4: <em>Erpa meshuvotam ohavem nedavah ki shav appi mimehem</em> — I will heal their apostasy (<em>meshuvotam</em>); I will love them freely, for my anger has turned away from them. The word <em>meshuvah</em> (apostasy, H4878) is the noun form of <em>shuv</em> — YHWH heals the very return-failure itself, the structural inability to repent. <em>Nedavah</em> (H5071, free-will, voluntarily, gratuitously) — the love is unconditional, without cause in the beloved's merit. In the sacrificial system, the <em>nedavah</em>-offering was the highest category — given out of pure joy and gratitude, not obligation or atonement. YHWH's restoration-love has the character of the freest possible gift. This is the theological resolution of the Gomer marriage narrative: the husband who loved without condition despite repeated infidelity.</p>",
    "5": "<p>V5: <em>Ehyeh kaTal leYisrael yifra kaSoshana veyach shereshav kaLevanon</em> — I will be like the dew to Israel; he will blossom like a lily and take root like the cedars of Lebanon. The dew (<em>tal</em>) is the daily morning moisture that sustains life in the Mediterranean dry season (May–September), when no rain falls for months. Every living thing depends on the nightly dew condensing on leaves and rocks. The lily (<em>shoshanna</em> — same root as the Shulammite in Song 2:1–2) and the cedar of Lebanon (the most famous and durable tree of the ANE, used in Solomon's temple, 1 Kings 6:9–10) image beauty and permanence. This is the covenant restoration of what was reversed in ch2:8–12 (the withholding of grain, wine, oil, and wool).</p>",
    "6": "<p>V6: <em>Yelekhu yonaqotav vihi che'zayit hodo uvere'ach lo kaLevanon</em> — his branches will spread out; his beauty will be like the olive tree, and his fragrance like that of Lebanon. The olive tree was the most economically significant tree in ancient Palestine — providing food, light, medicine, and wood (Deut 8:8 includes it among the seven species of the Promised Land). The olive's beauty is understated but enduring: silver-green leaves, gnarled ancient trunk, centuries of bearing fruit. A healthy olive grove was the visible sign of covenant prosperity (Ps 52:8: I am like a green olive tree in the house of God). The fragrance of Lebanon — cedar resin, forest aromatics — was the aromatic ideal of the ANE (Song 4:11; 1 Kings 10:2).</p>",
    "7": "<p>V7: <em>Yashuvu yoshvei betzilo yechayu dagan veyifretzu kagafen</em> — those who dwell in his shade will flourish again; they will thrive like grain and blossom like the vine; their fragrance will be like the wine of Lebanon. The shade (<em>tzel</em>) of the restored Israel provides shelter and life for those who dwell in it. In a hot, arid climate, shade was a primary blessing and a figure for divine protection (Ps 91:1: he who dwells in the shelter of the Most High will abide in the shadow of the Almighty; Song 2:3: I sat down in his shade with great delight). The grain (<em>dagan</em>) and vine (<em>gafen</em>) are the first two of Deut 8:8's promised land bounty — they were taken away in Hos 2:9 (I will take back my grain and wine) and are now fully restored.</p>",
    "8": "<p>V8: <em>Ephraim mah li od le'atzabim</em> — Ephraim, what more have I to do with idols? The covenant restoration is complete when Ephraim himself repudiates idols. YHWH speaks both as the one who answers and as the one who observes: <em>ani anitiv va'ashurenu</em> — I am the one who answers him and watches over him. The closing image — <em>ani kaberosh ra'anan mimmeni peryekha nimtza</em> — I am like a flourishing cypress (<em>berosh ra'anan</em>); your fruit comes from me — is the theological reversal of the Baal-fertility cult. Baal was worshipped precisely as the deity who provided agricultural fruitfulness; YHWH reclaims that role definitively. The evergreen cypress (or juniper) never loses its foliage even in drought, symbolizing the unfailing source of life.</p>",
    "9": "<p>V9: <em>Mi chakham veyaven eleh nabon veyeda'em ki yesharim darkei YHWH</em> — who is wise? Let him understand these things. Who is discerning? Let him know them. For the ways of the LORD are right. The wisdom epilogue is characteristic of prophetic books edited for sapiential reading (cf. Amos 5:13 for a similar wisdom voice within prophecy; Ps 107:43 as a psalm that ends in the same register). The <em>chakham</em> (wise) and <em>nabon</em> (discerning) vocabulary is the technical language of Proverbs (1:2–6). <em>Yesharim darkei YHWH</em> — the ways of YHWH are right/straight/upright — uses the same adjective as Jeshurun (H3484, the upright one, an honorific name for Israel in Deut 32:15). The book closes with the fundamental choice that it has illustrated throughout: the upright walk in YHWH's ways and live; transgressors stumble in them. The whole marriage-apostasy-restoration narrative of Hosea is, in the final verse, offered as a reading text for those wise enough to understand it.</p>"
  }
}

def main():
    c = load_comm('mkt-context', 'hosea')
    merge_comm(c, HOSEA)
    save_comm('mkt-context', 'hosea', c)
    total = sum(len(vv) for vv in HOSEA.values())
    parts = ', '.join(f'ch{ch}={len(HOSEA[ch])}' for ch in sorted(HOSEA, key=int))
    print(f'Hosea 13–14 mkt-context: {total} verses written ({parts}).')

if __name__ == '__main__':
    main()
