"""
MKT Christ Commentary — Jeremiah chapters 10–13 (fill)
Fills 45 missing verses: ch10 v4,8,9,15,17-20,22; ch11 v2,3,6,7,9,10,12,13,16-18,22;
ch12 v2,4,6,8,9,12,13,16; ch13 v2-8,10,12,18-22,24,26
Run: python3 scripts/zc-christ-jeremiah-fill.py

Key decisions:
- ch10 idol polemic: contrast with Col 1:15 (Christ as the true image of God)
- ch11:19 already exists (lamb-to-slaughter verse); fill covers surrounding verses
- ch13 linen sash: sign-act of binding/union anticipates Incarnation
- Ch12:9 speckled bird: read as type of Christ the Outsider/Rejected
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

JER_CHRIST = {
  "10": {
    "4": "<p>A shadow: the idol adorned with silver and gold, fastened with nails so it cannot topple. The idol is static, manufactured, and powerless — a thing made by human hands rather than a person who acts. Christ is the antithesis: he is &ldquo;the image of the invisible God&rdquo; (<a class=\"ref\" data-ref=\"Col 1:15\">Col 1:15</a>), not crafted but begotten, not nailed into place but nailed to the cross by his own willing submission. The nails that secure the idol in verse 4 are echoed by the nails of the Passion — but their purpose is inverted. The idol is nailed down so it cannot move; Christ is nailed up so that he can draw all people to himself (<a class=\"ref\" data-ref=\"John 12:32\">John 12:32</a>).</p>",
    "8": "<p>A theme: the worthlessness of idol instruction — &ldquo;the instruction that comes from idols is nothing but worthless wood.&rdquo; The idols teach nothing; they have no word of life to give. Christ is the Word who gives life: &ldquo;The words I have spoken to you are spirit and they are life&rdquo; (<a class=\"ref\" data-ref=\"John 6:63\">John 6:63</a>). Where idol instruction is wood — inert, lifeless, combustible — Christ&rsquo;s word is living and active, sharper than any two-edged sword (<a class=\"ref\" data-ref=\"Heb 4:12\">Heb 4:12</a>). Jeremiah&rsquo;s polemic against idol-instruction prepares for the NT&rsquo;s proclamation of the Logos who speaks with divine authority.</p>",
    "9": "<p>A shadow: the craftsman-made gods — beaten silver, worked gold, clothed in violet and purple. These gods are the product of the craftsman (<em>maʿăśēh ḥārāš</em>); their existence depends entirely on human artisanship. Christ is the maker, not the made: &ldquo;all things were made through him, and without him was not anything made that was made&rdquo; (<a class=\"ref\" data-ref=\"John 1:3\">John 1:3</a>). The contrast in Jer 10:9 between the elaborately dressed idol and the living God of v.10 finds its ultimate form in the incarnation paradox: the one through whom all things were made clothed himself in human flesh — not because he needed to be dressed by human hands, but to dwell among us and redeem the human artisan who had turned to idol-making.</p>",
    "15": "<p>A direct anticipation: &ldquo;They are worthless, a product of delusion; when they are called to account, they will be destroyed.&rdquo; The Hebrew <em>bᵉʿēṯ pᵉquddāṯām yōḇēdû</em> — &ldquo;at the time of their visitation/reckoning they will perish&rdquo; — uses the same word <em>pᵉquddāh</em> (visitation) that the NT uses for the coming of the Messiah and the judgment he brings. Christ&rsquo;s first coming is the &ldquo;visitation&rdquo; of God to his people (<a class=\"ref\" data-ref=\"Luke 1:68\">Luke 1:68</a>; <a class=\"ref\" data-ref=\"Luke 19:44\">Luke 19:44</a>); his second coming is the final reckoning at which all that is false and worthless — every idol of the heart — will be destroyed. The idols that fail their worshipers at the time of visitation are the shadows of every substitute for Christ that will not survive the final judgment.</p>",
    "17": "<p>A theme: the summons to gather belongings in preparation for exile — &ldquo;gather your belongings from the ground, O inhabitant of the besieged city.&rdquo; Christ echoes this summons in the Olivet Discourse, warning of the coming destruction of Jerusalem: &ldquo;let those who are in Judea flee to the mountains; let those who are inside the city get out&rdquo; (<a class=\"ref\" data-ref=\"Luke 21:21\">Luke 21:21</a>). Jesus reads the coming Roman siege through the lens of Jeremiah&rsquo;s Babylonian siege, applying the same pattern of divine judgment to the generation that rejected the Messiah. The exile-warning of 587 BCE and the Jerusalem-warning of 70 CE are both expressions of the same covenantal dynamic Jeremiah announces here.</p>",
    "18": "<p>A theme: the divine act of hurling inhabitants from the land — &ldquo;I am going to hurl the inhabitants of the land out at this very time.&rdquo; The verb <em>qālaʿ</em> (to hurl, sling) is the same root used for David&rsquo;s sling in 1 Sam 17:49-50. The divine slinging of Judah into exile is an act of covenant judgment. Christ absorbs the covenant wrath this judgment represents: he becomes &ldquo;a curse for us&rdquo; (<a class=\"ref\" data-ref=\"Gal 3:13\">Gal 3:13</a>), taking the exile&rsquo;s penalty so that those in him are not hurled away but drawn near. Those in Christ are not subject to being &ldquo;slung out&rdquo; — they are held by the one who himself bore the sling.</p>",
    "19": "<p>A theme: the lament &ldquo;Woe to me for my wound! My injury is severe.&rdquo; This is Jeremiah speaking as the embodiment of the wounded city and people. The confessional poems of Jeremiah (the &ldquo;laments&rdquo; or &ldquo;confessions&rdquo;) are regularly read as anticipating Christ&rsquo;s Passion in the NT — the righteous sufferer who bears the wound of corporate sin. The phrase &ldquo;I must bear it&rdquo; (<em>wᵉʾanî ʾāmartî ʾaḵ zeh ḥŏlî wᵉʾeśśāʾennû</em>) echoes Isa 53:4: &ldquo;he has borne our griefs and carried our sorrows.&rdquo; Christ is the one who says the same — taking the wound that belongs to others and bearing it as his own burden.</p>",
    "20": "<p>A theme: the tent ruined, ropes snapped, children gone. The image of the destroyed tent anticipates the destroyed temple — and beyond that, the body of Christ, the true temple: &ldquo;destroy this temple, and in three days I will raise it up&rdquo; (<a class=\"ref\" data-ref=\"John 2:19\">John 2:19</a>). The scattered children whom the tent-dweller mourns become the scattered flock Christ comes to gather: &ldquo;how often I would have gathered your children together as a hen gathers her brood under her wings, and you were not willing!&rdquo; (<a class=\"ref\" data-ref=\"Matt 23:37\">Matt 23:37</a>). The ruin of the tent is real, but Christ&rsquo;s resurrection is the re-pitching of the eternal dwelling among his people (<a class=\"ref\" data-ref=\"Rev 21:3\">Rev 21:3</a>).</p>",
    "22": "<p>A direct anticipation: &ldquo;Listen! A report is coming — a great commotion from the north — to turn the cities of Judah into a desolate waste, a lair of jackals.&rdquo; Christ echoes this desolation in his apocalyptic discourse, citing the Danielic &ldquo;abomination of desolation&rdquo; (Dan 9:27; Matt 24:15) that will render Jerusalem desolate. Jesus weeps over Jerusalem specifically because it did not recognize the time of its visitation (<a class=\"ref\" data-ref=\"Luke 19:41-44\">Luke 19:41-44</a>) — the commotion that Jeremiah hears coming from the north (Babylon) is the distant rumble of the same pattern that will come again in 70 CE. Both desolations find their meaning in the refusal to receive the one whom YHWH sent.</p>"
  },
  "11": {
    "2": "<p>A theme: &ldquo;Hear the terms of this covenant.&rdquo; The Sinai covenant is announced and its terms proclaimed. Christ comes as the covenant mediator who does not merely announce terms but fulfills them in his own person: &ldquo;Do not think that I have come to abolish the Law or the Prophets; I have not come to abolish them but to fulfill them&rdquo; (<a class=\"ref\" data-ref=\"Matt 5:17\">Matt 5:17</a>). The covenant of Sinai, whose terms Jeremiah is commissioned to proclaim, is the shadow of the new covenant that Christ inaugurates in his blood (<a class=\"ref\" data-ref=\"Luke 22:20\">Luke 22:20</a>; <a class=\"ref\" data-ref=\"Heb 9:15\">Heb 9:15</a>). The command to &ldquo;hear&rdquo; (<em>šimʿû</em>) the covenant terms is fulfilled in the Shema and finds its NT form in the command to hear the Son (<a class=\"ref\" data-ref=\"Matt 17:5\">Matt 17:5</a>).</p>",
    "3": "<p>A theme: &ldquo;Cursed is anyone who does not obey the terms of this covenant.&rdquo; The covenant curse is the penalty for disobedience. Christ becomes the bearer of this curse: &ldquo;Christ redeemed us from the curse of the law by becoming a curse for us — for it is written, &lsquo;Cursed is everyone who is hanged on a tree&rsquo;&rdquo; (<a class=\"ref\" data-ref=\"Gal 3:13\">Gal 3:13</a>). The curse of Jeremiah 11:3 is not a threat hanging over the obedient but the covenant penalty that the disobedient people have accumulated — and which Christ absorbs at the cross. The &ldquo;cursed is anyone who&rdquo; formula from Deut 27 runs through Jeremiah as a live threat and through Galatians as an absorbed judgment.</p>",
    "6": "<p>A theme: &ldquo;Proclaim all these words in the towns of Judah and in the streets of Jerusalem: Hear and obey.&rdquo; The prophetic commission to preach the covenant words throughout the land anticipates the apostolic commission: &ldquo;Go therefore and make disciples of all nations... teaching them to observe all that I have commanded you&rdquo; (<a class=\"ref\" data-ref=\"Matt 28:19-20\">Matt 28:19-20</a>). Jeremiah preaches the old covenant words in the towns; the apostles preach the new covenant word — Christ himself — to the nations. Both are &ldquo;herald&rdquo; missions, and both involve the suffering of rejection by those who refuse to hear.</p>",
    "7": "<p>A revelation of God: &ldquo;For I repeatedly warned your ancestors when I brought them out of Egypt, warning them urgently right up to this day.&rdquo; The divine persistence in warning — <em>hāšēm wᵉhāʿēḏ bᵉʾaḇôṯêhem</em>, &ldquo;I persistently warned your ancestors&rdquo; — is the OT form of the Father&rsquo;s patient sending: &ldquo;He sent them another servant, and that one they beat; he sent still another, and that one they killed&rdquo; (<a class=\"ref\" data-ref=\"Mark 12:5\">Mark 12:5</a>). Christ himself is the last and greatest envoy in this long sequence of warnings — the Son sent after the servants, whose rejection is qualitatively different because of who he is (<a class=\"ref\" data-ref=\"Heb 1:1-2\">Heb 1:1-2</a>).</p>",
    "9": "<p>A direct anticipation: &ldquo;There is a conspiracy among the people of Judah and the inhabitants of Jerusalem.&rdquo; The conspiracy against Jeremiah in this chapter (v.19-21) prefigures the conspiracy against Jesus. The word <em>qešer</em> (conspiracy/plot) is the same word used for the assembly of those who plotted to eliminate Jeremiah (vv.9, 19). In the NT, the conspiracy against Jesus is described in identical terms: &ldquo;the chief priests and the elders of the people plotted together to arrest Jesus secretly and kill him&rdquo; (<a class=\"ref\" data-ref=\"Matt 26:3-4\">Matt 26:3-4</a>). Jeremiah&rsquo;s experience of conspiracy is a type of Christ&rsquo;s Passion — the prophet whose words provoke a plot against his life.</p>",
    "10": "<p>A theme: &ldquo;They have returned to the sins of their ancestors who refused to listen to my words.&rdquo; The pattern of apostasy — receiving the covenant, then returning to the same rebellion — is the diagnostic of human incapacity for covenant keeping. This is why the new covenant in Jer 31:31-34 must write the law on the heart rather than on stone. Christ is the mediator of this new covenant: &ldquo;I will put my law within them, and I will write it on their hearts&rdquo; (Jer 31:33) — made possible through the Holy Spirit who is poured out from Christ&rsquo;s glorified body (<a class=\"ref\" data-ref=\"John 7:39\">John 7:39</a>; <a class=\"ref\" data-ref=\"Acts 2:33\">Acts 2:33</a>).</p>",
    "12": "<p>A theme: the futility of crying to the gods they have served — &ldquo;they will cry out to them, but they will certainly not save them.&rdquo; The idols that cannot save contrast with Christ who is able to save to the uttermost: &ldquo;he is able to save completely those who come to God through him, because he always lives to make intercession for them&rdquo; (<a class=\"ref\" data-ref=\"Heb 7:25\">Heb 7:25</a>). The idol that cannot save when cried out to is the negative testimony to the necessity of the one Mediator. Jeremiah&rsquo;s repeated insistence on idol-impotence (chs. 2, 10, 11) is the prophetic preparation for the NT&rsquo;s proclamation of the one name given among men by which we must be saved (<a class=\"ref\" data-ref=\"Acts 4:12\">Acts 4:12</a>).</p>",
    "13": "<p>A shadow: &ldquo;as many gods as you have cities, O Judah; as many altars to Baal as streets in Jerusalem.&rdquo; The multiplication of worship objects — localized, plural, competing — is the inverse of the one God in one temple in one city. Christ consolidates and fulfills this singularity: there is one God and one mediator between God and humanity (<a class=\"ref\" data-ref=\"1 Tim 2:5\">1 Tim 2:5</a>). The replacement of Jerusalem&rsquo;s many Baal altars with the one altar of the cross shows how the divine judgment of Jeremiah 11 is not merely destructive but preparatory — clearing the ground for the one offering that actually avails.</p>",
    "16": "<p>A shadow: &ldquo;the LORD once called you a flourishing olive tree, beautiful with fine fruit; but with the roar of a great storm he will set it on fire, and its branches will be broken.&rdquo; Paul uses precisely this olive-tree image in Romans 11 — Israel as the cultivated olive tree, with some branches broken off, and Gentiles as a wild branch grafted in. The burning branches of Jeremiah 11 become the broken-off branches of Rom 11:17. Christ is the root that supports the tree: &ldquo;do not boast over those branches... it is not you who support the root, but the root that supports you&rdquo; (<a class=\"ref\" data-ref=\"Rom 11:18\">Rom 11:18</a>). The olive-tree judgment of Jeremiah opens into the olive-tree mercy of Romans.</p>",
    "17": "<p>A theme: &ldquo;The LORD of hosts, who planted you, has pronounced disaster on you because of the evil that the house of Israel and the house of Judah have done.&rdquo; The parable logic — the planter who planted his vine/tree and finds it faithless — runs from Ps 80 through Isa 5 to Jer 11-12 to Jesus&rsquo; parable of the vineyard (Matt 21:33-41). In each case, the owner of the vineyard/tree expects fruit, finds faithlessness, and pronounces judgment. Christ embodies both the Owner who pronounces judgment and the new Planting — the true vine (<a class=\"ref\" data-ref=\"John 15:1\">John 15:1</a>) who produces the fruit that Israel failed to yield.</p>",
    "18": "<p>A revelation of God: &ldquo;The LORD revealed it to me, and I knew; you opened my eyes to their actions.&rdquo; The prophetic knowledge of hidden conspiracy comes by divine revelation, not human intelligence. This is a pattern that reaches its fullest expression in Christ, who &ldquo;knew all people&rdquo; and &ldquo;did not need anyone to tell him what was in a person, for he himself knew what was in a person&rdquo; (<a class=\"ref\" data-ref=\"John 2:24-25\">John 2:24-25</a>). Jesus knows the conspiracy against him before it unfolds (John 13:1-3; 18:4); his foreknowledge is not merely prophetic warning but omniscience — YHWH&rsquo;s own attribute of knowing all hearts (<a class=\"ref\" data-ref=\"Acts 1:24\">Acts 1:24</a>).</p>",
    "22": "<p>A theme: &ldquo;their young men will die by the sword; their sons and daughters will die by famine.&rdquo; The judgment on those who conspired against Jeremiah extends to their households. This principle of covenant consequence — that the covenant penalty reaches those who reject the prophets — finds its most serious expression in Christ&rsquo;s pronouncement over Jerusalem: &ldquo;The blood of all the prophets shed since the foundation of the world will be charged against this generation&rdquo; (<a class=\"ref\" data-ref=\"Luke 11:50\">Luke 11:50</a>). Those who reject the last and greatest Prophet bear the accumulated weight of all prophetic rejection. The judgment on Anathoth&rsquo;s conspirators is a small-scale enactment of this larger covenantal logic.</p>"
  },
  "12": {
    "2": "<p>A theme: &ldquo;You planted them, and they have taken root; they grow and produce fruit; yet you are near to their lips but far from their hearts.&rdquo; Jeremiah&rsquo;s lament over hypocrites — prospering outwardly but distant from God inwardly — is the setting for Christ&rsquo;s sharpest criticism of religious externalism: &ldquo;This people honors me with their lips, but their heart is far from me&rdquo; (<a class=\"ref\" data-ref=\"Matt 15:8\">Matt 15:8</a>, quoting Isa 29:13). The prophetic complaint of Jeremiah, picked up and deepened by Isaiah, is the direct precursor to Christ&rsquo;s denunciation of scribal hypocrisy. The one who plants truly — Christ as the true vine (<a class=\"ref\" data-ref=\"John 15:5\">John 15:5</a>) — produces genuine fruit precisely because the heart is united with the root, not merely the lips.</p>",
    "4": "<p>A theme: creation mourning because of the wickedness of its inhabitants — &ldquo;the grass of every field dries up.&rdquo; Paul draws on this same creation-suffering motif: &ldquo;the creation groans in the pains of childbirth right up to the present time... waiting eagerly for the revelation of the sons of God&rdquo; (<a class=\"ref\" data-ref=\"Rom 8:19-22\">Rom 8:19-22</a>). Creation mourns under the curse of human sin in Jeremiah; it awaits liberation from the bondage of decay in Paul. Christ is the one through whom creation&rsquo;s restoration comes — &ldquo;all things were made through him... in him all things hold together&rdquo; (<a class=\"ref\" data-ref=\"Col 1:16-17\">Col 1:16-17</a>) — and at his return the creation itself will be liberated into &ldquo;the glorious freedom of the children of God&rdquo; (<a class=\"ref\" data-ref=\"Rom 8:21\">Rom 8:21</a>).</p>",
    "6": "<p>A direct anticipation: &ldquo;Even your own brothers and your father&rsquo;s household have betrayed you; even they have raised a loud cry after you.&rdquo; Jeremiah&rsquo;s betrayal by his own family from Anathoth is a type of Christ&rsquo;s betrayal. Jesus experiences the same pattern: &ldquo;For even his brothers did not believe in him&rdquo; (<a class=\"ref\" data-ref=\"John 7:5\">John 7:5</a>); and more precisely, betrayal by one of his inner circle (<a class=\"ref\" data-ref=\"John 13:21\">John 13:21</a>). The prophet betrayed by his household is the template; the Messiah betrayed by his disciple is the fulfillment. Psalm 41:9 — &ldquo;even my close friend in whom I trusted, who ate my bread, has lifted his heel against me&rdquo; — bridges Jeremiah&rsquo;s experience and Christ&rsquo;s Passion.</p>",
    "8": "<p>A shadow: &ldquo;my heritage has become like a lion in the forest to me; she has raised her voice against me; therefore I hate her.&rdquo; This is YHWH&rsquo;s lament over Israel turned enemy — the heritage that was beloved (v.7: &ldquo;the one I deeply love&rdquo;) has become a threatening lion. In Christ, the one who was &ldquo;hated&rdquo; in judgment becomes the Lion of Judah who vindicates his people: &ldquo;weep no more; behold, the Lion of the tribe of Judah, the Root of David, has conquered&rdquo; (<a class=\"ref\" data-ref=\"Rev 5:5\">Rev 5:5</a>). The rebelling lion-heritage of Jeremiah 12 is redeemed by the conquering Lion-Christ of Revelation. The judgment-hatred of Jer 12:8 gives way to the love that sent the Son (<a class=\"ref\" data-ref=\"John 3:16\">John 3:16</a>).</p>",
    "9": "<p>A shadow: &ldquo;is my heritage like a speckled bird of prey to me, with birds of prey all around attacking her?&rdquo; The image of the speckled bird — distinctive, alien-looking, attacked by others — anticipates Christ as the rejected outsider. Jesus is attacked by the religious establishment, dismissed by his own people, &ldquo;despised and rejected by men&rdquo; (<a class=\"ref\" data-ref=\"Isa 53:3\">Isa 53:3</a>). The birds gathered to attack the speckled one find their NT counterpart in the coalition of priests, scribes, Pharisees, and Romans assembled against Christ. Yet the attacked one is the one whom YHWH calls &ldquo;my heritage&rdquo; — precious, owned, ultimately vindicated.</p>",
    "12": "<p>A theme: &ldquo;the sword of the LORD devours from one end of the land to the other.&rdquo; The sword of divine judgment runs through the prophetic corpus as the image of eschatological reckoning. Christ identifies himself with this sword-dimension of the divine: &ldquo;Do not think that I have come to bring peace to the earth. I have not come to bring peace, but a sword&rdquo; (<a class=\"ref\" data-ref=\"Matt 10:34\">Matt 10:34</a>). The sword Christ brings is not violence but the word that divides truth from falsehood, the faithful from the faithless. Hebrews 4:12 identifies this sword with the living and active word of God. The sword of Jeremiah 12:12 finds its NT fulfillment in the sword proceeding from the mouth of the glorified Christ (<a class=\"ref\" data-ref=\"Rev 19:15\">Rev 19:15</a>).</p>",
    "13": "<p>A theme: &ldquo;they planted wheat but harvested thorns; they wore themselves out for nothing.&rdquo; The futility of the faithless farmer is the obverse of Christ&rsquo;s parable of the sower, where good seed on good ground yields thirty-, sixty-, and a hundredfold (<a class=\"ref\" data-ref=\"Matt 13:8\">Matt 13:8</a>). The curse of thorns — &ldquo;cursed is the ground because of you; through painful toil you will eat food from it until you return to the ground... it will produce thorns and thistles for you&rdquo; (<a class=\"ref\" data-ref=\"Gen 3:17-18\">Gen 3:17-18</a>) — is what Jeremiah&rsquo;s farmers encounter. Christ wears the crown of thorns at his Passion, absorbing the curse-of-the-ground into his own body, so that those who sow in him may harvest life.</p>",
    "16": "<p>A fulfillment: &ldquo;And if they will diligently learn the ways of my people... then they will be built up among my people.&rdquo; This is the promise that Gentile nations who embrace covenant life will be incorporated into the covenant community. In Christ, this promise is fulfilled universally: &ldquo;Go therefore and make disciples of all nations&rdquo; (<a class=\"ref\" data-ref=\"Matt 28:19\">Matt 28:19</a>); &ldquo;In Christ Jesus you are all sons of God through faith&rdquo; (<a class=\"ref\" data-ref=\"Gal 3:26\">Gal 3:26</a>). The nations who &ldquo;learn the ways of my people&rdquo; in Jeremiah 12:16 become the nations &ldquo;built up among my people&rdquo; — a direct anticipation of the one new humanity formed in Christ from both Jew and Gentile (<a class=\"ref\" data-ref=\"Eph 2:14-15\">Eph 2:14-15</a>).</p>"
  },
  "13": {
    "2": "<p>A theme: the first stage of the linen sash sign-act — buying and wearing the sash according to YHWH&rsquo;s command. The linen sash (<em>ʾēzôr</em>) was the undergarment worn against the skin — an intimate article of clothing. The sign-act begins with perfect obedience: &ldquo;I bought the sash, as the LORD directed.&rdquo; Christ&rsquo;s obedience follows the same pattern: &ldquo;I have come down from heaven, not to do my own will but the will of him who sent me&rdquo; (<a class=\"ref\" data-ref=\"John 6:38\">John 6:38</a>). The prophet who acts at YHWH&rsquo;s command models the Servant who &ldquo;learned obedience through what he suffered&rdquo; (<a class=\"ref\" data-ref=\"Heb 5:8\">Heb 5:8</a>).</p>",
    "3": "<p>A theme: the second divine word comes to Jeremiah. The sign-act is multi-staged, requiring repeated divine instruction. God&rsquo;s pedagogy through enacted parables — commanding his prophet to live out the message — anticipates Christ&rsquo;s own use of enacted signs: the cleansing of the temple, the cursing of the fig tree, the foot-washing. The prophet&rsquo;s life becomes a living parable of judgment and mercy. In this sense, Jeremiah&rsquo;s prophetic career is a corporate &ldquo;type&rdquo; that Christ fulfills — not one enacted sign but an entire life that enacts the word of God.</p>",
    "4": "<p>A theme: hiding the sash at the Euphrates — YHWH&rsquo;s people hidden and ruined among the nations. The Euphrates is the emblem of exile — Babylon lies along it. The sash is to be buried there, symbolizing that Israel will be &ldquo;hidden&rdquo; in Babylon, spoiled by exile. Christ uses the hiding-and-finding motif in his parables: the treasure hidden in a field (<a class=\"ref\" data-ref=\"Matt 13:44\">Matt 13:44</a>), the lost coin (<a class=\"ref\" data-ref=\"Luke 15:8-10\">Luke 15:8-10</a>). The thing that is hidden is the thing of greatest value — found by the one who seeks diligently. The &ldquo;hidden&rdquo; people of Israel, spoiled in Babylon, are found and restored by the one who sought the lost sheep (<a class=\"ref\" data-ref=\"Luke 15:4-7\">Luke 15:4-7</a>).</p>",
    "5": "<p>A theme: &ldquo;so I went and hid it at the Euphrates, as the LORD commanded.&rdquo; Jeremiah&rsquo;s complete obedience to the enacted sign — including the physical act of travel to the Euphrates (whether literal or visionary) — underlines the cost of prophetic obedience. The prophets did not merely speak; they lived the message. Christ embodies this principle at the highest possible level: the incarnation is the ultimate enactment of the divine message, the Word made flesh dwelling among us (<a class=\"ref\" data-ref=\"John 1:14\">John 1:14</a>). YHWH does not merely describe exile; he sends his prophet to enact it. The Father does not merely describe redemption; he sends his Son to accomplish it.</p>",
    "6": "<p>A theme: the divine command to retrieve the ruined sash — &ldquo;go to the Euphrates; retrieve the sash I told you to hide there.&rdquo; The retrieval is the return from exile, the restoration after judgment. This two-stage movement — hiding (exile) and retrieval (restoration) — is the deep structure of the exile-return narrative. Christ himself enters the &ldquo;exile&rdquo; of death and is retrieved/raised: the resurrection is YHWH retrieving from death the one he had given over. The resurrection as the divine act of recovery mirrors the retrieve-the-sash command: &ldquo;you will not abandon my soul to Hades, or let your Holy One see corruption&rdquo; (<a class=\"ref\" data-ref=\"Acts 2:27\">Acts 2:27</a>).</p>",
    "7": "<p>A direct anticipation: &ldquo;I took the sash from the place where I had hidden it — and the sash was ruined; it was no longer useful for anything.&rdquo; The sash ruined by burial — unable to serve its purpose of clinging to YHWH — is a type of Israel in exile, marred and made useless through covenant unfaithfulness. In Christ, the ruined humanity is restored: &ldquo;if anyone is in Christ, he is a new creation; the old has passed away; behold, the new has come&rdquo; (<a class=\"ref\" data-ref=\"2 Cor 5:17\">2 Cor 5:17</a>). The sash that was useless is restored not by the sash reforming itself but by the divine act of re-creation in Christ — the ruined garment replaced by the robe of righteousness (<a class=\"ref\" data-ref=\"Isa 61:10\">Isa 61:10</a>; <a class=\"ref\" data-ref=\"Rev 3:5\">Rev 3:5</a>).</p>",
    "8": "<p>A theme: the word of YHWH comes again, interpreting the sign. The pattern of action followed by divine interpretation is the structure of prophetic sign-acts: the act is performed, then YHWH explains its meaning. Christ uses this same pattern — healing, then teaching; feeding, then explaining. John&rsquo;s Gospel in particular organizes around &ldquo;signs&rdquo; followed by interpretive discourses. The structure of enacted parable (sign-act) followed by divine word is one of the deep continuities between Jeremiah&rsquo;s prophetic method and Jesus&rsquo;s teaching method.</p>",
    "10": "<p>A theme: &ldquo;this wicked people who refuse to listen to my words, who follow the stubbornness of their heart... will be like that ruined sash, good for nothing.&rdquo; The interpretive conclusion of the sash sign-act applies the image to the spiritually hardened community. Christ identifies the same hardness: &ldquo;Though they have seen all these signs, they still would not believe&rdquo; (<a class=\"ref\" data-ref=\"John 12:37\">John 12:37</a>); and attributes it to the prophetically predicted hardening (Isa 6:10; John 12:40). The sash good for nothing is the person who refuses to cling to YHWH — and the only remedy is not reformation of the old sash but new creation in Christ, who makes all things new.</p>",
    "12": "<p>A shadow: &ldquo;every wineskin will be filled with wine.&rdquo; The people&rsquo;s response (&ldquo;we know that&rdquo;) treats this as a truism, but YHWH transforms it into a judgment metaphor: they will be filled with the wine of confusion and staggering. Christ uses the new wine / new wineskin image to describe his own coming: &ldquo;No one puts new wine into old wineskins; if he does, the new wine will burst the wineskins&rdquo; (<a class=\"ref\" data-ref=\"Luke 5:37\">Luke 5:37</a>). The wine of Jeremiah&rsquo;s judgment-filling (drunken staggering) contrasts with the new wine of the kingdom (joy and abundance at the wedding feast, <a class=\"ref\" data-ref=\"John 2:1-11\">John 2:1-11</a>; <a class=\"ref\" data-ref=\"Rev 19:9\">Rev 19:9</a>).</p>",
    "18": "<p>A direct anticipation: &ldquo;Say to the king and to the queen mother: Take a lower place and sit down; your positions of authority will come down off your heads.&rdquo; The humiliation of the Davidic king — Jehoiachin and his mother before Nebuchadnezzar — is part of the low point of the Davidic line that Christ reverses. Jesus is born into the humbled Davidic line: no throne, no palace, &ldquo;no place to lay his head&rdquo; (<a class=\"ref\" data-ref=\"Luke 9:58\">Luke 9:58</a>), born to a young woman in an occupied land. Yet this humiliation is the path to the exaltation: &ldquo;God highly exalted him and gave him the name that is above every name&rdquo; (<a class=\"ref\" data-ref=\"Phil 2:9\">Phil 2:9</a>). The crown taken off at Jer 13:18 is the crown that Christ restores in glory.</p>",
    "19": "<p>A theme: &ldquo;The towns of the Negev will be locked shut with no one to open them; all of Judah will be taken into exile.&rdquo; The total exile — no one left to open the locked towns — is the nadir of the Davidic covenant. Christ is the key of David: &ldquo;the holy one, the true one, who has the key of David, who opens and no one will shut, who shuts and no one opens&rdquo; (<a class=\"ref\" data-ref=\"Rev 3:7\">Rev 3:7</a>). The locked towns of Jeremiah&rsquo;s judgment are the shadow of every door closed by human sin; Christ is the one who opens what no one can shut — beginning with the sealed tomb from which he rises.</p>",
    "20": "<p>A theme: &ldquo;Where is the flock that was entrusted to you — the beautiful flock?&rdquo; The scattered flock is the people of God in the hour of their judgment. Christ the Good Shepherd answers this question definitively: &ldquo;I am the good shepherd; I know my own and my own know me&rdquo; (<a class=\"ref\" data-ref=\"John 10:14\">John 10:14</a>); &ldquo;I lay down my life for the sheep&rdquo; (<a class=\"ref\" data-ref=\"John 10:15\">John 10:15</a>). The beautiful flock scattered in Jeremiah&rsquo;s day is gathered by the Shepherd who leaves the ninety-nine to find the one lost sheep (<a class=\"ref\" data-ref=\"Luke 15:4-7\">Luke 15:4-7</a>), ultimately laying down his life to gather the flock that had been entrusted to him.</p>",
    "21": "<p>A theme: &ldquo;What will you say when he punishes you — when those you trained as your allies are placed over you as head?&rdquo; The reversal — trusted allies become masters — is the logic of covenant curse (Deut 28:44). Christ&rsquo;s kingdom operates by the same reversal-logic but in grace: the first will be last and the last first (<a class=\"ref\" data-ref=\"Matt 20:16\">Matt 20:16</a>); the one who humbles himself will be exalted (<a class=\"ref\" data-ref=\"Luke 14:11\">Luke 14:11</a>). Where Jeremiah&rsquo;s reversal is punitive (Judah&rsquo;s allies become her rulers), Christ&rsquo;s reversal is redemptive (the servant becomes the heir, <a class=\"ref\" data-ref=\"Gal 4:7\">Gal 4:7</a>).</p>",
    "22": "<p>A theme: &ldquo;it is because of the magnitude of your iniquity that your skirts were lifted up.&rdquo; The exposure of shame as covenant penalty appears throughout the prophets (Ezek 16; Hos 2). Christ provides the covering for human shame: &ldquo;I counsel you to buy from me white garments so that you may clothe yourself and the shame of your nakedness may not be seen&rdquo; (<a class=\"ref\" data-ref=\"Rev 3:18\">Rev 3:18</a>). The shame exposed in Jeremiah&rsquo;s judgment is the same shame that Christ covers at the cross — putting on himself the nakedness of crucifixion so that his people might be clothed in the righteousness he earned (<a class=\"ref\" data-ref=\"2 Cor 5:21\">2 Cor 5:21</a>; <a class=\"ref\" data-ref=\"Isa 61:10\">Isa 61:10</a>).</p>",
    "24": "<p>A theme: &ldquo;I will scatter them like chaff blown away by a desert wind.&rdquo; The winnowing image — separating wheat from chaff, the genuine from the worthless — runs from the prophets to John the Baptist to Christ: &ldquo;his winnowing fork is in his hand, and he will clear his threshing floor, gathering his wheat into the barn and burning up the chaff with unquenchable fire&rdquo; (<a class=\"ref\" data-ref=\"Matt 3:12\">Matt 3:12</a>). The scattering by desert wind in Jeremiah 13 is a preview of the eschatological winnowing at which Christ presides. The same Christ who is himself the grain of wheat that falls into the earth and dies (<a class=\"ref\" data-ref=\"John 12:24\">John 12:24</a>) will gather the final harvest and separate chaff from grain.</p>",
    "26": "<p>A theme: &ldquo;so I will pull your skirts up over your face and expose your shameful nakedness.&rdquo; The prophetic use of exposure imagery as covenant judgment is widespread (Ezek 16; Nah 3:5). It speaks of the stripping away of the pretensions of the covenant people who have acted as faithless. Christ on the cross enacts the ultimate exposure of shame — stripped of his garments while soldiers cast lots (<a class=\"ref\" data-ref=\"John 19:23-24\">John 19:23-24</a>; <a class=\"ref\" data-ref=\"Ps 22:18\">Ps 22:18</a>) — not because of his own shame but to bear the shame of others. His exposure becomes the covering: &ldquo;put on the Lord Jesus Christ&rdquo; (<a class=\"ref\" data-ref=\"Rom 13:14\">Rom 13:14</a>) is Paul&rsquo;s application of the garment-theology that runs from Genesis through Jeremiah to the cross.</p>"
  }
}

def main():
    existing = load_comm('mkt-christ', 'jeremiah')
    merge_comm(existing, JER_CHRIST)
    save_comm('mkt-christ', 'jeremiah', existing)
    import json as _j
    il = _j.loads((ROOT / 'data' / 'interlinear' / 'jeremiah.json').read_text())
    for ch in ['10', '11', '12', '13']:
        missing = set(il.get(ch, {}).keys()) - set(existing.get(ch, {}).keys())
        if missing:
            print(f'  ch {ch} STILL MISSING: {sorted(missing, key=int)}')
        else:
            print(f'  ch {ch}: complete ({len(existing.get(ch, {}))} verses)')

if __name__ == '__main__':
    main()
