"""
MKT Christ Commentary — Proverbs chapters 1–3
Run: python3 scripts/zc-christ-proverbs-1-3.py

Key decisions in this range:
- Lady Wisdom (ch1:20-33) treated as typological anticipation of Christ as Wisdom (1 Cor 1:24; John 7:37)
- "Tree of life" (3:18) connected to Eden and Rev 22:2 (type)
- Wisdom in creation (3:19-20) connected to Christ as Creator (Col 1:16; John 1:3)
- 3:11-12 and 3:34 are direct NT citations (Heb 12:5-6; Jas 4:6; 1 Pet 5:5) — classified as 'direct'
- 1:23 "pour out my spirit" anticipates Pentecost — classified as 'shadow' not 'direct' (OT speaker is Wisdom, not YHWH directly)
- ch2 adulteress material: covenant-fidelity theme, connected to Christ-church marriage (Eph 5:25-32)
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

PROVERBS = {
  "1": {
    "1": "<p>The superscription — the proverbs of Solomon son of David, king of Israel — places this wisdom within the Davidic covenant line. When Jesus declares himself 'greater than Solomon' (Matt 12:42), he claims to be the fulfillment of what Solomonic wisdom was aiming at: the perfect embodiment of divine wisdom in a Davidic king. The title functions as a typological pointer; Christ is what Solomon's wisdom was a dim prefiguration of.</p>",
    "2": "<p>The sevenfold purpose list — wisdom, instruction, understanding, righteousness, justice, equity, and prudence — summarizes the full scope of what wisdom offers. Paul identifies Christ as the one 'in whom are hidden all the treasures of wisdom and knowledge' (Col 2:3): every category named in Proverbs 1:2 finds its fullest expression in Christ, who is himself 'wisdom from God — our righteousness, sanctification, and redemption' (1 Cor 1:30).</p>",
    "3": "<p>The goal of wisdom is instruction in prudence, righteousness, justice, and equity — the Hebraic vocabulary of covenant character. These are not abstract virtues but the character of YHWH himself (Exod 34:6-7) and therefore the character of Christ, who is 'the righteousness of God' (Rom 3:21-22; 2 Cor 5:21). Proverbs announces the curriculum; Christ is the curriculum's content made flesh.</p>",
    "4": "<p>A revelation of God: wisdom is given to the simple and inexperienced — not only to the already-wise. This anticipates Christ's consistent ministry pattern: calling the uneducated (fishermen, tax collectors), declaring that the gospel is hidden from the wise and revealed to little children (Matt 11:25-26), and making the simple the recipients of divine teaching (Luke 10:21). Wisdom is democratic in its reach.</p>",
    "5": "<p>The wise person increases in learning; the person of understanding acquires guidance. This openness to ongoing instruction is the posture of discipleship — the student who continues to sit at wisdom's feet (Luke 10:39). The theme of wisdom's growth finds its christological anchor in the surprising statement that Jesus 'increased in wisdom' as he grew (Luke 2:52), modeling the very disposition Proverbs calls its readers toward.</p>",
    "6": "<p>Understanding proverbs, figures, and riddles of the wise is the task of wisdom education. Jesus taught primarily in parables — a form that requires discernment to understand and that intentionally conceals from the careless while disclosing to the attentive (Mark 4:11-12). The wisdom tradition's use of the riddle prepares Israel for a teacher who communicates wisdom indirectly, demanding active engagement rather than passive reception.</p>",
    "7": "<p>The foundational axiom: the fear of YHWH is the beginning of wisdom. This is simultaneously Proverbs' anchor verse and a key text for NT Christology. Paul declares that Christ is 'the wisdom of God' (1 Cor 1:24) and that 'all the treasures of wisdom and knowledge' are hidden in him (Col 2:3). What begins with fear of YHWH ends in Christ — the fear that Proverbs prescribes as wisdom's starting point leads ultimately to the one in whom wisdom is embodied.</p>",
    "8": "<p>The parental address — 'my son, hear your father's instruction and do not forsake your mother's teaching' — establishes wisdom's transmission through covenant family. This theme deepens christologically: God disciplines his children as a father disciplines his sons (Heb 12:7-9), and Christ himself was 'learned obedience through what he suffered' (Heb 5:8), modeling the receptivity to fatherly discipline that wisdom requires.</p>",
    "9": "<p>Wisdom's instruction is 'a graceful garland for your head and pendants for your neck' — the imagery of honor and adornment. The NT pictures the disciples of Christ as those being clothed: 'put on the new self' (Col 3:10), clothed with righteousness (Rev 19:8). Covenant formation through wisdom is the garment God adorns his people with; Christ is the source of that adornment (Gal 3:27: clothed with Christ).</p>",
    "10": "<p>The warning against enticement by sinners introduces the two-ways theme that runs through Proverbs and the NT. Jesus will later warn: 'Enter by the narrow gate' (Matt 7:13-14); 'the gate is wide and the way is easy that leads to destruction.' The sinners who entice in Proverbs 1:10 embody the broad way; wisdom's path — narrow, demanding, life-giving — anticipates Christ's invitation to the difficult way that leads to life.</p>",
    "11": "<p>The violence described — lying in wait, ambushing the innocent — foreshadows the pattern of the wicked lying in wait for the righteous that reaches its climax in the betrayal and crucifixion of Christ. Proverbs 1:11 is not directly prophetic, but it establishes a structural theme: the innocent are targeted by the violent, and wisdom warns against joining such schemes. The christological reversal is that the innocent victim becomes the source of life.</p>",
    "12": "<p>Swallowing alive like Sheol, whole like those who go down to the pit — the vocabulary of death as the goal of the wicked's violence. This imagery of being swallowed whole is inverted in Christ's resurrection: 'Death is swallowed up in victory' (1 Cor 15:54, citing Isa 25:8). What the wicked intended for the innocent — death — is overcome; the threat of the pit is reversed by the empty tomb.</p>",
    "13": "<p>The promise of plunder and spoil — the motive behind the enticement. This is the logic of covetousness: take by force what belongs to another. The NT diagnosis is that 'the love of money is a root of all kinds of evil' (1 Tim 6:10); the christological alternative is the self-emptying pattern of Christ (Phil 2:6-8), who 'though he was rich, yet for your sake he became poor, so that you by his poverty might become rich' (2 Cor 8:9).</p>",
    "14": "<p>Cast your lot among us; share one purse — the enticement of social inclusion through common crime. The community of wickedness contrasts with the community of wisdom. Christ's call is the counter-invitation: 'Follow me' (Mark 1:17); his community shares not plunder but the resources of covenant fellowship (Acts 2:44-45). The NT's koinonia (fellowship, shared life) is wisdom's community set against folly's gang.</p>",
    "15": "<p>Do not walk in the way with them; hold back your foot from their paths. The two-ways ethic here is exactly the choice Christ presents: 'I am the way' (John 14:6) — the way of wisdom incarnate — set against the broad way of destruction (Matt 7:13). Proverbs 1:15 establishes the moral geography of the two ways that the NT claims is embodied in Christ himself.</p>",
    "16": "<p>Their feet run to evil and hasten to shed blood — the characterization of the wicked as those driven by sinful appetite. Paul quotes the parallel in Ps 36:1-4 in Romans 3:15-17 as part of his catalog of universal human sinfulness: 'their feet are swift to shed blood.' The depravity that Proverbs diagnoses as the way of folly is the same bondage from which Christ came to deliver (Rom 3:24: justified freely by his grace through redemption in Christ).</p>",
    "17": "<p>In vain a net is spread in sight of any bird — the foolishness of a trap that announces itself. The self-defeating nature of sin is a persistent theme in wisdom literature: the wicked are ensnared by their own schemes (Ps 7:15-16). This theme of the trap reversed — the one who sets the snare falls into it — finds its ultimate expression in the cross: what was intended to destroy Christ became the instrument of salvation (Col 2:15: disarming the powers through the cross).</p>",
    "18": "<p>They lie in wait for their own blood and set an ambush for their own lives — the ultimate self-destruction of the way of folly. Betrayal and violence against the innocent return to destroy the perpetrators; this is the wisdom axiom that finds expression in the Judas narrative (Matt 27:5) and in the broader NT theme that those who seek their own life will lose it (Matt 16:25). The way of wickedness is ultimately suicidal.</p>",
    "19": "<p>Such are the ways of everyone who is greedy for unjust gain; it takes away the life of its possessors. The diagnostic force of this verse — greed as self-destruction — underlies Jesus's warning in Luke 12:15-21 (the rich fool who stored up treasure and lost his life). The revelation of God here is that God does not permit the accumulation of unjust wealth to satisfy; the life taken by greed foreshadows the life freely given by Christ, who did not grasp (Phil 2:6).</p>",
    "20": "<p>Wisdom cries aloud in the street; she raises her voice in the markets. This is the pivotal verse where Proverbs' personification of Wisdom becomes a type of Christ. Jesus stands in the temple courts crying out: 'If anyone is thirsty, let him come to me and drink' (John 7:37). The public, urgent, unrestricted call of Wisdom in Proverbs 1:20-21 is the pattern that Jesus explicitly fulfills — Wisdom made flesh, calling from the streets and temple courts of Jerusalem.</p>",
    "21": "<p>At the entrance of city gates she speaks her words — the highest seat of public life. Wisdom's proclamation at the gates (where legal proceedings occurred, where leaders gathered) corresponds to Christ's teaching in the temple, in synagogues, and in public assemblies. The claim is that divine wisdom is not hidden in esoteric circles but proclaimed openly; Jesus echoes this: 'I have spoken openly to the world' (John 18:20). Wisdom demands a public hearing.</p>",
    "22": "<p>How long will you love being simple, scoff, and hate knowledge? The interrogation directed at the simple, the scoffer, and the fool anticipates the rejected invitation. Jesus's lament parallels this exactly: 'How often would I have gathered your children together as a hen gathers her brood under her wings, and you were not willing!' (Matt 23:37; Luke 13:34). The Wisdom who called and was rejected is Christ who called Jerusalem and was rejected.</p>",
    "23": "<p>If you turn at my reproof, I will pour out my spirit to you — Wisdom's conditional promise of spiritual outpouring. The vocabulary connects to Joel 2:28-29 (I will pour out my Spirit on all flesh) and its fulfillment at Pentecost (Acts 2:17). The 'pouring out' of Wisdom's spirit in Proverbs 1:23 is a shadow of the Spirit poured out by the exalted Christ (Acts 2:33: having received from the Father the promise of the Holy Spirit, he has poured out this that you yourselves are seeing and hearing).</p>",
    "24": "<p>Because I have called and you refused — the judgment speech of rejected Wisdom. Jesus cites the same pattern in his parable of the great banquet (Luke 14:16-24): the invited guests refused to come, and their refusal results in exclusion. The Wisdom who called in Proverbs 1:24 and the Christ who called in the Gospels are the same divine summons, and the human response of refusal carries the same consequences.</p>",
    "25": "<p>You have ignored all my counsel and would have none of my reproof. Willful rejection of wisdom's guidance is the pattern of Israel's rejection of the prophets — which Jesus identifies himself with: 'Jerusalem, Jerusalem, the city that kills the prophets and stones those who are sent to it' (Matt 23:37). The christological logic is that Wisdom personified and Christ himself stand in continuity: rejecting wisdom is rejecting God's word, which is ultimately rejecting Christ (John 1:11: he came to his own, and his own people did not receive him).</p>",
    "26": "<p>I also will laugh at your calamity and mock when terror strikes you — the reversal in which rejected Wisdom becomes judge. This is not vindictiveness but eschatological justice: those who rejected the offer of grace face the consequences of their refusal. The NT theme of reversal — the rejected stone becomes the cornerstone (Ps 118:22; Matt 21:42) — reflects the same logic. Wisdom scorned becomes Wisdom enthroned; Christ crucified becomes Christ raised as Lord and Judge.</p>",
    "27": "<p>When terror strikes you like a storm and your calamity comes like a whirlwind — the eschatological judgment on those who refused wisdom's call. This is the 'sudden destruction' Paul warns about in 1 Thessalonians 5:3: 'while people are saying peace and security, sudden destruction will come upon them.' Proverbs 1:27 establishes the pattern of sudden inescapable judgment that the NT applies to the return of Christ as judge.</p>",
    "28": "<p>Then they will call upon me but I will not answer; they will seek me diligently but will not find me. The parable of the ten virgins (Matt 25:10-12) replays this scene exactly: 'Afterward the other virgins came also, saying, Lord, lord, open to us. But he answered, Truly I say to you, I do not know you.' The wisdom principle — that rejected grace has a terminus — is given its most vivid NT expression in the closed door of the judgment.</p>",
    "29": "<p>Because they hated knowledge and did not choose the fear of the LORD — the interior cause of the judgment is revealed as willful rejection, not ignorance. Jesus echoes this in John 3:19: 'this is the judgment — the light has come into the world, and people loved the darkness rather than the light.' The 'hating knowledge' of Proverbs 1:29 is the same culpable refusal that the NT diagnoses as the root of condemnation.</p>",
    "30": "<p>They did not accept my counsel; they despised all my reproof. The Psalter's warning — 'Today, if you hear his voice, do not harden your hearts' (Ps 95:7-8; cited in Heb 3:7-8, 15; 4:7) — is the NT's direct engagement with this Proverbs theme. Hardening against wisdom's call is the consistent pattern Hebrews warns its readers against: do not be like those in the desert who despised God's word and fell. Christ is the voice not to be resisted.</p>",
    "31": "<p>They will eat the fruit of their way and have their fill of their own devices. The principle of reaping what one sows (Gal 6:7-8) is Proverbs' agricultural metaphor made explicit: rejection of wisdom yields its own harvest. The NT makes the same point christologically: those who reject Christ, who is the bread of life (John 6:35), are left with the unsatisfying fruit of their own choosing. Christ's banquet invitation is the counter-offer to the bitter fruit of folly.</p>",
    "32": "<p>The waywardness of the simple kills them, and the complacency of fools destroys them — spiritual death through apathy and misdirection. The NT intensifies this: those who are 'lukewarm' are the most at risk (Rev 3:16); the parable of the talents warns that burying what has been given — passive non-use — is itself a form of faithlessness that results in loss (Matt 25:26-28). Complacency is not a neutral state but an active rejection of the gift.</p>",
    "33": "<p>But whoever listens to me will dwell secure and be at ease without dread of disaster — the counterpart to the judgment. This is the promise that climaxes Wisdom's speech: attentiveness to wisdom yields security. Jesus makes the same structural promise with himself as the referent: 'Everyone who hears these words of mine and does them will be like a wise man who built his house on the rock' (Matt 7:24). Proverbs 1:33 is the foundation; Christ is the rock on whom wisdom's house is built.</p>"
  },
  "2": {
    "1": "<p>If you receive my words and treasure up my commandments — wisdom as covenant gift to be received and stored. The image of treasuring recalls Jesus's parable of the treasure hidden in a field (Matt 13:44): the one who discovers wisdom sells everything to obtain it. More directly, the covenant instruction to 'bind these words on your heart' (Deut 6:6) finds its christological fulfillment in Christ's teaching that enters not just the ear but transforms the heart (Heb 8:10: I will put my laws into their minds and write them on their hearts).</p>",
    "2": "<p>Making your ear attentive to wisdom and inclining your heart to understanding — the disposition of receptive faith. Paul's principle that 'faith comes from hearing, and hearing through the word of Christ' (Rom 10:17) is the NT application of this posture: attentiveness to the word is the mechanism of wisdom's reception. Wisdom is not achieved by intellectual effort alone but received by attentive openness — precisely the posture Mary models when she 'sat at the Lord's feet and listened to his teaching' (Luke 10:39).</p>",
    "3": "<p>If you call out for insight and raise your voice for understanding — the seeking that precedes finding. Jesus's invitation in Matthew 7:7-8 ('ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you') directly echoes the Proverbs pattern of wisdom obtained through earnest seeking. The difference in the NT is that the one who is sought has now become visible: seeking wisdom leads to Christ, who is wisdom (Col 2:3).</p>",
    "4": "<p>If you seek it like silver and search for it as for hidden treasures — wisdom's worth exceeding material wealth. The parable of the pearl of great price (Matt 13:45-46) makes the same comparison explicit: the merchant sold everything he had to purchase the one pearl of surpassing value. Christ as wisdom is the hidden treasure and the pearl of great price; the seeking that Proverbs mandates is the seeking of the kingdom, which Christ calls his followers to pursue above all else (Matt 6:33).</p>",
    "5": "<p>Then you will understand the fear of the LORD and find the knowledge of God — the goal of wisdom-seeking is personal knowledge of YHWH. This is the new covenant's defining promise: 'They shall all know me, from the least of them to the greatest' (Jer 31:34; Heb 8:11). Jesus makes it explicit: 'This is eternal life, that they know you the only true God, and Jesus Christ whom you have sent' (John 17:3). The knowledge of God that Proverbs 2:5 holds out as wisdom's goal is given in Christ.</p>",
    "6": "<p>For the LORD gives wisdom; from his mouth come knowledge and understanding — wisdom as divine gift, not human achievement. James 1:5 cites exactly this principle: 'If any of you lacks wisdom, let him ask God, who gives generously to all without reproach, and it will be given him.' The christological dimension: Christ himself is the word from God's mouth (John 1:1-14), the fullness of wisdom from the source of all wisdom. Asking for wisdom means asking to know Christ more fully.</p>",
    "7": "<p>He stores up sound wisdom for the upright; he is a shield to those who walk in integrity — the storing and shielding function of divine wisdom. The image of God as shield (Ps 18:2; 28:7) is applied in the NT to faith: 'the shield of faith, with which you can extinguish all the flaming darts of the evil one' (Eph 6:16). The stored-up wisdom of God is disclosed in Christ, and the protection of the upright is secured through the one who bore every dart on the cross.</p>",
    "8": "<p>Guarding the paths of justice and watching over the way of his saints — divine providence over the covenant community. The NT presents Christ as the shepherd who guards his sheep: 'I am the good shepherd; I know my own and my own know me' (John 10:14). The guarding of the just in Proverbs 2:8 is a revelation of God's character — his protective oversight of those who walk with him — fulfilled in Christ's constant intercession (Heb 7:25: always living to make intercession) and his promise never to lose those given to him (John 10:28-29).</p>",
    "9": "<p>Then you will understand righteousness and justice and equity, every good path — moral comprehension that comes from wisdom's formation. Paul identifies Christ as the one who is 'our righteousness' (1 Cor 1:30): the moral formation that wisdom offers is not merely ethical instruction but participation in the character of Christ. 'Understanding every good path' is the language of Micah 6:8 (justice, mercy, humility) reexpressed in the NT as conformity to Christ's image (Rom 8:29).</p>",
    "10": "<p>When wisdom enters your heart and knowledge is pleasant to your soul — wisdom's internalization is the new covenant's distinctive promise. Jeremiah 31:33 (the new covenant): 'I will put my law within them, and I will write it on their hearts.' Ezekiel 36:26-27: 'I will give you a new heart and put a new spirit in you.' Proverbs 2:10 anticipates what the new covenant effects: wisdom is no longer external instruction but an internalized reality, made possible by the Spirit of Christ who dwells in believers (Rom 8:9-11).</p>",
    "11": "<p>Discretion will guard you; understanding will watch over you — the double protection of internalized wisdom. The Holy Spirit is described in similar terms: the Paraclete (advocate, helper, guard) who will 'teach you all things and bring to your remembrance all that I have said to you' (John 14:26). The Spirit indwells and guards; wisdom internalized in the NT is inseparable from the Spirit's presence, the deposit and guarantee of the inheritance (Eph 1:13-14).</p>",
    "12": "<p>Delivering you from the way of evil, from men of perverted speech — wisdom as deliverance from the power of evil. The NT extends this: 'the Lord knows how to rescue the godly from trials' (2 Pet 2:9). More fundamentally, Christ himself is the deliverer — 'he has delivered us from the domain of darkness and transferred us to the kingdom of his beloved Son' (Col 1:13). The deliverance from evil paths that wisdom offers is a shadow of the redemption Christ accomplishes.</p>",
    "13": "<p>Men who forsake the paths of uprightness to walk in the ways of darkness — apostasy and moral inversion. The NT warning against forsaking the assembly (Heb 10:25) and the repeated call not to return to the 'old self' (Eph 4:22) and not to drift away from the message heard (Heb 2:1) engage this theme. The one who delivers from darkness is Christ, who has come as 'the light of the world' (John 8:12), and those who forsake uprightness return from light to darkness.</p>",
    "14": "<p>Who rejoice in doing evil and delight in the perverseness of evil — the characterization of depravity as inversion of delight. Romans 1:32 uses this same diagnostic: the wicked 'not only do them but give approval to those who practice them.' The unredeemed rejoice in evil; the redeemed are called to a different delight — 'Rejoice in the Lord always' (Phil 4:4). The transformation of delight, from evil to the Lord, is what wisdom and ultimately what Christ effects in the life of the disciple.</p>",
    "15": "<p>Men whose paths are crooked, and who are devious in their ways — moral crookedness as the mark of the fool. The OT preparation involves making crooked paths straight (Isa 40:3-4), and this is applied to John the Baptist's ministry (Matt 3:3; Mark 1:3; Luke 3:4-5) as preparation for Christ's coming. Crooked paths are what Christ came to straighten; his ministry — healing, forgiving, calling — is the making-straight of what was bent.</p>",
    "16": "<p>Delivering you from the forbidden woman — the covenant-fidelity dimension of wisdom. The adulteress who lures away from the covenant is a metaphor that deepens in the NT: Paul uses marriage imagery to describe the exclusive covenant relationship between Christ and the church (2 Cor 11:2: 'I feel a divine jealousy for you, since I betrothed you to one husband, to present you as a pure virgin to Christ'). Departure from wisdom is infidelity to Christ; wisdom's deliverance is faithfulness to the covenant.</p>",
    "17": "<p>Who forsakes the companion of her youth and forgets the covenant of her God — the adulteress as covenant-breaker. The 'covenant of God' is the marriage covenant, but the OT consistently uses marriage as a figure for the YHWH-Israel covenant (Hos 2:2-13; Jer 2:2; Ezek 16). The NT applies the bride-bridegroom image to Christ and the church (Eph 5:25-32; Rev 19:7-9). Forgetting the covenant of God is, in the fullest sense, forgetting Christ — and wisdom delivers from that spiritual adultery.</p>",
    "18": "<p>Her house sinks down to death and her paths to the shades — the way of folly leads ultimately to Sheol. The NT's confrontation with death is christological: Christ 'tasted death for everyone' (Heb 2:9) and by his death destroyed 'the one who has the power of death' (Heb 2:14). The sinking house of folly is what Sheol represents; the resurrection is the inversion — from sinking into death to rising into life. Wisdom's path avoids the downward trajectory that Christ descended into and overcame.</p>",
    "19": "<p>None who go to her come back, nor do they regain the paths of life — the irreversibility of the way of folly without redemption. The prodigal son who 'came to himself' (Luke 15:17) and returned is the NT's answer to this verse's despair: there is a return possible, but only through repentance and the father's reception. Christ's parable directly addresses the possibility of return for those who have walked the way of folly — something wisdom alone cannot provide; it requires the Father's running out to meet the returning son.</p>",
    "20": "<p>Walk in the way of the good and keep to the paths of the righteous — the positive call of wisdom after the negative warnings. Jesus declares himself 'the way' (John 14:6): the way of the good is not merely a moral standard but a person. Walking in the way of wisdom becomes, in the NT, following Christ — the explicit language of discipleship ('follow me,' Mark 1:17) replaces wisdom's abstract path-walking with attachment to a person.</p>",
    "21": "<p>For the upright will inhabit the land, and those with integrity will remain in it — covenant inheritance tied to covenant fidelity. The Beatitude — 'Blessed are the meek, for they shall inherit the earth' (Matt 5:5) — is a direct engagement with this Proverbs theme (and Ps 37:11). Christ declares that the inheritance is given not to the violent but to the meek; wisdom's path of integrity leads to the inheritance that the NT presents as the new creation, the renewed earth.</p>",
    "22": "<p>But the wicked will be cut off from the land, and the treacherous will be rooted out of it — the eschatological removal of evil. The parable of the wheat and tares (Matt 13:36-43) presents the same two destinies at the harvest: the tares are bound and burned; the wheat enters the kingdom. The 'cutting off from the land' in Proverbs 2:22 is the OT form of what the NT presents as the final judgment — the separation of the wicked from the inheritance of the righteous in Christ.</p>"
  },
  "3": {
    "1": "<p>My son, do not forget my teaching and let your heart keep my commandments — covenant memory and the heart. The new covenant promise directly addresses this: 'I will put my law within them, and I will write it on their hearts' (Jer 31:33). What Proverbs calls the student to do by effort — keep the commandments in the heart — the new covenant effects by the Spirit. Christ is the mediator of the new covenant (Heb 9:15) who makes the internal keeping possible by giving the Spirit who writes the law on the heart.</p>",
    "2": "<p>For length of days and years of life and peace they will add to you — the promise of abundant and peaceful life as the fruit of wisdom. Jesus declares: 'I came that they may have life and have it abundantly' (John 10:10). The length-of-days promise of Proverbs is a temporal shadow of the eternal life Christ offers; the 'peace' anticipated here becomes the 'peace that surpasses all understanding' (Phil 4:7) given by the risen Christ who says 'Peace be with you' (John 20:19-21).</p>",
    "3": "<p>Let not steadfast love and faithfulness forsake you; bind them around your neck; write them on the tablet of your heart — the covenant character pair <em>ḥesed</em> (steadfast love) and <em>ʾemet</em> (faithfulness). These are the two attributes YHWH declares at Sinai (Exod 34:6-7) and the character Christ embodies: 'full of grace and truth' (John 1:14 — <em>charis</em> and <em>alētheia</em> as the Greek equivalent of <em>ḥesed</em> and <em>ʾemet</em>). The tablet of the heart (Jer 31:33; 2 Cor 3:3) becomes the NT's metaphor for the Spirit's work in new covenant formation.</p>",
    "4": "<p>So you will find favor and good success in the sight of God and man — wisdom produces honor before both God and people. The narrative statement about Jesus — 'And Jesus increased in wisdom and in stature and in favor with God and man' (Luke 2:52) — is a direct echo of Proverbs 3:4 applied to Jesus. Luke presents Jesus as the embodiment of the ideal son who grows up in wisdom and covenant favor, modeling the path Proverbs prescribes.</p>",
    "5": "<p>Trust in the LORD with all your heart and do not lean on your own understanding — the total trust demanded by wisdom. This is the foundational faith posture that the NT fills out in Christ: 'Believe in the Lord Jesus, and you will be saved' (Acts 16:31); 'the righteous shall live by faith' (Hab 2:4; Rom 1:17; Gal 3:11; Heb 10:38). Proverbs 3:5 sets up the alternative to human self-sufficiency; Christ is the trustworthy one in whom that total trust finds its object.</p>",
    "6": "<p>In all your ways acknowledge him and he will make straight your paths — divine direction flowing from total acknowledgment of God. The NT's calling to 'pray without ceasing' (1 Thess 5:17) and to 'do everything in the name of the Lord Jesus' (Col 3:17) is the concrete form of 'acknowledging God in all your ways.' The straight paths that result are the paths of the kingdom: Christ who is 'the way' (John 14:6) is the one in whom all the crooked places are made straight (Isa 40:3-5; Luke 3:4-5).</p>",
    "7": "<p>Be not wise in your own eyes; fear the LORD and turn away from evil — the humility that wisdom requires. This verse stands against the self-deception that Paul diagnoses in Romans 12:16 ('never be wise in your own sight') and that Christ confronts in the Pharisees who were 'confident in their own righteousness' (Luke 18:9). The wisdom of God revealed in Christ deliberately confounds the wisdom of the self-sufficient: 'God chose what is foolish in the world to shame the wise' (1 Cor 1:27).</p>",
    "8": "<p>It will be healing to your flesh and refreshment to your bones — the physical dimension of covenant wholeness. The Hebrew concept of <em>shalom</em> encompasses bodily health as well as relational peace. Christ's healing ministry is the concrete enactment of this wholeness: 'He healed all who were sick' (Matt 8:16; Isa 53:4: he bore our illnesses). The healing that wisdom's way promises in Proverbs 3:8 anticipates the wholeness that Christ's kingdom brings — inaugurated in his earthly ministry and consummated in the resurrection of the body.</p>",
    "9": "<p>Honor the LORD with your wealth and with the firstfruits of all your produce — the priority offering that acknowledges YHWH as the source of all good. Jesus reinforces this with 'Seek first the kingdom of God and his righteousness, and all these things will be added to you' (Matt 6:33). The firstfruit principle points forward to Christ himself: 'Christ has been raised from the dead, the firstfruits of those who have fallen asleep' (1 Cor 15:20) — the firstfruit offering becomes a type of the resurrection.</p>",
    "10": "<p>Then your barns will be filled with plenty and your vats will be bursting with new wine — covenant blessing in response to faithful stewardship. The abundant harvest and overflowing wine connect to the messianic feast imagery: 'the mountains shall drip sweet wine' (Amos 9:13-14; Joel 3:18). Jesus's first sign at Cana — transforming water into superabundant wine (John 2:1-11) — announces that the era of covenant blessing is arriving in him: wisdom's promise of plenty is being inaugurated by the one who is wisdom.</p>",
    "11": "<p>My son, do not despise the LORD's discipline or be weary of his reproof — this verse is directly quoted in Hebrews 12:5 as a word of God addressed to believers enduring hardship: 'My son, do not regard lightly the discipline of the Lord, nor be weary when reproved by him.' A direct citation: the word of wisdom spoken in Proverbs becomes the word of God applied to Christians suffering for their faith. Christ himself 'learned obedience through what he suffered' (Heb 5:8), modeling the non-despising of discipline that Proverbs calls for.</p>",
    "12": "<p>For the LORD reproves him whom he loves, as a father the son in whom he delights — the love behind discipline. This verse is also directly quoted in Hebrews 12:6: 'For the Lord disciplines the one he loves, and chastises every son whom he receives.' A direct citation: Proverbs 3:12 is the theological foundation for the NT's theology of suffering as sonship formation. The Father's love — expressed through disciplinary hardship — is the christological pattern: the Son who suffered did so as the ultimate expression of divine fatherly love shaping him for the work of salvation (Heb 2:10: it was fitting that he make the founder of salvation perfect through suffering).</p>",
    "13": "<p>Blessed is the one who finds wisdom, and the one who gets understanding — the beatitude of the wisdom-finder. Jesus's Beatitudes (Matt 5:3-12) echo this form: 'Blessed are those who...' The blessedness that Proverbs 3:13 declares for the wisdom-finder is fulfilled in the Christ-follower: 'Blessed are you, Simon Bar-Jonah! For flesh and blood has not revealed this to you, but my Father who is in heaven' (Matt 16:17) — to receive wisdom about who Christ is brings blessedness exceeding all other goods.</p>",
    "14": "<p>For the gain from her is better than gain from silver and her profit better than gold — wisdom surpasses material wealth. Paul applies this comparative logic to Christ: 'I count everything as loss because of the surpassing worth of knowing Christ Jesus my Lord' (Phil 3:8). The wisdom tradition's relativization of all material goods in favor of wisdom becomes, in the NT, the relativization of all goods in favor of union with Christ. The 'profit better than gold' is the unsearchable riches of Christ (Eph 3:8).</p>",
    "15": "<p>She is more precious than rubies and nothing you desire can compare with her — wisdom's incomparable worth. The parable of the merchant seeking fine pearls (Matt 13:45-46) and the woman who searched for her lost coin (Luke 15:8-10) both image the pursuit of what is incomparably valuable. The pearl of great price and the recovered coin represent Christ's kingdom — and Christ himself — as the one thing of surpassing worth that surpasses everything desired. Wisdom's incomparable value finds its christological expression in the kingdom.</p>",
    "16": "<p>Long life is in her right hand; in her left hand are riches and honor — wisdom holds the gifts of the good life. The NT transposes these: the right hand is Christ's position of honor (Heb 1:3; Ps 110:1 — 'sit at my right hand'), and the riches in his hand are 'the riches of his grace' (Eph 1:7) and the 'riches of his glory' (Eph 3:16). The life and honor that wisdom holds in her hands are held in Christ's hands, and they are given to those united to him.</p>",
    "17": "<p>Her ways are ways of pleasantness and all her paths are peace — the character of wisdom's way. Jesus declares himself 'the way' (John 14:6) and gives 'peace that surpasses all understanding' (Phil 4:7) and 'not as the world gives' (John 14:27). The pleasantness and peace of wisdom's paths are not automatic but flow from union with the one in whom wisdom is embodied. The NT intensification: peace is not merely the absence of conflict but the gift of reconciliation — 'justified by faith, we have peace with God through our Lord Jesus Christ' (Rom 5:1).</p>",
    "18": "<p>She is a tree of life to those who lay hold of her; those who hold her fast are called blessed — the third mention of the tree of life in Proverbs (3:18; 11:30; 13:12; 15:4). The tree of life appears first in Eden (Gen 2:9; 3:22) — life's source before the fall — and last in the new Jerusalem (Rev 22:2: the tree of life yielding twelve kinds of fruit, for the healing of the nations). Wisdom as tree of life is a type: the original gift, lost through disobedience, restored through Christ. Revelation 2:7 promises the tree of life to the one who conquers — the gift of Eden restored in Christ.</p>",
    "19": "<p>The LORD by wisdom founded the earth; by understanding he established the heavens — creation through wisdom. This is one of the OT's key texts for the identification of wisdom with the pre-existent Christ. The NT applies this directly: 'All things were made through him' (John 1:3); 'by him all things were created, in heaven and on earth' (Col 1:16); 'through whom also he created the world' (Heb 1:2). Proverbs 3:19 presents wisdom as God's instrument in creation; the NT identifies that instrument as Christ, the eternal Logos, the divine Son who is wisdom incarnate.</p>",
    "20": "<p>By his knowledge the deeps broke open and the clouds drop down the dew — creation's ordering through divine wisdom-knowledge. The same theme continues: the cosmic knowledge that structures creation is the knowledge of the Son. Colossians 1:17 adds: 'in him all things hold together' — Christ is not only the agent of creation but its sustaining principle. The rain and dew that wisdom's knowledge releases in creation are part of the providential ordering that Christ maintains moment by moment.</p>",
    "21": "<p>My son, do not lose sight of these — keep sound wisdom and discretion — the call to hold fast to wisdom. The NT's parallel: 'Hold fast to the word of life' (Phil 2:16); 'hold fast what you have, so that no one may seize your crown' (Rev 3:11). Holding to wisdom means holding to Christ, and the warning not to lose sight of wisdom is the epistle's warning not to drift from the confession of faith (Heb 2:1: we must pay much closer attention to what we have heard, lest we drift away from it).</p>",
    "22": "<p>And they will be life for your soul and adornment for your neck — wisdom as the soul's life and beauty. Christ is 'the life' (John 14:6; 1 John 5:12: whoever has the Son has life). The NT's adornment language moves from jewelry to character: 'clothe yourselves with compassion, kindness, humility' (Col 3:12); 'let your adorning be the hidden person of the heart with the imperishable beauty of a gentle and quiet spirit' (1 Pet 3:4). Christ adorns the soul with his own character through union with him.</p>",
    "23": "<p>Then you will walk on your way securely and your foot will not stumble — the security of the wisdom-path. Jesus's parable ends with the wise man's house standing firm through storm (Matt 7:24-25). The path-security Proverbs promises is the NT's assurance of God's guarding: 'Now to him who is able to keep you from stumbling and to present you blameless before the presence of his glory with great joy' (Jude 24). Christ is the one who keeps from stumbling — the security Proverbs promises is secured by him.</p>",
    "24": "<p>When you lie down you will not be afraid; when you lie down your sleep will be sweet — the peaceful rest of the wisdom-walker. The deep peace of those who trust God is illustrated by Jesus sleeping in the storm (Mark 4:38) — not disturbed by what terrifies his disciples. The promise of sweet sleep anticipates 'the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus' (Phil 4:7). Trust in God through Christ produces the rest that wisdom promises.</p>",
    "25": "<p>Do not be afraid of sudden terror or of the ruin of the wicked when it comes — the wisdom-walker's freedom from existential fear. The NT: 'God gave us a spirit not of fear but of power and love and self-control' (2 Tim 1:7); 'perfect love casts out fear' (1 John 4:18). The freedom from sudden terror that wisdom offers is the fruit of trust in God's sovereignty — and Christ's resurrection is the ultimate argument against existential fear: he has overcome death, the most catastrophic of all sudden terrors (Heb 2:14-15).</p>",
    "26": "<p>For the LORD will be your confidence and will keep your foot from being caught — divine confidence and keeping. The application in Hebrews 13:6 ('The Lord is my helper; I will not fear; what can man do to me?', citing Ps 118:6) is the NT's use of this confidence theme. Christ himself is the one who keeps from being caught: 'I give them eternal life, and they will never perish, and no one will snatch them out of my hand' (John 10:28). The keeper who guards from traps is the Good Shepherd.</p>",
    "27": "<p>Do not withhold good from those to whom it is due when it is in your power to do it — the immediate enactment of neighbor-love. Jesus's summary of the law — love your neighbor as yourself (Matt 22:39) and the parable of the Good Samaritan (Luke 10:25-37) — make neighbor-love the test of wisdom's possession. The 'good' withheld or given is the measure of covenant character; James 2:15-17 makes this explicit: faith without works (without giving good when it is in your power) is dead.</p>",
    "28": "<p>Do not say to your neighbor, 'Go and come again, tomorrow I will give it' — when you have it with you — the sin of deferral. James 2:16 exactly mirrors this: if a brother lacks food and one says to them, 'Go in peace, be warmed and filled,' without giving them what is needed, what good is that? James applies Proverbs 3:28 directly to the Christian community: wisdom's ethics of immediacy become the test of genuine faith.</p>",
    "29": "<p>Do not plan evil against your neighbor who dwells trustingly beside you — the prohibition against using trust as a weapon. This covenant ethics of trustworthiness runs through the NT's teaching on community life: 'Let no one seek his own good, but the good of his neighbor' (1 Cor 10:24); 'love does no wrong to a neighbor' (Rom 13:10). Christ himself is the trustworthy neighbor who never plans harm — his hospitality extends to those who will betray him (John 13:26-27), maintaining covenant love even toward the enemy.</p>",
    "30": "<p>Do not contend with a man for no reason when he has done you no harm — the prohibition against gratuitous strife. The beatitude 'Blessed are the peacemakers, for they shall be called sons of God' (Matt 5:9) is the positive form of this wisdom principle. Christ models it in his response to accusers: 'He was oppressed and afflicted, yet he opened not his mouth' (Isa 53:7; 1 Pet 2:23). The avoidance of groundless contention is wisdom; Christ's silence before his accusers is its ultimate expression.</p>",
    "31": "<p>Do not envy a man of violence and do not choose any of his ways — the prohibition against admiring power obtained through force. The NT confrontation with worldly power is christological: 'the rulers of this age... would not have crucified the Lord of glory' if they had understood wisdom (1 Cor 2:6-8). Christ's kingdom is 'not of this world' (John 18:36) and does not operate through violence; Paul declares 'the weapons of our warfare are not of the flesh' (2 Cor 10:4). Envy of violent power is choosing the way of the anti-kingdom.</p>",
    "32": "<p>For the devious person is an abomination to the LORD but the upright are in his confidence — God's intimate relationship with the upright contrasted with his abhorrence of the devious. Christ makes this intimacy central: 'No longer do I call you servants... but I have called you friends' (John 15:15). The 'confidence' (Hebrew <em>sod</em>, intimate counsel) that God shares with the upright is the intimacy of friendship — disclosed fully in Christ, who reveals the Father's heart to his disciples (John 1:18: the only Son, who is at the Father's side, has made him known).</p>",
    "33": "<p>The LORD's curse is on the house of the wicked but he blesses the dwelling of the righteous — the reversal of covenant curses and blessings. The NT's great reversal: Christ redeemed us from the curse of the law by becoming a curse for us — for it is written, cursed is everyone who is hanged on a tree (Gal 3:13; Deut 21:23). The curse on the house of the wicked is absorbed by Christ on the cross; the blessing of the righteous dwelling flows from his bearing of the curse. Proverbs 3:33 is the covenant structure; the cross is its resolution.</p>",
    "34": "<p>Toward the scornful he is scornful but to the humble he gives grace — this verse is directly quoted twice in the NT. James 4:6 and 1 Peter 5:5 both cite the LXX form: 'God opposes the proud but gives grace to the humble.' A direct application: Peter uses it to call the church to humble submission to God and resistance to the devil (1 Pet 5:5-9); James uses it to call the double-minded to single-hearted devotion (Jas 4:6-10). The principle of Proverbs 3:34 becomes the theological foundation for the NT's call to humility — the way of Christ, who 'humbled himself' (Phil 2:8) and to whom God gave the name above every name (Phil 2:9).</p>",
    "35": "<p>The wise will inherit honor but fools get disgrace — the eschatological reversal in which wisdom vindicates its adherents. The Beatitudes' promise of inheritance (Matt 5:5: the meek inherit the earth) and honor (Matt 5:12: your reward is great in heaven) are the NT's development of this theme. The final reversal — honor for the wise, disgrace for the fool — is the eschatological verdict of the last judgment, where 'those who honored me I will honor, and those who despise me shall be lightly esteemed' (1 Sam 2:30). Christ's vindication at the resurrection is the guarantee that wisdom's way leads to the honor Proverbs promises.</p>"
  }
}

def main():
    existing = load_comm('mkt-christ', 'proverbs')
    merge_comm(existing, PROVERBS)
    save_comm('mkt-christ', 'proverbs', existing)

    import json as _json
    il = _json.load(open(str(ROOT / 'data' / 'interlinear' / 'proverbs.json')))
    out = existing
    for ch in [1, 2, 3]:
        ck = str(ch)
        missing = set(il.get(ck, {}).keys()) - set(out.get(ck, {}).keys())
        print(f'  ch{ch}: {"complete" if not missing else "MISSING " + str(sorted(missing, key=int))}')

if __name__ == '__main__':
    main()
