import json, pathlib
ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

NEW = {
"25": {
"1": "<p>LORD, you are my God — I will exalt you; I will praise your name, for you have done wonderful things: plans formed long ago, faithful and true. The doxology opening Isaiah 25 praises YHWH for enacting plans formed long ago. Paul identifies these long-ago plans as fulfilled in Christ: <em>in accordance with the eternal purpose that he accomplished in Christ Jesus our Lord</em> (Eph 3:11). The faithful-and-true character of YHWH's plans becomes the title of the returning Christ in Revelation 19:11: <em>Faithful and True.</em> The praise for what YHWH has done wonderful — <em>pele</em>, the same root as the Messianic child's name Wonderful Counselor (9:6) — resonates across the book's Christological arc.</p>",
"2": "<p>For you have turned a city into a heap of rubble — the stronghold of foreigners will never be rebuilt. The judgment on the representative proud city (Babylon, Nineveh, or the composite ANE empire) is the necessary clearing for the eschatological vision that follows. Christ's judgment on cities that reject the gospel (Matt 11:23-24: <em>Capernaum... you will go down to Hades</em>) enacts this same pattern. Revelation 18:21-23's destruction of Babylon — thrown down like a great millstone, never to be found again — is the NT fulfillment: the stronghold of opposition to YHWH's covenant permanently demolished.</p>",
"3": "<p>Therefore strong peoples will glorify you — cities of ruthless nations will stand in awe of you. The conversion of the ruthless through YHWH's judgments is the eschatological gathering of the nations. Revelation 15:3-4 presents the redeemed multitude singing the Song of Moses and the Lamb: <em>Great and marvelous are your deeds... All nations will come and worship before you.</em> The strong peoples who glorify YHWH are those who, having seen his judgment on the proud city, recognize that the one they resisted is also the one who rescues. Their awe becomes worship of the Lamb who was slain.</p>",
"4": "<p>For you have been a refuge for the poor, a shelter from the storm, a shade from the scorching heat — the blast of the ruthless is like a driving rainstorm against a wall. The covenant theology of YHWH as the poor community's refuge finds its NT fulfillment in Matthew 11:28-30: <em>Come to me, all you who are weary and burdened, and I will give you rest.</em> Jesus is the shade from scorching heat and the shelter from the storm — the one to whom the blast of the ruthless has been directed in the cross, so that those sheltered by his atoning work no longer bear it. The poor for whom he is a refuge are the <em>poor in spirit</em> of the Beatitudes (Matt 5:3).</p>",
"5": "<p>You silence the clamor of the foreigners as drought is broken by cloud-shadow — you subdue the triumph of the ruthless. The relief of cloud-shadow in scorching heat is the image of divine intervention as physical refreshment. Revelation 7:16-17 applies this directly to the redeemed multitude: <em>the sun will not beat down on them, nor any scorching heat, for the Lamb at the center of the throne will be their shepherd and will lead them to springs of living water.</em> The cloud-shadow that silences the foreigners' clamor is the Spirit-cloud that rested on Christ at his baptism and received him at the ascension — the divine presence that is also the eschatological shade.</p>",
"6": "<p>On this mountain the LORD of hosts will prepare a feast for all peoples — a feast of rich food and well-aged wines, of choice meat full of marrow, of the finest strained vintages. The Messianic banquet — the fullest OT statement of the eschatological feast. Jesus draws on this vision across multiple teachings: the Parable of the Great Banquet where all are invited (Luke 14:15-24), the Wedding Banquet where invitations go to those on the roads (Matt 22:1-14), and the promise that <em>many will come from east and west and recline at table with Abraham, Isaac, and Jacob in the kingdom of heaven</em> (Matt 8:11). At the Last Supper, Jesus explicitly anticipates this feast: <em>I will not drink again of the fruit of the vine until that day when I drink it new in the kingdom of God</em> (Mark 14:25). Revelation 19:9 declares: <em>Blessed are those who are invited to the wedding supper of the Lamb.</em></p>",
"7": "<p>On this mountain he will destroy the shroud cast over all peoples, the sheet spread over all nations. The death-shroud covering all humanity is the universal mortality that sin introduced (Gen 2:17; Rom 5:12). Christ's destruction of the death-shroud is enacted in the resurrection: at Lazarus's tomb, Jesus commands <em>Take off the grave clothes and let him go</em> (John 11:44), performing in miniature what the resurrection performs universally. The grave clothes left behind in the empty tomb (John 20:6-7) are the shroud removed from the one who first breaks through it. Paul: <em>Since death came through a man, the resurrection of the dead comes also through a man</em> (1 Cor 15:21).</p>",
"8": "<p>He will swallow up death forever. The Lord GOD will wipe away every tear from every face; the disgrace of his people he will remove from all the earth. The three eschatological reversals — death swallowed, tears wiped, disgrace removed — are all attributed to Christ in the NT. Paul quotes this verse directly in 1 Corinthians 15:54: <em>when the perishable puts on the imperishable... then shall come to pass the saying: Death is swallowed up in victory. O death, where is your victory? O death, where is your sting?</em> (citing also Hos 13:14). Revelation 21:4 is the fullest realization: <em>He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain.</em> Isaiah 25:8 is the hinge on which all NT eschatology turns.</p>",
"9": "<p>In that day they will say: This is our God; we waited for him, and he has saved us. This is the LORD; we waited for him. Let us rejoice and be glad in his salvation. The recognition-exclamation at the consummation — <em>This is our God!</em> — is the moment of unveiled identity. John 1:14: <em>the Word became flesh and dwelt among us, and we have seen his glory.</em> At the resurrection, Thomas's recognition: <em>My Lord and my God!</em> (John 20:28) is the individual's version of this communal cry. Revelation 21:3: <em>the dwelling place of God is with man</em> — the <em>This is our God</em> moment that the whole of Scripture has been building toward. The salvation (<em>yeshu'ato</em>) for which they waited is the name Jesus: <em>you shall call his name Jesus, for he will save his people from their sins</em> (Matt 1:21).</p>",
"10": "<p>For the hand of the LORD will rest on this mountain, but Moab will be trampled in place as straw is trampled into a dung heap. Moab as the representative enemy stands in contrast to the covenant mountain under YHWH's protecting hand. The trampling of Moab under divine judgment while the feast occurs on the holy mountain is the eschatological pattern Paul describes in 1 Corinthians 15:25-27: Christ must reign <em>until he has put all his enemies under his feet</em> (citing Ps 110:1). Hebrews 10:13 sees Christ waiting at the Father's right hand <em>until his enemies are made a footstool for his feet</em> — the divine hand resting on Zion while the enemies are progressively trampled.</p>",
"11": "<p>He will spread his hands over Moab as a swimmer spreads his arms through water — and he will bring down their pride despite all their struggling. The image of YHWH's hands spread wide over the enemy to subdue their pride carries a quiet but striking resonance with the cross: the arms of the crucified one spread wide in the gesture of both total vulnerability and sovereign embrace. What appears as Rome's and Israel's victory over Jesus (his hands spread, nailed, helpless) is in fact the moment when YHWH spreads his hands over sin, death, and pride — bringing them down despite all their struggling against him. The swimmer's arms subdue the current; the crucified arms subdue the powers.</p>",
"12": "<p>The high fortifications of your walls he will pull down, lay low, and cast to the ground — to the very dust. The demolition of Moab's pride-fortifications to the dust closes the chapter in the same key as the feast opened it: while the holy mountain hosts the banquet for all peoples, the enemy's greatest defenses become dust. Christ's promise in Matthew 16:18 — <em>the gates of Hades will not prevail against my church</em> — is the positive expression of what this verse promises negatively. The fortifications that seemed impregnable cannot stand before the one who swallows up death and wipes every tear.</p>"
}
}

data = load_comm('mkt-christ', 'isaiah')
merge_comm(data, NEW)
save_comm('mkt-christ', 'isaiah', data)
print('Done.')
