"""
MKT Context -- Luke 10-11
Output: data/commentary/mkt-context/luke.json

Ch10: Mission of the 72 (number symbolism, shaliach principle), woes on
  Galilean towns (Tyre/Sidon OT background), Good Samaritan (Jericho road
  context, Samaritan tensions, priestly purity concerns), Mary/Martha.
Ch11: Lord's Prayer (shorter Lukan form, Aramaic Abba background), persistent
  friend parable (Mediterranean hospitality), Beelzebul controversy (finger of
  God / Exod 8 allusion), sign of Jonah, lamp/eye idioms, woes against
  Pharisees and lawyers (halakhic background).
"""
import json, pathlib
ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists(): return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    # INTENT: merge new_data into existing without overwriting any present entry
    for ch, verses in new_data.items():
        if ch not in existing: existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]: existing[ch][v] = html

NEW = {
'10': {
'1': '<p>The mission of the seventy-two (or seventy, depending on manuscript tradition -- P75, B, D read seventy; majority text reads seventy-two) deliberately invokes two OT precedents. Seventy is the number of elders Moses appointed (Num 11:16-17, 24-25) and the number of nations in the Table of Nations (Gen 10 MT = 70; LXX = 72 nations). Seventy-two aligns with the LXX count. Luke\'s choice positions the expanded mission as both a new-Moses leadership structure and an anticipation of the universal Gentile mission that Acts will narrate. Sending in pairs (ana duo) follows the Jewish legal principle that testimony requires two witnesses (Deut 17:6; 19:15) and was the practice of later rabbinical emissaries (m. Sanhedrin 1:1-3).</p>',
'2': '<p>"The harvest is plentiful, but the workers are few" -- the harvest metaphor for the gathering of souls appears in Jewish eschatology (Isa 27:12: "the Lord will thresh... one by one"; Joel 3:13: "swing the sickle, for the harvest is ripe"; 4 Ezra 4:28-32). In the OT, the harvest of nations was often an image of divine judgment; Jesus reappropriates it as the gathering of the saved. The prayer to the Lord of the harvest (the Lord as owner of the crop, who dispatches workers) frames mission as response to divine initiative: God is already working; the disciples are sent to participate, not to originate.</p>',
'3': '<p>"Go! I am sending you out like lambs among wolves" -- the vulnerability contrast (lamb/wolf) was proverbial in antiquity. In the OT, the sheep among wolves image described Israel among hostile nations (Ezek 22:27; Jer 50:17; Zeph 3:3). Here it is the disciples among hostile audiences. The shaliach principle (m. Berakhot 5:5: "a person\'s agent is as the person himself") governs the mission: to receive the disciples is to receive Jesus; to reject them is to reject him (v.16). The lambs being sent implies the shepherd\'s awareness and responsibility for the lambs\' vulnerability.</p>',
'4': '<p>"Do not take a purse or bag or sandals" -- the travel instructions mirror the Passover night (Exod 12:11: "with your cloak tucked in, sandals on your feet, staff in hand"), conveying urgency. "Do not greet anyone on the road" echoes Elisha\'s instruction to Gehazi (2 Kgs 4:29: "if you meet anyone, do not greet him; if anyone greets you, do not answer"), signaling single-minded focus on the urgent mission. In Oriental culture, greetings could involve lengthy exchange of formal courtesies; bypassing them signals the urgency of the kingdom\'s arrival.</p>',
'5': '<p>"When you enter a house, first say, \'Peace to this house\'" -- Shalom (Peace) was the standard Jewish greeting (1 Sam 25:6; Dan 10:19). In the mission context, however, the greeting is not merely social formula but a prophetic word that carries its own power: if a "son of peace" (ben shalom in Aramaic = someone characterized by peace, receptive to the gospel) is there, the peace will rest on the household. The "son of peace" idiom is a Semitic idiom for a person whose essential character is described by the noun: "son of wisdom," "son of perdition," "son of the resurrection" (20:36).</p>',
'6': '<p>"A son of peace" (huios eir&#275;n&#275;s) is a Lukan Semitism: huios + genitive noun denotes a person characterized by the noun. The dynamic quality of the peace-greeting -- it "rests on" the receptive person but "returns to you" if rejected -- reflects the understanding of the prophetic word as active (cf. Isa 55:11: "my word... will not return to me empty"). The mission is not a conditional offer but an active force: peace is released by the greeting and either received (and stays) or rejected (and returns to the sender).</p>',
'7': '<p>"Stay in that house, eating and drinking whatever they give you, for the worker deserves his wages" -- the prohibition on moving from house to house prevented the appearance of shopping for better accommodations (an honor issue in Mediterranean culture) and prevented the disciples from becoming a burden that exhausted hospitality. "The worker deserves his wages" appears also in 1 Tim 5:18 and 1 Cor 9:14, suggesting it was a recognized principle in early Christianity. The Didache 11-12 later grapples with the problem of traveling prophets who abuse hospitality -- the Lukan instruction anticipates this concern.</p>',
'8': '<p>"Eat what is set before you" -- this instruction has been interpreted as a practical suspension of Jewish food laws when staying in Gentile homes, anticipating the Acts 10-11 vision (Peter\'s sheet vision). In Jewish law, eating with Gentiles risked consuming forbidden foods; the instruction allows the mission to proceed without imposing Jewish dietary observance on hosts. Alternatively, it may simply mean not being fastidious within Jewish contexts. Either way, it subordinates ritual concerns to mission priority, a pattern Paul later develops (1 Cor 10:27: "eat whatever is set before you").</p>',
'9': '<p>"Heal the sick who are there and tell them, \'The kingdom of God has come near to you\'" -- the pairing of healing and proclamation defines the mission: the deeds confirm the words, and the words interpret the deeds. "The kingdom of God has come near" (ēggiken eph\' hymas = has come upon you) is the closest Luke comes to the Markan "the kingdom of God is at hand." The healings are not merely humanitarian acts but signs of the kingdom\'s presence (cf. 11:20: "if I drive out demons by the finger of God, the kingdom of God has come upon you").</p>',
'10': '<p>When a town does not receive the disciples, the prophetic-sign of wiping off the dust (v.11) is performed publicly in the town streets. This is not mere personal rejection but communal rejection, carrying communal consequences. The town-square witness maximizes the public character of the act: the whole community can see the sign and understand the declaration that the kingdom has been offered and refused.</p>',
'11': '<p>"Even the dust of your town we wipe from our feet as a warning to you" -- Jews returning from Gentile lands wiped the dust from their feet to avoid bringing Gentile impurity into the Holy Land (m. Oholot 2:3 and later sources). The gesture here reverses the direction: the disciples shake off the dust of the rejecting town, treating it as profane territory. "Yet be sure of this: the kingdom of God has come near" -- the warning is that the kingdom\'s nearness makes the rejection more serious, not less.</p>',
'12': '<p>"It will be more bearable for Sodom on that day than for that town" -- Sodom was the paradigm of divine judgment on the most wicked city (Gen 19; Isa 1:9-10; Ezek 16:46-50). Sodom\'s notorious wickedness (Gen 18:20: "the outcry against Sodom and Gomorrah is so great") makes its sentence a measuring standard. Jesus\' claim that Galilean towns that reject the kingdom will face harsher judgment than Sodom is shocking: the privilege of having heard the gospel makes rejection more culpable, not less.</p>',
'13': '<p>Chorazin and Bethsaida were Galilean towns near Capernaum. Chorazin (modern Khirbet Kerazeh, 3 km north of Capernaum) was excavated to reveal a fourth-century CE synagogue, probably built on an earlier site. Bethsaida (modern et-Tell near the Jordan\'s entry into the lake) was the hometown of Philip, Andrew, and Peter (John 1:44; 12:21). Both towns apparently witnessed significant miracles not recorded in the Gospels. The comparison cities -- Tyre and Sidon -- were Phoenician port cities condemned repeatedly in OT prophecy (Isa 23; Ezek 26-28; Joel 3:4-8; Amos 1:9-10) as paradigms of pride and wealth.</p>',
'14': '<p>Tyre and Sidon represent the epitome of Gentile paganism -- proud commercial cities that forgot God (Ezek 28:2: "Because you think you are wise, as wise as a god"). The OT prophets devoted extended oracles to their judgment. That these pagan cities would have repented in sackcloth and ashes (the garments of mourning and penitence: Est 4:1; Dan 9:3; Jonah 3:6) if they had seen Chorazin\'s miracles underscores both the adequacy of the revelation given to the Galilean towns and their culpable failure to respond to it.</p>',
'15': '<p>Capernaum\'s special condemnation -- "will you be lifted up to heaven? No, you will go down to Hades" -- echoes the oracle against the king of Babylon in Isa 14:13-15 ("you said in your heart, \'I will ascend to heaven... I will raise my throne above the stars of God\'... But you will be brought down to the realm of the dead"). Capernaum was the base of Jesus\' Galilean ministry and the site of his greatest miracles; its judgment is correspondingly severe. The Hades reference (Hadēs = the realm of the dead) reflects the OT Sheol tradition, contrasted with heaven as the place of divine favor.</p>',
'16': '<p>"Whoever listens to you listens to me; whoever rejects you rejects me; but whoever rejects me rejects him who sent me" -- the shaliach (agent) principle in its fullest form. In Jewish law, the principle kish&#259;lu&#7717;o k&#333;mot&#333; ("as his sender, so the one sent") meant the agent\'s actions had full legal force as the principal\'s own actions (m. Berakhot 5:5; b. Kiddushin 41b-43a). Jesus applies this to the disciples: reception/rejection of them is reception/rejection of him, which is reception/rejection of the Father. The chain of divine sending (Father -- Son -- disciples) makes the mission cosmic in significance.</p>',
'17': '<p>"The seventy-two returned with joy and said: \'Lord, even the demons submit to us in your name!\'" -- the disciples\' report focuses on the unexpected: not healing or welcome but authority over demons. The authority over demons was given in 9:1 and 10:17-19; the specific mention of Jesus\' name reflects the Second Temple Jewish practice of invoking the name of divine figures in exorcism (Acts 19:13: "In the name of Jesus whom Paul preaches"). The "name" (onoma) represents the authority, character, and power of the person; to act in Jesus\' name is to act as his authorized agent.</p>',
'18': '<p>"I saw Satan fall like lightning from heaven" -- Luke\'s unique logion. The background is complex: Isa 14:12 LXX ("how you have fallen from heaven, O morning star, son of the dawn") was applied to a primordial fall of Satan/Lucifer in Jewish and later Christian interpretation (1 Enoch 86-88 describes angels falling as stars; Rev 12:9 narrates Satan\'s expulsion from heaven). Jesus\' vision -- whether of a primordial event or a present cosmic consequence of the disciples\' mission -- frames the exorcisms as battles in a cosmic war. The disciples\' victories on earth have heavenly significance: each exorcism is a blow to the enemy\'s domain.</p>',
'19': '<p>"I have given you authority to trample on snakes and scorpions and to overcome all the power of the enemy" -- snakes and scorpions as symbols of demonic danger appear in Ps 91:13 ("you will tread on the lion and the cobra; you will trample the great lion and the serpent") and Deut 8:15 (the wilderness "with its venomous snakes and scorpions"). The authority given is not just over physical dangers but over the full power of the enemy -- the spiritual forces behind them. Acts 28:3-6 (Paul bitten by a viper but unharmed) and Acts 16:16-18 (exorcism of the fortune-telling spirit) show this authority in practice.</p>',
'20': '<p>"Rejoice that your names are written in heaven" -- the heavenly book of life appears in Exod 32:32-33 (Moses asks God not to blot him from the book), Dan 12:1 ("everyone whose name is found written in the book"), Ps 69:28 ("erase them from the book of life"), and Rev 3:5; 20:12. The Lukan reassurance shifts the disciples\' joy from their performance (exorcisms) to their standing (enrollment in God\'s register). The victory over demons is real but contingent; the permanent enrollment in the heavenly record is the firmer ground of joy.</p>',
'21': '<p>The prayer of jubilation -- "I praise you, Father, Lord of heaven and earth, because you have hidden these things from the wise and learned, and revealed them to little children" -- echoes Isa 29:14 ("the wisdom of the wise will perish, the intelligence of the intelligent will vanish") and Sir 51:23-27. "Little children" (n&#275;piois = infants, those without wisdom or status) as the recipients of revelation contrasts with the sophos kai synetos (wise and understanding = the scribal elite). The Qumran community similarly restricted the mysteries to the elect (1QS 11:3-8; 1QH 12:27-28). Luke\'s "at that time Jesus, full of joy through the Holy Spirit" (agrallias&#257;to in the Holy Spirit) underscores the Trinitarian character of the moment.</p>',
'22': '<p>"All things have been committed to me by my Father" -- the most Johannine-sounding logion in the Synoptics (cf. John 3:35; 13:3; 17:2). Matthew 11:27 has the same saying. It is sometimes called the "Johannine thunderbolt" for its resemblance to the Fourth Gospel\'s high Christology. The claim to exclusive mutual knowledge ("no one knows who the Son is except the Father, and no one knows who the Father is except the Son") establishes a relationship of unique intimacy that grounds the mission\'s authority: what the disciples receive from Jesus is not one teacher\'s insight but the self-revelation of the one who uniquely knows the Father.</p>',
'23': '<p>The private beatitude to disciples (vv.23-24, parallel in Matt 13:16-17) is addressed specifically to "his disciples" (tous math&#275;tas kat\' idian = to the disciples privately). The blessedness is not for performance but for historical location: to be living in the generation of fulfillment, to see what prophets and kings longed to see (Dan 2:28: "there is a God in heaven who reveals mysteries, and he has shown King Nebuchadnezzar what will happen in days to come"). The prophets who predicted the Servant\'s suffering and glory wanted to understand what they predicted (1 Pet 1:10-12).</p>',
'24': '<p>"I tell you that many prophets and kings wanted to see what you see but did not see it, and to hear what you hear but did not hear it" -- the prophets who foresaw the messianic age (Isa 61; Dan 9; Mic 5:2) and the kings of the Davidic line who hoped for the ultimate Davidic heir (Ps 2; 72; 110) were anticipating what the disciples now witness directly. The privilege is not of the disciples\' deserving but of their moment: they live in the fullness of time (Gal 4:4: "when the set time had fully come"). This verse is the hermeneutical key for Luke\'s use of the OT: the whole prophetic tradition was anticipating this.</p>',
'26': '<p>The lawyer\'s question "What is written in the Law? How do you read it?" shifts the burden back to the questioner. In rabbinic discussion, citing Scripture (ma katuv = what is written) followed by interpretation (kiv&#39;an de katib = how do you read it?) was the standard pedagogical method. Jesus does not simply answer the question but draws out the lawyer\'s own knowledge, making him the source of the correct answer. This is consistent with the Socratic method of Jesus\' teaching (also Luke 10:36: "Which of these three do you think was a neighbor?").</p>',
'27': '<p>The lawyer combines Deut 6:5 (love God with all heart/soul/strength -- the Shema) and Lev 19:18 (love your neighbor as yourself). In Matthew 22:34-40 and Mark 12:28-34, it is Jesus who combines these two commandments; in Luke 10:27, the lawyer makes the combination himself -- Luke\'s version emphasizes the lawyer\'s own correct understanding, which Jesus affirms. The Shema (Deut 6:4-9) was recited twice daily in Jewish prayer; Lev 19:18 was recognized by Rabbi Akiva (b. Sifra 89b) as "the great principle of the Torah." The combination thus represents the highest insight of Jewish ethical reflection.</p>',
'28': '<p>"You have answered correctly. Do this and you will live" -- Jesus\' affirmation of the lawyer\'s answer echoes Lev 18:5 ("keep my decrees and laws, for the person who obeys them will live by them") and Ezek 20:11 ("I gave them my decrees and made known to them my laws, by which the person who obeys them will live"). The "do this" is the operative clause: the lawyer knows the commandment but does not do it -- hence the follow-up question "who is my neighbor?" which is an attempt at self-justification (v.29) rather than genuine inquiry.</p>',
'29': '<p>"And who is my neighbor?" -- the lawyer\'s self-justifying question (thel&#333;n dikaio&#333;sai heauton = wishing to justify himself) reveals that the real question is not theoretical but practical: he is looking for the minimum definition of "neighbor" that allows him to declare his obligation fulfilled. The Second Temple debate on who counts as a "neighbor" was real: some interpretations limited the neighbor-obligation to fellow Jews, or even to members of one\'s own Pharisaic group (haverim = associates who observe tithing purity laws). The parable Jesus tells does not answer the definitional question but reframes it entirely (v.36).</p>',
'30': '<p>The Jerusalem-to-Jericho road was a real, well-known 27 km descent of approximately 900 meters through the Judean wilderness. It was notorious for banditry: Josephus mentions it (War 4.474); Jerome called it the "Bloody Way" or "Ascent of Adummim" (Adummim = blood-red, from the red rock color -- some identify this with the brigand-haunted pass). The victim "fell among robbers" (peripesen l&#275;stais) -- the same verb as "fell" in Ezekiel\'s allegory of Jerusalem (Ezek 16:15; lēstēs = bandit/robber, the same word used of Barabbas and the crucified alongside Jesus in 23:18-19, 39). The attack was total: stripped, beaten, left half-dead (h&#275;mithane = half-dead, barely alive).</p>',
'31': '<p>A priest happened to be going down the road. The priest\'s failure to help has been most plausibly explained by the concern for ritual impurity: contact with a corpse (or a potentially dead person) would render a priest unclean for seven days (Lev 21:1-4; Num 19:11-13). During the period of uncleanness, he could not perform temple service. Some interpreters have argued that the priest was traveling away from Jerusalem (going down to Jericho) and therefore not at risk of immediately serving; others note that a priest could own property in Jericho and needed to maintain ritual purity for future service. Either way, the risk-calculation of purity-maintenance over compassion is the narrative\'s indictment.</p>',
'32': '<p>A Levite came to the same place and passed by on the other side. Levites served in the temple in subordinate roles to priests (musicians, doorkeepers, assistants) and were also subject to purity regulations, though less strictly than priests (Lev 21:1-4 applies specifically to Aaronide priests; Levites had fewer restrictions). The Levite\'s passing mirrors the priest\'s: he "saw him" (id&#333;n) and then passed by on the other side (antip&#275;lthen). The deliberate action (passing on the other side rather than simply continuing) implies active avoidance rather than mere inattention.</p>',
'33': '<p>A Samaritan traveler came upon the man. The audience would have expected the third figure in the priest-Levite-third sequence to be an Israelite layman. Instead, Jesus introduces a Samaritan -- the most despised group from a Jewish perspective. Samaritans were descended from the mixed population settled in the Northern Kingdom after the Assyrian deportation (2 Kgs 17:24-41) and had developed a distinct religious identity (the Pentateuch only, worship on Mt. Gerizim, rejection of the Jerusalem temple). Jewish-Samaritan tensions were intense (John 4:9: "Jews do not associate with Samaritans"; Josephus Ant. 18.29-30 describes violent incidents on the Galilee-Jerusalem pilgrimage route). The Samaritan hero makes the parable maximally provocative.</p>',
'34': '<p>The Samaritan\'s care is described in extended detail: he "took pity on him" (esp&#225;gchnis&#347;th&#275; = was moved in his bowels/compassion), went to him, bandaged his wounds, poured oil and wine (oil as soothing agent, wine as antiseptic -- basic ancient wound care), put him on his own donkey, brought him to an inn, and took care of him. Each action represents an escalation of personal involvement and cost. The inn (pandocheion = an establishment that received everyone) was the common lodging facility on major roads; the term pandochos (host of all) reflects the universal hospitality that the inn offers -- in ironic contrast to the priest and Levite who offered none.</p>',
'35': '<p>The next day, the Samaritan gave the innkeeper two denarii (approximately two days\' wages for a laborer) and promised to reimburse any additional expenses on his return. The financial commitment is open-ended: "whatever you spend in addition, I will repay you when I return." This is not charity with a fixed limit but unlimited obligation assumed by the Samaritan on behalf of a stranger from an ethnic group hostile to his own. The return journey implies the Samaritan was a regular traveler on this route -- a merchant or tradesman who would pass through again.</p>',
'36': '<p>"Which of these three do you think was a neighbor to the man who fell into the hands of robbers?" -- the question inverts the lawyer\'s original question. The lawyer asked: "Who counts as my neighbor?" (seeking to define and limit his obligation). Jesus asks: "Which one acted as a neighbor?" (shifting from definition to disposition). The answer cannot be the "Samaritan" (an answer the lawyer could not bring himself to say; he says "the one who had mercy on him"). The redefinition: a neighbor is not a category of person to whom I owe obligations but a quality of relationship I establish by my action. Neighborliness is not determined by who the other person is but by how I choose to act.</p>',
'37': '<p>"Go and do likewise" (poreuou kai sy poiei hom&#333;ios) -- the imperative that ends the parable is both personal (sy = you) and present-continuous (poiei = keep doing). The parable is not an inspiring story about Samaritan goodness but a direct challenge to the lawyer\'s existing practice. The neighbor he failed to be is the neighbor he is now called to become -- not toward some abstract other person but in the next moment of encountering a person in need. The "likewise" (hom&#333;ios) echoes the word used in the lawyer\'s own summary of the second commandment (hom&#333;ios in v.28 is implicit; the pattern is the Samaritan\'s pattern).</p>',
'38': '<p>"A village" without a name in Luke (John 11:1 identifies it as Bethany, 3 km east of Jerusalem on the Jericho road). The identification of Bethany as Mary and Martha\'s home is supported by John 11-12, where the same sisters appear with their brother Lazarus. The episode is unique to Luke, serving as the pairing narrative for the Good Samaritan (action) and the Mary/Martha encounter (contemplation). The two women represent different but complementary responses to Jesus: Martha\'s diakonia (service/hospitality) and Mary\'s listening at his feet (the learner\'s posture).</p>',
'39': '<p>Mary "sat at the Lord\'s feet listening to what he said" -- sitting at a teacher\'s feet was the posture of the disciple (Acts 22:3: Paul "educated at the feet of Gamaliel"). Women normally did not function as disciples in Jewish educational settings; the Mishnah records debates about teaching Torah to women (m. Sotah 3:4: "Let the words of the Torah be burned rather than handed over to women" -- the minority opinion of Rabbi Eliezer, opposed by others). Jesus\' acceptance of Mary\'s discipleship role (and his defense of it in v.42) is a counter-cultural act of inclusion.</p>',
'40': '<p>Martha was "distracted by all the preparations" (perispaō = pulled around, scattered) -- the Greek suggests her attention was being pulled in multiple directions by the work of hosting. Her appeal to Jesus to tell Mary to help reflects both the social obligation (the host\'s honor depended on adequate hospitality) and the expectation that Mary should be performing her domestic duty. "Don\'t you care?" (ou melei soi) is a direct address that implies Jesus is at fault for the situation by allowing Mary to sit rather than help. This is the only time in the Gospels that someone rebukes Jesus for what he allows.</p>',
'41': '<p>"Martha, Martha" -- the repeated name of address appears at moments of tender urgency in the NT: "Simon, Simon" (22:31), "Saul, Saul" (Acts 9:4). The doubling in Jewish address can indicate deep emotion, urgency, or affection. "You are worried and upset about many things" -- the critique of Martha is not that hospitality is wrong but that anxiety (merimn&#257;s = worry/anxiety) and being upset (thorybaz&#275; = troubled/disturbed) about the many preparations reveals a misplaced priority. The worry itself -- not the service -- is the problem. The contrast with Mary is not service vs. leisure but anxious distraction vs. focused attention.</p>',
'42': '<p>"But few things are needed -- or indeed only one" -- the textual tradition varies: some MSS read "one thing is needed"; others read "few things are needed, or one" (a conflation). The point is the contrast between the "many things" of Martha\'s preparation and the "one thing" or "few things" that actually matter. "Mary has chosen what is better" (t&#275;n agath&#275;n merida = the good portion) and "it will not be taken away from her" (using the same root as the estate-division imagery). The "good portion" echoes Ps 16:5-6 (God as portion), the Levitical tradition (God as the Levites\' portion, Num 18:20), and the wisdom tradition where the sage\'s portion is wisdom itself (Wis 8:7). The contemplative life is not superior to the active but is the necessary ground of it.</p>',
},
'11': {
'1': '<p>Jesus\' prayer habit generates the disciples\' request: "Lord, teach us to pray" -- a request for a prayer-signature, since John the Baptist had given his disciples a characteristic prayer (and the Baptist movement was known for its prayer practices, cf. 5:33). Rabbinic masters often had distinctive short prayers: the Talmud preserves short prayers of individual rabbis (b. Berakhot 17a). The disciples\' request implies that a distinctive prayer would identify them as Jesus\' disciples in the same way John\'s prayer identified the Baptist\'s community. The Lord\'s Prayer becomes the community-marker of the Jesus movement.</p>',
'2': '<p>Luke\'s version of the Lord\'s Prayer is shorter than Matthew\'s (Matt 6:9-13). Scholarly consensus holds that Luke\'s version is closer to the original, with Matthew\'s version showing liturgical expansion (the doxology "for yours is the kingdom..." is absent from the best early MSS of Matthew and almost certainly a later addition). "Father" (Abb&#257; in Aramaic, preserved in Mark 14:36; Rom 8:15; Gal 4:6) -- the intimate address of a child to a parent, a significant departure from the more formal "Our Father in heaven" of Matthew and the typical Jewish liturgical address (Avinu she-b-ashamayim). The intimacy of "Father" alone reflects the unique filial relationship Jesus claims with God.</p>',
'3': '<p>"Give us each day our daily bread" (ton arton h&#275;m&#333;n ton epiousion didou h&#275;min to kath\' h&#275;meran) -- the adjective epiousios (daily/for the coming day) is extremely rare in Greek, found only here in the NT and Matt 6:11 (and in a single papyrus reference, P. Lond. 3.965). Its meaning is debated: "for today/daily" (everyday bread), "for tomorrow" (the next day\'s bread), "essential/necessary" (bread for existence), or "supernatural/eschatological" (the bread of the coming age, anticipating the messianic banquet). The "each day" phrasing (to kath\' h&#275;meran) in Luke\'s version contrasts with Matthew\'s "today" (s&#275;meron), suggesting a petition for ongoing rather than one-time provision.</p>',
'4': '<p>"Forgive us our sins, for we also forgive everyone who sins against us" -- Luke\'s "sins" (hamartias) versus Matthew\'s "debts" (opheile&#772;mata). The debt-metaphor of Matthew (reflecting the Aramaic hoba = both sin and debt) is an economic metaphor consistent with Jubilee theology (Lev 25 debt-cancellation); Luke\'s version uses the more direct moral category. The linking of divine and human forgiveness ("for we also forgive") makes human forgiveness the prerequisite or corollary of requesting divine forgiveness -- a pattern Jesus elaborates in the parable of the unforgiving servant (Matt 18:23-35). "Lead us not into temptation" (peirasmos = testing/temptation) echoes the Lord\'s testing of Jesus in the wilderness (4:1-13).</p>',
'5': '<p>The parable of the persistent friend (vv.5-8), unique to Luke, is set at midnight -- the most extreme violation of normal social hours. The hospitality obligation in Mediterranean culture was absolute: to receive a traveler was a sacred duty (Gen 18-19; Judg 19; Heb 13:2). An unexpected guest at midnight demanded that the host produce food -- failure to provide would bring dishonor. The friend\'s knock at his neighbor\'s door is motivated not by personal need but by the honor-obligation to his guest: "a friend of mine on a journey has come to me, and I have nothing to set before him." He asks on behalf of another, not for himself.</p>',
'6': '<p>The cultural context of the request: "I have nothing to set before him" (ouk ech&#333; ho parathēsō aut&#333;) was a socially catastrophic admission. In Mediterranean culture, the host\'s honor was entirely bound up in his ability to provide adequate hospitality. The shame of being unable to feed a guest was not merely a personal embarrassment but a family and community dishonor. The friend\'s persistence is not excessive -- it is proportional to the seriousness of his social obligation. He cannot give up until the need is met.</p>',
'7': '<p>The neighbor\'s refusal -- "Don\'t bother me. The door is already locked, and my children and I are in bed" -- reflects the typical sleeping arrangement of a first-century Palestinian house: a one-room dwelling where the entire family slept on an elevated platform. Getting up would disturb the whole family. The neighbor\'s reluctance is understandable; his eventual compliance is not motivated by friendship (ouk epid&#333;sei... dia to einai philon autou = not because he is his friend) but by the friend\'s shameless persistence (di\' ge t&#275;n anaidian autou = because of his shamelessness/importunity).</p>',
'8': '<p>Anaideia (shamelessness, importunity, persistence) is the hinge word of the parable. In Greek culture, anaideia was normally a negative quality (absence of shame, shamelessness, impudence). Here it is the quality that prevails. Some interpreters read the parable as a kal vachomer (lesser-to-greater) argument: if a reluctant neighbor will eventually give to a persistent friend, how much more will a willing Father give to his persistent children? The point is not that God needs to be pestered but that the asking itself is the proper posture of the disciple before the generous Father.</p>',
'9': '<p>"Ask... seek... knock" -- the triple imperative (ask/ait&#275;ite, seek/z&#275;teite, knock/krouete) is a progressive intensification: asking is verbal, seeking involves action, knocking involves persistence at a closed door. All three are present-imperative (keep asking, keep seeking, keep knocking) -- the persistence modeled in the parable is built into the grammatical form of the instruction. The triple structure also corresponds to three levels of relationship: ask (as a child to a parent), seek (as one who has lost something valuable), knock (as one waiting for admission).</p>',
'10': '<p>"For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened" -- the universal promise (p&#257;s = everyone) is remarkable in its scope: not just disciples but "everyone" who asks receives. In the context of the Lord\'s Prayer and the preceding parable, the "everyone" is qualified by the relationship of filial trust with the Father -- the Gentile pursuit of knowledge or wealth does not fall within this promise. The parallel in Matt 7:8 has the same language; both reflect a Q tradition (the double tradition of Matthew and Luke).</p>',
'11': '<p>The two negative analogies (father and son) underscore the Father\'s goodness by contrast. "Which of you fathers, if your son asks for a fish, will give him a snake instead?" The snake-for-fish contrast picks two items that might look superficially similar (an eel vs. a snake, both elongated) but differ entirely in edibility and danger. The question assumes the answer: no father would deliberately deceive or harm his child with a dangerous substitute for a harmless food request.</p>',
'12': '<p>"Or if he asks for an egg, will give him a scorpion?" -- the scorpion-for-egg contrast again picks items that might be confused (a curled scorpion possibly resembling a white egg) but differ entirely. The reductio ad absurdum is designed to make the Father\'s generosity self-evident by contrast: if even evil human fathers would not deceive their children in this way, the Father who is genuinely good would never give harmful things when good things are asked.</p>',
'13': '<p>"If you then, though you are evil, know how to give good gifts to your children, how much more will your Father in heaven give the Holy Spirit to those who ask him!" -- the kal vachomer (lesser-to-greater): human parents, despite being "evil" (pon&#275;roi = morally imperfect/flawed), give good gifts. The heavenly Father, who is genuinely good, will give the greatest gift. Luke\'s version says "the Holy Spirit" where Matthew 7:11 has "good things" -- a characteristically Lukan substitution reflecting the centrality of the Spirit in Luke-Acts (the Spirit received at Pentecost, Acts 2; the Spirit as the guide of the early mission).</p>',
'14': '<p>The exorcism of a mute demon leads to a divided response: the crowd wonders, but some attribute the miracle to Beelzebul. The Beelzebul accusation appears in all three Synoptics (Mark 3:22; Matt 12:24; Luke 11:15) -- its multiple attestation suggests an early, historically grounded tradition. The name Beelzebul (or Beelzebub in 2 Kgs 1:2-3: Ba\'al-Zebub = "Lord of Flies," the god of Ekron) was apparently reinterpreted in Second Temple Judaism as a demonic figure or prince of demons. The accusation attempts to explain Jesus\' exorcistic power in the most hostile possible way.</p>',
'15': '<p>The Pharisees\' accusation: "By Beelzebul, the prince of demons, he is driving out demons." The logic is that Jesus\' power must come from somewhere, and if not from God then from the demonic chief himself. This is not simple ignorance but deliberate attribution to the worst possible source. The charge has a parallel in later rabbinic polemic against Jesus in the Tosefta and Talmud, where Jesus is accused of leading Israel astray by magic (t. Sanhedrin 10:11; b. Sanhedrin 43a). The accusation represents the most extreme form of opposition -- attributing divine works to Satan.</p>',
'16': '<p>Others "tested him by asking for a sign from heaven" -- the demand for a heavenly sign (from heaven = directly from God, distinguishable from human or demonic origin) reflects the continuing demand for messianic validation. The wilderness temptation (4:9-12) involved Satan\'s demand that Jesus demonstrate divine protection; now the crowds make a similar demand. Jesus\' refusal to perform signs on demand (v.29: "a wicked generation asks for a sign") is consistent with his refusal to "test the Lord" in the temptation.</p>',
'17': '<p>"Every kingdom divided against itself will be ruined, and a house divided against itself will fall" -- the political proverb was a common piece of ancient wisdom: Thucydides 3.82; Josephus War 4.397 quotes a similar principle about internal division. The application to the Beelzebul accusation: if Satan is casting out his own demons, the demonic kingdom is self-defeating. The logic exposes the absurdity of the accusation: no unified intelligent power destroys its own forces. Either the Pharisees\' charge is wrong or Satan has become suicidal.</p>',
'18': '<p>"If Satan is divided against himself, how can his kingdom stand?" -- the argument from kingdom-unity extends the previous verse. Jesus grants the premise for argument\'s sake: if I were casting out demons by Satan\'s power, that would mean Satan is destroying his own work. But a kingdom self-divided cannot stand (historical examples: the divided kingdoms of Israel and Judah, 1 Kgs 12; the Roman civil wars; Herod\'s divided family). The absurdity of the Beelzebul hypothesis makes it self-refuting.</p>',
'19': '<p>"Now if I drive out demons by Beelzebul, by whom do your followers drive them out?" -- the tu quoque argument: Jewish exorcists also practiced exorcism (Acts 19:13-16; Josephus Ant. 8.46-49; the Damascus Document; the Aramaic Levi Document all attest Jewish exorcistic practice). If Jesus\' exorcisms require demonic explanation, the same charge should apply to Jewish exorcists. "They will be your judges" (autoi hym&#333;n kritai esontai): the exorcistic disciples of the Pharisees\' own tradition will testify against the logical inconsistency of the charge.</p>',
'20': '<p>"But if I drive out demons by the finger of God, then the kingdom of God has come upon you" -- the "finger of God" is an Exodus allusion: when the Egyptian magicians could no longer replicate Moses\' miracles, they said "This is the finger of God" (Exod 8:19 LXX: daktylos theou estin touto). The phrase identifies Jesus\' power as the same divine power that freed Israel from Egypt -- the new Exodus motif. Matthew 12:28 reads "Spirit of God" rather than "finger of God"; both may reflect different applications of the same underlying tradition. "Has come upon you" (ephthasen eph\' hymas = has arrived, reached you) -- the aorist implies the kingdom has already arrived, not merely approached.</p>',
'21': '<p>"When a strong man, fully armed, guards his own house, his possessions are safe" -- the strong man parable (also Mark 3:27; Matt 12:29) provides the cosmic framework for the exorcisms. The strong man = Satan, ruling his domain; the stronger man (ischyroteros) who overcomes him = Jesus. The parable reflects the Jewish understanding of cosmic warfare: before the Messiah\'s work, the present age was under the dominion of "the evil one" or "the ruler of this world" (John 12:31; Eph 6:12; 1 John 5:19: "the whole world is under the control of the evil one"). The exorcisms are not isolated healings but tactical victories in the conquest of Satan\'s domain.</p>',
'22': '<p>"When someone stronger attacks and overpowers him, he takes away the armor in which the man trusted and divides up his plunder" -- the armor (panoplia = full armor) and plunder (skyla = the spoils of war) extend the military metaphor. Jesus is the stronger one who has invaded Satan\'s domain and is systematically plundering it. This echoes the Servant\'s role in Isa 53:12 ("he will divide the spoils with the strong") and the Jubilee release of captives (4:18 -- the "prisoners" are Satan\'s captives). Ephesians 4:8 (quoting Ps 68:18) applies the same warfare-and-spoils imagery to the ascension.</p>',
'23': '<p>"Whoever is not with me is against me, and whoever does not gather with me scatters" -- the stark binary admits no neutral position. In the context of the Beelzebul controversy, the accusation that Jesus uses Satanic power is itself an expression of being "against" him. The gather/scatter imagery reflects the pastoral-harvest metaphor: gathering the flock (=the mission of the 72, harvest imagery) versus scattering it (=the work of the adversary who devours the flock, 1 Pet 5:8). Luke 9:50 has the apparently opposite principle ("whoever is not against you is for you") in a different context (about an outsider exorcist) -- context determines which principle applies.</p>',
'24': '<p>"When an impure spirit comes out of a person, it goes through arid places seeking rest and does not find it. Then it says, \'I will return to the house I left.\'" -- the wandering of expelled spirits through "waterless places" (anapoustes dierchetai anydron topo&#363; = going through waterless regions) reflects a widespread ancient belief about the habitat of demons in deserts (Isa 13:21; 34:14; Tob 8:3: Asmodeus flees to "the remotest parts of Egypt"). The personification of the spirit with intentionality (it "says"... it "returns") frames the internal spiritual state as an ongoing conflict between occupation and vacancy.</p>',
'25': '<p>"When it arrives, it finds the house swept clean and put in order" -- the swept-and-orderly house represents the person who has been exorcised but has not filled the vacancy with the positive presence of the Spirit. Spiritual reform without spiritual filling is dangerously insufficient. The Qumran community grappled with this: their covenant of repentance and strict Torah observance was an attempt to ensure that the purified person remained pure through active engagement with God\'s instruction. The warning here is not against exorcism but against the assumption that removal of evil is sufficient without replacement with good.</p>',
'26': '<p>"Then it goes and takes seven other spirits more wicked than itself, and they go in and live there" -- the number seven (hebdomad) in Jewish numerology often signifies completeness or the totality of evil powers (cf. Mary Magdalene from whom seven demons went out, 8:2; the seven evil spirits of the Testament of Solomon and other Second Temple texts). "The final condition of that person is worse than the first" -- the escalation from one to eight demons represents not just recurrence but intensification. The warning applies to individuals (religious reform that doesn\'t become genuine relationship), communities, and nations (Israel after the Exile who returned to idolatry).</p>',
'27': '<p>"Blessed is the mother who gave you birth and nursed you" -- a woman in the crowd offers a spontaneous beatitude on Jesus\' mother, a natural cultural response: the honor of a son reflects on his mother. The beatitude form (makaria = blessed) evokes Elizabeth\'s words to Mary (1:45: "blessed is she who has believed"). In Mediterranean honor-shame culture, the ultimate compliment to a man was to praise his mother for producing him. The woman\'s beatitude is sincere admiration, but it focuses on biological relationship.</p>',
'28': '<p>"Blessed rather are those who hear the word of God and obey it" -- Jesus\' response is not a dismissal of his mother (cf. 8:19-21 where "my mother and brothers are those who hear God\'s word and put it into practice"). The m&#275;noun ye (rather/but rather) introduces a corrective emphasis, not a contradiction: the higher blessing is not biological kinship with Jesus but the hearing-and-obeying relationship available to all. This opens discipleship to the universality that Luke emphasizes throughout -- no biological, ethnic, or gender restriction on the truly blessed relationship with Jesus.</p>',
'29': '<p>"A wicked and adulterous generation asks for a sign, but none will be given it except the sign of Jonah" -- "adulterous generation" (genea pon&#275;ra) is the OT metaphor for Israel\'s spiritual unfaithfulness (Hos 1-3; Ezek 16; Jer 3:8-9: Israel as unfaithful wife who "went after other lovers"). The Jonah sign: Matthew 12:40 interprets it as three days in the great fish (= death and resurrection). Luke\'s version (v.30) focuses on Jonah\'s preaching itself as the sign: Jonah was the sign to the Ninevites. The implicit message: the preaching of Jesus is itself the sign, if they will hear it.</p>',
'30': '<p>"For as Jonah was a sign to the Ninevites, so also will the Son of Man be to this generation" -- Jonah (the prophet who was thrown into the sea and swallowed by a great fish: Jonah 1:17; 2:1-10) emerged from his three days and preached to Nineveh, the great Assyrian city (Jonah 3). The Ninevites\' repentance (Jonah 3:5: "the Ninevites believed God; they declared a fast") makes them the positive counterpoint to the demanding crowd. The Son of Man\'s mission -- preaching, signs, presence -- is itself the sign to this generation, as Jonah\'s mission was the sign to Nineveh.</p>',
'31': '<p>The Queen of the South (the Queen of Sheba, 1 Kgs 10:1-10; 2 Chr 9:1-12) traveled "from the ends of the earth" to hear Solomon\'s wisdom. Sheba was identified with southern Arabia (modern Yemen) or with Ethiopia in ancient tradition; either way, it represents the utmost geographical distance. Her journey implies enormous effort and cost for wisdom; this generation has wisdom in their midst and refuses to seek it. She "will rise at the judgment with the people of this generation and condemn them" -- the eschatological court will include Gentile witnesses against unfaithful Israel, a pattern also in Ezek 16:46-52 (Sodom and Samaria as witnesses against Jerusalem).</p>',
'32': '<p>The people of Nineveh "will stand up at the judgment with this generation and condemn it; for they repented at the preaching of Jonah, and now something greater than Jonah is here." Nineveh was the capital of the Assyrian Empire, which had destroyed the Northern Kingdom (722 BCE) -- the paradigm of Israel\'s worst enemy. Their repentance at the preaching of a reluctant Israelite prophet makes them the ultimate model of responsive faith in contrast to the resistant Galilean towns. "Greater than Jonah" (pl&#275;ion I&#333;na) -- the comparative without a verb: "there is something greater than Jonah here." The neuter allows the greatness to refer to the event (the kingdom), the person (Jesus), or both.</p>',
'33': '<p>"No one lights a lamp and puts it in a place where it will be hidden, or under a bowl. Instead they put it on its stand, so that those who come in may see the light" -- the lamp saying occurs in different contexts in the Synoptics (Mark 4:21; Luke 8:16; Matt 5:15). In the present context, following the sign-of-Jonah discussion, the "lamp" is Jesus\'s preaching and ministry -- not hidden in a private room but publicly available to all who enter. The Lukan distinctives: "in a place where it will be hidden" (eis krypt&#275;n) and "under a bowl" (hypo ton mod&#301;on -- a grain measure) both represent deliberate concealment, which would be self-defeating.</p>',
'34': '<p>"Your eye is the lamp of your body. When your eyes are healthy, your whole body also is full of light" -- the eye metaphor draws on the ancient optics theory that the eye emitted light to see (intromission vs. extramission theories were debated in antiquity). More relevantly, the Hebrew/Aramaic "eye" idiom: ayin tov (good/generous eye) = generosity; ayin ra&#39;ah (evil/diseased eye) = greed and stinginess (Deut 15:9; Matt 6:23; Prov 28:22). The haplous (healthy/simple/generous) eye and the pon&#275;ros (diseased/evil/stingy) eye thus have both physical and moral dimensions: the person whose inner orientation is generous and receptive will be flooded with light; the grasping, resistant person will be darkened.</p>',
'35': '<p>"See to it, then, that the light within you is not darkness" -- the exhortation bridges the physical and moral dimensions of the eye metaphor. "The light within you" (to phos to en soi) refers to the inner orientation, the moral disposition that receives or rejects revelation. If the inner eye is set against the light (as with the sign-demanding generation), even the light of Jesus\' ministry will be interpreted as darkness. The warning is self-assessment: examine whether your receptive capacity is healthy or has been damaged by greed, status-seeking, or hardness of heart.</p>',
'36': '<p>"Therefore, if your whole body is full of light, and no part of it dark, it will be just as full of light as when a lamp shines its light on you" -- the positive conclusion of the lamp-and-eye sequence: a person of total receptivity (the whole body full of light, no part dark) will receive the full illumination of the lamp. In the context of the sign-seeking generation, the implication is: the problem is not the lamp (Jesus\' ministry) but the eye (their receptivity). The light is fully available; the question is whether the receiver is fully open to it.</p>',
'37': '<p>A Pharisee invites Jesus to eat with him. In Mediterranean culture, to invite someone to a meal was to honor them and to invite them into your social network -- a declaration of social solidarity. The Pharisee\'s invitation may be genuinely hospitable, motivated by curiosity or admiration. Jesus "reclined" (anapesen = lay back, took the reclining dining posture on the triclinium, the U-shaped dining arrangement of formal Hellenistic meals) -- a posture reserved for formal symposia and significant meals. The tension arises from the pre-meal ritual washing.</p>',
'38': '<p>"The Pharisee was surprised that he did not first wash before the meal" -- the pre-meal handwashing (nipsis = washing) was a distinctive Pharisaic practice. The Mishnah (m. Yadayim = "Hands") records extensive debates about handwashing: how much water, poured from what height, over what part of the hand. Mark 7:3-4 explains this practice for Gentile readers. The washing was a purity extension -- applying to non-priests the priestly purity obligations of Lev 22:6. Jesus\' failure to wash signals non-adherence to the Pharisaic purity extension program -- a deliberate, provocative departure from their halakhah.</p>',
'39': '<p>"Now then, you Pharisees clean the outside of the cup and dish, but inside you are full of greed and wickedness" -- the cup-and-dish metaphor was used in rabbinic debates about purity: the school of Shammai and the school of Hillel debated which was more important, interior or exterior purity of vessels (m. Berakhot 8:2). Jesus appropriates the technical dispute to make a moral point: the Pharisaic focus on ritual externals (the visible surface of the vessel) ignores the interior condition (the actual contents: greed and wickedness). "Greed" (harpag&#275;s = plundering, extortion) and "wickedness" (pon&#275;rias = evil) are strong terms.</p>',
'40': '<p>"You foolish people! Did not the one who made the outside make the inside also?" -- the rhetorical question appeals to creation theology: God made both the interior and exterior of human persons. The God who requires purity of the vessel\'s exterior also made and cares about the interior. The separation of ritual-exterior purity from moral-interior character is theologically incoherent: the Creator\'s concern encompasses both. The "foolishness" (aphrones = lacking reason, thoughtless) is the failure to draw the obvious conclusion from the doctrine of creation.</p>',
'41': '<p>"But now as for what is inside you -- give what is inside the dish to the poor, and everything will be clean for you" -- a compressed and difficult saying. The instruction to "give what is inside to the poor" (ta enonta dote eleemosynen) may mean: give alms from what you have (money, possessions, the actual contents of the dish -- the food you eat), and this genuine generosity (the disposition of the inside) will make everything clean. Almsgiving (eleemosynē) was understood in Judaism to atone for sin and restore purity (Tob 12:9: "almsgiving saves from death and purges away every sin"; Sir 3:30: "almsgiving atones for sin"). Luke\'s consistent emphasis on wealth-redistribution finds expression here.</p>',
'42': '<p>"Woe to you Pharisees, because you give God a tenth of your mint, rue and all other kinds of garden herbs, but you neglect justice and the love of God" -- the first woe addresses halakhic precision without proportionality. The Mishnah (m. Maasrot 4:5) records that dill, mint, and cumin required tithing; the Talmud discusses whether rue (p&#275;ganon) required tithing (b. Shabbat 128b). The Pharisees extended the tithe to the smallest garden herbs -- an act of extraordinary halakhic conscientiousness. But this meticulous micro-piety coexists with neglect of judgment (krisis = justice in legal disputes) and the love of God (t&#275;n agap&#275;n tou theou). Jesus does not reject tithing ("these you ought to have done") but insists on proportion.</p>',
'43': '<p>"Woe to you Pharisees, because you love the most important seats in the synagogues and respectful greetings in the marketplaces" -- the second woe addresses the honor-seeking that accompanies religious practice. "Most important seats" (protocathedrias = the seats at the front facing the congregation) were reserved for honored members of the community; the synagogue scroll was read facing the congregation, so the front seats had the most visibility. "Respectful greetings in the marketplaces" (aspassmous en tais agorais) were public acts of honor -- being addressed by title and being publicly acknowledged by important people. The desire for these honors turns religious practice into a mechanism of social status.</p>',
'44': '<p>"Woe to you, because you are like unmarked graves, which people walk over without knowing it" -- contact with a grave caused seven days of ritual uncleanness (Num 19:16: "anyone who touches a human bone or a grave will be unclean for seven days"; m. Oholot 2:1-4). To protect people from unknowingly contracting this impurity, graves were whitewashed (Matt 23:27: "whitewashed tombs") so they could be avoided. An unmarked grave was the most dangerous kind: people walked over it without knowing they were contracting uncleanness. The Pharisees, Jesus says, are like such graves: they look harmless but spread the uncleanness of their hidden corruption to those who unknowingly encounter them.</p>',
'45': '<p>A lawyer (nomikos = expert in the Jewish law, an interpreter and teacher) objects: "Teacher, when you say these things, you insult us also." The lawyers and Pharisees were distinct groups: the Pharisees were a lay piety movement; the lawyers/scribes (grammateis/nomikoi) were professional legal experts who could be Pharisees, Sadducees, or independent. The lawyer correctly recognizes that the woes apply to his profession as well as to the Pharisees\' party.</p>',
'46': '<p>"And you experts in the law, woe to you, because you load people down with burdens they can hardly carry, and you yourselves will not lift one finger to help them" -- the first woe against lawyers addresses the expansion of legal obligations. The "burdens" (phortia = loads, burdens) refer to the rabbinic expansion of the 613 biblical commandments through the "fence around the Torah" (m. Avot 1:1: "make a fence around the Torah"), which added protective interpretations to prevent even approaching the boundaries of the law. These extensions, however, fell most heavily on ordinary people who lacked the rabbinic training to navigate them. The lawyers\' failure to "lift one finger" may contrast with Jesus\' finger-of-God (v.20) that brings liberation.</p>',
'47': '<p>"Woe to you, because you build tombs for the prophets, and it was your ancestors who killed them" -- the second woe against lawyers addresses the monument-building for the murdered prophets. Archaeological evidence for elaborate prophets\' tombs exists: the tombs of Zechariah, Absalom, and Jehoshaphat in the Kidron Valley were prominent first-century monuments. The combination of building their tombs while repeating their murders is the deep irony: the same religious establishment that honors the prophets of the past persecutes the prophets of the present, just as their ancestors did.</p>',
'48': '<p>"So you testify that you approve of what your ancestors did; they killed the prophets, and you build their tombs" -- the testimony (martyres este = you are witnesses) is ironic: the tomb-building is intended to honor, but it functions as ongoing endorsement of the pattern of killing and then memorializing. The principle: those who inherit the fruits of violence without repudiating the violence share in its guilt. This is the logic of the OT prophets (Ezek 23; Matt 23:30-31) who connected the present generation to the long history of resistance to God\'s messengers.</p>',
'49': '<p>"Because of this, God in his wisdom said, \'I will send them prophets and apostles, some of whom they will kill and others they will persecute\'" -- the citation "God in his wisdom said" introduces a saying without a direct OT parallel; it may reflect a lost wisdom text, an interpretation of Prov 9:1-6, or the personified Wisdom who speaks throughout the wisdom tradition (Wis 7-9; Prov 8). The pattern of sending prophets and apostles to be killed recapitulates the whole OT history of prophetic rejection (Neh 9:26; Jer 7:25-26; 2 Chr 36:15-16).</p>',
'50': '<p>"Therefore this generation will be held responsible for the blood of all the prophets that has been shed since the beginning of the world" -- the cumulative guilt principle: the rejection of Jesus is the capstone of a pattern of prophetic rejection that stretches from "the beginning of the world." Abel is the first innocent blood shed (Gen 4:8-10); Zechariah son of Berekiah (or son of Jehoiada, 2 Chr 24:20-22) is the last in the Hebrew canon (Chronicles was the final book in the Hebrew arrangement). "From the blood of Abel to the blood of Zechariah" spans the entire canonical narrative of prophetic martyrdom.</p>',
'51': '<p>"From the blood of Abel to the blood of Zechariah, who was killed between the altar and the sanctuary" -- Abel\'s blood "cries out from the ground" (Gen 4:10); Zechariah son of Jehoiada was "stoned in the court of the temple of the Lord" (2 Chr 24:21). The two murders bracket the entire Hebrew canon (Genesis-Chronicles in the Hebrew order) as the first and last recorded instances of innocent blood. The phrase "this generation will be held responsible" (ekz&#275;t&#275;th&#275;setai apo t&#275;s geneas taut&#275;s) echoes Gen 9:5: "I will surely demand an accounting" -- the same divine demand for blood-reckoning applied to the whole pattern.</p>',
'52': '<p>"Woe to you experts in the law, because you have taken away the key of knowledge. You yourselves have not entered, and you have hindered those who were entering" -- the third woe against lawyers addresses their monopoly on and subversion of the knowledge of God. The "key of knowledge" (tēn kleid&#257; t&#275;s gn&#333;se&#333;s) is the interpretive expertise that should open access to the Scripture\'s meaning and to God. The lawyers have "taken away" (&#275;rate = removed, carried off) this key: their interpretations have not illuminated the Scripture but obscured it, preventing both themselves and others from entering. The Rabbinical successors of these lawyers will be accused of burying the messianic prophecies under layers of inapplicable interpretation.</p>',
'53': '<p>"When Jesus went outside, the Pharisees and the teachers of the law began to oppose him fiercely and to besiege him with questions" -- the escalation of opposition after the woes is expected. "Oppose him fiercely" (deinōs enechein = to hold violently against, to be furiously hostile) -- the intensity of the reaction matches the severity of the woes. "Besiege him with questions" (apostomatizein = to cause someone to speak from memory, to question exhaustively -- possibly to catch him in a contradiction that could be used against him). The legal questioning is an attempt at entrapment.</p>',
'54': '<p>"Waiting to catch him in something he might say" -- the trap-laying strategy (enedrenontes = lying in ambush; th&#275;reusai = to hunt, to trap) is legal-political strategy: if they can get Jesus to say something blasphemous, politically dangerous, or halakhically indefensible, they have grounds for action. The same strategy appears in the temple controversies of chapter 20 (the tribute question, the resurrection question, the David\'s Son question). Luke\'s framing of this opposition as ambush and hunting reveals the murderous intent behind the religious questioning.</p>',
}
}

def main():
    existing = load_comm('mkt-context', 'luke')
    merge_comm(existing, NEW)
    save_comm('mkt-context', 'luke', existing)
    import json as _json, pathlib as _pl
    inter = _json.loads((_pl.Path(__file__).parent.parent / 'data/interlinear/luke.json').read_text())
    for ch in [10, 11]:
        ck = str(ch)
        have = set(existing.get(ck, {}).keys())
        need = set(inter.get(ck, {}).keys())
        missing = sorted(int(v) for v in (need - have))
        print(f'  ch{ch}: {len(have)}/{len(need)} -- missing: {missing}')

if __name__ == '__main__':
    main()
