"""
mkt-context layer — Colossians chapters 1–4 (full coverage)
Output: data/commentary/mkt-context/colossians.json
Run: python3 scripts/zc-context-colossians-1-4-full.py

Context spine: Colossae as a Lycus Valley wool-trading city; Epaphras as
founder; the Colossian 'philosophy' (2:8) combining angel veneration,
stoicheia cosmology, Jewish calendar observance, and asceticism; household
codes (Haustafeln) in Greco-Roman moral philosophy; letter-network with
Laodicea; Paul imprisoned (Rome or Ephesus); slave/free social reality.
"""
import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    # INTENT: Merge new verse entries without overwriting already-present keys — safe to re-run.
    # CHANGE? If commentary JSON structure changes from {ch:{v:html}}, update this traversal.
    # VERIFY: Re-running the script should produce identical output.
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

NEW = {
  "1": {
    "1": "Paul, an apostle of Christ Jesus by the will of God, and Timothy our brother — the letter's prison origin (4:3, 10, 18) most likely places it in Rome (ca. 60-62 CE) or Ephesus (ca. 54-55 CE). Colossae was a city Paul did not personally found (2:1) nor apparently ever visit; the church arose through Epaphras during Paul's Ephesian ministry.",
    "3": "We always thank God, the Father of our Lord Jesus Christ, when we pray for you — the formal thanksgiving period follows Greco-Roman epistolary convention. Ancient letters routinely opened with health wishes and gratitude to the gods; Paul transforms this convention with a christological prayer of thanksgiving.",
    "4": "Since we heard of your faith in Christ Jesus and of the love that you have for all the saints — the report reached Paul through Epaphras (1:7-8). Communication across the Roman empire flowed through personal messengers; Epaphras carried news of the Colossian congregation to the imprisoned apostle.",
    "5": "Because of the hope laid up for you in heaven — the three-part formula faith/love/hope echoes 1 Cor 13:13 and 1 Thess 1:3. The gospel of truth you heard before is distinguished from the deviant teaching the letter addresses; the chronological priority of the authentic gospel is the argument against the newer philosophy.",
    "6": "The gospel, which has come to you, as indeed in the whole world it is bearing fruit and increasing — the world-wide scope (oikoumenē) of gospel advance is an implicit argument against the local Colossian philosophy: the gospel is not a regional peculiarity but a universal movement. Bearing fruit (karpophoroun) echoes agricultural language common in Greek moral philosophy.",
    "7": "Just as you learned it from Epaphras our beloved fellow servant — Epaphras (Epaphroditus is likely a longer form) is described as a faithful minister of Christ on your behalf (hyper hymōn) — suggesting he was a Colossian native who carried the gospel back to his home region during Paul's Ephesian period (Acts 19). He is also mentioned in Phm 23 as Paul's fellow prisoner.",
    "8": "Who has made known to us your love in the Spirit — the love in the Spirit is the Spirit's own gift producing communal affection (Gal 5:22: love is the fruit of the Spirit). Epaphras's report is the communication link between the imprisoned Paul and the distant congregation.",
    "9": "From the day we heard, we have not ceased to pray for you, asking that you may be filled with the knowledge of his will in all spiritual wisdom and understanding — epignōsis (full knowledge) and sophia (wisdom) are terms the Colossian false teaching apparently claimed to provide (2:3: in Christ are hidden all the treasures of wisdom and knowledge — a response to that claim).",
    "10": "So as to walk in a manner worthy of the Lord, fully pleasing to him, bearing fruit in every good work — the peripatetic (walking) metaphor for moral conduct was standard in both Jewish (Heb: halakah from hlk, to walk) and Hellenistic moral philosophy. The Stoics spoke of the sage as one who walks according to nature; Paul speaks of walking according to the Lord.",
    "11": "Being strengthened with all power, according to his glorious might, for all endurance and patience with joy — the language of power (dynamis, kratos, ischus) in vv.11-12 evokes the cosmological power-vocabulary of the Colossian philosophy which assigned cosmic powers to angelic hierarchies. Paul's counter-claim: the power available to believers exceeds anything the angelic powers provide.",
    "12": "Giving thanks to the Father, who has qualified you to share in the inheritance of the saints in light — the inheritance of the saints (klēros tōn hagiōn) echoes the Deuteronomic land-inheritance language of Israel (Deut 32:9: YHWH's portion is his people, Jacob his allotted heritage). Paul applies this OT inheritance category to the new covenant community's participation in the divine light.",
    "13": "He has delivered us from the domain of darkness and transferred us to the kingdom of his beloved Son — the transfer (metestēsen) is a technical term for the deportation of a conquered population to a new territory. Antiochus IV deported Israelites; Rome deported conquered peoples. Paul applies the imperial deportation vocabulary to the spiritual transfer from darkness to Christ's kingdom — a counter-imperial use of the language.",
    "14": "In whom we have redemption, the forgiveness of sins — apolytrōsis (redemption, release by ransom) was the term for the legal liberation of a slave or prisoner through the payment of a purchase price (lytron). The redemption of slaves was a common social institution in the Roman world; Paul's use of the term places the liberation from sin in that framework.",
    "15": "He is the image of the invisible God, the firstborn of all creation — the Colossian hymn (1:15-20) likely draws on Jewish Wisdom speculation (Wisdom of Solomon 7:26: wisdom is the image of his goodness; Philo, Leg. All. 1.43: the Logos is the image of God). The firstborn (prōtotokos) denotes priority and preeminence over creation, not membership in it.",
    "17": "And he is before all things, and in him all things hold together — the pre-existence claim and the sustaining function of the divine Logos were both present in Hellenistic Jewish theology (Philo, Cher. 27: the Logos holds together and holds up all things). Paul applies the Logos-function directly to the personal Christ.",
    "18": "And he is the head of the body, the church — in Stoic philosophy, the cosmos itself was conceived as a body with a head (kephalē, the logos or divine reason that governed it). Paul applies the body-head metaphor to Christ and the church, countering the Stoic cosmological model with a christological ecclesiological one.",
    "19": "For in him all the fullness (plērōma) was pleased to dwell — plērōma (fullness, totality) was a technical term in later Gnosticism for the totality of divine attributes distributed among a hierarchy of aeons. If proto-Gnostic speculation is already influencing the Colossian philosophy, Paul's counter-claim is that the entire divine fullness — not a portion — dwells in Christ alone.",
    "20": "And through him to reconcile to himself all things, whether on earth or in heaven — the cosmic scope of the reconciliation (panta — all things; en tois ouranois — in the heavens) responds to the Colossian interest in heavenly powers. If the angelic powers are a concern, Paul's answer is that Christ's reconciling work encompasses them.",
    "21": "And you, who once were alienated and hostile in mind, doing evil deeds — the Colossians' pre-conversion state is described in the standard Pauline contrast between former alienation (apallotrioō — to be estranged, a legal term for exclusion from a community) and present reconciliation. This Gentile alienation from God is a standard Jewish description of the pagan condition.",
    "22": "He has now reconciled in his body of flesh by his death — the specificity of the incarnate body (sōma tēs sarkos) and physical death (thanatos) is significant: the Colossian philosophy may have minimized or spiritualized the incarnation. Paul insists the reconciliation was effected through actual physical flesh and actual death.",
    "23": "If indeed you continue in the faith, stable and steadfast, not shifting from the hope of the gospel that you heard — the conditional warning: the gospel's benefits accrue to those who remain in it. The Colossian philosophy represented a deviation from the received gospel; stability in the original gospel is the protection.",
    "24": "I am now rejoicing in my sufferings for your sake, and in my flesh I am completing what is lacking in Christ's afflictions — the phrase filling up (antanaplēroō) what is lacking (ta hysterēmata) in Christ's afflictions has generated enormous commentary. The most probable interpretation: the Messiah's ordained suffering (the messianic woes of Jewish apocalyptic thought — 1QH, 2 Bar.) has a fixed measure; Paul participates in completing that measure through apostolic suffering, not supplementing the atonement.",
    "25": "Of which I became a minister according to the stewardship (oikonomia) from God that was given to me for you — oikonomia (household management, stewardship) was the term for the management of a household by its administrator. Applied to Paul, it denotes his commissioned management of the divine mystery; the letter applies it to his Gentile mission (Eph 3:2-3).",
    "26": "The mystery hidden for ages and generations but now revealed to his saints — the apocalyptic category of mystery (mystērion) refers to a divine secret that has been hidden in the divine counsel and is now disclosed through revelation. Daniel uses this language (Dan 2:19, 27-30, 47: the mystery of the king's dream revealed to Daniel). The mystery of the Gentiles' inclusion is Paul's specific application.",
    "27": "To them God chose to make known how great among the Gentiles are the riches of the glory of this mystery, which is Christ in you, the hope of glory — Christ in you (Christos en hymin) is the Colossian congregation's specific articulation of what 'Christ in me' meant for Paul (Gal 2:20). The indwelling Christ is Paul's answer to the Colossian philosophy's offer of spiritual fullness through angelic intermediaries.",
    "28": "Him we proclaim, warning everyone and teaching everyone with all wisdom — the three-part apostolic ministry: proclaiming (katangelomen), warning (nouthetountes), teaching (didaskontes). The repetition of everyone (panta anthrōpon) three times in vv.28-29 emphasizes the universal scope of the mission — no special elite, no inner circle, no graduated levels of initiation as mystery religion or Gnostic teaching offered.",
    "29": "For this I toil, struggling with all his energy that he powerfully works within me — the energy vocabulary (kopiaō, agōnizomai, energeia, energeō) echoes athletic and gladiatorial contest language. The apostolic struggle is energized by Christ's own power working within Paul — the same power that raised him from the dead.",
  },
  "2": {
    "1": "For I want you to know how great a struggle I have for you and for those at Laodicea — the Lycus Valley cluster: Colossae, Laodicea (about 18 km west), and Hierapolis (about 6 km north of Laodicea) formed a geographical and ecclesiastical triangle. Laodicea was the larger and more prosperous city; Hierapolis was known for its hot springs and healing cult (Acts 19:10 suggests the whole region was evangelized from Ephesus).",
    "2": "That their hearts may be encouraged, being knit together in love — symbibaō (knit together, united) was a medical term for the setting of bones and the binding of a community. Plutarch and other Greek authors used it for civic unity. The love that knits the congregation together is the counter to the philosophical teaching that threatened to fragment it.",
    "3": "In whom are hidden all the treasures of wisdom (sophia) and knowledge (gnōsis) — the language directly responds to what the Colossian philosophy claimed to offer. Mystery religions and philosophical schools competed to provide wisdom and knowledge of hidden divine realities; Paul claims Christ contains all of these without remainder, making any additional source redundant.",
    "4": "I say this in order that no one may delude you with plausible arguments (pithanologia) — pithanologia (persuasive speech, probable reasoning) was a technical term in Hellenistic rhetoric for arguments that seem probable without being demonstrably true. The Sophists were accused of pithanologia by philosophers who valued truth over persuasion. Paul warns that the Colossian philosophy uses rhetorical skill to compensate for theological error.",
    "5": "For though I am absent in body, yet I am with you in spirit, rejoicing to see your good order (taxin) and the firmness of your faith in Christ — taxis (order, formation) and stereōma (firmness, solid footing) are military terms. A body of troops in good order, maintaining its solid formation, was the Roman military ideal. Paul applies the military language to the congregation's doctrinal stability.",
    "6": "Therefore, as you received Christ Jesus the Lord, so walk in him — the reception (paralambanō) of tradition is a technical term in both rabbinic (qibbel — received) and Greek educational practice for the transmission of authoritative teaching from teacher to student. The Colossians received the gospel tradition from Epaphras; Paul appeals to that received teaching as the standard.",
    "7": "Rooted and built up in him and established in the faith, just as you were taught — the mixed metaphor of rooting (rhizoō — agricultural) and building up (epoikodomeō — construction) reflects the composite image of 1 Cor 3:9 (God's field, God's building). Being established (bebaiouō) was used for the legal confirmation of a deed or contract.",
    "9": "For in him the whole fullness (plērōma) of deity dwells bodily — sōmatikōs (bodily, in bodily form) is the word that distinguishes Paul's answer from any Gnostic or proto-Gnostic alternative. The divine fullness is not distributed among spiritual intermediaries or accessed through mystical ascent but concentrated in the specific, physical, crucified, and risen body of Jesus.",
    "10": "And you have been filled in him, who is the head of all rule and authority — peplērōmenoi (you have been filled, you are complete) is the counter to any teaching that suggests the Colossians lack something and need additional spiritual resources from the angelic powers. In Christ they are already complete; in him the angelic authorities find their head.",
    "11": "In him also you were circumcised with a circumcision made without hands, by putting off the body of the flesh — the circumcision debate appears throughout the Pauline letters. The Colossian philosophy may have included Jewish elements including circumcision observance. Paul's response: the true circumcision is not physical but the Spirit's work of removing the flesh-nature.",
    "12": "Having been buried with him in baptism, in which you were also raised with him through faith in the powerful working of God — baptismal death and resurrection is Paul's answer to the question of how the believer participates in Christ's death and resurrection. The language echoes mystery religion initiation (Apuleius, Metamorphoses XI: the initiate into the Isis mysteries passes through death), but Paul's content is specifically christological.",
    "13": "And you, who were dead in your trespasses and the uncircumcision of your flesh, God made alive together with him — the Colossians as Gentiles are described as uncircumcised (akrobystia tēs sarkos — the foreskin of the flesh), the classic Jewish marker of Gentile exclusion from the covenant. God's making-alive collapses the circumcision/uncircumcision distinction.",
    "14": "By canceling the record of debt (cheirographon) that stood against us with its legal demands — cheirographon (handwritten bond, IOU) was used in Hellenistic papyri for a personal acknowledgment of debt: the debtor's own signature on a document stating what was owed. The canceled cheirographon nailed to the cross is an image drawn from actual Roman legal and financial practice.",
    "15": "He disarmed the rulers and authorities and put them to open shame — apekdysamenos (having stripped, having disarmed) — the image of stripping defeated enemies of their weapons and armor was standard in Roman triumphal imagery. Defeated barbarian chieftains were paraded through Rome stripped of their weapons and regalia. The cross is the paradoxical triumph in which the apparently defeated Christ actually disarms his opponents.",
    "16": "Therefore let no one pass judgment on you in questions of food and drink, or with regard to a festival or a new moon or a Sabbath — the specific practices listed (food/drink restrictions, festival calendar, new moons, sabbaths) reflect Jewish religious practice as observed in diaspora synagogues. The Colossian philosophy apparently incorporated these Jewish observances as part of its program, possibly as requirements for accessing higher spiritual realities.",
    "17": "These are a shadow (skia) of the things to come, but the substance belongs to Christ — the shadow/substance (skia/sōma — literally shadow/body) contrast was used in Platonic philosophy for the relationship between the sensible world (shadow) and the intelligible world (the real). Paul applies it differently: the Mosaic practices are the shadow; Christ is the substance they foreshadow. The real/shadow language is reversed from Platonism: the material (Christ's body) is more real than the abstract shadow.",
    "18": "Let no one disqualify you, insisting on asceticism (tapeinophrosynē — humility/self-abasement) and worship of angels — threskeia tōn angelōn (worship/veneration of angels) is one of the most debated phrases in the letter. It may denote: (1) worship offered to angels; (2) worship practiced by angels (the heavenly liturgy which initiates claimed to join); or (3) angel-mediated worship of God. The Dead Sea Scrolls' Songs of the Sabbath Sacrifice describe participation in the angels' heavenly worship — this type of Jewish mystical tradition may be the background.",
    "19": "And not holding fast to the Head, from whom the whole body, nourished and knit together through its joints and ligaments, grows — the body-head physiology reflects Greco-Roman medical knowledge. Galen and other medical writers described the body's unified function as governed by the head through pneuma (spirit/breath) flowing through the nerves. Paul applies the medical model to Christ and the church.",
    "20": "If with Christ you died to the elemental spirits (stoicheia) of the world, why, as if you were still alive in the world, do you submit to regulations? — stoicheia tou kosmou (elemental principles/spirits of the world) is the letter's most debated term. Options: (1) the ABCs — basic elementary principles; (2) the four physical elements (earth, water, fire, air); (3) the spiritual powers associated with the cosmos (stars, planets, elemental spirits). The Galatian parallel (Gal 4:3, 9) associates stoicheia with the Mosaic law and pre-Christian religious observance — here likely the powers that enforced the old religious order now superseded in Christ.",
    "21": "Do not handle, do not taste, do not touch — the three prohibitions (mē hapsē, mē geuō, mē thigēs) reflect the ascetic regulations of the Colossian philosophy. The clustering of three short prohibitions reflects a catechetical or regulatory style similar to Pythagorean taboo-lists and some Dead Sea Scrolls sectarian rules.",
    "22": "Referring to things that all perish as they are used — according to human precepts and teachings — the distinction between divine commands and human traditions (paradoseis and didaskalia tōn anthrōpōn) echoes Jesus's critique of Pharisaic halakah (Mark 7:7-8: in vain do they worship me, teaching as doctrines the commandments of men). Paul applies the same critique to the Colossian philosophy.",
    "23": "These have indeed an appearance (logon) of wisdom in promoting self-made religion (ethelothreskia) and asceticism and severity to the body — ethelothreskia (self-chosen/voluntary worship/religion) is a hapax legomenon in the NT and rare in Greek generally. The self-chosen quality distinguishes it from divinely commanded worship: it is religiously impressive but not God-ordained. Severity to the body (apheidia sōmatos) describes harsh ascetic treatment that was common in various philosophical schools (Pythagoreans, some Cynics) and mystery religion initiation.",
  },
  "3": {
    "1": "If then you have been raised with Christ, seek the things that are above (ta anō), where Christ is, seated at the right hand of God — the upward orientation (ta anō — the above things) responds to the Colossian philosophy's interest in heavenly realities. Rather than spiritual ascent through mystical practice and angelic veneration, Paul reorients the upward gaze toward the risen and enthroned Christ.",
    "2": "Set your minds on things that are above, not on things that are on earth — the contrast between the heavenly (epouranios) and the earthly (epigeios) reflects standard Platonic dualism — but Paul transforms it: the heavenly is not an abstract realm of ideas but the specific place where the risen Christ is enthroned. The Platonic framework is adopted and christologically redefined.",
    "3": "For you have died, and your life is hidden with Christ in God — the hiddenness (kekryptai — perfect passive: is and remains hidden) of the believer's life in the divine reality corresponds to the apocalyptic concept of the hidden things that will be revealed at the end. The believer's true identity is eschatologically concealed until the parousia.",
    "4": "When Christ who is your life appears, then you also will appear with him in glory — the parousia (appearing, coming) as the moment of eschatological disclosure. The glory (doxa) is the Shekinah-glory that characterized YHWH's presence in the OT and that will characterize the final revelation of the redeemed. Christ's appearing is simultaneously the community's appearing.",
    "5": "Put to death therefore what is earthly in you: sexual immorality, impurity, passion, evil desire, and covetousness, which is idolatry — the vice list (porneia, akatharsia, pathos, epithymia kakē, pleonexia) is a standard form in Hellenistic Jewish moral teaching (the Two Ways literature, the Testaments of the Twelve Patriarchs) adapted to describe the Gentile condition. Covetousness as idolatry appears in Eph 5:5 and reflects the Jewish understanding that all sin is ultimately the worship of something other than God.",
    "6": "On account of these the wrath of God is coming — the divine wrath (orgē theou) as the eschatological consequence of idolatry reflects both OT prophetic tradition (Isa 13:11; Jer 25:15-16) and Jewish apocalyptic (1 Enoch 91:9; Rom 1:18). The coming wrath sets the ethical urgency of vv.5-17.",
    "7": "In these you too once walked, when you were living in them — the once/now schema (pote/nyn) is Paul's standard conversion narrative structure. The Colossians' Gentile past was marked by these vices; their present is defined by Christ's death and resurrection (3:1-4). The narrative contrast motivates the ethical imperative.",
    "8": "But now you must put them all away: anger, wrath, malice, slander, and obscene talk from your mouth — the second vice list (orgē, thymos, kakia, blasphēmia, aischrologia) focuses on relational and verbal sins that disrupt community. The distinction between the two lists: vv.5 addresses vices primarily regarding God and self; v.8 addresses vices primarily regarding others in community.",
    "9": "Do not lie to one another, seeing that you have put off the old self (ton palaion anthrōpon) with its practices — the old self/new self (palaios anthrōpos/kainos anthrōpos) contrast reflects the Adam-typology: the old self is the Adam-pattern of existence under sin and death (Rom 5:12-21); the new self is the Christ-pattern of existence in righteousness and life.",
    "10": "And have put on the new self, which is being renewed in knowledge after the image of its creator — the image of God (eikōn tou ktisantos) echoes Genesis 1:26-27: humanity created in the image of God, which image was damaged in the Fall and is now restored in the new creation. The knowledge (epignōsis) in which renewal occurs is the relational knowledge of God in Christ.",
    "11": "Here there is not Greek and Jew, circumcised and uncircumcised, barbarian, Scythian, slave, free; but Christ is all, and in all — the social categories being dissolved reflect the hierarchies of the Greco-Roman world: Greek/barbarian was the fundamental cultural distinction (Greeks were civilized; barbarians were those who could not speak Greek properly); Scythian was the extreme example of barbaric — the wild steppe peoples beyond the civilized world; slave/free was the fundamental social and legal distinction.",
    "12": "Put on then, as God's chosen ones (eklektoi), holy and beloved, compassionate hearts, kindness, humility, meekness, and patience — the virtue list (splagchna oiktirmou, chrēstotēs, tapeinophrosynē, praütēs, makrothymia) follows the vice lists of vv.5-9. The adoption of eklektoi (chosen, elect) as a descriptor for the Gentile church applies OT Israel's election vocabulary to the new covenant community.",
    "13": "Bearing with one another and, if one has a complaint against another, forgiving each other; as the Lord has forgiven you, so you also must forgive — the practice of communal forgiveness was formalized in the Lord's Prayer tradition (Matt 6:12, 14-15) and the Matthew 18 community discipline procedure. The Lord's forgiveness as the model and ground of communal forgiveness reflects the covenant pattern.",
    "14": "And above all these put on love (agapēn), which binds everything together in perfect harmony (syndesmos tēs teleiotētos) — the syndesmos (binding ligament, bond) that holds the virtues together is love. The perfection (teleiotēs) that love produces reflects both Stoic and Platonic ideals of virtue-unity: the virtues form a unified whole. Paul's specific Christian content: the binding agent is love, not logos or reason.",
    "15": "And let the peace of Christ rule (brabeuetō) in your hearts, to which indeed you were called in one body — brabeuō (to umpire, to act as arbitrator, to rule as judge of a contest) was used for the official who awarded the prize in athletic games. The peace of Christ as the umpire/arbitrator of community disputes is a uniquely Pauline image for conflict resolution.",
    "16": "Let the word of Christ dwell in you richly, teaching and admonishing one another in all wisdom, singing psalms and hymns and spiritual songs — the threefold musical division (psalmos, hymnos, ōdē pneumatikē) reflects the actual diversity of early Christian song-practice. Psalms were the OT Psalter; hymns may have been christological pieces like Phil 2:6-11 or Col 1:15-20; spiritual songs were spontaneous or prophetic compositions.",
    "17": "And whatever you do, in word or deed, do everything in the name of the Lord Jesus, giving thanks to God the Father through him — the all-encompassing scope (pan hoti ean poiēte — whatever you do) reflects the Stoic ideal of the logos governing all human activity. Paul christologically concretizes this: all activity is to be done in the name of the Lord Jesus.",
    "18": "Wives, submit to your husbands, as is fitting in the Lord — the household code (Haustafeln) in 3:18-4:1 follows a form found in Aristotle (Politics 1253b: the household's three pairs — husband/wife, father/children, master/slave) and developed by Hellenistic Jewish writers (Josephus, Philo) and Stoic moralists. Paul's version is Christianized by the repeated qualifier in the Lord/to the Lord.",
    "19": "Husbands, love your wives, and do not be harsh with them — the reciprocal obligation placed on husbands is significant: Greco-Roman household codes typically focused on the duties of the subordinate party. By commanding husbands to love and not be harsh, Paul inserts the mutual obligation that the conventional codes did not require of the dominant party.",
    "20": "Children, obey your parents in everything, for this pleases the Lord — the fifth commandment (Exod 20:12; Deut 5:16) had a standard interpretation in both Jewish and Greco-Roman tradition. Philo wrote extensive commentary on it; Aristotle included parent/child relations in his household discussions. Paul's addition: this pleases the Lord — a distinctively theological motivation absent from secular household codes.",
    "21": "Fathers, do not provoke your children, lest they become discouraged — the reciprocal obligation to fathers: patria potestas (the father's legal authority over his household in Roman law) was nearly absolute, extending to the power of life and death. Paul limits this power by commanding fathers to avoid provoking children — a striking qualification of Roman paternal authority.",
    "22": "Bondservants (douloi), obey in everything those who are your earthly masters (kata sarka kyriois) — the slave instructions occupy the most space in the household code (3:22-4:1), reflecting the social reality that many Colossian believers were slaves. The qualifier kata sarka (fleshly, earthly) distinguishes the human master from the divine kyrios (Lord) who is Christ.",
    "23": "Whatever you do, work heartily, as for the Lord and not for men — the working-for-the-Lord motivation transforms the slave's labor from coerced servitude into an act of worship. This was not a liberation theology in the modern sense — Paul did not call for the abolition of slavery — but it was a radical reframing of the slave's inner relationship to his work.",
    "24": "Knowing that from the Lord you will receive the inheritance as your reward — the inheritance (klēronomia) language applied to slaves was countercultural: slaves had no right to inheritance in Roman law. Paul tells the slave-believer that the divine inheritance awaits them — a cosmic reversal of their legal status.",
    "25": "For the wrongdoer will be paid back for the wrong he has done, and there is no partiality — the divine impartiality (prosōpolēmpsias — face-receiving, favoritism) is a standard Jewish and Jewish-Christian principle (Deut 10:17; Acts 10:34; Rom 2:11). The warning applies to all parties in the household code: the slave who wrongs will face divine judgment regardless of social status.",
  },
  "4": {
    "1": "Masters, treat your bondservants justly and fairly (to dikaion kai tēn isotēta — the just and the equal), knowing that you also have a Master in heaven — isotēs (equality, fairness) was a concept from Greek political philosophy (Thucydides, Aristotle) and Roman legal tradition. The command to treat slaves with equity was not conventional — Roman law gave masters near-total authority. The heavenly Master who holds earthly masters accountable relativizes all human authority structures.",
    "2": "Continue steadfastly in prayer, being watchful in it with thanksgiving — the combination of prayer (proseuche), watchfulness (grēgorountes), and thanksgiving (eucharistia) reflects the early Christian prayer tradition. Watchfulness in prayer is associated with eschatological alertness in the gospel tradition (Mark 13:33; 14:38: watch and pray that you may not enter into temptation).",
    "3": "And pray for us also, that God may open to us a door for the word, to declare the mystery of Christ, on account of which I am in prison — the open-door metaphor for missionary opportunity appears in 1 Cor 16:9 and 2 Cor 2:12. The mystery of Christ (mystērion tou Christou) is the Gentile-inclusion gospel that Paul was commissioned to proclaim (1:27; Eph 3:3-6) and for which his imprisonment (desmois — bonds) is the consequence.",
    "4": "That I may make it clear, which is how I ought to speak — the clarity (phanerōsō, to make manifest) Paul seeks stands in contrast to the obscurity that the Colossian philosophy cultivated. Mystery religion and philosophical schools often prized esoteric knowledge accessible only to initiates; Paul's gospel is to be proclaimed openly.",
    "5": "Walk in wisdom (sophia) toward outsiders (tois exō), making the best use of the time (ton kairon exagorazomenoi) — the outsiders (hoi exō — those outside) was a standard Pauline designation for non-Christians (1 Cor 5:12-13; 1 Thess 4:12). The time-buying (exagorazō ton kairon — redeeming the time) echoes the commercial language of purchasing time in the marketplace and reflects the urgency of the eschatological moment.",
    "6": "Let your speech always be gracious, seasoned with salt, so that you may know how you ought to answer each person — salt as a flavoring and preservative was essential in ancient Mediterranean life. As a metaphor for speech, it appears in rabbinic literature (speech should be flavored with salt-like wisdom, Abot R. Nathan 34). Salt also carried covenantal significance (Num 18:19; 2 Chr 13:5: covenant of salt). Knowing how to answer each person reflects the rhetorical ideal of the skilled orator who adapts his speech to each audience.",
    "7": "Tychicus will tell you all about my activities. He is a beloved brother and faithful minister and fellow servant in the Lord — Tychicus (from Tychos, meaning luck/fortune — a common Greek name) appears as Paul's emissary in Eph 6:21 and 2 Tim 4:12, suggesting he was a regular carrier of Pauline correspondence. He is probably the letter-carrier for both Colossians and Ephesians.",
    "8": "I have sent him to you for this very purpose, that you may know how we are and that he may encourage your hearts — the letter-carrier in antiquity was not merely a postal delivery mechanism but an authoritative representative who could amplify and explain the letter's content verbally. Tychicus carries both the written letter and the authority to interpret and extend it.",
    "9": "And with him Onesimus, our faithful and beloved brother, who is one of you — Onesimus is the slave of Philemon (Phm 10-16) whom Paul is sending back to his master with the accompanying letter to Philemon. His identification as one of you (ek hymōn — from among you) identifies him as a Colossian. The two letters — Colossians and Philemon — are companion pieces sent with the same delegation.",
    "10": "Aristarchus my fellow prisoner greets you, and Mark the cousin of Barnabas — Aristarchus the Macedonian (from Thessalonica, Acts 20:4; 27:2) is Paul's companion from the third missionary journey. The cousin (anepsios) relationship between Barnabas and Mark (John Mark of Acts 12:12) establishes the Jerusalem connection. The split between Paul and Barnabas over Mark (Acts 15:37-39) has apparently been healed by the time of Colossians.",
    "11": "Jesus who is called Justus — this otherwise unattested believer with the Jewish name Jesus (Yeshua) and the Latin cognomen Justus (the Just) represents the Jewish-Christian tradition. His Jewish-Roman dual naming was common in the diaspora. These three are the only Jews among my fellow workers for the kingdom of God — underscoring that Paul's co-workers at the time were predominantly Gentile.",
    "12": "Epaphras, who is one of you, a servant of Christ Jesus, greets you, always struggling on your behalf in his prayers — Epaphras (1:7) is the Colossian-born founder of the congregation. His prayer struggle (agōnizomai — competing in an athletic contest) for the Colossians mirrors Paul's own apostolic struggle (1:29). The word is used of Gethsemane (Luke 22:44: agōnia — wrestling) and athletic competition (1 Cor 9:25).",
    "13": "For I bear him witness that he has worked hard for you and for those in Laodicea and in Hierapolis — the three Lycus Valley cities form Epaphras's pastoral field. Hierapolis (modern Pamukkale) was known for its spectacular travertine terraces from hot springs and its healing shrines; it had a significant Jewish community attested in inscriptions. Paul's apostolic testimony (martyreō) validates Epaphras's work.",
    "14": "Luke the beloved physician (ho iatros ho agapētos) greets you — Luke is identified as a physician only here in the NT. His medical profession is consistent with the technical precision of some medical descriptions in Luke-Acts (the woman with a hemorrhage, Luke 8:43-44; the ear of the high priest's servant, Luke 22:51). Demas greets you — Demas later abandoned Paul (2 Tim 4:10: Demas, in love with this present world, has deserted me).",
    "15": "Give my greetings to the brothers at Laodicea, and to Nympha and the church in her house — the house church (ekklēsia kat' oikon — church according to the house) was the standard unit of early Christian community. Nympha is a woman hosting a house church in Laodicea — one of several women who hosted early Christian communities (Lydia, Acts 16:15; Priscilla, Rom 16:5; Mary, Acts 12:12; Chloe, 1 Cor 1:11).",
    "16": "And when this letter has been read among you, have it also read in the church of the Laodiceans — the inter-church reading of Paul's letters establishes the foundation for the eventual collection and canonical formation of the Pauline corpus. The Laodiceans letter (hē ek Laodiceias — the one from Laodicea) is now lost, unless it is the canonical Ephesians (which has no addressee in some manuscripts).",
    "17": "And say to Archippus, see that you fulfill the ministry that you have received in the Lord — Archippus is addressed in Phm 2 as Paul's fellow soldier and is apparently a leader in the Colossian/Laodicean community (possibly Philemon's son or a house-church leader). The public charge to fulfill his ministry (diakonia) adds an element of congregational accountability.",
    "18": "I, Paul, write this greeting with my own hand. Remember my chains. Grace be with you — the autograph (the closing greeting in Paul's own handwriting — Gal 6:11; 1 Cor 16:21; 2 Thess 3:17; Phm 19) serves as authentication: the body of the letter was dictated to an amanuensis (secretary), but the closing in Paul's hand vouches for the letter's genuineness. Remember my chains (mnēmoneuete mou tōn desmōn) is a poignant last word from the imprisoned apostle — a request for prayer and solidarity.",
  }
}

if __name__ == '__main__':
    existing = load_comm('mkt-context', 'colossians')
    merge_comm(existing, NEW)
    save_comm('mkt-context', 'colossians', existing)
    for ch in ['1', '2', '3', '4']:
        print(f'  ch {ch}: {len(existing.get(ch, {}))} verses')
