"""
MKT Christ Commentary — Proverbs chapters 19–21
Run: python3 scripts/zc-christ-proverbs-19-21.py

Ch19: Wealth, speech, and social ethics — poverty of the blameless (v1) → Beatitudes;
      v14 prudent wife from YHWH → Christ securing the bride (Eph 5:25-27);
      v17 lending to YHWH → Matt 25:40; v20-21 YHWH's counsel stands → Isa 46:10
Ch20: Commercial integrity and royal justice — v9 (no clean heart) → 1 John 1:8;
      v27 spirit as YHWH's lamp → John 1:4; v28 ḥesed/ʾěmet guard king → John 1:14;
      v22 do not repay evil → Rom 12:17-19; v24 steps from YHWH → Heb 12:2
Ch21: Divine sovereignty — v1 king's heart as water → Isa 45:1 / John 19:11;
      v3 justice > sacrifice → Matt 9:13; v21 pursue righteousness → Matt 5:6;
      v30 no wisdom against YHWH → 1 Cor 1:25; v31 victory from YHWH → Rev 17:14
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(layer, book):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    return json.loads(p.read_text()) if p.exists() else {}

def save_comm(layer, book, data):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

CHRIST = {
  "19": {
    "1": "<p>The blameless poor man superior to the perverse-lipped rich — a Beatitude-anticipating inversion of social evaluation. Matthew 5:3: &ldquo;blessed are the poor in spirit, for theirs is the kingdom of heaven.&rdquo; Christ himself was the blameless poor man (<em>rāš</em> in moral orientation if not material poverty: &ldquo;though he was rich, yet for your sake he became poor,&rdquo; 2 Cor 8:9), and he is the judge who validates the blameless poor over the perverse-wealthy — &ldquo;has not God chosen those who are poor in the world to be rich in faith?&rdquo; (Jas 2:5).</p>",
    "2": "<p>Desire without knowledge and hasty feet — the pairing of zeal unguided by wisdom with destructive speed. Christ is both the knowledge that guides zeal (1 Cor 1:30: &ldquo;Christ Jesus, who became to us wisdom from God&rdquo;) and the one who moved with perfect intentionality: &ldquo;he set his face to go to Jerusalem&rdquo; (Luke 9:51), knowing the hour, the path, and the cost. His zeal was perfectly informed by the Father&rsquo;s will; his feet did not hasten to evil but to redemption.</p>",
    "3": "<p>The man whose folly ruins his way, then rages against YHWH — the self-deceptive psychology of blaming God for one&rsquo;s own choices. Romans 5:8 shows the christological reversal: &ldquo;while we were still sinners, Christ died for us.&rdquo; The one against whom the ruined man rages is the one who, in Christ, absorbs that rage in the crucifixion and still provides redemption. Luke 23:34: &ldquo;Father, forgive them, for they know not what they do&rdquo; — the prayer offered to the God the raging sinner blamed.</p>",
    "4": "<p>Wealth adds friends, poverty loses them — the social mechanics of patron-client dynamics observed without sentimentality. Christ was abandoned by all his disciples at the cross (Matt 26:56: &ldquo;all the disciples left him and fled&rdquo;), experiencing the poverty-abandonment Proverbs describes. Yet in the resurrection he restored the scattered friends: &ldquo;go and tell my brothers&rdquo; (Matt 28:10). His friendship survives the ultimate poverty — death — which no human patron-client bond can match.</p>",
    "5": "<p>The false witness who will not go unpunished. Christ faced false witnesses at his own trial (Matt 26:60-61: &ldquo;at last two came forward and said, &lsquo;This man said, I am able to destroy the temple of God&rsquo;&rdquo;), was condemned on false testimony, and yet will judge all testimony at the last day. Revelation 20:12: &ldquo;the dead were judged by what was written in the books.&rdquo; The one falsely condemned is the judge before whom all false witnesses will stand without escape.</p>",
    "6": "<p>Many seek the favor of a generous man — the patron-seeking of ANE social dynamics. The generosity pattern is ultimately divine: every human generous man is an image of the God who gives to all without reproach (Jas 1:5). Christ is the one toward whom all humanity ultimately runs for favor: &ldquo;everyone who calls on the name of the Lord will be saved&rdquo; (Rom 10:13). The noble/generous one whose favor all seek is the mediator through whom the Father&rsquo;s inexhaustible generosity is accessed.</p>",
    "7": "<p>The poor man abandoned by all his relatives — Christ&rsquo;s experience at the cross. But the resurrection reverses all abandonment: &ldquo;he is not here, for he has risen&rdquo; (Matt 28:6). Christ who was forsaken (Matt 27:46: &ldquo;my God, my God, why have you forsaken me?&rdquo;) becomes the one who will &ldquo;never leave you nor forsake you&rdquo; (Heb 13:5) — the abandoned one who secures that no one who is his will be abandoned.</p>",
    "8": "<p>Acquiring wisdom-heart (<em>lēb</em>) and guarding understanding as love for one&rsquo;s own soul. Christ acquired perfect wisdom through his obedient life: Heb 5:8 — &ldquo;although he was a son, he learned obedience through what he suffered.&rdquo; The wisdom he acquired was not for his own benefit alone but for ours: he &ldquo;became to us wisdom from God, righteousness and sanctification and redemption&rdquo; (1 Cor 1:30), so that his acquired wisdom becomes our imparted gift.</p>",
    "9": "<p>The false witness who perishes (variant of v5). The repetition underscores the absolute certainty of divine justice against false testimony. Acts 5:1-11 (Ananias and Sapphira&rsquo;s instant death for lying to the Spirit) is the NT illustration of the perishing false witness. Christ, the true and faithful witness (Rev 3:14: &ldquo;the words of the Amen, the faithful and true witness&rdquo;), is the standard against which all false testimony is measured and found wanting.</p>",
    "10": "<p>Luxury unfitting for the fool; a servant ruling over princes. The wisdom category of appropriate-to-role connects to Christ&rsquo;s own self-ordering within the divine economy: though Lord of all, he took the role of servant (Phil 2:7: &ldquo;taking the form of a servant&rdquo;), inverting the ruler-servant hierarchy not through disorder but through deliberate condescension. The new order he establishes reverses the wisdom category itself: &ldquo;whoever would be great among you must be your servant&rdquo; (Matt 20:26).</p>",
    "11": "<p>Slow to anger and the glory of overlooking an offense. YHWH&rsquo;s own self-declaration is &ldquo;slow to anger and abounding in steadfast love&rdquo; (Exod 34:6), and Christ embodies this perfectly: he did not retaliate when reviled (1 Pet 2:23), he forgave from the cross (Luke 23:34), and he overlooked the disciples&rsquo; repeated failures to understand. The glory that belongs to the one who overlooks offense is the glory Christ demonstrates — not weakness but the strength that does not need to enforce itself.</p>",
    "12": "<p>The king&rsquo;s wrath like a lion&rsquo;s roar, his favor like dew on grass. Revelation 5:5 identifies Christ as &ldquo;the Lion of the tribe of Judah&rdquo; — the royal lion of Proverbs is a type. His wrath is real (Rev 6:16-17: &ldquo;the wrath of the Lamb&rdquo;) and his favor is life-giving dew (Hos 14:5: &ldquo;I will be like the dew to Israel&rdquo;). The two aspects of Proverbs&rsquo; royal portrait — terrifying wrath and life-giving favor — converge in the Lamb who is also the Lion.</p>",
    "13": "<p>A foolish son as father&rsquo;s ruin and the contentious wife as constant dripping. Christ is the son who is not a ruin to the Father but his delight: &ldquo;this is my beloved Son, with whom I am well pleased&rdquo; (Matt 3:17; 17:5). The pattern of the son who brings honor versus the son who brings ruin runs through the parable of the prodigal (Luke 15:11-32), where the Father runs to the returning son who had been a ruin — grace restoring what folly had destroyed.</p>",
    "14": "<p>&ldquo;House and riches are inherited from fathers, but a prudent wife is from YHWH.&rdquo; The divine provision of the fitting wife is the template for Eph 5:25-27 — Christ loved the church and gave himself up for her, presenting her to himself holy and without blemish. The &ldquo;prudent wife&rdquo; that YHWH gives becomes, in the NT, the bride that Christ secures by his own death and resurrection. Every good marriage is a gift of divine provision; the ultimate gift is the Lamb&rsquo;s own bride, the new Jerusalem (Rev 21:2).</p>",
    "15": "<p>Deep sleep and the idle soul going hungry. Christ&rsquo;s call to wakefulness and work in the brief day of opportunity (John 9:4: &ldquo;we must work the works of him who sent me while it is day&rdquo;) is the positive counterpart. Ephesians 5:14: &ldquo;Awake, O sleeper, and arise from the dead, and Christ will shine on you.&rdquo; The deep sleep of the idle soul is the condition Christ addresses with both warning (Matt 25:5-13, the sleeping virgins) and resurrection-waking power.</p>",
    "16": "<p>Keeping the commandment to keep the soul; despising one&rsquo;s ways dying. John 14:15: &ldquo;if you love me, you will keep my commandments&rdquo; — Christ links commandment-keeping to love for him, not to legal compliance. He also kept the Father&rsquo;s commandments completely (John 15:10) and in so doing preserved the life of those who could not keep their own souls. His commandment-keeping is their soul-preservation.</p>",
    "17": "<p>&ldquo;Whoever is generous to the poor lends to YHWH, and he will repay him for his deed.&rdquo; Christ&rsquo;s direct identification of himself with the poor makes this verse Christological at its core: &ldquo;as you did it to one of the least of these my brothers, you did it to me&rdquo; (Matt 25:40). Generosity to the poor is lending to YHWH because Christ is present in the needy — the one who was himself poor (2 Cor 8:9) identifies with those in poverty. Every act of charity is a transaction with Christ.</p>",
    "18": "<p>Discipline your son while there is hope — the urgency of the formative window. Hebrews 12:5-11 applies the father-discipline metaphor to Christ&rsquo;s people: &ldquo;the Lord disciplines the one he loves, and chastises every son whom he receives.&rdquo; Christ disciplines not from anger but from love, with the goal of producing &ldquo;the peaceful fruit of righteousness&rdquo; (v11). The father&rsquo;s discipline of the son is the temporal image of Christ&rsquo;s loving discipline of his own through the circumstances he ordains.</p>",
    "19": "<p>The great-anger man who must bear his penalty; rescuing him only repeats the need. The observation about patterns that require transformation, not just rescue, corresponds to Christ&rsquo;s distinction between healing symptoms and addressing sources. John 5:14: &ldquo;sin no more, that nothing worse may happen to you&rdquo; — Christ does not merely rescue from consequences but addresses the root. He heals and calls to repentance, so that the rescue produces transformation rather than dependency.</p>",
    "20": "<p>Listen to counsel, accept instruction, that you may gain wisdom for the future. The Father&rsquo;s counsel that Christ perfectly received and executed (John 12:49: &ldquo;the Father who sent me has himself given me a commandment — what to say and what to speak&rdquo;) is the perfect fulfillment of this exhortation. The disciples&rsquo; education was the pattern of receiving instruction from Christ: &ldquo;come, follow me&rdquo; (Matt 4:19); &ldquo;learn from me&rdquo; (Matt 11:29) — the Master&rsquo;s school as wisdom&rsquo;s embodiment.</p>",
    "21": "<p>&ldquo;Many are the plans in the mind of a man, but it is the purpose of YHWH that will stand.&rdquo; Isaiah 46:10: &ldquo;my counsel shall stand, and I will accomplish all my purpose.&rdquo; Christ is the content of that standing purpose — the lamb &ldquo;slain from the foundation of the world&rdquo; (Rev 13:8), whose redemption was the eternal plan of the Father. Every human plan that opposed him — Herod&rsquo;s infanticide (Matt 2:16), the Sanhedrin&rsquo;s plotting (John 11:53), Pilate&rsquo;s judgment — was overturned by the purpose of YHWH that culminated in resurrection.</p>",
    "22": "<p>The desirability of loyal love (<em>ḥesed</em>) and the better-ness of the poor man over a liar. Christ is the supreme <em>ḥesed</em>-giver: John 1:14 — &ldquo;the Word became flesh and dwelt among us, and we have seen his glory, glory as of the only Son from the Father, full of grace and truth&rdquo; — where &ldquo;grace and truth&rdquo; (<em>charis kai alētheia</em>) is the Greek rendering of the Hebrew <em>ḥesed weʾěmet</em>. The desirability of <em>ḥesed</em> above wealth and above the liar&rsquo;s prosperity reaches its ultimate expression in the incarnate <em>ḥesed</em>.</p>",
    "23": "<p>The fear of YHWH leads to life; satisfied, untouched by evil. Christ as the way to life makes the fear of YHWH personal rather than abstract: &ldquo;I am the way, and the truth, and the life; no one comes to the Father except through me&rdquo; (John 14:6). The life promised through YHWH-fear is available only through Christ who is that life. Revelation 21:3-4: the promised dwelling with God — satisfaction without evil&rsquo;s visitation — is the eschatological fulfillment of what the fear of YHWH pointed toward.</p>",
    "24": "<p>The sluggard who hides his hand in the dish and won&rsquo;t return it — comic extreme of self-defeating passivity. Against all spiritual passivity, Christ acts with complete initiative: John 10:18 — &ldquo;no one takes my life from me, but I lay it down of my own accord.&rdquo; His is the supreme active self-giving that the sluggard&rsquo;s comic passivity refuses to imitate. The Spirit sent by Christ produces in his people the same active engagement: &ldquo;work out your own salvation with fear and trembling, for it is God who works in you&rdquo; (Phil 2:12-13).</p>",
    "25": "<p>Strike the scoffer and the simple learns; rebuke the discerning and he gains knowledge. The punishing of the scoffer serves an educational function for others — a principle Christ applies at the temple cleansing (Matt 21:12-13), where the overturning of the money-changers&rsquo; tables was a public action whose reverberations reached beyond the immediate participants. The prophetic sign-act that publicly rebukes the corrupt temple economy is simultaneously a teaching event for all who witness it.</p>",
    "26": "<p>Assaulting the father and driving out the mother — the ultimate filial dishonor. Christ perfectly honored both the Father and his mother: &ldquo;I always do the things that are pleasing to him&rdquo; (John 8:29); and from the cross he entrusted his mother to the Beloved Disciple (John 19:26-27). His filial faithfulness is the positive fulfillment of the fifth commandment that the son who drives out his mother desecrates.</p>",
    "27": "<p>Stop hearing instruction and you will stray from words of knowledge. Christ&rsquo;s warning about the servant who stops attending to the master&rsquo;s voice corresponds: &ldquo;my sheep hear my voice, and I know them, and they follow me&rdquo; (John 10:27). The continuous hearing of Christ&rsquo;s voice is the NT equivalent of the continuous hearing of wisdom&rsquo;s instruction — when the hearing stops, the straying begins. The Good Shepherd pursues the straying sheep (Luke 15:4) before the cessation of hearing becomes permanent loss.</p>",
    "28": "<p>The worthless witness mocks justice and the wicked mouth swallows iniquity. Christ as the faithful and true witness (Rev 1:5; 3:14) is the anti-type of the worthless witness. Before Pilate, Jesus bore witness to the truth when all other testimony was corrupt: &ldquo;for this purpose I was born and for this purpose I have come into the world — to bear witness to the truth&rdquo; (John 18:37). His faithful witness under pressure is what the worthless witness inverts — and his resurrection vindicates the witness the court rejected.</p>",
    "29": "<p>Judgments prepared for scoffers, beatings for the backs of fools. The preparation of judgment for the impenitent is the solemn counterpart to the preparation of eternal life for the faithful. John 5:22: &ldquo;the Father judges no one, but has given all judgment to the Son.&rdquo; The prepared judgments of Proverbs 19:29 are administered by the one who himself endured the beating (Matt 27:26: &ldquo;having scourged Jesus, delivered him to be crucified&rdquo;). He who bore the judgment for his people administers it for those who reject the mercy offered.</p>"
  },
  "20": {
    "1": "<p>Wine as mocker, strong drink as brawler, and those led astray by them lacking wisdom. The Nazarite vow and priestly abstinence traditions found their fulfillment in Christ&rsquo;s self-discipline: though he turned water into wine (John 2:1-11), he drank from the cup of suffering (Matt 26:42) and refused the wine mingled with gall at the cross (Matt 27:34). His final abstinence — &ldquo;I will not drink again of this fruit of the vine until that day when I drink it new with you in my Father&rsquo;s kingdom&rdquo; (Matt 26:29) — is the eschatological restraint that shapes the use of all earthly pleasures.</p>",
    "2": "<p>The king&rsquo;s terror like a lion&rsquo;s roar — provoking his anger is forfeiting your life. Revelation 5:5 and 6:16-17 present Christ as the lion whose wrath is equally terrifying: &ldquo;who can stand?&rdquo; The fear of the king&rsquo;s wrath is the temporal image of the fear of Christ&rsquo;s judgment — yet the same one whose wrath is like the lion&rsquo;s roar says to his people: &ldquo;do not fear those who kill the body&rdquo; (Matt 10:28), providing the only standing-place before the divine wrath.</p>",
    "3": "<p>Honor in avoiding strife; every fool breaks out in quarreling. Christ as the peacemaker sets the standard: &ldquo;blessed are the peacemakers, for they shall be called sons of God&rdquo; (Matt 5:9). He himself is &ldquo;our peace, who has made us both one and has broken down in his flesh the dividing wall of hostility&rdquo; (Eph 2:14). The honor belonging to the one who avoids strife is the honor of the Son who came not to destroy but to reconcile (2 Cor 5:18-19).</p>",
    "4": "<p>The sluggard who doesn&rsquo;t plow in autumn and seeks at harvest but finds nothing. Against all spiritual failure to prepare in the appointed season, Christ provides the only sustainable preparation: &ldquo;seek first the kingdom of God and his righteousness, and all these things will be added to you&rdquo; (Matt 6:33). The one who plows in the Spirit reaps eternal life (Gal 6:8); the one who neglects the plowing of repentance and faith in the present season finds no harvest when the judgment comes.</p>",
    "5": "<p>Purpose in a man&rsquo;s heart like deep water; the man of understanding draws it out. Christ as the man of understanding who drew out what was hidden in human hearts is illustrated throughout the Gospels: his questions to the disciples — &ldquo;who do you say that I am?&rdquo; (Matt 16:15) — and to individuals draw out the deepest intentions and recognitions. John 2:25: &ldquo;he himself knew what was in man.&rdquo; He is the supreme counselor who draws from the deep waters of the human person what the person cannot reach alone.</p>",
    "6": "<p>&ldquo;Many a man proclaims his own steadfast love, but a faithful man — who can find?&rdquo; The rhetorical question about the rarity of reliable <em>ḥesed</em> receives its Christological answer: Christ is the faithful man who can be found. John 1:17: &ldquo;grace and truth came through Jesus Christ.&rdquo; 2 Tim 2:13: &ldquo;if we are faithless, he remains faithful — for he cannot deny himself.&rdquo; The universally rare quality of human faithfulness is the exclusively certain quality of Christ — he is the only human being of whom the question &ldquo;who can find?&rdquo; receives a definitive positive answer.</p>",
    "7": "<p>The righteous man walking in integrity, his children blessed after him. Christ walks in perfect integrity — Heb 7:26: &ldquo;holy, innocent, unstained, separated from sinners&rdquo; — and his children are blessed through his integrity, not their own: &ldquo;for as by the one man&rsquo;s disobedience the many were made sinners, so by the one man&rsquo;s obedience the many will be made righteous&rdquo; (Rom 5:19). The children who walk after the father of integrity are the redeemed community blessed because of Christ&rsquo;s perfect walk.</p>",
    "8": "<p>The king sitting on the judgment throne, winnowing all evil with his eyes. Matthew 25:31-33: &ldquo;when the Son of Man comes in his glory, and all the angels with him, then he will sit on his glorious throne. Before him will be gathered all the nations, and he will separate people one from another as a shepherd separates the sheep from the goats.&rdquo; The king on the judgment throne winnowing evil with his eyes is the OT image whose eschatological fulfillment is Christ&rsquo;s own royal judgment scene.</p>",
    "9": "<p>&ldquo;Who can say, I have made my heart clean; I am pure from my sin?&rdquo; — the rhetorical question implying no one. 1 John 1:8: &ldquo;if we say we have no sin, we deceive ourselves, and the truth is not in us.&rdquo; The one exception is Christ: &ldquo;he committed no sin, neither was deceit found in his mouth&rdquo; (1 Pet 2:22). He is the only human being who could truthfully say his heart was clean — and his clean heart is the righteousness imputed to those who cannot clean their own (2 Cor 5:21: &ldquo;for our sake he made him to be sin who knew no sin&rdquo;).</p>",
    "10": "<p>Diverse weights and measures as abomination to YHWH. Commercial dishonesty is not a peripheral sin but a structural covenant violation. Christ&rsquo;s cleansing of the temple (Matt 21:12-13; John 2:14-16) targeted precisely the commercial exploitation of the sacred — the money-changers who manipulated exchange rates within the house of prayer. His action demonstrates that YHWH&rsquo;s abomination of commercial dishonesty extends into the center of the covenant community&rsquo;s worship, not just the marketplace.</p>",
    "11": "<p>Even a child is known by his deeds — character is visible in action from the earliest years. Luke 2:41-52 records the one episode from Christ&rsquo;s childhood preserved in the Gospels: the twelve-year-old Jesus in the temple, about his Father&rsquo;s business. Even as a child his deeds already revealed his identity — the teachers who heard him were astonished (v47). The wisdom of Proverbs 20:11 applies to Jesus with its full force: his childhood deeds already disclosed the character that would be fully revealed in his public ministry.</p>",
    "12": "<p>The hearing ear and seeing eye — YHWH made them both. Christ as creator of all human faculties (John 1:3: &ldquo;all things were made through him&rdquo;) made the hearing ear and seeing eye. He also healed both in his ministry: &ldquo;the blind receive their sight and the deaf hear&rdquo; (Matt 11:5, citing Isa 35:5-6). The Creator of hearing and sight demonstrates his identity by restoring what sin and death had damaged — the healed ear and opened eye are the sign that the Creator-God has come in flesh.</p>",
    "13": "<p>Love not sleep lest you come to poverty; open your eyes and have plenty of bread. Christ&rsquo;s own ministry was characterized by active watchfulness: he often rose early to pray (Mark 1:35: &ldquo;rising very early in the morning, while it was still dark, he departed and went to a desolate place and there he prayed&rdquo;). John 6:35: &ldquo;I am the bread of life; whoever comes to me shall not hunger.&rdquo; The open eyes and plenty of bread promised by Proverbs meet their ultimate fulfillment in the one who is himself the bread of life for all who do not slumber in unbelief.</p>",
    "14": "<p>&ldquo;Bad, bad,&rdquo; says the buyer, then boasts — the commercial negotiator&rsquo;s gap between professed and private evaluation. James 2:1-4 targets the same hypocrisy in the covenant community: showing partiality between rich and poor while professing equal regard. Christ exposed such hypocrisy consistently: &ldquo;they say, and do not do&rdquo; (Matt 23:3). He himself maintained complete congruence between his words and his evaluations — no public deprecation and private approval, no flattery and hidden contempt.</p>",
    "15": "<p>Gold and costly stones abound, but lips of knowledge are the precious jewel. Christ&rsquo;s lips of knowledge are the supreme precious jewel: &ldquo;no one ever spoke like this man!&rdquo; (John 7:46). Paul identifies the content of his speech as surpassing all other wealth: &ldquo;I count everything as loss because of the surpassing worth of knowing Christ Jesus my Lord&rdquo; (Phil 3:8). The wisdom tradition&rsquo;s valuation of speech over precious metals anticipates Paul&rsquo;s declaration that the treasure of knowing Christ exceeds all calculated gain.</p>",
    "16": "<p>Take the garment of one who puts up security for a stranger. The pledge/surety dynamic (see Prov 6:1-5 and Heb 7:22) has its christological center in Christ as the ultimate guarantor. He who was the ultimate surety did not escape the taking of his garment — the soldiers cast lots for his clothing (John 19:23-24, fulfilling Ps 22:18). The cosmic surety was stripped of his outer covering in his death, completing the pledge he had made for those he represented.</p>",
    "17": "<p>Bread of deceit is sweet but becomes gravel in the mouth. Against the false sweetness of deceptive gain, Christ offers true bread: &ldquo;I am the bread of life; whoever comes to me shall not hunger&rdquo; (John 6:35). The gravel that replaces the deceptive bread&rsquo;s sweetness is the inverse of the manna in the wilderness — gravel where bread should be. Christ is the true manna (John 6:31-35), the bread that does not become gravel but sustains to eternal life.</p>",
    "18": "<p>Plans established by counsel; by wise guidance wage war. Christ is the counselor of perfect wisdom (Isa 9:6: &ldquo;Wonderful Counselor&rdquo;) whose guidance guarantees victory. His own counsel for spiritual warfare is complete: &ldquo;take up the whole armor of God&rdquo; (Eph 6:11-17); &ldquo;in the world you will have tribulation. But take heart; I have overcome the world&rdquo; (John 16:33). The wise guidance that Proverbs says establishes war-plans is the counsel that Christ as the Wonderful Counselor provides — and the victory he has already secured grounds the confidence of those who follow his guidance.</p>",
    "19": "<p>The gossip who reveals secrets — do not associate with a simple babbler. Christ&rsquo;s counsel about trustworthy speech and the community of trust he forms inverts the gossip&rsquo;s pattern. John 15:15: &ldquo;no longer do I call you servants, for the servant does not know what his master is doing; but I have called you friends, for all that I have heard from my Father I have made known to you.&rdquo; Christ shares the Father&rsquo;s counsel with his disciples — the reverse of the gossip who reveals secrets harmfully; he reveals secrets (mysteries of the kingdom, Matt 13:11) to those entrusted with them.</p>",
    "20": "<p>The lamp extinguished for cursing parents — the fifth commandment carried to its deadly endpoint. Christ perfectly honored his Father — &ldquo;I always do the things that are pleasing to him&rdquo; (John 8:29) — and is the eternal lamp: &ldquo;the city has no need of sun or moon to shine on it, for the glory of God gives it light, and its lamp is the Lamb&rdquo; (Rev 21:23). The lamp that is extinguished for filial dishonor is the inverse of the Lamb who is the eternal light — his lamp cannot be extinguished because his filial obedience is perfect and complete.</p>",
    "21": "<p>An inheritance gained hastily in the beginning will not be blessed in the end. The prodigal son&rsquo;s hastily demanded inheritance squandered in the far country (Luke 15:11-13) is the narrative illustration — and the father&rsquo;s restoration of the returning son is the christological reversal. The unhastily gained inheritance is the one secured by Christ through patient suffering: &ldquo;heirs of God and fellow heirs with Christ, provided we suffer with him in order that we may also be glorified with him&rdquo; (Rom 8:17).</p>",
    "22": "<p>&ldquo;Do not say, I will repay evil; wait for YHWH, and he will deliver you.&rdquo; Romans 12:19: &ldquo;beloved, never avenge yourselves, but leave it to the wrath of God, for it is written, &lsquo;Vengeance is mine, I will repay,&rsquo; says the Lord.&rdquo; Christ himself performed this waiting: &ldquo;when he was reviled, he did not revile in return; when he suffered, he did not threaten, but continued entrusting himself to him who judges justly&rdquo; (1 Pet 2:23). His entrusting of himself to the Father-judge is the supreme example of the waiting that Proverbs commands.</p>",
    "23": "<p>Diverse weights again as abomination — the repetition emphasizes commercial covenant integrity. Christ&rsquo;s final judgment will include an accounting of all commercial dealings: &ldquo;for we must all appear before the judgment seat of Christ, so that each one may receive what is due for what he has done in the body, whether good or evil&rdquo; (2 Cor 5:10). The YHWH who abhors false weights is the Christ who will weigh all human dealings with the perfect scale of divine justice.</p>",
    "24": "<p>&ldquo;A man&rsquo;s steps are from YHWH; how then can man understand his way?&rdquo; Hebrews 12:2: &ldquo;looking to Jesus, the founder and perfecter of our faith, who for the joy that was set before him endured the cross.&rdquo; Christ&rsquo;s steps were entirely from the Father — he did nothing of his own initiative (John 5:30: &ldquo;I can do nothing on my own... I seek not my own will but the will of him who sent me&rdquo;). His steps being perfectly from YHWH provides the model for discipleship: trusting the divine direction of one&rsquo;s own path rather than grasping for autonomous understanding.</p>",
    "25": "<p>The trap of rash vows — sacred before reflection. Christ&rsquo;s own counsel on vows addresses the same danger: &ldquo;let what you say be simply &lsquo;Yes&rsquo; or &lsquo;No&rsquo;&rdquo; (Matt 5:37). He himself made no rash vows but fulfilled perfectly the eternal covenant pledge he had made — not rashly but with complete foreknowledge of the cost (John 17:24: &ldquo;Father, I desire that they also, whom you have given me, may be with me where I am&rdquo;). His deliberate, foresighted commitment is the opposite of the snaring rash vow.</p>",
    "26": "<p>The wise king winnowing the wicked, driving the threshing wheel over them. Matthew 3:12 applies the winnowing image to Christ: &ldquo;his winnowing fork is in his hand, and he will clear his threshing floor and gather his wheat into the barn, but the chaff he will burn with unquenchable fire.&rdquo; The wise king of Proverbs 20:26 is the type; Christ is the eschatological fulfillment — the royal winnowing that sorts the wicked from the righteous at the last day.</p>",
    "27": "<p>&ldquo;The spirit of man is the lamp of YHWH, searching all his innermost parts.&rdquo; John 1:4: &ldquo;in him was life, and the life was the light of men.&rdquo; Christ is the source of the inner lamp — the breath/spirit that God breathed into man (Gen 2:7) is renewed and relit in those who receive the Spirit that Christ sends (John 20:22: &ldquo;he breathed on them and said to them, &lsquo;Receive the Holy Spirit&rsquo;&rdquo;). The human spirit as YHWH&rsquo;s lamp for inner searching becomes, in the Spirit-filled believer, the indwelling of the divine light itself.</p>",
    "28": "<p>&ldquo;Steadfast love and faithfulness (<em>ḥesed weʾěmet</em>) preserve the king; by steadfast love his throne is upheld.&rdquo; John 1:14: &ldquo;we have seen his glory, glory as of the only Son from the Father, full of grace and truth&rdquo; — <em>charin kai alētheian</em>, the Greek rendering of <em>ḥesed weʾěmet</em>. Christ is the king whose throne is upheld by his own <em>ḥesed</em> and <em>ʾěmet</em>: Rev 1:5 — &ldquo;the faithful witness, the firstborn of the dead, and the ruler of kings on earth.&rdquo; His rule is not sustained by force but by the covenant virtues that Proverbs identifies as royal foundations.</p>",
    "29": "<p>The glory of young men is their strength; the splendor of old men is their gray hair. Christ, the &ldquo;Ancient of Days&rdquo; prototype and the &ldquo;one like a son of man&rdquo; (Dan 7:9, 13), encompasses both: the eternal wisdom of the Ancient of Days and the vigor of the incarnate Son. Revelation 1:14 describes the risen Christ with &ldquo;hair white as white wool, as white as snow&rdquo; — the white/gray of age — combined with eyes like flames of fire and a voice like the roar of many waters. He is the one in whom all human glories, of youth and age, find their completion and source.</p>",
    "30": "<p>Blows that wound cleanse away evil; stripes make clean the innermost parts. Isaiah 53:5: &ldquo;he was pierced for our transgressions; he was crushed for our iniquities; upon him was the chastisement that brought us peace, and with his wounds we are healed.&rdquo; The wounds that cleanse in Proverbs 20:30 find their ultimate instance in Christ&rsquo;s stripes: the blows that fell on him cleanse those he represents. The painful discipline that purifies in the wisdom tradition becomes at the cross the substitutionary wounding through which all inner cleansing flows.</p>"
  },
  "21": {
    "1": "<p>&ldquo;The king&rsquo;s heart is a stream of water in the hand of YHWH; he turns it wherever he will.&rdquo; John 19:11: &ldquo;you would have no authority over me at all unless it had been given you from above.&rdquo; Pilate, the king-representative who sentenced Jesus, was himself an instrument turned by YHWH&rsquo;s hand — the condemnation of Christ was not the triumph of human power but the execution of the divine redemptive plan. Isaiah 45:1 presents Cyrus similarly: the pagan king whose channel YHWH directed for Israel&rsquo;s restoration. Every ruler who touches Christ is turned by YHWH&rsquo;s hand toward the purposes of salvation.</p>",
    "2": "<p>Every way right in one&rsquo;s own eyes, but YHWH weighs the heart. Christ as the judge who weighs the heart — John 2:24-25: &ldquo;he knew all people and needed no one to bear witness about man, for he himself knew what was in man.&rdquo; The divine heart-weighing of Proverbs is performed by the incarnate Christ: he sees past self-evaluation to the reality within. His Sermon on the Mount begins with &ldquo;blessed are the pure in heart&rdquo; (Matt 5:8) — the heart is the arena of kingdom membership, and Christ alone can assess and cleanse it.</p>",
    "3": "<p>&ldquo;To do righteousness and justice is more acceptable to YHWH than sacrifice.&rdquo; Matthew 9:13 and 12:7: &ldquo;I desire mercy, and not sacrifice&rdquo; — Christ&rsquo;s repeated citation of Hosea 6:6 in his own ministry. He himself embodied this priority: his death was not the offering of a ritual sacrifice but the act of supreme justice and righteousness — satisfying the demands of justice (Rom 3:26: &ldquo;so that he might be just and the justifier of the one who has faith in Jesus&rdquo;). The justice that is more acceptable than sacrifice is perfectly enacted in the one act that was both justice and sacrifice simultaneously.</p>",
    "4": "<p>Haughty eyes and proud heart — the lamp of the wicked — are sin. Christ is the anti-type: &ldquo;I am gentle and lowly in heart&rdquo; (Matt 11:29). His eyes do not look haughtily at those around him; he sees the crowd and has compassion (Matt 9:36). The &ldquo;lamp of the wicked&rdquo; that is sin contrasts with Christ as the true lamp: &ldquo;in him was life, and the life was the light of men&rdquo; (John 1:4). The wicked lamp goes out (13:9; 24:20); the light of Christ &ldquo;shines in the darkness, and the darkness has not overcome it&rdquo; (John 1:5).</p>",
    "5": "<p>Plans of the diligent lead to abundance; haste leads to poverty. Christ planned his redemption with eternal precision: the cross was not an accident or improvisation but &ldquo;the Lamb slain from the foundation of the world&rdquo; (Rev 13:8). His diligent execution of the Father&rsquo;s plan — step by step through ministry, suffering, death, and resurrection — produced the abundance of the new creation: &ldquo;I came that they may have life and have it abundantly&rdquo; (John 10:10). The diligent plans that produce abundance reach their ultimate expression in the redemptive plan perfectly executed.</p>",
    "6": "<p>Treasures of wickedness as fleeting vapor (<em>hebel</em>) and a snare of death. Against all vanishing wealth, Christ offers eternal treasure: &ldquo;do not lay up for yourselves treasures on earth... but lay up for yourselves treasures in heaven, where neither moth nor rust destroys&rdquo; (Matt 6:19-20). Paul&rsquo;s counter-declaration is direct: &ldquo;I count everything as loss because of the surpassing worth of knowing Christ Jesus my Lord&rdquo; (Phil 3:8). The <em>hebel</em>-treasure of wickedness is the foil for the imperishable treasure that relationship with Christ provides.</p>",
    "7": "<p>The violence of the wicked sweeping them away because they refuse to do justice. Christ&rsquo;s lament over Jerusalem is the compassionate counterpart: &ldquo;O Jerusalem, Jerusalem, the city that kills the prophets and stones those who are sent to it! How often would I have gathered your children together as a hen gathers her brood under her wings, and you were not willing!&rdquo; (Matt 23:37). The refusal of justice leads to being swept away by one&rsquo;s own violence; the refusal of Christ&rsquo;s mercy leads to the same eschatological consequence — the wicked swept away by the very force they chose over justice.</p>",
    "8": "<p>The way of the guilty is crooked; the pure man&rsquo;s conduct is upright. Christ&rsquo;s path was perfectly upright — Heb 7:26: &ldquo;holy, innocent, unstained, separated from sinners.&rdquo; 1 Peter 2:22: &ldquo;he committed no sin, neither was deceit found in his mouth.&rdquo; His upright conduct is both the example and the grounds of the believer&rsquo;s justification: he walked the straight path that the guilty cannot walk, and his righteous conduct is reckoned to those whose path has been crooked (Rom 5:18: &ldquo;one act of righteousness leads to justification and life for all men&rdquo;).</p>",
    "9": "<p>Better the housetop corner than a contentious household. Christ&rsquo;s own homelessness — &ldquo;foxes have holes, and birds of the air have nests, but the Son of Man has nowhere to lay his head&rdquo; (Matt 8:20) — is the ultimate &ldquo;corner of the housetop,&rdquo; a chosen exposure and limitation that enabled his mission. He did not avoid the contentious household but entered it: &ldquo;do not think that I have come to bring peace to the earth. I have not come to bring peace, but a sword&rdquo; (Matt 10:34) — the sword of truth that divides even households.</p>",
    "10": "<p>The soul of the wicked desiring evil; his neighbor finding no mercy in his eyes. Christ is the opposite at every point: he went about doing good (Acts 10:38); his eye was for the one who found no mercy elsewhere — the Samaritan woman (John 4), the tax collector Zacchaeus (Luke 19:1-10), the woman caught in adultery (John 8:1-11). Where the wicked soul seeks evil and withholds mercy, Christ seeks the lost and gives mercy extravagantly.</p>",
    "11": "<p>When the scoffer is punished the simple learns; when the wise man is instructed he gains knowledge. The disciples&rsquo; learning pattern tracks through both modes: they learn by witnessing Christ&rsquo;s dealings with opponents (the Pharisees rebuked: Matt 23; the temple cleansed: Matt 21) and by receiving direct instruction (the Sermon on the Mount: Matt 5-7; the Farewell Discourse: John 13-17). Both modes — punitive rebuke of the scoffer and direct instruction of the teachable — are present in Christ&rsquo;s pedagogy.</p>",
    "12": "<p>The Righteous One who watches the wicked household and throws them down to ruin. Acts 5:1-11 (Ananias and Sapphira) and Revelation 2-3 (Christ&rsquo;s letters to the churches threatening judgment on the unrepentant) demonstrate the risen Christ as the Righteous One who observes and acts. His watching is not passive surveillance but active governance: &ldquo;the eyes of the LORD run to and fro throughout the whole earth, to give strong support to those whose heart is blameless toward him&rdquo; (2 Chr 16:9).</p>",
    "13": "<p>Closing the ear to the poor&rsquo;s cry means one&rsquo;s own cry will go unanswered. Matthew 25:41-46: those who refused to care for &ldquo;the least of these my brothers&rdquo; hear the same refusal from Christ at the judgment. James 2:13: &ldquo;judgment is without mercy to one who has shown no mercy.&rdquo; The mirror-principle of Proverbs 21:13 is applied by Christ to the final judgment: the same measure one uses for others is the measure used for oneself (Matt 7:2), and the closed ear to the poor becomes a closed gate at the eschatological threshold.</p>",
    "14": "<p>A gift in secret averts anger; a concealed bribe averts strong wrath. The pragmatic acknowledgment of the gift-economy contrasts with the total economy of grace in Christ: &ldquo;for God so loved the world, that he gave his only Son&rdquo; (John 3:16). No concealed bribe or secret gift averts divine wrath — only the public, cosmic gift of the Son, given openly, bears the weight of divine anger on behalf of those who receive him. The gift that averts wrath is not secret but the most public act in history: the cross.</p>",
    "15": "<p>Joy to the just to do justice; terror to evildoers. Christ brings both: to his people he says &ldquo;well done, good and faithful servant; enter into the joy of your master&rdquo; (Matt 25:21); to the unjust: &ldquo;depart from me, you cursed&rdquo; (Matt 25:41). The same Christ who is the joy of the righteous (Rev 19:7: &ldquo;let us rejoice and exult and give him glory, for the marriage of the Lamb has come&rdquo;) is the terror of evildoers (Rev 6:16-17: &ldquo;hide us from the face of him who is seated on the throne&rdquo;).</p>",
    "16": "<p>The man wandering from understanding resting in the assembly of the dead. Christ&rsquo;s mission is to seek and save those who have wandered: Luke 15:4-7; John 10:11 — &ldquo;the good shepherd lays down his life for the sheep.&rdquo; He does not leave those who have wandered into the assembly of the dead without intervention — rather, he himself descended to death (Acts 2:27: &ldquo;you will not abandon my soul to Hades&rdquo;) to bring back those who had wandered there. The destination of the wanderer is the place Christ himself entered to reverse.</p>",
    "17": "<p>Loves pleasure comes to poverty; loves wine and oil will not be rich. Against the poverty of pleasure-love, Christ offers true riches: &ldquo;I counsel you to buy from me gold refined by fire, so that you may be rich&rdquo; (Rev 3:18). Paul&rsquo;s contentment-in-all-circumstances (Phil 4:11-13) is the christological transformation of pleasure-love into pleasure-in-Christ: &ldquo;I can do all things through him who strengthens me.&rdquo; The poverty that follows pleasure-love is displaced by the riches of knowing Christ.</p>",
    "18": "<p>The wicked as ransom for the righteous. Isaiah 43:3-4 presents YHWH giving nations as ransom for Israel; here the logic runs that the wicked bear the consequences their wickedness brings, freeing the righteous from those consequences. The ultimate christological reversal is the inverse: Christ, the righteous one, became a ransom for the unrighteous: &ldquo;the Son of Man came not to be served but to serve, and to give his life as a ransom for many&rdquo; (Matt 20:28). The wicked-as-ransom pattern of creaturely justice is transcended by the righteous-as-ransom of divine grace.</p>",
    "19": "<p>Better the desert than a contentious woman. Christ&rsquo;s own experience of solitude in the desert was formative: forty days in the wilderness (Matt 4:1-11), repeated withdrawal to desolate places (Luke 5:16: &ldquo;he would withdraw to desolate places and pray&rdquo;). His desert withdrawals were not avoidance but engagement with the Father — transforming the desert into the place of divine communion rather than mere escape from human conflict.</p>",
    "20": "<p>Precious treasure and oil in the wise man&rsquo;s dwelling; the fool devours it. The wise man&rsquo;s stored treasure anticipates the parable of the talents (Matt 25:14-30): those who invest the master&rsquo;s gifts receive more; the one who buries his talent (foolishly hoards) loses even what he has. Christ is also the treasury himself: &ldquo;in whom are hidden all the treasures of wisdom and knowledge&rdquo; (Col 2:3). The wise man&rsquo;s dwelling that holds precious treasure is the life hidden with Christ in God (Col 3:3).</p>",
    "21": "<p>&ldquo;Whoever pursues righteousness and kindness (<em>ḥesed</em>) will find life, righteousness, and honor.&rdquo; Matthew 5:6: &ldquo;blessed are those who hunger and thirst for righteousness, for they shall be satisfied.&rdquo; Christ himself pursued righteousness and <em>ḥesed</em> perfectly — &ldquo;I do not seek my own glory&rdquo; (John 8:50); &ldquo;he humbled himself by becoming obedient to the point of death&rdquo; (Phil 2:8) — and found life in the resurrection, righteousness confirmed by the Father, and the name above every name. His pursuit of righteousness is the pattern that those who follow him are called to replicate.</p>",
    "22": "<p>A wise man scales the city of the mighty and brings down the stronghold they trust. Christ is the supreme conqueror of fortified strongholds. Matthew 16:18: &ldquo;I will build my church, and the gates of hell shall not prevail against it.&rdquo; 2 Corinthians 10:4: &ldquo;the weapons of our warfare are not of the flesh but have divine power to destroy strongholds.&rdquo; The wise man who scales the city of the mighty is Christ who, through the weakness of the cross, overthrew the apparently impregnable fortress of sin and death (Col 2:15: &ldquo;he disarmed the rulers and authorities and put them to open shame&rdquo;).</p>",
    "23": "<p>Guard mouth and tongue — guard soul from trouble. Christ&rsquo;s speech is the model: &ldquo;the words that I say to you I do not speak on my own authority, but the Father who dwells in me does his works&rdquo; (John 14:10). James 3:2: &ldquo;if anyone does not stumble in what he says, he is a perfect man.&rdquo; Christ is the only perfect man who never stumbled in speech — his mouth was the perfect instrument of divine communication, guarded not by discipline alone but by complete union with the Father&rsquo;s own speech.</p>",
    "24": "<p>The arrogant scoffer who acts with arrogant pride — the <em>lēṣ</em> profile. Christ confronted this profile directly in the Pharisees (Matt 23: &ldquo;woe to you... for you shut the kingdom of heaven in people&rsquo;s faces&rdquo;) and identified its root: &ldquo;you are of your father the devil, and your will is to do your father&rsquo;s desires&rdquo; (John 8:44). The arrogant scoffer who rejects wisdom is ultimately in the lineage of the adversary who first scorned the divine counsel. Christ, who is gentle and lowly (Matt 11:29), is the anti-scoffing presence in the world.</p>",
    "25": "<p>The sluggard&rsquo;s desire kills him because his hands refuse to labor. Christ&rsquo;s parable of the talents (Matt 25:14-30) and the servants who must work while the master is away both target the spiritual paralysis of the one who buries his gift and refuses to use it. The one-talent servant who hid his talent &ldquo;from fear&rdquo; — desire without action — is cast into outer darkness. Against this paralysis Christ offers both command and enablement: &ldquo;work, for I am with you&rdquo; (Hag 2:4 applied in the NT frame of Phil 2:13: &ldquo;it is God who works in you&rdquo;).</p>",
    "26": "<p>The wicked craves all day long, but the righteous gives and does not hold back. Christ is the righteous giver par excellence: &ldquo;he did not count equality with God a thing to be grasped, but emptied himself&rdquo; (Phil 2:6-7). &ldquo;It is more blessed to give than to receive&rdquo; (Acts 20:35 — a saying of Jesus). His giving was total — his life, his Spirit, his righteousness — and he calls his people into the same pattern of open-handed generosity as the expression of the righteous character they receive from him.</p>",
    "27": "<p>The sacrifice of the wicked is an abomination; more so when brought with evil intent. Christ&rsquo;s Hosea-citation — &ldquo;I desire mercy, and not sacrifice&rdquo; (Matt 9:13; 12:7) — and his own sacrifice converge here: his sacrifice was not abominable but the fulfillment of what all acceptable sacrifices pointed toward (Heb 10:5-7: &ldquo;sacrifices and offerings you have not desired... then I said, &lsquo;Behold, I have come to do your will, O God&rsquo;&rdquo;). He abolished the category of abominable sacrifice by offering the one sacrifice of pure intent and perfect fulfillment.</p>",
    "28": "<p>The false witness perishes; the word of the one who hears endures. Christ is the Word that endures: &ldquo;heaven and earth will pass away, but my words will not pass away&rdquo; (Matt 24:35). John 1:1: &ldquo;in the beginning was the Word.&rdquo; All false testimony against Christ has perished — the false witnesses at his trial are forgotten while his words endure across millennia. He is the ultimate faithful hearer who listened to the Father&rsquo;s voice and spoke only what he heard (John 12:49), and his word is the one testimony that cannot be overthrown.</p>",
    "29": "<p>The wicked puts on a bold face; the upright gives thought to his ways. Christ&rsquo;s practice of self-examination before the Father is the supreme example of thinking carefully about one&rsquo;s ways: &ldquo;the Father who sent me has himself borne witness about me&rdquo; (John 8:18); &ldquo;I always do the things that are pleasing to him&rdquo; (John 8:29). His upright self-examination is continuous, transparent, and perfect — the model for the self-examination Paul calls believers to practice (1 Cor 11:28: &ldquo;let a person examine himself&rdquo;).</p>",
    "30": "<p>&ldquo;No wisdom, no understanding, no counsel can avail against YHWH.&rdquo; 1 Corinthians 1:25: &ldquo;the foolishness of God is wiser than men, and the weakness of God is stronger than men.&rdquo; The cross appeared to be the defeat of wisdom — &ldquo;the word of the cross is folly to those who are perishing&rdquo; (1 Cor 1:18) — but it was the surpassing wisdom of God overcoming all human counsel against YHWH. The Sanhedrin&rsquo;s wisdom, Rome&rsquo;s power, and death itself could not avail against the YHWH who raised Christ from the dead.</p>",
    "31": "<p>&ldquo;The horse is made ready for the day of battle, but the victory belongs to YHWH.&rdquo; Revelation 17:14: &ldquo;they will make war on the Lamb, and the Lamb will conquer them, for he is Lord of lords and King of kings, and those with him are called and chosen and faithful.&rdquo; The victory-belongs-to-YHWH declaration of Proverbs 21:31 is fulfilled in Christ&rsquo;s resurrection (the definitive victory) and eschatological return. All military preparation, political power, and strategic planning finally yields to the one whose victory was secured not by the horse but by the cross and empty tomb.</p>"
  }
}

def main():
    existing = load_comm('mkt-christ', 'proverbs')
    merge_comm(existing, CHRIST)
    save_comm('mkt-christ', 'proverbs', existing)
    total = sum(len(vv) for vv in CHRIST.values())
    print(f'proverbs mkt-christ: wrote {total} verses for ch 19–21')

if __name__ == '__main__':
    main()
