"""
mkt-context layer — 2 Corinthians all 13 chapters
Output: data/commentary/mkt-context/2corinthians.json

2 Corinthians is written ca. 54-57 CE after a painful visit and an
intermediate letter (now lost). The 'super-apostles' (11:5; 12:11) are
likely Hellenistic Jewish missionaries with letters of recommendation
who competed with Paul on Greco-Roman rhetorical and wonder-worker grounds.
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(layer, book):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(layer, book, data):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

CONTEXT = {
  "1": {
    "8": "<p>The affliction Paul suffered in Asia (v. 8: we were so utterly burdened beyond our strength that we despaired of life itself) is unspecified — candidates include: a near-fatal illness (cf. Gal 4:13-14), violent persecution at Ephesus (cf. 1 Cor 15:32 'I fought with beasts'), or the riot of Acts 19. Paul's <em>sentence of death</em> (<em>apokrima tou thanatou</em>) is a judicial term — either the experience felt like a death verdict or he received an actual legal condemnation. Whatever the event, it produced the pneumatological outcome Paul describes: reliance on the God who raises the dead (v. 9), the experiential foundation of 2 Corinthians' theology of resurrection-through-suffering.</p>"
  },
  "3": {
    "1": "<p>Letters of recommendation (<em>systatikaí epistolai</em>, 3:1) were a standard social institution in the ancient Mediterranean world: a prominent person would write a letter attesting to the character, status, and worthiness of a traveling associate. Cicero wrote dozens (Ad Atticum; Ad Familiares); papyri preserve examples from Egyptian commerce. Paul's opponents brought such letters to Corinth, establishing their credentials through social networks Paul lacked or scorned. Paul's counterargument: the Corinthians themselves are his letter of recommendation — written on hearts by the Spirit, readable by everyone. The apostolic community is the authenticating credential for genuine ministry.</p>",

    "7": "<p>The contrast between the 'ministry of death, carved in letters on stone' (<em>diakonia tou thanatou en grammasin entetypōmenē lithois</em>) and the 'ministry of the Spirit' reflects Paul's understanding of Sinai. The Mosaic covenant was glorious — Moses's face shone (Exod 34:29-35); the Israelites could not look at it. But that glory was transient (<em>katargoumene</em>, passing away, v. 7). Paul's argument uses a <em>qal vahomer</em> (lesser to greater) rabbinic form: if the lesser (Mosaic) had glory, the greater (Spirit-ministry) surpasses it immeasurably. This is not anti-Torah polemic (Paul quotes Torah approvingly throughout 2 Corinthians) but a salvation-historical ordering.</p>"
  },
  "5": {
    "10": "<p>The judgment seat of Christ (<em>bema tou Christou</em>, v. 10): the <em>bema</em> was the elevated platform in a Roman city center where the magistrate or proconsul rendered judgments — Gallio sat on the Corinthian <em>bema</em> when Jews dragged Paul before him (Acts 18:12). Paul transforms this civic institution into an eschatological reality: each person will appear before Christ's <em>bema</em> to receive what is due for what was done in the body, whether good or evil. This is not justification-reversal (Paul consistently teaches no condemnation for those in Christ, Rom 8:1) but an accounting of stewardship — the believer's life-work is evaluated by the risen judge.</p>"
  },
  "8": {
    "1": "<p>The collection for the Jerusalem poor (chs. 8-9) was Paul's major trans-community project ca. 52-57 CE, coordinating Gentile churches (Galatia, Macedonia, Achaia, Asia) to send material aid to impoverished believers in Jerusalem. Paul speaks of it in Rom 15:25-27 as a theological act: Gentiles share in Jews' spiritual blessings; it is right to share material resources in return. The political dimension: the collection demonstrates to Jerusalem that Gentile churches are genuine members of the same body, potentially addressing the ongoing Jewish-Gentile tension that produced the Jerusalem Council controversy (Acts 15). Josephus (Ant. 20.51-53) documents chronic food shortage and famine in Judea in this period.</p>"
  },
  "10": {
    "1": "<p>Paul's opponents apparently criticized him for being 'humble when face to face with you, but bold toward you when I am away' (v. 1) — i.e., his letters are severe but his personal presence is weak (<em>asthenes</em>, v. 10) and his speech contemptible (<em>ho logos exouthenemos</em>). This reflects Greco-Roman rhetorical values: a true philosopher-orator should have a physically impressive presence and oratorical power (the Sophistic tradition). Paul's physical weakness, possible speech defect (Gal 4:13-14 hints at illness), and refusal to use the Sophists' professional rhetorical techniques made him vulnerable to dismissal. His defense: the weapons of his warfare are not of the flesh (v. 4) — apostolic authority is not measured by Sophistic standards.</p>"
  },
  "11": {
    "22": "<p>Paul's Israelite identity catalogue (v. 22: Hebrews, Israelites, offspring of Abraham) mirrors the probable claims of the 'super-apostles'. 'Hebrews' (<em>Hebraioi</em>) may indicate Aramaic-speaking Jews of Palestinian origin (cf. Acts 6:1); 'Israelites' emphasizes covenant membership; 'offspring of Abraham' likely points to messianic expectations rooted in the Abrahamic promise. Paul matches their credentials item by item — but his rebuttal is that his list of sufferings (vv. 23-33), not his ethnic credentials, authenticates his apostleship. The most extensive catalogue of apostolic hardship in the NT: five floggings, three beatings, stoning, three shipwrecks, dangers from rivers, robbers, compatriots, Gentiles, wilderness, sea, false brothers.</p>"
  },
  "12": {
    "2": "<p>The man caught up to the third heaven / Paradise (vv. 2-4): Paul's apocalyptic-vision tradition belongs to the well-documented Second Temple Jewish literature of heavenly ascent — 1 Enoch, 2 Enoch, 3 Baruch, T. Levi, and later the Hekhalot literature describe journeys through multiple heavens (three, five, or seven, depending on the source). The rabbinic concept of <em>pardes</em> (paradise) as the garden of God in the highest heaven (b. Hagigah 14b — the four who entered pardes) provides context. Paul's reticence (he cannot tell whether in the body or out of the body, vv. 2-3; he refuses to boast about it, v. 5) is the inverse of the typical apocalyptic visionary who boasts of his heavenly journey.</p>"
  }
}

FILL_CH6 = {
  "6": {
    "1": "<p>Paul opens with 'working together' — a claim of collaborative apostolic agency. The Isaianic Servant background (vv. 1-2 cite Isa 49:8) situates Paul within the tradition of the prophetic servant who co-labors with God in the restoration of Israel and the nations. The Second Servant Song (Isa 49:1-7) describes a figure who is frustrated by apparent failure ('I have labored in vain') yet commissioned to be a light to the nations. Paul reads his own apostolate through this lens, making his Corinthian appeal the continuation of the Servant's mission. The call not to receive grace in vain echoes the Servant's charge not to exhaust himself without result.</p>",
    "2": "<p>The citation of Isa 49:8 ('In a favorable time I listened to you, and in a day of salvation I have helped you') transforms the Servant oracle into an eschatological announcement: the 'favorable time' has arrived now, in the apostolic proclamation. This is characteristic of early Christian hermeneutics: the Isaianic promises are not merely fulfilled in Christ's historical ministry but continue to be fulfilled in the ongoing apostolic proclamation. The scrolls from Qumran (4Q176) collected Isaianic comfort-texts for the community awaiting the restoration, evidence that Second Isaiah's 'favorable time' oracles were actively used in contemporaneous Jewish expectation.</p>",
    "3": "<p>Paul's concern not to cause offense in anything reflects the social dynamics of apostolic credibility in an honor-shame culture. In Greco-Roman client-patron society, a missionary's personal conduct was inseparable from his message: a messenger whose character was discredited brought his principal's reputation into question. The hardship catalog that follows (vv. 4-10) is Paul's positive alternative credential: not social status or rhetorical training but endured suffering authenticates his claim to be God's co-worker. This inverts the Sophistic standard that impressed Corinth's status-conscious community.</p>",
    "4": "<p>The hardship catalog form (vv. 4-10) has parallels in Stoic philosophical literature: Epictetus's Discourses list the circumstances (peristaseis) that cannot disturb the wise man's equanimity; Seneca's Letters catalog the sage's endurance of external misfortune. Paul adapts the genre for apostolic self-defense: where the Stoic sage endures hardship through philosophical detachment, Paul endures through divine power working in human weakness. The catalog functions as a social credential in a culture where visible suffering could either shame (the slave's degradation) or honor (the philosopher's contempt for comfort) depending on the interpretive frame applied.</p>",
    "5": "<p>The specific items in the catalog — beatings, imprisonments, tumults, labors, sleepless nights, hunger — map onto Paul's actual documented history (Acts 16:22-24; 2 Cor 11:23-27). Flogging (<em>plēgai</em>) was administered by Jewish synagogue authorities (39 stripes per the Mishnah, m. Makkot 3:1-9) and Roman lictors with rods. Imprisonment in the ancient world was typically pre-trial detention in cramped, dark conditions (the Philippian jail, Acts 16:24; the Mamertine Prison tradition for Rome). 'Tumults' (<em>akatastasiai</em>) reflect the social disorder that apostolic proclamation regularly triggered in cities with mixed Jewish-Gentile populations.</p>",
    "6": "<p>Paul pairs the external hardship list with an inner virtue list: purity, knowledge, patience, kindness, the Holy Spirit, unhypocritical love, the word of truth, the power of God. The structure reflects the ancient philosophical distinction between external circumstances (beyond one's control) and internal character (within one's control — the Stoic <em>prohairesis</em>, the faculty of moral choice). Paul's list of virtues is neither purely Greek nor purely Jewish but draws on both traditions: the Hellenistic virtue catalog meets the Jewish emphasis on wisdom and purity, integrated by the Spirit and love that are distinctively Christian.</p>",
    "7": "<p>The 'weapons of righteousness for the right and left hands' invokes Roman military imagery that Corinthian residents would recognize: the Roman soldier carried the offensive weapon (sword) in the right hand and the defensive shield in the left, producing a coordinated two-sided defense. Roman Corinth was a military colony founded by Julius Caesar in 44 BCE with significant veteran population, and its citizens would immediately visualize the legionary's standard fighting stance. Paul's use of military imagery for apostolic ministry (cf. 10:3-5) participates in the broader Pauline pattern of redeploying Roman martial vocabulary for the gospel's advance.</p>",
    "8": "<p>The antithetical pairs 'honor and dishonor, slander and praise' map directly onto the Greco-Roman honor-shame system that governed social interaction in Corinth. The Roman colony's social hierarchy was acutely sensitive to <em>honor</em> (<em>timē</em>) — inscriptions throughout the ancient Mediterranean document the obsessive tracking of honors, titles, and public recognition. Paul's paradoxical existence — simultaneously occupying honor and dishonor, praise and slander — reflects the ambiguous social position of a Jewish craftsman-philosopher whose message divided households, disrupted patronage networks, and attracted both elite converts (Crispus, Gaius) and slave-class members (1 Cor 1:26-29).</p>",
    "9": "<p>The 'dying and yet we live' paradox resonates with Corinthian cultic language: the mystery religions of the ancient Mediterranean (Eleusinian mysteries, Isis cult, Dionysus cult) all featured death-resurrection symbolism in their initiation rites. Paul's actual near-death experiences (1:9-10; 4:10-12; 11:23-27) ground the paradox in concrete biography rather than ritual symbol. The 'discipline of God' (<em>paideuomenoi</em>) invokes the Jewish understanding of suffering as divine instruction (Prov 3:11-12; Ps 118 LXX) — the affliction that educates rather than destroys, a framework that made sense within Israel's covenantal theology of suffering.</p>",
    "10": "<p>The final pair — 'poor yet making many rich, having nothing yet possessing everything' — reflects the economic realities of Paul's itinerant mission. Ancient artisan-craftsmen like tentmakers occupied the non-elite but non-slave middle of the social spectrum; their income was irregular and their social status ambiguous (Hock, 'The Social Context of Paul's Ministry'). Paul's voluntary refusal to take support from Corinth (1 Cor 9:15-18) meant literal poverty at times. The 'enriching many' is spiritual and eschatological: the wealth Paul distributes is the gospel, which carries no market price but infinite eschatological value in Paul's economy of grace.</p>",
    "11": "<p>The direct address 'Corinthians' — the only vocative use in the letter — marks an emotional peak that reflects ancient rhetorical conventions of <em>apostrophe</em> (direct address to evoke emotional engagement). Paul's 'open mouth' and 'wide heart' toward the Corinthians recalls the Hebrew emotional idiom of 'enlarging the heart' (Ps 119:32; Isa 60:5) for expansive generosity and openness. The Mediterranean emotional culture expressed in the letter's emotional vocabulary was not the restrained Nordic pattern but the openly-demonstrated affection of ancient Mediterranean social relations, where friendship was performed through expressed longing, physical presence, and gift exchange.</p>",
    "12": "<p>Paul's charge that the Corinthians are 'restricted in your own hearts' uses the spatial metaphor of emotional narrowness. In ancient medical theory (Hippocratic corpus; Galen), the heart's emotional capacity was directly connected to the body's actual physical condition — grief literally contracted the heart; joy expanded it. Paul's point is diagnostic: the dysfunction in the apostle-community relationship is located in the community's emotional economy, not in Paul's. The reference to 'affection' (<em>splanchnois</em>, bowels/viscera) as the seat of feeling was universally understood in Mediterranean culture as pointing to the deepest emotional register.</p>",
    "13": "<p>The appeal for 'widened hearts' in return — 'as to children' — invokes the ancient father-child relationship as the model for apostolic-community dynamics. In the Greco-Roman household (<em>oikos</em>), the paterfamilias had total authority over children but ideally expressed this through <em>philanthropia</em> (benevolent love) and education. Paul's adoption of the father-children metaphor (cf. 1 Cor 4:15: 'I became your father through the gospel') places the relationship within the ancient domestic institution but qualifies it: the apostle's authority serves the community's growth, not the apostle's status advancement.</p>",
    "14": "<p>The prohibition against being 'unequally yoked with unbelievers' addresses a concrete Corinthian social challenge: the city's commercial and civic life was saturated with religious practice. Guild meetings were held in temples; civic festivals involved sacrificial meals; business relationships were consecrated by oaths to city deities. The Jewish community in Corinth maintained separation from these practices through strict Torah-observance; Gentile believers faced the same challenge without the established halakhic traditions. The 'unequal yoke' imagery from Lev 19:19 and Deut 22:10 (prohibiting mixed-species plowing) provided scriptural warrant for social-religious boundary maintenance.</p>",
    "15": "<p>'Beliar' (or Belial) as a name for the adversarial power reflects Second Temple Jewish demonology. The Dead Sea Scrolls use Belial extensively as the leader of the forces of darkness opposing the sons of light (1QM 1.1; 1QS 1.18-2.19). The Community Rule at Qumran explicitly frames the community's social boundaries in terms of separation from Belial's domain: members renounce all that belongs to the lot of Belial (1QS 2.4-5). Paul's framing of the Corinthians' dilemma in terms of Christ-versus-Beliar draws on this contemporary Jewish eschatological dualism, though in a missionary (not sectarian) direction.</p>",
    "16": "<p>The question 'what agreement has the temple of God with idols?' had acute force in Corinth, a city with prominent temples to Apollo (the impressive Archaic-period temple still standing), Aphrodite, Poseidon, and the imperial cult. Pausanias's Description of Greece (II.1-4) documents the density of sacred sites. The juxtaposition of 'temple of God' (<em>naos theou</em>) and 'idols' (<em>eidōlon</em>) maps onto the actual urban geography: the Christian community's gathering was an alternative sacred space in a city full of traditional ones. The covenantal formula citations that follow (vv. 16-18) establish the community's identity through OT tabernacle/temple presence texts.</p>",
    "17": "<p>The call to 'come out from their midst and be separate' cites Isa 52:11, an oracle to the exilic community to leave Babylon, purified of its defilements, to carry the temple vessels home. Paul's application to the Corinthian situation continues a pattern of reading the Babylonian exile as a type: just as Israel was called to leave pagan Babylon and return to Zion, so the Gentile believers are called to leave the cultic world of Corinthian paganism. The Qumran community applied similar separation-from-Babylon texts to their own social withdrawal (1QS 8.13: 'separate from the habitation of the perverse men'). Paul's application, unlike Qumran's, does not require physical separation from the city but cultic boundary-keeping within it.</p>",
    "18": "<p>The composite covenant formula — 'I will be a father to you and you will be my sons and daughters' — brings together 2 Sam 7:14 (God's promise to David's heir: 'I will be his father') and Isa 43:6 (the ingathering of sons and daughters from the ends of the earth). The expansion to include 'daughters' (<em>thygateras</em>) alongside sons reflects the new covenant community's inclusive character — women were full members of the eschatological family of God, not just beneficiaries through their fathers or husbands. The citation closes with 'Lord Almighty' (<em>Kyrios Pantokratōr</em>), the LXX's standard rendering of YHWH Tsevaot, invoking divine sovereignty over the whole chain of OT promises.</p>"
  }
}

FILL_CH7 = {
  "7": {
    "1": "<p>The holiness-call of 7:1 — 'let us cleanse ourselves from every defilement of flesh and spirit, perfecting holiness in the fear of God' — follows the catena of separation texts (6:14-18) and grounds the ethical appeal in covenant loyalty. The 'defilement of flesh and spirit' suggests contamination at both the bodily level (perhaps sexual immorality and idolatrous eating) and the spiritual level (divided loyalty in worship). The Jewish purity tradition distinguished physical impurity (Levitical categories: corpse, skin disease, sexual discharge) from moral impurity (Ezekiel's tradition: idolatry, bloodshed, sexual immorality contaminates both person and land). Paul invokes both registers for the new covenant community's holiness.</p>",
    "2": "<p>Paul's triple denial of wrongdoing — 'we wronged no one, we corrupted no one, we exploited no one' — addresses specific accusations apparently circulating in Corinth. The charge of financial exploitation (<em>pleonekteō</em>) was a standard attack on itinerant teachers and philosophers: Dio Chrysostom (Or. 32-35) and Lucian (Peregrinus; Hermotimus) both satirize philosophers who prey financially on their followers. The Cynic tradition's ideal of the philosopher-beggar who neither took money nor demanded support provided one counter-model; Paul's actual practice of manual labor and self-support (1 Cor 9; Acts 18:3) provided another, at the cost of appearing to lack the social status that professional patronage conveyed.</p>",
    "3": "<p>The apostolic solidarity expressed as 'you are in our hearts, to die together and live together' reflects the ancient ideal of friendship (<em>philia</em>) as described by Aristotle (Nicomachean Ethics 9.4) and Cicero (De Amicitia): friends share a common soul, sharing both life and death. The famous Greek friendship formulas (Aristotle's 'one soul in two bodies'; Cicero's 'alter ego') provide the cultural background for Paul's intensity here. But the apostolic friendship transcends the philosophical ideal: Paul is bound to the Corinthians not merely by voluntary affection but by the Spirit-created bonds of a new-covenant community that makes the ancient ideal of soul-friendship a lived social reality.</p>",
    "4": "<p>The bold speech (<em>parrhēsia</em>) Paul claims here was a specific social virtue in Athenian democratic culture: the citizen's right to speak frankly in public assembly, regardless of popular opinion. The Cynics adopted <em>parrhēsia</em> as their philosophical trademark — the Cynic's frank critique of conventional values regardless of social consequences. Epictetus (Discourses 2.12-13; 3.22) describes the Cynic philosopher as the only person with genuine <em>parrhēsia</em> before kings and tyrants. Paul's claim to <em>parrhēsia</em> toward the Corinthians situates him within this philosophical tradition while redefining its basis: his boldness comes not from philosophical independence but from apostolic commission and the community's good character.</p>",
    "5": "<p>The specific mention of 'fighting on the outside, fears on the inside' (v. 5) situates the letter in Paul's known Macedonian travel context. The Macedonian churches (Philippi, Thessalonica, Beroea) had faced intense local opposition (Acts 16:19-40; 17:5-9; 17:13-14), and Philippi in particular had both given Paul substantial support and been a site of legal-religious conflict. The 'fears within' likely refer to anxiety about the Corinthian situation — Paul had sent both Titus and the tearful letter, and was waiting for news. Ancient letter-writing theory (Ps.-Demetrius, On Style; Pseudo-Libanius, Epistolary Styles) emphasized that letters should convey the writer's emotional state as if he were physically present.</p>",
    "6": "<p>The arrival of Titus as the source of consolation illustrates the role of personal messengers in Paul's network. Titus functioned as a trusted apostolic delegate who could both carry letters and represent Paul's interests orally — a combined role of courier, oral spokesperson, and pastoral agent. Ancient letter-writing supplemented rather than replaced face-to-face communication; the bearer of a letter often carried additional oral instructions and could answer questions the letter could not anticipate. The Greco-Roman postal system (the <em>cursus publicus</em>) was available only to those with official government status; private parties relied on trusted travelers and slaves, making Titus's availability and trustworthiness a significant apostolic resource.</p>",
    "7": "<p>The emotional cascade that Titus reported — the Corinthians' 'longing, mourning, and zeal' for Paul — reflects the ancient Mediterranean emotional culture's comfort with intense, publicly-expressed affect. The Hellenistic letter tradition had developed an elaborate vocabulary for expressing longing for an absent friend: the papyri contain dozens of private letters expressing longing for an absent correspondent, grief at separation, and joy at news of their well-being. Paul's emotional life, mediated through the letter-network that connected his separated communities, followed the patterns of intimate Hellenistic friendship correspondence while placing all of it within the framework of apostolic co-suffering and co-consolation (1:3-7).</p>",
    "8": "<p>The 'painful letter' referred to in v. 8 was an intermediate letter Paul wrote to Corinth between 1 and 2 Corinthians, now lost. Scholars call it the 'severe' or 'tearful' letter (referenced in 2:3-4: 'I wrote to you with many tears'). Its content apparently addressed a specific offense — likely the humiliation of Paul or one of his delegates by a Corinthian individual (2:5-8; 7:12). Paul's temporary regret about the letter's severity reflects the ancient emotional dynamics of written communication: a letter written in emotional distress could seem, on reflection, to have exceeded appropriate bounds. The Hellenistic genre of the 'letter of rebuke' (<em>epistolē epitimētikē</em>) had its own social conventions about proportionality.</p>",
    "9": "<p>Paul's distinction between 'being grieved in a godly way' and suffering loss reflects the ancient debate about the value of grief. Stoic philosophy taught that all grief (<em>lypē</em>) was among the four 'passions' (<em>pathē</em>) to be eradicated — the sage should feel neither grief nor excessive joy but <em>eupatheiai</em> (good emotions: joy, caution, wishing). Aristotle had defended a more moderate position: some emotions in proper measure were appropriate. Paul's position is neither Stoic (suppress all grief) nor merely Aristotelian (moderate grief is fine) but theologically functional: grief that moves toward repentance and restoration serves God's purposes, whatever its emotional intensity.</p>",
    "10": "<p>The contrast between 'godly grief' producing 'repentance unto salvation' and 'worldly grief' producing 'death' reflects both Greek philosophical categories and Jewish covenantal patterns. The Hebrew concept of <em>teshuvah</em> (return/repentance) as a full reorientation of life toward God differs from the Greek philosophical emphasis on intellectual reconsideration (<em>metanoia</em> in philosophical contexts often meant a change of mind). Paul's <em>metanoia</em> here is closer to the Jewish covenantal concept: a full turning that affects behavior, relationships, and community structures, not merely an internal emotional resolution. The Qumran penitential psalms (Hodayot) provide contemporaneous evidence of this communal-covenantal grief-and-return pattern.</p>",
    "11": "<p>The seven fruits of godly grief — eagerness, defense, indignation, fear, longing, zeal, punishment — read like a community's formal response to a disciplinary situation. Ancient synagogues had structured procedures for community discipline (m. Sanhedrin; the Damascus Document describes the community's disciplinary process at Qumran). The Corinthian community's response maps these categories onto what appears to have been a formal community process: self-defense by the community against the charge of complicity, indignation at the offense, appropriate fear of apostolic authority, longing to restore the relationship, zeal to correct the situation, and actual administrative punishment of the offender.</p>",
    "12": "<p>Paul's claim that the letter was written 'not for the sake of the one who did wrong, nor for the sake of the one wronged, but so that your care for us might be revealed' provides a pastoral reframing of what must have seemed like personal conflict. The specific individuals — 'the one who wronged' and 'the one wronged' — are deliberately anonymous in this public letter; their identities would have been known to the Corinthian community reading or hearing the letter, but Paul protects them from wider publicity. The ancient letter typically named its third parties; Paul's discretion here may reflect the delicacy of restored relationships and the pastoral principle of not re-opening resolved conflicts for a broader audience.</p>",
    "13": "<p>Titus's refreshed spirit from his Corinthian visit reflects the importance of pastoral face-to-face encounter in ancient ministry. Letter-writing was acknowledged even by its practitioners as a substitute for presence (Seneca, Letters 75.1: 'I prefer that our letters should be as our talk would be if we were sitting in one another's company'). Titus's role as Paul's personal representative gave him authority and pastoral capacity that the letter could not fully replicate. The fact that his spirit was refreshed — not merely that he carried good news — suggests the Corinthians received and honored him in a way that rebuilt the fractured apostolic relationship.</p>",
    "14": "<p>Paul's boasting about the Corinthians to Titus — and the risk of that boast being falsified — illustrates the social dynamics of apostolic networking. Recommendations and reports traveled through the chain of apostolic co-workers, building (or damaging) community reputations across the network. Pliny the Younger's letters (first century CE) show how Roman social networks operated on exactly this basis: a patron's positive recommendation was a social asset for the recommended community; a disappointed expectation brought shame on both the boaster and the recommended party. Paul's relief that his boast 'proved true' is the relief of the patron whose protégés have honored his recommendation.</p>",
    "15": "<p>Titus's 'affection for you that has increased as he remembers the obedience of all of you' points to the specific Corinthian act of welcoming and respecting Paul's delegate 'with fear and trembling.' The phrase 'fear and trembling' (<em>phobos kai tromos</em>) appeared in Exod 15:16 for the nations' terror at God's saving acts; Paul applies it to the Corinthians' reception of Titus as an expression of genuine reverence before apostolic authority. Ancient communities showed their respect for visiting dignitaries through formal reception ceremonies — the <em>adventus</em> (arrival) of an important person triggered civic protocol; the Corinthians' comparable gesture toward Titus demonstrated their restored orientation toward Paul's apostolate.</p>",
    "16": "<p>The chapter closes with complete confidence in the Corinthians — 'I rejoice that I have complete confidence in you in everything' — signaling that the disciplinary crisis of the painful letter has been fully resolved and the relationship restored. This restoration is not sentimental but practical: Paul can now proceed to the collection appeal (chs. 8-9) from a position of relational trust rather than unresolved tension. The ancient letter-writing convention of ending with confidence and goodwill before making a request (the <em>captatio benevolentiae</em>) is amplified here by the genuine emotional arc of the entire section (chs. 1-7): the letter has moved from affliction (1:8) through comfort (1:3-7) through anxious uncertainty (7:5) to restored joy (7:13-16).</p>"
  }
}

FILL_CH8 = {
  "8": {
    "2": "<p>The Macedonian churches' generosity 'in a severe test of affliction' reflects the documented persecution that the Macedonian communities (Philippi, Thessalonica, Beroea) experienced. At Thessalonica, Paul and Silas were driven out by mob violence (Acts 17:5-9); at Philippi, Paul and Silas were beaten and imprisoned (Acts 16:22-24); at Beroea, opponents from Thessalonica followed them to disrupt the mission (Acts 17:13). The 'extreme poverty' of the Macedonian churches was compounded by the social exclusion that accompanied conversion: converts who separated from guild meals and civic festivals lost economic networks and commercial relationships that often provided their livelihood.</p>",
    "3": "<p>The Macedonians' giving 'beyond their ability' reflects the ancient culture of generous benefaction despite limited resources. The Hellenistic benefactor tradition (<em>euergetism</em>) expected the wealthy to fund civic projects and community needs; the Macedonian Christians, not wealthy by ancient standards, gave in a way that inverted the normal class-based expectations. Epictetus (Discourses 1.2.5-7) discusses the philosophical ideal of giving beyond one's apparent means as evidence of genuine value-commitment rather than social calculation. Paul presents the Macedonians as exemplars of a genuinely different giving economy: grace-driven (v. 1) rather than social-obligation driven.</p>",
    "4": "<p>The Macedonians' 'begging earnestly for the favor of taking part in the service to the saints' frames financial giving as a social honor the Macedonians were requesting, not a burden being extracted from them. This inverts the normal social dynamic of charitable solicitation: ordinarily the solicitor begs the potential donor; here the donors beg for the privilege of participating. The 'saints' (<em>hagiois</em>) as the recipients of the collection is Paul's consistent designation for the Jerusalem community — the holy ones whose covenant status in the mother-church of Jewish Christianity gave them a dignity that made caring for them a privilege rather than an obligation.</p>",
    "5": "<p>The sequence 'they gave themselves first to the Lord and then to us by the will of God' describes a two-stage gift that mirrors the covenant-logic of Deuteronomy: Israel's giving to God precedes and grounds their obligations to one another within the covenant community. The Macedonians' self-gift to the Lord is not a mystical act but a concrete commitment to the apostolic mission and its purposes, expressed through the subsequent material giving. The 'will of God' (<em>dia thelēmatos theou</em>) in which they gave 'to us' (Paul and his team) legitimizes the apostolic channel: the collection flows through Paul's team as an expression of divine ordering, not merely human organization.</p>",
    "6": "<p>Titus's prior beginning of the collection in Corinth (he 'started before') refers to an earlier visit — possibly the same visit on which he delivered the painful letter and received the Corinthians' repentance, or a distinct earlier collection-organization visit. Paul's organizational strategy involved multiple envoys working in different communities simultaneously: Titus in Corinth, others in Macedonia and Galatia (Gal 2:10; 1 Cor 16:1-4). This network approach to the collection, coordinating dozens of communities across three to four Roman provinces, was administratively complex and required trusted intermediaries who could represent Paul's instructions and respond to local conditions.</p>",
    "7": "<p>Paul's appeal to the Corinthians to 'excel in this grace also' comes after cataloging their existing spiritual gifts: faith, speech, knowledge, earnestness, love. This gift-catalog echoes 1 Corinthians where the same community's gifts are acknowledged (1 Cor 1:5-7: 'enriched in every way, in all speech and all knowledge'). The Corinthian community was charismatically rich — the problem was channeling those gifts toward the common good rather than individual honor. Adding financial generosity to the list of spiritual gifts challenges the Corinthian tendency to value only spectacular spiritual displays while neglecting the mundane work of concrete solidarity with suffering communities.</p>",
    "8": "<p>Paul's explicit refusal to command the collection — 'I say this not as a command' — reflects both his general pastoral method and the specific social dynamics of financial appeals. In the Greco-Roman patron-client system, gifts extracted by obligation were less socially valuable than gifts given voluntarily: a true benefaction was freely given, not coerced. The Macedonians' self-giving (v. 3-5) provides the positive model of voluntary super-giving; the comparison motivates without demanding. Ancient moralists (Seneca, On Benefits; Cicero, De Officiis 2) discussed at length the ethics of benefaction, arguing that the manner of giving was as important as the gift's size.</p>",
    "9": "<p>The description of Christ 'becoming poor' for the Corinthians' enrichment reflects the common early Christian application of the Incarnation to ethical imperatives. The Jewish Wisdom tradition described divine Wisdom descending from heaven to dwell among humanity (Sir 24; Prov 8:22-31; Wis 9:10) — Paul's claim that the pre-existent Lord became economically destitute for human benefit applies this descent-pattern to concrete economics. The philosophical tradition had its own version: the Stoic sage voluntarily accepts poverty as an expression of philosophical freedom (Epictetus was a slave; Diogenes lived in a tub). Paul's Christ-model goes further: the wealth-to-poverty movement is not philosophical posturing but salvific self-expenditure.</p>",
    "10": "<p>Paul's reference to the collection 'a year ago' provides chronological data for reconstructing the Pauline mission timeline. The collection was apparently planned during Paul's 18-month stay in Corinth (Acts 18:1-18, ca. 49-51 CE) and organized through the multiple communities during the period between 1 and 2 Corinthians. The 'year ago' places the Corinthians' initial enthusiasm well before the writing of 2 Corinthians, suggesting the painful-letter crisis had disrupted the collection project. Now that relational repair (ch. 7) is accomplished, Paul can resume the practical request.</p>",
    "11": "<p>The principle of giving 'out of what you have' engages the ancient philosophical discussion of proportional giving. Aristotle (Nicomachean Ethics 4.1) described the virtue of <em>eleutheriotēs</em> (liberality) as giving in proportion to one's means — neither miserly (withholding what one can give) nor profligate (giving more than one has). Jewish law had similar proportionality principles: the tithe (10% of produce) and the poor-tithe (ma'aser 'ani) were proportional requirements, not fixed amounts. Paul's standard of 'out of what you have' places him within a broad ancient consensus on proportional giving while embedding it in the grace-and-freedom framework of the new covenant.</p>",
    "12": "<p>The acceptability of giving 'according to what a person has' reflects the ancient Jewish principle articulated in the Mishnah (m. Peah 1:1): the corners of the field left for the poor were calibrated to the field's size. The Jerusalem Talmud documents discussion of how poor farmers with small fields fulfilled the gleanings obligation. Paul's practical pastoral accommodation to the Corinthians' variable economic capacities engages these same ancient proportionality debates: the collection cannot be administered as a one-size-fits-all extraction but must reflect the diversity of economic circumstances within the community.</p>",
    "13": "<p>The principle of equality (<em>isotēs</em>) as the goal of the collection reflects Greek democratic ideals and Jewish covenantal ethics simultaneously. In Athenian democracy, <em>isotēs</em> (equality) was a foundational civic value; Pericles' Funeral Oration (Thucydides 2.37) cites equality before the law as Athens's great achievement. In the Covenant Code, the goal of the sabbatical year and the Jubilee was redistribution to prevent permanent poverty (Lev 25). Paul's appeal to equality in the collection draws on both traditions to argue that the economic solidarity of the one body of Christ (1 Cor 12) should find expression in concrete material redistribution across the network.</p>",
    "14": "<p>The mutual-need exchange — Corinthian material surplus addressing Jerusalem's need; Jerusalem's spiritual surplus previously addressing Corinth's spiritual need — articulates the economic logic of the body of Christ as a redistributive network. Romans 15:27 makes the logic explicit: 'the Gentiles have shared in their spiritual blessings, so they ought also to serve them in material blessings.' This is not merely practical charity but covenantal solidarity: the Gentile communities owe a debt of spiritual inheritance to the Jewish community through which the gospel came to them, expressed now through material support. The collection is an economic enactment of the theological argument of Romans 9-11.</p>",
    "15": "<p>The manna citation (Exod 16:18: 'the one who gathered much had no excess, and the one who gathered little had no shortage') applies the wilderness provision principle to the collection. The rabbinic tradition read the manna narrative as illustrating divine proportional provision: God's daily bread was calibrated to each household's need (b. Yoma 75b; Mekhilta on Exod 16:17-18). The miracle of the manna was not superhuman quantity but perfect adequacy — each person had exactly enough. Paul uses this as the template for the collection's intended outcome: mutual provision calibrated to need, neither wasteful excess on one side nor grinding shortage on the other.</p>",
    "16": "<p>Paul's thanksgiving for Titus's God-given earnestness places apostolic motivation within the framework of divine gift. The ancient philosophical ideal of the morally serious person (<em>spoudaios</em>, the earnest one) who cares about the things that truly matter was a standard of character in both Stoic and Platonic traditions. Paul baptizes the philosophical character ideal: Titus's earnestness for the Corinthians' good is not his own philosophical achievement but a gift placed in his heart by God. This frames the entire apostolic network's motivation as Spirit-generated, not merely admirable human virtue — a distinction with practical implications for community trust.</p>",
    "17": "<p>Titus's going 'of his own accord' — voluntarily, without needing Paul's command — reinforces the freedom-in-service pattern central to chs. 8-9. Ancient patronage systems created complex obligations that could burden both patron and client: the client who had received benefits was expected to reciprocate in specific ways on schedule. Paul consistently presents apostolic relationships as transcending this obligatory pattern: Titus gives his presence to Corinth freely because he genuinely cares, not because Paul has commanded him. The contrast with the obligatory system makes Titus's voluntary service a concrete instantiation of the grace-economy Paul is constructing through the entire collection argument.</p>",
    "18": "<p>The anonymous 'brother famous among all the churches for his preaching of the gospel' has generated extensive scholarly speculation. Leading candidates include Luke (whose travel with Paul is indicated by the 'we' passages of Acts), Barnabas (Paul's early partner, known to the Corinthians), and Apollos (Acts 18:24-28; 1 Cor 1:12; 3:5-6). The deliberate anonymity may protect the individual from identification by enemies, reflect diplomatic discretion in a politically sensitive letter, or simply indicate that the Corinthians would have known him by name from oral communication. The multi-person delegation (Titus + brother + another brother, v. 22) provides accountability for the collection that individual handling could not.</p>",
    "19": "<p>The appointment of the anonymous brother 'by the churches' to travel with Paul reflects the early development of inter-church administrative structures for financial accountability. The Jewish synagogue's use of two or three official witnesses for financial transactions (m. Bava Batra 10:3) provided a model; Roman commercial law required witnesses for valid transactions. The phrase 'for the glory of the Lord himself and to show our good will' places the administrative accountability structure in a theological frame: practical financial governance serves both divine honor and apostolic integrity. This combination of theology and management was characteristic of Paul's administrative style.</p>",
    "20": "<p>Paul's explicit concern that 'no one should blame us in this generous gift' reflects documented tensions about apostolic financial management in the ancient church. 1 Clement (later, ca. 96 CE) and the Didache (ca. 100 CE) both address concerns about itinerant prophets and teachers exploiting community hospitality and generosity. Lucian of Samosata's satirical account of Peregrinus (a Christian leader who exploited community generosity) illustrates how apostolic financial misconduct could discredit entire movements. Paul's advance accountability through the three-person delegation preempts both the accusation and the reality of financial exploitation, protecting the gospel's credibility through administrative transparency.</p>",
    "21": "<p>The appeal to 'what is honorable before the Lord and before people' (citing Prov 3:4 LXX) engages both vertical (divine) and horizontal (social) accountability. Roman public life made heavy use of honorability (<em>honestas</em>) as a social standard: the <em>vir bonus</em> (good man) was recognized by both his peers and his divine patrons. Paul's dual accountability formula — before God and before people — refuses the dichotomy that would separate inner spiritual integrity from social transparency. The collection's handling must be visibly honorable in the community's eyes as well as genuinely honorable in God's — because the gospel's public credibility depends on the apostle's public conduct.</p>",
    "22": "<p>The third delegate — another unnamed brother tested and found earnest in many matters — completes the accountability structure. The Corinthians would have recognized all three delegates by name; Paul's reticence in the written letter preserved a degree of privacy appropriate to a potentially hostile reading environment (letters in antiquity were routinely read aloud in public gatherings and could be intercepted). The testing (<em>edokimasamen</em>) of the brother 'in many matters' over time reflects the ancient community's practice of evaluating character through track record — the Latin <em>probatio</em> (proof/testing) was a social process by which trust was earned and verified over repeated interactions.</p>",
    "23": "<p>The identification of the delegates as 'messengers of the churches' and 'the glory of Christ' places their practical mission within the highest theological register. In Jewish tradition, the <em>shaliach</em> (agent/messenger) carried the authority of the sender: 'a man's agent is as the man himself' (m. Berakhot 5:5). The Pauline apostolic network operated on this principle: Titus and the brothers represent Paul who represents Christ, in a chain of authorized representation. 'The glory of Christ' as a description of the delegates is remarkable — they are not merely functionaries but the embodiment of Christ's honor in the practical work of the collection's administration.</p>",
    "24": "<p>The appeal to 'show them the proof of your love and of our boasting about you before the churches' mobilizes Corinthian honor-consciousness in the service of the collection. In the ancient city, public reputation was managed carefully: what one city's community did was observed and reported throughout the network of connected communities. Paul's boasting about Corinth to Titus (v. 14) and to Macedonia (9:2) means the Corinthians' response to the collection will be watched and reported. The appeal to demonstrate love 'before the churches' transforms the individual giving act into a public community statement — the Corinthians' generosity or stinginess will define their reputation in the wider apostolic network.</p>"
  }
}

FILL_CH9 = {
  "9": {
    "1": "<p>Chapter 9 resumes the collection appeal with a fresh rhetorical strategy: Paul claims writing about it is superfluous, then writes at length. This <em>praeteritio</em> device (ostensibly passing over a subject while actually discussing it) was a standard technique of ancient rhetoric documented in Quintilian (Institutio Oratoria 9.2.47). The 'ministry for the saints' (<em>diakonia tēs eis tous hagious</em>) was a genuine institutional project with multiple communities participating: Gal 2:10 records it as a condition of Paul's Jerusalem agreement; 1 Cor 16:1-4 shows Galatian and Corinthian participation; Romans 15:25-28 confirms the collection's eventual delivery to Jerusalem.</p>",
    "2": "<p>Paul's boast to the Macedonians that 'Achaia has been ready since last year' illustrates the competitive communal dynamics he intentionally created around the collection. Ancient Mediterranean gift culture was deeply competitive: benefactors competed for public honor; communities competed for prestige. Paul redirects this competitive energy toward mutual generosity: each community's zeal motivates the other. The Macedonians were moved to give by the Corinthians' example (v. 2); the Corinthians are now moved to complete what they began by the Macedonians' generosity (8:1-5). This cross-fertilization of communal emulation was a sophisticated pastoral strategy for maintaining momentum across separated communities.</p>",
    "3": "<p>The sending of the brothers 'in advance' (v. 3: <em>epempsa tous adelphous</em>) so that the collection is ready when Paul arrives reflects the practical logistics of the ancient collection project. Travel in the ancient Mediterranean required advance planning: the sailing season (late March to late October) constrained movement; overland travel was slow; community preparations for a major financial act required time. Paul's advance delegation gave the Corinthians time to gather the collection before Paul's arrival with Macedonian companions — avoiding the social embarrassment of an unprepared community in front of witnesses.</p>",
    "4": "<p>The social embarrassment at stake — being found 'unprepared' by the Macedonians who accompany Paul — reflects the acute shame-consciousness of ancient Mediterranean communities. In the honor-shame culture of the Greco-Roman world, public humiliation before one's peers and social equals was among the most damaging social experiences possible. Plutarch (On Complaisance 18) discusses how shame functions as a social regulator; the community's embarrassment at being found to have exaggerated their readiness would have real social and reputational consequences. Paul is not merely appealing to abstract virtue but to the Corinthians' concrete social interest in maintaining their network reputation.</p>",
    "5": "<p>The distinction between a 'voluntary gift' (<em>eulogia</em>, blessing) and 'an exaction' (<em>pleonexia</em>, covetousness/extortion) identifies the two economic frames that could characterize the collection depending on how it was administered. In ancient patronage systems, 'gifts' extracted under social obligation were functionally indistinguishable from tribute — the patron expected reciprocal benefits and the client felt compelled to give. Paul insists the collection must remain in the <em>eulogia</em> category: a freely given expression of blessing, not a tribute extracted by apostolic authority. The advance preparation ensures it is ready before Paul arrives, removing the pressure of his physical presence.</p>",
    "6": "<p>The agricultural sowing-and-reaping principle invoked in v. 6 draws on the basic economic reality of the ancient agricultural world, where most people's livelihoods depended directly on the annual harvest cycle. The maxim 'you reap what you sow' was a universal folk wisdom across the ancient Mediterranean — Greek proverbs (Galatians 6:7 cites the Hellenistic version), Jewish Wisdom literature (Prov 22:8 LXX), and agricultural treatises (Columella, De Re Rustica) all use this pattern. Paul applies it to the giving economy of the collection: generous sowing produces generous harvest, not merely as a spiritual metaphor but as a description of how God's economy actually works.</p>",
    "7": "<p>'God loves a cheerful giver' cites LXX Prov 22:8a (in some manuscript traditions), a wisdom maxim that circulated widely in the ancient Jewish world. The Sirach tradition on almsgiving (Sir 35:11-13: 'give to him as he has given to you, with a cheerful eye and as much as you can, for the Lord repays and will give you seven times as much') represents the same wisdom tradition Paul is drawing from. The Didache (15.4) later cites the cheerful-giver principle for the support of prophets and teachers. Paul's application of Wisdom's giving principle to the Jerusalem collection situates the collection within the long tradition of Jewish charitable giving as an expression of covenant loyalty.</p>",
    "8": "<p>The Stoic concept of <em>autarkeia</em> (self-sufficiency) is here appropriated and transformed. For Diogenes Laertius (6.104-105) and Epictetus, <em>autarkeia</em> was the philosophical achievement of the sage who needs nothing external — contentment through philosophical detachment. Paul's version is radically different: <em>autarkeia</em> is God-given, not self-achieved, and its purpose is not detachment from the world but superabundant generosity toward it. The sufficient person is sufficient precisely so they can give beyond sufficiency. This is the economic paradox of grace: God's provision is never for mere private accumulation but for productive outward-flowing generosity.</p>",
    "9": "<p>The citation of LXX Ps 111:9 (ET 112:9: 'he has distributed freely, he has given to the poor; his righteousness endures forever') applies a psalm about the righteous/generous person to the principle of God's own giving. The psalm's portrait of the blessed righteous person who fears God and delights in his commands — and whose righteousness endures forever — is a stock portrait in the Wisdom tradition (Pss 1, 112; Prov 11:24-25; Sir 11:14-28). Paul's application both maintains the human reference (the Corinthian giver whose righteousness-through-giving endures) and hints at the divine reference (God himself is the ultimate generous distributer).</p>",
    "10": "<p>The image of God as the 'one who supplies seed to the sower and bread for food' (citing Isa 55:10 and Hos 10:12 LXX) situates the collection within Israel's agricultural theology of divine provision. Isa 55:10 describes God's word going out and not returning without producing its intended harvest — the natural agricultural cycle as a type of the word's productive power. Paul extends the metaphor: God who supplies physical seed for physical sowing also multiplies the 'seed' of financial generosity and increases the 'harvest' of righteousness. The agricultural imagery is not ornamental but structural: it reflects the actual covenantal economy in which God is both the source and multiplier of all good gifts.</p>",
    "11": "<p>The chain of enrichment → generosity → thanksgiving reflects the ancient Mediterranean's understanding of gift-giving as embedded in social relationships. Aristotle's analysis of the complete gift (Nicomachean Ethics 4.1) emphasized that a true benefaction was given freely, without calculation of return, but nonetheless generated genuine gratitude. Seneca's On Benefits is an extended meditation on how the gift-cycle (giving, receiving, and returning thanks) constitutes the bonds of society. Paul transforms this social theory: the Christian gift-cycle flows through God (who gives → humans who give freely → recipients who give thanks back to God), creating a circuit of grace in which human generosity is always secondary to divine generosity.</p>",
    "12": "<p>The collection functions simultaneously as <em>diakonia</em> (service/ministry — a concrete act of meeting material need) and <em>leitourgia</em> (liturgy — a public service act with cultic overtones). In Athenian civic life, the <em>leitourgia</em> was the wealthy citizen's obligation to fund a public necessity (triremes, dramatic festivals, gymnasia) at personal expense. Paul's application of the term to the collection elevates financial giving from charitable transaction to public worship — the collection is a liturgical act that glorifies God through its generosity and generates the thanksgiving (eucharistia) of those who receive it. The material and spiritual dimensions of the act are inseparable.</p>",
    "13": "<p>The Jerusalem community's glorification of God for the Corinthians' 'obedience in acknowledging the gospel of Christ' treats the collection as an act of confessional witness. In the ancient world, economic solidarity between communities was a powerful social signal of genuine relationship: when Gentile Christians in wealthy Corinth sacrificed economic resources for impoverished Jewish Christians in Jerusalem, it demonstrated that the gospel's claim — that there is neither Jew nor Gentile, that all are one in Christ Jesus (Gal 3:28) — had actual social content. The collection was not merely charity but enacted theology: living proof that the new creation community transcended ethnic and economic divisions.</p>",
    "14": "<p>The Jerusalem community's prayer for the Corinthians — provoked by witnessing God's surpassing grace in them — illustrates the network of intercession that connected the early church's scattered communities. Jewish communal prayer in the synagogue included prayers for the welfare of communities in other locations; the Amidah's petitions for Israel's restoration assumed a pan-diaspora network of mutual concern. Paul envisioned the collection creating a similar network of mutual prayer and concern across the Jewish-Gentile divide: Jerusalem would pray for Corinth; Corinth would give for Jerusalem; both would glorify the God whose grace exceeded all ethnic and economic barriers.</p>",
    "15": "<p>The doxological close — 'thanks be to God for his inexpressible gift' — identifies the whole collection enterprise within the framework of divine gift that exceeds human description. The 'inexpressible gift' (<em>anekdiēgētos dōrea</em>) is Paul's only use of this extraordinary compound adjective in the NT. The tradition of divine gifts beyond human expression — the <em>aposiopesis</em> (silence before what cannot be said) in Hellenistic religious texts; the Jewish apophatic tradition before the name of God — provides context. Paul's <em>charis tō theō</em> (thanks be to God) doxology opens and closes chapters 8-9 (cf. 8:16), framing the entire collection appeal as a response to grace rather than a demand for generosity.</p>"
  }
}

FILL_CH10 = {
  "10": {
    "2": "<p>Paul's request not to have to 'be bold' when present against those who suspect him of 'walking according to the flesh' addresses the opponents' characterization of his apostolic style. The charge of 'walking according to the flesh' (<em>kata sarka peripatein</em>) likely meant using ordinary human power-strategies — social networking, rhetorical display, financial patronage — rather than genuine spiritual authority. This was the standard Sophistic critique of a rival: reducing his effectiveness to mere human technique rather than divine inspiration. The Second Sophistic (the Greek rhetorical revival of the first through third centuries CE) was just developing in Paul's lifetime; Corinth was a prime venue for Sophistic performance and competition.</p>",
    "3": "<p>The distinction between 'living in the flesh' and 'waging war according to the flesh' addresses a misunderstanding about Paul's embodied apostolic existence. Paul's opponents apparently equated his manual labor, physical weakness, and non-professional rhetoric with a fundamentally worldly ('fleshly') approach to ministry. The philosophical context: Cynics like Diogenes deliberately emphasized bodily simplicity and roughness as markers of philosophical authenticity; Stoics cultivated bodily discipline; neither would have characterized manual labor as 'fleshly.' Paul's response: the mode of ministry (humble, suffering, non-Sophistic) is determined not by the flesh's standards but by divine calling and pneumatic power.</p>",
    "4": "<p>The military metaphor of 'weapons of warfare' that have 'divine power to destroy strongholds' would have resonated immediately in Roman Corinth — a military colony founded by Julius Caesar. The Roman legionary with his standardized armament (<em>gladius</em>, <em>pilum</em>, <em>scutum</em>) was the most powerful military force in the ancient world, and Corinthian culture absorbed Roman military values. Siegecraft (<em>poliorkia</em>) — the systematic assault and demolition of fortified positions — was a major area of Roman military engineering (Josephus, Jewish War, describes Roman siege operations at Jerusalem in vivid detail). Paul applies this familiar martial imagery to the intellectual-spiritual campaign against false teaching.</p>",
    "5": "<p>The 'demolition of arguments' (<em>logismous kathairountes</em>) reflects the Greco-Roman educational background in which logic, rhetoric, and philosophical argumentation were the primary intellectual weapons. The Sophistic tradition trained students to construct and demolish arguments — <em>dialektikē</em> (dialectic) and <em>rhetorikē</em> (rhetoric) were core subjects in the ancient curriculum. Paul's claim that apostolic warfare has power to demolish these intellectual constructions is an epistemological claim: the gospel's power relativizes even the most sophisticated philosophical argumentation, rendering it unable to resist 'the knowledge of God.' The context is the specific intellectual pretension that was shielding the opponents' false teaching from apostolic challenge.</p>",
    "6": "<p>Paul's readiness to 'punish every disobedience when your obedience is complete' reflects the ancient disciplinary structure of the apostolic community. The Qumran community's disciplinary codes (1QS 5.24-6.1; Damascus Document) specified procedures for addressing community violations: accusation before witnesses, community deliberation, appropriate punishment. The Jewish synagogue had similar structures (m. Sanhedrin; m. Makkot). Paul's disciplinary authority as apostle is analogous but community-mediated: the majority's restored compliance creates the context within which the minority's recalcitrance can be addressed without destroying the community's cohesion.</p>",
    "7": "<p>'Look at what is before your eyes' addresses the Corinthian community's perceptual framework — specifically, their assessment of who is authentically 'Christ's.' The opponents apparently claimed a special relationship to Christ (pneumatic experiences, direct commission, Hebrew heritage) that Paul's community-building work could not match. The phrase 'if anyone is confident he is Christ's' may echo the opponents' specific rhetoric: they identified themselves as Christ-people over against Paul's supposedly inferior apostolate. Paul's response appeals to the observable evidence — the Corinthian community itself — as the proof of his apostolic legitimacy rather than subjective spiritual claims.</p>",
    "8": "<p>Paul's authority for 'building up and not tearing down' reflects a consistent construction metaphor (the Greek <em>oikodomē</em>) that appears throughout both Corinthian letters (1 Cor 3:9-15; 14:4, 12, 26; 2 Cor 12:19; 13:10). The image of the community as a building under construction being built by the apostle was a natural metaphor in a city undergoing major building projects — the Roman colonia of Corinth was still being physically constructed in Paul's time, with the Temple of Apollo (archaic period) dominating the Acrocorinth while new Roman-period structures were being added. The building metaphor made the apostolic project concrete: the community is under construction, and the builder's authority must be exercised for the building's benefit.</p>",
    "9": "<p>Paul's concern about 'appearing to be frightening you by letters' addresses the disconnect between epistolary boldness and personal restraint that his opponents were exploiting. The ancient Mediterranean had well-developed conventions for distinguishing appropriate letter-boldness from inappropriate. Seneca (Letters 75.1-2) argues that a letter should be like a conversation between friends — frank but not aggressively confrontational. The opponents apparently weaponized Paul's letter-severity to characterize him as a cowardly bully: brave on papyrus, timid in person. Ancient epistolary theory held that letters should reflect the writer's genuine character; the implication of the opponents' charge was that Paul's character was fundamentally dishonest.</p>",
    "10": "<p>The specific criticism — 'his letters are weighty and strong, but his bodily presence is weak and his speech contemptible' — reflects the Sophistic evaluation criteria for legitimate philosophical authority in Corinth. The Second Sophistic tradition valorized the impressive physique, authoritative bearing, and oratorical power of the professional rhetorician. Favorinus, Dio Chrysostom, and later Aelius Aristides exemplified the Sophist ideal: commanding presence, polished delivery, witty repartee. Paul's physical appearance (ancient descriptions, including the Acts of Paul, mention a small, bow-legged man with meeting eyebrows) and possible speech impediment (Gal 4:13-14; the 'thorn in the flesh') made him vulnerable to dismissal by those who applied Sophistic standards.</p>",
    "11": "<p>Paul's claim that his 'word by letter when absent' and his 'deed when present' will match establishes the ancient test of character: consistency between speech and action, between private and public conduct, between letter and presence. The philosophical ideal of the integrated person (<em>holos anthrōpos</em> in Stoicism; <em>kalos kagathos</em> in aristocratic Greek culture) who is the same in all circumstances was a standard character-test. Paul's opponents apparently claimed he failed this test — brave in letters, timid in person. His response is not to deny the difference in register (letters versus presence) but to predict that his actual behavior when present will vindicate his written boldness.</p>",
    "12": "<p>The critique of 'comparing themselves with themselves' (<em>synkrinomtes heautous heautois</em>) addresses the self-referential evaluation system the opponents were using. In Corinthian honor culture, reputation was assessed by comparison with one's peers — the inscription records of ancient cities show competition for position on the civic honor-roll. The Sophistic tradition created its own evaluation system: who had the best rhetorical reputation, the most impressive pupil list, the most successful public performances. By operating within this self-referential system, the opponents could declare themselves superior without any external standard of comparison. Paul refuses this game by appealing to the divine-assigned <em>kanōn</em> (sphere of authority) as the only legitimate measure.</p>",
    "13": "<p>The concept of the <em>kanōn</em> (measuring line/sphere of authority) assigned by God reflects the ancient practice of defining territories and jurisdictions. In Hellenistic administration, regions were assigned to officials with defined boundaries; Roman provincial administration was built on precisely delimited territorial responsibility. Paul's apostolic 'territory' was defined at Jerusalem (Gal 2:7-9: 'the gospel to the uncircumcised was committed to Paul as the gospel to the circumcised was to Peter'). Corinth fell within this territory as a Gentile-majority city where Paul was the founding apostle. The opponents' incursion into his territory violates the Jerusalem agreement, not merely Paul's personal preference.</p>",
    "14": "<p>Paul's claim to have 'come all the way to you with the gospel of Christ' establishes the chronological priority of his apostolic presence in Corinth. The city was on Paul's established mission route from Ephesus westward through Macedonia and Achaia, and his initial 18-month stay (Acts 18:1-18) was the foundational mission event. In ancient patron-client networks, the one who first established a relationship had ongoing claims of loyalty: the first patron's rights could not simply be displaced by a newcomer's arrival. Paul's priority of arrival is not merely a point of pride but a claim to the relational loyalty the Corinthians owed their founding apostle.</p>",
    "15": "<p>Paul's hope that 'as your faith grows, our field among you may be greatly enlarged' connects the Corinthians' spiritual maturation to the expansion of the mission westward. This reflects the geographical logic of Paul's mission strategy as described in Romans 15:20-24: having completed the eastern arc from Jerusalem to Illyricum, he intended to move west through Corinth to Spain. The Corinthian community's stability and financial partnership (cf. Rom 15:24: 'helped on my way there by you') was essential for the Spanish mission project. Paul's pastoral investment in Corinth was inseparable from his missionary ambition for the unreached western Mediterranean.</p>",
    "16": "<p>'Preaching the gospel in lands beyond you' (v. 16) points to Paul's western mission ambition — Spain, as Romans 15:24, 28 makes explicit. Spain was the far western edge of the Roman world, culturally Latin rather than Greek, representing a genuinely new mission frontier. Paul's ambition not to 'build on another's foundation' (v. 16; cf. Rom 15:20) reflects both apostolic etiquette and strategic mission logic: where there is no Christian presence, the pioneer missionary has maximum freedom and maximum potential impact. The Spanish mission remained Paul's ambition even as the Jerusalem trip (Rom 15:25-28) and subsequent Roman imprisonment (Acts 21-28) intervened.</p>",
    "17": "<p>The citation of Jer 9:23-24 ('let the one who boasts boast in the Lord') was a widespread Jewish anti-pride text applied in various contexts to counter the human tendency toward self-glorification. Ben Sirach (Sir 10:26-11:1) develops the same theme against those who glory in wealth, beauty, or status. The Dead Sea Scrolls use the 'boasting in God' principle in community hymns (1QH 9.23-24). Paul's use of the same Jeremiah text in 1 Cor 1:31 to address Corinthian wisdom-pride shows this was a consistent Pauline counter-move: whenever human-glory competition erupts (whether over wisdom, rhetorical skill, or apostolic status), the prophetic word redirects all boasting to God.</p>",
    "18": "<p>The final verdict — 'it is not the one who commends himself who is approved, but the one whom the Lord commends' — applies the ancient standard of ultimate divine evaluation to the apostolic legitimacy debate. In Roman law and public life, <em>probatio</em> (proof/approval) could be established through recognized credentials, letters of recommendation, community testimony, or direct demonstration of ability. Paul's opponents brought letters of recommendation (3:1) and demonstrated Sophistic ability. Paul's 'approval' (<em>dokimasia</em>) is eschatological: the Lord's verdict, rendered at the judgment seat (5:10), is the only commendation that ultimately matters. This eschatological reframing of the credentialing debate is characteristic of Paul's move to redirect human competition toward divine evaluation.</p>"
  }
}

def main():
    existing = load_comm('mkt-context', '2corinthians')
    merge_comm(existing, CONTEXT)
    merge_comm(existing, FILL_CH6)
    merge_comm(existing, FILL_CH7)
    merge_comm(existing, FILL_CH8)
    merge_comm(existing, FILL_CH9)
    merge_comm(existing, FILL_CH10)
    save_comm('mkt-context', '2corinthians', existing)
    total = sum(len(v) for v in existing.values())
    print(f'2 Corinthians mkt-context: {len(existing)} chapters, {total} verses.')

if __name__ == '__main__':
    main()
