"""
mkt-context — 2 Kings 9–11
run: python3 scripts/zc-context-2kings-9-11.py

Ch9: Jehu anointed at Ramoth-gilead; Joram and Ahaziah killed; Jezebel thrown
Ch10: Seventy heads at Samaria gate; Jonadab; Baal temple destroyed
Ch11: Athaliah's usurpation; Jehosheba hides Joash; Jehoiada's coup
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(layer, book):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    return json.loads(p.read_text()) if p.exists() else {}

def save_comm(layer, book, data):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

KINGS2_CONTEXT = {
  "9": {
    "1": "<p>Elisha sends one of the sons of the prophets to Ramoth-gilead to anoint Jehu. Ramoth-gilead (identified with Tell ar-Rumeith in the Gilead region of modern Jordan) was a strategic border fortress contested between Israel and Aram; it had been the site of Ahab's fatal battle (1 Kgs 22) and where Joram was wounded (2 Kgs 8:28-29). A prophetic anointing in the military camp, not the palace, signals that this is a military coup authorized by divine commission.</p>",
    "2": "<p>The young prophet is to find Jehu son of Jehoshaphat son of Nimshi among the army officers, bring him to an inner chamber (<em>ḥeḏer bəḥāḏer</em> — literally room within room, i.e., an inner room away from witnesses), and anoint him. The secrecy is tactically necessary: a prophetic anointing in the officers' mess would trigger immediate confrontation with the commander.</p>",
    "3": "<p>The anointing formula: pour oil on his head and say 'Thus says YHWH: I anoint you king over Israel.' The messenger is then to flee without delay — the anointing is a one-way prophetic act; there is no negotiation or ceremony, only the word and departure. The economy mirrors the urgency of a military operation.</p>",
    "4": "<p>The young man goes to Ramoth-gilead. The officers are sitting together — the military council (a <em>sereḏ</em> or officer assembly) — when the prophet arrives and addresses Jehu directly in their presence, then withdraws to the inner chamber.</p>",
    "5": "<p>When Jehu follows to the inner room, the prophet pours oil and delivers the oracle: YHWH's anointing of Jehu over Israel as king, and the specific commission — strike the house of Ahab to avenge the blood of YHWH's servants the prophets, and all YHWH's servants killed by Jezebel. This connects to Elijah's complaint (1 Kgs 19:10: 'they have killed your prophets') and the Naboth oracle (1 Kgs 21:19-26).</p>",
    "6": "<p>The commission is grounded in covenant justice: Ahab's house is to be destroyed just as the houses of Jeroboam son of Nebat and Baasha son of Ahijah were destroyed. The dynastic-destruction pattern from 1 Kings is now being applied to the third apostate dynasty of the north; YHWH is consistent in the covenant sanctions he announced.</p>",
    "7": "<p>The specific charge against Jezebel: her killing of YHWH's prophets. The whole house of Ahab shall perish, and YHWH will make the house of Ahab like the houses of Jeroboam and Baasha — the two previous dynasties God destroyed. The oracle is a comprehensive death sentence on the Omride line.</p>",
    "8": "<p>The prophet then flees — exactly as instructed. The brevity and stealth of the anointing protect the prophet from immediate political retaliation and allow Jehu to control the timing of the coup himself.</p>",
    "9": "<p>Jehu returns to the officers who ask what the madman (<em>hamməšuggāʿ</em>) wanted. <em>Məšuggāʿ</em> (from <em>šāgaʿ</em>, to be mad) is the term Shemaiah calls Jeremiah in Jer 29:26 — prophets were commonly dismissed as madmen; the officers' language reflects the low social estimation of ecstatic prophets among military professionals.</p>",
    "10": "<p>When Jehu reveals the oracle, the officers immediately affirm him: they take their garments (<em>bigdêhem</em>), put them under him on the bare steps, blow the trumpet, and declare 'Jehu is king!' The spontaneous use of garments as a makeshift throne and the trumpet as coronation signal reproduce the ad hoc royal acclamation of 1 Kgs 1:33-40 (Solomon) without the court apparatus. This is a field coronation.</p>",
    "11": "<p>Jehu immediately moves to prevent intelligence reaching Jezreel before him. He gives orders that no one escape the city to go tell it in Jezreel — information control is the tactical precondition for a successful coup against a sitting court.</p>",
    "12": "<p>Jehu drives to Jezreel — Joram is recuperating there from his wound at Ramoth-gilead (8:29). The watchman on the Jezreel tower reports: a company is coming from the direction of Ramoth-gilead; then reports the messenger Joram sent is not returning; the watchman reports another rider dispatched to meet Jehu, and he also does not return.</p>",
    "13": "<p>Jehu is recognized from a distance by characteristic driving style: <em>kəmišpat Yēhûʾ ḇen-Nimšî kî ḇəšiggāʿôn yinhag</em> — 'it is like the driving of Jehu son of Nimshi, for he drives furiously.' <em>Šiggāʿôn</em> is cognate with <em>šāgaʿ</em> (madness); ironically the officers called the prophet a madman (<em>məšuggāʿ</em>) and the watchman identifies Jehu by his mad driving. The reputation for reckless speed defines his character.</p>",
    "14": "<p>Joram orders his chariot harnessed and rides out with Ahaziah king of Judah to meet Jehu. The two kings ride together — Joram the wounded, Ahaziah his nephew — without recognizing the danger.</p>",
    "15": "<p>They meet Jehu at the plot of Naboth the Jezreelite. The geographic detail is precise and theologically loaded — this is the very field Ahab seized after Jezebel arranged Naboth's murder (1 Kgs 21). The meeting point makes the execution a visible fulfillment of Elijah's oracle (1 Kgs 21:19: 'in the place where dogs licked up Naboth's blood, shall dogs lick your own blood').</p>",
    "16": "<p>Joram asks: 'Is it peace, Jehu?' (<em>hăšālôm Yēhûʾ</em>). Jehu's answer is devastating: 'What peace (<em>šālôm</em>), so long as the harlotries of your mother Jezebel and her sorceries are so many?' The covenant term šālôm cannot coexist with Jezebel's cult practices; Jehu frames the coup as a matter of covenant incompatibility.</p>",
    "17": "<p>Joram turns to flee and calls to Ahaziah: <em>mirmāh ʾAḥazyāhû</em> — 'Treachery, Ahaziah!' He is telling his nephew that Jehu is a traitor, not a military report; Joram has just realized this is a coup, not a military return. Both kings flee in separate directions.</p>",
    "18": "<p>Jehu draws his bow with full strength and shoots Joram between the arms (<em>bên zərōʿāyw</em> — literally between the arms = through the chest); the arrow exits through the heart. Joram slumps in his chariot. The Hebrew is anatomically specific — this is not a battle wound but a precise execution shot.</p>",
    "19": "<p>Jehu commands Bidkar his aide: take up Joram and throw him in the plot of the field of Naboth the Jezreelite. He then recites the Elijah oracle from memory (1 Kgs 21:19): 'Surely I saw yesterday the blood of Naboth and the blood of his sons, says YHWH; and I will repay you in this plot, says YHWH.' Jehu himself connects the execution to the prophetic word — the coup is executed as a fulfillment of covenant justice, not merely political ambition.</p>",
    "20": "<p>Ahaziah of Judah flees toward Beth-haggan; Jehu pursues him and orders him struck at the ascent of Gur, which is by Ibleam (Khirbet Bel'ameh, identified in the Jezreel Valley near the Dothan pass). Ahaziah is Ahab's grandson through his mother Athaliah (8:26) and is killed because he was part of the Omride network of alliance.</p>",
    "21": "<p>Ahaziah flees to Megiddo and dies there. He is taken by his servants in a chariot to Jerusalem and buried in his tomb with his fathers in the City of David. Despite being a casualty of the Jehu coup, he receives a royal Davidic burial — his status as a Davidic king is maintained even in death.</p>",
    "22": "<p>Jehu comes to Jezreel. Jezebel has painted her eyes with kohl (<em>pûk</em> — the antimony/lead sulfide cosmetic applied around the eyes as black liner; documented in Egyptian and Levantine art and texts from the 2nd millennium BCE onward) and adorned her head. She looks from the window — the classic 'woman at the window' motif known from Canaanite ivory carvings.</p>",
    "23": "<p>Jezebel calls down: 'Is it peace, O Zimri, murderer of your master?' The reference to Zimri is biting — Zimri assassinated Elah and reigned only seven days before being burned to death (1 Kgs 16:9-18); Jezebel is comparing Jehu to Israel's shortest-lived coup leader. She is insulting him, not pleading — a defiant, composed death.</p>",
    "24": "<p>Jehu looks up at the window and asks: 'Who is on my side? Who?' Two or three eunuchs look out. These are palace eunuchs (<em>sārîsîm</em>), who administered access to the queen's quarters; their willingness to betray Jezebel on command shows how completely her authority has collapsed.</p>",
    "25": "<p>At Jehu's command — 'Throw her down!' — the eunuchs throw Jezebel from the window. Her blood spatters on the wall and the horses, and they trampled her. The death is violent, undignified, and public — precisely the opposite of royal burial.</p>",
    "26": "<p>When Jehu sends servants to bury her ('for she is a king's daughter'), they find only the skull, feet, and hands — dogs have eaten the rest. This fulfills Elijah's oracle (1 Kgs 21:23: 'dogs shall eat Jezebel in the territory of Jezreel') with anatomical precision. The text of the oracle is then cited explicitly in v36.</p>",
    "27": "<p>Jehu notes the fulfillment: this is the word of YHWH that he spoke through his servant Elijah the Tishbite. The narrator and Jehu both function as interpreters of the prophetic word — Jehu understands himself as a prophetic fulfillment agent. His reference to Elijah as 'servant of YHWH' (<em>ʿeḇeḏ YHWH</em>) uses the highest prophetic honorific.</p>",
    "28": "<p>No burial can be performed for Jezebel in the proper sense. The remnants cannot even be gathered for a tomb. The woman who opposed YHWH's prophets and instigated Naboth's death receives the prophesied death of the covenant-breaker: no grave, no memorial, no dignity in death.</p>",
    "29": "<p>The narrator supplies the chronological synchronism for Ahaziah's accession (the eleventh year of Joram) — a technical note inserted here to clarify a date discrepancy with the accession notice in 8:25 (twelfth year), which most scholars explain by different counting conventions (accession-year vs. non-accession-year reckoning).</p>",
    "30": "<p>The coup is complete: three kings killed (Joram of Israel, Ahaziah of Judah, and Jezebel the queen mother), all prophetic oracles from Elijah fulfilled in sequence. Jehu's arrival in Jezreel as undisputed king opens the next phase: the administrative purge of the Omride network.</p>",
    "31": "<p>A summary notice: Jehu has killed all who remained of the house of Ahab in Jezreel, all his great men and his familiar friends and his priests — a comprehensive purge of the royal household and its religious establishment. No one from Ahab's inner circle survives in the northern capital.</p>",
    "32": "<p>Jehu also strikes all who remained of Joram's supporters — military and political allies of the Omride house who would resist the new dynasty. The scope of the purge establishes Jehu's control through elimination rather than assimilation of the previous court.</p>",
    "33": "<p>The geographic summary of the coup: Jehu went from Ramoth-gilead to Jezreel; the entire execution of the prophetic commission happened within the span of a single military march. The speed of the coup (one day, two kings, one queen mother) is itself the sign of divine authorization — YHWH prepared the ground.</p>",
    "34": "<p>The Elijah oracle sequence is complete: Joram (1 Kgs 21:19) and Jezebel (1 Kgs 21:23) have both received exactly the death-in-field and dogs-eat prophecies. The narrative notes these fulfillments twice (vv27, 36) to ensure the reader maps prophecy to event.</p>",
    "35": "<p>Summary of the battle at Ramoth-gilead context: Joram was wounded there fighting Hazael (8:28-29), which removed him from Jezreel to recover — the wound that created the window for Jehu's coup. Without Hazael's pressure on Ramoth-gilead, Jehu would have had no opportunity to slip away from the front with an anointing.</p>",
    "36": "<p>The fulfillment statement for Jezebel: <em>zeh dəḇar YHWH ʾăšer dibber bəyaḏ-ʿaḇḏô ʾĒliyyāhû haṬṭišbî</em> — 'this is the word of YHWH that he spoke by the hand of his servant Elijah the Tishbite.' The second citation of the Elijah oracle within the same chapter serves as the chapter's theological bracket — the coup is not political but prophetic fulfillment.</p>",
    "37": "<p>The carcass of Jezebel shall be like dung on the face of the field in the portion of Jezreel, so they shall not say 'This is Jezebel.' No identification, no memorial, no tomb — the anti-burial as anti-monument. In ancient Near Eastern thought, an unmarked death without burial was the ultimate disgrace; Jezebel who tried to kill the prophets of YHWH receives the death YHWH declared through his prophet.</p>"
  },
  "10": {
    "1": "<p>Ahab had seventy sons in Samaria — the number signals the scale of royal polygamy and the extent of the dynasty's administrative reach; 70 is also the number of Jacob's descendants in Egypt (Exod 1:5) and the 70 elders who accompanied Moses (Exod 24:1). Jehu writes to the 'rulers of Jezreel' (reading with LXX), the city elders, and the guardians of the royal sons, proposing they choose the best man to fight him or submit.</p>",
    "2": "<p>The letter frames a stark choice: if they have chariots, horses, a fortified city, and weapons, they should choose the best of their master's sons, set him on his father's throne, and fight for the house of Ahab. The offer is not sincere — Jehu knows they will capitulate; the letter is a legal record showing that Samaria was given the choice to resist.</p>",
    "3": "<p>The elders and guardians respond immediately with fear — 'two kings could not stand before him; how can we stand?' The rapid capitulation echoes Rahab's assessment of Israel's crossing (Josh 2:10-11); military reputation as a submission catalyst. They submit without a fight.</p>",
    "4": "<p>Jehu's second letter is more explicit: if you are on my side, bring me the heads of the men of your master's sons tomorrow at this time in Jezreel. The demand for heads was an ancient Near Eastern proof-of-submission — delivering the heads of the deposed dynasty's children signals irreversible commitment to the new ruler.</p>",
    "5": "<p>The seventy sons of Ahab are killed by the guardians; their heads are put in baskets and sent to Jehu in Jezreel. The scale of the execution — seventy deaths in one night, organized by the very men charged to protect them — shows the completeness of the Omride dynasty's political collapse.</p>",
    "6": "<p>The heads arrive in two heaps at the gate — a public display at the city gate was the standard ancient Near Eastern form of military announcement and warning. Jehu emerges in the morning and addresses the assembled people: 'You are righteous (<em>ṣaddîqîm ʾattem</em>) — it is I who conspired against my master and killed him; but who struck all these?'</p>",
    "7": "<p>Jehu's rhetorical move is subtle: he absolves himself of personal conspiracy by pointing to the Samarian elders' action, while also noting that this fulfills YHWH's oracle. He frames the corporate execution as divine confirmation — YHWH has done what he spoke through Elijah; nothing can fall to the ground of YHWH's word.</p>",
    "8": "<p>Jehu strikes all who remained of the house of Ahab in Jezreel — every great man, every acquaintance, every priest. The purge extends to the social network of the Omride court, not just blood relatives. Priests (likely Baal priests associated with the court) are included in the sweep.</p>",
    "9": "<p>On the way from Jezreel to Samaria, at Beth-eked of the Shepherds, Jehu encounters the brothers of Ahaziah of Judah — forty-two kinsmen of the Judahite king. They are going down to visit the sons of the king and the queen mother (not yet knowing of the deaths). Jehu has them taken and killed at the pit of Beth-eked — forty-two men, none escaped.</p>",
    "10": "<p>Jonadab son of Rechab comes to meet Jehu. The Rechabites were a clan that maintained a nomadic, non-agricultural lifestyle as a religious commitment — no wine, no houses, no vineyards (Jer 35:6-7). Their founder Jonadab's alliance with Jehu's anti-Baal purge suggests a shared anti-Canaanite-syncretism stance; they rejected the agricultural cult that Baal worship represented.</p>",
    "11": "<p>Jehu's question to Jonadab: 'Is your heart right, as my heart is right with your heart?' (<em>hăyēšār libbəḵā ʿim-libbî kaʾăšer libbî ʿim-libbəḵā</em>) — a covenant-loyalty formula; 'right heart' (<em>lēḇāḇ yāšār</em>) is not merely personal sincerity but covenant alignment. When Jonadab affirms, Jehu says 'Give me your hand' — the handshake as covenant seal.</p>",
    "12": "<p>Jonadab rides in Jehu's chariot — a public display of alliance. The Rechabite presence at Jehu's side during the Baal-temple purge legitimizes the action in the eyes of conservative Yahwists; Jonadab's reputation for purity validates Jehu's religious agenda.</p>",
    "13": "<p>When Jehu comes to Samaria he kills all who remained of Ahab in Samaria until he had annihilated them, 'according to the word of YHWH which he spoke to Elijah' — the third explicit prophetic-fulfillment notice in these two chapters (vv9:27, 9:36, 10:17). The repetition is the historian's theological structure: Jehu's coup is interpretively framed as prophetic completion throughout.</p>",
    "14": "<p>Jehu's anti-Baal operation: he gathers all the people and announces that Ahab served Baal a little but Jehu will serve Baal much — a deceptive announcement, a <em>ruse de guerre</em> to gather Baal worshippers. He summons all Baal's prophets, servants, and priests — none are to be absent on pain of death.</p>",
    "15": "<p>The Baal worshippers arrive; the house of Baal is filled from end to end. Jehu then orders vestments for all Baal's worshippers — the distribution of official cult garments serves the tactical purpose of identifying all present as Baal devotees and preventing any infiltrators from escaping the purge.</p>",
    "16": "<p>Jehu station eighty men outside with the order: 'The man who allows any of the men whom I bring into your hands to escape shall forfeit his life.' The perimeter is sealed before the massacre begins — a military encirclement operation applied to a cultic building.</p>",
    "17": "<p>When the burnt offering was finished, Jehu commanded: 'Go in, strike them down; let not a man come out.' The burnt offering was used as a cover — the assembly format of a religious ceremony prevented early escape. The guards strike them down; the executioners throw the bodies out and go into the inner shrine of the house of Baal.</p>",
    "18": "<p>They bring out the pillar (<em>maṣṣēḇôṯ</em>) of Baal's house and burn it. They pull down the <em>maṣṣēḇāh</em> of Baal and tear down the house of Baal and make it a latrine (<em>məḥărāʾôṯ</em>) — the latrine desecration is the definitive anti-cultic act: the most sacred space of Baalism is converted to the most polluting use. The pattern matches Josiah's later desecrations (23:8, 10).</p>",
    "19": "<p>Baal is destroyed from Israel — the text is explicit: wayyašmēḏ ʾeṯ-habbáʿal miyyiśrāʾēl. But (v29) Jehu does not depart from the sins of Jeroboam, which made Israel to sin — the golden calves at Bethel and Dan are left standing. The anti-Baal purge is complete; the anti-Jeroboam reform is not attempted. Jehu destroys the foreign cult but not the domestic idolatry.</p>",
    "20": "<p>YHWH commends Jehu: 'Because you have done well in carrying out what is right in my eyes and have done to the house of Ahab all that was in my heart, your sons shall sit on the throne of Israel to the fourth generation.' The conditional promise gives Jehu's dynasty the longest tenure in northern history — four generations (Jehoahaz, Jehoash, Jeroboam II, Zechariah) — explicitly limited to four as a reward-not-a-covenant structure.</p>",
    "21": "<p>But Jehu was not careful to walk in the law of YHWH the God of Israel with all his heart — <em>lōʾ šāmar lāleḵeṯ bəṯôraṯ YHWH ʾĕlōhê yiśrāʾēl bəkol-libbô</em>. The qualification mirrors the standard regnal evaluation; the four-generation reward is given despite incomplete fidelity. YHWH's sovereignty does not require its human instruments to be fully righteous to accomplish his purposes.</p>",
    "22": "<p>In Jehu's time Hazael began to cut off parts of Israel; the Aramean pressure that characterized Jehoahaz's reign begins to build. Jehu's reign is marked by territorial loss to Aram even as his purge secured internal religious control — a trade-off that shows the limits of a purely coup-based reform.</p>",
    "23": "<p>Jehu dies and is buried in Samaria; Jehoahaz his son reigns in his place. The death notice is brief; the four-generation promise begins its count here. The Jehu dynasty is the only northern dynasty that extends beyond two generations.</p>",
    "24": "<p>The twenty-eight year reign of Jehu is the longest single reign of any northern king except Jeroboam II (forty-one years). The length of the dynasty, combined with Jeroboam II's military successes, makes the Jehu dynasty the high-water mark of the northern kingdom — which makes its end (Zechariah's assassination, 15:10) all the more sudden.</p>",
    "25": "<p>Chronological note linking Jehu's accession to Joram's twelfth year in Judah — the synchronism anchors Jehu's dynasty in the bi-national chronological framework that runs throughout Kings. The precision of Kings' chronology (despite its complexity) reflects an archival tradition of royal synchronism.</p>",
    "26": "<p>YHWH's assessment of Jehu — the act of destroying the Baal cult was 'what was right in YHWH's eyes' — but the persistent Jeroboam-golden-calf worship meant that Israel continued in its structural sin. Divine evaluation distinguishes between what was done right and what remained incomplete; the commission to destroy Baal was fulfilled; the broader covenant restoration was not.</p>",
    "27": "<p>The attack on Israel's territory by Hazael — cutting off parts of Gilead from the Arnon to Gilead — points to the military cost of the internal purge; Jehu's energies were consumed by regime change rather than border defense. Israel lost the Transjordanian territories to Aram during Jehu's reign, territories that Jeroboam II would later recover.</p>",
    "28": "<p>The archival notice about Jehu's acts in the Book of the Chronicles of the Kings of Israel closes the chapter; the comprehensive purge narrative (chs 9-10) stands as the most detailed single military-political operation in Kings, a literary monument to the fulfillment of the Elijah-Jezebel-Ahab oracle sequence.</p>",
    "29": "<p>The remaining summary: Jehu's son Jehoahaz reigns in his place; the four-generation promise begins its fulfillment. The dynasty that started with a coup against Joram (Ahab's son) will itself be terminated by a coup against Zechariah (Jehu's great-great-grandson) in 15:10 — the same mechanism of violent regime change that began the dynasty ends it.</p>",
    "30": "<p>Final synchronism: Jehu reigned twenty-eight years over Israel in Samaria. The number closes the chapter on a reign that was simultaneously the most theologically significant (Baal-destruction, prophetic fulfillment) and politically consequential (launching the most durable northern dynasty) of any northern king.</p>",
    "31": "<p>The territorial summary: all the territory that Hazael took from Israel east of the Jordan — from Aroer by the Arnon Valley through Gilead and Bashan — was lost to Aram during Jehu's dynasty. The military weakness that accompanied the Baal purge created the opening for Aramean expansion that would not be reversed until Jeroboam II.</p>",
    "32": "<p>The note about YHWH's anger beginning to reduce Israel signals the theological framework: the Jehu purge satisfied the Ahab-Jezebel covenant debt but did not restore full covenant obedience; the trajectory of divine judgment continues because the Jeroboam golden calves remain. Reform without full covenant renewal leaves the structural problem intact.</p>",
    "33": "<p>Summary of the Hazael losses: all the land of Gilead, from Aroer to the Arnon (the southern Transjordanian boundary) through Gilead and Bashan. These were the territories of Gad and Reuben and Manasseh. The loss of the Transjordan strips Israel to the western bank, reducing the kingdom to its minimal core.</p>",
    "34": "<p>The archival formula for Jehu closes chapter 10: the rest of his acts, all he did, all his might — in the Book of the Chronicles of the Kings of Israel. The 'might' reference (<em>gəḇûrāṯô</em>) is used for Jehu despite the territorial losses; military and political decisiveness apparently qualified for the 'might' designation regardless of strategic outcome.</p>",
    "35": "<p>Jehu sleeps with his fathers and they bury him in Samaria. The burial in Samaria is the standard northern-kingdom burial location — none of the northern kings are buried in Jerusalem. The dynastic continuity (Jehoahaz succeeds) begins the four-generation countdown of YHWH's promise in v30.</p>",
    "36": "<p>The final verse confirms twenty-eight years for Jehu's reign over Israel in Samaria — the archival number matching the synchronistic framework of the chronology. The reign that began with a coup at Ramoth-gilead ends with a burial in Samaria, the capital the Omrides built and Jehu inherited.</p>"
  },
  "11": {
    "1": "<p>Athaliah (daughter of Ahab and Jezebel, mother of the slain Ahaziah) sees her son is dead and rises to destroy all the royal seed of the house of Judah (<em>zeraʿ hammamlākāh</em> — the seed/offspring of the kingdom). Her action mirrors Jehu's purge in Israel but targets the Davidic line — the only one who could claim the southern throne. The lamp of David (8:19) is within one infant generation of being extinguished.</p>",
    "2": "<p>Jehosheba (<em>Yəhôšeḇaʿ</em> — YHWH is abundance/oath), sister of Ahaziah and wife of Jehoiada the priest (2 Chr 22:11), takes Joash son of Ahaziah and steals him from among the royal sons being killed. She hides him and his nurse in the bedroom (<em>ḥăḏar hammiṭṭôṯ</em>) — literally the room of beds, perhaps a storage room attached to the temple chambers. One woman's courage and one room's obscurity preserves the Davidic covenant.</p>",
    "3": "<p>Joash is hidden with Jehosheba in the house of YHWH for six years while Athaliah rules the land. The temple as sanctuary for the hidden king is doubly ironic: YHWH's own house shelters the heir against the woman who has introduced Baal worship into Judah (2 Chr 24:7). The six-year hiding period is one of concealment before the seventh-year revelation, structurally mirroring sabbatical patterns.</p>",
    "4": "<p>In the seventh year, Jehoiada the priest sends for the commanders of hundreds of the Carites (<em>hakkārî</em>) and of the guards. The Carites were likely mercenary troops of non-Israelite (possibly Aegean) origin — the same word may be translated 'Cherethites' in LXX tradition, connecting to the Cherethites who were David's royal guard (2 Sam 8:18; 20:23). Jehoiada swears them in at YHWH's house and shows them the king's son.</p>",
    "5": "<p>The operational plan: one third of the troops guard the palace on the Sabbath, one third guard the gate of Sur, one third guard the gate behind the guards. The Sabbath timing is tactically chosen — the changing of the guard creates a moment of maximum confusion and minimum alertness at the palace.</p>",
    "6": "<p>Two divisions of all who go out on the Sabbath shall keep watch at YHWH's house around the king — the temple compound is the staging ground, with the guards forming a protective ring around the hidden child. The operational geometry places the palace and temple in coordinated defense of the new king before his presentation.</p>",
    "7": "<p>Anyone who approaches the ranks is to be killed — lethal rules of engagement protect the operation. The weapons used are to be from the temple armory: King David's spears and shields kept in the house of YHWH. The symbolic use of David's own weapons to crown David's heir is deliberate.</p>",
    "8": "<p>The guards take their positions — from the south side of the house to the north side of the house, surrounding the altar and the house, with the king in the middle. The spatial arrangement of the coup is carefully described: the king is at the center of a military ring inside the sacred space.</p>",
    "9": "<p>Jehoiada brings out the king's son and puts on him the <em>nēzer</em> (crown/diadem) and the <em>ʿēḏûṯ</em> (testimony/protocol — perhaps the covenant document or the law of the king from Deut 17:18-20). The two coronation acts — the physical crown and the written covenant responsibility — represent the dual nature of Israelite kingship: political power under covenant law.</p>",
    "10": "<p>They clap their hands (<em>wayyiḵpəʾû kap</em>) and shout 'Long live the king!' — the royal acclamation formula that echoes Solomon's acclamation (1 Kgs 1:39). The ceremony is complete: anointing, crown, covenant, acclamation. Athaliah hears the sound and comes to the temple.</p>",
    "11": "<p>Athaliah cries 'Treason! Treason!' (<em>qešer qāšer</em>) — the same word Joram used against Jehu (9:23) and that Jezebel's 'Zimri' taunt implied. The cry is accurate but futile; the military disposition is complete before she arrives. Jehoiada gives the order to bring her out outside the ranks and kill anyone who follows her.</p>",
    "12": "<p>They seize Athaliah and she is brought to the palace's horse entrance and killed there. The Carites and guards who executed the coup ensure that her blood does not pollute the temple precincts — the execution is outside the sacred space, a legal nicety that preserves the temple's sanctity even during a violent regime change.</p>",
    "13": "<p>Jehoiada makes a covenant between YHWH and the king and the people — the tripartite covenant structure repeats the Sinai pattern (YHWH / mediator / people) and the Mosaic covenant renewal form (Deut 29:1). The covenant binds the restored Davidic king to YHWH's law from the moment of accession — no honeymoon period before accountability.</p>",
    "14": "<p>The people tear down the house of Baal that Athaliah had built and smash its altars and images. They kill Mattan the priest of Baal before the altars. The immediate anti-Baal action parallels Jehu's destruction in Israel (ch10) — but in Judah it is the people and priest acting together, not a military purge. The covenant ratification produces the reform.</p>",
    "15": "<p>Jehoiada appoints overseers for YHWH's house under the priests and Levites — restoring the proper temple administration that Athaliah had disrupted. The phrase 'whom David had organized' (<em>ʾăšer ḥālaqa ḏāwiḏ</em>) in 2 Chr 23:18 connects the restoration directly to the Davidic order.</p>",
    "16": "<p>Joash is brought in through the gate of the guards to the king's house and sits on the throne of the kings. All the people of the land rejoice; the city is quiet — <em>wəhāʿîr šāqāṭāh</em>, 'and the city was quiet.' The Zion-city-at-rest formula echoes the peaceful accessions in the Davidic tradition. Six years of illegitimate rule end with the legitimate heir enthroned and the city at peace.</p>",
    "17": "<p>Joash was seven years old when he became king. The accession of a seven-year-old under Jehoiada's priestly guidance sets up the evaluative observation of 12:2: 'Jehoash did right all his days, because Jehoiada the priest instructed him.' The infant king's righteousness is entirely dependent on his priestly mentor — the pattern that will collapse after Jehoiada's death (2 Chr 24:17-22).</p>",
    "18": "<p>Athaliah died by the sword at the age of approximately fifty-five — she had reigned six years over Judah after Ahaziah's death at age forty (8:26). Her death closes the Omride intrusion into the Davidic dynasty: Ahab's daughter, who introduced Baal worship into Jerusalem, is executed in the year the Davidic heir is revealed, on the same day the Baal temple is torn down. The two acts are simultaneous and inseparable.</p>",
    "19": "<p>The chapter summary: the priest Jehoiada organized the military officers, Carites, and all the people of the land, brought the king down from YHWH's house, came through the gate of the guards to the palace, and he sat on the throne of the kings. The sequence — temple to throne — models the proper relationship between divine authorization and political power in the Davidic ideal.</p>",
    "20": "<p>Athaliah had been killed with the sword at the palace — the text confirms both the method and the location of the execution, outside the temple precincts. The narrative brackets the chapter with its two death notices (v1: Athaliah destroys the royal seed; v20: Athaliah is killed) to show the inversion: the woman who tried to destroy a dynasty is herself destroyed and replaced by the dynasty she tried to extinguish.</p>",
    "21": "<p>Joash was seven years old when he became king — the repetition of the age at accession closes the chapter at the same point where 12:1 will open: the boy king, the priest as regent, the forty-year reign that follows. The seven-year hidden king who becomes king at seven carries the structural symbolism of the sacred number: the hidden sabbatical period gives way to the year of revelation and royal restoration.</p>"
  }
}

def main():
    d = load_comm('mkt-context', '2kings')
    merge_comm(d, KINGS2_CONTEXT)
    save_comm('mkt-context', '2kings', d)
    print('2kings ch9-11 mkt-context: done')

if __name__ == '__main__':
    main()
