"""
MKT Context Commentary — 1 Kings chapters 10–11
Run: python3 scripts/zc-context-1kings-10-11.py

Source data used:
- data/interlinear/1kings.json
- data/translation/draft/mediating/1kings.json
- data/translation/notes/1kings.json

Key decisions in this range:
- Ch10 = Solomonic apex and covert violation of Deut 17:14-20 (horses from Egypt, excessive gold, implied many wives)
- 666 talents of gold (v14): same figure as Rev 13:18; the irony of the number is contextually significant
- Ch11 = the apostasy narrated as a judicial sentence; each foreign deity named historically
- Ashtoreth / Milcom / Chemosh / Molech: each identified with their ANE cult context
- Hadad and Rezon as śāṭān (adversary): YHWH raises external opponents as covenant-judgment instruments
- Ahijah's torn garment: the acted-prophecy tradition in Israel
- nîr (lamp) in v36: the Davidic succession metaphor that recurs throughout Kings
- Jeroboam's flight to Shishak: the same pharaoh who invades Judah in 14:25-26
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

KINGS = {
  "10": {
    "1": '<p>The queen of Sheba (<em>malkat-Šəḇāʾ</em>) represents the Sabaean kingdom of southwest Arabia (modern Yemen), the dominant power in the ancient spice trade. Sabaean merchants controlled the overland caravan routes from the Arabian Peninsula to the Levantine coast, trading incense, myrrh, gold, and luxury goods. Saba&rsquo;s capital, Marib, featured one of the ancient world&rsquo;s great dams, and Sabaean inscriptions attest an advanced literate culture. Her visit &ldquo;to test him with riddles&rdquo; (<em>ḥîḏôt</em>) fits the ANE tradition of wisdom contests between royal courts; Proverbs 1:6 lists <em>ḥîḏāh</em> (riddle) as a wisdom genre. The &ldquo;name of the LORD&rdquo; — her stated motivation — signals that Solomon&rsquo;s wisdom had acquired a specifically theological reputation among the nations, fulfilling the prayer of 8:41-43.</p>',
    "2": '<p>Her delegation brings the premier commodities of south Arabian trade: spices (<em>bəśāmîm</em>, aromatic resins), gold, and precious stones. The &ldquo;very large retinue&rdquo; and camels underline the distance and scale of the journey. The spice trade from Arabia was economically vital to the entire ancient Near East; the same goods appear in the Exodus tabernacle materials (Exod 25:7) and in the tribute lists of Assyrian kings. Her coming to Solomon with these gifts frames the encounter as both diplomatic mission and recognition of Israelite supremacy at the height of the empire.</p>',
    "3": '<p>Solomon answered all her questions: <em>lōʾ-hāyāh dāḇār nistar min-hammelek ʾăšer lōʾ-higgîd lāh</em> — there was nothing hidden from the king that he could not explain. The verb <em>nāgad</em> (declare, make plain) in the causative describes the sage who illuminates opaque things. The wisdom literature tradition values this capacity — the sage who makes the obscure plain resembles YHWH who reveals mysteries (Dan 2:22). The queen&rsquo;s riddle-testing frames Solomon as the exemplary wise king.</p>',
    "4": '<p>She sees &ldquo;all the wisdom of Solomon and the house he had built&rdquo; — wisdom and architecture are presented as a unified display. The Temple and palace complex was itself a form of enacted wisdom: its proportions, materials, and symbolism expressed cosmic order. ANE royal inscriptions regularly link wisdom to building — Gudea of Lagash&rsquo;s cylinder inscriptions and Egyptian royal didactic texts present the wise king as builder. Solomon&rsquo;s wisdom is not merely intellectual but material, embodied in stone and cedar.</p>',
    "5": '<p>The queen is overwhelmed by the full display: the food, court officials, servants, their attire, the cupbearers, and the burnt offerings at the Temple. <em>Wəlōʾ-hāyāh bāh ʿôd rûaḥ</em> — &ldquo;there was no longer any spirit in her.&rdquo; The phrase describes breathless astonishment — a temporary loss of self-possession. The detail of &ldquo;his burnt offerings which he offered at the house of the LORD&rdquo; connects material grandeur to cultic fidelity: the Temple liturgy is part of what impresses her. The sacred and the political are not separated at Solomon&rsquo;s court.</p>',
    "6": '<p>The queen&rsquo;s verdict: &ldquo;the report I heard in my own country about your deeds and your wisdom was true.&rdquo; A Sabaean queen validates what Israel knew: YHWH&rsquo;s gift of wisdom to Solomon is a verifiable fact accessible to outsiders. Her speech functions as a Gentile testimony — the nations confirming what the covenant people experience. Jesus cites her in this function (Matt 12:42): &ldquo;the queen of the South will rise up at the judgment with this generation and condemn it, for she came from the ends of the earth to hear the wisdom of Solomon.&rdquo;</p>',
    "7": '<p>&ldquo;The half was not told to me&rdquo; (<em>lōʾ huggad-lî haḥăṣî</em>) — the reality exceeded the report. This rhetorical structure of wonder — every account falling short — governs the queen&rsquo;s praise: <em>yāsaptā ḥoḵmāh wāṭôḇ ʾel-haššəmuʿāh</em> — you have exceeded in wisdom and prosperity the report I heard. The gap between report and reality is itself a form of divine self-disclosure: what can be said about YHWH&rsquo;s gifts never fully captures them.</p>',
    "8": '<p>The queen pronounces a beatitude: <em>ʾašrê ʾănāšêkā ʾašrê ʿăḇādêkā ʾēlleh hāʿōmḏîm lǝpānêkā tāmîd</em> — &ldquo;blessed are your men, blessed are these servants of yours who stand before you continually and hear your wisdom.&rdquo; The <em>ʾašrê</em> (blessed/happy) formula is the opening of Psalm 1 and the beatitude form Jesus develops in the Sermon on the Mount. To stand before Solomon and hear his wisdom is, in her analysis, the happiest human condition. The Psalter uses the same formula for standing in YHWH&rsquo;s presence (Ps 84:4).</p>',
    "9": '<p>The queen blesses YHWH: <em>yəhî yhwh ʾelōhêkā bārûk ʾăšer ḥāpēṣ bəkā</em> — &ldquo;blessed be the LORD your God, who has delighted in you.&rdquo; A Sabaean queen praises YHWH, the God of Israel. The phrase &ldquo;because the LORD loved Israel forever&rdquo; — a Gentile queen articulates Israel&rsquo;s covenant theology. This is the high-water mark of the Solomonic vision: the nations have come to Solomon, heard wisdom, and praised YHWH. The mission of 8:41-43 (that the foreigner may know YHWH&rsquo;s name) is fulfilled in this moment.</p>',
    "10": '<p>The queen gives Solomon 120 talents of gold — the same amount Hiram sent (9:14), a precise parallel suggesting equivalent trading partners. Her spices were &ldquo;very great&rdquo; in quantity: <em>bəśāmîm lārōḇ mǝʾōd</em> — the spice haul exceeded all previous imports. The verse closes: &ldquo;never again did there come such a quantity of spices as the queen of Sheba gave.&rdquo; The finality implies this transaction was unique in Israelite history — a moment of trade, diplomacy, and wisdom-witness that would not recur.</p>',
    "11": '<p>Hiram&rsquo;s Ophir fleet brought <em>ʿăṣê ʾalmûggîm</em> — almug wood (possibly red sandalwood from south Asia) — and precious stones. The almug wood was made into supports for the Temple and palace and into lyres and harps. The three-year round trip to Ophir (9:28) produced multiple luxury goods. The convergence of Hiram&rsquo;s Ophir trade and the Sheba visit at this point in the narrative creates the impression of an empire at its commercial zenith.</p>',
    "12": '<p>The almug supports (<em>misnᵊqôt</em>) for the Temple and palace are a hapax detail — both structural and aesthetic, the exotic wood serving as architecture and decor. The same wood produced musical instruments for the court. The combination of Temple use and musical use connects the Sheba-and-Ophir material to the liturgical life of Jerusalem: even international trade flows toward YHWH&rsquo;s house and its worship.</p>',
    "13": '<p>Solomon gave the queen &ldquo;all she desired, whatever she asked,&rdquo; plus gifts &ldquo;according to the bounty of King Solomon.&rdquo; The exchange is described as reciprocal but asymmetric: she came with maximum gifts, he outgave her. The narrative closes the Sheba episode with her departure. No political alliance is forged; no conversion is narrated. She came to hear wisdom, was convinced, praised YHWH, and returned. The episode stands complete as a testimony to wisdom&rsquo;s international reach — and to the covenant community&rsquo;s calling to be a light to the nations.</p>',
    "14": '<p>The annual gold income of 666 talents is a precise and theologically resonant figure. Revelation 13:18 uses the same number for the beast — &ldquo;the number of a man.&rdquo; Whether or not the Revelation author has Solomon in mind, the ancient reader of Kings would recognize the irony: the king whose wisdom was divine begins to accumulate at a rate that echoes the warning of Deuteronomy 17:17 — &ldquo;he must not greatly multiply silver and gold for himself.&rdquo; The excessive wealth is the beginning of the covert Deuteronomic critique that ch11 will make explicit.</p>',
    "15": '<p>In addition to the 666 talents, revenue came from &ldquo;traders and merchants, all the kings of Arabia, and the governors of the land.&rdquo; The administrative term <em>paḥôt</em> (governors) reflects the provincial structure established in ch4. The additional income streams mean the 666 figure is only part of a larger wealth flow. The empire&rsquo;s commercial infrastructure generates revenue from multiple directions simultaneously, all flowing toward the king.</p>',
    "16": '<p>Solomon made 200 large shields (<em>ṣinnôt</em>) of hammered gold, each requiring 600 shekels of gold. The shields were decorative-ceremonial, not military — they adorned the House of the Forest of Lebanon (7:2). The use of gold for objects that would normally be functional signals the crossing into conspicuous excess: military symbols reduced to display. ANE rulers frequently made such display objects, but the Torah&rsquo;s warning against excessive gold (Deut 17:17) is in the background.</p>',
    "17": '<p>Three hundred smaller shields (<em>māginnôt</em>) of hammered gold, three minas each. Both shield types were stored in the House of the Forest of Lebanon (v21), which functioned as an armory and treasury. The specific quantities and weights are recorded with the precision of an official inventory — the narrator presents these facts without comment, trusting the Deuteronomically literate reader to register the excess.</p>',
    "18": '<p>The ivory throne (<em>kissēʾ šēn gādôl</em>) overlaid with finest gold (<em>mûpāz</em>) represents the pinnacle of ANE royal furniture. Ivory thrones are attested archaeologically at Megiddo and at Ugarit and in the Nimrud ivories. The combination of ivory and gold was the luxury standard. The throne had six steps, a rounded top, and armrests with lion figures. The lion imagery (<em>ʾăryôt</em>) frames the throne with Judah&rsquo;s tribal symbol (Gen 49:9 — &ldquo;Judah is a lion&rsquo;s whelp&rdquo;): the Davidic king enthroned as lion of his tribe.</p>',
    "19": '<p>The throne had six steps and a rounded top (the Hebrew <em>raʾăšōt ʿăgulôt</em> is disputed; LXX reads differently). The armrests were on either side of the seat; a lion stood beside each armrest. The architectural precision of the description matches the Temple building accounts. The detail that &ldquo;nothing like it was ever made for any kingdom&rdquo; is the narrator&rsquo;s superlative — the throne of Solomon was without parallel in the ancient world.</p>',
    "20": '<p>Twelve lions stood on the six steps, one on each side of each step. The number twelve (tribes of Israel) and the symmetrical arrangement express the royal covenant: the king on the lion-throne presides over all Israel, supported by the symbolic completeness of the twelve-tribe structure. The throne is a political and theological architecture — its symbolism encodes the relationship between king, people, and covenant.</p>',
    "21": '<p>All Solomon&rsquo;s drinking vessels were gold; the House of the Forest of Lebanon&rsquo;s vessels were of pure gold. <em>ʾÊn kāsep lōʾ neḥšāḇ bîmê šəlōmōh</em> — &ldquo;silver was not considered as anything in the days of Solomon.&rdquo; This extreme statement marks the apex of wealth: when silver is worthless, gold has become commonplace. The Deuteronomic critique is implicit — the king was to be of &ldquo;humble heart&rdquo; (Deut 17:20), not one in whose reign precious metal was despised for abundance.</p>',
    "22": '<p>The &ldquo;Tarshish fleet&rdquo; (<em>ʾŏnî tarśîš</em>) — the designation probably refers to the class of large ocean-going vessels capable of long voyages rather than specifically vessels bound for Tarshish (likely Tartessus in Spain, though the term may be generic for the western Mediterranean). Once every three years they returned with gold, silver, ivory, apes (<em>qôpîm</em>), and peacocks (<em>tukkîyîm</em> — a disputed term; may mean baboons, parrots, or peacocks). The animals signal trade with sub-Saharan Africa or South Asia — the empire&rsquo;s commercial reach extended beyond the Near East.</p>',
    "23": '<p><em>Wayyigdal hammelek šəlōmōh mikkol malkhê hāʾāreṣ lĕʾōšer ûlĕḥoḵmāh</em> — &ldquo;King Solomon surpassed all the kings of the earth in riches and wisdom.&rdquo; This is the narrator&rsquo;s summary statement, the rhetorical peak of the Solomonic narrative. The double superlative — greater in wealth AND wisdom than every other king — makes Solomon the embodiment of the ideal ruler of Psalm 72. The praise is real; the narrative does not retract it. But the structure of Kings places this summit immediately before the account of its dismantling in ch11.</p>',
    "24": '<p>All the peoples of the earth sought audience with Solomon to hear the wisdom that God had placed in his heart (<em>laʾăšer-śāmāh ʾelōhîm bəlibbô</em>). The phrase &ldquo;that God placed in his heart&rdquo; keeps the wisdom explicitly divine in origin — not native Solomonic intellect but YHWH&rsquo;s gift (cf. 3:12). The universal seeking of Solomon&rsquo;s wisdom fulfills the Abrahamic promise that through Israel&rsquo;s seed all nations would be blessed (Gen 12:3).</p>',
    "25": '<p>Year after year every visitor brought a gift: silver, gold, garments, weapons, spices, horses, and mules. The annual tribute list covers luxury goods and military assets (horses, mules). The accumulation of horses from multiple nations quietly violates Deuteronomy 17:16 — &ldquo;he must not acquire many horses for himself.&rdquo; The narrator records the tribute list factually; the Deuteronomic critique operates through the reader&rsquo;s knowledge of the law, not through editorial comment.</p>',
    "26": '<p>Solomon accumulated 1,400 chariots and 12,000 horsemen, stationed in chariot cities and in Jerusalem. The chariot cities — Megiddo, Hazor, Gezer (9:15-17) — have been archaeologically confirmed as sites of large stable complexes; Megiddo yielded stall foundations for hundreds of horses (scholars debate whether these are Solomonic or Ahab-era). The military buildup is presented as impressive; the Deuteronomic text (17:16) is not cited by the narrator but would be heard by any Torah-literate reader.</p>',
    "27": '<p><em>Wayyittēn hammelek ʾet-hakkesep bîrûšālayim kāʾăḇānîm</em> — &ldquo;the king made silver as common in Jerusalem as stones.&rdquo; The simile is deliberately extreme — the rarest currency reduced to the commonest material. Cedar wood from Lebanon was equally commonplace. The rhetorical hyperbole serves two purposes: it glorifies the Solomonic era as unprecedented prosperity, and it sets up the implied judgment. The Torah warned that the king &ldquo;must not greatly multiply silver and gold for himself lest his heart be lifted up&rdquo; (Deut 17:17,20). Jerusalem has arrived at that condition.</p>',
    "28": '<p>Solomon&rsquo;s horses were imported from Egypt (<em>miṣrayim</em>) and Kue (Cilicia in southeastern Asia Minor, a major horse-breeding region in antiquity). The royal traders (<em>sōḥărê hammelek</em>) purchased them at fixed prices. The Egyptian + Kue combination is precisely what Deuteronomy 17:16 prohibits: &ldquo;he must not cause the people to return to Egypt to acquire many horses, since the LORD has said to you, &lsquo;You shall never return that way again.&rsquo;&rdquo; The account of Solomon&rsquo;s wealth in vv14-29 is a sustained portrait of Deuteronomic violation — gold, horses from Egypt, and (disclosed in ch11) many wives — with no explicit condemnation, letting the Torah provide its own commentary.</p>',
    "29": '<p>The price of a chariot (600 shekels of silver) and horse (150 shekels) is recorded with commercial precision. The chariots were exported to &ldquo;all the kings of the Hittites and the kings of Aram&rdquo; through Solomon&rsquo;s agency — Israel served as a military-trade middleman between Egypt and the northern states. The international commercial network is described with admiring detail. But the reader who knows Deuteronomy 17:16-17 has been presented with a systematic account of the king accumulating exactly what the law forbade: gold (v14), horses from Egypt (v28), and — as ch11 will disclose — many wives (v1).</p>'
  },
  "11": {
    "1": '<p>Chapter 11 opens with the abrupt assertion that Solomon loved (<em>ʾāhab</em>) many foreign women — the same verb used for YHWH&rsquo;s love for Israel (Deut 7:8) and for the love command (Deut 6:5). The irony is structured: the king who should love YHWH with all his heart redirects that love toward foreign women. The list of nationalities — Moabite, Ammonite, Edomite, Sidonian, Hittite — corresponds precisely to the nations Deuteronomy 7:1-4 prohibited intermarriage with, &ldquo;for they will turn away your sons from following me.&rdquo; The prohibition is then quoted verbatim in v2 to make the violation unmistakable.</p>',
    "2": '<p>YHWH&rsquo;s explicit prohibition: &ldquo;You shall not enter into marriage with them, neither shall they enter into marriage with you, for surely they will turn away your heart after their gods.&rdquo; <em>Lōʾ-tāḇōʾ ḇāhem wəhēm lōʾ-yāḇōʾû ḇākem</em> — the bilateral prohibition covers both directions. The theological rationale is relational: mixed-deity households produce divided loyalties. The narrator then states flatly: <em>wayyidbeq šəlōmōh ʾăhēbāh ḇāhem</em> — &ldquo;Solomon clung to these in love.&rdquo; The verb <em>dāḇaq</em> (cling) is the covenant-bonding word of Gen 2:24 (man cleaves to his wife) and Deut 13:4 (cleave to YHWH). Solomon cleaves to foreign women as he should have clung to YHWH.</p>',
    "3": '<p>The enumeration: 700 wives of royal standing (<em>šārôt</em>) and 300 concubines (<em>pîlagšîm</em>). The 1,000 total is hyperbolic, representing the totality of Solomon&rsquo;s diplomatic-alliance structure: every significant foreign court relationship was sealed by a marriage. Each wife brought her deity, cult objects, and priests. <em>Wayyaṭṭû nāšāyw ʾet-libbô</em> — his wives turned away his heart. The verb <em>nāṭāh</em> (incline, turn) is the same word Solomon used in his dedication prayer (8:58) asking YHWH to incline Israel&rsquo;s hearts toward himself. The heart that should have been inclined toward YHWH was systematically turned away by cumulative accommodation.</p>',
    "4": '<p><em>Wayhî lĕʿēt ziqnat šəlōmōh</em> — &ldquo;in Solomon&rsquo;s old age.&rdquo; The apostasy came gradually and late; the narrative does not present a young rebel but an old man&rsquo;s accumulated accommodations. <em>Lōʾ-hāyāh lǝḇāḇô šālēm ʿim-yhwh ʾelōhāyw kilĕḇaḇ dāwid ʾāḇîw</em> — his heart was not wholly devoted to YHWH as the heart of his father David. The <em>lēḇāḇ šālēm</em> (undivided heart) that Solomon himself set as the covenant standard in 8:61 is now denied him by the narrator. He failed his own criterion.</p>',
    "5": '<p>Ashtoreth (<em>ʿaštōret</em>) — the Canaanite goddess of love and war, equivalent to Ishtar/Inanna in Mesopotamia and Astarte in Phoenician texts. Associated with the evening star (Venus), fertility, and military prowess; her cult included ritual prostitution at certain sites. Milcom (<em>milkōm</em>) — the national deity of Ammon, related to <em>mlk</em> (king); related to or identical with Molech (<em>mōlek</em>), who is associated with child sacrifice in the Valley of Hinnom (2 Kgs 23:10; Jer 7:31). Solomon went after these foreign gods — <em>wayyēlek šəlōmōh ʾaḥărê ʿaštōret</em> — the language of covenantal abandonment: &ldquo;going after&rdquo; (<em>hālak ʾaḥărê</em>) other gods is the standard Deuteronomistic formula for apostasy.</p>',
    "6": '<p><em>Wayyaʿaś šəlōmōh hārāʿ bĕʿênê yhwh</em> — Solomon did what was evil in the sight of the LORD. This is the Deuteronomistic formula of royal judgment that will recur for nearly every king in Kings. Its first application is startling: Solomon, the Temple-builder, the recipient of divine wisdom at Gibeon, the author of the dedication prayer, is judged with the same formula as Ahab and Manasseh. <em>Wəlōʾ-millēʾ ʾaḥărê yhwh kəḏāwid ʾāḇîw</em> — he did not fully follow YHWH as his father David. The Davidic standard measures him and finds him deficient.</p>',
    "7": '<p>Solomon built high places (<em>bāmôt</em>) for Chemosh and for Molech. Chemosh (<em>kəmôš</em>) was the national deity of Moab; the Mesha Stele (ca. 840 BCE) records King Mesha attributing his military victories to Chemosh and denouncing the god&rsquo;s earlier anger that had allowed Israel to oppress Moab. The high place for Chemosh is placed on the hill east of Jerusalem — the Mount of Olives, which 2 Kings 23:13 calls &ldquo;the hill of corruption&rdquo; (<em>har hammašḥît</em>), where Josiah will defile these shrines. The Mount of Olives, site of Jesus&rsquo; prayer and arrest, had been defiled by Solomon&rsquo;s apostasy centuries before and awaited Josiah&rsquo;s reform.</p>',
    "8": '<p>For all his foreign wives Solomon built high places and burned incense and sacrificed to their gods. The plurality — <em>kōl-nāšāyw hannokrîyôt</em>, all his foreign wives — extends the apostasy to every foreign cult imported into the royal household. The scale of the religious accommodation matches the scale of the diplomatic alliances: hundreds of foreign deities were granted royal cult sites. The Temple that YHWH consecrated in ch9 now coexists with a proliferation of foreign sanctuaries on the surrounding heights.</p>',
    "9": '<p><em>Wayyitʾanep yhwh bišəlōmōh</em> — YHWH was angry with Solomon. The verb <em>ʾānap</em> (be angry) is used of YHWH&rsquo;s anger against covenant violations (Deut 1:37; 4:21). The basis of the anger is specified: Solomon&rsquo;s heart had turned away from YHWH who had appeared to him twice and had specifically warned him against going after other gods (9:6-9). YHWH&rsquo;s anger is not a raw emotional reaction but a measured covenant response to deliberate violation by a uniquely privileged king.</p>',
    "10": '<p>YHWH had specifically commanded Solomon concerning this matter (<em>ṣiwwāh ʾēlāyw ʾal-haddāḇār hazzeh</em>), and Solomon did not keep what YHWH had commanded. The combination of prior warning, explicit command, and subsequent violation constitutes the most aggravated form of covenant breach — not ignorance but willful disobedience of a directly communicated divine prohibition. The covenant theology of Deuteronomy 13 envisions the harshest judgment for deliberate apostasy; Solomon has fulfilled its conditions.</p>',
    "11": '<p><em>Wayyōʾmer yhwh lišəlōmōh yaʿan ʾăšer hāyǝṯāh-zōʾt ʿimmāk</em> — &ldquo;since this is what you have done...&rdquo; The judicial sentence follows the statement of crime. YHWH announces: &ldquo;I will surely tear the kingdom from you and give it to your servant.&rdquo; The verb <em>qāraʿ</em> (tear) is the same used for Ahijah&rsquo;s acted prophecy with the garment in v30. The tearing of the kingdom is both metaphor and coming reality. The word <em>ʿeḇed</em> (servant) — the recipient — will be Jeroboam (v26).</p>',
    "12": '<p>YHWH grants a delay: <em>raq-bîyāmêkā lōʾ ʾeʿeśennāh</em> — &ldquo;only in your days I will not do it, for the sake of your father David.&rdquo; The delay is a function of the Davidic covenant, not Solomon&rsquo;s merit. <em>Lĕmaʿan dāwid ʾāḇîkā</em> — &ldquo;for the sake of your father David.&rdquo; David&rsquo;s faithfulness delays judgment upon his unfaithful son. This pattern — Davidic merit deferring deserved judgment — runs throughout Kings (15:4; 2 Kgs 8:19; 19:34; 20:6). Grace through imputed merit operates across the dynastic line.</p>',
    "13": '<p>The mitigation: YHWH will not tear away all the kingdom; one tribe will remain for David&rsquo;s sake and for Jerusalem&rsquo;s sake (<em>lĕmaʿan dāwid ʿabdî ûlĕmaʿan yərûšālayim ʾăšer bāḥartî ḇāh</em>). The double <em>lĕmaʿan</em> — for the sake of David, for the sake of Jerusalem — anchors the remnant in covenant commitment rather than anyone&rsquo;s current merit. The one tribe is Judah (with Benjamin by implication). YHWH&rsquo;s prior commitments limit the scope of judgment even when fully deserved.</p>',
    "14": '<p>YHWH raises up (<em>wayyāqem yhwh śāṭān lišəlōmōh</em>) Hadad the Edomite as an adversary (<em>śāṭān</em>). The word <em>śāṭān</em> here means &ldquo;adversary&rdquo; or &ldquo;opponent&rdquo; in the legal/military sense — not yet the full demonic personification of later usage (cf. Job 1-2). YHWH is the active agent: he raises the adversary. External political opposition to Solomon is YHWH&rsquo;s covenant instrument, not mere geopolitical accident. Hadad was of Edomite royal descent — his existence as a refugee in Egypt is the consequence of David&rsquo;s military campaign against Edom (2 Sam 8:13-14). The seeds of Solomon&rsquo;s trouble were planted by his father&rsquo;s victories.</p>',
    "15": '<p>When David was in Edom and Joab the army commander went up to bury the slain and struck down every male in Edom, Hadad escaped. The claim that Joab &ldquo;struck down every male&rdquo; (<em>kol-zāḵār bĕʾĕḏôm</em>) is hyperbolic — the point is a comprehensive military destruction. Hadad&rsquo;s survival as an infant, his flight to Egypt, and his eventual return constitutes the mechanism by which David&rsquo;s military success plants the seeds of Solomon&rsquo;s troubles. Thorough military victories can generate generational enemies.</p>',
    "16": '<p>Joab and all Israel remained six months in Edom until every male was killed. The six-month campaign is the historical basis for Hadad&rsquo;s enduring hostility — his entire family and court were destroyed by Israelite military action. Edom&rsquo;s enmity toward Israel will persist across the entire period of Kings and feature prominently in the prophetic literature (Obadiah; Isa 34; Ezek 35-36). The destruction of a royal line creates dynastically motivated revenge across generations.</p>',
    "17": '<p>Hadad fled as a young child (<em>naʿar qāṭōn</em>) with Edomite servants through Midian and Paran to Egypt. The flight route — Midian (northwest Arabia) and Paran (Sinai/Negev wilderness) — traces the desert corridor that had also been Israel&rsquo;s path out of Egypt. Pharaoh gave Hadad a house, food, and land — royal patronage for a political exile. The same Egyptian royal household that gave Solomon a wife (3:1) shelters his future adversary. Egypt&rsquo;s ambivalent relationship with Israel — ally and enemy simultaneously — is concentrated in these two symmetrical stories.</p>',
    "18": '<p>Pharaoh gave Hadad the sister of Tahpenes the queen as a wife, integrating him into the Egyptian royal household at a level comparable to Solomon himself. Both Solomon and Hadad are sons-in-law of Pharaoh (of different pharaohs). The irony is structural: Solomon&rsquo;s Egyptian alliance, meant to secure the empire, produces the adversary who will trouble it. Political marriages solve short-term problems and create long-term ones — a lesson that the Davidic narrative keeps reinforcing.</p>',
    "19": '<p>Hadad found great favor in the sight of Pharaoh: <em>wayyimṣāʾ ḥadad ḥēn bĕʿênê parʿōh mǝʾōd</em>. The phrase <em>māṣāʾ ḥēn bǝʿênê</em> (find favor in the eyes of) is the formulaic language of providential advancement — the same formula used for Joseph in Egypt (Gen 39:4), for Moses (Exod 33:12), and for Ruth (Ruth 2:2). YHWH&rsquo;s adversaries advance through the same providential channels as his servants, because all history — including the instruments of judgment — operates under his direction.</p>',
    "20": '<p>Tahpenes weaned Hadad&rsquo;s son Genubath in the palace, among the sons of Pharaoh. The child of an Edomite royal exile, nursed by the Egyptian queen, raised in the palace — Genubath is a figure of entanglement: Edomite identity, Egyptian formation, future role as Hadad&rsquo;s heir. The detail personalizes what would otherwise be merely political: the adversary YHWH is raising against Solomon has a family, a history, and a household intertwined with Egypt.</p>',
    "21": '<p>When Hadad heard in Egypt that David had died and Joab was dead, he said to Pharaoh: &ldquo;Send me away that I may go to my own land.&rdquo; The death of his two enemies — the king who had prosecuted the Edomite campaign and the general who had executed it — triggers Hadad&rsquo;s request to return. Pharaoh&rsquo;s question — &ldquo;what do you lack with me?&rdquo; — underlines the comfort of Hadad&rsquo;s Egyptian life. His insistence on returning, even from luxury, reflects the drive of dispossession: the exile always wants to go home.</p>',
    "22": '<p>Pharaoh&rsquo;s &ldquo;what have you lacked with me&rdquo; is answered by Hadad&rsquo;s firm request. The narrator does not explain what Hadad planned to do upon return — his role as YHWH&rsquo;s adversary against Solomon is assumed. The brevity of the account is characteristic of the DtrH&rsquo;s adversary narratives: Hadad&rsquo;s activities after his return are not described. His existence as a standing threat to Solomon&rsquo;s southern border is sufficient context for the theological point: YHWH&rsquo;s judgment instruments are raised and positioned, whether active or latent.</p>',
    "23": '<p>The second adversary: Rezon son of Eliada, who had fled from his master Hadadezer king of Zobah. Rezon assembled a raiding band and became king over Damascus when David had put down the Zobah coalition (2 Sam 8:3-8). The Aramean kingdom of Damascus that Rezon founded will become Israel&rsquo;s most persistent enemy for the next century and a half — Ben-hadad I, Ben-hadad II, and Hazael are his successors. What begins as Solomon&rsquo;s era of trouble will become the great northern threat to both Israel and Judah through the 9th and 8th centuries.</p>',
    "24": '<p>Rezon gathered men after David slaughtered the Zobah forces and went to Damascus, becoming its king. The Damascene kingdom that emerged from David&rsquo;s victory over Zobah will outlast the divided monarchy of Israel and Judah. Solomon&rsquo;s father solved a military problem by creating a political vacuum into which a hostile dynasty moved; the unintended consequences operate across centuries. The DtrH records this with compressed irony: the greatest military achievement of David&rsquo;s reign generates one of the most durable enemies of his successor.</p>',
    "25": '<p>Rezon was adversary (<em>śāṭān</em>) to Israel all the days of Solomon. <em>Wayyāqōṣ bĕyiśrāʾēl wayyimlōk ʿal-ʾărām</em> — he abhorred Israel and reigned over Aram. The paired adversaries — Hadad from the south (Edom), Rezon from the north (Damascus) — bracket Solomon&rsquo;s empire geographically. Both are YHWH&rsquo;s raised instruments; both arise from the unresolved consequences of David&rsquo;s campaigns. The empire that appeared invincible in ch10 is already surrounded by hostile forces the king cannot suppress.</p>',
    "26": '<p>Jeroboam son of Nebat is introduced as the third and most consequential adversary. <em>ʾEprātî</em> — an Ephraimite — places him in the most politically assertive northern tribe. <em>Wayyārem yāḏ bammelek</em> — he &ldquo;lifted his hand against the king&rdquo; — the idiom for rebellion against royal authority (cf. 2 Sam 20:21). The three adversaries together (Hadad, Rezon, Jeroboam) represent the disintegration of the Solomonic empire from south, north, and within — the coalition of consequences that YHWH has assembled.</p>',
    "27": '<p>The occasion for Jeroboam&rsquo;s prominence: Solomon was building the Millo and repairing the breach in the wall of the city of David. <em>Wayyarᵊʾ šəlōmōh ʾet-hannáʿar kî ʿōśēh-mǝlāʾkāh hûʾ</em> — Solomon saw the young man that he was a capable worker. The administrative appointment of an able man to supervise Ephraim&rsquo;s labor directly seeds the rebellion: the man Solomon promotes to manage the burden of forced labor becomes the leader of those who will revolt against that burden in ch12.</p>',
    "28": '<p>Jeroboam was <em>gibbôr ḥayil</em> (a capable man of valor) — the same designation used for Boaz (Ruth 2:1) and David&rsquo;s military heroes. Solomon appointed him over all the labor levy of the house of Joseph (Ephraim and Manasseh). The appointment gave him oversight of the largest tribal labor force. The connection between forced-labor resentment and northern secession is explicit in 12:4: &ldquo;your father made our yoke heavy...&rdquo; Solomon&rsquo;s organizational genius in appointing competent men simultaneously created the leadership infrastructure of the coming rebellion.</p>',
    "29": '<p>As Jeroboam was leaving Jerusalem, the prophet Ahijah the Shilonite met him on the road. The setting — outside Jerusalem, on the road — follows the pattern of prophetic encounters with those who will be kings (Samuel and Saul, 1 Sam 9; Samuel and David, 1 Sam 16). Ahijah&rsquo;s hometown Shiloh was the location of the old tribal sanctuary that preceded the Jerusalem Temple; a prophet from Shiloh speaking against the Jerusalem establishment carries the weight of the northern tribal religious tradition.</p>',
    "30": '<p><em>Wayyitpōś ʾaḥiyyāh ḇabbeged heḥādāš ʾăšer ʿālāyw wayyiqrāʿēhû šnêm ʿāśār qərāʿîm</em> — Ahijah took his new garment and tore it into twelve pieces. The acted prophecy uses a physical object to embody the divine word. The new garment represents the kingdom — a whole that will be divided. Tearing into twelve pieces maps precisely onto the twelve tribes; ten given to Jeroboam, one (or two) remaining for David&rsquo;s house. Acted prophecies in the OT typically involve irreversibility — the garment cannot be untorn, as the kingdom cannot remain whole after the sin of Solomon.</p>',
    "31": '<p><em>Qaḥ-ləkā ʿăśārāh qərāʿîm kî kōh ʾāmar yhwh ʾĕlōhê yiśrāʾēl</em> — &ldquo;Take for yourself ten pieces, for thus says the LORD God of Israel.&rdquo; The ten pieces represent the ten northern tribes. YHWH&rsquo;s speech uses the messenger formula — <em>kōh ʾāmar yhwh</em> — the prophetic announcement of divine decree. The oracle is not primarily about Jeroboam&rsquo;s fitness but about YHWH&rsquo;s judgment on Solomon. Jeroboam receives the ten tribes as the instrument through whom YHWH acts, not as a reward for righteousness.</p>',
    "32": '<p>One tribe remains for David&rsquo;s servant and for Jerusalem the chosen city: <em>lĕmaʿan ʿabdî dāwid ûlĕmaʿan yərûšālayim hāʿîr ʾăšer bāḥartî ḇāh</em>. The language of double election — David and Jerusalem — defines what cannot be taken. The one tribe is Judah; Benjamin will eventually be grouped with it. The preservation of the Davidic remnant in Judah is not earned by anyone currently living but is guaranteed by YHWH&rsquo;s past commitments.</p>',
    "33": '<p>The catalog of sins that justify the division: Solomon went after Ashtoreth of the Sidonians, Chemosh of Moab, and Milcom of the Ammonites — each deity listed with their national origin. The formula <em>wəlōʾ-hālak bidərāḵay lāʿăśôt hayyāšār bĕʿênāyw</em> — he did not walk in my ways or do what was right in my eyes — applies the Davidic-walking standard. The catalog is also a geographic map of Solomon&rsquo;s diplomatic alliances: the deities his wives brought are the gods of the nations whose daughters he married.</p>',
    "34": '<p>YHWH will not take the whole kingdom from Solomon during his lifetime: <em>kî nāśīʾ ʾeśśennû kōl yəmê ḥayyāyw</em> — &ldquo;I will make him a prince all the days of his life.&rdquo; The word <em>nāśîʾ</em> (prince, leader) is used rather than <em>melek</em> (king) — a subtle demotion in divine evaluation. For the sake of David who kept the commandments, the kingdom is preserved in Solomon&rsquo;s hands through his lifetime. David&rsquo;s righteousness protects an unrighteous son: grace through imputed merit operates across the dynastic line.</p>',
    "35": '<p>After Solomon, the kingdom will be divided: ten tribes to Jeroboam, one tribe to Solomon&rsquo;s son. <em>Wənātattî lǝkā ʾet ʿeśeret haššǝḇāṭîm</em> — the divine gift of ten tribes to Jeroboam is YHWH&rsquo;s act, not Jeroboam&rsquo;s seizure. This framing is theologically critical: the division of the kingdom is not political accident or mere human ambition but YHWH&rsquo;s judicial act. This governs the entire subsequent history of the divided monarchy — the political division is always, at its root, a theological reality.</p>',
    "36": '<p><em>Wəlibənô ʾettēn šēbeṭ ʾeḥāḏ lĕmaʿan hĕyôt nîr lǝdāwid ʿabdî kol-hayyāmîm lǝpānay bîrûšālāyim</em> — &ldquo;to his son I will give one tribe, that there may be a lamp (<em>nîr</em>) for David my servant before me in Jerusalem forever.&rdquo; The <em>nîr</em> (lamp) of David is one of the most evocative images in Kings — the perpetually burning lamp of the covenant dynasty. The same image recurs in 15:4 (for Abijam), 2 Kings 8:19 (for Joram), and echoes the Temple lampstand burning continuously (Exod 27:20-21). The Davidic lamp in Jerusalem: the dynasty will not be extinguished even when reduced to a single flickering tribe.</p>',
    "37": '<p>To Jeroboam: <em>wəʾōtəkā ʾeqqāḥ wəmālaḵtā bəkōl ʾăšer tɔʾawweh napšəkā wəhāyîtā melek ʿal-yiśrāʾēl</em> — &ldquo;I will take you, and you will reign over all that your soul desires.&rdquo; The divine appointment precedes the human action; Jeroboam receives the kingdom as a gift before he takes it. The phrase <em>ʾăšer tɔʾawweh napšəkā</em> (all that your soul desires) is lavishly generous — YHWH offers not a consolation prize but a full mandate. The question is whether Jeroboam will honor the covenant condition that follows.</p>',
    "38": '<p>The conditional covenant given to Jeroboam mirrors the Solomonic covenant of 9:4-7: <em>wəhāyāh ʾim-tišmaʿ ʾēt kol-ʾăšer ʾăṣawwekā wəhālaḵtā ḇidərāḵay wəʿāśîtā hayyāšār bĕʿênay</em> — if you listen to all I command you and walk in my ways. The promised reward: &ldquo;I will be with you and build you an enduring house as I built for David.&rdquo; <em>Bayit neʾĕmān</em> (enduring house) is the Davidic covenant terminology of 2 Sam 7:16. YHWH offers Jeroboam the same covenant structure as David — the northern kingdom&rsquo;s legitimacy depends not on lineage but on obedience. Jeroboam will fail this condition immediately (12:28-29).</p>',
    "39": '<p><em>Wəʾăʿanneh ʾet-zeraʿ dāwid ʿal-zōʾt</em> — &ldquo;and I will afflict the descendants of David because of this.&rdquo; The affliction of David&rsquo;s line is itself a measure of YHWH&rsquo;s faithfulness: the covenant requires that sin be punished even within the chosen dynasty. <em>Raq lōʾ kol-hayyāmîm</em> — but not forever. YHWH&rsquo;s judgment on David&rsquo;s line is not final annihilation but disciplinary correction. The &ldquo;not forever&rdquo; points forward to the eschatological restoration of the Davidic throne that the prophets will proclaim (Amos 9:11; Ezek 37:24-25; Luke 1:32-33).</p>',
    "40": '<p>Solomon sought to kill Jeroboam: <em>wayyəḇaqeš šəlōmōh lăhamit ʾet-yārāḇəʿām</em>. The oracle given through Ahijah presumably became known to Solomon through informants. Jeroboam fled to Egypt — specifically to Shishak (<em>šîšaq</em>), known from Egyptian records as Sheshonq I, founder of the 22nd (Libyan) Dynasty (reigned ca. 945-924 BCE). The same Shishak will invade Judah in Rehoboam&rsquo;s fifth year (14:25-26) and sack Jerusalem. Jeroboam&rsquo;s Egyptian refuge is the political preparation for a future Egyptian military intervention against David&rsquo;s house — yet another consequence of Solomon&rsquo;s Egyptian entanglement.</p>',
    "41": '<p>The regnal closing formula: <em>wəyeter diḇrê šəlōmōh wəkol-ʾăšer ʿāśāh wəḥoḵmātô hălōʾ-hēm kǝṯûḇîm ʿal-sēper diḇrê šəlōmōh</em> — &ldquo;the rest of Solomon&rsquo;s acts, all he did and his wisdom, are they not written in the Book of the Acts of Solomon?&rdquo; This is the DtrH&rsquo;s standard citation of a source document now lost. &ldquo;The Book of the Acts of Solomon&rdquo; was apparently an official court chronicle. The Deuteronomistic History cites similar documents for subsequent kings — &ldquo;the Book of the Chronicles of the Kings of Israel/Judah&rdquo; — as sources for further reading, acknowledging that the theological-selective narrative is not a complete record.</p>',
    "42": '<p>Solomon reigned in Jerusalem over all Israel for forty years. The round number forty (<em>ʾarbaʿîm šānāh</em>) matches David&rsquo;s reign (2 Sam 5:4) and the wilderness generation (Num 14:33-34). In Deuteronomistic chronology, forty years is the standard unit for a significant reign or era. The equivalence of Solomon and David in regnal length creates a structural symmetry: father and son each ruled forty years, together constituting the eighty-year unified monarchy before the division.</p>',
    "43": '<p>Solomon died and was buried with his ancestors in the city of David. <em>Wayyimlōk rǝḥaḇʿām bənô taḥtāyw</em> — Rehoboam his son reigned in his place. The succession formula is brief and unqualified — no blessing, no elegy. The contrast with the elaborate praise of ch10 is felt: the king who sat on the incomparable ivory throne, whose wisdom surpassed all the earth&rsquo;s kings, is buried with the same terse formula applied to every other king. The golden age ends with a son who will, within a year, lose most of the empire his father built.</p>'
  }
}

def main():
    existing = load_comm('mkt-context', '1kings')
    merge_comm(existing, KINGS)
    save_comm('mkt-context', '1kings', existing)
    total = sum(len(v) for v in KINGS.values())
    print(f'1kings mkt-context ch10-11: wrote {total} verses')

if __name__ == '__main__':
    main()
