"""
MKT Original Commentary — Matthew chapters 13–14
Run: python3 scripts/zc-original-matthew-13-14.py

Source data used:
- data/interlinear/matthew.json
- data/translation/draft/mediating/matthew.json
- data/commentary/mkt-original/matthew.json (existing ch1-12 carried forward)

Key decisions in this range:
- 13:11: mysteria (mysteries, not secrets in an esoteric sense but
  previously hidden plans of God now disclosed)
- 13:12: future passives as divine passives — "will be given" by God
- 13:14-15: Isaiah 6:9-10 cited; Matthew follows LXX but with adjustments
- 13:19: ho ponēros (the evil one, masculine, not neuter) — personal
  reference to the devil, consistent with v.39
- 13:33: sata tria = three measures (saton = ~13 liters each): ~39 liters
  of flour, a massive quantity — the leaven is not a small domestic act
- 13:35: Ps 78:2 citation — ereugomai (to utter, belch forth: a strong
  emission verb)
- 13:44: apo tēs charas (from joy) — motivates total sell-off; joy is
  the driver, not duty
- 13:55: tektōn = craftsman in wood/stone/metal, not narrowly "carpenter"
- 14:19: eulogēsen (blessed/gave thanks — eulogeō) vs. eucharistēsen: the
  Synoptic tradition uses eulogeō for the feeding, preserving the
  Jewish berakah form
- 14:22: ēnankasen (compelled — enankazō): forceful necessity, not a polite
  request
- 14:27: egō eimi — "It is I/I AM": the divine name echoes Exod 3:14 in
  context of sea-walking
- 14:31: oligopiste — coined compound unique to Matthew's vocabulary
- 14:33: prosekynēsan (worshipped): the climactic act after the storm (cf.
  8:27 where the crowd merely marveled)
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

MATTHEW = {
  "13": {
    "1": '<p><strong>en tē hēmera ekeinē</strong> — on that day (the phrase links ch13 directly to ch12\'s rejection controversies; the parables are Jesus\'s response to the opposition just described) — <em>exelthōn ho Iēsous apo tēs oikias ekathēto para tēn thalassan</em> (Jesus going out of the house was sitting by the sea — <em>ekathēto</em> imperfect: was sitting, a settled posture for teaching). The movement from the house (private teaching) to the sea (public teaching) frames the parabolic discourse as a response to the situation of mixed reception described in ch12.</p>',
    "2": '<p><strong>kai synēchthēsan pros auton ochloi polloi</strong> — and large crowds gathered to him (<em>synēchthēsan</em> aorist passive of <em>synagō</em>: were gathered, assembled — a passive of circumstance: they gathered spontaneously) — <em>hōste auton eis ploion embanta kathēsthai</em> (so that he got into a boat and was sitting — <em>embanta</em> aorist participle: having stepped in; <em>kathēsthai</em> present infinitive: to be sitting): the boat provides both distance from the crowd and acoustics over water. The seated posture is the formal Jewish teaching position.</p>',
    "3": '<p><strong>kai elalēsen autois polla en parabolais</strong> — and he spoke to them many things in parables (<em>parabolais</em>: a parable — from <em>paraballō</em>, to throw alongside, to compare; in Jewish usage a <em>mashal</em>, a saying or story that uses one domain to illuminate another) — <em>legōn idou exēlthen ho speirōn tou speirein</em> (saying: behold, the sower went out to sow — the Greek is literally "the one sowing went out to the sowing of him": his purpose is built into the description). The parable opens without explaining its referent; the audience must work toward the meaning.</p>',
    "4": '<p><strong>en tō speirein auton</strong> — while he was sowing (<em>en tō speirein auton</em>: an articular infinitive with subject — the standard Matthean idiom for simultaneous action) — <em>ha men epesen para tēn hodon</em> (some fell along the road): the four soil types are presented in ascending order of receptivity. <em>Para tēn hodon</em> (alongside/along the path): the hard-packed path running through a field; seed falling there lies on the surface. <em>Elthen ta peteina kai katephagen auta</em> (the birds came and ate them up — <em>kataphagō</em> aorist: devoured completely).</p>',
    "5": '<p><strong>alla de epesen epi ta petrōdē</strong> — other fell on the rocky places (<em>petrōdē</em>: stony ground, rocky soil — <em>petra</em> + <em>-ōdēs</em>: full of rock, rocky) — <em>hopou ouk eichen gēn pollēn</em> (where it did not have much soil): the problem is not the absence of soil but its shallowness. <em>Eutheōs exanateillen</em> (it sprang up immediately — <em>eutheōs</em>: the characteristic word of Mark\'s urgency, here in Matthew for the false urgency of shallow enthusiasm) — <em>dia to mē echein bathos gēs</em> (because of not having depth of soil: the articular infinitive with <em>dia</em> expressing cause).</p>',
    "6": '<p><strong>hēliou de anateilantos ekaumatisthē</strong> — the sun rising, it was scorched (<em>anateilantos</em> genitive absolute: the sun having risen; <em>ekaumatisthē</em> aorist passive of <em>kaumatizō</em>: to be burned by scorching heat — the same verb in Rev 16:8-9 for eschatological burning) — <em>kai dia to mē echein rhizan exēranthē</em> (and because of not having root it withered: <em>rhizan</em> accusative of <em>rhiza</em>, root; the absence of root is the explanation for both the quick sprouting and the quick dying). Root and depth are correlated: shallow soil produces rootless growth.</p>',
    "7": '<p><strong>alla de epesen epi tas akanthas</strong> — other fell among the thorns (<em>akanthai</em>: thorns, thorn-plants; this soil has plant-growing capacity but already contains competing growth) — <em>kai anebēsan hai akanthai kai epnixan auta</em> (and the thorns grew up and choked them — <em>epnixan</em> aorist of <em>pnigō</em>: to choke, throttle; the same root used in 18:28 for seizing a man by the throat): the thorns did not prevent germination but prevented the seed from producing grain. The soil is good enough to grow; the competition is what kills the yield.</p>',
    "8": '<p><strong>alla de epesen epi tēn gēn tēn kalēn</strong> — other fell on the good soil (<em>gēn tēn kalēn</em>: the good/fine soil — <em>kalos</em>, the word for beauty-in-goodness, appropriate quality) — <em>kai edidou karpon</em> (and was giving fruit — <em>edidou</em> imperfect: was continuing to give, an ongoing producing): the imperfect marks the sustained yield. <em>Ho men hekaton ho de hexēkonta ho de triakonta</em> (one a hundred, one sixty, one thirty): the yields are all above the typical ancient grain yield of 5-7x. A hundredfold is exceptional; even thirtyfold is generous. The variety is not graded bad-to-good but simply differentiated abundance.</p>',
    "9": '<p><strong>ho echōn ōta akouetō</strong> — the one having ears, let them hear — the ear formula (cf. 11:15; 13:43) marks the end of the parable without explanation, creating space for active interpretation. The parable does not announce its meaning; it invites the hearer to locate themselves in the soils. <em>Akouetō</em> present imperative: a continuous command to hear and keep hearing. The formula also implies that not all who "hear" the parable thereby "hear" its meaning — the distinction between hearing and understanding is the theme of the next pericope.</p>',
    "10": '<p><strong>dia ti en parabolais laleis autois</strong> — why do you speak to them in parables (<em>dia ti</em>: on account of what, why — a purpose question) — the disciples\' question presupposes they have already understood the parabolic discourse differently from the crowd. <em>Autois</em> (to them): the distinction is between "them" (the crowd) and the disciples asking the question. The question opens the theological explanation of vv.11-17: the parables are not a simpler teaching method but a mode of disclosure that reveals to some and conceals from others.</p>',
    "12": '<p><strong>hostis gar echei dothēsetai autō kai perisseuphthēsetai</strong> — for whoever has, it will be given to him and he will have abundance (<em>dothēsetai</em> future passive divine: it will be given by God; <em>perisseuphthēsetai</em> future passive: he will have it in abundance) — <em>hostis de ouk echei kai ho echei arthēsetai ap autou</em> (but whoever does not have, even what he has will be taken from him — <em>arthēsetai</em> future passive divine): the principle is not economic but revelatory: those who receive the mystery of the kingdom receive more; those who reject it lose even the initial capacity. The future passives are divine passives throughout.</p>',
    "13": '<p><strong>dia touto en parabolais autois lalō hoti blepontes ou blepousin</strong> — this is why I speak to them in parables: seeing they do not see — <em>dia touto</em> (this is why): the parables are not despite the crowd\'s blindness but in response to it. <em>Blepontes ou blepousin kai akouontes ouk akouousin oude syniousin</em> (seeing they do not see, and hearing they do not hear nor understand — <em>syniousin</em> present of <em>syniēmi</em>, to put together, comprehend): the three-fold failure (seeing/seeing, hearing/hearing, understanding). This is a description of the crowd\'s spiritual state, not a permanent divine decree of blindness imposed from outside.</p>',
    "14": '<p><strong>kai anaplēroutai autois hē prophēteia Ēsaiou hē legousa</strong> — and on them is being fulfilled the prophecy of Isaiah saying (<em>anaplēroutai</em> present passive: is being fulfilled, completed — <em>ana</em> + <em>plēroō</em>: the <em>ana</em>- prefix can intensify or indicate completion) — the Isaiah 6:9-10 citation follows. This is a different fulfillment formula than Matthew\'s usual <em>hina plērōthē</em>: the present tense marks ongoing fulfillment rather than a single completed event. Isaiah\'s commission (6:9-10) is a description of the audience Jesus now faces.</p>',
    "15": '<p><strong>epachynthē gar hē kardia tou laou toutou</strong> — for the heart of this people has grown dull/fat (<em>epachynthē</em> aorist passive of <em>pachynō</em>: to make thick/fat; the idiom for spiritual insensitivity — a heart grown so padded it cannot feel) — <em>kai tois ōsin bareos ēkousan</em> (and they hear with heavy/dull ears — <em>bareos</em>: heavily, with weight, with difficulty): the ears are overburdened, not absent. <em>Kai tous ophthalmous autōn ekammusan</em> (and they have closed their eyes — <em>kammyō</em>: to close the eyes deliberately, a voluntary shutting). The verse diagnoses willful, not merely circumstantial, blindness.</p>',
    "16": '<p><strong>hymōn de makarioi hoi ophthalmoi hoti blepousin</strong> — but blessed are your eyes because they see — the Beatitude form applied to seeing and hearing, reversing the Isaiah curse. The disciples\' seeing is not their achievement but a gift that marks them as blessed. <em>Kai ta ōta hymōn hoti akouousin</em> (and your ears because they hear): the inversion of v.14-15 is complete — where the crowd cannot connect seeing/hearing to perceiving/understanding, the disciples\' organs of perception actually function.</p>',
    "17": '<p><strong>amen gar legō hymin hoti polloi prophētai kai dikaioi epethymēsan idein ha blepete</strong> — truly I tell you that many prophets and righteous people longed to see what you see (<em>epethymēsan</em> aorist of <em>epithymeō</em>: to desire ardently — the word can carry the sense of intense longing or craving; the prophets and righteous ones desired this with an unfulfilled longing) — <em>kai ouk eidon</em> (and did not see it). The disciples are positioned at the hinge of redemptive history: the prophets pointed forward to what is now present; the disciples receive what the prophets only anticipated.</p>',
    "18": '<p><strong>hymeis oun akousate tēn parabolēn tou speirontos</strong> — you therefore hear the parable of the sower — <em>hymeis oun</em> (you therefore): emphatic second person, contrasting the disciples\' privileged hearing with the crowd\'s deafness just described. <em>Akousate</em> aorist imperative: a sharp, focused act of hearing. The explanation that follows (vv.19-23) does not simply decode the parable but applies it — each soil type is identified by how one relates to <em>ho logos tēs basileias</em> (the word of the kingdom).</p>',
    "19": '<p><strong>pantos akouontos ton logon tēs basileias kai mē synientos</strong> — everyone hearing the word of the kingdom and not understanding it (<em>synientos</em> present participle of <em>syniēmi</em>: not putting together, not comprehending) — <em>erchetai ho ponēros kai harpazei to esparmenon en tē kardia autou</em> (the evil one comes and snatches away what was sown in his heart — <em>ho ponēros</em>: the evil one, masculine — a personal reference to the devil as identified in v.39; <em>harpazei</em> present: snatches, the same aggressive seizure-verb as 12:29 for plundering the strong man\'s house). The path-hearer\'s defining feature is non-understanding (<em>mē synieis</em>).</p>',
    "20": '<p><strong>ho de epi ta petrōdē spareis</strong> — the one sown on the rocky places (<em>spareis</em> aorist passive participle of <em>speirō</em>: having been sown — the person is identified with the seed sown in a location) — <em>houtos estin ho ton logon akouōn kai eutheōs meta charas lambanōn auton</em> (this is the one who hears the word and immediately receives it with joy — <em>eutheōs</em>: immediately, instantly; <em>meta charas</em>: with joy): the immediate joyful reception is itself diagnostic. Speed and emotion without root signal shallow engagement rather than genuine reception.</p>',
    "21": '<p><strong>ouk echei de rhizan en heautō</strong> — but he has no root in himself (<em>rhizan en heautō</em>: root within himself, not rooted in external soil only but internally without rootedness) — <em>alla proskaireos estin</em> (but is temporary — <em>proskairos</em>: for a season, time-limited): the word contains <em>kairos</em> (appointed time); this person is only for the appointed moment. <em>Genomenēs de thlipseōs ē diōgmou dia ton logon eutheōs skandalizatai</em> (when trouble or persecution comes on account of the word, immediately he stumbles/falls away — <em>skandalizatai</em> present passive: is caused to stumble): the same word Jesus used in 11:6 for the potential offense at himself.</p>',
    "22": '<p><strong>ho de eis tas akanthas spareis</strong> — the one sown among the thorns — <em>hē merimna tou aiōnos kai hē apatē tou ploutou sympnigei ton logon</em> (the worry of the age and the deceitfulness of wealth choke the word — <em>merimna tou aiōnos</em>: the anxiety belonging to this present age; <em>apatē tou ploutou</em>: the deceit/deception of wealth — <em>apatē</em>, deceit, the word for active falsehood; wealth deceives: it promises security and satisfaction it cannot deliver). <em>Sympnigei</em> present: is choking — the present tense marks an ongoing process. <em>Kai akarpos ginetai</em> (and it becomes unfruitful — the thorn-hearer hears and perhaps even understands, but bears nothing).</p>',
    "23": '<p><strong>ho de epi tēn kalēn gēn spareis</strong> — the one sown on the good soil — <em>houtos estin ho ton logon akouōn kai synieis</em> (this is the one who hears the word and understands it — <em>synieis</em> present participle of <em>syniēmi</em>: the understanding that is the path-hearer\'s absence, now present). <em>Hos dē karpophorei kai poiei ho men hekaton ho de hexēkonta ho de triakonta</em> (who indeed bears fruit and produces — <em>karpophorei</em> present: is bearing fruit; <em>poiei</em> present: is producing, continuously): the fruit is present-tense ongoing, and the yields (hundred, sixty, thirty) represent differentiated abundance, not a ranking of good-better-best.</p>',
    "24": '<p><strong>allēn parabolēn parethēken autois legōn</strong> — he placed another parable before them (<em>parethēken</em> aorist of <em>paratithēmi</em>: to place beside, set before — a serving/presenting verb; parables are presented as food for the hearer) — <em>hōmoiōthē hē basileia tōn ouranōn anthrōpō speironti kalon sperma en tō agrō autou</em> (the kingdom of the heavens is like a man who sowed good seed in his field): the kingdom is compared to the whole situation, not merely to the man or the seed. The noun <em>anthrōpō</em> (a man) identifies the figure who is later revealed as the Son of Man (v.37).</p>',
    "25": '<p><strong>en de tō katheudein tous anthrōpous ēlthen autou ho echthros kai epespeiren zizania</strong> — but while the people were sleeping his enemy came and sowed weeds among the wheat (<em>katheudein tous anthrōpous</em>: the people sleeping — not negligence but normal rest; <em>echthros</em>: enemy; <em>epespeiren zizania</em>: sowed tares/weeds over — <em>zizanion</em>, probably <em>Lolium temulentum</em>, darnel, a weed that closely resembles wheat in early growth stages and is toxic) — <em>ana meson tou sitou</em> (among the midst of the wheat): the tares are sown specifically among, not separately from, the wheat. The mixture is intentional.</p>',
    "26": '<p><strong>hote de eblastēsen ho chortos kai karpon epoiēsen</strong> — when the grain sprouted and bore fruit (<em>eblastēsen</em> aorist of <em>blastanō</em>, to sprout, germinate) — <em>tote ephanē kai ta zizania</em> (then the tares also appeared — <em>ephanē</em> aorist passive of <em>phainō</em>: appeared, became visible): the tares are recognizable only when both have matured enough to distinguish. Darnel is visually indistinguishable from wheat until the grain heads form; the enemy exploits this by planting them together. Early separation would destroy wheat; only at harvest is safe separation possible.</p>',
    "27": '<p><strong>proselthontes de hoi douloi tou oikodespotou eipon autō</strong> — approaching, the servants of the householder said to him — <em>kyrie ouchi kalon sperma espeiras en tō sō agrō</em> (sir/lord, did you not sow good seed in your field? — <em>kyrie</em>: the address of a servant to a master): the servants presuppose the master\'s competence; the question expresses genuine puzzlement, not accusation. <em>Pothen oun echei zizania</em> (how then does it have tares? — <em>pothen</em>: from where? whence? a question of source): they want to identify the origin of the contamination.</p>',
    "28": '<p><strong>ho de ephē autois echthros anthrōpos touto epoiēsen</strong> — he said to them: an enemy man did this (<em>echthros anthrōpos</em>: a hostile person — the repetition of <em>echthros</em> from v.25 identifies the source without naming the devil yet; that identification comes in the interpretation of v.39) — <em>hoi de douloi legousin autō theleis oun apelthontes syllexōmen auta</em> (the servants say to him: do you want us therefore, going out, to gather them up — <em>syllexōmen</em> aorist subjunctive: to collect, pull out): the servants\' offer is premature. Their instinct for immediate purity would destroy the wheat.</p>',
    "29": '<p><strong>ho de phēsin ou</strong> — he says: no (<em>phēsin</em> historical present: says — the vividness of direct discourse in narrative) — <em>mēpote syllегontes ta zizania ekrizoōsēte hama autois ton siton</em> (lest gathering the tares you uproot the wheat along with them — <em>mēpote</em>: lest, for fear that; <em>ekrizoōsēte</em> aorist subjunctive of <em>ekrizoō</em>: to uproot completely, to pull up by the roots): the danger is not the tares but the collateral damage of premature separation. The entanglement of root systems makes clean separation impossible until harvest.</p>',
    "30": '<p><strong>aphete synauxanesthai amphotera heōs tou therismou</strong> — let both grow together until the harvest (<em>synauxanesthai</em> present passive infinitive: to grow together, co-grow — the <em>syn</em>- prefix marks simultaneous growth) — <em>kai en kairō tou therismou erō tois theristais</em> (and at the time of the harvest I will say to the harvesters — <em>kairō</em>: the appointed moment): the harvesters are identified as angels in v.39. The harvest-sequence (weeds first → bundled → burned; wheat → gathered into the barn) is the reverse of typical priorities: removal of bad before collection of good, emphasizing the thoroughness of the final separation.</p>',
    "31": '<p><strong>allēn parabolēn parethēken autois legōn</strong> — he placed another parable before them — <em>homoia estin hē basileia tōn ouranōn kokkō sinapeōs</em> (the kingdom of the heavens is like a grain of mustard seed — <em>kokkos sinapeōs</em>: a mustard grain, probably <em>Sinapis alba</em> or <em>Brassica nigra</em>): the kingdom is compared to the whole scenario, not just the seed. <em>Hon labōn anthrōpos espeiren en tō agrō autou</em> (which a man took and sowed in his field — <em>labōn...espeiren</em>: the two-verb sequence of human action, deliberate planting).</p>',
    "32": '<p><strong>ho mikroteron men estin pantōn tōn spermatōn</strong> — which is smaller than all seeds (<em>mikroteron</em> comparative: smaller — the mustard seed was proverbially the smallest in Palestinian agricultural knowledge; <em>pantōn tōn spermatōn</em>: of all seeds, in the field/garden context; botanically not the world\'s smallest seed) — <em>hotan de auxēthē meizon tōn lachanōn estin kai ginetai dendron</em> (but when it grows it is greater than the garden plants and becomes a tree — <em>dendron</em>: a tree, though mustard shrubs are not true trees): the contrast between the proverbially small beginning and the bird-sheltering result is the point, not botanical precision. <em>Ta peteina tou ouranou...kataskhēnoun</em> — birds of the sky nesting in its branches echoes Ezek 17:22-24; 31:6; Dan 4:12 (the nations sheltering under the great kingdom-tree).</p>',
    "33": '<p><strong>allēn parabolēn elalēsen autois</strong> — he spoke another parable to them — <em>homoia estin hē basileia tōn ouranōn zymē</em> (the kingdom of the heavens is like leaven/yeast — <em>zymē</em>: leavening agent, normally a negative symbol in Jewish thought for corrupting influence, e.g., Passover unleavened bread requirements): the use of leaven as a positive image is striking. <em>Hēn labousa gynē</em> (which a woman took — the woman is the agent; the three sata = three <em>sata</em> measures, about 13 liters each = ~39 liters of flour total: an enormous quantity, enough for a large communal meal). <em>Enekrypsen eis aleurou sata tria</em> (she hid in three measures of flour — <em>enekrypsen</em>: hid, embedded — the leaven is not mixed on the surface but hidden within). <em>Heōs hou ezymōthē holon</em> — until all of it was leavened: the totality, not just the portion.</p>',
    "34": '<p><strong>tauta panta elalēsen ho Iēsous en parabolais tois ochlois</strong> — all these things Jesus spoke in parables to the crowds (<em>en parabolais</em>: in parables — not occasionally but as the exclusive mode for crowd teaching) — <em>kai chōris parabolēs ouden elalei autois</em> (and without a parable he said nothing to them): the absolute statement covers this discourse; Matthew does not claim Jesus never taught the crowds directly anywhere, but that in this parabolic discourse, parable was the only vehicle. The verse prepares the fulfillment citation of v.35.</p>',
    "35": '<p><strong>hopōs plērōthē to rēthen dia tou prophētou legontos</strong> — in order that what was spoken through the prophet might be fulfilled — the citation is Ps 78:2 (Asaph): <em>anoixō en parabolais to stoma mou</em> (I will open my mouth in parables). <em>Ereugomai kekrymena apo katabolēs kosmou</em> (I will utter/pour out things hidden since the foundation of the world — <em>ereugomai</em> future of <em>ereugomai</em>: to belch/utter forth forcefully — a strong emission verb, used in LXX Ps 19:2 for the heavens pouring out speech). <em>Katabolēs kosmou</em> (foundation/laying down of the world): the hidden things predate creation.</p>',
    "36": '<p><strong>tote apheis tous ochlous ēlthen eis tēn oikian</strong> — then leaving the crowds he came into the house — the movement from public (boat/crowds) to private (house/disciples) mirrors 13:1 in reverse. <em>Kai prosēlthon autō hoi mathētai autou legontes diasaphēson hēmin tēn parabolēn tōn zizaniōn</em> (and his disciples came to him saying: explain to us the parable of the weeds — <em>diasaphēson</em> aorist imperative of <em>diasapheō</em>: to make thoroughly clear, explain in detail — a stronger verb than simply "tell us the meaning"): the disciples, inside the house with Jesus, ask for the full disclosure that the crowd cannot receive.</p>',
    "37": '<p><strong>ho speirōn to kalon sperma estin ho huios tou anthrōpou</strong> — the one sowing the good seed is the Son of Man — the explanation is an allegory: each element is decoded. <em>Ho de agros estin ho kosmos</em> (the field is the world — <em>kosmos</em>: the whole created order, not just Israel): the kingdom\'s scope is universal, not national. The Son of Man is identified as the sower, identifying Jesus\'s mission with the planting of the good-seed people in the world-field. The identification of <em>agros = kosmos</em> is exegetically significant: the field is not the church but the world.</p>',
    "38": '<p><strong>to de kalon sperma houtoi eisin hoi huioi tēs basileias</strong> — the good seed are the sons of the kingdom (<em>huioi tēs basileias</em>: a Semitic genitive-of-characterization: those who belong to the kingdom, those shaped by it) — <em>ta de zizania houtoi eisin hoi huioi tou ponērou</em> (the tares are the sons of the evil one — <em>hoi huioi tou ponērou</em>: sons of the evil one, parallel to "sons of the kingdom"; those shaped by and belonging to the evil one): the two peoples coexist in the world, not in the church. The parable is about eschatological separation of humanity, not church discipline.</p>',
    "39": '<p><strong>ho de echthros ho speiras auta estin ho diabolos</strong> — the enemy who sowed them is the devil (<em>diabolos</em>: the slanderer, accuser — the Greek translation of Hebrew <em>satan</em>) — <em>ho de therismos synteia aiōnos estin</em> (the harvest is the end of the age — <em>synteleia aiōnos</em>: the completion/consummation of the age): <em>synteleia</em> is the word for final consummation, not merely cessation; the age comes to its intended completion. <em>Hoi de theristai angeloi eisin</em> (the harvesters are angels): the agents of final separation are divine, not human — the disciples are not to perform this separation themselves.</p>',
    "40": '<p><strong>hōsper oun syllegetai ta zizania kai pyri katakaieta</strong> — as therefore the tares are gathered and burned in fire (<em>katakaieta</em> present passive: are being burned up completely) — <em>houtōs estai en tē synteleia tou aiōnos</em> (so it will be at the end of the age): the harvest-scenario is the paradigm for the final judgment. The fire is not punitive inflammation added from outside but the natural destiny of material fit only for burning. <em>Synteleia tou aiōnos</em> is repeated from v.39, marking this as the controlling temporal reference for the entire parable\'s application.</p>',
    "41": '<p><strong>apostelei ho huios tou anthrōpou tous angelous autou</strong> — the Son of Man will send his angels (<em>apostelei</em> future: will send with a commission) — <em>kai syllexousin ek tēs basileias autou panta ta skandala kai tous poiountas tēn anomian</em> (and they will gather out of his kingdom everything that causes stumbling and those practicing lawlessness — <em>panta ta skandala</em>: all the causes-of-stumbling, the trap-springs; <em>tous poiountas tēn anomian</em>: those actively practicing lawlessness — <em>anomia</em>: the absence of law, the refusal of God\'s order; cf. 7:23 where the same phrase closes the Sermon on the Mount\'s false-prophet warning).</p>',
    "42": '<p><strong>kai balousin autous eis tēn kaminon tou pyros</strong> — and they will throw them into the furnace of fire (<em>kaminon tou pyros</em>: the furnace of fire — <em>kaminos</em> is the word for a kiln or smelting furnace, an intense enclosed fire; appearing also in Rev 1:15; 9:2) — <em>ekei estai ho klauthmos kai ho brygmos tōn odontōn</em> (there will be weeping and gnashing of teeth — <em>klauthmos</em>: loud weeping, lamentation; <em>brygmos tōn odontōn</em>: grinding/gnashing of teeth — a phrase Matthew uses six times, always in eschatological contexts): the formula describes the combination of grief (<em>klauthmos</em>) and rage/anguish (<em>brygmos</em>) in final separation.</p>',
    "43": '<p><strong>tote hoi dikaioi eklamphousin hōs ho hēlios</strong> — then the righteous will shine like the sun (<em>eklamphousin</em> future of <em>eklampō</em>: to shine out, to blaze forth — the <em>ek</em>- prefix marks emergence into full radiance; the verb is only used here in the NT) — <em>en tē basileia tou patros autōn</em> (in the kingdom of their Father): the righteous inherit the Father\'s kingdom as children, not merely subjects. <em>Ho echōn ōta akouetō</em> — the one having ears, let them hear: the ear formula closes the parable-interpretation, marking the eschatological disclosure as requiring the same active hearing as the parables themselves.</p>',
    "44": '<p><strong>homoia estin hē basileia tōn ouranōn thēsaurō kekrymmenō en tō agrō</strong> — the kingdom of the heavens is like treasure hidden in a field (<em>thēsauros</em>: treasure, a stored collection of value; <em>kekrymmenō</em> perfect passive participle: having been hidden, currently hidden) — <em>hon heurōn anthrōpos ekrypsen</em> (which a man found and hid again — he re-conceals the treasure to secure his claim before purchase): the re-hiding is not deceptive but protective. <em>Kai apo tēs charas autou hypagei kai pōlei panta hosa echei</em> — and from his joy he goes and sells all he has (<em>apo tēs charas</em>: from/out of his joy — the joy is the motivation for the total sell-off; the kingdom is recognized as worth everything by one who encounters it).</p>',
    "45": '<p><strong>palin homoia estin hē basileia tōn ouranōn emporos zētounti kalous margaritas</strong> — again the kingdom of the heavens is like a merchant seeking fine pearls (<em>emporos</em>: a traveling merchant, a wholesale trader — a person who knows the pearl market; <em>kalous margaritas</em>: fine/beautiful pearls — <em>kalos</em>, fine in quality, not just visually attractive): the merchant is an expert in pearls, not a casual buyer. His expertise is what enables him to recognize the exceptional pearl when he finds it.</p>',
    "46": '<p><strong>heurōn de hena polytimō margaritēn</strong> — having found one extremely valuable pearl (<em>polytimō</em>: of great price, highly valued — <em>poly</em> + <em>timē</em>: much-price, maximum value) — <em>apelthōn pepraken panta hosa eichen kai ēgorasen auton</em> (going away he sold all that he had and bought it): the merchant\'s expertise culminates in recognition and total investment. Unlike the hidden-treasure man who stumbled on the find, the merchant was actively seeking. Both parables end with total divestment for total acquisition: the kingdom worth everything is actually acquired by those who count it as everything.</p>',
    "47": '<p><strong>palin homoia estin hē basileia tōn ouranōn sagēnē blētheisē eis tēn thalassan</strong> — again the kingdom of the heavens is like a dragnet thrown into the sea (<em>sagēnē</em>: a large dragnet or seine net — a net weighted at the bottom and with floats at the top, dragged through the water and sweeping up everything in its path, not selective) — <em>kai ek pantos genous synagagousē</em> (and gathering fish of every kind — <em>ek pantos genous</em>: from every kind; <em>synagagousē</em> aorist participle of <em>synagō</em>: having gathered): the net is not a trap for a specific species but a total sweep. The sorting happens after the catch, not during.</p>',
    "48": '<p><strong>hēn hote eplērōthē anabibazein epi ton aigialon</strong> — when it was full they drew it up onto the shore (<em>eplērōthē</em> aorist passive: was filled, reached capacity; <em>anabibazein</em>: to drag up) — <em>kai kathisantes synelaexan ta kala eis angē</em> (and sitting down they gathered the good into containers — <em>kathisantes</em> aorist participle: having sat down, the formal working posture; <em>angeia</em>: containers, vessels): the parable parallels the weeds-and-wheat explanation. The good fish are gathered first (vessels), then the bad are cast out — the inverse order from v.30, but the same outcome of final separation. The <em>ta kala</em> (the good/beautiful) contrasts with <em>ta sapra</em> (the rotten, v.48b).</p>',
    "49": '<p><strong>houtōs estai en tē synteleia tou aiōnos</strong> — so it will be at the end of the age — the repetition of the synteleia formula (cf. v.40) frames the net-parable as the same eschatological scenario. <em>Exeleusontai hoi angeloi kai aphoriousin tous ponērous ek mesou tōn dikaiōn</em> (the angels will go out and separate the wicked from the midst of the righteous — <em>aphoriousin</em> future of <em>aphorizō</em>: to mark off by boundaries, to separate distinctly): the angels separate the wicked <em>from the midst of</em> the righteous — the mixture is inside the good, as in the field.</p>',
    "50": '<p><strong>kai balousin autous eis tēn kaminon tou pyros</strong> — and they will throw them into the furnace of fire — the formula repeats v.42 verbatim: <em>ekei estai ho klauthmos kai ho brygmos tōn odontōn</em> (there will be weeping and gnashing of teeth). The repetition of the eschatological formula in both parable-interpretations (weeds and net) emphasizes the unity of the teaching: the same final separation is described from two angles (the field/humanity as a whole; the sea/the full scope of the mission\'s catch).</p>',
    "51": '<p><strong>synēkate tauta panta</strong> — have you understood all these things? (<em>synēkate</em> aorist of <em>syniēmi</em>: the understanding-verb used throughout ch13, v.13,14,15,19,23; to bring together, comprehend) — <em>legousin autō nai</em> (they say to him: yes): the disciples\' affirmative answer to Jesus\'s direct question sets up the final parable of v.52. Their understanding (however partial) qualifies them as the "scribes instructed in the kingdom of the heavens" described next. The question and answer mark the transition from parable-hearing to parable-understanding.</p>',
    "53": '<p><strong>kai egeneto hote etelesen ho Iēsous tas parabolēs tautas</strong> — and it happened when Jesus had finished these parables (<em>etelesen</em> aorist of <em>teleō</em>: to complete — the discourse-closing formula, cf. 7:28; 11:1) — <em>metēren ekeithen</em> (he departed from there): the geographical transition marks the end of the parabolic discourse and the beginning of the hometown rejection pericope. The parables that revealed the kingdom to disciples and concealed it from the unperceptive now face a concrete test: the response of Jesus\'s own hometown.</p>',
    "54": '<p><strong>kai elthōn eis tēn patrida autou edidasken autous en tē synagōgē autōn</strong> — coming to his hometown he was teaching them in their synagogue (<em>patrida</em>: homeland, native country — hometown; <em>autōn</em>: their synagogue, the possessive marking the same institutional distance as 12:9) — <em>hōste ekplēssesthai autous</em> (so that they were astonished — <em>ekplēssesthai</em> imperfect passive: were being knocked out, struck with astonishment — the strongest word for amazement): the reaction is not neutral wonder but surprised displacement. <em>Pothen toutō hē sophia autē kai hai dynameis</em> (from where does this man get this wisdom and these powers? — <em>pothen</em>: whence, the question of source that reveals they have no framework for the answer).</p>',
    "55": '<p><strong>ouch houtos estin ho tou tektonos huios</strong> — isn\'t this the son of the craftsman? (<em>tektōn</em>: craftsman, worker in materials — the word covers carpenter, builder, stonemason, woodworker; it is not narrowly "carpenter" in the modern sense but a skilled craftsperson in the construction trades; Mark 6:3 applies the same term directly to Jesus) — <em>Mariam</em>: Mary is named directly; <em>Iakōbos, Iōsēph, Simōn, Ioudas</em>: the four brothers named. The family\'s ordinariness is the problem: the crowd\'s knowledge of Jesus\'s earthly origins prevents them from receiving his heavenly origin.</p>',
    "56": '<p><strong>kai hai adelphai autou ouchai pasai pros hēmas eisin</strong> — aren\'t all his sisters here with us (<em>hai adelphai</em>: the sisters are mentioned but unnamed; their number is implied by <em>pasai</em>, all — suggesting at least two, probably more) — <em>pothen oun toutō tauta panta</em> (where then does this man get all these things? — the repeated <em>pothen</em> question frames the hometown rejection as a failure to reconcile Jesus\'s known origins with his unprecedented claims and deeds): the neighbors\' intimate knowledge of his family becomes a barrier rather than a credential.</p>',
    "57": '<p><strong>kai eskandalizonto en autō</strong> — and they were being caused to stumble by him (<em>eskandalizonto</em> imperfect passive: were being continually tripped up — the passive marks the cause as Jesus himself; <em>skandalizō</em>: to set a trap, to cause to stumble, the same word used for the path-hearer in 13:21 and for the stumbling-block of 11:6) — <em>ho de Iēsous eipen autois</em>: Jesus\'s response cites a proverb: <em>ouk estin prophētēs atimos ei mē en tē patridi kai en tē oikia autou</em> (a prophet is not dishonored except in his hometown and in his own house — <em>atimos</em>: without honor, dishonored): the proverb is attested in varied forms in ancient literature but receives its most pointed application here.</p>',
    "58": '<p><strong>kai ouk epoiēsen ekei dynameis pollas dia tēn apistian autōn</strong> — and he did not do many miracles there because of their unbelief (<em>apistia</em>: unbelief, lack of faith — <em>a</em>- privative + <em>pistis</em>: the absence of the faith that is the receptor for miraculous healing; cf. 9:29: "according to your faith let it be done") — Matthew says <em>pollas</em> (many) rather than Mark\'s "none"; some healing occurred but the scale was drastically limited. The verse is not a theological claim that Jesus lacked power but that the reception of miracle requires the soil of faith; in its absence, miracles remain largely unsown.</p>'
  },
  "14": {
    "1": '<p><strong>en ekeinō tō kairō ēkousen Hērōdēs ho tetrarchēs tēn akoēn Iēsou</strong> — at that time Herod the tetrarch heard the report about Jesus (<em>tetrarchēs</em>: ruler of a quarter — Herod Antipas held the tetrarchy of Galilee and Perea under Roman appointment after his father Herod the Great\'s death; the title is less than "king" — v.9 uses "king" loosely as a courtesy title) — <em>tēn akoēn Iēsou</em> (the report/hearing about Jesus — <em>akoē</em>: what is heard, the public report): Herod\'s hearing connects back to the disciples being sent out in ch10 and the spreading fame since ch9.</p>',
    "2": '<p><strong>kai eipen tois paisin autou</strong> — and he said to his servants/attendants — <em>houtos estin Iōannēs ho baptistēs</em> (this is John the Baptist): Herod\'s identification is diagnostic of a guilty conscience — he sees the miraculous deeds of Jesus and interprets them through the lens of his act against John. <em>Autos ēgerthē apo tōn nekrōn</em> (he has risen from the dead — <em>ēgerthē</em> aorist passive of <em>egeirō</em>: the resurrection verb; Herod uses the standard resurrection vocabulary to describe his fear): <em>kai dia touto hai dynameis energousin en autō</em> (and therefore miraculous powers are at work in him — <em>energousin</em>: are working, are active — the word from which "energy" derives).</p>',
    "3": '<p><strong>ho gar Hērōdēs kratēsas ton Iōannēn edēsen</strong> — for Herod had seized John and bound him (<em>kratēsas</em> aorist participle of <em>krateō</em>: to seize, take hold of forcefully; <em>edēsen</em> aorist of <em>deō</em>: to bind — the binding vocabulary of 12:29 now applied literally to John) — <em>kai en phylakē apetheto dia Hērōdiada tēn gynaika Philippou tou adelphou autou</em> (and placed him in prison because of Herodias, the wife of his brother Philip): Herodias had left Philip to marry Antipas; John\'s denunciation of this as unlawful (v.4) was politically and dynastically dangerous.</p>',
    "4": '<p><strong>elegen gar ho Iōannēs autō</strong> — for John had been saying to him (<em>elegen</em> imperfect: was repeatedly saying, habitually denouncing — not a single accusation but a sustained prophetic rebuke) — <em>ouk exestin soi echein autēn</em> (it is not lawful for you to have her — <em>ouk exestin</em>: the same lawfulness-formula as the Sabbath controversies of ch12): John applies the same Torah-appeal to a political marriage that Jesus applies to Sabbath healing. The Levitical prohibitions (Lev 18:16; 20:21) forbade a man from marrying his brother\'s wife while the brother lived.</p>',
    "5": '<p><strong>kai thelōn auton apokteinai ephobēthē ton ochlon</strong> — wanting to kill him he was afraid of the crowd (<em>thelōn</em> present participle: continuously wanting/desiring to kill him; <em>ephobēthē</em> aorist passive: was made afraid): Herod\'s murderous desire is restrained not by scruple but by political calculation. <em>Hoti hōs prophētēn auton eichon</em> (because they held him as a prophet — <em>eichon</em> imperfect: were holding, in their considered estimation): the crowd\'s recognition of John as a prophet is the same recognition that produces Herod\'s restraint — and that produces the crowd\'s recognition in 21:26.</p>',
    "6": '<p><strong>genesiois de genomenos tou Hērōdou</strong> — on the birthday celebration of Herod (<em>genesia</em>: birthday celebration — the word can refer to the birthday itself or the festivities; birthday celebrations for rulers were known in the Hellenistic world) — <em>ōrchēsato hē thygatēr tēs Hērōdiados en tō mesō</em> (the daughter of Herodias danced in the midst — <em>ōrchēsato</em> aorist of <em>orcheomai</em>: to dance; dancing as entertainment for male guests was associated with lower social status; a princess dancing publicly would have been unusual and attention-seizing) — <em>kai ēresen tō Hērōdē</em> (and pleased Herod — <em>areskō</em>): the dancing produces the rash oath.</p>',
    "7": '<p><strong>hothen met horkous hōmologēsen autē dounai ho ean aitēsētai</strong> — whereupon he promised with an oath to give her whatever she might ask (<em>met horkous</em>: with oaths — plural, sworn solemnly; <em>hōmologēsen</em> aorist of <em>homologeō</em>: to publicly declare, promise, confess — the oath-making is a formal public commitment, not a private aside): the oath binds Herod before witnesses. <em>Ho ean aitēsētai</em> (whatever she might ask — <em>aitēsētai</em> aorist subjunctive: a fully open promise): the terms are blanket and unconditional, which the next verse exploits.</p>',
    "8": '<p><strong>hē de probibastheisa hypo tēs mētros autēs</strong> — but she, prompted/led forward by her mother (<em>probibastheisa</em> aorist passive participle of <em>probibazō</em>: to cause to step forward, to incite, to put up to something — the mother is the agent behind the request) — <em>dos moi phēsin hōde epi pinaki tēn kephalēn Iōannou tou baptistou</em> (she says: give me here on a dish the head of John the Baptist — <em>hōde</em>: here, immediately; <em>epi pinaki</em>: on a platter, on a serving dish): the gruesome specificity of the request — a severed head delivered on serving-ware at a banquet — is designed to make refusal maximally embarrassing before the guests.</p>',
    "9": '<p><strong>kai lypētheis ho basileus</strong> — and being grieved, the king (<em>lypētheis</em> aorist passive participle of <em>lypeō</em>: being grieved, distressed — Herod is not indifferent; his distress is real) — <em>dia tous horkous kai tous synanakeimenous</em> (because of the oaths and those reclining with him — the dinner guests): the two competing pressures are the public oath (which would dishonor him if broken) and the opinion of the guests (before whom he must appear strong). Herod is trapped by his own rash promise and his need to maintain honor. <em>Ekeleusen dothēnai</em> (he commanded it to be given).</p>',
    "10": '<p><strong>kai pempsas apekephalisen Iōannēn en tē phylakē</strong> — and sending he had John beheaded in the prison (<em>apekephalisen</em> aorist of <em>apokephalzō</em>: to behead — a compound verb; <em>apo</em>: away from + <em>kephalē</em>: head): the execution is narrated with clinical brevity. Matthew provides no scene-setting; the bare fact of John\'s death stands as a marker of the opposition that Jesus will face. John\'s fate anticipates Jesus\'s: both die by the political authority\'s hand under pressure from religious/domestic opponents.</p>',
    "11": '<p><strong>kai ēnechthē hē kephalē autou epi pinaki kai edothē tō korasio</strong> — and his head was brought on a platter and given to the girl (<em>ēnechthē</em> aorist passive: was brought/carried; the passive voice removes the bearers from sight, focusing on the object): the head\'s journey from prison to platter to girl to mother is told in four passive or impersonal verbs. <em>Kai ēnenken tē mētri autēs</em> (and she brought it to her mother): the chain of agency runs backward — Herod → executioner → girl → mother; the mother who initiated the sequence receives the result.</p>',
    "12": '<p><strong>kai proselthontes hoi mathētai autou ēran to ptōma kai ethapsan auton</strong> — and his disciples coming took the body and buried it (<em>ptōma</em>: corpse, fallen body — the word for a fallen/dead body, from <em>piptō</em>: to fall) — <em>kai elthontes apēngilan tō Iēsou</em> (and coming they reported to Jesus): John\'s disciples perform the final act of loyalty — burial — and then bring the news to Jesus. The report to Jesus closes the John narrative and opens the withdrawal/feeding pericope: Jesus receives the news of John\'s death and withdraws (v.13).</p>',
    "13": '<p><strong>akousas de ho Iēsous anechōrēsen ekeithen en ploiō eis erēmon topon</strong> — hearing this, Jesus withdrew in a boat to a deserted place (<em>akousas</em> aorist participle: having heard; <em>anechōrēsen</em>: withdrew — the same deliberate withdrawal verb as 12:15; <em>erēmon topon</em>: a deserted/solitary place — <em>erēmos</em>: without inhabitants, wild) — <em>kat idian</em> (privately, by himself): Jesus\'s withdrawal in response to John\'s death is more than grief; it is a strategic recognition that the political danger has escalated. <em>Kai akousantes hoi ochloi ēkolouthēsan autō pezē apo tōn poleōn</em> (the crowds, hearing, followed him on foot from the cities): the withdrawal is followed, not achieved.</p>',
    "14": '<p><strong>kai exelthōn eiden polun ochlon</strong> — and going out he saw a large crowd — <em>kai esplanchnisthē ep autois</em> (and he had compassion on them — <em>esplanchnisthē</em> aorist passive of <em>splagchnizomai</em>: the strongest compassion-verb, from <em>splanchnon</em>/intestines; cf. 9:36): the compassion overrides the private grief that motivated the withdrawal. <em>Kai etherapeuse tous arrōstous autōn</em> (and he healed their sick ones — <em>arrōstous</em>: literally without strength, weakened, sick): the compassion-response is healing, not merely sympathy. The scene recalls 9:36 where compassion led to the harvest-prayer; here it produces direct ministry.</p>',
    "15": '<p><strong>opsias de genomenes prosēlthon autō hoi mathētai legontes</strong> — evening coming on, the disciples came to him saying — <em>erēmos estin ho topos kai hē hōra ēdē parēlthen</em> (the place is deserted and the hour has already passed — <em>parēlthen</em> aorist: has gone by, is past; the meal-time has elapsed): the disciples\' assessment is logistically accurate. <em>Apoluson tous ochlous hina apelthontes eis tas kōmas agorasōsin heautois brōmata</em> (send the crowds away so that going to the villages they might buy food for themselves): the disciples\' solution is dispersal; they have no framework yet for what Jesus is about to do.</p>',
    "16": '<p><strong>ho de Iēsous eipen autois ou chreian echousin apelthein</strong> — but Jesus said to them: they do not need to go away — <em>dote autois hymeis phagein</em> (you give them something to eat — <em>hymeis</em>: emphatic, YOU give them — the pronoun is the challenge): Jesus redirects responsibility back to the disciples. The command is absurd by any calculation of their resources (v.17: five loaves and two fish); its point is to expose the disciples\' inadequacy and transfer the solution to Jesus. The feeding that follows is not a demonstration of Jesus\'s power independent of the disciples but happens through them: he gives to them, they give to the crowd.</p>',
    "17": '<p><strong>hoi de legousin autō ouk echomen hōde ei mē pente artous kai duo ichthyas</strong> — they say to him: we have here only five loaves and two fish — the <em>ei mē</em> (except/only) clause marks the minimum: five loaves, two fish is subsistence for a handful of people, not thousands. The specification of the supplies before the miracle is a standard feature of miracle accounts that establishes the baseline against which the abundance will be measured. <em>Hōde</em> (here, at this location) further limits even this small supply to what is immediately at hand.</p>',
    "18": '<p><strong>ho de eipen pherete moi hōde autous</strong> — he said: bring them here to me — the command <em>pherete moi</em> (bring to me) is the pivot: the disciples\' inadequate resources become the material for Jesus\'s action when placed in his hands. The transfer of the loaves to Jesus precedes the multiplication; the miracle happens not by Jesus creating food independently but by transforming what is given to him. The pattern anticipates the disciples\' role in distribution: they give to him; he multiplies; they distribute.</p>',
    "19": '<p><strong>kai keleusas tous ochlous anapesein epi tou chortou</strong> — and commanding the crowds to recline on the grass (<em>anapesein</em>: to recline, the posture of reclining for a meal) — <em>labōn tous pente artous kai tous duo ichthyas anablepas eis ton ouranon eulogēsen</em> (taking the five loaves and the two fish, looking up to heaven, he blessed — <em>anablepas eis ton ouranon</em>: looking up to heaven, the prayer posture; <em>eulogēsen</em> aorist of <em>eulogeō</em>: to bless, to speak blessing over — the Jewish <em>berakah</em> form: "Blessed are you, Lord our God, king of the universe, who brings forth bread from the earth"): <em>kai klesas edōken tois mathētais tous artous</em> (and breaking he gave the loaves to the disciples — <em>klesas</em>: having broken; the eucharistic language anticipates 26:26).</p>',
    "20": '<p><strong>kai ephagon pantes kai echortasthēsan</strong> — and they all ate and were satisfied (<em>echortasthēsan</em> aorist passive of <em>chortazō</em>: to be filled, to be satisfied — the word used in the fifth Beatitude, 5:6, for those "hungry and thirsting" for righteousness who will be filled; the same root as the animal-feeding satisfaction the Lord provides in Ps 147:9) — <em>kai ēran to perisseuon tōn klasmatōn dōdeka kophinous plēreis</em> (and they gathered the surplus of the fragments, twelve baskets full — <em>kophinos</em>: a wicker basket, specifically a Jewish type of basket; twelve baskets correspond to the twelve disciples, or symbolically to the twelve tribes).</p>',
    "21": '<p><strong>hoi de esthiontes ēsan andres hōsei pentakischilioi</strong> — those eating were about five thousand men (<em>andres</em>: men, adult males — specifically counted; <em>hōsei</em>: approximately) — <em>chōris gynaikōn kai paidiōn</em> (besides women and children): Matthew adds this qualifier, absent from Mark; the total crowd is therefore substantially more than five thousand. The counting of men (<em>andres</em>) follows the military census custom; the surplus population (women and children) are additional. This specification increases the miraculous scale beyond what any simple estimate would yield.</p>',
    "22": '<p><strong>kai eutheōs ēnankasen tous mathētas embēnai eis to ploion</strong> — and immediately he compelled the disciples to get into the boat (<em>ēnankasen</em> aorist of <em>enankazō</em>: to compel, force — a strong word: not a suggestion or invitation but a compelling, as if the disciples needed to be moved with force) — <em>kai proagein auton eis to peran</em> (to go on ahead of him to the other side): the disciples\' departure before the dismissal of the crowds is forced by Jesus — perhaps because they would have wanted to stay with him. <em>Heōs hou apolysei tous ochlous</em> (while he dismissed the crowds — <em>apolysei</em> future: will dismiss; he completes the crowd-dismissal alone).</p>',
    "23": '<p><strong>kai apolusas tous ochlous anebē eis to oros kat idian proseuxasthai</strong> — dismissing the crowds he went up on the mountain privately to pray (<em>anebē eis to oros</em>: went up on/into the mountain — the mountain in Matthew is frequently a locus of revelation and prayer: 5:1; 17:1; 28:16; <em>kat idian</em>: privately, by himself; <em>proseuxasthai</em> aorist infinitive of <em>proseuchomai</em>: to pray) — <em>opsias de genomenes monos ēn ekei</em> (evening coming, he was there alone): the evening is the second evening of v.15 (first evening = meal-time; second evening = nightfall). Jesus is alone on the mountain in prayer while the disciples battle the sea.</p>',
    "24": '<p><strong>to de ploion ēdē stadious pollous apo tēs gēs apeichen</strong> — the boat was already many stades from land (<em>stadious</em>: a stade = ~185 meters; "many stades" = a significant distance from shore) — <em>basanizomenon hypo tōn kymatōn</em> (being tormented by the waves — <em>basanizomenon</em> present passive participle of <em>basanizō</em>: to torment, put to torture, originally of testing metals with a touchstone; used for the extreme distress of being battered by waves) — <em>ēn gar enantios ho anemos</em> (for the wind was contrary — <em>enantios</em>: against, opposing, adverse): the boat makes no progress against an opposing wind while Jesus is alone on the mountain and the disciples are alone on the sea.</p>',
    "25": '<p><strong>tetartē de phylakē tēs nyktos ēlthen pros autous peripatōn epi tēn thalassan</strong> — in the fourth watch of the night he came to them walking on the sea (<em>tetartē phylakē</em>: the fourth watch — by Roman military reckoning, 3-6 AM; the darkest, most exhausted hour of the night) — <em>peripatōn epi tēn thalassan</em> (walking on the sea — <em>peripatōn</em> present active participle: actively walking, in motion): the divine act of walking on water echoes Job 9:8 LXX (God "walks on the sea as on firm ground") and Ps 77:19 (God\'s way through the sea). The OT background makes the action a theophanic sign.</p>',
    "26": '<p><strong>hoi de mathētai idontes auton epi tēs thalassēs peripatounta etarachthēsan</strong> — the disciples seeing him walking on the sea were troubled (<em>etarachthēsan</em> aorist passive of <em>tarassō</em>: to be shaken, disturbed, troubled — the strongest word for inner agitation) — <em>legontes hoti phantasma estin kai apo tou phobou ekraxan</em> (saying it is a ghost, and from fear they cried out — <em>phantasma</em>: a phantom, apparition — the disciples\' terror interprets Jesus\'s approach as a ghost): the cry from fear (<em>apo tou phobou</em>) precedes Jesus\'s word of reassurance. Fear is the disciples\' first response to theophanic presence before recognition.</p>',
    "28": '<p><strong>apokritheis de autō ho Petros eipen kyrie ei sy ei</strong> — Peter answering him said: Lord, if it is you (<em>ei sy ei</em>: if you are the one — the conditional is not doubt but verification; Peter wants confirmation before the request) — <em>keleuson me elthein pros se epi ta hydata</em> (command me to come to you on the waters — <em>keleuson</em> aorist imperative: command; <em>pros se</em>: toward you, not just "across the water" but specifically to Jesus): Peter\'s request is not a demonstration of faith-testing but an act of faith in Jesus\'s capacity to enable walking. The request positions the miracle as coming from Jesus\'s command, not Peter\'s initiative.</p>',
    "29": '<p><strong>ho de eipen elthet kai katabalōn apo tou ploiou ho Petros periepatēsen epi ta hydata</strong> — he said: come; and getting down from the boat Peter walked on the water (<em>elthe</em> aorist imperative: come; <em>katabalōn</em> aorist participle of <em>katabainō</em>: having stepped down; <em>periepatēsen</em> aorist: walked) — <em>kai ēlthen pros ton Iēsoun</em> (and came toward Jesus): the single verb <em>periepatēsen</em> is the action; the coming-toward-Jesus is the goal. Peter\'s walking on the water is real and brief — the miracle happens and is then interrupted by a change of focus.</p>',
    "30": '<p><strong>blepōn de ton anemon edeiiliasen</strong> — but seeing the wind he was afraid (<em>blepōn</em> present participle: seeing — the problem is the ongoing looking at the wind, not a glance; <em>edeiliaseen</em> aorist of <em>deiliaō</em>: to be cowardly, to be afraid) — <em>kai arxamenos katapontizesthai</em> (and beginning to sink — <em>katapontizesthai</em>: to go down under water, to be engulfed by the sea — a compound of <em>kata</em>: down and <em>pontos</em>: the deep sea): <em>ekraxen legōn kyrie sōson me</em> (he cried out saying: Lord, save me! — <em>sōson</em> aorist imperative of <em>sōzō</em>: the salvation word used for healing; Peter\'s cry invokes both physical rescue and the full weight of <em>sōzō</em>).</p>',
    "31": '<p><strong>eutheōs de ho Iēsous ekteinas tēn cheira epelabeto autou</strong> — immediately Jesus stretching out his hand took hold of him (<em>eutheōs</em>: immediately — the same immediacy-word that marked shallow enthusiasm in 13:5,20; here it marks divine rescue speed; <em>ekteinas tēn cheira</em>: stretching out his hand — the reaching-gesture used in 8:3 for healing the leper and 12:49 for identifying the disciples as family) — <em>oligopiste</em> (you of little faith — <em>oligopiste</em>: a compound coined by Matthew, appearing in 6:30; 8:26; 16:8; 17:20: <em>oligos</em> small/little + <em>pistis</em> faith). <em>Eis ti edistasas</em> (why did you waver/doubt — <em>distasas</em> aorist of <em>distazō</em>: to be divided, to stand in two directions, to waver).</p>',
    "32": '<p><strong>kai anabantōn autōn eis to ploion ekopasen ho anemos</strong> — and when they got into the boat the wind ceased (<em>anabantōn autōn</em> genitive absolute: they having gone up into the boat; <em>ekopasen</em> aorist of <em>kopazō</em>: to grow weary, to cease, to abate): the same sequence as the storm-calming of 8:26 where the rebuke of the wind produced a great calm. Here the wind stops at the moment of boarding without an explicit rebuke. The cessation is simultaneous with, but not structurally caused by, the boarding — the storm\'s end marks the completion of the theophanic episode.</p>',
    "33": '<p><strong>hoi de en tō ploiō prosekynēsan autō legontes</strong> — those in the boat worshipped him saying (<em>prosekynēsan</em> aorist of <em>proskyneō</em>: to worship, to bow in reverence — the same word used in 2:2,11 for the Magi\'s worship and in 28:9,17 for post-resurrection worship; distinguished from the "marveling" of the crowd in 8:27 after the storm) — <em>alēthōs theou huios ei</em> (truly you are the Son of God — <em>alēthōs</em>: truly, genuinely — an emphatic adverb of affirmation; <em>theou huios</em>: Son of God with the genitive): this is the first corporate confession of Jesus as Son of God in Matthew; it answers the demons\' correct identification (8:29) with genuine worship.</p>',
    "34": '<p><strong>kai diaperasantes ēlthon epi tēn gēn Gennēsaret</strong> — crossing over they came to the land of Gennesaret (<em>diaperasantes</em> aorist participle of <em>diaperaō</em>: having crossed over, completed the sea-crossing) — Gennesaret is the fertile plain on the northwest shore of the Sea of Galilee, south of Capernaum. The geographical specificity grounds the ensuing healing summary (vv.35-36) in a specific locale, where Jesus\'s reputation is sufficient for the population to mobilize before he has even disembarked.</p>',
    "35": '<p><strong>kai epignontes auton hoi andres tou topou ekeinou apesteilan eis holēn tēn perikhōron ekeinēn</strong> — recognizing him, the men of that place sent into all the surrounding region (<em>epignontes</em> aorist participle of <em>epiginōskō</em>: having recognized — the intensive recognition-verb) — <em>kai prosēnegkan autō pantas tous kakōs echontas</em> (and they brought to him all those who were ill — <em>pantas</em>: all; <em>kakōs echontas</em>: those having it badly, those ill): the regional mobilization to bring the sick to Jesus is the practical outworking of the recognition. Faith in his healing capacity is demonstrated by logistical effort before any word is spoken.</p>',
    "36": '<p><strong>kai parekaloun auton hina monon apsōntai tou kraspedou tou himatiou autou</strong> — and they were beseeching him to let them just touch the fringe of his garment (<em>parekaloun</em> imperfect: were continuously beseeching; <em>apsōntai</em> aorist subjunctive: to touch once; <em>kraspedon</em>: the fringe/tassel of the garment, the tassels required by Num 15:38-39 — the same word as in 9:20 for the hemorrhaging woman) — <em>kai hosoi ēpsanto diesōthēsan</em> (and as many as touched were completely saved/healed — <em>diesōthēsan</em> aorist passive of <em>diasōzō</em>: to save/heal completely, the compound intensifying the totality): the report is collective; individuals are healed as the crowds make contact with the fringe.</p>'
  }
}

def main():
    existing = load_comm('mkt-original', 'matthew')
    merge_comm(existing, MATTHEW)
    save_comm('mkt-original', 'matthew', existing)
    print('Matthew 13-14 mkt-original written.')

if __name__ == '__main__':
    main()
