"""
MKT Original Commentary — Psalms 48–54 (98 verses)
Run: python3 scripts/zc-original-psalms-48-54.py

Key decisions:
- Ps 48: yarkĕtê ṣāphôn (heights of the north, v2) identified as the Canaanite
  divine mountain (Baal's Zaphon/Baal-Zaphon) that YHWH's Zion displaces;
  ʿal-mût (v14) treated as ambiguous: "forever" or "beyond death"
- Ps 49: māshāl + ḥîdāh pair (proverb + riddle, v4) as wisdom-genre markers;
  phādāh (ransom, v7-8) as the impossibility underlying the psalm; yiqqāḥēnî
  (he will take me, v15) treated as deliberate echo of Enoch/Elijah takings
- Ps 50: Asaphite covenant lawsuit (rîb) genre; ʾēl-ʾĕlōhîm-YHWH triple name (v1)
  as solemn judicial formula; tôdāh (thanksgiving, v14) as the true sacrifice;
  hayyît heyôteh ʾehyeh kāmôkhā (you thought I was like you, v21) as theological
  diagnosis of practical idolatry
- Ps 51: bārāʾ (create, v10) as the Genesis-1 creation word — only God creates,
  not human moral renovation; kābaś (scrub/knead-wash, v2) more intensive than
  rāḥaṣ (bathe); rûaḥ qodshĕkhā (Holy Spirit, v11) as removable gift; v4 cited
  in Rom 3:4
- Ps 52: gibbôr (hero/mighty man) applied ironically to the wicked boaster (v1);
  olive-tree contrast (v8) to the uprooted wicked
- Ps 53: Elohistic variant of Ps 14; nābāl (fool = practical/moral not
  intellectual atheism, v1); difference at v5 signals a specific historical event
- Ps 54: zārîm (strangers/outsiders, v3) — Ziphites treated as "foreigners" by
  their betrayal; nĕdābāh (freewill offering, v6) as the highest voluntary gift
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

NEW = {
  "48": {
    "1": "<p><b>shîr mizmôr libnê-qōraḥ</b> — <i>a Song, a Psalm of the sons of Korah</i>. The double title (<i>shîr</i>: song for singing + <i>mizmôr</i>: psalm for instrumental accompaniment) is unusual — both vocal and instrumental performance indicated. <b>gādôl YHWH ûmĕhullāl mĕʾōd</b> — <i>great is the LORD and greatly to be praised</i>. <i>Gādôl</i> (great) + <i>mĕhullāl</i> (passive participle of hālal: the one who is greatly praised). The incomparability formula applied to Zion-worship. <b>bĕʿîr ʾĕlōhênû har qodshô</b> — <i>in the city of our God, on his holy mountain</i>. The praise is not abstract — it is geographically located: in the city, on the mountain.</p>",
    "2": "<p><b>yĕphēh nôph śĕmōaḥ kol-hāʾāreṣ</b> — <i>Mount Zion, beautiful in its height, the joy of all the earth</i>. <i>Nôph</i> (elevation, height — the aesthetic quality of the mount's height, not merely its altitude). <i>Śĕmōaḥ kol-hāʾāreṣ</i> (joy of all the earth — the source of joy radiating to the whole world). <b>har-ṣiyyôn yarkĕtê ṣāphôn</b> — <i>Mount Zion, on the heights of the north</i>. <i>Yarkĕtê ṣāphôn</i> (far recesses/heights of the north) is the most theologically loaded phrase: <i>ṣāphôn</i> is also the name of Mount Zaphon (Jebel el-Aqra, north of Ugarit) — the mountain where Baal held his court in Canaanite mythology. The psalm maps YHWH's Zion onto the cosmic mountain of the gods, displacing Baal: what was true of the pagan divine mountain is now true, and more truly true, of Zion. <b>qiryat melek rāb</b> — <i>the city of the great King</i>. <i>Melek rāb</i> (great King — the title for the supreme sovereign over other kings; cf. Ps 47:2; Matt 5:35).</p>",
    "3": "<p><b>ʾĕlōhîm bĕʾarmmĕnôteyhā nôdāʿ lĕmiśgāb</b> — <i>God has shown himself to be a fortress within her citadels</i>. <i>ʾArmmĕnôt</i> (citadels, palace-towers — the most heavily fortified buildings of an ancient city). <i>Nôdāʿ lĕmiśgāb</i> (niphal: he has made himself known as a fortress) — the divine self-disclosure as protective strength occurring within the city's own strongholds. The defensive architecture of Zion testifies to the divine presence that makes it impregnable.</p>",
    "4": "<p><b>kî-hinnēh hammĕlākhîm nôʿădû</b> — <i>for look — the kings assembled</i>. <i>Nôʿad</i> (niphal of yāʿad: to meet by appointment, to assemble — a deliberate, planned coalition). The kings who appear to be Zion's existential threat. <b>ʿābĕrû yaḥdāw</b> — <i>they came against her together</i>. The united advance — maximum military threat. The next verse (v5) reveals that their united power dissolves on sight of Zion.</p>",
    "5": "<p><b>hēmmāh rāʾû kēn tāmāhû</b> — <i>they saw it and were bewildered</i>. <i>Tāmah</i> (to be astonished, confounded — the stunned reaction when one sees something that defeats all expectation). <b>nibhălû nibbĕhālû</b> — <i>they were struck with terror and fled</i>. The intensified niphal (<i>nibhălû</i>) emphasizes the sudden panic. The alliteration in the Hebrew (<i>nibhălû nibbĕhālû</i>: they were terrified / they fled in terror) mimics the frantic flight. The military coalition collapses at the sight of the city — without the need for any described battle.</p>",
    "6": "<p><b>rĕʿādāh ʾăḥāzātam shām</b> — <i>trembling took hold of them there</i>. <i>Rĕʿādāh</i> (trembling, shaking — the involuntary physical response to terror). <i>Shām</i> (there — in that very place where they came to conquer). <b>ḥîl kĕyôledāh</b> — <i>pain like that of a woman giving birth</i>. <i>Ḥîl</i> (writhing, labor-pain — the intense, overwhelming physical pain of childbirth; a standard OT image for the paralysis that overcomes the apparently powerful in the moment of divine judgment, cf. Isa 13:8; Jer 4:31; Mic 4:10). The warriors' trembling reduces them to the helplessness of a woman in labor — the height of military irony.</p>",
    "7": "<p><b>bĕrûaḥ qādîm tĕshabbēr ʾoniyyôt tarshîsh</b> — <i>with the east wind you shatter the ships of Tarshish</i>. <i>Rûaḥ qādîm</i> (the east wind — the dry, powerful sirocco that blows in from the desert; used of the divine weapon in Exod 14:21, Ps 78:26, Ezek 27:26). <i>Tarshîsh</i> (Tarshish — possibly Tartessus in Spain or another distant trading port; the ships of Tarshish are the grandest ocean-going vessels of antiquity, symbol of commercial wealth and power). YHWH's east wind shatters even the greatest human vessels — the same power that routes armies (vv4-6) also commands the sea.</p>",
    "8": "<p><b>kaʾăsher shāmaʿnû kēn rāʾînû</b> — <i>as we have heard, so we have seen</i>. The conjunction of heard tradition and personal experience — the community's historical memory (<i>shāmaʿnû</i>: we have heard, the passed-down testimony) confirmed in their own sight (<i>rāʾînû</i>: we have seen). <b>bĕʿîr-YHWH ṣĕbāʾôt bĕʿîr ʾĕlōhênû</b> — <i>in the city of the LORD of hosts, in the city of our God</i>. The double identification of the city (Lord of hosts, Our God) emphasizes its divine ownership. <b>ʾĕlōhîm yĕkhônĕnehā ʿad-ʿôlām selāh</b> — <i>God establishes it forever</i>. <i>Kôn</i> (piel: to establish firmly, make permanent) + <i>ʿad-ʿôlām</i> (forever) — the permanence of Zion as the divine guarantee against all the kings who assembled.</p>",
    "9": "<p><b>dimmînû ḥasdekā ʾĕlōhîm bĕqereb hêkhālekhā</b> — <i>we have meditated on your steadfast love, O God, within your temple</i>. <i>Dimmāh</i> (piel: to picture, meditate on, liken — the root is related to dāmāh: likeness, image). In the temple the community meditates — pictures, ponders, contemplates — the divine ḥesed. The temple as the space for theological reflection on God's covenant love, not merely for ritual performance.</p>",
    "10": "<p><b>kĕshimĕkhā ʾĕlōhîm kēn tĕhillātekhā</b> — <i>as your name reaches, O God, so does your praise</i>. The proportionality of name and praise: wherever the divine name reaches, there praise follows — the geographical spread of YHWH's reputation is matched by the geographical spread of worship. <b>ʿal-qaṣwê-ʾāreṣ</b> — <i>to the ends of the earth</i>. The universal scope: from Zion (v1) to the ends of the earth (v10) — the psalm moves outward. <b>ṣedeq māleʾāh yĕmînekhā</b> — <i>your right hand is full of righteousness</i>. The divine right hand (<i>yāmîn</i>) — the hand of action and power — full of <i>ṣedeq</i> (righteousness, justice). What the hand is full of is what it distributes.</p>",
    "11": "<p><b>yiśmaḥ har-ṣiyyôn tāgēlanāh bĕnôt yĕhûdāh</b> — <i>let Mount Zion rejoice; let the towns of Judah be glad</i>. The call to rejoicing: the mountain itself (<i>har-ṣiyyôn</i>) and the daughter-villages of Judah (<i>bĕnôt yĕhûdāh</i>: daughters of Judah = the surrounding towns). <b>lĕmaʿan mishpāṭêkhā</b> — <i>because of your righteous judgments</i>. <i>Mishpāṭ</i> (judgment/decision — the righteous verdicts) as the reason for joy: the divine justice displayed in the defeat of the kings is cause for communal celebration.</p>",
    "12": "<p><b>sōbbû ṣiyyôn wĕhaqîphûhā</b> — <i>walk all around Zion, circle her</i>. The liturgical procession around the city — a pilgrimage act of inspection and praise. <b>siprû migdālêyhā</b> — <i>count her towers</i>. <i>Māgdāl</i> (tower — the watchtowers and defensive towers of the city wall). The counting is not military inventory but liturgical attention — seeing the city's defenses as testimony to divine protection.</p>",
    "13": "<p><b>shîtû libbĕkhem lĕḥêlāh</b> — <i>mark her walls carefully</i>. <i>Shît lēb</i> (to set the heart toward — to give careful attention to; the idiom for deliberate, attentive regard). <i>Ḥêl</i> (rampart, fortification wall — the outer defensive earthwork). <b>passĕgû ʾarmmĕnôteyhā</b> — <i>tour her citadels</i>. <i>Pāsag</i> (to survey, look over carefully — a rare verb; to pass between and inspect). <b>lĕmaʿan tĕsappĕrû lĕdôr ʾaḥărôn</b> — <i>that you may tell the next generation</i>. The purpose of the inspection: to remember what you have seen and transmit it to the next generation. The tour of Zion's defenses becomes a pedagogical act — what you mark and survey today you can narrate to your children.</p>",
    "14": "<p><b>kî zeh ʾĕlōhîm ʾĕlōhênû ʿôlām wāʿed</b> — <i>for this God is our God forever and ever</i>. The climactic confession — <i>zeh</i> (this one — demonstrative, pointing to the God whose power has just been celebrated) is <i>ʾĕlōhênû</i> (our God). The Zion-theology grounded in covenant identity. <b>hûʾ yĕnahăgênû ʿalmût</b> — <i>he will guide us until the very end</i>. <i>Nāhag</i> (to guide, lead — the shepherd's or caravan-guide's leading). <i>ʿAlmût</i> (the word is ambiguous: it can mean <i>ʿad-mût</i> = until death = forever; or <i>ʿal-mût</i> = over/beyond death = past the death-threshold). Most read it as 'forever' (unto death = all one's life), but the consonantal text admits a reading of 'beyond death' — a faint ray of post-mortem hope within the Zion psalm.</p>"
  },
  "49": {
    "1": "<p><b>shimĕʿû-zōʾt kol-hāʿammîm</b> — <i>hear this, all peoples!</i> The universal address of a wisdom psalm — not just Israel but <i>kol-hāʿammîm</i> (all the peoples). <b>haʾăzînû kol-yōshĕbê ḥāled</b> — <i>listen, all who live in the world</i>. <i>Ḥāled</i> (the world, the temporal world — from a root meaning duration; the world as the sphere of transient time; cf. Ps 17:14: <i>mēḥeled ḥelqām</i>, their portion in this life). The audience is as wide as humanity itself, because the psalm's subject (mortality and wealth's impotence before death) is universal.</p>",
    "2": "<p><b>gam-bĕnê ʾādām gam-bĕnê-ʾîsh</b> — <i>the humble and the great alike</i>. <i>Bĕnê ʾādām</i> (sons of Adam — the common person, humanity in its generic form) + <i>bĕnê ʾîsh</i> (sons of a man of rank — the distinguished, the notable). The Hebrew idiom distinguishes commoner from aristocrat — both are addressed. <b>yaḥad ʿāshîr wĕʾebyôn</b> — <i>the rich and the poor together</i>. <i>Yaḥad</i> (together — they are unified in the audience, as they will be unified in death, v12). The wisdom that follows applies to all without distinction.</p>",
    "3": "<p><b>pî yĕdabbēr ḥokhĕmôt</b> — <i>my mouth will speak wisdom</i>. The wisdom-genre self-identification: the speaker announces he will offer <i>ḥokhĕmôt</i> (wisdom — plural of ḥokhĕmāh: wisdoms, wisdom-speech in all its forms). <b>wĕhagût libbî tĕbûnôt</b> — <i>and the reflection of my heart will be understanding</i>. <i>Hagût</i> (meditation, reflection — from hāgāh: to murmur, to meditate) of the <i>lēb</i> (heart = the center of thought and understanding). <i>Tĕbûnôt</i> (understandings — plural: multiple facets of understanding). The heart's meditation as the source of what the mouth will speak — wisdom is not imported but grown internally.</p>",
    "4": "<p><b>ʾaṭṭeh lĕmāshāl ʾoznî</b> — <i>I bend my ear to a proverb</i>. <i>Māshāl</i> (proverb, wisdom-saying — the generic term for wisdom-literature; from māshal: to rule, to be like). The act of bending the ear (<i>nāṭāh ʾōzen</i>) to a proverb — listening to receive wisdom. <b>ʾeptaḥ bĕkhinnôr ḥîdātî</b> — <i>I will open my riddle with the harp</i>. <i>Ḥîdāh</i> (riddle, dark saying, enigmatic wisdom — the indirect wisdom that requires insight to unpack; from ḥûd: to propose a riddle, cf. Samson's riddle, Judg 14:12-19). The pairing of <i>māshāl</i> and <i>ḥîdāh</i> signals the highest wisdom-register (cf. Ps 78:2). The harp (<i>kinnôr</i>) as the instrument of prophetic inspiration (1 Sam 10:5; 2 Kgs 3:15).</p>",
    "5": "<p><b>lāmmāh ʾîrāʾ bîmê rāʿ</b> — <i>why should I be afraid in evil days?</i> The existential question the psalm addresses: what is the ground of fearlessness when evil days come? <b>ʿăwōn ʿăqēbay yĕsûbbênî</b> — <i>when the guilt of my accusers closes in around me</i>. <i>ʿĂqēb</i> (heel — those who trip at the heel, who pursue closely from behind; from ʿāqab: to supplant, to overtake from behind). The accusers (or the treacherous) surrounding the Psalmist. The answer to why not to fear occupies the rest of the psalm: because wealth cannot ransom, and death makes all equal, trust in God transcends the threat.</p>",
    "6": "<p><b>haboṭĕḥîm ʿal-ḥêlām</b> — <i>those who trust in their wealth</i>. <i>Bāṭaḥ ʿal</i> (to trust in, rely upon — placing one's weight on). <i>Ḥayil</i> (wealth, strength, resources — the accumulated capital in all its forms). <b>ûbĕrōb ʿoshĕrām yithallālû</b> — <i>and boast of their great riches</i>. <i>Hālal</i> (hitpael: to boast, to praise oneself — the same root as <i>hallelujah</i> inverted: self-praise instead of God-praise). The object of the self-boasting is <i>ʿōsher</i> (riches, wealth). The irony: those who will not escape death (vv7-12) are those who trust in wealth and boast of riches.</p>",
    "7": "<p><b>ʾāḥ lōʾ-phādōh yiphĕdeh ʾîsh</b> — <i>truly no one can by any means ransom another person</i>. The emphatic negation: <i>ʾāḥ lōʾ-phādōh yiphĕdeh</i> (surely no/by no means shall one ransom) — the infinitive absolute (<i>phādōh</i>) + imperfect (<i>yiphĕdeh</i>) expresses the categorical impossibility. <i>Phādāh</i> (to ransom, to buy back from danger/obligation/death — the redemption verb of the Exodus, Ps 130:8). The ransom that no human can pay for another. <b>lōʾ-yittēn lĕʾĕlōhîm kophĕrô</b> — <i>or give God a payment for their life</i>. <i>Kōpher</i> (the ransom price — the substitute payment that averts death, as in Exod 30:12). No ransom sufficient to God can be offered by a human.</p>",
    "8": "<p><b>wĕyāqar pidyon nafshām</b> — <i>for the price of their life is too costly</i>. <i>Pidyon</i> (ransom — from phādāh) + <i>yāqār</i> (too costly, too high — beyond affordability). <b>wĕḥādal lĕʿôlām</b> — <i>and no payment will ever be enough</i>. <i>Ḥādal</i> (to cease, to give up — the payment must be abandoned as an impossible task). The economic metaphor: the ransom price exceeds all possible human resources; it must be given up as unachievable forever.</p>",
    "9": "<p><b>wîḥî-ʿôd lāneṣaḥ</b> — <i>that one could live on forever</i>. The goal that the ransom would achieve — continued life — is declared impossible. <b>lōʾ yirʾeh hashshāḥat</b> — <i>and not see the pit</i>. <i>Shāḥat</i> (the pit — the grave, Sheol as a pit; the destination of every unransomed life). No humanly-funded ransom can prevent the grave.</p>",
    "10": "<p><b>kî yirʾeh ḥăkhāmîm yāmûtû</b> — <i>he sees that even the wise die</i>. The empirical observation: the wise (<i>ḥăkhāmîm</i>) die like everyone else — wisdom does not provide exemption from death. <b>yaḥad kĕsîl wābāʿar yōbēdû</b> — <i>the fool and the senseless alike perish</i>. <i>Kĕsîl</i> (fool — the morally obtuse) + <i>bāʿar</i> (brute, the senseless person of animal-like behavior, cf. Ps 92:6). All three — wise, fool, brute — perish together. <b>wĕʿāzĕbû lāʾăḥērîm ḥêlām</b> — <i>and leave their wealth behind for others</i>. The wealth (<i>ḥayil</i>) that was trusted (v6) and boasted of cannot be carried into death — it passes to others (<i>ʾăḥērîm</i>: strangers).</p>",
    "11": "<p><b>qirbām bāttêmô lĕʿôlām</b> — <i>in their hearts they imagined their homes would last forever</i>. <i>Qereb</i> (inner parts, heart — what they thought inside). Their homes (bāttêmô: their houses) imagined as permanent. <b>mishkĕnōtām lĕdōr wādōr</b> — <i>their dwelling places to all generations</i>. The fantasy of dynastic permanence — houses and estates passing through all generations. <b>qārĕʾû bishĕmôtām ʿălê ʾădāmôt</b> — <i>they called their lands after their own names</i>. The act of naming the land after oneself — the ancient equivalent of leaving one's name on a building or institution — as a gesture of claiming permanence that death will defeat.</p>",
    "12": "<p><b>wĕʾādām bîqār bĕlî-yālîn</b> — <i>man in all his honor will not last overnight</i>. <i>Bîqār</i> (in honor, in dignity — the splendor of wealth and position). <i>Lōʾ yālîn</i> (will not spend the night — will not remain through even a single night of time; the brevity expressed by a single night's lodging). <b>nidmeh kabbe-hēmôt nidĕmû</b> — <i>he is like the animals that perish</i>. <i>Dāmāh</i> (to be like, to resemble) + <i>bĕhēmôt</i> (animals, cattle) — the human without divine connection is likened to beasts that simply die and are gone. This refrain appears again at v20, with one significant variation.</p>",
    "13": "<p><b>zeh darkām kĕsel lāmô</b> — <i>this is the fate of those who are confident in themselves</i>. <i>Kesel</i> (foolish confidence, self-reliance — from the root of kĕsîl: the fool who trusts in the wrong thing). <b>wĕʾaḥărêhem bĕphêhem yirṣû selāh</b> — <i>and after them people applaud their talk</i>. Those who come after them (<i>ʾaḥărêhem</i>) approve of their path (<i>bĕphêhem yirṣû</i>: they find pleasure in their words). The fool's path gets inherited and continued by others who find it appealing. The selah marks a moment for the listener to absorb this cycle of folly.</p>",
    "14": "<p><b>kaṣṣōʾn lashshĕʾôl shattû</b> — <i>like sheep they are headed for Sheol</i>. The driving of sheep: <i>shātat</i> (to drive, appoint) — they are herded toward Sheol as sheep are driven to their destination. <b>māwet yirʿēm</b> — <i>death will be their shepherd</i>. <i>Rāʿāh</i> (to shepherd, to pasture) — Death as shepherd is the psalm's darkest inversion: the God who is shepherd (Ps 23:1; 80:1) is here replaced by Death as the shepherd of those who trust in wealth. <b>wîrdû-bām yeshārîm laboqer</b> — <i>and the upright will have dominion over them in the morning</i>. The eschatological reversal at the morning: the <i>yeshārîm</i> (the upright ones) rule over the formerly proud rich. <b>wĕṣûrām lĕbattôt sheʾôl</b> — <i>their bodies will decay in Sheol, with no home left for them</i>. The end of the household fantasy of v11: no home (<i>zĕbul</i>: dwelling, lordly residence) remains.</p>",
    "15": "<p><b>ʾakh-ʾĕlōhîm yiphĕdeh nafshî miyyad-shĕʾôl</b> — <i>but God will ransom my soul from the grip of Sheol</i>. The pivot verse — <i>ʾakh</i> (but, surely — the contrast particle). Everything vv7-9 said was impossible (<i>lōʾ-phādōh yiphĕdeh</i>: none can ransom another), God will do: <i>yiphĕdeh</i> (he will ransom). The vocabulary is exact: the impossible human ransom becomes the possible divine ransom. <b>kî yiqqāḥēnî selāh</b> — <i>for he will take me to himself</i>. <i>Lāqaḥ</i> (to take) — the word used of Enoch's divine taking (<i>wayyiqqah ʾōtô ʾĕlōhîm</i>, Gen 5:24) and of Elijah's translation (2 Kgs 2:1-11). The verb carries the weight of those two precedents: being taken by God is the vocabulary of post-mortem rescue. The selah marks this as the most weighty statement in the psalm.</p>",
    "16": "<p><b>ʾal-tîrāʾ kî-yaʿăshîr ʾîsh</b> — <i>do not be frightened when someone becomes rich</i>. The practical application of vv7-15: the command not to fear (<i>yārēʾ</i>) the enrichment of another. <b>kî-yirbbeh kĕbôd bêtô</b> — <i>when the splendor of their household grows</i>. <i>Kābôd</i> (glory, splendor — here applied to a household's impressive accumulation). The apparently threatening success of the wealthy person is the context of fear — the psalm counsels the right response.</p>",
    "17": "<p><b>kî lōʾ bĕmôtô yiqqaḥ hakkōl</b> — <i>for when they die they take nothing with them</i>. The reason not to fear: at death, all the accumulated wealth (<i>hakkōl</i>: everything) is left behind. <b>lōʾ-yērēd ʾaḥărāyw kĕbôdô</b> — <i>their glory will not follow them down</i>. The reversal: the glory (<i>kābôd</i>) that was growing (v16) will not descend with the person into Sheol — it stays in the world above and passes to others (v10: <i>lāʾăḥērîm</i>).</p>",
    "18": "<p><b>kî-nafshô bĕḥayyāyw yĕbārek</b> — <i>though in their lifetime they counted themselves fortunate</i>. <i>Bārak nafshô</i> (to bless oneself — to congratulate oneself, to pronounce oneself well-off; the self-congratulation of the prosperous). <b>wĕyôdûkhā kî-têṭîb lākh</b> — <i>and people praised them for prospering</i>. <i>Yādāh</i> (hiph: to praise) when things go well (<i>kî-têṭîb lākh</i>: because it is good for you). The social praise of prosperity: people praise the successful as long as success lasts.</p>",
    "19": "<p><b>tābôʾ ʿad-dôr ʾăbôtāyw</b> — <i>they will go to join their ancestors</i>. The inevitable reunion with the dead — the same Sheol that received their forefathers receives them. <b>ʿad-neṣaḥ lōʾ yirʾû-ʾôr</b> — <i>and never again see the light</i>. <i>ʾôr</i> (light — the light of the living world, of divine favor; cf. Ps 36:9: <i>bĕʾôrĕkhā nirʾeh-ʾôr</i>). The loss of light is the definitive characteristic of Sheol (cf. Ps 88:12; Job 10:21-22). The self-praising, wealth-trusting person goes into permanent darkness.</p>",
    "20": "<p><b>wĕʾādām bîqār wĕlōʾ yābîn nidmeh kabbe-hēmôt nidĕmû</b> — <i>man in all his honor, but without understanding, is like the animals that perish</i>. The refrain returns from v12 with one variation: v12 has <i>bĕlî-yālîn</i> (will not remain/lodge) but v20 has <i>wĕlōʾ yābîn</i> (without understanding). The final verse specifies what makes human honor equivalent to animal death: the absence of <i>bîn</i> (understanding/discernment — the wisdom-faculty). Honor without understanding ends in animal-death. V15's divine ransom is the alternative for those who do understand.</p>"
  },
  "50": {
    "1": "<p><b>ʾēl ʾĕlōhîm YHWH dibbēr</b> — <i>the Mighty One, God, the LORD, has spoken</i>. The solemn triple invocation of the divine name — <i>ʾēl</i> (the generic name for deity, the powerful one) + <i>ʾĕlōhîm</i> (the generic plural divine name) + <i>YHWH</i> (the covenant personal name). This judicial formula (cf. Josh 22:22: <i>ʾēl ʾĕlōhîm YHWH</i>) convenes the divine court. Psalm 50 is the first of the Asaphite psalms (50, 73-83). <b>wayyiqrāʾ ʾāreṣ mimmizerāḥ-shemesh ʿad-mĕbōʾô</b> — <i>and summons the earth from east to west</i>. The divine summons of the entire earth as witness to the covenant lawsuit (rîb) — from sunrise to sunset, the universal scope of the judicial proceeding.</p>",
    "2": "<p><b>mîṣiyyôn miklal-yōphî ʾĕlōhîm hôphîaʿ</b> — <i>out of Zion, perfect in beauty, God has shone forth</i>. <i>Miklal-yōphî</i> (perfection of beauty — the superlative of Zion's beauty; cf. Lam 2:15: <i>ʾăsher ʾāmĕrû kĕlîlat yōphî</i> of fallen Jerusalem). <i>Hôphîaʿ</i> (hiphil of yāphaʿ: to shine forth — the blazing appearance of the divine judge from Zion; the same verb as Ps 94:1 where YHWH is asked to shine forth in judgment).</p>",
    "3": "<p><b>yābôʾ ʾĕlōhênû wĕʾal-yeḥĕrash</b> — <i>our God comes and will not stay silent</i>. <i>Ḥāresh</i> (to keep silent, to hold one's peace — the accused calling on the judge to be silent; here YHWH will not remain silent). <b>ʾēsh lĕphānāyw tōʾkhēl</b> — <i>fire devours before him</i>. Fire as the divine judicial presence (cf. Exod 3:2; 19:18; Deut 4:24; Ps 97:3). <b>ûsĕbîbāyw niśʿărāh mĕʾōd</b> — <i>and a fierce storm rages around him</i>. <i>Niśʿar</i> (niphal: to be violently stormy — the storm-theophany surrounding the divine judge). The God who comes is neither neutral nor passive — fire and storm attend his arrival.</p>",
    "4": "<p><b>yiqrāʾ ʾel-hashshāmayim mēʿāl wĕʾel-hāʾāreṣ</b> — <i>he calls out to the heavens above and to the earth</i>. The witnesses summoned: heaven and earth — the two parties in the cosmic covenant (cf. Deut 30:19: <i>hāʿîdōtî bākem hayyôm ʾet-hashshāmayim wĕʾet-hāʾāreṣ</i>: I call heaven and earth to witness against you). <b>lādîn ʿammô</b> — <i>to judge his people</i>. <i>Dîn</i> (to judge — to enter into judicial proceedings against). The covenant lawsuit: YHWH is prosecuting Israel, not an external enemy.</p>",
    "5": "<p><b>ʾispû-lî ḥăsîday</b> — <i>bring together my faithful people</i>. <i>Ḥāsîd</i> (the faithful, covenant-loyal ones — those who embody ḥesed). <b>kōrĕtê bĕrîtî ʿălê-zābaḥ</b> — <i>those who sealed covenant with me by sacrifice</i>. <i>Kārat bĕrît</i> (to cut a covenant — the standard covenant formula; covenants were ratified by cutting animals in two, as in Gen 15:10-18; Jer 34:18-20). The faithful are defined by their covenantal relationship — they sealed the covenant with sacrifice. Now the sacrifices are the subject of the lawsuit.</p>",
    "6": "<p><b>wayyaggîdû shāmayim ṣidqô</b> — <i>the heavens declare his righteousness</i>. The heavens as witnesses now become witnesses to the divine righteousness — the cosmic court validates YHWH's justice. <b>kî-ʾĕlōhîm shōphēṭ hûʾ selāh</b> — <i>for God himself is the judge</i>. The selah after this declaration — God is the judge, both plaintiff and judge in the covenant lawsuit. The pause lets the weight of that identity settle before the divine speech begins.</p>",
    "7": "<p><b>shimĕʿāh ʿammî waʾădabbērāh</b> — <i>listen, my people, and I will speak</i>. The divine speech begins — YHWH addressing <i>ʿammî</i> (my people: the covenant relationship intact even in the lawsuit). <b>yisrāʾēl wĕʾāʿîdāh bākh</b> — <i>I will testify against you, O Israel</i>. <i>ʿûd</i> (hiphil: to testify solemnly, to warn — the judicial testimony function). <b>ʾĕlōhîm ʾĕlōhêkhā ʾānōkhî</b> — <i>I am God, your God</i>. The self-identification formula — exactly the form of the Ten Commandments' preface (<i>ʾānōkhî YHWH ʾĕlōhêkhā</i>, Exod 20:2). The covenant relationship is the basis for the lawsuit, not its repudiation.</p>",
    "8": "<p><b>lōʾ ʿal-zĕbāḥêkhā ʾôkhîḥekā</b> — <i>my rebuke is not over your sacrifices</i>. The lawsuit is not a critique of offering sacrifices per se — they have been brought (<i>wĕʿôlōtekhā lĕnegdî tāmîd</i>: your burnt offerings are before me continually). The complaint is not the absence of sacrifice but the misunderstanding of its purpose.</p>",
    "9": "<p><b>lōʾ-ʾeqqaḥ mibbêtekhā phār</b> — <i>I will not take from your household a bull</i>. The divine refusal of literal animal sacrifice as if God needed the animals — <i>phār</i> (bull — the most valuable sacrificial animal). <b>mimdibĕrōtekhā ʿattûdîm</b> — <i>or goats from your pens</i>. <i>Dibrāh</i> (fold, flock-enclosure) + <i>ʿattûd</i> (male goat — the leader of the flock). Both the largest and the most valuable animals are declared unnecessary as gifts to God.</p>",
    "10": "<p><b>kî-lî khol-ḥaytô-yāʿar</b> — <i>for every animal of the forest belongs to me</i>. The ownership argument: YHWH already owns all the animals (as creator and sovereign), so the gift of an animal adds nothing to his holdings. <b>behēmôt bĕʾalpê hārîm</b> — <i>the cattle on a thousand hills</i>. The totality of domesticated and wild animals — all belong to YHWH. The sacrificial system cannot transfer to God what he already possesses.</p>",
    "11": "<p><b>yādaʿtî kol-ʿôph hārîm</b> — <i>I know every bird in the hills</i>. <i>Yādaʿ</i> (to know — comprehensive divine knowledge of every creature). <b>wĕzîz śādeh ʿimmādî</b> — <i>everything that moves in the open fields is mine</i>. <i>Zîz</i> (moving thing, wild creature — possibly insects or small animals). All of creation's mobile life is with YHWH (<i>ʿimmādî</i>: with me). Nothing can be given to God as a gift since nothing is not-God's to begin with.</p>",
    "12": "<p><b>ʾim-ʾerʿab lōʾ-ʾōmar lākh</b> — <i>if I were hungry, I would not tell you</i>. The absurd hypothetical pressed to make the point: if hunger were even possible for YHWH, he would not need to ask the worshiper — he could supply himself. <b>kî-lî tēbēl ûmĕlōʾāh</b> — <i>for the world and all it contains is mine</i>. <i>Tēbēl ûmĕlōʾāh</i> (the inhabited world and its fullness — the creation-claim formula of Ps 24:1). What the worshiper offers comes from what already belongs to YHWH — the gift returns to its source.</p>",
    "13": "<p><b>hăʾōkhal bĕśar ʾabbîrîm</b> — <i>do I eat bull meat?</i> The anthropomorphic assumption corrected: God does not eat the flesh of the sacrifices. <b>wĕdam ʿattûdîm ʾeshteh</b> — <i>do I drink the blood of goats?</b> The blood, which was specifically prohibited for Israelite consumption (Lev 17:10-14), is also not consumed by YHWH. The physical substance of animal sacrifice accomplishes nothing by transfer of matter to the divine.</p>",
    "14": "<p><b>zebah lĕʾĕlōhîm tôdāh</b> — <i>bring God a thank-offering as your sacrifice</i>. The positive instruction — the alternative to misunderstood animal sacrifice. <i>Tôdāh</i> (thanksgiving, the thank-offering — from yādāh: to acknowledge/praise; the specific sacrificial genre in which the worshiper gives thanks for a completed divine rescue). <b>wĕshallēm lĕʿelyôn nĕdārêkhā</b> — <i>and keep your vows to the Most High</i>. <i>Shālem nĕdārim</i> (to fulfill/complete vows) — the ethical dimension: the sacrifice YHWH wants is keeping promises. <i>ʿElyôn</i> (the Most High) in the place of <i>ʾĕlōhîm</i> — the divine sovereign whose vows cannot be ignored.</p>",
    "15": "<p><b>ûqrāʾēnî bĕyôm ṣārāh</b> — <i>call on me when trouble comes</i>. The covenant prayer-promise: the sacrifice God accepts is the prayer of the distressed person. <b>ʾăḥalleṣkā wattĕkhabbĕdēnî</b> — <i>I will rescue you, and you will honor me</i>. The reciprocal: divine rescue produces human honor of God. The true sacrificial cycle: prayer-rescue-praise, not animal-offering-divine satisfaction.</p>",
    "16": "<p><b>wĕlārāshāʿ ʾāmar ʾĕlōhîm</b> — <i>but to the wicked God says</i>. The second part of the lawsuit turns from the misunderstanding of sacrifice (vv8-15) to the misuse of covenant language by those whose lives contradict it. <b>māh-lĕkhā lĕsappēr ḥuqqāy</b> — <i>what right do you have to quote my laws?</i> <i>Sāphar ḥuqqay</i> (to recount/recite my statutes) — those who recite the covenant law but do not keep it. <b>wattisśāʾ bĕrîtî ʿălê-phîkhā</b> — <i>or to take my covenant on your lips?</i> <i>Nāśāʾ ʿălê-pheh</i> (to take on the lips — to verbalize covenant language without moral correspondence).</p>",
    "17": "<p><b>wĕʾattāh śānēʾtā mûsār</b> — <i>you despise correction</i>. <i>Mûsār</i> (discipline, instruction, correction — the educative action of God that the wicked reject). <b>wattashlikhēhû dĕbāray ʾaḥărêkhā</b> — <i>and flung my words aside</i>. <i>Shalakh ʾaḥărāyw</i> (to throw behind oneself — to dismiss contemptuously). The covenant words of God treated as unwanted refuse thrown over the shoulder.</p>",
    "18": "<p><b>ʾim-rāʾîtā gannāb wattirṣ ʿimmô</b> — <i>when you see a thief you go along with him</i>. <i>Rāṣāh ʿimmô</i> (to be pleased with him, to approve — active complicity with theft). <b>wĕʿim-mĕnāʾăphîm ḥelqĕkhā</b> — <i>and you make yourself at home with adulterers</i>. The explicit listing of covenant-violations: complicity in theft and adultery (the seventh and eighth commandments reversed).</p>",
    "19": "<p><b>phîkhā shālaḥtā bĕrāʿāh</b> — <i>you let your mouth run loose into evil</i>. <i>Shālaḥ pheh bĕ</i> (to send/let loose the mouth into) — the unrestrained mouth directed into evil speech. <b>ûleshônĕkhā taṣmîd mirmmāh</b> — <i>and your tongue is busy weaving lies</i>. <i>Ṣāmad</i> (to attach, join closely — the tongue joined to deceit as a craftsman works at a loom). <i>Mirmāh</i> (deceit, treachery — the crafted lie).</p>",
    "20": "<p><b>tēshēb bĕʾāḥîkhā tĕdabbēr</b> — <i>you sit and talk against your own brother</i>. <i>Yāshab + dibber bĕ</i> (to sit and speak against — the posture of settled slander, deliberate and comfortable). <b>bĕben-ʾimmĕkhā titten dōphî</b> — <i>you slander your mother's son</i>. <i>Ben-ʾēm</i> (son of your mother — the closest familial bond, the full sibling) is the one slandered (<i>dōphî</i>: blemish, slander). The covenant violations cut through the most intimate human bonds.</p>",
    "21": "<p><b>ʾēlleh ʿāśîtā wĕhehĕrashttî</b> — <i>you did all these things, and I said nothing</i>. The divine silence interpreted by the wicked as divine approval — the dangerous theological mistake. <b>dimmîtā heyôt-ʾehyeh kāmôkhā</b> — <i>you concluded I must be just like you</i>. <i>Dimmāh</i> (to think, imagine — to picture in the mind) + <i>heyôt-ʾehyeh kāmôkhā</i> (that I would be like you). The theological diagnosis: anthropomorphism in the deepest sense — projecting human moral character onto God, concluding that the silent God shares the worshiper's values. <b>ʾôkhîḥăkhā wĕʾerkhāh lĕʿênêkhā</b> — <i>but now I rebuke you and lay everything out before your eyes</i>. The divine silence is broken — the judicial speech (v7) delivers its full rebuke.</p>",
    "22": "<p><b>bînû-nāʾ zōʾt shōkĕḥê ʾĕlōhîm</b> — <i>take this seriously, you who have forgotten God</i>. <i>Shākhah ʾĕlōhîm</i> (to forget God — the covenant failure of Deut 6:12; 8:11-14). <b>pen-ʾeṭrōph wĕʾên maṣṣîl</b> — <i>or I will tear you apart, and no one will rescue you</i>. <i>Tāraph</i> (to tear as a lion tears prey — the predatory divine judgment on those who forget God). The urgency: no rescuer will be available once the divine tearing begins.</p>",
    "23": "<p><b>zōbēaḥ tôdāh yĕkhabbĕdānnî</b> — <i>whoever brings thanksgiving as their sacrifice glorifies me</i>. The closing positive statement (cf. v14): the tôdāh-sacrifice honors God precisely because it acknowledges dependence rather than attempting to obligate God through material gifts. <b>wĕśām dārekh ʾarʾennû bĕyeshaʿ ʾĕlōhîm</b> — <i>to the one who walks a right path I will show the salvation of God</i>. <i>Śām dārekh</i> (one who orders/prepares the way — who walks in the prepared path of the covenant) receives the divine salvation (<i>yeshaʿ ʾĕlōhîm</i>) as its natural outcome. The lawsuit closes not with condemnation but with the open door of thanksgiving and right-path-walking.</p>"
  },
  "51": {
    "1": "<p><b>ḥānnēnî ʾĕlōhîm kĕḥasdekā</b> — <i>have mercy on me, O God, according to your steadfast love</i>. The triple ground of the petition: <i>ḥesed</i> (steadfast love) + <i>raḥămîm</i> (compassion, tender mercies — from reḥem: the womb; the visceral compassion of a mother for her child) + <i>ḥesed</i> again in expanded form. The three divine attributes are offered as the only basis the Psalmist can appeal to — not innocence but divine character. <b>kĕrōb raḥămêkhā meḥē pĕshāʿay</b> — <i>in your great compassion, blot out my transgressions</i>. <i>Māḥāh</i> (to blot out, wipe away — as ink is wiped from a tablet; the record of <i>pĕshāʿîm</i> (rebellious acts — the most willful category of sin, from pāshaʿ: to rebel, to transgress deliberately against authority) erased from the divine ledger.</p>",
    "2": "<p><b>harbeḥ kabbĕsênî mēʿăwōnî</b> — <i>scrub away my guilt completely</i>. <i>Kābaś</i> (to wash by pressing, kneading, treading — the vigorous washing that requires physical effort; the laundering of heavily soiled cloth, not a gentle rinse). The intensive washing vocabulary: <i>harbeḥ kabbĕsênî</i> (wash me greatly — the adverb <i>harbeḥ</i> intensifying the already intense verb). <b>ûmēḥaṭṭāʾtî ṭahărênî</b> — <i>and purify me from my sin</i>. <i>Ṭāhēr</i> (piel: to declare clean, to purify — the priestly verdict of purification). <i>Ḥaṭṭāʾt</i> (sin — the missing of the mark, the deviation from the path).</p>",
    "3": "<p><b>kî-pĕshāʿay ʾănî ʾēdāʿ</b> — <i>for I know my rebellious acts</i>. The acknowledgment of full awareness — the Psalmist cannot plead ignorance. <b>wĕḥaṭṭāʾtî negdî tāmîd</b> — <i>and my sin is before me at every moment</i>. <i>Negdî tāmîd</i> (before me always — continuously present to the conscience). The sin that was committed at a specific moment (the David/Bathsheba crisis) has become an unrelenting presence in the sinner's self-awareness.</p>",
    "4": "<p><b>lĕkhā lĕbaddekā ḥāṭāʾtî wĕhārāʿ bĕʿênêkhā ʿāśîtî</b> — <i>against you — you alone — have I sinned and done what is evil in your sight</i>. <i>Lĕkhā lĕbaddekā</i> (to you, to you alone — the exclusive particle <i>lĕbad</i>) emphasizes the vertical dimension of sin: the sin against Bathsheba and Uriah is simultaneously and ultimately a sin against God. Not that David did not sin against humans, but that the divine offense is primary. <b>lĕmaʿan tiṣdaq bĕdabbĕrekhā</b> — <i>so that you are proved right when you speak</i>. <i>Ṣādaq</i> (qal: to be righteous, be in the right) when he speaks his verdict — the confession validates the divine judgment. Paul cites this in Rom 3:4 (<i>hina an dikaiōthēs en tois logois sou</i>: that you might be justified in your words) as establishing the universal sinfulness that only divine justification can address.</p>",
    "5": "<p><b>hēn bĕʿāwôn ḥôlāltî</b> — <i>surely I was brought forth into guilt</i>. <i>Ḥôlāltî</i> (polal of ḥûl/ḥîl: to be brought forth in labor-pangs — to be born). <i>ʿĀwôn</i> (iniquity, guilt — the state of crooked relationship to God's standard). The Psalmist traces his present sin back to his condition at birth — solidarity with human sinfulness. <b>ûbĕḥēṭ yĕḥemmatanî ʾimmî</b> — <i>and in sin my mother conceived me</i>. Not a statement that conception or birth are sinful acts, but that the human condition from its first moment is marked by the sinful state of humanity that precedes any individual act.</p>",
    "6": "<p><b>hēn ʾĕmet ḥāpaṣtā battûḥôt</b> — <i>you desire truth deep inside a person</i>. <i>Battûḥôt</i> (in the innermost parts — the hidden interior of a person; from tāḥaḥ: to be beneath/below). <i>ʾĕmet</i> (truth, reliability — the covenant faithfulness). God's requirement is not exterior performance but interior truthfulness. <b>ûbĕsātûm ḥokhĕmāh tôdîʿēnî</b> — <i>in the hidden place you are teaching me wisdom</i>. <i>Sātûm</i> (the covered, hidden place — the innermost secret; from sātar: to hide). The divine instruction in the hidden interior: wisdom taught in the secret place, corresponding to the truth required there.</p>",
    "7": "<p><b>tĕḥaṭṭĕʾênî bĕʾēzôb wĕʾeṭhār</b> — <i>cleanse me with hyssop, and I will be clean</i>. <i>ʾĒzôb</i> (hyssop — the small, fragrant herb used in ritual purification for those with skin disease or corpse-impurity: Lev 14:4-7, 49-52; Num 19:6, 18). The hyssop dipped in the blood of a bird or the water of purification was used to sprinkle the unclean. Here the Psalmist applies the imagery to his inner moral condition. <b>tĕkabbĕsênî ûmishsheleg ʾalbîn</b> — <i>wash me, and I will be whiter than snow</i>. The comparison to snow (<i>sheleg</i>) sets the highest possible standard of whiteness — snow is the purest white in the natural world (cf. Isa 1:18: <i>ʾim-yihyû ḥăṭāʾêkhem kashĕnî kĕsheleg yalbînû</i>).</p>",
    "8": "<p><b>tashmiʿênî śāśôn wĕśimḥāh</b> — <i>let me hear the sounds of joy and gladness</i>. The petition to hear joy and gladness as the divine response to forgiveness — the senses restored to their proper objects. <b>tāgēlanāh ʿăṣāmôt dikkîtāh</b> — <i>let the bones you have crushed be glad</i>. <i>Dākhāh</i> (piel: to crush — the same root as <i>dakkāʾ</i> in Ps 90:3). The bones as the deepest physical structure — divine judgment reaches to the skeletal level. The crushed bones that are glad when forgiveness comes express the physicality of guilt and its relief.</p>",
    "9": "<p><b>hastēr pānêkhā mēḥăṭāʾāy</b> — <i>look away from my sins</i>. <i>Haster pānim</i> (to hide the face — to look away from, not to see). The unusual request: the divine face hidden from the sins rather than from the sinner (normally, <i>hester pānim</i> from the person is the experience of abandonment; here it is requested that God look away from the sin record). <b>wĕkhol-ʿăwōnōtay meḥē</b> — <i>wipe out all my guilt</i>. <i>Māḥāh</i> again (cf. v1) — the complete erasure of all iniquity.</p>",
    "10": "<p><b>lēb ṭāhôr bĕrāʾ-lî ʾĕlōhîm</b> — <i>create a pure heart in me, O God</i>. <i>Bārāʾ</i> (to create — the Genesis 1 creation word; used only of God, never of human creative activity). The request for a pure heart uses the creation vocabulary because moral renovation of this depth requires an act of new creation, not human moral improvement. The verb stands alone as the theological declaration: this is not possible through human effort. <b>wĕrûaḥ nākhôn ḥadddēsh bĕqirbî</b> — <i>and renew a steadfast spirit within me</i>. <i>Ḥādash</i> (piel: to renew — to make new again, to restore to original freshness). <i>Rûaḥ nākhôn</i> (a steadfast/established spirit — reliable, unwavering; from kûn: to be fixed, established).</p>",
    "11": "<p><b>ʾal-tashlîkhênî millĕphānêkhā</b> — <i>do not banish me from your presence</i>. <i>Shalakh millĕphānāyw</i> (to cast from the face — the royal expulsion from the royal presence; cf. Cain's expulsion from YHWH's presence, Gen 4:14). The theological horror of the petition: rejection from the divine presence is the ultimate punishment, worse than death. <b>wĕrûaḥ qodshĕkhā ʾal-tiqqaḥ mimmennî</b> — <i>do not take your Holy Spirit from me</i>. <i>Rûaḥ qōdesh</i> (Holy Spirit — the divine Spirit specifically designated as holy) — the petition not to have the Holy Spirit taken away reflects the experience of Saul (1 Sam 16:14: <i>wĕrûaḥ YHWH sārāh mēʿim-shāʾûl</i>: the Spirit of YHWH departed from Saul) as the negative paradigm David fears repeating.</p>",
    "12": "<p><b>hāshîbāh lî śĕśôn yishʿekā</b> — <i>give back to me the joy of your rescue</i>. <i>Shûb</i> (hiphil: to restore, return) — the joy of salvation that existed before the sin is asked to be restored to its prior state. <b>wĕrûaḥ nĕdîbāh tisměkhênî</b> — <i>and sustain me with a generous, willing spirit</i>. <i>Rûaḥ nĕdîbāh</i> (a generous/willing/noble spirit — from nādab: to volunteer, to give freely; the spirit of willing, ungrudging devotion). The spirit that gives freely to God without compulsion — the antithesis of the grudging, self-serving approach to worship criticized in Ps 50.</p>",
    "13": "<p><b>ʾălammĕdāh phōshĕʿîm dĕrākhêkhā</b> — <i>then I will show other rebels your ways</i>. <i>Pōshĕʿîm</i> (the rebellious — the same root as <i>pĕshāʿ</i> in v1). The forgiven rebel becomes the teacher of other rebels — the missionary consequence of forgiveness. <b>wĕḥaṭṭāʾîm ʾēlêkhā yāshûbû</b> — <i>and sinners will come back to you</i>. <i>Shûb</i> (to return, repent) — the sinners will turn back to God through the testimony of the forgiven Psalmist. The repentance of the one generates the repentance of others.</p>",
    "14": "<p><b>haṣṣîlênî middāmîm ʾĕlōhîm ʾĕlōhê tĕshûʿātî</b> — <i>rescue me from the guilt of bloodshed, O God — God of my salvation</i>. <i>Dāmîm</i> (bloods — the plural of blood, used specifically of shed blood and its guilt; Uriah's blood). The specific sin named: bloodguilt, the most severe category of moral pollution in the OT (Num 35:33; Deut 19:10). <b>tĕrannēn lĕshônî ṣidqātekhā</b> — <i>and my tongue will ring out your righteousness</i>. The forgiven tongue — freed from the guilt that silenced it — sings the divine righteousness. The tongue that was the instrument of deception in David's sin becomes the instrument of praise.</p>",
    "15": "<p><b>ʾădōnāy śĕphātay tiphttāḥ</b> — <i>O Lord, open my lips</i>. The paradox: the Psalmist cannot open his own lips to praise because sin has closed them. The divine action (opening lips) must precede the human act (praise). <b>ûphî yaggîd tĕhillātekhā</b> — <i>and my mouth will declare your praise</i>. The praise that follows the divine opening — not self-initiated but response to divine gift. The mouth that was loosened in evil speech (cf. Ps 50:19) is now opened by God for praise.</p>",
    "16": "<p><b>kî lōʾ-taḥpōṣ zebaḥ wĕʾettēnāh</b> — <i>you do not want sacrifice — otherwise I would bring it</i>. The echo of Ps 50:8-14 — the theme of what God truly wants as sacrifice. The Psalmist will not bring animal sacrifice not because he refuses but because he understands God's actual desire. <b>ʿôlāh lōʾ tirṣeh</b> — <i>you take no delight in burnt offerings</i>. <i>Rāṣāh</i> (to be pleased with, to accept favorably — the technical term for the divine acceptance of a sacrifice). The <i>ʿôlāh</i> (burnt offering — the wholly burned offering) does not achieve what only contrition achieves.</p>",
    "17": "<p><b>zibĕḥê ʾĕlōhîm rûaḥ nishbārāh</b> — <i>God's desired sacrifice is a broken spirit</i>. <i>Rûaḥ nishbārāh</i> (a broken spirit — from shābar: to break, shatter). The spirit broken by the weight of known guilt is the sacrifice that pleases God — a complete inversion of the sacrificial system's material expectations. <b>lēb-nishbār wĕnidkkeh ʾĕlōhîm lōʾ tivzeh</b> — <i>a broken and crushed heart, O God, you will not despise</i>. <i>Nidkeh</i> (niphal of dākhāh: crushed — the same root as <i>dakkāʾ</i> in Ps 90:3 and <i>dikkîtāh</i> in Ps 51:8). The divine verdict: the broken and crushed heart will not be despised (<i>bāzāh</i>: to treat with contempt). God who rejects the formally correct sacrifice accepts the broken heart.</p>",
    "18": "<p><b>hêṭîbāh birṣônĕkhā ʾet-ṣiyyôn</b> — <i>in your favor, do good to Zion</i>. The communal petition — the individual psalm reaches outward to the community. <b>tibneh ḥômôt yĕrûshālāim</b> — <i>build up the walls of Jerusalem</i>. <i>Bānāh ḥômôt</i> (to build walls — the construction of the city's defenses). This verse (and v19) are often read as a later addition reflecting the exile when Jerusalem's walls were destroyed. Whether original or added, the movement from personal contrition (v17) to communal restoration (v18-19) is theologically significant: the individual's forgiveness is connected to the community's welfare.</p>",
    "19": "<p><b>ʾāz taḥpōṣ zibĕḥê-ṣedeq</b> — <i>then you will be pleased with right sacrifices</i>. <i>Zibĕḥê-ṣedeq</i> (sacrifices of righteousness — sacrifices offered from a right heart, the inner condition that makes the outward offering acceptable; cf. Deut 33:19; Ps 4:5). <b>ʿôlāh wĕkhālîl</b> — <i>with burnt offerings and whole offerings</i>. The animal sacrifices that v16 declared God did not want are not permanently abolished — they are restored to their proper function once the heart is right (v17). <b>ʾāz yaʿălû ʿal-mizbĕḥakā phārîm</b> — <i>then bulls will go up on your altar</i>. The material offerings return to their proper place — after, not instead of, the broken and contrite heart.</p>"
  },
  "52": {
    "1": "<p><b>māh-tithalēl bĕrāʿāh haggîbbôr</b> — <i>why do you boast of evil, O powerful man?</i> The ironic address: <i>gibbôr</i> (mighty man, warrior, hero) — the title of honor applied with bitter irony to Doeg the Edomite, whose boast is in betrayal rather than valor. <b>ḥesed ʾēl kol-hayyôm</b> — <i>the steadfast love of God holds all the day</i>. The theological counter to the hero's boasting: while the <i>gibbôr</i> boasts in wickedness, the divine ḥesed endures through all the day. The juxtaposition of the wicked hero's momentary triumph against the permanent divine steadfast love.</p>",
    "2": "<p><b>hawwôt taḥshōb lĕshônekā</b> — <i>your tongue plots ruin</i>. <i>Ḥāshab</i> (to devise, think out, plan — the deliberate, calculated planning of harm; the tongue as the instrument of the planning). <i>Hawwāh</i> (ruin, destruction — from hāwāh: to fall; the catastrophic ruin brought by the wicked tongue). <b>kĕtaʿar mĕlûṭāsh</b> — <i>sharp as a razor blade</i>. <i>Taʿar mĕlûṭāsh</i> (a sharpened razor/knife) — the tongue as a cutting weapon. The tongue-as-weapon metaphor (cf. Ps 57:4; 64:3) applied to Doeg whose words to Saul caused the massacre of the Nob priests (1 Sam 22:9-10, 18-19). <b>ʿōśēh rĕmiyyāh</b> — <i>you craftsman of deceit</i>. <i>Rĕmiyyāh</i> (deceit, treachery — the deceptive quality that makes the razor-tongue doubly dangerous).</p>",
    "3": "<p><b>ʾāhabtā rāʿ miṭṭôb</b> — <i>you love evil rather than good</i>. The choice is not ignorance but love (<i>ʾāhab</i>: to love — the affective, volitional commitment to evil over good). <b>sheqer middabbēr ṣedeq selāh</b> — <i>and lies rather than truth</i>. <i>Sheqer</i> (lie, falsehood — the spoken word that diverges from reality) loved more than <i>ṣedeq</i> (righteousness, truth, right-speaking). The selah marks the weight of the verdict before the consequence is described.</p>",
    "4": "<p><b>ʾāhabtā khol-dibĕrê-baladaʿ</b> — <i>you love every word that destroys</i>. <i>Baladaʿ</i> (swallowing, destruction — from bālaʿ: to swallow up). Every destructive word is loved — the comprehensive appetite for ruinous speech. <b>lĕshôn mirmāh</b> — <i>you treacherous tongue</i>. The direct address to the tongue itself — the tongue named for its defining quality: <i>mirmāh</i> (deceit, treachery — the betrayal that the tongue performs).</p>",
    "5": "<p><b>gam-ʾēl yiṭṭāḥăkhā lāneṣaḥ</b> — <i>but God will also pull you down permanently</i>. <i>Nātaḥ</i> (hiphil: to demolish, throw down — the tearing down of what has been built up). <i>Lāneṣaḥ</i> (permanently, forever — in contrast to the temporary success of the wicked). <b>yaḥtĕkhā wĕyissāḥăkhā meʾōhel</b> — <i>he will grab and rip you from your home</i>. <i>Ḥātāh</i> (to seize — as one seizes burning coals with tongs) + <i>nāsaḥ</i> (to tear out, uproot — as a plant is torn from the soil). <b>wĕshēreshshĕkhā mēʾereṣ ḥayyîm selāh</b> — <i>he will tear you out of the land of the living</i>. <i>Shāresh</i> (piel: to root out, to remove completely by the roots — the destruction that reaches to the foundational level). <i>ʾEreṣ ḥayyîm</i> (the land of the living — the world of the living, in contrast to Sheol). The selah marks the divine verdict before the community's response.</p>",
    "6": "<p><b>wĕyirʾû ṣaddîqîm wĕyîrāʾû</b> — <i>the righteous will see and be filled with awe</i>. The communal response to the wicked one's downfall: <i>yirʾû</i> (they will see — witness the event) + <i>yîrāʾû</i> (they will fear/be awed — the reverential response to divine judgment). <b>wĕʿālāyw yiśḥāqû</b> — <i>and they will laugh</i>. <i>Śāḥaq</i> (to laugh — not cruel mockery but the laughter of vindication; the laughter of those who were threatened by the powerful wicked person and now see the divine reversal).</p>",
    "7": "<p><b>hinnēh haggeber lōʾ yāśîm ʾĕlōhîm maʿûzzô</b> — <i>here is the man who would not take refuge in God</i>. <i>Śîm maʿôz</i> (to set/make as a fortress — to adopt as one's stronghold). The man who refused to make God his stronghold. <b>wayyibṭaḥ bĕrōb ʿoshĕrô</b> — <i>but relied on his great wealth</i>. <i>Bāṭaḥ bĕ</i> (to trust in — the same verb as Ps 49:6 where the foolish trust in wealth). <b>yaʿōz bĕhawwātô</b> — <i>and found his strength in destruction</i>. <i>ʿāzaz bĕhawwāh</i> (to make oneself strong through ruin — the power built on the destruction of others: Doeg's strength was built on the ruin of Ahimelech and the Nob priests).</p>",
    "8": "<p><b>waʾănî kĕzayit raʿănān bĕbêt ʾĕlōhîm</b> — <i>but I am like a flourishing olive tree in the house of God</i>. <i>Zayit raʿănān</i> (a flourishing/green olive tree — <i>raʿănān</i>: fresh, lush, full of life as in Ps 92:14). The contrast with the uprooted wicked (v5): where Doeg is torn from his home, David is like an olive tree planted in the divine house. The olive tree's longevity (centuries), its productivity (oil for light, food, and anointing), and its evergreen character make it a rich image for enduring covenant life. <b>bāṭaḥtî bĕḥesed-ʾĕlōhîm ʿôlām wāʿed</b> — <i>I trust in God's steadfast love forever and ever</i>. The ground of the olive-tree flourishing: trust (<i>bāṭaḥ</i>) in the divine ḥesed — the opposite of the wicked's trust in wealth and destructive power.</p>",
    "9": "<p><b>ʾôdekhā lĕʿôlām kî ʿāśîtā</b> — <i>I will give you thanks forever, because of what you have done</i>. <i>Yādāh</i> (to give thanks, to acknowledge publicly) — the thanksgiving that Ps 50 identified as the true sacrifice (<i>tôdāh</i>). <b>wăʾăqawweh shimĕkhā kî-ṭôb neged ḥăsîdêkhā</b> — <i>I will hope in your name, for it is good, before your faithful people</i>. <i>Qāwāh</i> (to hope, wait for — the patient expectation oriented toward the divine name). The final word: in the presence of the <i>ḥăsîdîm</i> (the faithful ones — those who embody the ḥesed that is the opposite of Doeg's treachery) the Psalmist will declare the goodness of the divine name.</p>"
  },
  "53": {
    "1": "<p><b>ʾāmar nābāl bĕlibbô ʾên ʾĕlōhîm</b> — <i>the fool has said in his heart, 'There is no God.'</i> <i>Nābāl</i> (fool — not intellectual atheism but moral and practical rejection of God's involvement in human affairs; the nābāl is the person who acts as if God does not observe, evaluate, or respond to human behavior; cf. Abigail's description of Nabal, 1 Sam 25:25). The denial is in the heart (<i>bĕlibbô</i>: in his heart) — an interior decision about divine governance that then shapes behavior. Psalm 53 is a variant of Psalm 14; the main difference is the use of <i>ʾĕlōhîm</i> (53) vs. <i>YHWH</i> (14) — the Elohistic variant. <b>hisḥîtû wĕhiṭṭîbû ʿāwel</b> — <i>they are corrupt and have done vile deeds</i>. <i>Sāḥat</i> (hiphil: to corrupt, act corruptly — from the Flood's vocabulary, Gen 6:12). <i>ʿĀwel</i> (injustice, wrong — the practical social consequence of the interior denial of God).</p>",
    "2": "<p><b>ʾĕlōhîm mishshāmayim hishqîph</b> — <i>God looked down from heaven</i>. <i>Shāqaph</i> (to look down from above — to peer over an edge from a height). The divine counter-survey: the fool claims there is no God; God looks down and surveys the fool's claim and the human reality beneath it. <b>ʿal-bĕnê ʾādām lirʾôt hay-yēsh maskîl</b> — <i>on all humanity to see if anyone understands</i>. <i>Maskîl</i> (one who understands, who acts wisely — from śākal: to have insight). The divine survey looking for a single <i>maskîl</i> — the most ironic title in the context: the psalm-title (<i>maskîl</i>) identifies the psalm itself as a wisdom-teaching, while the content reports the divine failure to find anyone with wisdom. <b>dōrēsh ʾet-hāʾĕlōhîm</b> — <i>if anyone seeks after God</i>. The seeking of God as the measure of understanding.</p>",
    "3": "<p><b>kullô sāg yāḥdāw neʾĕlāḥû</b> — <i>every single one has turned aside; together they have become rotten</i>. <i>Sûg</i> (to turn back, withdraw — the apostasy of turning away from God). <i>ʾĀlaḥ</i> (niphal: to become rotten/putrid — of milk that has curdled, of something that has gone bad; the corruption reaching the point of decomposition). <b>ʾên ʿōśēh-ṭôb ʾên gam-ʾeḥād</b> — <i>there is no one who does good — not a single person</i>. The emphatic universal negation (<i>gam-ʾeḥād</i>: even one). Paul cites this in Rom 3:11-12 as scriptural proof of universal human sinfulness.</p>",
    "4": "<p><b>hălōʾ yādĕʿû pōʿălê ʾāwen</b> — <i>don't those who work evil know anything?</i> <i>Yādaʿ</i> (to know — the rhetorical question: do they truly have no knowledge?). <b>ʾōkĕlê ʿammî ʾākhĕlû leḥem</b> — <i>those who devour my people the way they eat bread</i>. The image of the oppressors consuming (<i>ʾākal</i>: to eat) the people of God as if eating bread — casual, routine consumption of the vulnerable. <b>ʾĕlōhîm lōʾ qārāʾû</b> — <i>and never call on God</i>. The failure to call on God (<i>qārāʾ</i>) is both symptom and diagnosis: the evildoers do not pray because they do not believe God will or should respond.</p>",
    "5": "<p><b>shām pāḥădû-phāḥad lōʾ-hāyāh phāḥad</b> — <i>but there they are, overwhelmed with terror where there was no terror</i>. The divine irony: the people who denied God's existence and operation experience overwhelming terror (<i>pāḥad</i>: fear, dread) where there was nothing to fear — the panic comes from nowhere visible because its source is the God who was denied. <b>kî-ʾĕlōhîm pizzar ʿaṣmôt ḥōnākekhā</b> — <i>for God scattered the bones of those who attacked you</i>. The specific historical reference (different from Ps 14) — a deliverance in which YHWH scattered the bones of the attackers. <b>hĕbōshotāh kî-ʾĕlōhîm mĕʾāsām</b> — <i>you put them to shame, for God has rejected them</i>. <i>Mĕʾāsām</i> (he has rejected them — from māʾas: to despise, reject; cf. Ps 78:67 where Ephraim is rejected). The divine rejection as the theological explanation for the historical defeat.</p>",
    "6": "<p><b>mî yittēn miṣṣiyyôn yĕshûʿōt yisrāʾēl</b> — <i>oh, that Israel's rescue would come out of Zion!</i> The closing eschatological prayer — <i>mî yittēn</i> (who will give? = O that! — the wish-formula expressing longing). <i>Yĕshûʿōt</i> (salvations, plural — the fullness of rescue). From Zion as the source (cf. Ps 14:7 which is nearly identical). <b>bĕshûb ʾĕlōhîm shĕbût ʿammô</b> — <i>when God restores the fortunes of his people</i>. <i>Shûb shĕbût/shĕbît</i> (to restore the restoration — a figure of speech expressing complete reversal of captivity and distress; cf. Job 42:10; Jer 29:14). <b>yāgēl yaʿăqōb yiśmaḥ yisrāʾēl</b> — <i>Jacob will rejoice and Israel will be glad</i>. The conclusion connects the wisdom-psalm's grim survey of universal foolishness and corruption with the hope of divine salvation: only YHWH's initiative from Zion can break the cycle.</p>"
  },
  "54": {
    "1": "<p><b>ʾĕlōhîm bĕshimĕkhā hôshîʿênî</b> — <i>O God, save me by your name</i>. <i>Bĕshimĕkhā</i> (by your name — the divine name as a power-source for salvation; the name concentrates the identity and authority of the one named). <b>ûbigĕbûrātĕkhā tĕdînnênî</b> — <i>vindicate me by your strength</i>. <i>Gĕbûrāh</i> (strength, might — the military power of YHWH). <i>Dîn</i> (to judge, vindicate — to render a verdict in favor of the one pleading). The petition: salvation by divine name + vindication by divine strength = the complete rescue the Psalmist needs.</p>",
    "2": "<p><b>ʾĕlōhîm shĕmaʿ tĕphillātî</b> — <i>hear my prayer, O God</i>. <i>Shāmaʿ</i> (to hear, listen attentively — the first action required of the divine judge). <b>haʾăzînāh lĕʾimrê-phî</b> — <i>listen to what I am saying</i>. <i>ʾĀzan</i> (hiphil: to give ear — the attentive cupping of the ear to receive the petition). The double petition for divine attention before the situation is described.</p>",
    "3": "<p><b>kî zārîm qāmû ʿālay</b> — <i>for outsiders are threatening me</i>. <i>Zārîm</i> (strangers, foreigners, outsiders — those who do not belong to the covenant community; from zûr: to be a stranger). In the historical context the Ziphites were Judahites who betrayed David to Saul (1 Sam 23:19; 26:1) — they became functionally <i>zārîm</i> (strangers) by their betrayal, crossing from the covenant community to the enemy's side. <b>wĕʿārîṣîm biqqĕshû nafshî</b> — <i>violent men are hunting my life</i>. <i>ʿĀrîṣ</i> (violent, ruthless — one who uses force without restraint). <b>lōʾ śāmû ʾĕlōhîm lĕnegdām</b> — <i>they have no thought of God</i>. <i>Śîm ʾĕlōhîm lĕneged</i> (to set God before one — the interior orientation of the heart toward God; cf. Ps 16:8: <i>shiwwîtî YHWH lĕnegdî tāmîd</i>: I have set YHWH always before me). The betrayers do not have God in view — practical atheism as the root of betrayal, mirroring Ps 53:1.</p>",
    "4": "<p><b>hinnēh ʾĕlōhîm ʿōzēr lî</b> — <i>but God is my helper</i>. <i>Hinnēh</i> (behold — the particle of dramatic attention) + <i>ʿōzēr</i> (helper, one who gives aid — from ʿāzar: to help). The confident counter to the threat: God as active helper. <b>ʾădōnāy bĕsōmĕkhê nafshî</b> — <i>the Lord is the one who sustains my life</i>. <i>Sāmakh</i> (to support, sustain — the upholding of the life/soul). <i>Nafshî</i> (my soul/life — the full personal existence sustained by divine support).</p>",
    "5": "<p><b>yāshîb hārāʿ lĕshōrĕrāy</b> — <i>he will bring the evil back on my enemies</i>. <i>Shûb ʿāl</i> (hiphil: to make return upon — the divine return of the evil the enemies intended to the senders; the boomerang-justice of divine retribution). <b>baʾămittĕkhā haṣmîtēm</b> — <i>in your faithfulness, silence them</i>. <i>Ṣāmat</i> (to cut off, silence — the silencing of those who acted against the trusting one). <i>ʾĔmûnāh</i> (faithfulness) as the ground of the silencing — YHWH's faithfulness to his covenant is the basis for the petition.</p>",
    "6": "<p><b>binĕdābāh ʾezbĕḥāh lākh</b> — <i>with a freewill offering I will sacrifice to you</i>. <i>Nĕdābāh</i> (freewill offering — the voluntary sacrifice beyond what is required by law; offered purely from gratitude, not from obligation; from nādab: to volunteer). The highest form of sacrifice — the one that cannot be commanded because it must arise spontaneously from a grateful heart. <b>ʾôdeh shimĕkhā YHWH kî-ṭôb</b> — <i>I will give thanks to your name, LORD, for it is good</i>. The thanksgiving (<i>tôdāh</i>-type praise) to the divine name — echoing the theme of Ps 52:9 and Ps 50:14.</p>",
    "7": "<p><b>kî mikkol-ṣārāh hiṣṣîlānî</b> — <i>for he has rescued me from every distress</i>. The past-tense certainty: though the situation is still dangerous (the Ziphites are still a threat), the prayer expresses the confidence of completed rescue. The perfect tense (<i>hiṣṣîlānî</i>: he has rescued me) anticipates the divine action as already accomplished — the grammar of faith. <b>ûbĕʾōybay rāʾătāh ʿênî</b> — <i>and my eye has seen the downfall of my enemies</i>. <i>Rāʾāh ʿênî</i> (my eye has seen) — the testimony of personal witness to the divine vindication. The same confident vision as Ps 52:6 (the righteous see the wicked's fate) and Ps 54:7 closes the psalm with that same perspective: the trusting person's eye sees what the enemy plotted against them rebound on the enemy.</p>"
  }
}

def main():
    data = load_comm('mkt-original', 'psalms')
    merge_comm(data, NEW)
    save_comm('mkt-original', 'psalms', data)
    for ch in ['48', '49', '50', '51', '52', '53', '54']:
        vcount = len(data.get(ch, {}))
        print(f'  Ps {ch}: {vcount} verses')

if __name__ == '__main__':
    main()
