"""
Original Layer — 2 Chronicles chapters 35–36
Run: python3 scripts/zc-original-2chronicles-35-36.py

Ch35: Josiah's great Passover (greatest since Samuel); death at Megiddo.
Ch36: Four last kings; the Babylonian destruction; Cyrus decree —
      the final verses of the Hebrew Bible in its canonical order.
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

CHRON2_ORIGINAL_35_36 = {
  "35": {
    "1": "<p>Josiah celebrates the Passover to YHWH in Jerusalem — <em>wayyišḥaṭ happesaḥ bᵉʾarbāʿāh ʿāśār laḥōḏeš hārīʾšôn</em> — on the fourteenth of the first month. The precision of the date matches the Mosaic prescription exactly (Exod 12:6; Lev 23:5; Num 9:3). After all of Josiah&rsquo;s reform work — the discovery of the Law, the covenant renewal, the destruction of high places — the Passover is the covenant feast that seals the reform. The Passover re-enacted is the nation&rsquo;s confession that its identity as YHWH&rsquo;s people is grounded in the Exodus event.</p>",
    "2": "<p>Josiah stations the priests at their posts (<em>wayyaʿămiḏ hakḵōhănîm ʿal-mišmᵉrôtām</em>) and encourages them (<em>wayyḥazzēq</em> — strengthens/encourages) for the service of YHWH&rsquo;s house. The verb <em>ḥāzaq</em> (to strengthen) is the charge-to-Joshua word (Josh 1:6-7; Deut 31:7) — Josiah is commissioning the priests with the same urgency as the conquest commission. Priestly service is a form of spiritual warfare requiring the same courage.</p>",
    "3": "<p>Josiah speaks to the Levites who taught all Israel and who were holy to YHWH: <em>tᵉnû ʾet-ʾărôn haqqōḏeš babbayit ʾăšer bānāh Šᵉlōmōh ʾên-lāḵem māśāʾ baḵḵātēp</em> — &ldquo;Put the holy ark in the house that Solomon the son of David built. You need not carry it on your shoulders any more.&rdquo; The Levites&rsquo; ancient transport duty — carrying the ark on their shoulders during the wilderness (Num 7:9; 2 Chr 5:4) — is now permanently obsolete. The ark is in its permanent home; the Levites are freed for ministry to the people (<em>ʿiḇᵉḏû ʾet-YHWH ʾĕlōhêḵem wᵉʾet-ʿammô Yiśrāʾēl</em>).</p>",
    "4": "<p>Josiah commands the Levites to prepare themselves by their fathers&rsquo; houses, by their divisions, following the written instructions of David and Solomon. The dual appeal to David&rsquo;s <em>miktāḇ</em> (written order) and Solomon&rsquo;s <em>miktāḇ</em> (written document) establishes the documentary authority behind the liturgical organization. The Chronicler consistently grounds temple service in written, transmitted order — not improvised piety but the disciplined form that the fathers established.</p>",
    "5": "<p>The Levites are to stand in the holy place by the divisions of the fathers&rsquo; houses of your brothers the laypeople — a distribution of Levites throughout the congregation. <em>Uḥᵉlōqat bêt-āḇ</em> (a division of the father&rsquo;s house) — each lay division has a corresponding Levitical assignment, ensuring that no one in the gathered community is without priestly support during the Passover. The structured pastoral deployment reflects the Chronicler&rsquo;s vision of the whole people cared for by the whole Levitical corps.</p>",
    "6": "<p><em>ûšaḥăṭû happeseḥ wᵉhitqaḏḏᵉšû wᵉhāḵînû laʾăḥêḵem laʿăśôt kiḏᵉḇar YHWH bᵉyaḏ-Mōšeh</em> — &ldquo;And slaughter the Passover lamb and consecrate yourselves and prepare for your brothers to act according to the word of YHWH given through Moses.&rdquo; Three imperatives — slaughter, consecrate, prepare — structure the Levitical mission. The authority of Moses&rsquo; word (<em>kiḏᵉḇar YHWH bᵉyaḏ-Mōšeh</em>) frames the Passover as the fulfillment of Torah instruction, not creative innovation.</p>",
    "7": "<p>Josiah gives from his own property 30,000 young goats and kids and 3,000 bulls for the Passover offerings. The king&rsquo;s personal donation from his possessions — the royal <em>sᵉgullāh</em> — echoes David&rsquo;s personal donation for the temple (1 Chr 29:3-5). The reforming king who funds the people&rsquo;s worship from his own treasury models the principle that leadership gives first and most generously before calling others to give.</p>",
    "8": "<p>The princes and officials give willingly (<em>lᵉnᵉḏāḇāh</em>) — Hilkiah, Zechariah, Jehiel give 2,600 Passover offerings from the priests; Conaniah and his brothers give 5,000 Passover offerings among the Levites. The freewill giving of the leaders (<em>nᵉḏāḇāh</em>) echoes the tabernacle and temple-dedication offerings — the same vocabulary of voluntary generosity that the Chronicler uses for the highest expressions of covenant devotion.</p>",
    "9": "<p>Conaniah and Shemaiah and Nethanel his brothers, and Hashabiah and Jeiel and Jozabad, chiefs of the Levites, gave to the Levites for the Passover offerings 5,000 lambs and goats and 500 bulls. The sheer quantity of animals — overwhelming abundance beyond necessity — signals that this is not a minimal compliance Passover but a feast of extravagant covenant devotion. The abundance of the sacrifice mirrors the abundance of YHWH&rsquo;s original deliverance from Egypt.</p>",
    "10": "<p>The service is prepared (<em>wattikkôn hāʿăḇōḏāh</em>): the priests stand at their places, the Levites in their divisions according to the king&rsquo;s command. <em>Wattikkôn</em> (was established/prepared) is the key verb — the entire service infrastructure is in place before any offering is made. The Chronicler&rsquo;s ideal is a worship order that runs because it is properly structured, not because of last-minute scrambling.</p>",
    "11": "<p>The Passover animals are slaughtered; the priests sprinkle the blood (<em>wayyizrᵉqû hakḵōhănîm</em>) from their hand, and the Levites flay (<em>ûmapšîṭîm</em>) them. The technical division of labor — priests handle the blood (always a priestly prerogative, as blood is the life, Lev 17:11), Levites flay — is the precision of covenant liturgy. Every detail has its appointed handler; the system of accountability extends to each physical action in the sacrifice.</p>",
    "12": "<p>They set aside the burnt offerings to give them to the groupings of the laypeople by fathers&rsquo; houses, to offer to YHWH as it is written in the Book of Moses. The phrase <em>kakkātûb bᵉsēper Mōšeh</em> (as it is written in the Book of Moses) appears here and in v6 — the double reference grounds the entire Passover in textual authority. Josiah&rsquo;s great Passover is the king&rsquo;s obedience to the recovered Torah, whose authority is not royal decree but divine word through Moses.</p>",
    "13": "<p><em>wayyᵉḇaššᵉlû happesaḥ bāʾēš kammišpāṭ</em> — &ldquo;They roasted the Passover lamb with fire according to the rule.&rdquo; The fire-roasting (<em>bayyebalûšēl bāʾēš</em>) follows the Mosaic prescription exactly (Exod 12:8-9: &ldquo;roasted over fire&rdquo; — not boiled). The <em>kammišpāṭ</em> (according to the rule/ordinance) applies to the Passover; the other holy offerings (<em>qōḏāšîm</em>) they boil in pots and caldrons. The precision of fire-vs-boil reflects the Chronicler&rsquo;s concern for exact liturgical compliance.</p>",
    "14": "<p>Afterward the Levites prepare for themselves and for the priests, because the priests, the sons of Aaron, were busy until night offering the burnt offerings and fat portions. The Levites&rsquo; self-preparation comes last — they serve others first, eat after the community is served. The ethic of servant leadership embedded in the liturgical order: those who serve the service eat after those they serve. The Chronicler&rsquo;s ideal of Levitical ministry is other-centered before self-caring.</p>",
    "15": "<p>The singers, sons of Asaph, are at their station according to the commandment of David, and Asaph and Heman and Jeduthun the king&rsquo;s seer. The temple singers occupy their posts throughout the Passover — they do not rotate to help with the animal processing but maintain continuous song. The gatekeepers are at each gate. Neither singers nor gatekeepers leave their appointed stations: <em>kî-ʾaḥêhem halᵉwiyyim hēḵînû lāhem</em> — because their Levite brothers prepared for them.</p>",
    "16": "<p><em>wattikkôn kol-ʿăḇōḏat YHWH bayyôm hahûʾ</em> — &ldquo;So all the service of the LORD was prepared that day.&rdquo; The summary verdict: the entire liturgical system operated as designed. The word <em>kûn</em> (to be established/prepared) appears at v10 (preparations) and here (completion) — bookending the Passover execution. What was established at the beginning was realized at the end: ordered service, faithfully executed, becomes the completion of what it began.</p>",
    "17": "<p>The people of Israel who were present kept the Passover at that time and the Feast of Unleavened Bread for seven days. The full eight-day festival — Passover plus the week of Unleavened Bread — is observed completely. <em>Ûḥag hammaṣṣôt šiḇʿat yāmîm</em> — the seven days of the Feast of Unleavened Bread complete the festival unit that the Torah mandates (Exod 12:15-20; Lev 23:6-8). Josiah&rsquo;s Passover is not abbreviated or curtailed by administrative convenience.</p>",
    "18": "<p><em>wᵉlōʾ-naʿăśāh ḵappesaḥ hazzeh bᵉYiśrāʾēl mimê Šᵉmûʾēl hannāḇîʾ ûḵol malḵê Yiśrāʾēl lōʾ ʿāśû ḵappesaḥ kaʾăšer ʿāśāh Yōšiyyāhû</em> — &ldquo;No Passover like it had been kept in Israel since the days of Samuel the prophet. None of the kings of Israel had kept such a Passover as was kept by Josiah.&rdquo; The superlative is remarkable in its historical reach: back to Samuel, bypassing David and Solomon. The reference to Samuel (rather than Moses or Joshua) recalls that Samuel was the last judge who restored proper covenant worship before the monarchy — Josiah&rsquo;s Passover connects pre-monarchic covenant faithfulness to the final reforming king.</p>",
    "19": "<p>This Passover was kept in the eighteenth year of Josiah&rsquo;s reign. The year-marker connects this celebration to the discovery of the Law book (2 Chr 34:8) and Josiah&rsquo;s covenant renewal (34:31-33) — the Passover is the liturgical climax of the reform year. The internal chronological consistency is the Chronicler&rsquo;s way of showing that the discovery of Torah, the renewal of covenant, and the celebration of Passover are a single integrated event: hearing leads to committing leads to celebrating.</p>",
    "20": "<p>After all this, when Josiah had prepared the temple, Neco king of Egypt came up to fight at Carchemish on the Euphrates, and Josiah went out against him. The temporal marker <em>ʾaḥărê kol-zōʾt</em> (after all this) sets the Passover and the battle in stark contrast: the height of covenant celebration is immediately followed by Josiah&rsquo;s inexplicable military engagement. Carchemish is far from Judah&rsquo;s territory — Josiah has no strategic reason to engage Neco there; his motivation is never stated by the Chronicler.</p>",
    "21": "<p>Neco sends messengers to Josiah: <em>meh-lî wᵉlāḵ melek Yᵉhûḏāh lōʾ ʿāleḵā ʾattāh hayyôm kî ʾel-bêt milḥamtî</em> — &ldquo;What have I to do with you, king of Judah? I am not against you this day, but against the house with which I am at war. And God has commanded me to hurry. Cease opposing God, who is with me, lest he destroy you.&rdquo; The formula <em>mah-lî wᵉlāḵ</em> (what have I to do with you?) is a rebuff-formula in biblical Hebrew (Judg 11:12; 2 Sam 16:10; 1 Kgs 17:18). Neco claims divine authorization — and the Chronicler implies he speaks truth (v22: Josiah &ldquo;did not listen to the words of Neco from the mouth of God&rdquo;).</p>",
    "22": "<p><em>wᵉlōʾ hēsîḇ Yōšiyyāhû ʾet-pānāyw mimmennû wayyithappēś lᵉhillāḥēm bô wᵉlōʾ šāmaʿ ʾel-diḇrê Nᵉkôh mippî ʾĕlōhîm</em> — &ldquo;Josiah did not turn away from him, but disguised himself to fight with him. He did not listen to the words of Neco from the mouth of God.&rdquo; Two crucial terms: <em>wayyithappēś</em> (disguised himself) — the same verb used of Ahab at Ramoth-gilead (18:29), connecting Josiah&rsquo;s death to Ahab&rsquo;s in a tragic typological echo. And <em>mippî ʾĕlōhîm</em> (from the mouth of God) — the Chronicler&rsquo;s stunning verdict that Neco was YHWH&rsquo;s instrument, a divine word Josiah refused.</p>",
    "23": "<p>Archers shoot King Josiah — <em>wayyōrû hayōrîm lammelek Yōšiyyāhû</em> — and the king says to his servants: <em>haʿăbîrûnî kî hāḥōlatî mᵉʾōḏ</em> — &ldquo;Take me away, for I am badly wounded.&rdquo; The wounding at Megiddo with an arrow — as Ahab was wounded at Ramoth-gilead (18:33) — seals the parallel. The great reforming king dies as the apostate northern king died: arrow-wounded in battle, taken out of the chariot. The Chronicler does not moralize; he presents the parallel and trusts the reader to feel its weight.</p>",
    "24": "<p>Josiah&rsquo;s servants take him out of the chariot (<em>wayyaʿăbîrūhû min-hammerkaḇāh</em>), put him in the second chariot, bring him to Jerusalem — and he dies. He is buried in the tombs of his fathers. All Judah and Jerusalem mourned for Josiah (<em>wayyitʾabbᵉlû ʿālāyw kol-Yᵉhûḏāh wîrûšālaim</em>). The national mourning for the death of the greatest reforming king since Hezekiah is the Chronicler&rsquo;s measure of Josiah&rsquo;s stature: his death is felt as a national catastrophe, a collective wound.</p>",
    "25": "<p>Jeremiah also lamented (<em>wayyqônēn</em>) for Josiah, and all the singing men and singing women spoke of Josiah in their laments to this day — <em>wayyitᵉnûm lᵉḥōq ʿal-Yiśrāʾēl</em> — these were made a rule/statute in Israel and are written in the Laments. <em>Wayyqônēn</em> is the technical term for the lament-genre (the <em>qînāh</em>) — the same genre as the book of Lamentations. Jeremiah&rsquo;s lament for Josiah established the <em>qînāh</em> as a liturgical form; the lament that ends the reform era becomes the template for the laments that survive the exile.</p>",
    "26": "<p>The rest of the acts of Josiah, and his good deeds (<em>ḥăsādāyw</em> — his loyal acts), according to what is written in the Law of YHWH. <em>Ḥăsādāyw</em> — the Chronicler uses the covenant-love vocabulary (<em>ḥesed</em>) to characterize Josiah&rsquo;s royal deeds. The king whose deeds are <em>ḥesed</em>-acts — loyal covenant love expressed in reform and Passover — is being evaluated by the highest covenantal standard. His life is a <em>ḥesed</em>-life.</p>",
    "27": "<p>His acts, first and last, are written in the book of the kings of Israel and Judah. The dual source citation — a single work encompassing both kingdoms — is the Chronicler&rsquo;s bibliography for Josiah&rsquo;s reign. The unified source reflects the Chronicler&rsquo;s pan-Israelite perspective: Josiah&rsquo;s reforms extended to the north (34:6-7); his Passover included &ldquo;all Israel&rdquo; (35:3). The last reforming king of the Davidic line is recorded in the book of all Israel.</p>"
  },
  "36": {
    "1": "<p>The people of the land take Jehoahaz son of Josiah and make him king in Jerusalem in his father&rsquo;s place. <em>ʿAm hāʾāreṣ</em> (the people of the land) — the collective designation for the native Judahite population who bypass the normal succession to install Josiah&rsquo;s son (Jehoahaz was younger than his brother Jehoiakim, 2 Kgs 23:31, 36). Popular installation of a king — outside the usual succession — signals the political instability that will characterize the final decades. The Chronicler&rsquo;s four-king run begins with this popular but short-lived choice.</p>",
    "2": "<p>Jehoahaz was twenty-three years old when he began to reign, and he reigned three months in Jerusalem. The brevity — three months — is the Chronicler&rsquo;s measure of YHWH&rsquo;s judgment on an unworthy king. The short reigns of the last kings (Jehoahaz 3 months, Jehoiachin 3 months) bracket the slightly longer evil reigns of Jehoiakim (11 years) and Zedekiah (11 years), creating a structural symmetry: two brief bookends, two extended-evil middles.</p>",
    "3": "<p>The king of Egypt <em>wayyᵃsîrēhû bîrûšālaim</em> — deposed him at Jerusalem and imposed a tribute of 100 talents of silver and a talent of gold. Jehoahaz is removed not by Babylonian power (the coming threat) but by Egyptian — the old empire asserting control over the corridor between its territory and Mesopotamia. The tribute (<em>wayyitten ʿal-hāʾāreṣ ʿŏneš</em>) imposed on Judah is the economic mark of vassalage, the material consequence of covenant faithlessness.</p>",
    "4": "<p>Neco makes Jehoiakim, Jehoahaz&rsquo;s brother, king over Judah and Jerusalem, and takes Jehoahaz to Egypt. <em>Wayyaḥăpōḵ nᵉkô ʾet-šᵉmô</em> — Neco changes Jehoahaz&rsquo;s name (presumably to Shallum, his pre-throne name; the Chronicler mentions only the throne name). A foreign power renaming the king of Judah is the visible symbol of sovereignty transferred: the king is a vassal whose identity is shaped by his overlord.</p>",
    "5": "<p>Jehoiakim was twenty-five when he began to reign, and he reigned eleven years in Jerusalem. <em>Wayyaʿaś hārāʿ bᵉʿênê YHWH ʾĕlōhāyw</em> — he did evil in the eyes of YHWH his God. The Chronicler&rsquo;s verdict on Jehoiakim is compressed into the regnal formula without elaboration — his eleven years of evil are summarized in the same phrase used for the worst kings. What the Chronicler emphasizes is not the specific sins but the outcome: Nebuchadnezzar comes against him (v6).</p>",
    "6": "<p>Nebuchadnezzar king of Babylon comes up against Jehoiakim and binds him (<em>wayyᵃʾasrēhû bᵉnaḥuštatayim</em> — in bronze chains) to take him to Babylon. The bronze chains are the language of humiliation — the same instrument used on Manasseh (2 Chr 33:11) and later on Zedekiah (v13-implied; 2 Kgs 25:7). Nebuchadnezzar as YHWH&rsquo;s instrument of judgment appears here for the first time in Chronicles — the Babylonian king who will dominate the remainder of the chapter.</p>",
    "7": "<p>Nebuchadnezzar takes some of the vessels of YHWH&rsquo;s house to Babylon and puts them in his palace in Babylon. <em>ûmikkᵉlê bêt-YHWH</em> — from the vessels of the house of YHWH. The removal of temple vessels — the sacred objects that represent YHWH&rsquo;s presence among his people — is the beginning of the desecration that culminates in the full destruction of ch36:17-19. The progressive removal of vessels (vv7, 10, 18) maps the stages of divine withdrawal from the temple.</p>",
    "8": "<p>The rest of Jehoiakim&rsquo;s acts, the abominations he committed, and what was found against him, are written in the book of the kings of Israel and Judah. <em>Wᵉhannimṣāʾ ʿālāyw</em> — &ldquo;and what was found against him&rdquo; — a unique phrase suggesting a legal dossier of offenses. The Chronicler does not elaborate but signals that the record exists and is available. His son Jehoiachin reigns in his place.</p>",
    "9": "<p>Jehoiachin was eighteen years old when he began to reign (the MT; the LXX and 2 Kgs 24:8 say eight), and he reigned three months and ten days in Jerusalem. <em>Wayyaʿaś hārāʿ bᵉʿênê YHWH</em> — he did evil. The brevity of his reign (three months and ten days — one of the most precise short-reign records in Chronicles) signals that he is barely given time to establish himself before the Babylonian judgment falls.</p>",
    "10": "<p>At the turn of the year, Nebuchadnezzar sends and brings Jehoiachin to Babylon, with the precious vessels of YHWH&rsquo;s house. <em>Wayyaʿălēhû bāḇelāh ʿim kᵉlê ḥemḏat bêt-YHWH</em> — &ldquo;and brought him to Babylon with the precious things of the house of YHWH.&rdquo; <em>Kᵉlê ḥemḏat</em> = vessels of desire/preciousness — the choicest temple objects. With each king&rsquo;s fall another tranche of temple vessels leaves Jerusalem: the sacred is being drained from the holy city. Zedekiah, Jehoiachin&rsquo;s brother, is made king.</p>",
    "11": "<p>Zedekiah was twenty-one years old when he began to reign, and he reigned eleven years in Jerusalem. Zedekiah (<em>Ṣiḏqiyyāhû</em> — &ldquo;YHWH is my righteousness&rdquo;) is given a name that his reign fails to embody. The irony of the name echoes throughout the fall narrative: the king whose name claims YHWH&rsquo;s righteousness as his own is precisely the king whose rebellion against YHWH&rsquo;s prophets occasions the final judgment.</p>",
    "12": "<p><em>Wayyaʿaś hārāʿ bᵉʿênê YHWH ʾĕlōhāyw wᵉlōʾ kānaʿ millipnê Yirmᵉyāhû hannāḇîʾ mippî YHWH</em> — &ldquo;He did evil in the sight of YHWH his God. He did not humble himself (<em>kānaʿ</em>) before Jeremiah the prophet, who spoke from the mouth of YHWH.&rdquo; <em>Kānaʿ</em> (to humble/submit) is the Chronicler&rsquo;s key word for the covenantal posture that averts judgment (2 Chr 7:14; 12:6, 7, 12; 30:11; 33:12, 19, 23; 34:27). Every king who <em>kānaʿ</em> received mercy; Zedekiah&rsquo;s refusal to <em>kānaʿ</em> seals the exile.</p>",
    "13": "<p><em>wayyašqē ʾet-ʿarᵉpô wayyᵃʾammēṣ ʾet-libbō mišûḇ ʾel-YHWH ʾĕlōhê Yiśrāʾēl</em> — &ldquo;He stiffened his neck and hardened his heart against turning (<em>mišûḇ</em>) to YHWH the God of Israel.&rdquo; Two idioms of obstinacy: <em>qāšāh ʿōrep</em> (stiffened neck — the classic phrase from Exod 32:9; Deut 9:6; Jer 7:26) and <em>ʾāmaṣ lēḇāḇ</em> (hardened heart — an unusual form; normally <em>ḥāzaq</em> is used for hardening). He also rebels against Nebuchadnezzar who had made him swear by God (<em>ʾăšer hišbîʿô bēʾlōhîm</em>) — oath-breaking compounds covenant unfaithfulness.</p>",
    "14": "<p><em>gam kol-śārê hakḵōhănîm wᵉhāʿām hirḇû limaʿôl maʿal kᵉḵōl tôʿᵃḇôt haggôyim</em> — &ldquo;All the leading priests and the people likewise were exceedingly unfaithful (<em>hirḇû limaʿôl maʿal</em>), following all the abominations of the nations.&rdquo; <em>Maʿal</em> — the Chronicler&rsquo;s signature word for covenant treachery (unfaithfulness, 29x in Chronicles) — here reaches its intensified form: <em>hirḇû limaʿôl</em> (multiplied unfaithfulness), spread from king to priests to people. The contamination is total; the judgment must be total.</p>",
    "15": "<p><em>wᵉYHWH ʾĕlōhê ʾăḇōtêhem šālaḥ ʾălêhem bᵉyaḏ-malʾākāyw hašḵēm wᵉšālôaḥ kî-ḥāmal ʿal-ʿammô wᵉʿal-mᵉʿônô</em> — &ldquo;The LORD, the God of their fathers, sent persistently to them by his messengers, because he had compassion (<em>ḥāmal</em>) on his people and on his dwelling place.&rdquo; <em>Hašḵēm wᵉšālôaḥ</em> (lit. rising early and sending) is the idiom from Jeremiah (7:25; 25:4; 26:5; 29:19; 35:15; 44:4) for persistent prophetic outreach. The prophets are sent by divine compassion (<em>ḥāmal</em> — a tender, protective love) — YHWH&rsquo;s sending is not mechanical judgment but the last acts of love before judgment falls.</p>",
    "16": "<p><em>wᵉhēm hayu maʿălîlîm bᵉmalʾăḵê hāʾĕlōhîm ûḇôzîm dᵉḇārāyw ûmitōlᵉlîm binᵉḇîʾāyw ʿaḏ ʿălôt ḥamat-YHWH bᵉʿammô ʿaḏ lēʾên marpēʾ</em> — &ldquo;But they kept mocking (<em>maʿălîlîm</em>) the messengers of God, despising (<em>ḇôzîm</em>) his words and scoffing (<em>mōtîlîm</em>) at his prophets, until the wrath of the LORD rose against his people, until there was no remedy (<em>ʿaḏ lēʾên marpēʾ</em>).&rdquo; Three verbs of prophetic rejection (mock, despise, scoff) build to the terminal diagnosis: <em>lēʾên marpēʾ</em> — no healing, no remedy. The same root as <em>rāpāʾ</em> (to heal) negated: beyond healing. The patient has refused every treatment; the physician can only stand back.</p>",
    "17": "<p>Therefore God brings up against them the king of the Chaldeans — <em>wayyaʿal ʿălêhem ʾet-melek Kaśdiyyim</em>. Nebuchadnezzar kills their young men with the sword in the temple sanctuary, has no compassion on young man or virgin, old man or aged — <em>hakkōl nātan bᵉyāḏô</em> — God gives all into his hand. The destruction is comprehensive: no demographic exemption, no mercy. YHWH himself gives his people into Nebuchadnezzar&rsquo;s hand. The same YHWH who compassionately sent prophets (v15) now delivers his people to the sword when the prophets are rejected.</p>",
    "18": "<p>All the vessels of God&rsquo;s house, great and small, and the treasures of YHWH&rsquo;s house, and the treasures of the king and his princes — Nebuchadnezzar brings all to Babylon. <em>ʾet kol kᵉlê bêt-hāʾĕlōhîm hagᵉḏōlîm wᵉhaqqᵉṭannîm</em> — great and small, without exception. The complete removal of sacred objects completes the process begun in vv7 and 10: the temple is physically stripped. The vessels that Cyrus will later restore (Ezra 1:7-11) are the link between exile and restoration — physical objects that carry the memory of YHWH&rsquo;s presence through the darkness.</p>",
    "19": "<p>They burn the house of God, break down the wall of Jerusalem, burn all its palaces with fire, and destroy all its precious vessels. <em>Wayyiśrᵉpû ʾet-bêt hāʾĕlōhîm wayyîṭṭᵉšû ʾet-ḥômat Yᵉrûšālaim wᵉḵol-ʾarᵉmᵉnôtêhā śārᵉpû ḇāʾēš</em>. Four destructions: temple burned, wall broken, palaces burned, vessels destroyed. The comprehensive destruction — no structure left standing, no object left intact — is the Chronicler&rsquo;s most concentrated horror: the place where YHWH&rsquo;s glory dwelt, where David planned and Solomon built and Hezekiah and Josiah reformed, is ash.</p>",
    "20": "<p>Those who escape the sword go into exile in Babylon, where they become servants to Nebuchadnezzar and his sons until the establishment of the kingdom of Persia. <em>Wayyiglû lāḇāḇlāh</em> — they were exiled to Babylon. The remnant that survives the sword (sword is the first covenant curse; exile is the ultimate) serves (<em>wayᵃhîyû-lô laʿăḇāḏîm</em>) the Babylonian empire. The servants of YHWH become the servants of the king of Babylon — the covenant consequence for a people who refused to serve their true Lord.</p>",
    "21": "<p><em>lᵉmalōʾ dᵉḇar-YHWH bᵉpî Yirmᵉyāhû ʿaḏ-rāṣᵉtāh hāʾāreṣ ʾet-šabbᵉtōtêhā kol-yᵉmê hašammāh šāḇātāh lᵉmalōʾ šiḇʿîm šānāh</em> — &ldquo;to fulfill the word of the LORD by the mouth of Jeremiah, until the land had enjoyed its Sabbaths. All the days that it lay desolate it kept Sabbath, to fulfill seventy years.&rdquo; <em>Rāṣāh ʾet-šabbᵉtōtêhā</em> — the land &ldquo;paid off/enjoyed&rdquo; its Sabbath years. The verb <em>rāṣāh</em> (to be pleased with, to accept, to repay a debt) is used for the satisfaction of a creditor. Lev 26:34-35 promised this enforced Sabbath; the land&rsquo;s forced rest for seventy years is the fulfillment of both Lev 26 and Jer 25:11; 29:10.</p>",
    "22": "<p><em>ûḇišnat ʾaḥat lᵉKōreš melek Pāras liḵlôt dᵉḇar-YHWH mippî Yirmᵉyāhû hēʿîr YHWH ʾet-rûaḥ Kōreš melek Pāras</em> — &ldquo;Now in the first year of Cyrus king of Persia, that the word of the LORD by the mouth of Jeremiah might be fulfilled, the LORD stirred up (<em>hēʿîr</em>) the spirit of Cyrus king of Persia.&rdquo; <em>Hēʿîr ʾet-rûaḥ</em> (stirred up the spirit) — the divine stirring of a human agent&rsquo;s spirit to accomplish YHWH&rsquo;s purpose (Hag 1:14; Ezra 1:1; Isa 45:13). As YHWH stirred the spirit of the Babylonian king to punish (v17), he now stirs the spirit of the Persian king to restore. The God of the exile is also the God of the return.</p>",
    "23": "<p><em>kōh-ʾāmar Kōreš melek Pāras kōl mamlᵉḵôt hāʾāreṣ nātan lî YHWH ʾĕlōhê haššāmayim wᵉhûʾ-pāqaḏ ʿālay liḇnôt-lô ḇayit bîrûšālaim... mî-ḇāḵem mikkol-ʿammô YHWH ʾĕlōhāyw ʿimmô wᵉyaʿal</em> — &ldquo;Thus says Cyrus king of Persia: The LORD, the God of heaven, has given me all the kingdoms of the earth, and he has charged me to build him a house at Jerusalem, which is in Judah. Whoever is among you of all his people, may the LORD his God be with him. Let him go up (<em>wᵉyaʿal</em>).&rdquo; The final word of the Hebrew Bible in its canonical order is <em>wᵉyaʿal</em> — &ldquo;let him go up.&rdquo; The Hebrew canon ends not with a period but with an open imperative of ascent: the invitation has been given; the response awaits; the story is not yet finished. The canon closes mid-sentence in divine invitation.</p>"
  }
}

def main():
    existing = load_comm('mkt-original', '2chronicles')
    merge_comm(existing, CHRON2_ORIGINAL_35_36)
    save_comm('mkt-original', '2chronicles', existing)
    print('2 Chronicles 35-36 original layer written.')

if __name__ == '__main__':
    main()
