"""
MKT Original — Matthew chapters 21–22
Output: data/commentary/mkt-original/matthew.json (adds ch21-22)
"""
import json, pathlib
ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

# INTENT: Per-verse Greek lexical commentary for Matthew 21-22; covers Triumphal
#   Entry through the Controversy Dialogues. Strictly Greek vocabulary/syntax/aspect.
# CHANGE? If verse keys change in data/interlinear/matthew.json, update dict keys here.
# VERIFY: Run script; confirm "wrote data/commentary/mkt-original/matthew.json".
#   Then check ch21/22 keys match interlinear counts (46/46).

NEW_DATA = {
  "21": {
    "1": "<p><strong>ēggisan eis Hierosolyma</strong> — <em>drew near to Jerusalem</em> — <em>Eggizō</em> (to draw near) marks the beginning of the Passion Week narrative. Bethphage (<em>Bēthphagē</em> = house of unripe figs in Aramaic) is on the eastern slope of the Mount of Olives; the phrase <em>tote Iēsous apesteilen</em> (then Jesus sent) opens the deliberate arrangement of the entry.</p>",
    "2": "<p><strong>onon dedemenen kai pōlon met\' autēs</strong> — <em>a donkey tied and a colt with her</em> — Matthew uniquely has two animals (cf. Mark/Luke: one). The <em>dedemenen</em> (perfect passive participle: having been tied) and <em>lysantes</em> (loosing, aorist) echo a prophetic staging. The <em>ho kyrios autōn chreian echei</em> (the Lord has need of them) phrase uses <em>chreian echei</em> = has need, an expression of genuine requirement.</p>",
    "3": "<p><strong>ho kyrios autōn chreian echei</strong> — <em>the Lord has need of them</em> — The absolute use of <em>ho kyrios</em> (the Lord) without further specification echoes LXX divine-address usage; the disciples apply it directly to Jesus. <em>Euthys de apostellei autous</em> (and immediately he will send them) — the future <em>apostellei</em> implies a prearranged signal.</p>",
    "4": "<p><strong>hina plērōthē to rhēthen dia tou prophētou</strong> — <em>in order that what was spoken through the prophet might be fulfilled</em> — <em>Hina plērōthē</em> + aorist passive subjunctive is Matthew\xe2\x80\x99s standard fulfillment formula. The citation combines Isa 62:11 (LXX) and Zech 9:9, both messianic texts; Matthew\xe2\x80\x99s conflation of sources is deliberate editorial work.</p>",
    "5": "<p><strong>idou ho basileus sou erchetai soi prays</strong> — <em>behold your king comes to you meek</em> — From Zech 9:9 LXX. <em>Prays</em> (meek, gentle) recurs from 11:29 (Jesus\xe2\x80\x99 self-description) and 5:5 (Beatitudes). <em>Epibebēkōs epi onon kai epi pōlon</em> (mounted on a donkey and on a colt) — the Hebrew parallelism of Zech 9:9 (synonymous: one animal) is taken as two animals by Matthew\xe2\x80\x99s literal reading.</p>",
    "6": "<p><strong>poiēsantes kathōs synetaxen autois ho Iēsous</strong> — <em>having done as Jesus directed them</em> — <em>Syntassō</em> (to arrange, direct, command) aorist; the disciples\xe2\x80\x99 obedience is exact and immediate. The aorist participle <em>poiēsantes</em> precedes the main verb, emphasizing compliance before arrival.</p>",
    "7": "<p><strong>epethēkan ep\' autōn ta himatia</strong> — <em>they put the garments on them</em> — Draping garments over the animals and spreading them on the road echoes the royal acclamation of Jehu in 2 Kgs 9:13 (LXX: <em>elabon hekastos to himation autou kai ethēkan</em>). <em>Ekathisen epanō autōn</em> (he sat upon them) — ambiguous plural; likely refers to the garments, not both animals.</p>",
    "8": "<p><strong>ho de pleistos ochlos estrōsan</strong> — <em>the very large crowd spread</em> — <em>Pleistos</em> is the superlative of <em>polys</em>: the largest/very great crowd. <em>Estrōsan</em> (spread, strewed) their garments on the road; others cut <em>kladous apo tōn dendrōn</em> (branches from the trees) — not specifically palm branches as in John 12:13; Matthew\xe2\x80\x99s <em>kladoi</em> = leafy branches generically.</p>",
    "9": "<p><strong>hōsanna tō huiō Dauid</strong> — <em>Hosanna to the Son of David</em> — <em>Hōsanna</em> is the Greek transliteration of Heb. <em>hōšîaʿ-nāʾ</em> (save, please! / O save!) from Ps 118:25-26. By Jesus\xe2\x80\x99 day it had become an acclamation of royal welcome, having lost its strict imperative force. <em>Eulogēmenos ho erchomenos en onomati kyriou</em> quotes Ps 118:26 LXX verbatim; <em>ho erchomenos</em> (the coming one) is a recognized Messianic designation (cf. 11:3).</p>",
    "10": "<p><strong>eseisthē pasa hē polis</strong> — <em>all the city was shaken</em> — <em>Seiō</em> (to shake, quake) is used for earthquake (27:51; 28:4); its application to the city\xe2\x80\x99s reaction creates an eschatological resonance. <em>Tis estin houtos</em> (who is this?) — the city\xe2\x80\x99s question mirrors the sea-stilling disciples\xe2\x80\x99 question (8:27); Jerusalem does not recognize its king.</p>",
    "11": "<p><strong>houtos estin ho prophētēs Iēsous ho apo Nazareth tēs Galilaias</strong> — <em>this is the prophet Jesus from Nazareth of Galilee</em> — The crowd identifies Jesus as <em>ho prophētēs</em> (the prophet), recalling the eschatological prophet of Deut 18:15-18. The full geographical designation (<em>ho apo Nazareth tēs Galilaias</em>) marks regional identity; Jerusalem crowds may intend a slight by the Galilean label.</p>",
    "12": "<p><strong>exebalen pantas tous pōlountas kai agorazontas</strong> — <em>he drove out all those selling and buying</em> — <em>Ekballō</em> (to throw out, expel) is the exorcism verb; its use here frames the temple cleansing as analogous to casting out an unclean presence. <em>Katestrepsen tas trapezas</em> (overturned the tables) — <em>katastrephō</em> = to turn over completely, overturn.</p>",
    "13": "<p><strong>ho oikos mou oikos proseuchēs klēthēsetai</strong> — <em>my house shall be called a house of prayer</em> — Quoting Isa 56:7 LXX. <em>Klēthēsetai</em> (shall be called) future passive = this is its established divine designation. <em>Hymeis de auton poieite spēlaion lēstōn</em> (but you are making it a den of robbers) — quotes Jer 7:11 LXX. <em>Spēlaion</em> (cave, den) + <em>lēstōn</em> (robbers, bandits — Josephus uses <em>lēstēs</em> for violent insurgents) is a jarring contrast to <em>oikos proseuchēs</em>.</p>",
    "14": "<p><strong>proseēlthan autō typhloi kai chōloi</strong> — <em>the blind and the lame came to him</em> — The temple healing follows immediately on the cleansing; the restored temple becomes a place of healing. <em>Typhloi</em> (blind) and <em>chōloi</em> (lame) are those excluded from the temple precincts in Lev 21:18 and 2 Sam 5:8; Jesus reverses the exclusion.</p>",
    "15": "<p><strong>ta thaumasia ha epoiēsen</strong> — <em>the wonderful things he did</em> — <em>Thaumasia</em> (wonderful, marvelous things) is the LXX word for God\xe2\x80\x99s mighty acts (Ps 71:17 LXX). The chief priests\xe2\x80\x99 and scribes\xe2\x80\x99 indignation at <em>hōsanna tō huiō Dauid</em> from children reveals their opposition to the Davidic Messianic claim.</p>",
    "16": "<p><strong>ek stomatos nēpiōn kai thēlazontōn katērtisō ainon</strong> — <em>from the mouth of infants and nursing ones you have prepared praise</em> — Quoting Ps 8:3 LXX (MT: <em>ʿoz</em> = strength/power; LXX: <em>ainon</em> = praise — Matthew follows LXX). Jesus applies this to the children\xe2\x80\x99s cry; the infant praise vindicates the legitimacy of the acclamation the authorities reject.</p>",
    "17": "<p><strong>exelthen exō tēs poleōs eis Bēthanian</strong> — <em>he went out of the city to Bethany</em> — Jesus\xe2\x80\x99 nightly withdrawal to Bethany (cf. 21:18) is a structural feature of Passion Week; he does not lodge in Jerusalem. <em>Ēulisthē ekei</em> (spent the night there) — <em>aulizomai</em> = to spend the night outdoors or in a courtyard, appropriate to Passover practices.</p>",
    "18": "<p><strong>prōï de epanagōn eis tēn polin epeinase</strong> — <em>returning early to the city he was hungry</em> — <em>Prōï</em> (early) and <em>epanagōn</em> (returning, aorist participle) frame the fig tree episode on the morning after the entry. <em>Epeinase</em> (was hungry) — the aorist describes a state; Matthew\xe2\x80\x99s Jesus experiences genuine physical hunger, affirming full humanity.</p>",
    "19": "<p><strong>ouden heuron en autē ei mē phylla monon</strong> — <em>he found nothing in it except leaves only</em> — <em>Ei mē phylla monon</em> (except leaves only) — the <em>monon</em> (only) is emphatic. Fig trees in Palestine develop fruit buds before full foliage; leaves without any fruit signal abnormality. <em>Exēranthē parachrēma hē sykē</em> (the fig tree withered immediately) — <em>parachrēma</em> = immediately, at once; Matthew compresses Mark\xe2\x80\x99s two-day sequence into one.</p>",
    "20": "<p><strong>pōs parachrēma exēranthē hē sykē</strong> — <em>how did the fig tree wither immediately?</em> — The disciples\xe2\x80\x99 amazement focuses on the instantaneous effect (<em>parachrēma</em>). <em>Exēranthē</em> (aorist passive of <em>xērainō</em> = to dry up, wither) is the same verb used for the withering of seed sown on rocky ground (13:6).</p>",
    "21": "<p><strong>ean echēte pistin kai mē diakrthēte</strong> — <em>if you have faith and do not doubt</em> — <em>Diakrinō</em> in the passive or middle = to doubt, be divided (in judgment); literally to separate, discriminate. <em>Ou monon to tēs sykēs poiēsete</em> (not only the fig tree thing will you do) — the <em>to tēs sykēs</em> (the fig-tree thing) is a demonstrative articular phrase referring to the specific act. <em>Tō̧ orei toutō̧</em> (to this mountain) = presumably the Mount of Olives.</p>",
    "22": "<p><strong>panta hosa an aitēsēte en tē proseuchē pisteuontes lēmpsesthe</strong> — <em>all things whatever you ask in prayer believing you will receive</em> — <em>Pisteuontes</em> (present active participle: believing) is the condition; the promise is governed by faith-in-prayer, not raw petition. <em>Lēmpsesthe</em> future indicative = you will receive — the confidence of promise, not mere possibility.</p>",
    "23": "<p><strong>en poiā exousiā tauta poieis</strong> — <em>by what authority do you do these things?</em> — <em>Exousia</em> (authority, from <em>exesti</em> = it is permitted) was the central question in Jewish religious politics: who had authorized teaching, healing, and temple action? <em>Kai tis soi edōken tēn exousian tautēn</em> (and who gave you this authority?) — both the basis and source of authority are challenged.</p>",
    "24": "<p><strong>erōtēsō hymas kagō logon hena</strong> — <em>I will ask you also one word</em> — Jesus\xe2\x80\x99 counter-question (<em>logon hena</em> = one question/matter) employs the rabbinic debate technique of silencing an adversary with a counter-dilemma. <em>Hon ean eipēte moi kagō hymin erō</em> (which if you tell me I will also tell you) — the conditional is a formal debate commitment.</p>",
    "25": "<p><strong>to baptisma to Iōannou pothen ēn</strong> — <em>the baptism of John, from where was it?</em> — <em>Ex ouranou ē ex anthrōpōn</em> (from heaven or from humans) — the binary forces recognition: divine authorization or human invention. <em>Ex ouranou</em> is the circumlocution for divine origin common in Jewish speech to avoid the divine name.</p>",
    "26": "<p><strong>pantes gar hōs prophētēn echousin ton Iōannēn</strong> — <em>for all hold John as a prophet</em> — The authorities\xe2\x80\x99 reasoning is transparent: political calculation rather than theological judgment. <em>Phoboumenoi ton ochlon</em> (fearing the crowd) governs their answer; this reveals that their authority rests on crowd management, not divine truth.</p>",
    "27": "<p><strong>oude egō legō hymin en poiā exousiā tauta poiō</strong> — <em>neither do I tell you by what authority I do these things</em> — The refusal is not evasion but a declaration: their disqualification from receiving the answer. <em>Ouk oidamen</em> (we do not know) was dishonest — they had deliberated the answer; their own dishonesty disqualifies them.</p>",
    "28": "<p><strong>anthrōpos eichen tekna dyo</strong> — <em>a man had two children</em> — The parable of the two sons sets up a direct application to the authorities and toll collectors. <em>Teknon</em> (child) rather than <em>huios</em> (son) emphasizes the paternal relationship. <em>Hypage sēmeron ergazou en tō̧ ampelōni</em> (go today, work in the vineyard) — the <em>sēmeron</em> (today) stresses urgency.</p>",
    "29": "<p><strong>ho de apokritheis eipen ou thelō</strong> — <em>he answered and said: I do not wish to</em> — The direct refusal <em>ou thelō</em> (I do not wish) is then reversed: <em>hysteron metamelētheis apēlthen</em> (later having changed his mind he went). <em>Metamélomai</em> (to regret, have a change of feeling) differs from <em>metanoeō</em> (repentance from sin); it is emotional reversal leading to action.</p>",
    "30": "<p><strong>ho de apokritheis eipen egō kyrie</strong> — <em>he answered and said: I, lord</em> — The second son\xe2\x80\x99s instant formal compliance (<em>egō kyrie</em> = I, sir/lord) and then failure to act exposes the hypocrisy. <em>Ouk apēlthen</em> (did not go) — the aorist negation is definitive; he never went.</p>",
    "31": "<p><strong>hoi telōnai kai hai pornai proagousin hymas eis tēn basileian</strong> — <em>the tax collectors and prostitutes go before you into the kingdom</em> — <em>Proagousin</em> (lead the way, go before) is a shocking reversal: those considered most impure enter first. <em>Telōnai</em> (toll collectors) and <em>pornai</em> (prostitutes) represent religious and moral outsiders respectively — both responded to John\xe2\x80\x99s call.</p>",
    "32": "<p><strong>ēlthen gar Iōannēs pros hymas en hodō dikaiosynēs</strong> — <em>for John came to you in the way of righteousness</em> — <em>Hodos dikaiosynēs</em> (way/path of righteousness) is a Hebrew idiom (derek ṣedeq) for righteous conduct and teaching. <em>Ou metemelēthēte hysteron</em> (you did not afterwards change your mind) — the same verb <em>metamélomai</em> from v.29; the authorities lack even the emotional reversal the first son displayed.</p>",
    "33": "<p><strong>allēn parabolēn akousate</strong> — <em>hear another parable</em> — The Wicked Tenants parable draws on Isa 5:1-7 (Song of the Vineyard); <em>phragmon</em> (fence/hedge), <em>lēnon</em> (winepress), <em>pyrgon</em> (tower) all appear in Isaiah\xe2\x80\x99s vineyard description, making the allusion deliberate and clear to any biblically literate hearer.</p>",
    "34": "<p><strong>apesteilen tous doulous autou pros tous geōrgous</strong> — <em>he sent his servants to the tenants</em> — <em>Geōrgos</em> (farmer, vine-dresser, tenant) = one who works the earth. <em>Labein tous karpous autou</em> (to receive his fruits) — the owner\xe2\x80\x99s expectation is a share of the produce, the standard lease arrangement. The servants represent the prophets.</p>",
    "35": "<p><strong>labontes hoi geōrgoi tous doulous autou</strong> — <em>the tenants having seized his servants</em> — Three fates: <em>edeiran</em> (flogged/beat), <em>apektenan</em> (killed), <em>elithobolēsan</em> (stoned) — the escalating violence against prophets mirrors Israel\xe2\x80\x99s historical rejection of prophets (cf. Neh 9:26; Heb 11:36-37).</p>",
    "36": "<p><strong>apesteilen allous doulous pleionas tōn prōtōn</strong> — <em>he sent other servants more than the first</em> — <em>Pleionas</em> (more in number) — the second delegation is larger; the same treatment ensues. Matthew\xe2\x80\x99s two waves of servants (vs. Mark\xe2\x80\x99s individual sequence) emphasizes the pattern of rejection.</p>",
    "37": "<p><strong>hysteron de apesteilen pros autous ton huion autou</strong> — <em>last of all he sent his son to them</em> — <em>Hysteron</em> (finally, last of all) marks the climax. <em>Entrapēsontai</em> (they will respect, be shamed before) uses <em>entrepō</em> = to turn toward with respect; the owner\xe2\x80\x99s reasoning is generous but fatally optimistic — the dramatic irony is complete.</p>",
    "38": "<p><strong>deute apokteinōmen auton kai schōmen tēn klēronomian autou</strong> — <em>come let us kill him and possess his inheritance</em> — <em>Deute</em> (come!) is an imperative of invitation/incitement. <em>Klēronomia</em> (inheritance) = the estate that would pass to the heir; killing the heir before the owner\xe2\x80\x99s death was a known legal strategy in some Roman contexts. The tenants\xe2\x80\x99 logic reveals deliberate murderous calculation.</p>",
    "39": "<p><strong>ekballon exō tou ampelōnos apekteinan</strong> — <em>having thrown him outside the vineyard they killed him</em> — The sequence <em>ekballon exō</em> (throwing outside) before killing mirrors Jesus\xe2\x80\x99 own fate: he is taken outside Jerusalem (exō tēs pylēs, Heb 13:12) before crucifixion. Matthew places this in the same order as the historical Passion.</p>",
    "40": "<p><strong>hotan oun elthē ho kyrios tou ampelōnos</strong> — <em>when therefore the lord of the vineyard comes</em> — Jesus turns the parable into a question, forcing the authorities to pronounce their own judgment. <em>Tí poiēsei toîs geōrgois ekeinois</em> (what will he do to those tenants?) — the future deliberative implicates them as judges of their own case.</p>",
    "41": "<p><strong>kakous kakōs apolesei autous</strong> — <em>evildoers he will utterly destroy</em> — The figure <em>kakous kakōs</em> is a Greek wordplay (kakos/kakōs: evil ones evilly) constituting a paronomasia: evil men will meet an evil end. <em>Ekdōsetai ton ampelōna allois geōrgois</em> (he will lease the vineyard to other tenants) — the authorities unwittingly pronounce the transfer of the covenant community to others.</p>",
    "42": "<p><strong>lithon hon apedokimasan hoi oikodomountes</strong> — <em>the stone which the builders rejected</em> — Ps 118:22-23 LXX cited verbatim. <em>Apodokimazō</em> (to reject after examination, declare unfit) is a technical term from construction; the builders\xe2\x80\x99 professional judgment is overturned by God. <em>Houtos egenēthē eis kephalēn gōnias</em> (this became the head of the corner) — <em>kephalē gōnias</em> = cornerstone or capstone (keystone); the foundational or final stone that holds the structure together.</p>",
    "43": "<p><strong>arthēsetai aph\' hymōn hē basileia tou theou</strong> — <em>the kingdom of God will be taken from you</em> — <em>Arthēsetai</em> (future passive of <em>airō</em> = to take up, remove) is a decisive eschatological statement. <em>Kai dothēsetai ethnei poiounti tous karpous autēs</em> (and given to a nation producing its fruits) — <em>ethnos</em> here likely refers not to Gentiles specifically but to the reconstituted people of God who bear kingdom fruit.</p>",
    "44": "<p><strong>ho pesōn epi ton lithon touton synthlasthēsetai</strong> — <em>the one falling on this stone will be broken to pieces</em> — <em>Synthlaomai</em> (to shatter, crush to pieces) and <em>likmēsei auton</em> (it will grind him to powder) — <em>likmáō</em> = to winnow, scatter; LXX uses it for divine judgment-scattering. The two images (fall on stone = shattered; stone falls on you = pulverized) both end in destruction; the stone is inescapable in either direction.</p>",
    "45": "<p><strong>egnōsan hoti peri autōn legei</strong> — <em>they knew that he was speaking about them</em> — <em>Egnōsan</em> (aorist of <em>ginōskō</em>) — the recognition is complete; the application of the parable to themselves is understood. The perception drives their desire to seize him rather than repentance.</p>",
    "46": "<p><strong>kai zētountes auton kratēsai ephobēthēsan tous ochlous</strong> — <em>seeking to seize him they feared the crowds</em> — <em>Kratēsai</em> (to seize, arrest) aorist infinitive; <em>ephobēthēsan</em> (feared) governed by crowd support for Jesus. <em>Hoti eis prophētēn auton eichon</em> (because they held him as a prophet) — the same identification as 21:11; the popular perception protects Jesus from immediate arrest.</p>"
  },
  "22": {
    "1": "<p><strong>apokritheis ho Iēsous palin eipen</strong> — <em>Jesus answering again spoke</em> — <em>Apokritheis</em> (answering) even without a preceding question is a Semitism inherited from LXX (<em>wayyaʿan</em>); it introduces a new discourse. <em>Palin</em> (again) links this parable directly to the preceding sequence.</p>",
    "2": "<p><strong>hōmoiōthē hē basileia tōn ouranōn anthrōpō̧ basilei</strong> — <em>the kingdom of heaven was likened to a king</em> — The Wedding Banquet parable (cf. Luke 14:15-24 — a different version). <em>Hostis epoiēsen gamous tō̧ huiō̧ autou</em> (who made a wedding feast for his son) — <em>gamos</em> (wedding, wedding feast) is the central image; the singular and plural forms both occur in vv. 2-12.</p>",
    "3": "<p><strong>apesteilen tous doulous autou kalesai tous keklēmenous</strong> — <em>he sent his servants to call those who had been invited</em> — <em>Tous keklēmenous</em> (the having-been-called, perfect passive participle) — those pre-invited; the initial invitation is assumed. <em>Kai ouk ēthelon elthein</em> (and they were not willing to come) — the imperfect <em>ēthelon</em> = ongoing unwillingness, sustained refusal.</p>",
    "4": "<p><strong>ta sitista mou etoimasin</strong> — <em>my fatted animals are prepared</em> — <em>Sitista</em> (fatted animals, grain-fed cattle) indicates a lavish feast. <em>Panta hetoima</em> (all things are ready) — the perfect <em>hetoima</em> (in a state of readiness) underscores that the only remaining action is the guests\xe2\x80\x99 arrival; they have no legitimate excuse.</p>",
    "5": "<p><strong>amelēsantes de apēlthon</strong> — <em>having been careless/indifferent they went off</em> — <em>Ameleō</em> (to be unconcerned, neglect) is the key word; the refusal is not hostile but indifferent — <em>ho men eis ton idion agron</em> (one to his own field), <em>ho de eis tēn emporian autou</em> (another to his business). Economic preoccupation displaces the invitation.</p>",
    "6": "<p><strong>hoi de loipoi kratēsantes tous doulous autou hybrizan kai apekteinan</strong> — <em>the rest seizing his servants insulted and killed them</em> — <em>Hybrizō</em> (to insult, mistreat, outrage) connotes deliberate humiliation beyond mere violence. The escalation from indifference (v.5) to murder (v.6) parallels the Wicked Tenants sequence, reinforcing the allegory of Israel\xe2\x80\x99s rejection of prophets.</p>",
    "7": "<p><strong>orgistheis de ho basileus apesteilen ta strateumata autou</strong> — <em>the king having become angry sent his armies</em> — <em>Strateumata</em> (armies, troops) — unusual for a wedding-feast context; the allegorical dimension is transparent. <em>Eneprēsen tēn polin ekeinēn</em> (burned that city) is widely read as a reference to the destruction of Jerusalem in AD 70 (the aorist describing a future-from-Jesus\xe2\x80\x99-perspective event).</p>",
    "8": "<p><strong>ho men gamos hetoimos estin</strong> — <em>the wedding feast is ready</em> — The present <em>estin</em> maintains the feast\xe2\x80\x99s continued readiness despite the refusals. <em>Hoi de keklēmenoi ouk ēsan axioi</em> (those who were called were not worthy) — <em>axios</em> (worthy, deserving) — the judgment is on fitness, not on God\xe2\x80\x99s desire to include them.</p>",
    "9": "<p><strong>epi tas diexodous tōn hodōn</strong> — <em>to the crossings of the roads</em> — <em>Diexodos</em> (thoroughfare, where roads cross and split, outer edges) = the main intersections and exits of the city, where the most diverse traffic would be found. <em>Hosous ean heurēte kalesate eis tous gamous</em> (whoever you find call to the wedding) — the universality of the new invitation.</p>",
    "10": "<p><strong>synēgagon pantas hous heuron ponērous te kai agathous</strong> — <em>they gathered all they found, evil and good alike</em> — <em>Ponērous te kai agathous</em> (both evil and good) — the mission to the crossroads gathers without discrimination; the mixed community prefigures the tares-among-wheat dynamic (cf. 13:24-30). <em>Eplēsthē ho nymphōn anakeimenōn</em> (the wedding hall was filled with those reclining) — <em>anakeimenōn</em> (reclining at table) is the posture of banquet guests.</p>",
    "11": "<p><strong>eiselthen de ho basileus theasasthai tous anakeimenous</strong> — <em>the king came in to see those reclining</em> — <em>Theasasthai</em> (to look at carefully, behold) aorist infinitive of <em>theaomai</em>; a formal inspection. <em>Eidon ekei anthrōpon ouk endedymenon endyma gamou</em> (he saw there a man not clothed with a wedding garment) — <em>endyma gamou</em> (wedding garment) — the absence is the focus, not just improper dress.</p>",
    "12": "<p><strong>hetaire pōs eisēlthes hōde mē echōn endyma gamou</strong> — <em>friend, how did you enter here not having a wedding garment?</em> — <em>Hetaire</em> (companion, friend — distancing form; cf. 20:13; 26:50) used three times in Matthew in contexts of gentle rebuke. <em>Ho de ephimōthē</em> (he was silenced) — <em>phimoō</em> (to muzzle, silence) aorist passive; the man has no answer, indicating his guilt is recognized even by himself.</p>",
    "13": "<p><strong>dēsantes autou podas kai cheiras ekballete auton</strong> — <em>bind his feet and hands and cast him out</em> — <em>Dēsantes</em> (having bound) aorist participle; the binding renders the man helpless. <em>Eis to skotos to exōteron</em> (into the outer darkness) with <em>ho klauthmos kai ho brygmos tōn odontōn</em> (the weeping and gnashing of teeth) = the standard Matthean formula for eschatological judgment (8:12; 13:42,50; 24:51; 25:30).</p>",
    "14": "<p><strong>polloi gar eisin klētoi oligoi de eklektoi</strong> — <em>for many are called but few are chosen</em> — <em>Klētoi</em> (called, invited) and <em>eklektoi</em> (chosen, selected — from <em>eklegō</em> = to choose out) are distinct: the call is universal, the election is particular. This serves as the parable\xe2\x80\x99s theological summary and anticipates the judgment scene of 25:31-46.</p>",
    "15": "<p><strong>poreutheies synebouleusanto hopōs auton pagideuōsin en logō̧</strong> — <em>having departed they plotted to trap him in a word</em> — <em>Pagideuō</em> (to trap, ensnare — from <em>pagis</em> = snare) is a hunting metaphor; the Pharisees aim to catch Jesus in a statement that either alienates the crowd or invites Roman action. <em>En logō̧</em> (in a word/statement) = by means of his own words.</p>",
    "16": "<p><strong>alēthēs ei kai tēn hodon tou theou en alētheia didaskeis</strong> — <em>you are truthful and teach the way of God in truth</em> — The flattery (vv. 16b) is transparent but formally correct; it sets up the question as if they sincerely sought Jesus\xe2\x80\x99 unbiased opinion. <em>Ou melei soi peri oudenos</em> (you care about no one) = you are impartial, immune to social pressure — the very quality they hope to exploit.</p>",
    "17": "<p><strong>exestin dounai kēnson Kaisari ē ou</strong> — <em>is it lawful to pay tribute to Caesar or not?</em> — <em>Kēnsos</em> (census tax, poll tax — from Latin <em>census</em>) was the annual per-head tax paid to Rome, deeply resented. The dilemma: yes = betrayal of Jewish national sentiment; no = sedition against Rome. Either answer seemed to destroy Jesus.</p>",
    "18": "<p><strong>gnous de ho Iēsous tēn ponērian autōn</strong> — <em>Jesus knowing their wickedness</em> — <em>Gnous</em> (aorist participle of <em>ginōskō</em>) = having known (supernatural insight). <em>Tēn ponērian</em> (their wickedness, evil intent) — Matthew uses the strong moral term <em>ponēria</em>. <em>Ti me peiraxete hypokritai</em> (why do you test me, hypocrites?) — <em>hypokritēs</em> (stage-actor, one who plays a part) is Jesus\xe2\x80\x99 sharpest address for religious performance.</p>",
    "19": "<p><strong>epideíxaté moi to nomisma tou kēnsou</strong> — <em>show me the tribute coin</em> — <em>Nomisma</em> (coin in common use, currency — from <em>nomos</em> = law/custom) = the standard coin; specifically a denarius bearing Caesar\xe2\x80\x99s image. Jesus\xe2\x80\x99 request for the coin shifts the burden to them — they produce it, implying their participation in the Roman economy.</p>",
    "20": "<p><strong>tinos hē eikōn hautē kai hē epigraphē</strong> — <em>whose image and inscription is this?</em> — <em>Eikōn</em> (image, likeness) and <em>epigraphē</em> (inscription, superscription) together establish identity and ownership. The question invites them to articulate the coin\xe2\x80\x99s nature before Jesus draws the theological conclusion.</p>",
    "21": "<p><strong>apodote oun ta Kaisaros Kaisari kai ta tou theou tō̧ theō̧</strong> — <em>give back therefore the things of Caesar to Caesar and the things of God to God</em> — <em>Apodidōmi</em> (to give back, render) rather than <em>didōmi</em> (to give) implies returning what is already owed — obligation, not gift. The answer is neither capitulation to Rome nor seditious refusal; it distinguishes two orders of obligation without subordinating the divine to the imperial. <em>Ta tou theou tō̧ theō̧</em> — the humanity who bears God\xe2\x80\x99s image (<em>eikōn</em>, Gen 1:26-27) belongs to God.</p>",
    "22": "<p><strong>thaumasantes aphēkan auton kai apēlthon</strong> — <em>marveling they left him and went away</em> — <em>Thaumazō</em> (to marvel, be amazed) without the further step of faith recurs in Matthew as a response that falls short of discipleship. The adversaries are silenced but not converted.</p>",
    "23": "<p><strong>Saddoukaioi hoi legontes mē einai anastasin</strong> — <em>Sadducees who say there is no resurrection</em> — Matthew\xe2\x80\x99s parenthetical gloss identifies the Sadducees by their distinctive doctrinal position: rejection of bodily resurrection (held only Torah as authoritative, not the Prophets or Writings where resurrection texts appear). <em>Epērōtēsan auton</em> (questioned him) — aorist, a single formal question.</p>",
    "24": "<p><strong>Mōysēs eipen ean tis apothanē mē echōn tekna</strong> — <em>Moses said if someone dies not having children</em> — The Sadducees cite Deut 25:5-10 (Levirate marriage law: <em>epigambrieuein</em> = to marry the brother\xe2\x80\x99s widow). <em>Anastēsei sperma tō̧ adelphō̧ autou</em> (will raise up offspring for his brother) — a technical legal obligation to preserve the deceased brother\xe2\x80\x99s lineage.</p>",
    "25": "<p><strong>ēsan de par\' hēmin hepta adelphoi</strong> — <em>there were among us seven brothers</em> — The constructed scenario escalates to absurdity (seven levirate marriages) precisely to make the resurrection afterlife appear logically incoherent. <em>Aphēken tēn gynaika autou tō̧ adelphō̧ autou</em> (left his wife to his brother) — standard levirate fulfillment vocabulary.</p>",
    "26": "<p><strong>homoiōs kai ho deuteros kai ho tritos heōs tōn hepta</strong> — <em>likewise the second and the third through the seven</em> — The rapid enumeration (<em>homoiōs</em> = likewise, in the same way) through all seven compresses the scenario to reveal its reductio ad absurdum intent.</p>",
    "27": "<p><strong>hysteron de pantōn apethanen hē gynē</strong> — <em>last of all the woman also died</em> — The final death closes the hypothetical chain. <em>Hysteron... pantōn</em> (last of all) places the woman\xe2\x80\x99s death as the culminating event that makes the resurrection question unavoidable.</p>",
    "28": "<p><strong>en tȩ̄ anastásei oun tinos tōn hepta estai gynē</strong> — <em>in the resurrection therefore whose wife of the seven will she be?</em> — The question assumes resurrection must replicate earthly social structures (marriage and ownership) — the very assumption Jesus will demolish. <em>Pantes gar eschon autēn</em> (for all had her) — the final phrase is designed for maximum logical shock.</p>",
    "29": "<p><strong>planasthe mē eidotes tas graphas mēde tēn dynamin tou theou</strong> — <em>you are deceived not knowing the scriptures nor the power of God</em> — <em>Planasthe</em> (present passive: you are being led astray, deceived) is a strong charge; the Sadducees\xe2\x80\x99 error stems from two ignorances: <em>tas graphas</em> (the scriptures) and <em>tēn dynamin tou theou</em> (the power of God). Both are required to understand resurrection.</p>",
    "30": "<p><strong>en tȩ̄ anastásei oute gamousin oute gamizontai</strong> — <em>in the resurrection they neither marry nor are given in marriage</em> — <em>Gameō</em> (to marry, active: the man\xe2\x80\x99s act) and <em>gamizō</em> (to give in marriage, the father\xe2\x80\x99s act of betrothal) distinguish the two parties in Jewish marriage customs. Resurrection life transcends the social institution entirely. <em>All\' hōs angeloi en tō̧ ouranō̧ eisin</em> (but as angels in heaven they are) — the comparison is to angelic existence, not to dissolution of personhood.</p>",
    "31": "<p><strong>peri de tēs anastaseōs tōn nekrōn ouk anegnōte</strong> — <em>concerning the resurrection of the dead have you not read?</em> — Jesus now defeats the Sadducees on their own canonical ground: the Torah itself (not the Prophets). <em>To rhēthen hymin hypo tou theou</em> (what was spoken to you by God) — direct divine speech, not merely human author.</p>",
    "32": "<p><strong>egō eimi ho theos Abraam kai ho theos Isaak kai ho theos Iakōb</strong> — <em>I am the God of Abraham and the God of Isaac and the God of Jacob</em> — Ex 3:6 LXX cited with precision. The present tense <em>eimi</em> (I am) is the argument: God speaks of himself as the God of Abraham in the present, not the past — therefore Abraham exists presently in relationship with God. <em>Ouk estin ho theos nekrōn alla zōntōn</em> (he is not God of the dead but of the living) — the logical inference: if God is Abraham\xe2\x80\x99s God presently, Abraham must be living.</p>",
    "33": "<p><strong>kai akousantes hoi ochloi exeplēssonto epi tȩ̄ didachȩ̄ autou</strong> — <em>the crowds hearing were astonished at his teaching</em> — <em>Ekplēssō</em> (to strike out of one\xe2\x80\x99s senses, astound) perfect passive — the astonishment is complete and ongoing. <em>Epi tȩ̄ didachȩ̄ autou</em> (at his teaching) — it is the content and method of the argument, not merely a miracle, that produces this response.</p>",
    "34": "<p><strong>hoi de Pharisaioi akousantes hoti ephimōsen tous Saddoukiaous</strong> — <em>the Pharisees having heard that he had silenced the Sadducees</em> — <em>Phimoō</em> (to muzzle, silence) aorist: Jesus\xe2\x80\x99 defeat of the Sadducees satisfies the Pharisees doctrinally but renews their own challenge. <em>Synēchthēsan epi to auto</em> (were gathered together) — a formal assembly to coordinate the next question.</p>",
    "35": "<p><strong>nomikos peirazōn auton</strong> — <em>a lawyer testing him</em> — <em>Nomikos</em> (lawyer, legal expert in Torah — not Roman law) appears only here in Matthew; Mark 12:28 describes him more sympathetically. <em>Peirazōn</em> (testing, present participle) marks adversarial intent, though the question itself is a legitimate and important one in rabbinic discussion.</p>",
    "36": "<p><strong>poia entolē megalē en tō̧ nomō̧</strong> — <em>which commandment is great in the law?</em> — The question about the greatest commandment (<em>megalē entolē</em>) was a live rabbinic debate; various sages offered summaries. The lawyer seeks either to catch Jesus in a controversial ranking or to hear his answer for debate purposes.</p>",
    "38": "<p><strong>hautē estin hē megalē kai prōtē entolē</strong> — <em>this is the great and first commandment</em> — Jesus identifies Deut 6:5 (the Shema continuation) as <em>megalē kai prōtē</em> (great and first). <em>En holȩ̄ tȩ̄ kardia̧ sou kai en holȩ̄ tȩ̄ psychȩ̄ sou kai en holȩ̄ tȩ̄ dianoia̧ sou</em> — Matthew\xe2\x80\x99s version adds <em>dianoia</em> (mind/understanding) to the Deut 6:5 triad of heart/soul/strength, following the LXX variant.</p>",
    "39": "<p><strong>deutera de homoia autȩ̄</strong> — <em>and a second is like it</em> — <em>Homoia</em> (like, similar) — Jesus\xe2\x80\x99 addition of the second commandment (Lev 19:18: <em>agapēseis ton plēsion sou hōs seauton</em>) was not asked; he volunteers it as inseparably paired with the first. The neighbor-love command is not subordinate but <em>homoia</em> = of the same kind and order.</p>",
    "40": "<p><strong>en tautais tais dysin entolais holos ho nomos krematai kai hoi prophētai</strong> — <em>on these two commandments hang all the law and the prophets</em> — <em>Krematai</em> (hangs, depends — from <em>kremannymi</em>) is a striking metaphor: the entire Torah and prophetic corpus <em>hangs from</em> these two love-commands as weights hang from a beam. This is the Matthean summary of scriptural ethics (cf. 7:12).</p>",
    "41": "<p><strong>synēgmenōn de tōn Pharisaiōn</strong> — <em>the Pharisees being gathered together</em> — Jesus now takes the initiative; having answered all challenges he poses the decisive Christological question. <em>Epērōtēsen autous ho Iēsous</em> (Jesus questioned them) — the reversal: the interrogated becomes the interrogator.</p>",
    "42": "<p><strong>tinos huios estin ho christos</strong> — <em>whose son is the Christ?</em> — The fundamental question of identity: whose descendant (<em>huios</em>) is the Messiah? Their answer <em>tou Dauid</em> (of David) is correct but insufficient; Jesus will show it is incomplete. The question anticipates 22:43-45.</p>",
    "43": "<p><strong>pōs oun Dauid en pneumati kalei auton kyrion</strong> — <em>how then does David in the Spirit call him Lord?</em> — <em>En pneumati</em> (in the Spirit) = under divine inspiration, the standard understanding of prophetic authorship (cf. 2 Sam 23:2; 2 Tim 3:16). David\xe2\x80\x99s psalm-composition is Spirit-inspired, giving his words in Ps 110 the character of divine oracle.</p>",
    "44": "<p><strong>eipen kyrios tō̧ kyriō̧ mou</strong> — <em>the Lord said to my Lord</em> — Ps 110:1 LXX: <em>eipen ho kyrios tō̧ kyriō̧ mou</em>. The two <em>kyrios</em> designations: first = YHWH (LXX <em>kyrios</em> for the Tetragrammaton); second = the Psalmist\xe2\x80\x99s Lord (adoni). David calls his own descendant <em>adoni</em> (my lord) — an extraordinary reversal of the expected ancestor-descendant honor relationship. <em>Kathous ek dexiōn mou</em> (sit at my right) — the position of highest co-regency (cf. 20:21).</p>",
    "45": "<p><strong>ei oun Dauid kalei auton kyrion</strong> — <em>if therefore David calls him Lord</em> — The conditional is straightforward: if David (as author) called this figure <em>kyrios</em>, and the Messiah is David\xe2\x80\x99s descendant, a contradiction appears under ordinary kinship logic. <em>Pōs huios autou estin</em> (how is he his son?) — the question forces recognition that the Messiah transcends human genealogical categories; he is simultaneously David\xe2\x80\x99s son and David\xe2\x80\x99s Lord.</p>",
    "46": "<p><strong>kai oudeis edynato apokrithēnai autō̧ logon</strong> — <em>and no one was able to answer him a word</em> — <em>Apokrithēnai logon</em> (to answer a word) = to give any reply at all. The silencing of all challengers is total and deliberate: the chief priests, Herodians, Sadducees, and Pharisees have all failed. <em>Oude etólmēsen tis</em> (nor did anyone dare) — <em>tolmaō</em> (to dare, have courage) — even the attempt at further question was abandoned.</p>"
  }
}

comm = load_comm('mkt-original', 'matthew')
merge_comm(comm, NEW_DATA)
save_comm('mkt-original', 'matthew', comm)

print('Done.')
for ch in ['21', '22']:
    print(f'  ch{ch}: {len(comm.get(ch, {}))} verses')
