"""
MKT Original — 1 Kings chapters 12–14
Run: python3 scripts/zc-original-1kings-12-14-full.py

Ch12: Rehoboam's folly at Shechem; the kingdom splits; Jeroboam's golden calves (33 verses)
Ch13: The man of God from Judah; the Josiah prophecy; the old prophet's deception (34 verses)
Ch14: Ahijah's oracle against Jeroboam; Abijah's death; Shishak's plunder (31 verses)

Key term decisions:
- yoke (ʿōl) retained; burden/service (ʿăḇōḏāh) as state corvée labor
- ḥāṭāʾt as sin/transgression not merely mistake
- môpēṯ as sign-wonder (portent), not merely sign
- nāgîḏ as appointed leader/ruler (YHWH's election language)
- qĕḏēšîm as male cult prostitutes (Canaanite shrine functionaries)
- šîšaq = Shishak/Shoshenq I (historically attested Egyptian pharaoh)
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / f'mkt-{source}' / f'{book}.json'
    return json.loads(p.read_text()) if p.exists() else {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / f'mkt-{source}' / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

ORIGINAL = {
  "12": {
    "1": "<p><em>wayyēleḵ rĕḥaḇʿām šĕḵemāh</em> — Rehoboam went to Shechem for the coronation assembly. Shechem (<em>šĕḵem</em>, H7927) was not his capital but the covenant assembly site — the place where Joshua renewed the covenant (Josh 24) and where Abimelech made his bid for kingship (Judg 9). The choice of Shechem signals that Rehoboam knew he needed northern ratification, not merely Judahite succession. The assembly (<em>qāhal</em>, H6951) functions as the covenant community gathered to confirm the king; Israelite kingship required the people&#8217;s consent expressed through the tribal representatives. The Deuteronomic law of the king (Deut 17:14-20) presupposes this dynamic: the king is set up by the community, not only by dynastic succession.</p>",
    "2": "<p>Jeroboam son of Nebat was in Egypt, where he had fled from Solomon (cf. 1 Kgs 11:40). The note that Jeroboam was still in Egypt when news arrived is the narrative preparation for the contrast between the two responses to Rehoboam&#8217;s question: the elders who served Solomon (vv. 6-7) and the young men who grew up with Rehoboam (vv. 8-11). Jeroboam&#8217;s Egyptian exile is the political background — he had already received the prophetic word from Ahijah (11:29-39) about the ten tribes; his return is the fulfillment in process.</p>",
    "3": "<p>The assembly summoned Jeroboam and brought him back; he came before Rehoboam with the whole assembly of Israel. The <em>qāhal kol-yiśrāʾēl</em> (whole assembly of Israel) is the formal covenant body — not a popular crowd but the representative covenant gathering that has legal authority to make covenantal demands of the incoming king. Their request in v.4 is a formal petition from the covenant assembly, not a complaint from disgruntled workers. The presence of Jeroboam alongside the assembly signals that he is their representative voice and potential alternative.</p>",
    "4": "<p><em>ʾāḇîḵā hiqqšāh ʾeṯ-ʿullēnû wĕʿaṯṯāh hāqēl mēʿăḇōḏaṯ ʾāḇîḵā</em> — Your father made our yoke hard; lighten the servitude of your father. The <em>ʿōl</em> (H5923, yoke) and <em>ʿăḇōḏāh</em> (H5656, servitude/labor) are the vocabulary of the Egyptian bondage (cf. Exod 1:14; 6:6-9 where both terms describe Pharaoh&#8217;s oppression). The assembly is deliberately invoking the exodus: Solomon&#8217;s corvée state had replicated the conditions Israel was delivered from. The request is for covenant relief — a return to the servant-king model where the king serves the people (v.7) rather than enslaving them. The adjective <em>qāšāh</em> (H7185, hard/harsh) in <em>hiqqšāh ʾeṯ-ʿullēnû</em> is the same word used for Pharaoh&#8217;s hardening (Exod 13:15).</p>",
    "5": "<p>Rehoboam asks for three days: <em>lĕḵû ʿôḏ šĕlōšāh yāmîm</em>. The three-day deliberation period is a standard ancient Near Eastern consultation interval — not a legal term but a recognized period for taking counsel. Rehoboam&#8217;s delay is prudent protocol, but it will be poorly used. The parallel with 1 Kgs 12:12 (the people returned on the third day as the king had told them) creates the structure of a formal hearing with deliberation followed by verdict. The interval is a gift he squanders by consulting the wrong advisors.</p>",
    "6": "<p>Rehoboam consults the <em>zĕqēnîm</em> (H2205, elders) who had stood before (<em>ʿāmĕdû lipnê</em>) Solomon during his lifetime. <em>ʿāmad lipnê</em> (to stand before) is the technical term for royal service (cf. 1 Kgs 1:2; 10:8; 12:8) — these are experienced court officials who had observed Solomon&#8217;s administration firsthand. The elders&#8217; advice in v.7 articulates the servant-king ideal of Deuteronomy 17: the king who is not lifted up above his brothers (Deut 17:20), who reads YHWH&#8217;s law daily (17:19) and learns the fear of YHWH. They are recommending the covenant constitution of Israelite kingship.</p>",
    "7": "<p><em>ʾim-hayyôm tihyeh-ʿeḇeḏ lāʿam hazzeh ûḵĕḇaltô waʿănîtām wĕdibbartā ʾălêhem dĕḇārîm ṭôḇîm</em> — If today you will be a servant to this people and serve them and answer them with good words, they will be your servants forever. The elders&#8217; advice centers on the <em>ʿeḇeḏ</em> (H5650, servant) language — the king who serves his people is the biblical ideal. <em>dĕḇārîm ṭôḇîm</em> (good words) stands in contrast to the harsh word Rehoboam will actually give (v.13: <em>qāšāh</em>). The conditional promise — <em>wĕhāyû lĕḵā ʿăḇādîm kol-hayyāmîm</em> (they will be your servants forever) — shows that genuine servant-leadership generates willing loyalty, not the forced service that breaks it.</p>",
    "8": "<p>Rehoboam rejected (<em>wayyaʿăzōḇ</em>, H5800, abandoned/forsook) the advice of the elders and consulted the young men (<em>hayyelādîm</em>, H3206, boys/youths) who had grown up with him. The verb <em>ʿāzaḇ</em> (to forsake/abandon) is used extensively in DtrH for abandoning YHWH (1 Kgs 11:33; 14:22; 18:18) — its use here for forsaking the elders&#8217; counsel is theologically loaded. Rehoboam abandons wisdom as the unfaithful kings will abandon YHWH. The young men who &#8220;grew up with him&#8221; (<em>gāḏĕlû ʾittô</em>) are courtiers of his own peer-cohort, lacking the formation that comes from witnessing the consequences of policy over time.</p>",
    "9": "<p>Rehoboam&#8217;s question to the young men is identical to his question to the elders: &#8220;what do you advise that we answer this people?&#8221; The parallel question generates the contrasting answers that define the chapter&#8217;s theological claim. The fact that Rehoboam asks both groups the same question in the same words shows that his failure is not informational — he received the same inquiry both times — but dispositional: he was already inclined toward the answer he received from the young men.</p>",
    "10": "<p><em>qāṭān mimmennî yigbah mimmōṯnê ʾāḇî</em> — My little finger is thicker than my father&#8217;s loins/waist. The gross anatomical boast of the young men is one of the most arrogant statements in the Hebrew Bible. <em>qāṭān</em> (H6996, small/little) in <em>qāṭān mimmennî</em> refers to the little finger — the least significant part of the king. The comparison of the king&#8217;s little finger to his father&#8217;s loins (<em>mōṯnayim</em>, H4975, the seat of strength) is a deliberate assertion of superiority through anatomical vulgarity. The young men are advising not merely firmness but contemptuous dominance.</p>",
    "11": "<p><em>wĕʿaṯṯāh ʾāḇî ʾibbas ʾĕṯḵem bašśôṭîm wăʾănî ʾăyasēr ʾĕṯḵem bāʿaqrabbîm</em> — My father disciplined you with whips; I will discipline you with scorpions. The contrast between <em>šôṭîm</em> (H7752, whips) and <em>ʿaqrabbîm</em> (H6137, scorpions) escalates the image of punishment. <em>ʿaqrabbîm</em> may refer to a barbed or spiked whip, not actual scorpions (cf. the scorpion metaphor in Ezek 2:6 for the stubborn people). The rhetorical function is the claim to surpass Solomon&#8217;s harshness by an order of magnitude. This is the language of the despot, not the shepherd-king — precisely the failure of Israelite kingship that the Deuteronomic law warned against (Deut 17:20: the king must not think himself above his brothers).</p>",
    "12": "<p>Jeroboam and all the people returned on the third day, as the king had instructed. The formal structure of the hearing is preserved: the assembly had been sent away with a time limit, they return punctually, and await the royal verdict. The careful protocol of the assembly contrasts with the contempt about to be shown to it. The narrator&#8217;s point-by-point parallel (v.12 echoing v.5) structures the scene as a formal covenant proceeding with a disastrous verdict.</p>",
    "13": "<p><em>wayyaʿănēm hammelek qāšāh</em> — the king answered the people harshly. <em>qāšāh</em> (H7185) is the harsh-hardness of Pharaoh&#8217;s oppression and the stubborn neck of the rebellious people. The narrator&#8217;s summary before the specific words — &#8220;rejecting the advice of the elders&#8221; — is a theological verdict. The <em>zeqēnîm</em> (elders) embody accumulated covenant wisdom; <em>wayyaʿăzōḇ</em> (he rejected/abandoned) anticipates the apostasy-language that will characterize the northern kingdom&#8217;s relationship with YHWH. The king who abandons wisdom for flattery will produce a kingdom that abandons YHWH for idols.</p>",
    "14": "<p>He spoke according to the advice of the young men: my father loaded your yoke heavy; I will add to it. The exact repetition of the young men&#8217;s words (vv.10-11) in the king&#8217;s formal answer is the narrator&#8217;s technique of showing Rehoboam&#8217;s complete capture by his peer-cohort. He has not weighed the advice and chosen; he has simply repeated what he was told. The king who cannot distinguish between advisors — who cannot evaluate counsel according to covenant wisdom — is the king the DtrH is showing to be unfit. The whip-and-scorpion language in a formal covenant proceeding is the declaration that this king does not understand the covenant relationship between king and people.</p>",
    "15": "<p><em>kî-hāyĕṯāh sĕḇîḇāh mēʿim YHWH lĕmaʿan hāqîm ʾeṯ-dĕḇārô</em> — for this turn of events was from YHWH, to establish/fulfill his word. The narrator interrupts the political narrative with a theological explanation: the <em>sĕḇîḇāh</em> (H5438, turn of events/cause) is YHWH&#8217;s sovereign action. <em>lĕmaʿan hāqîm</em> (in order to establish/fulfill) marks divine purpose behind historical contingency. The word being established is Ahijah&#8217;s prophecy to Jeroboam (11:29-39). The hardening of Pharaoh&#8217;s heart to establish the Exodus is the theological precedent: YHWH works through human stubbornness to accomplish his decreed purpose. Rehoboam&#8217;s folly is real; it is also YHWH&#8217;s instrument.</p>",
    "16": "<p><em>mah-lānû ḥēleq bĕḏāwid wĕlōʾ-naḥălāh bĕḇen-yišāy lĕʾohāleḵā yiśrāʾēl</em> — What share do we have in David? What inheritance in the son of Jesse? The war-cry of secession echoes Sheba son of Bichri&#8217;s cry in 2 Sam 20:1 — nearly word for word. <em>ḥēleq</em> (H2506, portion/share) and <em>naḥălāh</em> (H5159, inheritance/portion) are covenant-land terms: the ten tribes are declaring that they have no covenantal stake in the Davidic house. &#8220;To your tents, O Israel&#8221; is the ancient dispersal-formula after assembly (cf. 1 Kgs 8:66); here it signals permanent dissolution rather than mere dismissal.</p>",
    "17": "<p>Rehoboam still reigned over the Israelites who were living in the cities of Judah. The contracted scope of the Davidic kingship — now &#8220;the cities of Judah&#8221; rather than &#8220;all Israel and Judah&#8221; — is the immediate consequence of the folly. The note is transitional but theologically significant: the dynasty that was promised the eternal covenant (2 Sam 7) now governs a truncated territory. The covenant promise remains; its scope is provisionally narrowed by covenant faithlessness.</p>",
    "18": "<p>Rehoboam sent Adoram (<em>ʾadōrām</em>) — the official in charge of forced labor (<em>hammās</em>, H4522) — into the north; the people stoned him to death. The sending of the corvée-overseer rather than a diplomat or conciliator as the first post-declaration contact is the height of political obtuseness. <em>mammās</em> (forced levy/conscript labor) was the very grievance driving the secession; Rehoboam&#8217;s response is to send the officer who represents the most resented aspect of the policy. The people&#8217;s response — stoning (<em>rāgam</em>, H7275) — was the covenant penalty for crimes against the assembly. Rehoboam flees in his chariot.</p>",
    "19": "<p><em>wayyipšĕʿû yiśrāʾēl bĕḇêṯ dāwid ʿaḏ hayyôm hazzeh</em> — Israel has been in rebellion against the house of David to this day. <em>pāšaʿ</em> (H6586, to rebel/transgress) is both political rebellion and covenant transgression — the same verb used for Israel&#8217;s rebellion against YHWH (Isa 1:2). The narrator&#8217;s &#8220;to this day&#8221; (<em>ʿaḏ hayyôm hazzeh</em>) connects the narrator&#8217;s own time to this founding moment of the division — written after the exile, looking back at the ongoing rupture. The division is not presented as merely political but as an act of covenant transgression that characterizes the northern kingdom throughout its existence.</p>",
    "20": "<p>The assembly of all Israel summoned Jeroboam and installed him as king over all Israel; none followed the house of David except the tribe of Judah alone. The <em>wayyaqhîlû</em> (assembled him, from <em>qāhal</em>) echoes the covenant assembly vocabulary; Jeroboam&#8217;s accession is formally parallel to Rehoboam&#8217;s — both receive assembly-ratification. The exception note — &#8220;only the tribe of Judah&#8221; — preserves the Davidic line with its promise but reduces its territorial scope drastically. The narrator&#8217;s framing &#8220;all Israel&#8221; vs. &#8220;only the tribe of Judah&#8221; is the DtrH&#8217;s account of the covenant people&#8217;s permanent division.</p>",
    "21": "<p>Rehoboam assembled 180,000 soldiers to fight against the house of Israel and restore the kingdom to Rehoboam. The number 180,000 (<em>me&#8217;at ûšĕmōnîm ʾālep̄</em>) — whether literal or rhetorical — represents the full military mobilization of Judah and Benjamin. The stated purpose is restoration of the united kingdom by force — a legitimate dynastic goal but one YHWH will explicitly prohibit through the prophetic word.</p>",
    "22": "<p>The word of God (<em>dĕḇar hāʾĕlōhîm</em>) came to Shemaiah the man of God (<em>ʾîš hāʾĕlōhîm</em>). The divine word through the prophetic figure interrupts the military mobilization — YHWH&#8217;s word is the sovereign check on royal action throughout Kings. <em>ʾîš hāʾĕlōhîm</em> (H376 + H430) is the title for the authoritative divine messenger (cf. Moses, Deut 33:1; Samuel, 1 Sam 9:6; Elijah and Elisha throughout). Shemaiah is otherwise unknown; the DtrH preserves the name to authenticate the oracle&#8217;s prophetic origin.</p>",
    "23": "<p>The oracle is directed at &#8220;Rehoboam son of Solomon, king of Judah, and all the house of Judah and Benjamin, and the rest of the people.&#8221; The specific address to all parties — not only Rehoboam but the whole mobilized force — is the covenantal scope of the prohibition. The divine word does not merely advise the king; it commands the entire assembly. The inclusiveness of the address shows that YHWH&#8217;s sovereign direction applies to the community as a whole, not only its leaders.</p>",
    "24": "<p><em>lōʾ-taʿălû wĕlōʾ-tiilāḥămû ʿim-ʾăḥêḵem bĕnê-yiśrāʾēl</em> — Do not go up and do not fight against your brothers, the sons of Israel. The prohibition uses <em>ʾăḥêḵem</em> (your brothers) — the covenant kinship term. The division is YHWH&#8217;s work (<em>kî mēʾittî hāyĕṯāh haddāḇār hazzeh</em>, this thing is from me): YHWH prohibits the military reversal of what he himself ordained. The obedience of the people — they went home according to the divine word — is remarkable in a military mobilization context. The divine word spoken through the prophet has legal authority that overrides the royal military command.</p>",
    "25": "<p>Jeroboam built (<em>wayyiḇen</em>) Shechem in the hill country of Ephraim and settled there; he also built Penuel. The establishment of administrative cities — Shechem (central, near the covenant assembly site) and Penuel (Transjordanian, east of the Jordan) — is Jeroboam&#8217;s political consolidation. Shechem was a natural administrative center for the northern highland; Penuel provided a Transjordanian foothold. The building activity is the narrative marker of a king establishing his territorial claim (cf. Solomon&#8217;s building program, ch5-9).</p>",
    "26": "<p><em>wayyōʾmer yārāḇʿām bĕlibbô</em> — Jeroboam said in his heart. The internal deliberation — unspoken, private — is reported by the omniscient narrator as the source of the apostasy. The reasoning is politically rational: the temple cult in Jerusalem would draw pilgrims north-to-south, and repeated contact between the northern people and the Jerusalem-Judah establishment would erode Jeroboam&#8217;s political hold. His fear that &#8220;the kingdom will revert to the house of David&#8221; is the fear of covenant re-centering around the Davidic sanctuary, which from a purely political perspective was well-founded.</p>",
    "27": "<p>If the people go up to offer sacrifices in the house of YHWH in Jerusalem, their hearts will turn back to their lord (<em>ʾădōnêhem</em>) Rehoboam, king of Judah, and they will kill me and return to Rehoboam. The political logic is lucid: cultic loyalty produces political loyalty. Jeroboam correctly perceived that the Jerusalem temple was not merely a religious institution but the covenant center that embodied Davidic legitimacy. His alternative cult will be designed to prevent this gravitational pull. The tragedy is that his solution — alternative worship sites — will be the formal breach of covenant that triggers the judgment announced in ch14.</p>",
    "28": "<p><em>wayyiqqaḥ hamelek ʿēṣāh wayyaʿaś šĕnê ʿĕglê zāhāḇ</em> — the king took counsel and made two golden calves. The golden calves (<em>ʿêglê zāhāḇ</em>) echo Aaron&#8217;s golden calf at Sinai (Exod 32:4) in the precise words: &#8220;These are your gods, O Israel, who brought you up from the land of Egypt.&#8221; The DtrH&#8217;s use of the Sinai apostasy formula here is deliberate: Jeroboam&#8217;s cult innovation is the Sinai apostasy replicated at the national level. The worship formula redefines the covenant — it addresses the same God (YHWH who brought Israel from Egypt) while providing an illegitimate image. The calves likely functioned as thrones or pedestals for the invisible YHWH (as in the Ark theology) rather than as idols per se, but the DtrH treats them as equivalent to pagan idolatry.</p>",
    "29": "<p>He set up one in Bethel and the other in Dan. The two sites are geographically strategic: Bethel in the south (near the Judahite border, on the main north-south route) and Dan in the far north (at the foot of Mount Hermon). Both were ancient sanctuaries — Bethel had patriarchal associations (Gen 28:10-22; 35:1-15) and Dan was an established northern cult center (Judg 18). The choice of these two sites rather than a new one is Jeroboam&#8217;s appropriation of existing sacred geography to give his cult the aura of ancient legitimacy. The DtrH&#8217;s judgment is that this legitimacy is fraudulent.</p>",
    "30": "<p><em>wayhî haddāḇār hazzeh lĕḥaṭṭāʾṯ</em> — this became a sin (<em>ḥēṭ</em>/transgression, from <em>ḥāṭāʾ</em>, H2399). The narrator&#8217;s formula &#8220;this became a sin&#8221; is repeated throughout Kings in reference to Jeroboam&#8217;s golden calves (cf. 1 Kgs 14:16; 15:26,30; 2 Kgs 10:29) — it becomes the technical phrase for the founding apostasy of the northern kingdom. The people went as far as Dan — the far northern sanctuary — showing that the cult took hold broadly across the territory. The <em>ḥāṭāʾt</em> is both the transgression and its consequences — a semantic range that the MKT &#8220;sin&#8221; captures more fully than &#8220;mistake&#8221; or &#8220;error&#8221;.</p>",
    "31": "<p>Jeroboam made shrines (<em>bêṯ bāmôṯ</em>, high-place temples) and appointed priests from all sorts of people who were not Levites (<em>miqṣôṯ hāʿām ʾăšer lōʾ-hāyû mibĕnê lēwî</em>). The appointment of non-Levitical priests is a second covenant violation alongside the golden calves — it directly contravenes the Mosaic prescription that the Levitical tribe alone serve as priests (Num 3:5-10). <em>bêṯ bāmôṯ</em> (plural, high-place temples) suggests a network of shrines, not merely the two calf-sites. Jeroboam is constructing a comprehensive alternative cultic infrastructure: new sites, new symbols, new clergy.</p>",
    "32": "<p>Jeroboam instituted a festival on the fifteenth day of the eighth month, similar to the festival in Judah (<em>kaḥag ʾăšer bîhûḏāh</em>). The Feast of Tabernacles (<em>sukkôṯ</em>) was celebrated on the fifteenth of the seventh month (Lev 23:34); Jeroboam moved it to the eighth month. The narrator&#8217;s comparison to the Judahite festival shows the deliberate parallelism — Jeroboam is creating an alternative liturgical calendar that mirrors Jerusalem&#8217;s while being permanently offset from it. The calendar manipulation is ideologically potent: whoever controls the sacred calendar controls the community&#8217;s rhythms of covenant renewal.</p>",
    "33": "<p><em>baḥōḏeš ʾăšer-bādāʾ millibô</em> — in the month he had devised from his own heart. The phrase <em>bādāʾ millibô</em> (invented/devised from his own heart) is the DtrH&#8217;s theological verdict: Jeroboam&#8217;s calendar change was human innovation without divine authorization. The word <em>bādāʾ</em> (H908) — to devise, invent, fabricate — is the term for unauthorized religious innovation, worship not commanded by YHWH. The contrast with the prescribed calendar of Leviticus is stark: YHWH commanded specific festivals on specific days; Jeroboam created his own. The narrator&#8217;s repeated emphasis on this — Jeroboam himself went up to the altar at Bethel, burned incense, and officiated — shows the king assuming priestly functions that also violate the Mosaic separation of royal and priestly roles.</p>"
  },
  "13": {
    "1": "<p>A man of God (<em>ʾîš ʾĕlōhîm</em>, H376 + H430) came from Judah to Bethel by the word of YHWH (<em>bĕḏĕḇar YHWH</em>) — the introductory phrase establishes both the messenger&#8217;s authority (<em>ʾîš ʾĕlōhîm</em>) and his commission (<em>bĕḏĕḇar YHWH</em>, by the command/word of YHWH). His southern origin — from Judah, the territory of the Davidic covenant — makes his appearance at Jeroboam&#8217;s altar in Bethel geographically and theologically charged. Jeroboam was standing beside the altar (<em>ʿōmēd ʿal-hammizḇēaḥ</em>) to offer incense — the king assuming priestly functions, combining the royal and sacerdotal offices that the covenant carefully separated.</p>",
    "2": "<p><em>wayyiqrāʾ ʿal-hammizḇēaḥ bĕḏĕḇar YHWH wayyōʾmar mizḇēaḥ mizḇēaḥ kōh-ʾāmar YHWH</em> — He cried out against the altar by the word of YHWH: &#8220;O altar, altar, thus says YHWH.&#8221; The apostrophe to the altar itself — the direct address of an inanimate object with the divine oracle — is unusual and rhetorically powerful. The oracle names Josiah (<em>yōšîyāhû</em>) by name as the future destroyer of the altar, approximately 300 years before his birth and reign (2 Kgs 23:15-20). This is one of the most explicit predictive prophecies in the Hebrew Bible — a specific personal name given centuries in advance. The priest&#8217;s bones burned on the altar is the image of ultimate desecration: not mere destruction but the use of the altar&#8217;s own sacred fire to consume those who served at it.</p>",
    "3": "<p><em>ûmôpēṯ nāṯan bayyôm hahûʾ</em> — he gave a sign (<em>môpēṯ</em>, H4159) on that same day. <em>môpēṯ</em> is the sign-wonder that authenticates the prophet&#8217;s word (cf. Deut 13:1-3 where signs and wonders must be tested against doctrinal fidelity; Exod 4:21 where <em>môpēṯ</em> refers to the plague miracles). The sign given is the immediate splitting of the altar and spilling of the ashes — a visible confirmation of the long-term prediction. In prophetic epistemology (Deut 18:22), the fulfillment of the near-term prediction authenticates the distant one. The altar splitting validates the Josiah prophecy by demonstrating YHWH&#8217;s power to immediately act on his declared word.</p>",
    "4": "<p>Jeroboam stretched out his hand from the altar — <em>šallaḥ yāḏô mēʿal hammizḇēaḥ</em> — and said &#8220;seize him!&#8221; (<em>tiśpĕsûhû</em>). The attempt to arrest the man of God is the direct human countermeasure to the divine word — the king&#8217;s authority challenged by prophetic authority, with the king asserting royal power. The hand that stretched out to command the arrest immediately withered: <em>yibbāš yāḏô</em> (his hand dried up/withered). <em>yāḇēš</em> (H3001, to dry up/wither) is the term for plant withering in drought — the hand becomes a shriveled, powerless thing. The bodily sign confirms the prophetic authority over royal power.</p>",
    "5": "<p>The altar split apart and the ashes poured from it, according to the <em>môpēṯ</em> the man of God had given by the word of YHWH. The simultaneous occurrence of both signs — the withered hand and the splitting altar — in direct response to the royal intervention against the prophet validates YHWH&#8217;s sovereign protection of his messenger. The altar&#8217;s destruction begins immediately even as the distant fulfillment (the Josiah prediction) remains centuries away. The proximate signs are YHWH&#8217;s witnesses to the reliability of his distant word.</p>",
    "6": "<p><em>ḥal-nā ʾeṯ-pĕnê YHWH ʾĕlōhêḵā</em> — &#8220;Please seek the face of YHWH your God.&#8221; Jeroboam&#8217;s address — &#8220;YHWH your God&#8221; (not &#8220;our God&#8221;) — reveals that the king recognizes YHWH&#8217;s authority in this moment while distancing himself from personal covenant relationship. The man of God prays; YHWH restores the king&#8217;s hand. The restoration of the withered hand despite the king&#8217;s attempt to arrest YHWH&#8217;s messenger is YHWH&#8217;s gracious response to prayer even from the agent of a rebellious king. The grace is real, but Jeroboam does not repent (v.33: even after this he did not turn from his evil ways).</p>",
    "7": "<p>Jeroboam offers hospitality: &#8220;Come home with me and refresh yourself (<em>hittaḥzaq</em>, strengthen yourself), and I will give you a gift.&#8221; <em>hittaḥzaq</em> (from <em>ḥāzaq</em>, H2388, to be strong) in the context of hospitality means to receive refreshment/sustenance. The offer is a political move — the king who has just experienced the prophet&#8217;s authority now offers to domesticate him through hospitality and reward. The gift (<em>māttān</em>, H4976) would create patronage-obligation: the prophet who accepts the king&#8217;s gift becomes the king&#8217;s beneficiary. The man of God&#8217;s refusal in vv.8-9 is not rudeness but the preservation of prophetic independence from royal patronage.</p>",
    "8": "<p>The man of God refuses: &#8220;If you gave me half your palace, I would not go with you, nor eat bread nor drink water in this place.&#8221; The absoluteness of the refusal — even hypothetically the largest imaginable royal gift would not change the answer — is the prophetic declaration of independence from patronage. <em>lōʾ-ʾōḵal leḥem wĕlōʾ-ʾešteʾ māyim bammāqôm hazzeh</em> (I will not eat bread nor drink water in this place) — the explicit prohibition from YHWH applies to this place (<em>maqôm</em>), not merely to the king. The place itself is under prophetic judgment; receiving its hospitality would imply fellowship with what is under condemnation.</p>",
    "9": "<p><em>kî-ḵēn ṣiwwānî bĕḏĕḇar YHWH</em> — for so he commanded me by the word of YHWH. The man of God&#8217;s threefold prohibition — no bread, no water, no return by the same road — is the specific divine command (<em>dĕḇar YHWH</em> as binding obligation) that governs his mission. The prohibition against eating or drinking in Bethel signals the separateness required of YHWH&#8217;s messenger in a defiled cultic environment. The prohibition against returning by the same road is unexplained but may signal that the messenger&#8217;s presence has effected a one-directional change — the word has been spoken, cannot be unspoken, and the messenger cannot retrace it. This specific command will be the instrument of his death when he disobeys it (v.19).</p>",
    "10": "<p>He went home by a different route and did not return the way he came to Bethel. The obedience is precise: <em>wayyelek bĕdereḵ ʾaḥer</em> (went by another way) — verbal echo of the specific command. The man of God has fulfilled his mission at Bethel with complete fidelity. His vulnerability arises not from lack of obedience in the mission but from susceptibility to deception in the aftermath. The DtrH&#8217;s point is not that prophets are generally unreliable but that even the genuinely commissioned messenger can be deceived when he leaves his divine instruction and accepts human testimony over the divine word.</p>",
    "11": "<p>An old prophet (<em>nāḇîʾ ʾeḥāḏ zāqēn</em>) was living in Bethel; his sons reported to him what the man of God had done that day in Bethel. The old Bethel prophet is an enigmatic figure — why does a prophet of YHWH live at Jeroboam&#8217;s cult center? He may be a resident prophet who has compromised with the existing religious establishment, or he may be genuinely prophetic but operating within a corrupted cultic context. His sons witnessed the entire Bethel event; their report to their father sets up the old prophet&#8217;s deceptive pursuit of the man of God.</p>",
    "12": "<p>The sons showed their father the road the man of God from Judah had taken. The detail that the sons saw the road and reported it to their father is the narrative preparation for the pursuit. The old prophet&#8217;s knowledge of the man of God&#8217;s route enables his deception. The narrator does not explain the old prophet&#8217;s motivation for pursuing and deceiving the man of God — whether envy, curiosity, or something more sinister. The moral ambiguity of the old Bethel prophet is one of the chapter&#8217;s most theologically dense elements.</p>",
    "13": "<p>&#8220;Saddle the donkey for me&#8221; (<em>ḥābĕšû-lî haḥămôr</em>) — the old prophet&#8217;s urgency is expressed in the command-form. The donkey as transport reflects the same economic world as 1 Sam 9 — the significant animal whose saddling marks a journey with purpose. The sons saddle it and the old prophet rides after the man of God. The deliberate pursuit of the man of God by the old prophet — on a donkey, covering the same road in reverse — is the setup for the decisive deception of v.18.</p>",
    "14": "<p>He found him sitting under an oak tree (<em>yôšēḇ taḥat hāʾallôn</em>). The oak tree as resting spot after the prophetic mission — the man of God sitting in the shade after his task — is a moment of vulnerability. The sitting man who has completed his work is more susceptible to social interaction than the moving man with mission-focus. The old prophet&#8217;s first question — &#8220;Are you the man of God who came from Judah?&#8221; — establishes identification before the deceptive invitation of v.15.</p>",
    "15": "<p>&#8220;Come home with me and eat bread.&#8221; The invitation is the same as Jeroboam&#8217;s (v.7) but without the gift-component — it is presented as simple hospitality rather than patronage. The repetition of the identical invitation (with slight variation) that the man of God has already refused once is the test of his faithfulness to the divine command. That he succumbs to the old prophet&#8217;s version when he resisted the king&#8217;s reveals that the social authority of a fellow prophet is more persuasive than royal patronage in breaking down his resolve.</p>",
    "16": "<p>The man of God&#8217;s response is identical to his response to Jeroboam (vv.8-9): &#8220;I cannot go back with you or go in with you; I will not eat bread or drink water with you in this place.&#8221; His initial response to the old prophet is correct — the <em>dĕḇar YHWH</em> binding him is cited again (<em>lōʾ-ʾûḵal lāšûḇ ʾittĕḵā</em>). His correct refusal in v.16 sets up the tragedy of his capitulation in v.19 — demonstrating that the failure was not a simple moral lapse but a doctrinal error: he accepted a claimed prophetic word over the actual word already received from YHWH.</p>",
    "17": "<p><em>dāḇār YHWH ʾēlay lēʾmōr lōʾ-tōʾkal leḥem wĕlōʾ-ṯišteʾ-māyim šām</em> — a word of YHWH was spoken to me saying: Do not eat bread or drink water there. The man of God states the specific divine command clearly in refusing the old prophet&#8217;s invitation. The clarity of his knowledge of the command — he can articulate it precisely — makes his subsequent failure to abide by it more tragic. He is not confused about the command; he is convinced by a false word that the command has been modified. The epistemological problem is the addition of a second (false) prophetic word to the first (true) one.</p>",
    "18": "<p><em>gam-ʾănî nāḇîʾ kāmôḵā ûmalʾāḵ dibbēr ʾēlay bĕḏĕḇar YHWH lēʾmōr hăšibēhû ʾittĕḵā ʾel-bêteḵā wĕyōʾkal leḥem wĕyišteʾ-māyim kāzēḇ lô</em> — I too am a prophet like you, and an angel spoke to me by the word of YHWH saying: Bring him back with you to your house so he may eat bread and drink water. He lied to him. The narrator&#8217;s insertion — <em>kāzēḇ lô</em> (he lied to him) — is one of the most direct authorial intrusions in the Hebrew Bible. The claim to prophetic authority plus angelic mediation was designed to override the man of God&#8217;s direct divine command. The word <em>kāzēḇ</em> (H3577, a lie) leaves no ambiguity: the angel story is fabricated. The DtrH&#8217;s point is that a claimed prophetic word that contradicts a received divine command must be rejected, regardless of the authority claimed (cf. Gal 1:8: &#8220;if we or an angel from heaven should preach a gospel contrary to the one we preached...&#8221;).</p>",
    "19": "<p>The man of God went back with him and ate and drank in his house. The capitulation to the false prophetic word is described with stark simplicity. The man of God has violated his specific divine command on the basis of a claimed competing prophetic authority. The DtrH&#8217;s theological point is precise: the word of YHWH already received is normative; a subsequent word that contradicts it, however it is packaged (even as angelic mediation), is not to be believed (cf. Deut 13:1-5). The man of God&#8217;s failure is not a moral failure but a theological one — he privileges social authority over the word already given.</p>",
    "20": "<p>While they were sitting at the table, the <em>dĕḇar YHWH</em> came to the prophet who had brought him back. The divine word now comes through the very prophet who lied — the same channel of the false word is now the channel of true judgment. YHWH&#8217;s use of the false prophet as the instrument of true pronouncement against the man of God he deceived is a severe irony: the lie becomes the occasion for the truth it attempted to suppress. The authenticity of this word (unlike v.18) is confirmed by its fulfillment (vv. 24-26).</p>",
    "21": "<p><em>yaʿan kî mārîṯā pî YHWH</em> — because you disobeyed the mouth of YHWH. The charge is direct: <em>māraʾ</em> (H4784, to be rebellious/disobedient) against <em>pî YHWH</em> (the mouth of YHWH — YHWH&#8217;s direct spoken word). The man of God&#8217;s sin is defined precisely: not general moral failure but specific disobedience to a specific divine command. The category <em>māraʾ</em> is used for Israel&#8217;s rebellion in the wilderness (Num 20:24; 27:14) — the same vocabulary connects the individual prophet&#8217;s failure to the national pattern.</p>",
    "22": "<p>Because he returned and ate bread and drank water in the place where YHWH had told him not to, his body would not come to the tomb of his fathers (<em>lōʾ-yāḇôʾ nĕḇilātĕḵā ʾel-qeḇer ʾăḇōṯêḵā</em>). The specific punishment — denial of burial in the ancestral tomb — is a severe covenant curse. In Israelite theology, burial with one&#8217;s fathers was the completion of the covenant inheritance; to be denied it was to be cut off from the community&#8217;s covenantal continuity. <em>nĕḇēlāh</em> (H5038, corpse) is the term for an unburied or dishonored body — the man of God dies and his body lies on the road, consumed by a lion, which is the opposite of the honored burial he expected.</p>",
    "23": "<p>After the man of God had eaten and drunk, the old prophet saddled the donkey for him. The hospitality that was the vehicle of the deception is now completed with full courtesy — the old prophet saddling the donkey for his guest&#8217;s departure. The ordinary social courtesies continue even after the word of judgment has been pronounced. The man of God departs not knowing that the word of judgment he just heard from the prophet who deceived him will be immediately executed on the road.</p>",
    "24": "<p>A lion met him on the road and killed him. The lion stands beside the body; the donkey also stands beside it. The lion that kills the man of God is YHWH&#8217;s instrument of covenant discipline — the lion as covenant executor appears also in 2 Kgs 17:25-26 (lions sent by YHWH against the non-Israelites who resettled Samaria) and in the covenant curse list (Lev 26:22: wild animals that devour). The lion does not eat the body nor harm the donkey — its task is execution, not consumption. The restraint of the lion is the supernatural evidence that this death is judicial, not accidental predation.</p>",
    "25": "<p>Men passing by saw the body on the road with the lion standing beside it and reported it in the city where the old prophet lived. The public visibility of the scene — the lion standing beside the body without eating it — is the self-authenticating nature of the divine judgment. The news reaches the old prophet who had been the proximate cause of the man of God&#8217;s return. The passers-by&#8217;s report begins the chain of events that will bring the man of God to burial — ironically through the very prophet who had caused his death.</p>",
    "26": "<p><em>ʾîš hāʾĕlōhîm hûʾ ʾăšer māraʾ ʾeṯ-pî YHWH wayyittĕnēhû YHWH lāʾărî</em> — It is the man of God who disobeyed the mouth of YHWH; YHWH has given him to the lion. The old prophet&#8217;s recognition-speech is simultaneously his testimony against himself — the prophet who lied and caused the man of God&#8217;s disobedience now identifies the judicial execution as YHWH&#8217;s action. The formula <em>wayyittĕnēhû YHWH lāʾărî</em> (YHWH gave him to the lion) uses the divine-agency formula for judicial execution.</p>",
    "27": "<p>The old prophet saddles the donkey a second time — the same action as in v.13, forming the chapter&#8217;s narrative bracket. The first saddling initiated the deception; the second initiates the act of respect for the deceased. The chapter&#8217;s moral complexity is concentrated in the old prophet: deceiver, recipient of true prophetic word, and ultimately the one who buries and mourns the man he destroyed.</p>",
    "28": "<p>He found the body on the road — the lion and donkey still standing beside it, the lion had not eaten the body nor harmed the donkey. The restated observation of the lion&#8217;s restraint (cf. v.24) is the double-witness to the supernatural character of the execution. The body lying honorably on the road — uneaten despite a lion standing guard — is a visually paradoxical image of both judgment and dignity. The DtrH preserves the detail because the lion&#8217;s restraint authenticates the divine agency.</p>",
    "29": "<p>The old prophet picked up the man of God&#8217;s body, laid it on the donkey, and brought it back to the city to mourn and bury him. The act of retrieval and proper burial — despite the judgment that the man of God&#8217;s body would not reach his fathers&#8217; tomb — is the old prophet&#8217;s act of covenant honor for the deceased. The mourning (<em>yisspōḏ</em>, H5594, to beat the breast/lament) is genuine; the burial in the old prophet&#8217;s own tomb is an act of covenant solidarity with the one he had caused to die.</p>",
    "30": "<p><em>wayyisspōḏ ʾālāyw ʾôy ʾāḥî</em> — he mourned over him: &#8220;Alas, my brother!&#8221; The lament formula <em>hôy ʾāḥî</em> (woe/alas, my brother) is the covenant mourning cry (cf. Jer 22:18 where the same formula is denied to the wicked king — the denial of the mourning-cry is itself a curse). The old prophet&#8217;s &#8220;my brother&#8221; (<em>ʾāḥî</em>) acknowledges the prophetic brotherhood between them — two men of God, one deceived by the other. The mourning is genuine even as the old prophet bears responsibility for the death.</p>",
    "31": "<p><em>wayĕhî ʾaḥărê qobrô ʾōṯô wayyōʾmer ʾel-bānāyw</em> — after he buried him, he said to his sons: &#8220;When I die, bury me in the same grave as the man of God.&#8221; The old prophet&#8217;s final wish — burial alongside the man he deceived — is the expression of his confidence in the man of God&#8217;s oracle. By choosing burial in the same tomb, he is placing himself under the protection of the man of God&#8217;s prophetic authority — specifically the Josiah prophecy of v.2. The tomb at Bethel will be spared when Josiah desecrates the other tombs (2 Kgs 23:17-18: Josiah saw the marker of the man of God&#8217;s tomb and preserved it). The old prophet&#8217;s deathbed wish is both an act of penitence and a prophetic foresight.</p>",
    "32": "<p><em>kî hāyôʾ yihyeh haddāḇār ʾăšer qārāʾ bĕḏĕḇar YHWH ʾal-hammizḇēaḥ</em> — for the word he proclaimed by the word of YHWH against the altar in Bethel will surely come to pass. The old prophet&#8217;s posthumous testimony to the reliability of the man of God&#8217;s oracle is stated in the emphatic infinitive absolute construction (<em>hāyôʾ yihyeh</em>) — &#8220;it will surely, certainly come to pass.&#8221; The prophet who lied about angelic messages now attests truly to the prophetic word he had sought to suppress. His final testimony validates the oracle he had attempted to circumvent.</p>",
    "33": "<p><em>wĕʾaḥar haddāḇār hazzeh lōʾ-šāb yārāḇʿām middarkô hārāʿāh</em> — even after this, Jeroboam did not turn from his evil way. The <em>lōʾ-šāb</em> (did not turn) is the DtrH&#8217;s repentance formula in reverse: the covenant call to <em>šûḇ</em> (return/repent, H7725) was not heeded. &#8220;After this&#8221; (<em>ʾaḥar haddāḇār hazzeh</em>) refers to the signs, the withered hand, and the entire ch13 episode — Jeroboam witnessed prophetic authentication of YHWH&#8217;s word and still continued appointing non-Levitical priests for the high places. The hardened king is the DtrH&#8217;s object lesson: miraculous signs do not produce repentance in those who have decided against the covenant.</p>",
    "34": "<p><em>wayhî baddāḇār hazzeh lĕḥaṭṭāʾṯ bêṯ-yārāḇʿām</em> — this became the sin of the house of Jeroboam, to cut it off and to wipe it from the face of the earth. The summary formula closes the Jeroboam section with the DtrH&#8217;s verdict: the <em>ḥēṭ</em> (sin/transgression) is not merely personal but dynastic — it will &#8220;cut off&#8221; (<em>lĕhakrît</em>, H3772, to cut off/exterminate, the covenant curse term of Lev 26:30) the entire Jeroboam dynasty. <em>mĕḥôṯ ûlĕʾabbēḏ</em> (to destroy and to cause to perish) — two verbs of complete elimination. The founding apostasy of the northern kingdom carries within it the sentence of the entire dynasty&#8217;s destruction.</p>"
  },
  "14": {
    "1": "<p>At that time (<em>bāʿēṯ hahîʾ</em>) Jeroboam&#8217;s son Abijah became ill. The notice connects this episode to the preceding material — the &#8220;that time&#8221; is the period of Jeroboam&#8217;s consolidation of the northern apostasy. The illness of the crown prince is the occasion for Jeroboam&#8217;s consultation of the prophet Ahijah — the same prophet who had announced Jeroboam&#8217;s election (11:29-39). The king who rejected YHWH&#8217;s covenant worship still turns to YHWH&#8217;s prophet in crisis; the pattern of selective religious use (consulting YHWH only when personally in need) is a form of the covenant violation it accompanies.</p>",
    "2": "<p>Jeroboam instructs his wife to disguise herself so no one will know she is Jeroboam&#8217;s wife, then go to Shiloh to consult Ahijah. The disguise (<em>hišṯannê</em>, from <em>šānāh</em>, H8138, to change/disguise) is Jeroboam&#8217;s attempt to conceal his identity from the prophet — as if the prophet&#8217;s knowledge were merely human. The choice of Shiloh is significant: the ancient covenant sanctuary where the ark rested (1 Sam 1-4), now superseded by the Jerusalem temple and Jeroboam&#8217;s Bethel-Dan installations. Jeroboam consults the authentic YHWH-prophet at the authentic covenant site while maintaining his own false cult elsewhere — the contradiction revealing his theological duplicity.</p>",
    "3": "<p>The wife takes ten loaves, some cakes, and a jar of honey — a modest consultation gift (cf. 1 Sam 9:7-8 where a quarter shekel was given to Samuel). The specific provisions — <em>lōḥem ûniqquḏîm ûḇaqqbuqiṯ dĕḇaš</em> — are ordinary food items, not royal gifts. The disguise extends to the modest gift: by sending ordinary hospitality-provisions rather than royal gifts, Jeroboam attempts to present his wife as a common petitioner. Ahijah will reveal the identity regardless — his blindness makes the disguise irrelevant to him; his prophetic sight makes it irrelevant to YHWH.</p>",
    "4": "<p>Jeroboam&#8217;s wife came to Ahijah&#8217;s house in Shiloh. Ahijah could not see because his eyes were set (<em>kāmû ʿênāyw</em>) from old age. The blindness of the old prophet — established before his identification of Jeroboam&#8217;s wife — is the narrative preparation for the supernatural recognition in v.6. The physical blindness contrasts with the prophetic sight: Ahijah cannot see with eyes but YHWH had already told him who was coming. The same dynamic recurs with the blind Isaac in Gen 27 (where the blindness created an opportunity for deception) — here it creates an opportunity for demonstration of prophetic (YHWH-given) knowledge over against human (disguise-based) concealment.</p>",
    "5": "<p>But YHWH had told Ahijah: &#8220;The wife of Jeroboam is coming to you — she will ask you about her son, who is sick.&#8221; YHWH&#8217;s preemptive disclosure to the prophet is the standard prophetic preparation narrative (cf. 1 Sam 9:15-16 where YHWH told Samuel about Saul the day before his arrival). The prophet who has been told in advance receives the disguised visitor with full knowledge, making the disguise irrelevant. The command to Ahijah — <em>kōh wĕḵōh tĕdabbēr ʾēlêhā</em> (say this and this to her) — shows the prophetic oracle as YHWH&#8217;s direct speech through the prophet, not the prophet&#8217;s independent composition.</p>",
    "6": "<p><em>wayyishmaʿ ʾăḥiyyāh ʾeṯ-qôl raglêhā bāʾāh bappetaḥ</em> — Ahijah heard her footstep at the door. The prophet&#8217;s hearing in place of sight is the DtrH&#8217;s subtle irony: the blind prophet hears what the disguise cannot conceal. His greeting — &#8220;Come in, wife of Jeroboam. Why do you pretend to be someone else (<em>lāmmāh zōʾ miṯnaḵrîy</em>)?&#8221; — penetrates the disguise immediately. <em>naḵar</em> in <em>miṯnaḵrîy</em> (H5234 Hithpael, to act as a stranger, disguise oneself) is the verb used for Joseph pretending to be a stranger to his brothers (Gen 42:7). The question &#8220;why do you disguise yourself?&#8221; exposes the futility of concealment before YHWH&#8217;s prophet.</p>",
    "7": "<p><em>lēḵ ʾimrî lĕyārāḇʿām</em> — Go, say to Jeroboam: thus says YHWH the God of Israel. The oracle begins with YHWH&#8217;s covenant title and his acts of election: &#8220;I raised you up (<em>ʾerimmōm</em>, H7311 Polel, to exalt/lift up) from among the people and made you <em>nāgîḏ</em> over my people Israel.&#8221; <em>nāgîḏ</em> (H5057, appointed leader/ruler) is the election vocabulary: YHWH appointed Saul (1 Sam 9:16; 10:1), David (2 Sam 5:2; 7:8), and Solomon (1 Chr 29:22) as <em>nāgîḏ</em> — the designation of the one whom YHWH has specifically chosen from among the people for covenant leadership. The contrast between YHWH&#8217;s generous election and Jeroboam&#8217;s response will structure vv. 8-9.</p>",
    "8": "<p><em>wāʾeqraʿ ʾeṯ-hammamlāḵāh mibêṯ dāwid wāʾettĕnāh lāḵ wĕlōʾ-hāyîṯā kĕʿaḇdî dāwid</em> — I tore the kingdom from the house of David and gave it to you; yet you have not been like my servant David. The contrast is explicit: YHWH gave the kingdom to Jeroboam as a gift; David is the covenant standard against which Jeroboam is measured. <em>ʿaḇdî dāwid</em> (my servant David) is the highest covenant designation — David kept my commandments and walked after me with all his heart (<em>bĕḵol-lĕḇāḇô</em>, H3824) doing only what was right in my eyes. The Deuteronomic standard of wholehearted covenant loyalty (<em>kol-lēḇāḇ</em>) is the baseline Jeroboam has violated.</p>",
    "9": "<p><em>wayyaʿaś rāʿōṯ mikkōl ʾăšer hāyû lĕpānêḵā wayyēleḵ wayyaʿaś lĕḵā ʾĕlōhîm ʾăḥērîm ûmaṣṣēḵôṯ lĕhakʿisēnî</em> — you have done more evil than all who were before you, making for yourself other gods and cast images, to provoke me to anger. <em>hakkĕʿîs</em> (H3707, to provoke to jealousy/anger) is the technical term for covenant-violation through idolatry (Deut 31:29; 32:21). The golden calves are classified as <em>ʾĕlōhîm ʾăḥērîm</em> (other gods) — not merely representations of YHWH but functionally equivalent to the foreign gods that the covenant prohibits. <em>wayyašlēḵ ʾōṯî ʾaḥăreḵā</em> (you cast me behind your back) — the idiom for contemptuous dismissal, as if YHWH were an inconvenient obligation to be discarded.</p>",
    "10": "<p><em>lāḵēn hinnî mēḇîʾ rāʿāh ʾel-bêṯ yārāḇʿām</em> — therefore I am bringing disaster on the house of Jeroboam. The <em>hinnênî</em> (behold me/I am) formula introduces direct divine action. The dynastic curse formula — &#8220;I will cut off from Jeroboam every male, slave or free in Israel&#8221; (<em>kol-māgûr ûsāḡûr bĕyiśrāʾēl</em>) — is the technical language for total dynastic elimination. <em>māgûr ûsāḡûr</em> is an idiomatic pair meaning everyone without exception (cf. the same formula in Deut 32:36; 1 Kgs 21:21). &#8220;As one burns dung until it is gone&#8221; (<em>ûḇiʿartî ʾaḥărê bêṯ yārāḇʿām kaʾăšer yĕbaʿer haggālāl ʾaḏ-tummô</em>) — the dung-burning metaphor for complete, undignified elimination of the dynasty.</p>",
    "11": "<p>Dogs will eat those of Jeroboam who die in the city; birds of the air will eat those who die in the countryside. The double curse — dogs in the city, birds in the field — is the covenant curse of unburied death (Deut 28:26: &#8220;your carcass shall be food for all birds of the air and for the beasts of the earth&#8221;). The denial of proper burial is the severest expression of covenant judgment. The formula applies to Jeroboam&#8217;s entire household — the same fate announced for Ahab&#8217;s house (21:24) and for the house of Baasha (16:4) — suggesting a standard DtrH formula for dynasties under covenant judgment.</p>",
    "12": "<p><em>qûmî lĕḵî lĕḇêṯēḵ bĕḇôʾ raglayiḵ hāʿîrāh wāmēṯ hayyāleḏ</em> — get up and go home. When your feet enter the city, the child will die. The immediately fulfilled sign-prediction (the child dying when she crosses the threshold) is the authenticating portent for the longer-term dynasty-doom oracle. The child&#8217;s death is simultaneously punishment (on the house of Jeroboam) and mercy (on the child himself, as v.13 explains). The threshold-crossing is a precise trigger — the moment she re-enters Jeroboam&#8217;s household, the child dies. The child is the last good thing in the house of Jeroboam; his death removes it.</p>",
    "13": "<p><em>wĕhûʾ lĕḇaddô yiqqāḇēr lĕyārāḇʿām</em> — he alone of Jeroboam&#8217;s house will come to burial (<em>lĕ qĕḇûrāh</em>). The explanation: &#8220;in him alone, in the house of Jeroboam, was found something good (<em>daḇar ṭôḇ</em>) before YHWH the God of Israel.&#8221; <em>dāḇār ṭôḇ</em> (a good word/thing) — the precise content is unstated but the structural point is clear: among all the members of Jeroboam&#8217;s household, only this child retained some genuine covenant orientation. The proper burial is the covenant mercy extended specifically to the one in whom good was found. YHWH&#8217;s judicial precision extends to individuals within a condemned dynasty.</p>",
    "14": "<p><em>wĕhēqîm YHWH lô meleḵ ʿal-yiśrāʾēl ʾăšer yakrît ʾeṯ-bêṯ-yārāḇʿām</em> — YHWH will raise up for himself a king over Israel who will cut off the house of Jeroboam. The announcement of the dynasty&#8217;s divine replacement uses the same election vocabulary as Jeroboam&#8217;s own appointment (<em>hēqîm</em>, H6965, to raise up — the covenant appointment formula). The king YHWH will raise up is Baasha (1 Kgs 15:27-30), who fulfills this oracle by killing Jeroboam&#8217;s son Nadab and eliminating the entire dynasty. The pattern: YHWH appoints, dynasty fails, YHWH raises up a new dynasty — the cycle that characterizes the northern kingdom&#8217;s history until the Assyrian conquest.</p>",
    "15": "<p><em>wĕhikkāh YHWH ʾeṯ-yiśrāʾēl kaʾăšer yānûd hāqāneh bammāyim</em> — YHWH will strike Israel as a reed is shaken in the water. The simile of the water-reed (<em>qāneh bammāyim</em>) for Israel&#8217;s instability is a powerful image: the reed is rooted but bends completely with every current, having no stability of its own. <em>wĕnāṯaš ʾeṯ-yiśrāʾēl mēʿal hāʾădāmāh haṭṭôḇāh</em> — he will uproot Israel from this good land. The &#8220;good land&#8221; (<em>hāʾădāmāh haṭṭôḇāh</em>) is the covenant inheritance — YHWH&#8217;s gift to Israel at the conquest. The uprooting from the good land anticipates the Assyrian exile (722 BCE) — Ahijah is prophesying the northern kingdom&#8217;s end approximately 200 years before it occurs.</p>",
    "16": "<p><em>wĕyitēn ʾeṯ-yiśrāʾēl bĕgĕlal ḥaṭṭōʾṯ yārāḇʿām</em> — he will abandon Israel because of the sins of Jeroboam. The causal connection between Jeroboam&#8217;s foundational sins and the exile of the northern kingdom is the DtrH&#8217;s central theological claim about the north. The phrase &#8220;who sinned and who caused Israel to sin&#8221; (<em>ʾăšer ḥāṭāʾ wăʾăšer heḥĕṭîʾ ʾeṯ-yiśrāʾēl</em>) — Jeroboam as both personal sinner and national sin-instigator — will become the standard formula applied to virtually every northern king (1 Kgs 15:26,30,34; 16:2,19,26; 22:52; 2 Kgs 3:3; 10:29; etc.). The formula establishes Jeroboam as the paradigmatic covenant-violator against whom all northern kings are measured.</p>",
    "17": "<p>Jeroboam&#8217;s wife rose and left for Tirzah (<em>tirṣāh</em>) — the new royal city replacing Shechem/Penuel as Jeroboam&#8217;s capital. As she crossed the threshold (<em>kĕḇōʾāh bĕsap-habbayyiṯ</em>), the child died. The precise fulfillment of the threshold-trigger (v.12) is reported without embellishment: word-event correspondence at the moment specified. Tirzah (<em>tirṣāh</em>, H8656) is likely Tell el-Farʿah North, a major Iron Age site in the Samarian highlands. Its name means &#8220;pleasantness/favor&#8221; — the irony of a city whose name evokes divine pleasure being the site of the dynasty&#8217;s judgment-fulfillment.</p>",
    "18": "<p>They buried him and all Israel mourned for him, as YHWH had said through his servant Ahijah the prophet. The fulfillment notice — <em>kĕḏĕḇar YHWH ʾăšer dibbēr bĕyaḏ-ʿaḇdô ʾăḥiyyāh hannaḇîʾ</em> (according to the word of YHWH which he spoke through his servant Ahijah the prophet) — is the DtrH&#8217;s standard prophetic fulfillment formula. The child receives the mourning of all Israel (<em>wəkol-yiśrāʾēl yisspĕḏû-lô</em>) and proper burial — the covenant honor that the rest of Jeroboam&#8217;s dynasty will be denied. The fulfillment of the specific prediction validates the wider oracle against the dynasty.</p>",
    "19": "<p>The rest of the acts of Jeroboam — how he made war and how he reigned — are recorded in the Book of the Chronicles of the Kings of Israel (<em>sēper diḇrê hayyāmîm lĕmalkê yiśrāʾēl</em>). The reference to the &#8220;Book of the Chronicles of the Kings of Israel&#8221; is the DtrH&#8217;s standard citation formula for the official court annals — a royal archive now lost. The citation validates the historical claims while acknowledging that the DtrH is selective in its presentation, focusing on theological evaluation rather than comprehensive history.</p>",
    "20": "<p>Jeroboam reigned twenty-two years (<em>ʿeśrîm ûšĕtayim šānāh</em>) and rested with his ancestors (<em>wayyiškāḇ ʿim-ʾăḇōṯāyw</em>). The &#8220;rested with his ancestors&#8221; formula is the standard DtrH death notice. The length of Jeroboam&#8217;s reign — 22 years — is long for a northern king; most of the northern dynasty successions are violent and brief. His son Nadab succeeded him. The transition note is brief because the dynasty is already under the divine sentence announced in vv. 10-16; Nadab will be killed by Baasha in his second year (15:25-27).</p>",
    "21": "<p>Rehoboam son of Solomon reigned in Judah — forty-one years old at accession, seventeen-year reign, in Jerusalem the city YHWH had chosen from all the tribes of Israel to put his name there (<em>lāśûm ʾeṯ-šĕmô šām</em>). The <em>šēm</em> (Name) theology is the DtrH&#8217;s central formulation of the Deuteronomic presence-theology: YHWH does not dwell physically in the temple but causes his name to dwell there (Deut 12:5,11,21; 1 Kgs 8:29). His mother was Naamah the Ammonite (<em>nāʿămāh hāʿammônîṯ</em>) — Solomon&#8217;s foreign wife whose son now reigns over Judah. The Ammonite queen-mother is a notable datum: the Davidic dynasty&#8217;s heir is half-Ammonite, from exactly the foreign-wife marriages that 1 Kgs 11 condemned.</p>",
    "22": "<p><em>wayyaʿaś yĕhûḏāh hārāʿ bĕʿênê YHWH wayyaqnĕʾûhû miqqōl ʾăšer ʿāśû ʾăḇōṯām bĕḥaṭṭōʾṯêhem</em> — Judah did what was evil in YHWH&#8217;s eyes; with their sins they provoked him to jealousy more than all their ancestors had done. <em>qānāʾ</em> (H7065, to be jealous/provoke to jealousy) is the covenant-marriage term: YHWH&#8217;s relationship with Israel is covenantally spousal, and idolatry is adultery against the covenant spouse. &#8220;More than all their ancestors had done&#8221; is a superlative of covenant faithlessness — each generation&#8217;s apostasy is measured against the entire preceding tradition.</p>",
    "23": "<p>High places (<em>bāmôṯ</em>), sacred pillars (<em>maṣṣēḇôṯ</em>), and Asherah poles (<em>ʾăšērîm</em>) on every high hill and under every spreading tree. The triad of Canaanite cultic installations — high place, standing stone, Asherah pole — represents the full program of indigenous Levantine religion that Deuteronomy prohibited (Deut 7:5; 12:3; 16:21-22). The &#8220;every high hill and spreading tree&#8221; (<em>kol-gibʿāh gĕḇōhāh wĕtaḥat kol-ʿēṣ raʿănān</em>) is the DtrH&#8217;s formulaic description of Canaanite sanctuary topography — the same formula used for Israel&#8217;s pervasive cultic apostasy throughout Kings and the prophets (cf. Jer 2:20; 3:6; Ezek 6:13).</p>",
    "24": "<p><em>wĕgam-qāḏēš hāyāh bāʾāreṣ</em> — there were also <em>qĕḏēšîm</em> in the land. <em>qāḏēš</em> (H6945, consecrated person, male cult prostitute) designates the shrine-functionary who participated in Canaanite fertility rituals. The DtrH regards this as the most extreme marker of Canaanite assimilation: &#8220;they did all the abominations (<em>ḵol-tôʿăḇōṯ haggerôyim</em>) of the nations which YHWH drove out before the Israelites.&#8221; <em>tôʿēḇāh</em> (H8441, abomination) is the strongest DtrH term for proscribed practices — the cult prostitution represents complete assimilation to what the Canaanite dispossession was designed to eliminate from the land.</p>",
    "25": "<p>In Rehoboam&#8217;s fifth year, Shishak (<em>šîšaq</em>) king of Egypt came up against Jerusalem. <em>šîšaq</em> is Shoshenq I (Sheshonq I), founder of Egypt&#8217;s 22nd dynasty (ruled ca. 945-924 BCE) — the first externally corroborated event in the Kings narrative (corroborated by Shoshenq&#8217;s own victory inscription at Karnak, which lists over 150 conquered cities including sites in both Judah and Israel). His campaign (ca. 926-925 BCE) is a historically verifiable event that anchors the DtrH chronology in Egyptian records. Rehoboam&#8217;s fifth year = ca. 926 BCE.</p>",
    "26": "<p><em>wayyiqqaḥ ʾeṯ-ʾōṣrôṯ bêṯ-YHWH wĕʾeṯ-ʾōṣrôṯ bêṯ-hammelek hakkōl lāqāḥ</em> — he took the treasures of the house of YHWH and the treasures of the royal palace — he took everything. The formula &#8220;he took everything&#8221; (<em>hakkōl lāqāḥ</em>) is the DtrH&#8217;s verdict on total plunder. The golden shields that Solomon had made — 300 large shields, 200 small (1 Kgs 10:16-17) — are included in the plunder. The golden shields were ceremonial objects of Solomonic wealth; their removal begins the visible deterioration of Davidic royal splendor.</p>",
    "27": "<p>In their place Rehoboam made bronze shields (<em>māginnê nĕḥōšeṯ</em>) and gave them to the commanders of the palace guard. The substitution of bronze for gold is the DtrH&#8217;s most economical symbol of Judah&#8217;s covenantal diminishment: the gold of Solomon&#8217;s kingdom replaced by the bronze of a lesser king. The visual image is deliberate — bronze looks like gold from a distance but is worth far less. The reduced kingdom maintains the forms of Solomonic glory without the substance. The shield substitution will become a recurring image in the Kings narrative for the gap between covenant promise and covenant reality.</p>",
    "28": "<p>Whenever the king went to the house of YHWH, the guard carried the shields and then returned them to the guard room. The ceremonial function of the bronze shields — carried in procession, returned to storage — preserves the ritual form of the Solomonic guard-procession while demonstrating the diminishment of its material. The DtrH records this detail because it captures the entire Rehoboam period: the form of the Solomonic covenant maintained, the substance diminished. Cultic continuity in the midst of covenantal decline is a persistent DtrH theme.</p>",
    "29": "<p>The rest of Rehoboam&#8217;s acts are written in the Book of the Chronicles of the Kings of Judah (<em>sēper diḇrê hayyāmîm lĕmalkê yĕhûḏāh</em>). The Judean chronicle citation parallels the Israelite citation in v.19, establishing the DtrH&#8217;s dual source-protocol for northern (Israel) and southern (Judah) kings. The Judean chronicles are a separate archive from the Israelite chronicles — distinct royal administrations maintaining their own records from the division onward.</p>",
    "30": "<p>There was war between Rehoboam and Jeroboam all their days (<em>kol-hayyāmîm</em>). The summary of continuous warfare between the divided kingdoms is the DtrH&#8217;s indictment of the division&#8217;s consequences: the covenant brother-kingdoms are perpetually at war. The warfare consumes the military resources that Solomon had used against external enemies; the north and south bleed each other while external threats (Shishak) exploit the weakness. The summary frames the period as one of unrelieved covenant-dysfunction.</p>",
    "31": "<p>Rehoboam rested with his ancestors and was buried with them in the city of David (<em>ʿîr dāwid</em>). The burial in the city of David — Jerusalem, the Davidic capital — is the standard honorable burial for Judahite kings, contrasting with the denials of burial that the DtrH records for apostate dynasties. His mother&#8217;s name is given again: Naamah the Ammonite. The DtrH&#8217;s repetition of the Ammonite-queen-mother datum (cf. v.21) frames Rehoboam&#8217;s reign within the problematic foreign-marriage legacy of Solomon. His son Abijam succeeded him — the Davidic dynasty continues despite the covenant failures.</p>"
  }
}

def main():
    c = load_comm('original', '1kings')
    merge_comm(c, ORIGINAL)
    save_comm('original', '1kings', c)
    total = sum(len(v) for v in ORIGINAL.values())
    print(f'1kings mkt-original: wrote {total} verses across ch 12-14')

if __name__ == '__main__':
    main()
