"""
MKT Original — Job chapters 22–26
Run: python3 scripts/zc-original-job-22-26.py

Ch22: Eliphaz's third speech — direct accusations against Job. Key terms:
      taḥbol ʾaḥîkā (seize collateral, v6), ʾalmānôt/yĕtōmîm (widows/orphans, vv7-9),
      haskēn (make peace/profit, v21), šadday yihy lĕkā bĕṣer (Almighty as your gold, v25).
Ch23: Job's response — the hidden God. Key terms:
      mārî (complaint/rebellion, v2), bāḥan (tried like metal, v10), bĕʾeḥāḏ (resolute, v13).
Ch24: Job on hidden injustice. Key terms:
      ʿittîm (appointed times, v1), gĕbûlôt (boundary stones, v2), ṣāʿaq (cry, v12),
      rĕpāʾîm (shades/Rephaim, v14 context), rimmāh (worm, v20).
Ch25: Bildad's third brief speech. Key terms:
      miśrāh (dominion, v2), yiṣdaq (be declared righteous, v4), tôlāʿat (worm, v6).
Ch26: Job's sarcasm + doxology. Key terms:
      tōhû (void, v7), rāhaḇ (sea dragon, v12), nāḥāš bārîaḥ (twisting serpent, v13),
      ʾabaddôn (Abaddon, v6), qĕṣôt dĕrākāyw (edges of his ways, v14).
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(layer, book):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    return json.loads(p.read_text()) if p.exists() else {}

def save_comm(layer, book, data):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

JOB = {
  "22": {
    "1": "<p>Eliphaz's third speech opens with the standard formula. This is his most direct speech: he abandons general argument and launches specific accusations against Job.</p>",
    "2": "<p><span class='term'>Hăyiskōn lĕʾēl gāber</span>: 'Can a human be of use to God?' — <span class='term'>sākan</span> (to be useful/profitable, to have advantage): the commercial term applied to the human-divine relationship. Eliphaz's argument: since humans cannot profit God, God's judgment of Job cannot be motivated by self-interest — it must be pure justice responding to Job's sin. The logic will be refuted in 40:1-5.</p>",
    "3": "<p><span class='term'>Ḥēpeṣ lĕšadday</span>: 'Does the Almighty take pleasure?' — <span class='term'>ḥāpeṣ</span> (desire, delight, pleasure) is the will-term. <span class='term'>Biṣdāqĕtĕkā</span> (in your being righteous) and <span class='term'>tĕtammîm dĕrākêkā</span> (in your walking blameless paths): these are the Job-identity terms from 1:1. Eliphaz implicitly denies that God would care about such righteousness — a position God directly refutes in the prologue and epilogue.</p>",
    "4": "<p><span class='term'>Hayirʾātĕkā</span>: 'Is it because of your fear/reverence?' — the sarcastic pivot: Eliphaz claims Job's trouble cannot be divine response to his piety. <span class='term'>Yāḇôʾ ʿimmĕkā bammišpāṭ</span>: 'he enters into judgment with you' — the legal term <span class='term'>mišpāṭ</span> (judgment, legal proceeding). Eliphaz's claim: God would not bother with a lawsuit just because Job is pious.</p>",
    "5": "<p><span class='term'>Rabbāh rāʿātĕkā</span>: 'Your wickedness is immense' — the direct accusation. <span class='term'>Rabbāh</span> (great, immense) and <span class='term'>ʾên-qēṣ</span> (without end): the unprecedented scope of the charges Eliphaz is about to fabricate. The hyperbole reveals the poverty of his evidence.</p>",
    "6": "<p><span class='term'>Taḥbol ʾaḥêkā ḥinnām</span>: 'You seized collateral from your kinsmen without reason' — <span class='term'>ḥābal</span> (to take a pledge/collateral): the legal-economic act of debt-collateral, regulated in Deut 24:10-13 to protect the poor. <span class='term'>Ḥinnām</span> (for nothing, without cause): the same word used of the adversary's challenge in 1:9 — Job suffered ḥinnām; now Eliphaz accuses Job of sinning ḥinnām. <span class='term'>Tĕpassēṭ lĕḇûšîm</span>: 'you stripped people of clothes' — the specific violation of Deut 24:12-13.</p>",
    "7": "<p><span class='term'>Mayim ʿāyēp lōʾ hišqîtāh</span>: 'You have not given water to the weary' — the specific breach of desert hospitality, a capital moral failure in the ANE. <span class='term'>Lāʾeh</span> (weary traveler) and <span class='term'>rāʿēb</span> (starving/hungry): the two most vulnerable conditions. These charges have no basis in the narrative — Eliphaz invents them to fit his retributive scheme.</p>",
    "8": "<p><span class='term'>ʾîš zĕrôaʿ lô hāʾāreṣ</span>: 'The man of strong arm possessed the land' — <span class='term'>zĕrôaʿ</span> (arm/strength) as the means of land acquisition by force. <span class='term'>Nĕśûʾ pānîm</span> (man of high standing/lifted face): social status that enables land-seizure. Eliphaz implies Job was such a man — benefiting from structural injustice.</p>",
    "9": "<p><span class='term'>ʾAlmānôt šillaḥtā rêqām</span>: 'You have sent away widows empty-handed' — <span class='term'>ʾalmānāh</span> (widow) is one of the covenant-care triad (orphan, widow, stranger) whose protection defines covenant faithfulness (Deut 10:18; 14:29). <span class='term'>Zĕrōʿôt yĕtōmîm yĕdukkāʾ</span>: 'the strength of orphans is crushed' — <span class='term'>dāḵāʾ</span> (to crush) — the most vulnerable social categories systematically oppressed. These are the very categories Job claims to have protected (29:12-16).</p>",
    "10": "<p><span class='term'>Pāḥîm sĕḇîḇôtêkā</span>: 'That is why traps are all around you' — the causal connector: Eliphaz's retributive logic applied. <span class='term'>Paḥaḏ piṯʾōm yĕḇahălekā</span>: 'sudden terror terrifies you' — <span class='term'>paḥad piṯʾōm</span> (sudden terror/dread): the paired wisdom term for divine surprise-judgment (Prov 3:25; Isa 47:11).</p>",
    "11": "<p><span class='term'>ʾôr lōʾ-tirʾeh</span>: 'darkness so dense you cannot see' — light is the metaphor for divine presence and moral clarity. <span class='term'>Šeṭep mayim yĕkassekā</span>: 'a flood of waters sweeps over you' — the flood-judgment image (cf. Ps 69:1-2). Eliphaz applies the full weight of covenant-curse vocabulary to Job's condition.</p>",
    "12": "<p><span class='term'>ʾĔlôah gōbah šāmayim</span>: 'Is not God in the heights of heaven?' — the rhetorical question sets up Eliphaz's critique of Job's implied theology. <span class='term'>Rōʾš kôkābîm</span>: 'the top of the stars' — the highest point of the created order. Eliphaz is preparing to accuse Job of thinking God is too remote to see human affairs.</p>",
    "13": "<p><span class='term'>Wĕʾāmartā mah-yāḏaʿ ʾēl</span>: 'And you say, What does God know?' — Eliphaz puts these words in Job's mouth; Job never said them. <span class='term'>ʾărāpel yišpōṭ</span>: 'Can he judge through the dense cloud?' — <span class='term'>ʿărāpel</span> (deep darkness, storm-cloud): the same word used for the theophanic cloud at Sinai (Exod 20:21). Eliphaz inverts the theophanic vocabulary into an accusation of Job's supposed theology.</p>",
    "14": "<p><span class='term'>ʿābîm sēter-lô</span>: 'clouds screen him' — Eliphaz attributes to Job the belief that clouds prevent divine vision. <span class='term'>Ḥûg šāmayim yithallāk</span>: 'he walks only along the circuit of the sky' — <span class='term'>ḥûg</span> (circle, vault): the word used in 26:10 and Isa 40:22 for the circle of creation. Eliphaz reduces the transcendent God to a distant walker on the sky-vault.</p>",
    "15": "<p><span class='term'>Hăhăšmōr ʾōraḥ ʿôlām</span>: 'Will you keep to the old path?' — <span class='term'>ʾōraḥ ʿôlām</span> (ancient path/road of ages): the road of the wicked from of old. The implied accusation: Job is repeating the path of the pre-flood wicked.</p>",
    "16": "<p><span class='term'>Lōʾ-ʿēt quṣṣāpû</span>: 'cut down before their time' — <span class='term'>qāṣap</span> (to cut off prematurely): the violent early death of the wicked as confirmation of guilt. <span class='term'>Yûṣaq nāhār yĕsōḏām</span>: 'a river poured out their foundation' — flood-judgment as historical paradigm (the flood generation, Gen 6-7).</p>",
    "17": "<p><span class='term'>ʾĂšer ʾāmĕrû lāʾēl</span>: 'those who said to God, Leave us alone' — the refusal of divine claim, echoing the wicked generation's rejection. <span class='term'>Mah-yišʿad šadday lāhem</span>: 'What can the Almighty do to us?' — divine impotence asserted as basis for autonomous living. Eliphaz links Job's protests to this ancient rebellion.</p>",
    "18": "<p><span class='term'>Wĕhûʾ millēʾ ḇāttêhem ṭôb</span>: 'Yet he had filled their houses with abundance' — the paradox of the wicked prospered by God. <span class='term'>ʿAṣat rĕšāʿîm rāḥăqāh mimmennî</span>: 'the counsel of the wicked is far from me' — Eliphaz distances himself from the implications of his own observation; the statement begins to undermine his retributive case.</p>",
    "19": "<p><span class='term'>Yirʾû ṣaddîqîm wĕyiśmāḥû</span>: 'the righteous see their destruction and celebrate' — the divine reversal: the community of the righteous witnesses the fall of the wicked. <span class='term'>Nāqî yilaʿag lāmô</span>: 'the innocent man mocks them' — <span class='term'>lāʿag</span> (to mock, scoff): the derisive laughter of vindication.</p>",
    "20": "<p><span class='term'>ʾIm-lōʾ nikkĕdū qîmānû</span>: 'Surely our opponents are destroyed' — the confession of the righteous community. <span class='term'>ʾEšām ʾāḵlāh ʾēš</span>: 'what remained of them the fire has devoured' — the totality of destruction. Eliphaz is sketching a picture of where Job's path leads.</p>",
    "21": "<p><span class='term'>Haskēn-nāʾ ʿimmô</span>: 'Make peace with him now' — <span class='term'>sākan</span> returns: the same word from v2 (to be of use/profit) now means 'to be at peace/reconciled with.' The commercial term captures Eliphaz's transactional theology: reconciliation is profitable. <span class='term'>Wĕḇāhem tāḇôʾ tôḇātĕkā</span>: 'in that way good will come to you' — moralistic promise of conditional prosperity.</p>",
    "22": "<p><span class='term'>Qĕḥal-nāʾ mippiyw tôrāh</span>: 'Accept his instruction from his own mouth' — <span class='term'>qāḥal</span> (to receive, take) + <span class='term'>tôrāh</span> (instruction, teaching, law): the wisdom-reception formula. <span class='term'>Śîm ʾămārāyw bĕlibbĕkā</span>: 'store his words in your heart' — the Torah-internalization command (Deut 6:6; Ps 119:11).</p>",
    "23": "<p><span class='term'>ʾIm-tāšûḇ ʿad-šadday tibbāneh</span>: 'If you return to the Almighty, you will be restored' — <span class='term'>šûb</span> (to return, repent) + <span class='term'>bānāh</span> in Niphal (to be built up, restored): the restoration promise is conditional on repentance. <span class='term'>Tarḥîq ʿawlāh</span>: 'banish iniquity' — the practical repentance Eliphaz demands.</p>",
    "24": "<p><span class='term'>Šît-ʿal-ʿāpār beṣer</span>: 'treat your gold like ordinary dust' — <span class='term'>bāṣer</span> (gold/ore/precious metal) treated as <span class='term'>ʿāpār</span> (dust/earth/ground): the value-inversion that characterizes genuine repentance. <span class='term'>ʾôpîr</span> (Ophir): the famous gold-producing region of uncertain location (1 Kgs 9:28; 10:11), treated like stream-bed pebbles. The point is radical revaluation: when God becomes your wealth, earthly wealth loses its grip.</p>",
    "25": "<p><span class='term'>Wĕhāyāh šadday bĕṣārekā</span>: 'The Almighty himself will be your gold' — the great inversion: <span class='term'>šadday</span> (Almighty) as <span class='term'>bĕṣer</span> (gold/precious metal). <span class='term'>Wĕkesep tôʿăpôt lāk</span>: 'abundance of silver to you' — Eliphaz's invitation, however misapplied to Job, contains genuine theological insight: God himself as the supreme treasure replaces material wealth.</p>",
    "26": "<p><span class='term'>Kî-ʾāz ʿal-šadday titʿannāg</span>: 'Then you will take delight in the Almighty' — <span class='term'>ʿānag</span> (to delight, take pleasure in) with God as the object: cf. Ps 37:4 ('delight yourself in the Lord'). <span class='term'>Tiśśāʾ ʾel-ʾĕlôah pānêkā</span>: 'lift your face toward God' — the gesture of confidence before God, the opposite of shame (cf. Ezra 9:6).</p>",
    "27": "<p><span class='term'>Teʿtar ʾēlāyw weyišmāʿekā</span>: 'You will pray and he will hear you' — <span class='term'>ʿātar</span> (to pray fervently, implore) — the same root as the intercessory prayer of Job for his friends in 42:8-10. <span class='term'>Wĕnĕḏārêkā tĕšallēm</span>: 'you will fulfill your vows' — the completion of worship promised upon restoration. Eliphaz's promise accidentally describes the final chapter's reality (42:7-10).</p>",
    "28": "<p><span class='term'>Wĕtiqmōṣ mimmennî mišpāṭ ʿanî</span>: 'Whatever you determine will be settled' — <span class='term'>qāmaṣ</span> is difficult here; the MKT renders it as the righteous person's decisions taking effect. <span class='term'>ʿal-dĕrākêkā nōgah ʾôr</span>: 'light will shine on your paths' — the path-imagery of Proverbs wisdom, here promised upon repentance.</p>",
    "29": "<p><span class='term'>Kî-hišpîlû wattōʾmer gēwāh</span>: 'When others are brought low, you will say, There is hope' — <span class='term'>gēwāh</span> (pride/height, here: lifting-up, elevation — i.e., hope): when others experience humiliation, the restored person speaks words of hope. <span class='term'>Wĕyôšaʿ šĕpaḥ ʿênāyim</span>: 'he will save the one who bows his eyes' — the reversal pattern: the lowly exalted.</p>",
    "30": "<p><span class='term'>Yĕmallēṭ ʾî-nāqî</span>: 'He will rescue even the one who is not innocent' — a remarkable statement for Eliphaz: even the not-innocent can be rescued through the purity of another. <span class='term'>Wĕnimlat bĕbōr kappêkā</span>: 'he will be delivered through the cleanness/purity of your hands' — the intercessory dimension: one person's clean hands can secure another's deliverance. Eliphaz speaks truer than he knows: Job's prayer for his friends will effect their deliverance (42:8-9).</p>"
  },
  "23": {
    "1": "<p>Job's ninth speech begins without counter-accusation. He is no longer trying to refute Eliphaz; he is searching for God.</p>",
    "2": "<p><span class='term'>Gam-hayyôm mārî mĕrî</span>: 'Even today my complaint is bitter/rebellious' — <span class='term'>mārî</span> from <span class='term'>mārar</span> (to be bitter) or <span class='term'>mārāh</span> (to rebel): the ambiguity is intentional. Job's speech is simultaneously lament-bitterness and a kind of rebellion against his situation. <span class='term'>Yādî kāḇĕḏāh ʿal-ʾanḥātî</span>: 'the burden laid on me is heavier than my groaning can express' — <span class='term'>kāḇēḏ</span> (heavy, serious): the weight of his affliction exceeds his capacity to articulate it.</p>",
    "3": "<p><span class='term'>Mî-yittēn yāḏaʿtî</span>: 'If only I knew!' — the wish-formula expressing impossible longing (cf. 6:8; 11:5). <span class='term'>ʾEmṣāʾĕhû</span> (find him): the dominant verb of this chapter — the hidden God who cannot be located. <span class='term'>ʿAd-tĕḵûnātô</span>: 'to the place where he dwells/his establishment' — <span class='term'>tĕḵûnāh</span> (dwelling-place, throne-setting): the divine throne-room Job longs to reach.</p>",
    "4": "<p><span class='term'>ʾEʿĕrĕḵāh lĕpānāyw mišpāṭ</span>: 'I would lay my case before him in full order' — <span class='term'>ʿāraḵ</span> (to arrange, set in order): the legal preparation of a case, the same term as the altar-arrangement of sacrifice. Job would present a formally ordered lawsuit. <span class='term'>Ûpî ʾĕmallēʾ tôḵāḥôt</span>: 'fill my mouth with the strongest arguments' — <span class='term'>tôḵāḥat</span> (argument, proof, reproof): the formal counter-evidence.</p>",
    "5": "<p><span class='term'>ʾēḏĕʿāh millîm yaʿănēnî</span>: 'I would know what he would say in reply' — Job's primary desire is not vindication but comprehension: to understand God's response. <span class='term'>ʾāḇîn mah-yōmar lî</span>: 'and understand every word' — the listening dimension: Job wants to hear and understand, not merely prevail.</p>",
    "6": "<p><span class='term'>Hĕḇĕrōb-kōaḥ yārîḇ ʿimmî</span>: 'Would he use his vast power to overwhelm me in argument?' — <span class='term'>rîḇ</span> (to contend, argue at law): the legal dispute term. Job answers his own question: <span class='term'>lōʾ ʾak-hûʾ yāśîm bî</span> — 'No, he would give me a hearing.' The conviction that God would hear him in person is the bedrock of Job's faith.</p>",
    "7": "<p><span class='term'>Šām yāšār nôkāḥ ʿimmô</span>: 'There an upright man could argue his case before him' — <span class='term'>yāšār</span> (upright, straight, honest): Job's self-designation. <span class='term'>ʾăpallĕṭāh lāneṣaḥ miššōpĕṭî</span>: 'I would receive final acquittal from my judge' — <span class='term'>pālaṭ</span> (to escape, be delivered) + <span class='term'>lāneṣaḥ</span> (forever/finally): the permanent acquittal that Job is certain the direct encounter would produce.</p>",
    "8": "<p><span class='term'>Hēn qeḏem ʾehĕlōk wĕʾênennû</span>: 'I go east and he is not there' — the four-direction search for God. <span class='term'>Qeḏem/ʾāḥôr</span> (east/west) + <span class='term'>śĕmôʾl/yāmîn</span> (left/right — i.e., north/south): the exhaustive compass search. God's absolute hiddenness in the face of Job's suffering is the experiential problem the book wrestles with.</p>",
    "9": "<p><span class='term'>Śemôʾl bĕʿośĕhû wĕlōʾ-ʾāḥāz</span>: 'he works on the left and I cannot seize him' — <span class='term'>ʾāḥaz</span> (to grasp, take hold of): Job cannot grab hold of the God who is acting (note: God is working — <span class='term'>bĕʿăśōtô</span> — even when hidden). <span class='term'>Yaʿaṭōp yāmîn wĕlōʾ ʾerʾeh</span>: 'he conceals himself on the right and I cannot see him' — the active divine hiddenness: <span class='term'>ʿāṭāp</span> (to cover oneself, conceal) — God wrapping himself in hiddenness.</p>",
    "10": "<p><span class='term'>Kî-yāḏaʿ derek ʿimmādî</span>: 'But he knows the path I walk' — the pivot: Job cannot find God, but God knows Job. The asymmetry is the ground of faith. <span class='term'>Bĕḥānānî kazzāhāḇ ʾēṣēʾ</span>: 'when he has tried/tested me I will come out as gold' — <span class='term'>bāḥan</span> (to test, examine metal): the metallurgical refinement metaphor. Suffering as the smelting process that purifies rather than destroys.</p>",
    "11": "<p><span class='term'>Bĕʾăšurô ʾāḥăzāh raglî</span>: 'My foot has stayed on his track' — the path-metaphor for covenant faithfulness. <span class='term'>Darkô šāmartî wĕlōʾ ʾāṭ</span>: 'I have kept his way without turning off' — <span class='term'>nāṭāh</span> (to turn aside): the standard warning against apostasy. Job claims unbroken path-fidelity.</p>",
    "12": "<p><span class='term'>Miṣwat śĕpātāyw wĕlōʾ ʾāmîš</span>: 'I have not departed from his commands' — <span class='term'>mûš</span> (to depart, move away): the standing-order term (cf. Josh 1:8: 'let not this Book of Torah depart from your mouth'). <span class='term'>ʾImrê pîw ṣāpantî mēḥuqqî</span>: 'I have valued the words of his mouth more than my daily bread' — <span class='term'>ḥuqqî</span> (my statute/allotment/daily portion): Job prioritizes divine speech over physical sustenance, prefiguring Matt 4:4.</p>",
    "13": "<p><span class='term'>Wĕhûʾ bĕʾeḥāḏ ûmî yĕšîḇennû</span>: 'But he is resolute/one in purpose, and who can turn him?' — <span class='term'>bĕʾeḥāḏ</span> (in one thing, resolute): God's absolute singularity of purpose, which cannot be reversed. <span class='term'>Napšô ʾiwwĕtāh wayyaʿaś</span>: 'what his soul desires, that he does' — the divine will as both unconstrained and unfathomable. This is the God Job cannot argue around.</p>",
    "14": "<p><span class='term'>Yĕšallēm ḥuqqî wĕkāhēnnāh</span>: 'He will carry out what he has ordained for me' — <span class='term'>ḥōq</span> (statute, prescribed portion/decree): the divine allocation for Job is fixed and will be fulfilled. <span class='term'>Wĕrabbôt kāhēnnāh ʿimmô</span>: 'and there is much more still with him' — the divine purpose for Job exceeds what has been revealed; more is coming.</p>",
    "15": "<p><span class='term'>ʿal-kēn mippānāyw ʾebbāhēl</span>: 'That is why I am shaken before his face' — <span class='term'>bāhal</span> (to be dismayed, terrified, agitated): the theophanic dread. Job's faith and fear coexist: he wants to find God and yet dreads the encounter. <span class='term'>ʾĂḇîn wĕʾepḥad mimmennû</span>: 'when I understand, I am afraid of him' — comprehension increases rather than decreases the dread.</p>",
    "16": "<p><span class='term'>Wĕʾēl hērak libbî</span>: 'God has made my heart soft/weak' — <span class='term'>rāḵaḵ</span> (to soften, melt): the heart losing its firmness. <span class='term'>Wĕšadday hĕḇahălānî</span>: 'the Almighty has shaken me' — <span class='term'>bāhal</span> (to terrify, agitate) in Piel: intense, repeated terrifying. The very God Job seeks is the one who dismantles his composure.</p>",
    "17": "<p><span class='term'>Kî lōʾ-niṣmattî mippĕnê-ḥōšeḵ</span>: 'Yet I am not silenced/cut off by the darkness' — <span class='term'>ṣāmat</span> (to cut off, destroy): Job refuses to be silenced by the surrounding darkness. The verse is difficult; the MKT renders it as Job's defiant persistence: despite everything, he does not stop. <span class='term'>Ûmippānay kissāh-ʾōpel</span>: 'deep darkness covers my face' — the conditions are as bad as possible, yet Job continues to speak and seek.</p>"
  },
  "24": {
    "1": "<p><span class='term'>Maddûaʿ miššadday lōʾ-niṣpĕnû ʿittîm</span>: 'Why does the Almighty not set appointed times?' — <span class='term'>ʿēt</span> (time, appointed moment): the theodicy question framed temporally. The God of history (who by definition controls <span class='term'>ʿittîm</span>) appears not to have scheduled judgment for visible wickedness. <span class='term'>Yōḏĕʿāyw lōʾ-ḥāzû yāmāyw</span>: 'those who know him cannot see his days of reckoning' — the hiddenness of divine judgment as the existential problem.</p>",
    "2": "<p><span class='term'>Gĕbûlôt yassîgû</span>: 'They move boundary stones' — <span class='term'>gĕḇûl</span> (boundary, territorial marker): the stones that demarcated tribal allotments. Moving them is the paradigmatic covenant violation (Deut 19:14; 27:17): it dissolves the land-distribution that expressed covenant justice. <span class='term'>ʿēḏer gāzĕlû wayirʿû</span>: 'they steal flocks and pasture them' — from <span class='term'>gāzal</span> (to seize by force): organized agricultural theft.</p>",
    "3": "<p><span class='term'>Ḥămôr yĕtōmîm yinḥāgû</span>: 'They drive away the orphan's donkey' — the orphan's donkey is his means of livelihood; taking it is destroying his subsistence. <span class='term'>Yāḥăbĕlû šôr ʾalmānāh</span>: 'they seize the widow's ox as collateral' — <span class='term'>ḥābal</span> (to take as pledge): the covenant-protection violation of ch22:6 now listed as systemic practice.</p>",
    "4": "<p><span class='term'>Yaṭṭû ʾeḇyônîm midderek</span>: 'They shove the needy off the road' — <span class='term'>ʾeḇyôn</span> (needy, poor): the standard covenant-protection category. <span class='term'>ʿAniyyê-ʾāreṣ nistarrû yaḥad</span>: 'the poor of the land go into hiding together' — the victims' response to the predatory society. Job is cataloguing the injustice that the friends say God always punishes immediately.</p>",
    "5": "<p><span class='term'>Hēn pĕrāʾîm bammiḏbār</span>: 'Like wild donkeys in the desert' — <span class='term'>pereʾ</span> (wild donkey): the animal of the wilderness, untamed and desperately foraging. The poor are reduced to animal-level survival. <span class='term'>Yāṣĕʾû pāʿălām lĕšaḥēr ṭāreP</span>: 'they go out to work, seeking food' — the predator-prey language applied to the economic system.</p>",
    "6": "<p><span class='term'>Baśśāḏeh bĕlîlô yiqṣōrû</span>: 'They harvest crops from fields that are not theirs' — the gleaning-rights of the poor violated by the powerful who harvest first. <span class='term'>Kerem rāšāʿ yĕlaqqēšû</span>: 'they glean in the wicked man's vineyard' — <span class='term'>lāqaš</span> (to gather late harvest): the destitute survive only by gleaning in fields controlled by those who oppress them.</p>",
    "7": "<p><span class='term'>ʿĀrôm yālînû mibbelî lĕḇûš</span>: 'They spend the night naked, without garment' — the nakedness violation is both literal and covenantal: the law specifically protects the garment-collateral of the poor (Exod 22:26-27; Deut 24:12-13). <span class='term'>Ûʾên kĕsût bassimrāh</span>: 'no covering against the cold' — <span class='term'>qōr</span> (cold): exposed in winter weather.</p>",
    "8": "<p><span class='term'>Mizzereṃ hārîm yirṭābû</span>: 'They are soaked by the mountain rains' — the weather-exposure of the homeless poor. <span class='term'>Ûmibbelî māḥaseh ḥibbĕqû-ṣûr</span>: 'they press against the rock for lack of shelter' — <span class='term'>māḥaseh</span> (shelter, refuge): the standard term for divine protection (Ps 46:2; 61:4) denied them by human wickedness.</p>",
    "9": "<p><span class='term'>Yigrĕzû miššaḏ yātôm</span>: 'They snatch the infant from its mother's breast' — the ultimate violation: tearing nursing infants from their mothers, presumably for debt-slavery. <span class='term'>Wĕʿal-ʿānî yaḥbōlû</span>: 'they take collateral from the destitute' — the systematic <span class='term'>ḥābal</span>-extraction targeting the most vulnerable.</p>",
    "10": "<p><span class='term'>ʿĂrôm hālĕkû bĕlî lĕḇûš</span>: 'They go about without clothing' — the workers who produce the harvest cannot afford to clothe themselves from its proceeds. <span class='term'>Wĕrāʿēb nāśĕʾû ʿāmîr</span>: 'starving, they carry the harvest sheaves' — the bitter irony: those who produce food go hungry.</p>",
    "11": "<p><span class='term'>Bên-šûrōtām yaṣhîrû</span>: 'They press olives among the terrace walls' — the agricultural labor vocabulary. <span class='term'>Yĕqāḇîm dārĕkû wayyiṣmāʾû</span>: 'they tread the winepresses, yet go thirsty' — the vintage-labor paradox: processing wine for others while thirsting themselves.</p>",
    "12": "<p><span class='term'>Mēʿîr mĕtîm yinʾāqû</span>: 'From the city the dying groan' — <span class='term'>nāʾaq</span> (to groan in death-agony): the pre-mortem cry. <span class='term'>Wĕnepeš ḥălālîm tĕšawwēaʿ</span>: 'the mortally wounded cry out' — <span class='term'>šāwaʿ</span> (to cry for help): the urgent distress call. <span class='term'>Wĕʾĕlôah lōʾ-yāśîm tiplāh</span>: 'yet God lays no charge of wrongdoing' — the theodicy punch: God sees, yet issues no indictment. This is Job's unresolved problem throughout the chapter.</p>",
    "13": "<p><span class='term'>Hēmmāh hāyû bĕmōrĕḏê-ʾôr</span>: 'These are among those who rebel against the light' — <span class='term'>mārad</span> (to rebel): the rebellion-vocabulary of covenant violation applied to those who love darkness (cf. John 3:19-20). <span class='term'>Lōʾ yāḏĕʾû dĕrākāyw wĕlōʾ yāšăḇû</span>: 'they do not know its ways and will not walk its paths' — <span class='term'>yāḏaʿ</span> as covenantal knowledge refused.</p>",
    "14": "<p><span class='term'>Lāʾôr yāqûm haṣṣôrēaḥ</span>: 'The murderer rises before dawn' — using the dark for cover, the criminal inverts the natural order: active when others sleep, hiding when others work. <span class='term'>Ballaylāh yihyeh kagannāb</span>: 'in the night he becomes the thief' — the convergence of murder and theft as darkness-crimes.</p>",
    "15": "<p><span class='term'>Wĕʿên nōpep yāšîm sēter pānāyw</span>: 'No one will spot me; he disguises his face' — the adulterer's calculation of privacy. <span class='term'>Šemar nešep ʿên tĕšûrēnî</span>: 'watches for the twilight' — <span class='term'>nešep</span> (twilight, dusk): the ambiguous light that enables concealment.</p>",
    "16": "<p><span class='term'>Baḥōšeḵ yaḥtĕrû ḇāttîm</span>: 'In the darkness they break through walls' — <span class='term'>ḥātar</span> (to dig through, break in): the thief's technique (cf. Matt 24:43). <span class='term'>Yômām ḥittĕmû lāmô</span>: 'by day they stay shut away' — their lives inverted: hidden by day, active by night.</p>",
    "17": "<p><span class='term'>Kî yaḥdāw bōqer lāhem ṣalmāwet</span>: 'The shadow of death is their morning' — the criminals' temporal experience inverted: morning (when others wake to life) is their deep darkness. <span class='term'>Yakkîr ballĕhôt ṣalmāwet</span>: 'they are familiar with the horrors of death's darkness' — they are habituated to what others flee from.</p>",
    "18": "<p><span class='term'>Qal-hûʾ ʿal-pĕnê-mayim</span>: 'He skims the surface of water like foam' — the transience of the wicked. <span class='term'>Tĕqullal ḥelqātô bāʾāreṣ</span>: 'his portion in the land is under a curse' — <span class='term'>qālal</span> (to be cursed/treated lightly): the curse that will ultimately overtake the wicked. <span class='term'>Lōʾ-yipen derek kĕrāmîm</span>: 'he does not turn toward vineyards' — perhaps prosperity escapes him.</p>",
    "19": "<p><span class='term'>Ṣiyāh wĕḥum yiśgĕlû mê-šeleg</span>: 'drought and heat evaporate the snow-waters' — the comparison: just as the desert heat absorbs snow-melt instantly and completely, <span class='term'>Šĕʾôl ḥāṭĕʾû</span>: 'Sheol takes those who have sinned' — the same inevitable, total absorption. The movement from life to death is as natural and irresistible as evaporation.</p>",
    "20": "<p><span class='term'>Yiškĕḥēhû reḥem</span>: 'The womb that bore him forgets him' — the ultimate erasure: the mother who bore him forgets him. <span class='term'>Rimmāh timetqā-lô</span>: 'the worm devours him eagerly' — <span class='term'>rimmāh</span> (worm, maggot): the post-mortem destruction. <span class='term'>Lōʾ-yizzāḵēr ʿôḏ</span>: 'he is no longer remembered' — the double erasure: forgotten by the living, consumed by worms.</p>",
    "21": "<p><span class='term'>Yirʿeh ʿăqārāh lōʾ-tēlēḏ</span>: 'He preys on the childless woman who cannot conceive' — targeting those without social protection or descendants to advocate for them. <span class='term'>Wĕʾalmānāh lōʾ-yēṭîb</span>: 'he shows no kindness to the widow' — the widow and barren woman: the most socially vulnerable, without male protectors.</p>",
    "22": "<p><span class='term'>Weyimsōḵ ʾabbîrîm bĕḵōḥô</span>: 'By his power he brings even the strong man down' — the tyrant who topples even those with resources. <span class='term'>Yāqûm wĕlōʾ-yaʾămîn bĕḥayyāyw</span>: 'he rises up, and no one's life is secure' — a difficult verse, possibly describing the tyrant's insecurity rather than his power.</p>",
    "23": "<p><span class='term'>Yittĕn-lô lābeṭaḥ wĕyiššāʿēn</span>: 'God allows him to rest in security' — the theological crux: divine provision of security to the wicked. <span class='term'>Wĕʿênāyw ʿal-darkêhem</span>: 'yet God's eyes are on their every path' — the tension: security granted while divine surveillance continues. Job observes the complexity of divine providential action without forcing it into simple categories.</p>",
    "24": "<p><span class='term'>Rāmû mĕʿaṭ wĕʾênennû</span>: 'They are lifted up for a moment and then they are gone' — the temporary exaltation of the wicked, followed by sudden removal. <span class='term'>Kĕrōʾš šibbōlet yimmālû</span>: 'they sink down like the top of a grain-stalk' — the grain-stalk bends and is cut: the image of swift, total harvesting.</p>",
    "25": "<p><span class='term'>Wĕʾim-lōʾ ʾēpôh mî yaḵzîḇēnî</span>: 'And if this is not true, who will prove me wrong?' — Job's challenge to the friends: his observation of the world's moral complexity cannot be refuted. <span class='term'>Wĕyāśēm lĕ-ʾepes millātî</span>: 'who will show that my words are worthless?' — <span class='term'>ʾepes</span> (nothingness): Job's confidence that his account of reality is true.</p>"
  },
  "25": {
    "1": "<p>Bildad's third speech is the shortest in the cycle (6 verses), suggesting the friends are running out of arguments.</p>",
    "2": "<p><span class='term'>Mišrāh wĕpāḥaḏ ʿimmô</span>: 'Dominion and dread belong to him' — <span class='term'>mišrāh</span> (dominion, government): the governing authority of God. <span class='term'>Paḥaḏ</span> (terror, dread) as the accompanying attribute. <span class='term'>ʿōśeh šālôm bimrômāyw</span>: 'he makes peace in his high places' — the divine peacemaking in the heavenly council, which Bildad invokes as contrast to Job's turbulence.</p>",
    "3": "<p><span class='term'>Hiš ḵĕsāpāyw yimmāneh</span>: 'Can his armies be numbered?' — <span class='term'>gĕdûḏ</span> (troop, army): the heavenly host. The unanswerable rhetorical question establishes divine immensity. <span class='term'>ʿal-mî lōʾ-yāqûm ʾôrô</span>: 'upon whom does his light not rise?' — universal divine illumination: no one and nowhere outside divine light.</p>",
    "4": "<p><span class='term'>Ûmah-yiṣdaq ʾĕnôš ʾim-ʾēl</span>: 'How can any mortal be declared righteous before God?' — <span class='term'>ṣāḏaq</span> (to be righteous, be declared righteous, be in the right) used legally: the formal verdict of acquittal. This is the question of 9:2 raised again by Bildad. <span class='term'>Yĕlûd ʾiššāh</span> (born of woman): the same creatureliness-phrase as 15:14 — birth conditions moral limitation.</p>",
    "5": "<p><span class='term'>Hēn ʿad-yārēaḥ wĕlōʾ yaʾăhîl</span>: 'Even the moon gives no real light before him' — <span class='term'>ʾāhal</span> (to shine brightly): the moon's light is dim before divine glory. <span class='term'>Kôḵāḇîm lōʾ-zakkû bĕʿênāyw</span>: 'the very stars are not pure in his sight' — <span class='term'>zāḵaḵ</span> (to be pure, clear): celestial impurity before divine holiness. The scale of the comparison makes human righteousness seem impossible.</p>",
    "6": "<p><span class='term'>ʾAp kî-ʾĕnôš rimmāh</span>: 'How much less a mortal, who is a maggot' — <span class='term'>rimmāh</span> (worm, maggot): the decomposition-creature. <span class='term'>Ûḇen-ʾāḏām tôlēʿāh</span>: 'and a human being, who is a worm' — <span class='term'>tôlēʿāh</span> (worm, crimson-worm): the same word used in Ps 22:7 ('I am a worm and not a man') — the creature beneath notice. Bildad intends to silence Job with creaturely insignificance; Ps 22 and the incarnation reveal that this is exactly the condition God enters in Christ.</p>"
  },
  "26": {
    "1": "<p>Job's tenth speech opens with devastating sarcasm, meeting Bildad's crushing speech with ironic counter-praise.</p>",
    "2": "<p><span class='term'>Eziartāh lĕlōʾ-kōaḥ</span>: 'What help you have given to the powerless!' — the sarcasm is biting: <span class='term'>ʿāzar</span> (to help) turned mock-praise. <span class='term'>Hôšaʿtā zerôaʿ lōʾ-ʿōz</span>: 'what strength you have brought to the feeble arm!' — Bildad has done absolutely nothing for Job. The speech that claims to describe God's might has brought no practical help to the suffering man before him.</p>",
    "3": "<p><span class='term'>Mah-yāʿaṣtā lĕlōʾ ḥāḵmāh</span>: 'What counsel you have given to one with no wisdom!' — the irony continues: <span class='term'>yāʿaṣ</span> (to advise, counsel) applied to Bildad's useless speech. <span class='term'>Wĕtûšiyāh lārōḇ hôḏaʿtā</span>: 'how abundantly you have offered sound understanding!' — <span class='term'>tûšiyāh</span> (sound wisdom, practical effectiveness): the rarest, most prized wisdom term used in mock-praise.</p>",
    "4": "<p><span class='term'>ʾet-mî higgadtā millîm</span>: 'Who are you addressing with these words?' — the challenge to Bildad's intended audience. <span class='term'>Ûmî-nĕšāmāh yāṣĕʾāh mimmekā</span>: 'whose spirit spoke through you?' — <span class='term'>nĕšāmāh</span> (breath, spirit): Bildad claimed divine inspiration (cf. 32:8); Job challenges the source.</p>",
    "5": "<p><span class='term'>Hārĕpāʾîm yĕḥôlālû mittaḥat mayim</span>: 'The shades of the dead tremble under the waters' — <span class='term'>rĕpāʾîm</span> (the Rephaim/shades): the dead in Sheol (cf. Isa 14:9; Prov 2:18). The trembling of the underworld dead before God establishes that divine authority penetrates even the cosmic underworld. <span class='term'>Wĕšōkĕnêhem</span> (and those who dwell beneath them): the layered depths of the cosmological underworld.</p>",
    "6": "<p><span class='term'>ʿĀrôm šeʾôl negdô</span>: 'Sheol is naked/exposed before him' — <span class='term'>ʿārôm</span> (naked, exposed): nothing in Sheol is hidden from God. <span class='term'>ʾAḇaddôn ʾên kĕsûth</span>: 'Abaddon has no covering' — <span class='term'>ʾaḇaddôn</span> (Abaddon, destruction — the place of final destruction, cf. Rev 9:11): no concealment possible in the deepest pit. Both Sheol and Abaddon appear together as the twin death-realms (cf. Prov 15:11).</p>",
    "7": "<p><span class='term'>Nōṭeh ṣāpôn ʿal-tōhû</span>: 'He stretches out the north over the void' — <span class='term'>tōhû</span> (formlessness, void): the same word as Gen 1:2 (<span class='term'>tōhû wābōhû</span>). Job uses the creation-vocabulary to describe the divine cosmological act. <span class='term'>Tōleh ʾereṣ ʿal-bĕlî māh</span>: 'he hangs the earth on nothing' — the remarkable cosmological statement that the earth is suspended on nothing (<span class='term'>bĕlî māh</span>): no visible support. The OT's most explicit statement of the earth's suspension in space.</p>",
    "8": "<p><span class='term'>ṣōrer mayim beʿābāyw</span>: 'He wraps the waters in his thick clouds' — the cloud-water storage system of the hydrological cycle. <span class='term'>Wĕlōʾ-nibqaʿ ʿānān taḥtām</span>: 'the cloud holds without bursting' — the marvel that clouds hold their water: an implicit acknowledgment of the divine engineering of weather.</p>",
    "9": "<p><span class='term'>Mĕʾaḥēz pĕnê-kissēʾ</span>: 'He screens the face of his throne' — <span class='term'>kissēʾ</span> (throne): the divine royal seat. The cloud-screen conceals the divine throne (cf. the Sinai cloud, Exod 24:16). <span class='term'>Piśtēhû ʿālāyw ʿănānô</span>: 'he spreads his cloud over it' — the veil of divine transcendence around the throne.</p>",
    "10": "<p><span class='term'>Ḥôg ḥāḡag ʿal-pĕnê-mayim</span>: 'He has drawn a circle on the face of the waters' — <span class='term'>ḥûg</span> (circle, vault): the horizon-circle marking the boundary between waters (cf. Prov 8:27; Isa 40:22). <span class='term'>ʿad-taktît ʾôr ʿim-ḥōšeḵ</span>: 'the boundary between light and dark' — the creation-separation of Gen 1 expressed as a drawn circle.</p>",
    "11": "<p><span class='term'>ʿAmmûḏê šāmayim yĕrōpĕpû</span>: 'The pillars of heaven tremble' — the cosmological pillars supporting the sky vault. <span class='term'>Wĕyitmahhû miggĕʿārātô</span>: 'they are stunned at his rebuke' — <span class='term'>gĕʿārāh</span> (rebuke, thunderous command): God's authoritative speech that shakes cosmic architecture. The same term used for the divine rebuke of chaos-waters (Ps 104:7; Isa 50:2).</p>",
    "12": "<p><span class='term'>Bĕkōḥô rāgaʿ hayyām</span>: 'By his power he calmed the sea' — <span class='term'>rāgaʿ</span> (to stir up or calm — the term is ambiguous; both meanings appear in the OT). <span class='term'>ûḇiṯḇûnātô māḥaṣ Rāhaḇ</span>: 'by his understanding he crushed Rahab' — <span class='term'>Rāhaḇ</span>: the sea-dragon/chaos monster (cf. Ps 89:10; Isa 51:9), the mythological figure for the primordial waters of chaos. God's creation is the defeat of chaos.</p>",
    "13": "<p><span class='term'>Rûḥô šāmayim šiprāh</span>: 'His Spirit made the heavens beautiful' — <span class='term'>šāprāh</span> (to be beautiful, clear): the Spirit's aesthetic dimension of creation. <span class='term'>Ḥōlĕlāh yāḏô nāḥāš bārîaḥ</span>: 'his hand transfixed the twisting serpent' — <span class='term'>nāḥāš bārîaḥ</span> (the twisting/fleeing serpent): the Leviathan/sea-serpent figure (cf. Isa 27:1; Rev 12:9). Creation as divine defeat of chaos-serpent.</p>",
    "14": "<p><span class='term'>Hēn-ʾēlleh qĕṣôt dĕrākāyw</span>: 'These things are but the edges of his ways' — <span class='term'>qāṣeh</span> (edge, extremity): what Job has described — cosmic creation, defeat of chaos, pillars of heaven — are merely the outermost fringes of divine activity. <span class='term'>Wĕremes dābār nišmaʿ-bô</span>: 'how faint a whisper we catch of him' — <span class='term'>remes</span> (a whisper, a murmur): the great theophanic acts are a barely audible whisper of the divine fullness. <span class='term'>Rāʿam gĕḇûrātô mî yiṯbônān</span>: 'the thunder of his power — who can understand?' — the doxological close. Job ends his survey of God's cosmic power with epistemological humility, not despair.</p>"
  }
}

def main():
    c = load_comm('mkt-original', 'job')
    merge_comm(c, JOB)
    save_comm('mkt-original', 'job', c)
    total = sum(len(v) for v in JOB.values())
    print(f'job mkt-original: wrote {total} verses across ch 22-26')

if __name__ == '__main__':
    main()
