"""
mkt-original Layer — Exodus chapters 13–15
Run: python3 scripts/zc-original-exodus-13-15-fill.py

Key philological decisions:
- Ch 13: bechor/petter rechem (firstborn/opener of womb); zachor as covenant memory verb;
  tefillin precursor language (ot/totafot); chamushim (armed/by fives — debated);
  Yam Suph = Sea of Reeds (suph = papyrus, not "Red"); ammud anan/esh (pillar of cloud/fire).
- Ch 14: chazaq/kahsah/kaved (hardening verbs — all from heaviness/strength roots);
  yabbashah (dry ground, Gen 1:9 creation echo); na'ar (shake out — divine weapon verb);
  yad gedolah (great hand) + aman (to believe — root of amen) as Exodus-faith climax.
- Ch 15: az yashir (retrospective poetic formula); Yah (first occurrence, short YHWH);
  mi-kamokha (incomparability formula — root of name Micah); ga'al (kinsman-redeemer
  again); etz (tree/wood at Marah — bitter→sweet; typological richness); YHWH-Rophe
  (healer compound name, first occurrence).
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

EXODUS_ORIGINAL = {
  "13": {
    "1": "<p><b>YHWH spoke to Moses, saying:</b> The standard prophetic address formula (waydabber YHWH el-Moshe le'mor) frames what follows not as legislation improvised after the event but as the divine interpretation of the Exodus itself. The consecration command is the theological corollary to the tenth plague.</p>",
    "2": "<p><b>Consecrate to me (qadeshu-li) every firstborn (kol-bechor):</b> Qadash (to set apart as holy) is the priestly consecration verb; bechor derives from bakar (to be first, to bear firstfruit). <b>Petter rechem</b> (opener of the womb) — from pathar (to open/burst through) — specifies the firstborn as the one who ruptures the birth canal, the biological and legal first of the line. Both human and animal firstborn are addressed; the command grounds the Passover logic: Israel's firstborn were spared because a substitute died in their place.</p>",
    "3": "<p><b>Remember this day (zachor et-hayom hazeh):</b> Zachor is the covenant-memory verb, used in Deuteronomy for sabbath (5:15), for the Exodus itself (16:3), and for the Amalekite attack (25:17). It means more than intellectual recall — it means to make present and act on. <b>House of slaves (beit avadim):</b> Egypt is defined not by geography but by its social structure; Israel is defined as the people freed from it.</p>",
    "4": "<p><b>Month of Abib (chodesh ha-aviv):</b> Aviv = green/tender ears of grain (barley ripening); the month is named from agricultural phenology, not a number or a god. Later calendar reform (Babylonian influence) replaced aviv with Nisan, but Deuteronomy still uses aviv (16:1). The spring month marks both the agricultural new year and the redemptive new beginning.</p>",
    "5": "<p><b>When YHWH brings you (ki yeviacha):</b> The causal-temporal ki + Hiphil imperfect of bo' anticipates the land-gift as already settled. <b>Flowing with milk and honey (zavet chalav u'devash):</b> The stock formula (appears ~20 times in the Pentateuch) describes agricultural abundance — chalav (milk from flocks) and devash (honey from date palms or wild bees). The five nations named are the standard catalog of Canaan's pre-Israelite inhabitants.</p>",
    "6": "<p><b>Seven days you shall eat matzot (unleavened bread):</b> Seven is the week of completeness; the festival (chag) on the seventh day is a mirror of the Sabbath structure embedded in Passover observance. The temporal overlap of the week-festival and the annual commemoration links personal discipline (no leaven in the house) to communal celebration.</p>",
    "7": "<p><b>No leaven shall be seen with you (lo-yera'eh lecha chametz):</b> The Niphal of ra'ah (to be seen) used as passive; chametz = leavened dough; se'or = sourdough starter or leaven. The prohibition covers not just eating but possession throughout all your territory (kol-gevulecha). Paul's midrash on this text (1 Cor 5:7-8) treats leaven as a metaphor for corruption spreading through a community.</p>",
    "8": "<p><b>You shall tell your son (v'higadeta l'vincha):</b> The Hiphil of nagad (to declare/tell) is the catechetical verb for Passover explanation. B'avur zeh (because of this, on account of this) — the demonstrative this points to the physical matzot and bitter herbs currently before the narrator; memory is made tangible through objects. The Passover Haggadah (from this same root nagad) derives its name from this verse.</p>",
    "9": "<p><b>Sign (l'ot) on your hand... memorial (l'zikaron) between your eyes:</b> Ot = sign (same term as circumcision in Gen 17:11, rainbow in Gen 9:12-13) — a physical marker of covenant status. Zikaron = memorial/reminder from zakar (the memory verb of v.3). The parallel is later literalized as tefillin (Deut 6:8 uses totafot): leather boxes with Torah portions worn on arm and forehead. <b>Torah of YHWH in your mouth:</b> The sign-on-body motif points to the ultimate goal — scripture internalized as speech.</p>",
    "10": "<p><b>Statute (chuqqah) at its appointed time (moed):</b> Chuqqah = binding ordinance from chaqaq (to engrave/inscribe); it conveys permanence — the law engraved, not merely spoken. Moed = appointed time/meeting, the same root as ohel moed (tent of meeting); both the tabernacle entrance and the annual feasts are moadim — times of divine-human rendezvous.</p>",
    "11": "<p><b>When YHWH brings you to the land of the Canaanite:</b> The promise-fulfillment frame (ki + Hiphil imperfect of bo') recurs from v.5, creating a sandwich structure around the Passover regulations. The firstborn law (vv.11-16) extends the Passover redemption logic into the future life of the nation in the land.</p>",
    "12": "<p><b>You shall cause to pass over (ha'avarta) to YHWH all that opens the womb:</b> The Hiphil of avar (to cross/pass over) uses the Passover verb — peh samech chaf — the same root as Pesach; the firstborn are 'passed over' to YHWH just as death 'passed over' Israel's houses. Every firstborn male (zachar) of your cattle belongs to YHWH (laYHWH).</p>",
    "13": "<p><b>Firstborn donkey (petter chamor) redeemed (tifdeh) with a lamb (seh):</b> The donkey (chamor) is the paradigm unclean animal — it cannot be sacrificed on the altar, so it must either be redeemed by substitution (padah = ransom by exchange) or have its neck broken (va'arafto — from oref, the nape of the neck). The lamb stands in for the donkey; the substitution logic is explicit. <b>Padah</b> (to redeem by payment/substitution) is distinct from ga'al (to redeem as kinsman); both appear in the Exodus redemption vocabulary. Every firstborn son also requires redemption — human sons and unclean animals share the same status before YHWH: too precious/dangerous to be unredeemed.</p>",
    "14": "<p><b>When your son asks in time to come (machar):</b> Machar = tomorrow/future; the catechetical question-and-answer sequence (asked also in Exod 12:26; Deut 6:20; Josh 4:6) structures Passover transmission across generations. <b>By strength of hand (bechozek yad) YHWH brought us out:</b> The yad (hand) is the primary Exodus metaphor — the outstretched arm, the strong hand. The summary formula 'hand + Egypt + slaves' condenses the whole narrative into a sentence for children.</p>",
    "15": "<p><b>Pharaoh hardened himself (hikshaih):</b> Here the root is qashah (to be hard/difficult), distinct from chazaq (strengthen) and kaved (be heavy) used elsewhere. The three hardening roots together form a theological composite: the heart can be made stubborn (qashah), strengthened in its resolve (chazaq), or weighted down in dullness (kaved). Pharaoh's hardening is both self-induced and divinely confirmed. <b>YHWH killed all the firstborns:</b> The theological consequence: because Pharaoh's firstborn died, Israel's firstborn must be consecrated — the covenant reciprocity of the tenth plague.</p>",
    "16": "<p><b>Totafot (frontlets) between your eyes:</b> Totafot is a hapax legomenon in the Pentateuch (also Deut 6:8, 11:18); the etymology is uncertain — possibly Akkadian tutuptu (band), possibly a foreign loanword. The rabbis identified these as the phylacteries (tefillin), small leather boxes containing Torah portions, bound to the arm and forehead during morning prayer. Whether the original command was meant literally or metaphorically is debated; the practice is ancient and attested in Second Temple Judaism.</p>",
    "17": "<p><b>God did not lead them by way of the land of the Philistines (derekh eretz-Pelishtim):</b> The Philistines (Pelishtim) occupied the coastal plain (the Via Maris); archaeologically attested Egyptian military fortifications lined this route. <b>Pen yinnachem (lest they regret/change their minds):</b> Nacham = to be comforted/consoled, but also to change one's mind or regret — the divine rationale for the longer wilderness route reveals pastoral psychology: YHWH reads the people's fragility and accommodates it.</p>",
    "18": "<p><b>Yam Suph (Sea of Reeds):</b> Suph = papyrus reeds/rushes (cf. 2:3 — the basket among the suph); the Greek translation 'Red Sea' (Erythra Thalassa) is a geographical overlay from later Hellenistic usage that identified the body of water with the Gulf of Suez. The Hebrew name points to a marshy reed-sea environment. <b>Chamushim (armed/by fives?):</b> The word appears twice in the OT (here and Josh 1:14); the root is debated — possibly chamesh (five, in military formation?) or chamush (loins/equipped). The LXX reads 'in the fifth generation' (fifth generation after the patriarchs?); most translations opt for 'armed for battle.'</p>",
    "19": "<p><b>Moses took the bones of Joseph (atzamot Yosef):</b> Joseph had sworn Israel under oath (shevet hishbia = made them swear a solemn oath, Gen 50:25) to carry his bones out of Egypt. Atzamot = bones — the embodied continuity of the patriarchal promise; the living carry the dead through the wilderness into the land. The bones of Joseph, the greatest of Jacob's sons, travel with the redeemed nation as a sign that the covenant spans generations and crosses death.</p>",
    "20": "<p><b>Succoth... Etham:</b> Succoth (Sukkot = booths/shelters) is probably Tell el-Maskhuta in the eastern Delta; Etham is at the edge of the wilderness (qetze hamidbar = end/border of the wilderness). The itinerary moves from Egyptian territory toward the desert frontier.</p>",
    "21": "<p><b>Pillar of cloud (ammud anan) by day... pillar of fire (ammud esh) by night:</b> Ammud = column/pillar; anan = cloud; esh = fire. The double form — cloud (concealment + shelter from desert heat) and fire (warmth + light in darkness) — manifests both the hiddenness and accessibility of the divine presence. <b>Lanchootam (to lead them on the way):</b> Hiphil infinitive of nachah (to guide/lead) — the same verb for the divine leading in Ps 23:3 (yancheini b'ma'aglei tzedeq) and Isa 40:11. YHWH is Israel's shepherd-guide.</p>",
    "22": "<p><b>He did not remove (lo-yamish) the pillar:</b> Yamish = Hiphil of mush (to remove/withdraw from a place); the negative verb emphasizes the constancy of the divine presence — day and night (yomam v'lailah) without interruption. The pillar is not intermittent but permanent throughout the wilderness journey, a sustained Shekinah-presence before the tabernacle formalizes the arrangement.</p>"
  },
  "14": {
    "1": "<p><b>YHWH spoke to Moses, saying:</b> The divine instruction frames the crossing not as an emergency improvisation but as a planned trap — YHWH directs the movement of Israel specifically to lure Pharaoh.</p>",
    "2": "<p><b>Pi-hahiroth... between Migdol and the sea... opposite Baal Tzephon:</b> Baal Tzephon = Baal of the North; a Canaanite deity whose shrine stood on the coast. The place names are Egyptian/Semitic hybrid; the exact locations are debated. Strategically, the geography creates a cul-de-sac: the sea ahead, mountains on one side, Egyptian territory behind — the perfect setting for the trap.</p>",
    "3": "<p><b>Pharaoh will say... they are wandering in confusion (nevukhim) in the land:</b> Navakh = to be confused/perplexed; the wilderness has closed in on them (sagar aleihem hamidbar). God deliberately creates a military situation that reads as Israelite incompetence, drawing Pharaoh's overconfidence. The hardening of Pharaoh's heart is accomplished not only internally but by managing circumstances.</p>",
    "4": "<p><b>I will harden (achazzeq) Pharaoh's heart:</b> Piel of chazaq (to make strong/hard); distinct from the earlier Qal forms where Pharaoh's own heart hardened. The divine initiative now takes over what Pharaoh had been doing to himself. <b>I will get glory (e'kkaved) over Pharaoh:</b> Niphal of kavad (to be honored/heavy); kavod (glory) derives from this same root meaning heaviness — what is weighty is glorious. The irony: Pharaoh's 'hardness' (chazaq) and YHWH's glory (kavod) operate from opposing directions; Egypt's heaviness becomes YHWH's glory.</p>",
    "5": "<p><b>The heart of Pharaoh and his servants was turned (nehehpak):</b> Niphal of haphak (to overturn/reverse) — the same root as Sodom's overthrow (Gen 19:25) and the turning of the plague-blood (Exod 7:17). <b>What have we done that we let Israel go from our service (me'avdenu)?</b> Avad = to serve/work; avadim = servants/slaves; avodah = service/labor/worship. The question reveals that Egypt defined itself by Israel's service — the identity of the empire rested on the enslavement of God's son.</p>",
    "6": "<p><b>He made ready his chariot (wayyesor markavto):</b> Asar = to harness/bind; markavah = chariot (from rakav, to ride); the six hundred chosen chariots (shesh-me'ot rekev bachar) — bachar = chosen/elite — represent Pharaoh's rapid-reaction force, his finest military asset.</p>",
    "7": "<p><b>Six hundred chosen chariots and all the chariots of Egypt:</b> The number six hundred echoes the six hundred thousand adult males of Israel (12:37); the military equivalence frames the confrontation as a cosmic imbalance — all of Egypt's chariots against YHWH's unarmed escaping slaves.</p>",
    "8": "<p><b>YHWH hardened (vay'chazeq) the heart of Pharaoh:</b> The divine hardening is now active and explicit; the phrase b'yad ramah (with a high/lifted hand) describes Israel's exit — ramah = to be high/exalted, the same root as the coming victory song's ga'oh ga'ah (he has triumphed gloriously). Israel marches openly, defiantly, under divine protection.</p>",
    "9": "<p><b>The Egyptians pursued (vayirdefu) them:</b> Radaf = to pursue/persecute (the verb of the Psalms' enemies and of Pharaoh's army here and in v.23); <b>horses (susim), chariots (rekev), horsemen (parashim), and army (cheil):</b> the full military vocabulary catalogs the force bearing down on Israel encamped at the sea.</p>",
    "10": "<p><b>The people were very afraid (yire'u me'od) and cried out (yitz'aku) to YHWH:</b> Yara = to fear/be in awe; za'aq = to cry out for help (the same verb as Israel's cry in 2:23 that moved YHWH to act — the cry of the oppressed). The wilderness complaint-cycle begins its first iteration here: fear → cry → complaint → Moses's reassurance → divine action.</p>",
    "11": "<p><b>Were there no graves in Egypt (ha'mibeli ein q'varim b'mitzrayim)?</b> The bitter irony: Egypt is the world's greatest civilization of the dead — its landscape is dominated by tombs and mortuary monuments. The complaint turns Egypt's obsession with death against the exodus. <b>You have brought us out (hotzetanu)</b> — Hiphil of yatza (to bring out); the very verb of the Exodus creed becomes their accusation.</p>",
    "12": "<p><b>Is not this what we said to you in Egypt: 'Leave us alone (chadal mimenu) that we may serve (va'na'avod) the Egyptians'?</b> Chadal = to cease/leave off/desist. The preference for Egyptian slavery over wilderness freedom is the recurring spiritual failure of the Exodus generation. Better to be well-fed slaves than hungry freedmen — the logic that Jesus addresses in John 8:33-36.</p>",
    "13": "<p><b>Do not fear (al-tira'u), stand firm (hitzyabu):</b> Hithpael of yatzav (to station oneself, take a stand); the reflexive form emphasizes deliberate action — don't just stop shaking, plant yourself. <b>See the salvation (yeshuah) of YHWH:</b> Yeshuah from yasha (to save/deliver) — the same root as Joshua and Jesus. Moses's command is to watch YHWH do the fighting; the salvation belongs to YHWH, not to military resistance. <b>You shall never see them again:</b> The double negative (lo tosifun lir'otam) is absolute — the enemy that pursues you will be annihilated, not merely repelled.</p>",
    "14": "<p><b>YHWH will fight (yilachem) for you, and you only need to be silent (tacharishun):</b> Lacham = to fight/do battle; charash = to be silent, still, to plow (the metaphor of a plowed field — quiet, open, ready to receive). This verse is the Exodus's greatest faith-statement: the battle posture called for is non-resistance. The same theology of divine warfare appears in 2 Chr 20:15-17 (Jehoshaphat) and Isa 30:15 ('in quietness and trust is your strength').</p>",
    "15": "<p><b>Why do you cry to me (mah titz'aq elai)?</b> YHWH's surprising rebuke of Moses's prayer; the time for prayer is past — the time for action has come. The intersection of human prayer and divine command: YHWH has already determined to act; Moses's role is to execute, not to petition. <b>Tell the people to go forward (yisa'u):</b> Qal imperfect of nasa (to set out/journey); the same verb used for the camp's movement throughout the wilderness itinerary.</p>",
    "16": "<p><b>Lift up your staff (harem et-matte'cha) and stretch out your hand over the sea:</b> The staff (mateh) has been the instrument of every plague sign; now it performs the ultimate sign. The gesture of outstretched hand (natah yad) over water is the signature action of Moses throughout chapters 7-14. The staff connects the Exodus miracles thematically — one instrument, many demonstrations.</p>",
    "17": "<p><b>I will harden (m'chazeq) the hearts of the Egyptians:</b> Piel participle — the continuous divine action maintains Pharaoh's pursuit into the trap. <b>And I will get glory (ve'ekkavedah) over Pharaoh and all his host:</b> The kavod/kavad theme reaches its climax — all the weight of the Egyptian military will become the glory of YHWH when the sea swallows it.</p>",
    "18": "<p><b>The Egyptians shall know (yede'u) that I am YHWH (ani YHWH):</b> The da'at-YHWH formula (to know YHWH experientially) is the purpose clause of the Exodus as a whole (3:19-20; 6:7; 7:5,17; 8:10; etc.). Egypt's knowledge is not salvific but judicial — they will know YHWH as the one who judges empire. <b>When I have gotten glory (behikaveddi) over Pharaoh:</b> The Niphal infinitive construct — when I am glorified, honored, made heavy with the weight of his destruction.</p>",
    "19": "<p><b>The angel of God (malach ha-Elohim) who was going before the host of Israel moved and went behind them:</b> The mal'ach ha-Elohim (angel/messenger of God, compare to mal'ach YHWH earlier) = the divine representative, perhaps identical to the pillar. The tactical shift from vanguard to rearguard is a military repositioning — the divine escort becomes the divine shield, covering the retreat. The same cloud that guides Israel becomes the darkness that blinds Egypt.</p>",
    "20": "<p><b>Darkness and cloud to one, light and fire to the other:</b> The same phenomenon serves opposite purposes — judgment and protection from the same divine presence. The pillar is not morally neutral; it discriminates according to the covenantal status of the parties. The wilderness darkness echoes the plague of darkness (10:21-23) where Egypt was in darkness while Israel had light.</p>",
    "21": "<p><b>A strong east wind (ruach qadim azzah) all night:</b> Ruach = wind/breath/spirit; qadim = east (the desert wind); azzah = strong. The wind is the instrument but YHWH is the agent — the text carefully distinguishes the natural means (wind) from the supernatural cause (YHWH drove the sea back). <b>Dry land (choravan):</b> From charev (dry/desolate); the sea floor becomes desert. The creation echo: in Gen 1:2 the ruach Elohim (Spirit/wind of God) moves over the waters before dry land (yabbashah) appears; here the ruach YHWH parts the waters and dry land appears again — Exodus as new creation.</p>",
    "22": "<p><b>Israel walked on dry ground (yabbashah) through the sea:</b> Yabbashah = dry land (Gen 1:9-10 — the term for dry land at creation). The creation-exodus typology is explicit: Israel passes through the parted waters to new life just as creation emerged when the waters were separated. <b>Waters being a wall (chomah) to their right and left:</b> Chomah = defensive city wall; the waters that threatened now protect, flanking Israel as a fortification.</p>",
    "23": "<p><b>The Egyptians pursued and went in after them into the midst of the sea:</b> The Egyptians enter the creation-space Israel has been given — they trespass into YHWH's protected zone. Their confidence (the hardened heart) drives them into the trap.</p>",
    "24": "<p><b>In the morning watch (b'ashmuret haboqer) YHWH looked down (vayashkef) through the pillar of fire and cloud:</b> Ashmuret = watch of the night; haboqer = morning (the period from roughly 2am to sunrise); shakaf = to look down from above. <b>He threw into panic (vayaham):</b> Hamam = to throw into confusion/panic (the same verb used for YHWH routing armies in Deut 7:23 and Josh 10:10); the divine gaze is itself a weapon.</p>",
    "25": "<p><b>He clogged/bound their chariot wheels (vayaser et-ofan markevotav):</b> Asar = to bind/remove; ofan = wheel; the precise mechanism (wheels coming off or sinking) is less important than the theological point: Egypt's greatest technological advantage — the chariot — is disabled by YHWH. <b>They drove heavily (bichvedut):</b> From kaved (heavy) — the root of kavod (glory); Pharaoh's heavy heart now makes his army drive heavily. The Egyptians recognize their situation: 'YHWH fights for them against Egypt' — the enemy confesses the theology of the Exodus.</p>",
    "26": "<p><b>Stretch out your hand over the sea, that the water may come back:</b> The gesture that parted the sea now reverses the division — Moses's hand mediates both the opening and the closing. The created order has been temporarily suspended; now it is restored, but not before its purpose is accomplished.</p>",
    "27": "<p><b>The sea returned (vayashov) to its normal flow when morning appeared:</b> Shuv = to return; the sea 'returns' as YHWH intended — the temporary suspension of natural order served its redemptive purpose. <b>YHWH shook out (vayena'er) the Egyptians into the sea:</b> Na'ar = to shake out (as one shakes a garment to empty it); the image is of YHWH as one who shakes the enemies of Israel out of existence the way dust is shaken from a cloak (cf. Job 38:13 — the earth shaken so the wicked are shaken out of it).</p>",
    "28": "<p><b>Not one of them remained (lo-nishar bahem ad-echad):</b> The total annihilation formula — every chariot, every horseman, every soldier of Pharaoh's elite force. The army that enslaved Israel for four hundred years is destroyed in a single night. The asymmetry between the means (an east wind, two outstretched hands) and the result (the total destruction of the Egyptian military) defines divine warfare.</p>",
    "29": "<p><b>The people of Israel walked on dry ground through the sea:</b> The repetition from v.22 forms a frame around the Egyptian destruction, emphasizing the contrast: the same waters that were walls of protection for Israel were walls of destruction for Egypt.</p>",
    "30": "<p><b>Thus YHWH saved (vayyosha') Israel that day:</b> The Hiphil of yasha — the salvation verb; yeshuah (salvation) in the abstract, yasha in the concrete act. <b>Israel saw the Egyptians dead on the seashore (al-sfat hayam):</b> The body count on the beach is the visible evidence of the invisible battle; seeing the dead is the first step toward the climactic faith-statement of v.31.</p>",
    "31": "<p><b>Israel saw the great power (yad gedolah — great hand) that YHWH used against Egypt:</b> The yad (hand) motif — the outstretched arm of YHWH — reaches its climax in this verse. <b>They feared YHWH (vayire'u et-YHWH) and believed (vaya'aminu) in YHWH and in his servant Moses:</b> The sequence — seeing → fearing → believing — is the Exodus paradigm for faith formation. Aman = to believe/trust, from the root meaning to be firm/reliable (the root of amen); faith is the response to evidence of YHWH's reliability. The Exodus functions as the founding demonstration of YHWH's trustworthiness, referenced throughout the Psalms and prophets as the ground of all future confidence.</p>"
  },
  "15": {
    "1": "<p><b>Then Moses and the people of Israel sang (az yashir Moshe):</b> Az = then (retrospective poetic formula; the perfect tense embedded in an imperfect form signals the performative, celebratory character of the ode; cf. Num 21:17, Josh 10:12). The Song of the Sea (Shirat HaYam) is among the oldest poetry in the Hebrew Bible, exhibiting archaic grammatical features. <b>For he has triumphed gloriously (ki ga'oh ga'ah):</b> The infinitive absolute + Qal perfect of ga'ah for intensification; ga'ah = to rise up, be exalted, triumph — the verb of majesty and pride used for divine victory. <b>The horse and his rider he has thrown into the sea (ramah):</b> Ramah = to throw/hurl; the conciseness of the image (horse + rider + sea) becomes the song's refrain.</p>",
    "2": "<p><b>YHWH is my strength and my song (ozi ve'zimrat Yah):</b> The first occurrence of <b>Yah</b> — the short form of YHWH — embedded in Hebrew poetry here and in Ps 118:14 (cited in Isa 12:2). Oz = strength/might; zimrat = song/praise, from zamar (to sing/make music). The phrase is not 'he is my strength and I sing about him' but 'he is my strength and my song' — his power is itself what I sing. <b>He has become my salvation (vayyehi-li lishuah):</b> Yeshuah — the noun that names Joshua and Jesus. <b>This is my God (zeh Eli):</b> The demonstrative force of zeh — not an abstract theological proposition but a finger pointed at the one who just split the sea and drowned the army.</p>",
    "3": "<p><b>YHWH is a man of war (ish milchamah):</b> The divine warrior title is explicit and unapologetic; milchamah = war/battle (from lacham = to fight). This is the only place in Scripture where YHWH is directly called a 'man of war'; the image is not domesticated. <b>YHWH is his name (YHWH shemo):</b> The self-identification formula — the victor's name is declared after the victory; the name is proven by the deed.</p>",
    "4": "<p><b>Pharaoh's chariots (markevot Par'oh) and his host (ve'cheilo) he cast (yaroh) into the sea:</b> Yaroh = Qal perfect of yarah (to throw/hurl); the same root as Torah (instruction/direction, from the same throwing/pointing gesture). <b>His chosen officers (mivchar shalishav) were sunk (tuba'u) in Yam Suph:</b> Bacha = to choose/select; shalish = officer of the third rank (possibly chariot commander); taba = to sink/drown.</p>",
    "5": "<p><b>The floods (tehomot) covered them:</b> Tehomot = deep waters, plural of tehom — the primordial deep of Gen 1:2 (tehom, the abyss over which the Spirit hovered); the waters of chaos/death that YHWH ordered at creation now serve as instruments of judgment on those who opposed the new creation of the Exodus. <b>They went down into the depths (metzulot) like a stone:</b> Metzulot = depths (from tzlul = to sink); the stone image becomes lead in v.10.</p>",
    "6": "<p><b>Your right hand (yemincha), O YHWH, glorious in power (ne'dari vakoach):</b> Nedar = to be glorious/distinguished/majestic; the divine right hand (yamin) is the instrument of both creation (Ps 98:1) and destruction. <b>Your right hand shatters (tir'atz) the enemy:</b> Ratatz = to dash to pieces/shatter (the same verb as Ps 2:9 — ‘dash them to pieces like a potter’s vessel’).</p>",
    "7": "<p><b>In the greatness of your majesty (berov ga'oncha) you overthrow (teharos) your adversaries:</b> Ga'on = majesty/grandeur, but also pride/arrogance — the word can be used for both divine majesty and human hubris; YHWH's ga'on is what Pharaoh's ga'on was trying to counterfeit. Haras = to pull down, tear down. <b>You send out your fury (charoncha) and it consumes them like stubble (ke'qash):</b> Charon = burning anger (from charah, to burn); the imagery of fire consuming chaff is judgment language used throughout the prophets (Isa 5:24; Nahum 1:10).</p>",
    "8": "<p><b>At the blast of your nostrils (beruach appecha):</b> Ruach appecha = the wind/breath of your nostrils — the dual form apayim (nostrils) emphasizes the physical image of YHWH exhaling in anger; the same ruach that moved over the waters in Gen 1:2. <b>The floods stood upright like a heap (netzvu ke'mo-ned):</b> Natzav = to stand erect/upright (Niphal); ned = a heap or mound of water (also used in Josh 3:13,16 for the Jordan's walls at the crossing). <b>The deep waters congealed (qafe'u tehomot):</b> Qapha = to congeal/coagulate (of water freezing or thickening) — the tehom of Gen 1:2, now congealed into solid walls at divine command, anticipates the Jordan crossing and inverts the creation narrative: waters that were separated at creation are re-parted for redemption.</p>",
    "9": "<p><b>The enemy said, 'I will pursue (erdof), I will overtake (asig), I will divide the spoil':</b> The enemies' first-person boast is quoted verbatim — five verbs of self-confident action (pursue, overtake, divide, fill, draw sword, destroy). The boast structure is a rhetorical device in ancient Near Eastern poetry; cf. the Assyrian king's boasts in Isa 10:8-14. <b>My desire (nafshi) shall have its fill of them:</b> Nefesh = soul/self/throat/desire; nafshi here = 'my appetite' — the enemy consuming Israel is now consumed by the sea.</p>",
    "10": "<p><b>You blew with your wind (nashafta b'ruacha), the sea covered them:</b> Nashaf = to blow; the divine breath/wind that parted the sea now reverses and closes it. <b>They sank like lead (ka'oferet) in the mighty waters (mayim addirim):</b> Oferet = lead (the heaviest common metal); addirim = mighty/majestic (same root as adon = lord). The progression from stone (v.5) to lead (v.10) emphasizes the finality of the sinking.</p>",
    "11": "<p><b>Who is like you (mi-kamokha), O YHWH, among the gods (ba'elim)?</b> The incomparability formula — the rhetorical question that functions as the song's theological climax. Ba'elim = among the mighty ones/gods; the song does not deny the existence of other powers but asserts YHWH's incomparable superiority. <b>The name Micah</b> (miykah = who is like YHWH?) derives from this verse. <b>Awesome in glorious deeds (nora tehillot):</b> Nora = awesome/fearsome (Niphal participle of yara = to fear); tehillot = praises/glorious deeds. <b>Doing wonders (oseh-pele'):</b> Pele' = wonder/miracle — the nomen of marvel that defies categorization.</p>",
    "12": "<p><b>You stretched out your right hand; the earth swallowed them (tivelam ha'aretz):</b> Bala' = to swallow/engulf; the earth (aretz) now joins the sea as instrument of judgment — the text moves beyond the historical event to its cosmic significance. The victory over Pharaoh is a defeat of the anti-creation forces.</p>",
    "13": "<p><b>In your covenant love (bechasdecha) you have led (nachita) the people whom you have redeemed (ga'alta):</b> Hesed = covenant faithfulness/steadfast love; nachah = to lead/guide (the shepherd verb); <b>ga'al</b> = to redeem as kinsman-redeemer (the same term as in 6:6 — YHWH as Israel's go'el). The Exodus is here framed as an act of kinsman-redemption: YHWH acting as the nearest relative who pays the ransom price to free enslaved kin. <b>To your holy abode (neveh qodshecha):</b> Neveh = pasture/abode (the shepherd's dwelling place — the cosmic mountain as YHWH's pasture).</p>",
    "14": "<p><b>The peoples have heard (shamu'u), they tremble (yirgazun):</b> Ragaz = to tremble/shake (with both fear and excitement — the ambiguous trembling of theophany). The ripple effect: Egypt's defeat produces existential terror in all surrounding nations. <b>Anguish has seized the inhabitants of Philistia (chil achaz yoshevei Peleshet):</b> Chil = birth pangs/writhing; achaz = to seize/grip; the nations writhe as if in labor — a frequent prophetic metaphor for divine judgment (Isa 13:8; Jer 6:24).</p>",
    "15": "<p><b>The chiefs of Edom (alufei Edom) are dismayed (nibhalu); the leaders of Moab, trembling seizes them (yo'chuzan ra'ad):</b> Aluf = chief/thousand-commander (from aleph = ox = strength); bahel = to be terrified/dismayed; ra'ad = trembling. Edom and Moab are the future enemies Israel will encounter on the way to Canaan — their paralysis is predicted here, to be confirmed in Num 22 (Balak of Moab's terror) and the Edom encounter in Num 20.</p>",
    "16": "<p><b>Terror and dread fall upon them (tippol aleihem emah va'pachad):</b> Emah = terror (from the root of fear); pachad = dread/sudden fear. <b>Because of the greatness of your arm (bigdol zero'echa) they are still as a stone:</b> Zero'a = arm (the arm of YHWH is a major Exodus image alongside the hand/yad); the nations are petrified — literally stone-still. <b>Till the people pass by whom you have purchased (qanita):</b> Qanah = to acquire/create/possess — the creation verb (Gen 14:19 'Creator/Possessor of heaven and earth' uses qanah). Israel is YHWH's possession in the sense of being his created handiwork.</p>",
    "17": "<p><b>You will bring them in and plant them (tebitemo v'tita'emo) on your own mountain (behar nachalotecha):</b> Neta' = to plant; nahalah = inheritance/allotment (the land-distribution term that will structure Joshua). The planting of Israel on the mountain is the agricultural image of settlement. <b>The sanctuary (miqdash) which your hands have established (konenut yadecha):</b> Miqdash = holy place; kun = to establish/prepare. The Song of the Sea anticipates both Sinai (the immediate destination) and Zion (the ultimate destination), with the tabernacle as the mobile version and the Temple as the fixed form.</p>",
    "18": "<p><b>YHWH will reign forever and ever (YHWH yimloch le'olam va'ed):</b> Malak = to reign/be king (Qal imperfect — ongoing, permanent reign); olam = age/eternity; va'ed = and beyond/and further. The concluding declaration of the Song: the Exodus has demonstrated YHWH's eternal kingship. This verse is embedded in Jewish liturgy (Aleinu prayer) as the eschatological hope; Revelation's heavenly hymns draw on this declaration (Rev 11:15; 19:6).</p>",
    "19": "<p><b>For when the horses of Pharaoh came with his chariots and horsemen into the sea, YHWH brought back the waters of the sea over them:</b> The prose summary (vv.19-21) provides the historical referent for the poetry of vv.1-18, framing the Song as the inspired response to a specific historical event. The prose restates the key facts without embellishment, grounding the poem in history.</p>",
    "20": "<p><b>Miriam the prophetess (Miriam hanevi'ah), the sister of Aaron:</b> Miriam is identified as a prophetess (nevi'ah) — the feminine form of navi, one who speaks for God. She is named sister of Aaron (not of Moses), possibly reflecting a tradition that distinguishes her primary association. <b>Took a tambourine (tof) in her hand:</b> Tof = hand-drum/tambourine (the standard instrument of female celebration in ancient Israel — cf. Judg 11:34; 1 Sam 18:6); <b>with dancing (b'machol):</b> machol = round dance (from chul = to whirl/dance). The women's antiphonal response was a recognized form of celebration after military victory.</p>",
    "21": "<p><b>Miriam sang to them: 'Sing to YHWH, for he has triumphed gloriously':</b> The Miriam Song (v.21) is possibly the oldest literary layer — a two-line refrain that Moses's longer song (vv.1-18) elaborates. The relationship between the two songs (which is earlier?) is debated; the antiphonal structure (Moses's song → Miriam's response) may reflect the liturgical performance tradition of Israel's victory celebrations. Both use the same opening (ki ga'oh ga'ah), suggesting either direct quotation or a shared liturgical formula.</p>",
    "22": "<p><b>Moses led Israel onward from Yam Suph (vayyasa' Moshe et-Yisra'el):</b> The Hiphil of nasa' (to cause to journey) — Moses as the human shepherd/leader. <b>Wilderness of Shur (midbar Shur):</b> Shur = wall (possibly the Egyptian border wall, known archaeologically as the 'Wall of the Ruler' or 'Walls of Horus' — the defensive frontier). The wilderness of Shur is the Sinai Peninsula's western desert. <b>Three days without finding water:</b> The three-day journey that tests the new nation immediately after the Song — from triumph to thirst in three days.</p>",
    "23": "<p><b>Marah — they could not drink (lo yaklu lishhot) the water because it was bitter (ki marim hem):</b> Marah means bitter; the place is named from the water's quality (aetiological etymology). Mar = bitter; the narrative names the place by the crisis it creates. The bitter-waters test follows immediately upon the crossing, establishing the wilderness complaint pattern: abundance and crisis alternate to develop trust.</p>",
    "24": "<p><b>The people grumbled (vayillonu) against Moses: 'What shall we drink?'</b> Lun = to murmur/lodge/complain (the technical wilderness-complaint verb; also used in 16:2, 17:3; Num 14:2; etc.). The complaint is against Moses but addressed to YHWH — the people's anger at the human leader is always implicitly against the divine one who sent him. The question mah nishteh (what shall we drink?) is the first of the wilderness water-complaints.</p>",
    "25": "<p><b>He cried to YHWH (vayyitz'aq el-YHWH), and YHWH showed him a log (etz):</b> Za'aq = to cry out (Moses uses the same verb the Israelites used in 2:23 — the leader intercedes using the vocabulary of oppression). <b>Etz</b> = tree/wood/timber — the material is deliberately unspecified; the tradition does not explain what species of tree or how the chemistry works, preserving the miraculous character of the sweetening. The etz thrown into bitter water to make it sweet is a type-pattern rich in later typology: the cross (the etz of crucifixion) makes the bitter waters of existence sweet. <b>There he made for them a statute and a rule (choq umishpat) and there he tested them (nissahu):</b> First occurrence of choq (statute/ordinance) and mishpat (judgment/rule) together — the pair that will structure Sinai legislation. Nissah = to test (the verb of Gen 22:1 — the Aqedah); the wilderness is the testing ground where faith formed at the sea is refined.</p>",
    "26": "<p><b>If you will diligently listen (shamo'a tishma') to the voice of YHWH:</b> The doubled infinitive absolute + imperfect = the most emphatic form of the conditional — 'if you will truly/completely listen.' <b>And do what is right in his eyes (hay'yashar b'einav):</b> Yashar = upright/straight/right; the ethical standard is YHWH's sight, not human consensus. <b>I will put none of the diseases (machalah) of Egypt upon you:</b> The diseases of Egypt = the plagues (the ten plagues are now a threat to Israel if they disobey — the covenant has two sides). <b>For I am YHWH your healer (YHWH rofecha):</b> Rapha = to heal; YHWH-Rophe' = YHWH the Healer — the first compound divine name in the post-Exodus narrative. The name reveals YHWH's character through the act: the God who made bitter water sweet is also the God who heals the diseases of Egypt. Healing and obedience are structurally linked.</p>",
    "27": "<p><b>Twelve springs of water (shtem esreh einot mayim) and seventy palm trees (shiv'im temarim):</b> Twelve springs (ayin = spring/eye) correspond to the twelve tribes — the abundant provision matches the structure of the community. Seventy palms (temarim = date palms, from tamar = upright/palm) correspond to the seventy souls who went down to Egypt (Gen 46:27) and the seventy elders of Israel. The numbers are too precise to be accidental; Elim is a type of the eschatological rest — twelve wells and seventy trees, enough for each tribe and each elder. <b>They encamped there by the water (al-hamayim):</b> After bitter Marah, abundant Elim — the rhythm of trial and provision that will structure the entire wilderness narrative.</p>"
  }
}

def main():
    existing = load_comm('mkt-original', 'exodus')
    merge_comm(existing, EXODUS_ORIGINAL)
    save_comm('mkt-original', 'exodus', existing)
    print('Exodus 13-15 mkt-original commentary written.')

if __name__ == '__main__':
    main()
