"""
mkt-original layer — Acts chapters 12–13
Run: python3 scripts/zc-original-acts-12-13.py
Output: data/commentary/mkt-original/acts.json

Key decisions:
- Acts 12 Herod = Agrippa I (ruled AD 41-44, grandson of Herod the Great); his death in v23
  matches Josephus's account (Ant. 19.8.2), corroborating Luke's historical precision
- Acts 12:18 etropophoresan (v18) is the text-critical crux — MKT follows the 'nursed/endured'
  (tropophoreō) reading supported by codex B; the 'bore their conduct' sense is more consonant
  with Deut 1:31 LXX than 'endured their behavior'
- Acts 13:9 'Saulos de ho kai Paulos' marks the permanent name-shift; 'Paul' is not a
  conversion name but the Hellenistic cognomen he used in Gentile contexts
- Acts 13:48 'tetagmenoi eis zōēn aiōnion' — the perfect passive participle implies prior
  divine appointment; Luke uses it without qualification; not to be flattened
- Existing entry: ch13 v39 — merge_comm will skip it
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(layer, book):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(layer, book, data):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    # INTENT: add entries without overwriting existing ones; ch13 v39 already present
    # CHANGE? If schema changes, update here
    # VERIFY: after run, ch12/ch13 in mkt-original/acts.json have all verse keys
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

ORIGINAL = {
  "12": {
    "1": "<p><strong>Hērōdēs ho basileus</strong> ('King Herod'): this is Herod Agrippa I (grandson of Herod the Great), who ruled Judea from AD 41-44 after receiving the kingdom from Claudius. Unlike the tetrarchs of Luke's Gospel, he held the full title of king over the entire Herodian territory. His persecution of the church is politically motivated — v.3 shows he acted because it 'met with approval among the Jewish leaders' — establishing him as an opportunistic rather than principled opponent of the movement.</p>",

    "2": "<p><strong>aneilen de Iakōbon ton adelphon Iōannou machaira</strong> ('he killed James the brother of John with the sword'): the death of James son of Zebedee — the first of the Twelve to die — is reported without commentary or martyrdom account. Luke's laconic treatment contrasts sharply with the extended Stephen narrative; perhaps the brevity reflects the speed and summary nature of James's execution, or a Lucan preference to focus on the continuing mission rather than deaths. <em>Machaira</em> (sword) suggests decapitation — the execution method for enemies of the state under Roman law.</p>",

    "3": "<p><strong>hēmerai tōn azymōn</strong> ('days of Unleavened Bread'): the Passover-season arrest of Peter deliberately echoes the Passover-season arrest of Jesus (Luke 22:1-2). Luke's temporal note is not merely historical precision but typological signaling: God delivers his servant at Passover, as he has before. The Exodus pattern structures both the Passion and the apostolic mission.</p>",

    "4": "<p><strong>tetradion stratiōtōn tessarsin</strong> ('four squads of four soldiers'): sixteen soldiers in rotating shifts of four meant continuous guard coverage. The military detail is historically precise; Roman custodial practice for high-value prisoners required soldiers chained directly to the prisoner (v.6). <em>Meta to Pascha</em> ('after the Passover'): Herod postpones the trial until after the festival, unwilling to execute during the feast — the same political calculation as before the Passion (Luke 22:2).</p>",

    "5": "<p><strong>proseuchē de ēn ektenōs ginomenē</strong> ('earnest prayer was being made'): <em>ektenōs</em> (intensely, fervently, stretched-out) appears only twice in the NT — here and Luke 22:44, where Jesus prayed ektenōs in Gethsemane. Luke's parallel is deliberate: at the crisis point, the response is prayer stretched to its limits. The community's prayer for Peter mirrors Jesus's Gethsemane prayer before his Passion; the outcome — miraculous deliverance — is the resurrection pattern applied to the apostle.</p>",

    "6": "<p><strong>hē de nyx ekeinē ēn ho Petros koimōmenos</strong> ('that very night Peter was sleeping'): Peter's sleep the night before his anticipated execution recalls the disciples' sleep in Gethsemane but inverts its significance. Where the disciples' sleep in Gethsemane represented failure of vigilance, Peter's sleep represents the peace of one entrusting himself to God (Ps 4:8: 'in peace I will lie down and sleep; for you alone, O LORD, make me dwell in safety'). The chains and guards frame the setting's impossibility; the sleep frames Peter's trust.</p>",

    "7": "<p><strong>angelos Kyriou epestē kai phōs elampsen en tō oikēmati</strong> ('an angel of the Lord appeared and light shone in the cell'): the angelic appearance with light is a theophanic marker throughout the OT and Luke-Acts (1:11-12; 2:9; Acts 10:3). <em>Pataxas de tēn pleuran</em> ('striking his side') — Luke's vocabulary is neutral but the physical gesture is intimate; the angel wakes Peter directly. The sequence — light, striking, waking, chains falling — is structured as a miniature liberation narrative.</p>",

    "8": "<p>The angel's instructions — dress, put on sandals, wrap your cloak — are practical and specific, in contrast to Peter's dreamlike disorientation (v.9). The mundane detail of clothing has been read as an Exodus allusion (Exod 12:11: 'eat it with your cloak tucked into your belt, your sandals on your feet, and your staff in your hand'), though Luke does not make the connection explicit. The specificity authenticates the account's grounding in eyewitness memory.</p>",

    "9": "<p><strong>ouk ēdei hoti alēthes estin to ginomenon dia tou angelou</strong> ('he did not know that what the angel was doing was real'): Peter's cognitive state is <em>horama</em>-like — he processes the experience as vision rather than event. This is Luke's narrative concession to the marvel: even the recipient did not initially believe what was happening. The use of <em>horama</em> (vision, v.9) connects to the Acts 10 vision language; divine communication and divine action blur at their edges.</p>",

    "10": "<p><strong>aute automate ēnoigē autois hē pyle</strong> ('the gate opened to them by itself'): <em>automate</em> (automatically, by itself) is a rare word in biblical Greek; it appears in Mark 4:28 for the earth producing grain 'by itself' as a natural process. Here the automatic opening is miraculous — no agent, no mechanism. Luke's vocabulary choice emphasizes that the gate's opening was neither accidental nor humanly engineered. The iron gate (<em>sidarean pylēn</em>) marks the definitive outer boundary; once through it, Peter is in the open city.</p>",

    "11": "<p><strong>en emautō genomenos</strong> ('having come to himself'): the Greek idiom (<em>en emautō ginomai</em>) means to recover one's senses, to return to normal consciousness. It appears in Luke 15:17 for the prodigal son's moment of recognition. Peter's coming-to-himself marks the transition from dreamlike disorientation to clear-eyed recognition of divine rescue. <em>Exeleto me ek cheiros Hērōdou</em> ('rescued me from Herod's hand'): the OT idiom of God's hand rescuing from a king's hand (2 Sam 3:18; 1 Kgs 8:53).</p>",

    "12": "<p>Mary the mother of John Mark is identified as the host of a prayer meeting, suggesting a house-church gathering. The name-chain — Mary, John called Mark — introduces John Mark, who will become significant as a point of contention between Paul and Barnabas (15:37-39) and who is identified with the author of the second Gospel in later tradition (Papias, ca. AD 130). Luke's attention to names in Acts reflects careful sourcing; his information about the Jerusalem community is consistently specific.</p>",

    "13": "<p><strong>Rhodē</strong> (Rhoda, meaning 'rose'): a maidservant who is named — unusual for slaves in ancient texts. The naming signals that Rhoda's role in the story was remembered in community tradition. Luke's narrative here is unusually novelistic — the servant's astonishment, her running back without opening the door, her excited announcement — suggesting a story told and retold within the community with affection for its vivid details.</p>",

    "14": "<p>Rhoda's failure to open the door from sheer joy (<em>apo tēs charas</em>) is Luke's most humanly comic scene in Acts. She recognizes Peter's voice before seeing him, races back to report, and leaves him knocking at the gate — a detail that the community apparently told for years. Luke's inclusion of this human particularity suggests that his sources included firsthand testimony from participants; it is precisely the kind of detail that survives in oral tradition because of its combination of joy and absurdity.</p>",

    "15": "<p><strong>ho angelos autou estin</strong> ('it is his angel'): the community's explanation — that it must be Peter's guardian angel — reflects the first-century Jewish tradition of personal angels modeled on Dan 10:13-21 and the OT divine-messenger tradition. They prayed for Peter but do not immediately believe he has been delivered; they posit that the angel they associate with Peter has taken his form. Luke records the belief without endorsing or dismissing it; the narrative's irony is that the actual Peter is outside knocking while they debate his angelic substitute.</p>",

    "16": "<p><strong>exestēsan</strong> ('they were astonished/beside themselves'): Luke's characteristic vocabulary for the response to miraculous divine action (2:7; 8:13; 9:21; 10:45). The astonishment of those who have been praying earnestly for Peter's release is Luke's quiet theological comment: prayer is offered in faith, but the faith of those praying is itself often smaller than the God to whom they pray. The community's astonishment is not a failure but a measure of the miracle's magnitude.</p>",

    "17": "<p><strong>kataseisas autois tē cheiri sigān</strong> ('motioning to them with his hand to be quiet'): the oratorial gesture — right hand raised, palm forward — is the same as Paul's gesture in 13:16 and 21:40. It is the standard ancient rhetorical signal for attention and silence before speaking. <em>Iakōbō kai tois adelphois</em> ('to James and the brothers'): this is James the Lord's brother (Gal 1:19), who is emerging as the leader of the Jerusalem church. The instruction to report to him signals the authority structure Luke is tracking toward the Jerusalem Council of ch.15.</p>",

    "18": "<p><strong>tarache ouk oligē en tois stratiōtais</strong> ('no small commotion among the soldiers'): Luke's characteristic litotes — 'not small' = considerable — understates the military crisis. <em>Ti ara ho Petros egeneto</em> ('what had become of Peter'): the question is unanswerable within the framework available to the soldiers; their prisoner is gone from a locked, guarded cell. The commotion is the mirror image of the community's prayer meeting — there, joy and astonishment; here, confusion and crisis.</p>",

    "19": "<p><strong>anakrinas</strong> ('having cross-examined'): the legal term for thorough judicial interrogation. Herod's response to failing to find Peter is to execute the guards — standard Roman military discipline for soldiers who allowed a prisoner to escape (cf. 16:27, where the Philippian jailer assumes the same fate and considers suicide). The detail authenticates Luke's knowledge of Roman military practice. <em>Katēlthen apo tēs Ioudaias eis Kaisareian</em>: Herod's withdrawal to Caesarea sets up his fatal speech in vv.21-23.</p>",

    "20": "<p><strong>thymomachōn</strong> ('extremely angry'): a hapax in the NT; the compound — <em>thymos</em> (passion/rage) + <em>machomai</em> (fight) — describes violent, passionate anger. Herod's quarrel with Tyre and Sidon is an economic dispute (they depended on Herod's territory for food imports, v.20b). The deputation's mission — securing audience through Blastus the chamberlain — uses the standard vocabulary of Hellenistic diplomacy. Luke's knowledge of this internal dynastic and commercial detail suggests he had access to Herodian court sources.</p>",

    "21": "<p><strong>endysas esthēta basilikēn</strong> ('dressed in royal robes'): Josephus's parallel account (<em>Antiquities</em> 19.8.2) describes silver robes that gleamed brilliantly in the morning sun, causing the crowd's exclamation. Luke's account and Josephus's are independent corroborations of the same event, each preserving different details. <em>Dēmēgorein</em> ('delivered a public address') is a technical term for formal civic oratory; Herod's speech is a set-piece of Hellenistic royal self-presentation.</p>",

    "22": "<p><strong>theou phōnē kai ouk anthrōpou</strong> ('the voice of a god, not of a man'): the crowd's acclamation is the precise form of blasphemy — attributing divine status to a mortal. Josephus adds that Herod saw an owl and took it as an omen of death (recalling an earlier omen), but Luke focuses on the theological issue: Herod accepted acclamation that should be given to God alone. The structural echo of Isa 14:13-15 ('I will make myself like the Most High') and Ezek 28:2 is the theological framework Luke invokes without citing.</p>",

    "23": "<p><strong>parachrēma de epataxen auton angelos Kyriou, anth' hōn ouk edōken tēn doxan tō theō</strong> ('immediately an angel of the Lord struck him, because he did not give glory to God'): the causation is explicit — <em>anth' hōn</em> ('because') names the theological reason. <strong>skōlēkobrōtos genomenos</strong> ('becoming eaten by worms'): a distinctive vocabulary item (hapax in NT) that Josephus's account corroborates (violent intestinal pain, five-day illness, death at Caesarea). The divine judgment is immediate, precise, and publicly witnessed — the inverse of the community's miraculous deliverance in vv.7-11.</p>",

    "24": "<p><strong>ho de logos tou theou ēuxanen kai eplēthyneto</strong> ('the word of God kept growing and multiplying'): the fourth of Luke's Acts growth-summaries (2:47; 4:4; 5:14; 6:7; 12:24). Luke places it immediately after Herod's death — the persecutor is gone; the word continues. The pairing of <em>auxanō</em> (grow) and <em>plēthynō</em> (multiply) echoes the language of Israel's growth in Egypt (Exod 1:7 LXX: <em>auxanon kai plēthynomenon</em>), framing the church's expansion as the continuation of God's people-multiplying work.</p>",

    "25": "<p><strong>hypostrepsan ex Ierousalēm</strong> ('having returned from Jerusalem'): the reference to the relief mission of 11:29-30; Barnabas and Saul had completed the famine-relief delivery and now return to Antioch with John Mark. This transitional verse closes the Jerusalem section (chs.11-12) and opens the Antioch mission section (ch.13). Luke's structure moves the narrative's center of gravity from Jerusalem to Antioch, as the Gentile mission is about to begin.</p>"
  },

  "13": {
    "1": "<p><strong>prophētai kai didaskaloi</strong> ('prophets and teachers'): the two foundational ministries of the Antioch community. The list of names is striking — Barnabas (Cypriot Levite), Simeon called Niger (perhaps African, Niger = 'black'), Lucius of Cyrene (North African), Manaen (a childhood companion of Herod Antipas — <em>syntrophos</em>), and Saul. The community's diversity — African, diaspora, royal-adjacent, Pharisee — is itself a sign of the Spirit's work transcending ethnic and social boundaries.</p>",

    "2": "<p><strong>leitourgountōn de autōn tō kyriō kai nēsteuontōn</strong> ('while they were serving the Lord and fasting'): <em>leitourgeō</em> is the LXX term for Levitical cultic service (Num 8:22; 16:9); Luke applies it to the church's corporate worship, framing the community's prayer and fasting as priestly ministry. <strong>to Pneuma to Hagion eipen</strong> ('the Holy Spirit said'): direct divine speech to the worshipping community — not through vision or dream but as direct prophetic address. This is the apostolic-age parallel to OT prophetic commissioning (Isa 6:8; Jer 1:5).</p>",

    "3": "<p><strong>nēsteusantes kai proseuxamenoi kai epithentes tas cheiras autois apelysan</strong>: the commissioning sequence — fasting, prayer, handlaying, sending — is the church's missionary ordination rite. The same triad appears at Stephen and the Seven's appointment (6:6) and anticipates the Pastoral Epistles' eldership-ordination (1 Tim 4:14; 2 Tim 1:6). It is the community's formal act of releasing Barnabas and Saul from local accountability to a broader mission accountability, while the Spirit's commissioning (v.2) is the primary authorization.</p>",

    "4": "<p><strong>ekpempomenoi hypo tou Hagiou Pneumatos</strong> ('sent out by the Holy Spirit'): the passive participle makes the Spirit the primary sender; the community's sending in v.3 is the human correlate. Luke's mission theology is consistently double-agented: the Spirit initiates and sends; the community confirms and releases. The route — Seleucia (port city of Antioch) → Cyprus → eventually Asia Minor — follows the natural sea routes of the eastern Mediterranean.</p>",

    "5": "<p><strong>en tais synagōgais tōn Ioudaiōn katēngellon ton logon tou theou</strong> ('they proclaimed the word of God in the synagogues of the Jews'): Paul's consistent synagogue-first strategy throughout Acts (13:5, 14; 14:1; 17:1, 10, 17; 18:4, 19; 19:8) reflects both theology (Rom 1:16: 'to the Jew first and also to the Greek') and pragmatic access to biblically literate audiences. The synagogue provided a ready context: readers of Scripture who needed only to hear that the prophecies were fulfilled.</p>",

    "6": "<p><strong>Bariēsoun</strong> ('Bar-Jesus', 'son of Jesus/salvation'): the name is ironic — a man named 'son of salvation' opposes the message of salvation. Luke identifies him as a <em>magos</em> (sorcerer/magician) and <em>pseudoprophētēs</em> (false prophet); the combination appears in Deut 13:1-5 as precisely the profile of those who lead Israel away from God. The confrontation will echo Moses's contest with Pharaoh's magicians (Exod 7-8) in its outcome.</p>",

    "7": "<p><strong>Sergios Paulos, anēr synetōs</strong> ('Sergius Paulus, an intelligent man'): the designation <em>synetos</em> (intelligent, prudent) anticipates his receptivity to the gospel. Archaeological evidence corroborates a Sergius Paulus as a Roman official in Cyprus in roughly this period. The proconsul's summoning of Barnabas and Saul (<em>epezētēsen akousai ton logon tou theou</em>, 'sought to hear the word of God') shows the gospel's attraction to thoughtful Gentile officials — a recurring Lukan theme.</p>",

    "8": "<p><strong>Elymas ho magos</strong> ('Elymas the sorcerer'): Luke's parenthetical explanation — 'for that is what his name means' — is puzzling since Elymas does not obviously derive from Bar-Jesus; the connection may be through an Aramaic word for 'wise man' or 'sorcerer'. Whatever its etymology, Luke presents the name as identifying his function. <em>Anthistato</em> ('opposed them continually'): the imperfect tense marks persistent, ongoing opposition — not a single objection but a sustained effort to prevent the proconsul's conversion.</p>",

    "9": "<p><strong>Saulos de, ho kai Paulos</strong> ('Saul, who was also called Paul'): Luke's transition formula marks the permanent shift to the Hellenistic cognomen. 'Paul' (<em>Paulos</em>) was a standard Roman family name; as a Roman citizen, Saul likely always had both names. From this point in Acts, Luke uses 'Paul' consistently, reflecting the name's appropriateness for the Gentile mission context. <em>Plēstheis Pneumatos Hagiou</em> ('filled with the Holy Spirit'): the same Spirit-filling formula as Peter's (4:8; 13:9) before a confrontation — the power of discernment and judgment is explicitly divine.</p>",

    "10": "<p><strong>huie diabolou, echthre pasēs dikaiosynēs</strong> ('son of the devil, enemy of all righteousness'): the denunciation is the antithesis of the community's identity markers. Bar-Jesus is named 'son of the devil' in contrast to the 'children of Abraham' (v.26); he is an 'enemy of righteousness' in contrast to the righteous who are vindicated; he is 'full of all deceit and fraud' in contrast to the Spirit-filled who speak truth. <em>Diastrepheōn</em> ('perverting/twisting'): the word for making crooked what God makes straight (Isa 40:4 reversed).</p>",

    "11": "<p><strong>typhlōthēsē</strong> ('you will be blind'): the temporary blindness imposed on Elymas mirrors Paul's own experience on the Damascus Road (9:8-9) — a pointed irony. Where Paul's blindness preceded sight (physical and spiritual), Elymas's blindness marks judgment on resistance. <em>Parachrēma de epesen ep' auton achlys kai skotos</em> ('immediately a mist and darkness fell on him'): the vocabulary is medical — <em>achlys</em> (mist) is used in medical texts for visual clouding. The judgment is precise and immediate, demonstrating the Holy Spirit's authority over spiritual opposition.</p>",

    "12": "<p><strong>episteusen ekplēssomenos epi tē didachē tou kyriou</strong> ('he believed, astonished at the teaching about the Lord'): the proconsul's conversion is triggered by what he <em>saw</em> (the sorcerer's blindness) but anchored in the <em>teaching</em> (<em>didachē</em>). Luke does not describe his response as astonishment at miracle alone but at the teaching confirmed by miracle — precisely the apostolic hermeneutic: signs authenticate the message, but the message is the content of faith.</p>",

    "13": "<p><strong>hoi peri Paulon</strong> ('those around Paul'): the shift in grammatical priority — Paul named first, Barnabas following — marks the reversal from 13:2 where 'Barnabas and Saul' were listed in that order. John Mark's departure from Perga <em>hupestrephsen eis Ierosolymata</em> ('returned to Jerusalem') will become a source of significant dispute (15:37-39). Luke reports the departure without explanation; Paul later views it as abandonment; Barnabas will defend Mark. The seed of a future division is planted without commentary.</p>",

    "14": "<p><strong>Pisidian Antioch</strong>: one of the Seleucid cities named Antioch; distinct from Syrian Antioch. The synagogue service on the Sabbath follows the standard Second Temple order: Scripture reading (<em>anagnōsis nomou kai tōn prophētōn</em>, v.15) followed by homiletical application. The invitation to speak — 'if you have a word of exhortation' (<em>logos paraklēseōs</em>) — is the standard opening for visiting teachers; the phrase will recur in Heb 13:22 as the self-description of that letter.</p>",

    "15": "<p><strong>logos paraklēseōs</strong> ('word of encouragement/exhortation'): the synagogue's invitation uses the same word-family as Barnabas's name (<em>huios paraklēseōs</em>, 4:36), linking the missionary community's character to its proclamation. Paul's response in vv.16-41 is the longest speech of his early ministry in Acts and the most detailed example of his synagogue preaching — a survey of salvation history from election to resurrection.</p>",

    "16": "<p><strong>kataseisas tē cheiri</strong> ('motioning with his hand'): the oratorial gesture signaling the audience to settle for formal speech — the same as Peter's in 12:17 and Paul's later in 21:40. The dual address — <em>andres Israēlitai</em> (Israelite men) and <em>hoi phoboumenoi ton theon</em> (those who fear God, i.e., Gentile sympathizers) — establishes from the opening that the gospel is addressed to both communities. Paul's speech to both audiences in one setting enacts the 'to the Jew first and also to the Greek' principle.</p>",

    "17": "<p><strong>exelexato tous pateras hēmōn</strong> ('he chose our ancestors'): Paul's speech begins with election — God's sovereign choice of Israel — before moving through the history of redemption. <em>Hypsōsen ton laon</em> ('exalted/lifted up the people'): the LXX term for God's special attention to Israel, used in Exod 1:7 for Israel's growth and here for their providential elevation during the Egyptian sojourn. The speech covers election → exodus → wilderness → conquest → judges → monarchy → David → Christ in miniature salvation-history form.</p>",

    "18": "<p><strong>etropophoresan</strong> (<em>etropophoresan</em>): a text-critical crux. The majority text reads <em>etrophophoresan</em> ('bore them as a nurse bears a child' — following Deut 1:31 LXX where God 'carried' Israel like a parent). The alternative <em>etropophoresan</em> (from <em>tropos</em>, manner) means 'endured their manner/conduct.' The MKT follows the nursing/bearing reading, which fits the exodus-care theme. Either reading emphasizes God's patient sustaining of Israel through the wilderness.</p>",

    "19": "<p><strong>kateklēronomēsen tēn gēn autōn</strong> ('distributed their land as inheritance'): the conquest under Joshua is compressed into one phrase. <em>Klēronomeō</em> (inherit) and its cognates are Luke's vocabulary for the covenant land-promise's fulfillment; the New Testament applies the same vocabulary to the eschatological inheritance of the kingdom (Matt 5:5; 25:34; Gal 3:18). Paul's salvation-history sketch treats the land-inheritance as one stage in the larger divine economy.</p>",

    "20": "<p><strong>hōs etesin tetrakosiois kai pentēkonta</strong> ('about 450 years'): the chronological summary integrating the periods from the patriarchs through the judges is notoriously difficult to reconcile with OT data (which, depending on how periods are calculated, yields different totals). The approximate 'about' (<em>hōs</em>) signals that Paul is not providing precise genealogical chronology but a rhetorical survey of God's faithfulness across the sweep of history.</p>",

    "21": "<p><strong>Saoul huion Kis, andra ek phylēs Beniamin</strong>: the identification of Israel's first king by tribal origin connects to the Benjaminite identity of Paul himself (Phil 3:5, 'of the tribe of Benjamin'). Whether the name-echo between Saul the king and Saul/Paul the apostle is deliberate is debated; Luke may be drawing attention to the parallel — a Benjaminite named Saul who was set aside in God's purposes for a greater Davidic mission.</p>",

    "22": "<p><strong>euron Dauid ton tou Iessai, andra kata tēn kardian mou</strong>: Paul blends 1 Sam 13:14 ('a man after God's own heart') with Ps 89:20 ('I have found David, my servant') — the same blend in the same application as Acts 4:25. The David testimony establishes the Davidic typology that leads to Christ: if David was the man after God's heart yet died and saw decay (v.36), the one whom God truly sought — the perfectly faithful Son of David — must be the one who did not see corruption.</p>",

    "23": "<p><strong>toutou ho theos apo tou spermatos kat' epangelian ēgagen tō Israēl sōtēra Iēsoun</strong> ('from this man's seed God brought to Israel a Savior, Jesus, as promised'): the sentence is the hinge of the entire speech. Every line from Abraham to David was moving toward this claim. <em>Kat' epangelian</em> ('according to promise'): the Davidic covenant (2 Sam 7:12-16) is the specific promise in view; <em>sōtēra</em> (Savior) is the title applied to Jesus that makes explicit the salvation-history logic Paul has been tracing.</p>",

    "24": "<p><strong>pro prosōpou tēs eisodou autou</strong> ('before his coming'): the temporal idiom literally means 'before the face of his entry' — John's preparation ministry clears the way for Jesus as forerunner. Paul's inclusion of John's ministry in the synagogue sermon is a consistent element of apostolic preaching (10:37; cf. Mark 1:1-4); it establishes chronological anchoring for the Jesus-claim and draws the John-Jesus connection for audiences who knew John's movement.</p>",

    "25": "<p><strong>erpomenon de Iōannou ton dromos</strong> ('as John was completing his course'): the racing metaphor — <em>dromos</em> (race-course) — appears here and in Paul's farewell at Miletus (20:24) and his self-assessment in 2 Tim 4:7. John completing his course is fulfilled preparation; Paul completing his course will be the apostolic fulfillment of the same pattern. The 'sandal' saying — 'I am not worthy to untie the sandals of his feet' — is verbatim consistent across all four Gospels and Acts, suggesting a fixed tradition.</p>",

    "26": "<p><strong>andres adelphoi, huioi genous Abraam kai hoi en hymin phoboumenoi ton theon</strong>: Paul addresses both groups simultaneously — 'brothers, sons of the family of Abraham, and those among you who fear God' — making explicit that the message of salvation is sent to both (<em>hēmin ho logos tēs sōtērias tautēs exapestalē</em>). The second-person plural includes Gentile God-fearers in 'us,' which is the theological claim the subsequent mission will enact.</p>",

    "27": "<p><strong>agnoēsantes</strong> ('not recognizing/in ignorance'): Paul, like Peter (3:17), attributes the Jerusalem authorities' action to ignorance — not exculpatory ignorance but culpable blindness. <em>Tas phōnas tōn prophētōn ... katakrinantes eplērōsan</em> ('fulfilling the prophets in their condemnation'): the paradox of fulfillment-through-opposition is central to Luke's theology: the very act of rejecting Jesus accomplished what the prophets had written about him. Opposition is not the frustration of the divine plan but its instrument.</p>",

    "28": "<p><strong>mēdemian aitian thanatou heurontes</strong> ('finding no grounds for a death sentence'): the triple innocence declarations of the Passion (Luke 23:4, 14, 22 — Pilate) are echoed in Paul's summary; he emphasizes that the legal verdict was innocent while the execution proceeded regardless. This is not merely historical information but apologetic: Jesus was condemned without legal warrant, which means the condemnation was unjust and the resurrection is God's reversal of an injustice.</p>",

    "29": "<p><strong>panta ta peri autou gegrammena</strong> ('all the things written about him'): the 'all things written' formula (Luke 24:44-46; Acts 13:27, 29) is Luke's comprehensive Scripture-fulfillment claim. Paul does not specify which texts — it is the entire scriptural trajectory, not proof-texts, that has been fulfilled. <em>Ethekan eis mnēmeion</em> ('placed in a tomb'): the burial is included in the kerygmatic sequence (cf. 1 Cor 15:4 — 'he was buried') because it establishes the physical reality of the death that the resurrection reverses.</p>",

    "30": "<p><strong>ho de theos ēgeiren auton ek nekrōn</strong> ('but God raised him from the dead'): the structural <em>de</em> ('but') marks the dramatic reversal at the center of the kerygma. The resurrection proclamation is syntactically simple — subject (God), verb (raised), object (him), prepositional phrase (from the dead) — because its content is world-altering enough to require no rhetorical embellishment. Luke preserves this bare form consistently in apostolic speech (2:24, 32; 3:15; 4:10; 5:30; 10:40; 13:30) as the irreducible core.</p>",

    "31": "<p><strong>hoi nyn eisin martyres autou pros ton laon</strong> ('who are now his witnesses to the people'): the Galilean witnesses — those who accompanied Jesus from Galilee to Jerusalem — constitute the apostolic testimony. Paul distinguishes himself from these witnesses while aligning with their message; he belongs to a different category of witness (the Damascus encounter, 9:3-6; 22:6-11; 26:12-18) but preaches the same risen Lord. The distinction is honest and significant: Paul's apostleship rests on a post-resurrection appearance, not on the pre-Passion companionship.</p>",

    "32": "<p><strong>hēmeis hymas euangelizometha tēn pros tous pateras epangelian genomenēn</strong> ('we proclaim to you the good news of the promise made to the fathers'): the <em>euangelion</em> (good news) is explicitly identified as the fulfillment of the patriarchal promises. Paul's preaching is not the announcement of a new religion but the declaration that Israel's long-awaited inheritance has arrived. The promise-fulfillment schema is the interpretive grid for everything that follows in vv.33-37.</p>",

    "33": "<p><strong>graphetai gar en tō psalmō tō deuterō</strong> ('for it is written in the second Psalm'): Ps 2:7 — 'You are my Son; today I have become your Father' — is applied to the resurrection. The resurrection is the 'today' of the divine declaration; God publicly declares Jesus to be the Son on the day he raises him from the dead (cf. Rom 1:4: 'declared to be the Son of God in power according to the Spirit of holiness by his resurrection from the dead'). The psalm's coronation language is resurrection-coronation language for Paul here.</p>",

    "34": "<p><strong>dōsō hymin ta hosia Dauid ta pista</strong> (Isa 55:3 LXX): 'I will give you the holy and sure blessings of David'. The LXX <em>ta hosia</em> ('the holy/sure things') translates Hebrew <em>chesed</em> (covenant-loyalty), with the LXX adding a layer of holiness (<em>hosios</em>) to the faithfulness concept. Paul's use of this text — the sure Davidic blessings that will not decay — grounds the resurrection in the Davidic covenant: the resurrection is God's faithfulness to his sworn commitment.</p>",

    "35": "<p><strong>dioti kai en heterō legei, Ou dōseis ton hosion sou idein diaphthoran</strong> (Ps 16:10): Paul cites Ps 16:10 as confirmation of 13:34, just as Peter did in Acts 2:27. The <em>hosion</em> ('holy one') whose body does not see corruption (<em>diaphthora</em>) cannot be David, since David died, was buried, and his tomb is known (2:29). The only candidate for the Psalm's fulfillment is the one whom God raised without allowing his body to decay — Jesus of Nazareth.</p>",

    "36": "<p><strong>Dauid men gar idiai genea hypeyretesan tē tou theou boulē ekoimēthē</strong> ('for David, having served God's purpose in his own generation, fell asleep'): the parallel contrast — David served <em>his</em> generation and died; the one God raised serves all generations — is the climax of Paul's argument. <em>Ekoimēthē</em> ('fell asleep'): the Christian euphemism for death rooted in Jewish practice (1 Kgs 2:10 LXX; Job 3:13; Ps 87:6 LXX). <em>Prosetethē pros tous pateras autou kai eiden diaphthoran</em> ('was gathered to his fathers and saw decay') is precisely what the resurrection-candidate of Ps 16:10 did not experience.</p>",

    "37": "<p><strong>hon de ho theos ēgeiren ouk eiden diaphthoran</strong> ('but the one whom God raised did not see decay'): the stark contrast of v.36-37 is Paul's refutation of the suggestion that Ps 16:10 applies to David. The logic is simple: David saw decay; the Psalm promises the Holy One will not see decay; therefore David cannot be the Psalm's referent; the one who did not see decay — Jesus, raised by God — is the Psalm's fulfillment. The argument is identical to Peter's at Pentecost (2:29-31).</p>",

    "38": "<p><strong>aphesis hamartiōn</strong> ('forgiveness of sins'): the offer that crystallizes the entire salvation-history argument. Through Christ — not through Moses (<em>apo pantōn hōn ouk ēdunēthēte en nomō Mōuseōs dikaiōthenai</em>, v.39) — forgiveness is proclaimed. Luke's <em>aphesis</em> vocabulary is his characteristic term for the new-covenant blessing (Luke 1:77; 3:3; 4:18; 24:47; Acts 2:38; 5:31; 10:43; 13:38; 26:18). It carries the sense of release, cancellation of debt — the judicial erasure of the record of sin.</p>",

    "40": "<p><strong>blepete oun mē epelthē to eirēmenon en tois prophētais</strong> ('therefore take care that what is spoken by the prophets does not happen to you'): the warning marks the transition from invitation to judgment — those who hear and refuse the gospel face the prophetic warning's application to themselves. Paul's sermon moves in the same arc as the OT prophets: proclamation → invitation → warning. The Hab 1:5 citation (v.41) is the scriptural ground of the warning.</p>",

    "41": "<p><strong>kataphronētai kai thaumasate kai aphanisthēte</strong> (Hab 1:5 LXX): 'scoffers, wonder and perish!' Paul applies Habakkuk's warning about the Babylonian invasion to the even more incredible 'work' of the resurrection. Habakkuk warned Israel that they would not believe even when told what God was doing through Babylon; Paul warns the synagogue that the same unbelief will prove fatal when confronted with the even more astonishing work of the risen Messiah.</p>",

    "42": "<p>The congregation's response — <em>parekloun eis to metaxy sabbaton lalēthēnai autois ta rhēmata tauta</em> ('begged that these words be spoken to them on the following Sabbath') — marks the initial positive reception that Luke regularly records before the opposition crystallizes (cf. 17:11-12, 32-33). The request for a return visit is the synagogue's standard practice for a compelling visitor-teacher; it gives Paul a second platform and extends the engagement.</p>",

    "43": "<p><strong>proseilython polloi ... tois paroikois</strong> ('many... and proselytes followed'): <em>paroikoi</em> (resident aliens, sojourners) in the LXX describes Israel's status in Egypt; here it identifies Gentile proselytes who have fully converted to Judaism. <em>Peithein autous prosmenein tē chariti tou theou</em> ('persuading them to remain in the grace of God'): Paul's pastoral exhortation to the newly responsive — grace must be continued in, not merely initially received. The language anticipates the Pauline <em>charis</em> theology of the letters.</p>",

    "44": "<p><strong>schedon hē pasa polis synēchthē akousai ton logon tou kyriou</strong> ('almost the whole city gathered to hear the word of the Lord'): Luke's 'almost the whole city' is his characteristic rhetorical hyperbole for civic-scale reception of the gospel (cf. 19:26). The scale of the gathering provokes the jealousy of v.45 — the Jewish leaders' opposition is reactive to the gospel's Gentile success, not a pre-existing theological position against Paul personally.</p>",

    "45": "<p><strong>zēlou eplēsthēsan</strong> ('they were filled with jealousy'): the same <em>plēroō</em>-filling vocabulary used throughout Acts — here for jealousy rather than the Spirit. Luke's contrast is pointed: Spirit-filled witnesses and jealousy-filled opponents. <em>Blasphēmountes</em> ('blaspheming'): the opponents' attacks cross into blasphemy — not against the law or Paul personally but against the word of God and the one it proclaims.</p>",

    "46": "<p><strong>hymin ēn anagkaion prōton lalēthēnai ton logon</strong> ('it was necessary to speak the word of God to you first'): <em>anagkaios</em> (necessary, obligatory) carries divine compulsion — not merely strategic priority but theological necessity. The 'to the Jew first' principle (Rom 1:16) is here stated as the church's non-negotiable missional order. The turning to the Gentiles is not abandonment of Israel but the fulfilment of Israel's missionary vocation: Israel was meant to be the vehicle through which the Gentiles received the blessing (Gen 12:3).</p>",

    "47": "<p><strong>tetheka se eis phōs ethnōn</strong> (Isa 49:6 LXX): 'I have made you a light for the Gentiles.' Paul and Barnabas apply the Second Servant Song's mission directly to themselves: the Servant's commission to be a light to the Gentiles becomes the apostolic commission. The same text cited by Simeon at Jesus's presentation (Luke 2:32) is now cited by the apostles as their own mandate — they continue the Servant's work through Spirit-empowered mission.</p>",

    "48": "<p><strong>tetagmenoi eis zōēn aiōnion</strong> ('appointed/ordained to eternal life'): the perfect passive participle — a completed, prior action with present effect — implies divine prior appointment. Those who believe are identified as those who had been appointed to eternal life; the appointment precedes the belief and is expressed in the belief. Luke does not resolve the tension between divine appointment and human response; he records both without philosophical qualification, as does Paul in his letters (Eph 1:4-5; Rom 8:29-30).</p>",

    "49": "<p><strong>diephereito de ho logos tou kyriou di' holēs tēs chōras</strong> ('the word of the Lord spread through the whole region'): the fifth of Luke's growth-summary refrains (6:7; 12:24; 13:49; 19:20; 28:30-31). Each appears at a narrative turning point; here it marks the successful establishment of the gospel in the Pisidian region before the expulsion that follows. The word's spread is not contingent on the missionaries' continued presence — it has been planted and takes root independently.</p>",

    "50": "<p><strong>epeseirasan tinas gynaikas tais euschēmonas kai tous prōtous tēs poleōs</strong> ('they stirred up devout women of high standing and the leading men of the city'): the opposition strategy — mobilizing socially prominent women and civic leaders against the missionaries — reflects the typical mechanics of community-level expulsion. Prominent women attached to the synagogue as God-fearers had social influence over their husbands; their agitation through their husbands produced the official civic response of expulsion.</p>",

    "51": "<p><strong>ektinaxamenoi ton koniorton tōn podōn</strong> ('shaking the dust from their feet'): the gesture is Jesus's instruction for rejected messengers (Luke 10:11; Matt 10:14; Mark 6:11); the dust-shaking is a visible acted judgment — 'your town's dust, which we carry no further'. Paul and Barnabas perform it 'against them' (<em>ep' autous</em>) — not as personal grievance but as prophetic sign. The missionaries proceed to Iconium; the rejected city receives the sign of coming judgment.</p>",

    "52": "<p><strong>hoi de mathētai eplērounto charas kai Pneumatos Hagiou</strong> ('the disciples were filled with joy and with the Holy Spirit'): Luke closes the Antioch episode with a double-filling — joy and the Holy Spirit together — as the condition of the community left behind. The pairing of joy (<em>chara</em>) and Spirit throughout Luke-Acts (Luke 2:10; 10:21; Acts 2:46; 8:8, 39; 13:52; 15:3) signals the authentic mark of Spirit-life. The missionaries are expelled; the community they leave is thriving. This is Luke's counterintuitive measure of mission success.</p>"
  }
}

def main():
    existing = load_comm('mkt-original', 'acts')
    merge_comm(existing, ORIGINAL)
    save_comm('mkt-original', 'acts', existing)
    for ch in ['12', '13']:
        count = len(existing.get(ch, {}))
        print(f'  ch{ch}: {count} entries')

if __name__ == '__main__':
    main()
