"""
MKT Original Commentary — Hebrews chapters 1–5
Run: python3 scripts/zc-original-hebrews-1-5.py

Key decisions:
- 1:1 polytropōs: adverbial; the varied modes of OT revelation vs. the singular finality of the Son
- 1:3 charakter tēs hypostaseōs: unique philological weight — charakter = engraved impression; hypostasis = substance
- 1:14 leitourgika pneumata: liturgical technical term; angels as liturgical servants of God
- 2:10 archēgon: founder/pioneer/captain — not simply 'author'; leader who goes first
- 2:17 hilaskesthai: propitiation debate — expiation vs. propitiation; LXX usage decisive
- 3:13 apate: 'deceitfulness of sin' — sin as a deceiver, not merely a force
- 4:12 tomōteros hyper: comparative of sharp; two-edged sword divides to the innermost nature
- 4:15 kechraismenon: perfect passive — permanently tested without sin; not 'unable' but 'having withstood'
- 5:8 emathen aph' hōn epathen: learned from what he suffered — deliberate wordplay on mathen/epathen
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

HEBREWS = {
  "1": {
    "1": '<p><strong>polumeros kai polytropōs</strong> — "at many times and in many ways" (<em>polumeros</em>: in many portions/parts; <em>polytropōs</em>: in many modes/manners): the adverbial pair describes the OT revelation\'s characteristic pluralism — different authors, genres, periods, and literary forms. The contrast is with the Son\'s single, definitive, eschatological speaking. <em>Palaios</em> (long ago) points to the temporal distance of the OT revelation; <em>ep\' eschatou tōn hēmerōn toutōn</em> (at the end of these days) is the eschatological marker that the Son\'s speech is the final word in the series.</p>',
    "2": '<p><strong>hon ethēken klēronomon pantōn</strong> — "whom he appointed heir of all things" (<em>klēronomon</em>: inheritor, heir): the appointment (<em>ethēken</em>, placed/set) precedes the creation in salvation-historical logic — the heir is appointed before the estate is created. <em>Di\' hou kai epoiēsen tous aiōnas</em> — "through whom he also made the ages" (<em>aiōnas</em>: ages, worlds — not merely the temporal ages but the entire created order in its temporal unfolding). The Son as both heir and creator establishes his double relationship to the created order: he made it and he will receive it.</p>',
    "3": '<p><strong>apaugasma tēs doxēs kai charakter tēs hypostaseōs autou</strong> — "the radiance of his glory and the exact imprint of his nature" (<em>apaugasma</em>: radiance, effulgence — that which streams out from the source of light; <em>charakter</em>: the impression made by an engraving tool, the exact stamp/character — NT hapax): the two metaphors are complementary. <em>Apaugasma</em> describes the continuous streaming-out of glory from its source (like light from the sun — the sun\'s radiance is not the sun itself but is genuinely from it and conveys it). <em>Charakter</em> describes the exact correspondence between the impression and the seal — the Son bears the exact impression of the Father\'s <em>hypostasis</em> (substance, essential nature). Both terms are drawn from the Hellenistic philosophical and wisdom traditions.</p><p><strong>pheron ta panta tō rhēmati tēs dynameōs autou</strong> — "upholding all things by the word of his power" (<em>pheron</em>: bearing, carrying, upholding — present active participle: continuously upholding): the Son\'s sustaining role in creation is present-tense and ongoing. <em>Tō rhēmati tēs dynameōs autou</em> (by the word of his power) — not by effort but by the same creative word that made all things.</p>',
    "4": '<p><strong>tosoutō kreittōn genomenos tōn angelōn</strong> — "having become so much better than the angels" (<em>kreittōn</em>: superior, better — a key term in Hebrews used 13 times; <em>genomenos</em>: having become — aorist participle marking the historical event of the Son\'s exaltation): the Son\'s superiority is not merely ontological but the result of the exaltation after humiliation. The "becoming better" does not imply a prior equality with angels but the eschatological manifestation of what was always true. <em>Diaphorōteron par\' autous keklēronomēken onoma</em> — "he has inherited a more excellent name than they" (<em>keklēronomēken</em>: perfect active — permanently inherited): the perfect tense indicates a permanent acquisition. The "name" is the Son-name (v5).</p>',
    "5": '<p><strong>Hyios mou ei sy, egō sēmeron gegennēka se</strong> — "You are my Son; today I have begotten you" (Ps 2:7 LXX): the <em>sēmeron</em> (today) is the eschatological "today" of the resurrection-exaltation (Acts 13:33 applies this text to the resurrection). The divine begetting is not eternal generation (though that may be implied in the background) but the eschatological declaration of the Son\'s identity at the exaltation event. <em>Egō esomai autō eis patera kai autos estai moi eis huion</em> (2 Sam 7:14 LXX) — the Davidic covenant promise extended beyond its original Solomonic application to the definitive Son.</p>',
    "7": '<p><strong>ho poiōn tous angelous autou pneumata kai tous leitourgous autou pyros phloga</strong> — "he makes his messengers winds, and his servants a flame of fire" (Ps 104:4 LXX): <em>leitourgous</em> (liturgical servants, ministers — the same word as the priestly and Levitical ministers): angels are characterized as servants/liturgists whose mode of being is as changeable as wind and fire — they serve but they do not reign. The contrast with the eternal Son (vv8-12) is the rhetorical point.</p>',
    "8": '<p><strong>pros de ton huion, Ho thronos sou, ho theos, eis ton aiōna tou aiōnos</strong> — "But of the Son he says: Your throne, O God, is forever and ever" (Ps 45:6 LXX): the vocative <em>ho theos</em> addressed to the Son is one of the strongest direct divine-title applications in the NT. The Psalm 45 text, originally a royal wedding song, addresses the Davidic king as <em>elohim</em> (God/divine one) — Hebrews reads this as a divine address to the Son that confirms his divine status. <em>Eis ton aiōna tou aiōnos</em> (unto the age of the age = forever): the eternal duration of the Son\'s throne contrasts with the angels\' servant role.</p>',
    "10": '<p><strong>Sy kat\' archas, Kyrie, tēn gēn ethemeliōsas, kai erga tōn cheirōn sou eisin hoi ouranoi</strong> — "You, Lord, laid the foundation of the earth in the beginning, and the heavens are the work of your hands" (Ps 102:25-27 LXX): the citation addresses <em>Kyrios</em> (LORD = YHWH in the OT) but Hebrews applies it to the Son — a Christological reading of a Yahweh-text. The permanent stability of the creator (<em>sy de diameneis</em> = you remain) contrasted with the perishing creation establishes the Son\'s divine eternity over against the angels who, like the creation, are changeable.</p>',
    "13": '<p><strong>pros tina de tōn angelōn eirēken pote, Kathou ek dexiōn mou heōs an thō tous echthrous sou hypopodion tōn podōn sou</strong> — "But to which of the angels has he ever said: Sit at my right hand until I make your enemies a footstool for your feet?" (Ps 110:1 LXX): the rhetorical question clinches the argument — God has never addressed any angel with the right-hand session command. <em>Heōs an</em> (until) — the session is not permanent stasis but active waiting for the eschatological subjugation. The verse inaugurates the rest-and-waiting theme that will recur throughout Hebrews.</p>',
    "14": '<p><strong>ouchi pantes eisin leitourgika pneumata eis diakonian apostellomena dia tous mellontas klēronomein sōtērian</strong> — "Are they not all ministering spirits sent out to serve for the sake of those who are to inherit salvation?" (<em>leitourgika pneumata</em>: liturgical/ministerial spirits — <em>leitourgikos</em> is the adjective of priestly/liturgical service; the angels as liturgical servants stands in contrast to the Son as liturgical high priest). The rhetorical question expects a "yes": all angels are servants-for-others, not seated lords.</p>'
  },
  "2": {
    "1": '<p><strong>dei perissoteros prosechein hēmas tois akoustheisin, mēpote pararrūomen</strong> — "we must pay much closer attention to what we have heard, lest we drift away from it" (<em>pararrūomen</em>: to drift past, to flow past — a nautical term for a ship drifting past its harbor because the pilot failed to steer properly): the image of passive drifting is the warning against neglect rather than active apostasy. The comparative <em>perissoteros</em> (more exceedingly) grounds the increased attentiveness requirement in the increased magnitude of the new covenant revelation.</p>',
    "3": '<p><strong>pōs hēmeis ekpheuxometha tēlikaytēs amelēsantes sōtērias</strong> — "how shall we escape if we neglect such a great salvation?" (<em>amelēsantes</em>: having neglected, having cared nothing for — aorist participle): <em>amelēo</em> (to be unconcerned about, to neglect) implies passive indifference rather than active rejection — the warning is against those who simply do not take salvation seriously. The <em>tēlikautēs</em> (so great) grounds the impossibility of escape: the magnitude of the salvation corresponds to the magnitude of the consequence for neglecting it.</p>',
    "9": '<p><strong>ton de brachy ti par\' angelous ēlatōmenon blepomen Iēsoun dia to pathēma tou thanatou doxē kai timē estephanōmenon</strong> — "but we see him who for a little while was made lower than the angels, namely Jesus, crowned with glory and honor because of the suffering of death" (<em>brachy ti par\' angelous ēlatōmenon</em>: made lower for a little — the Ps 8 phrase applied to the incarnate humiliation): the name <em>Iēsoun</em> (Jesus) appears here for the first time in Hebrews, positioned after the description of humiliation — the human name of the one who took the human condition. <em>Doxē kai timē estephanōmenon</em> (crowned with glory and honor) — the perfect passive participle indicates the permanent crown of the exaltation state.</p>',
    "10": '<p><strong>eprepen gar autō... ton archēgon tēs sōtērias autōn dia pathēmatōn teleiōsai</strong> — "it was fitting for him... to make the founder of their salvation perfect through suffering" (<em>archēgon</em>: pioneer, captain, founder — one who leads the way, the first to go through a path that others will follow; <em>teleiōsai</em>: to perfect, complete, bring to the goal — the <em>teleio</em>- root pervades Hebrews): <em>archēgos</em> is not merely an author who initiates from a distance but a pioneer who personally traverses the route. The perfection through suffering is not moral improvement (the Son was not morally deficient) but the completion of the vocational path — the suffering was necessary for the high-priestly qualification.</p>',
    "11": '<p><strong>ho te gar hagiazōn kai hoi hagiazomenoi ex henos pantes</strong> — "for he who sanctifies and those who are sanctified all have one source" (<em>ex henos pantes</em>: all from one — the <em>henos</em> is either masculine [one father, i.e., Abraham, or God] or neuter [one origin/source]): the shared origin establishes the solidarity that makes the Son\'s brotherhood genuine rather than merely analogical. <em>Di\' hēn aitian ouk epaischynetai adelphous autous kalein</em> — "for which reason he is not ashamed to call them brothers" (<em>ouk epaischynetai</em>: is not ashamed — the social-shame context: the exalted one acknowledging his solidarity with the lowly).</p>',
    "17": '<p><strong>hothen ōpheilen kata panta tois adelphois homoiōthēnai, hina eleēmōn genētai kai pistos archiereus ta pros ton theon eis to hilaskesthai tas hamartias tou laou</strong> — "therefore he had to be made like his brothers in every respect, so that he might become a merciful and faithful high priest in the service of God, to make propitiation for the sins of the people" (<em>hilaskesthai</em>: to propitiate, make atonement — the LXX verb for the priestly atonement act on the Day of Atonement [Lev 16:20 LXX]; used for covering/averting divine wrath against sin): the <em>hilaskesthai</em> debate centers on whether "expiation" (neutralizing sin\'s pollution) or "propitiation" (averting God\'s wrath) is primary. The LXX usage and the wrath-context of Hebrews favor propitiation, though the two are not sharply separable. <em>Eleēmōn kai pistos</em> (merciful and faithful) — the two qualifications for a legitimate high priest who genuinely represents the people before God.</p>',
    "18": '<p><strong>en hō gar peponthen autos peirastheis, dynatai tois peirazomenois boēthēsai</strong> — "for because he himself has suffered when tempted, he is able to help those who are being tempted" (<em>peponthen</em>: perfect passive of <em>paschō</em> = to suffer; <em>peirastheis</em>: having been tested/tempted — aorist passive participle): the perfect tense of <em>peponthen</em> (he has suffered, with the suffering-effect remaining) grounds the present capacity to help. The suffering is not merely past but bears on his present qualification. <em>Boēthēsai</em> (to come to the aid, to help — from <em>boaō</em> = to shout + <em>theō</em> = to run): to run to the cry of one who calls for help — the helping is urgent and responsive.</p>'
  },
  "3": {
    "1": '<p><strong>katanoeisate ton apostolon kai archierea tēs homologias hēmōn Iēsoun</strong> — "consider Jesus, the apostle and high priest of our confession" (<em>katanoeisate</em>: aorist imperative of <em>katanoeō</em>, to observe carefully, to fix one\'s attention on — the <em>kata</em> intensifies the observation): Jesus is called <em>apostolos</em> (apostle, sent one) only here in the NT — the term that the community uses for its own commissioned messengers is applied to the Son as the original sent-one from the Father. <em>Homologias</em> (confession): the common confession of faith that the community shares and that defines them.</p>',
    "6": '<p><strong>Christos de hōs huios epi ton oikon autou</strong> — "but Christ is faithful over God\'s house as a Son" (<em>epi ton oikon</em>: over the house — the preposition <em>epi</em> with accusative indicates authority over): the Son\'s position is qualitatively different from Moses\'s <em>en</em> (within) the house — the Son is over it as the builder and heir. <em>Hou oikos esmen hēmeis</em> (whose house we are) — the community is identified as God\'s household; the ecclesiology is household-shaped. <em>Eanper tēn parrēsian kai to kauchēma tēs elpidos mechri telous bebaian katáschōmen</em> — "if indeed we hold fast our confidence and our boasting in our hope firm to the end."</p>',
    "13": '<p><strong>alla parakaleite heautous kath\' hekastēn hēmeran, achris hou to Sēmeron kaleitai, hina mē sklērunthē tis ex hymōn apatē tēs hamartias</strong> — "but exhort one another every day, as long as it is called today, that none of you may be hardened by the deceitfulness of sin" (<em>apatē tēs hamartias</em>: the deceitfulness of sin — <em>apatē</em> is deceit, delusion; sin is personified as a deceiver who leads the mind astray from reality): <em>sklērunthē</em> (be hardened — aorist passive subjunctive of <em>sklērunō</em>): hardening is a process that daily mutual exhortation resists. The "today" of Ps 95 is the present moment of the community\'s hearing — a kairos that closes when the heart hardens.</p>',
    "14": '<p><strong>metochoi gar tou Christou gegonamen, eanper tēn archēn tēs hypostaseōs mechri telous bebaian katáschōmen</strong> — "for we have come to share in Christ, if indeed we hold our original confidence firm to the end" (<em>metochoi tou Christou</em>: partakers/sharers of Christ — <em>metochos</em> appears 6x in Hebrews; sharing/participation is a key Hebrews concept): <em>hypostaseōs</em> — the same word as in 1:3 (<em>charakter tēs hypostaseōs</em>); here it means the foundational confidence/assurance. The sharing in Christ is conditioned on maintaining the beginning (<em>archēn</em>) of that assurance to the end — the condition is not soteriological uncertainty but the community\'s perseverance in the faith-life.</p>'
  },
  "4": {
    "12": '<p><strong>zōn gar ho logos tou theou kai energēs kai tomōteros hyper pasan machairan distomos kai diiknoumenos achri merismou psychēs kai pneumatos, harmōn te kai myelōn, kai kritikos enthumsōeōn kai ennoiōn kardias</strong> — "for the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and of spirit, of joints and of marrow, and discerning the thoughts and intentions of the heart": <em>zōn</em> (living — present active participle: the word has continuous vitality, not static inscription); <em>energēs</em> (active, effective, at work — same root as <em>energeō</em>); <em>tomōteros hyper pasan machairan distomos</em> (sharper than every two-edged sword — <em>tomōteros</em>: comparative of <em>tomos</em>, sharp): the word\'s penetrating power exceeds the finest blade. <em>Merismou psychēs kai pneumatos</em> (division of soul and spirit) — not a technical trichotomy but the penetration of the innermost human reality; <em>psychē</em> and <em>pneuma</em> as the two terms for the inner life. <em>Kritikos</em> (discerning, able to judge — the root of <em>krisis</em>): the word not only penetrates but evaluates what it finds.</p>',
    "13": '<p><strong>kai ouk estin ktisis aphanēs enōpion autou, panta de gymna kai tetrachēlismena tois ophthalmois autou, pros hon hēmin ho logos</strong> — "and no creature is hidden from his sight, but all are naked and exposed to the eyes of him to whom we must give account" (<em>gymna kai tetrachēlismena</em>: naked and exposed/laid bare — <em>tetrachēlismenā</em> is a NT hapax from <em>trachēlos</em> = neck; the image may be of an animal with its neck bent back for slaughter, fully exposed; or a wrestler pinned with head forced back): the divine omniscience before which all creatures are transparent is the basis of the word\'s discerning power.</p>',
    "15": '<p><strong>ou gar echomen archierea mē dynamenon sympathēsai tais astheneiais hēmōn, pepeirasmenon de kata panta kath\' homoiotēta chōris hamartias</strong> — "for we do not have a high priest who is unable to sympathize with our weaknesses, but one who in every respect has been tempted as we are, yet without sin" (<em>sympathēsai</em>: to suffer-with, to feel-with — syn + pathein; not merely intellectual comprehension but shared experience): <em>pepeirasmenon</em> (having been tested/tempted — perfect passive participle: permanently in the state of having been tested — the testing is a completed historical event with permanent relevance): <em>kath\' homoiotēta</em> (according to likeness, in the same way): the testing was genuinely analogous to human experience. <em>Chōris hamartias</em> (apart from sin): the crucial qualification — tested in every way but without sinning; not "unable to sin" as an ontological constraint but "having withstood every test" as a historical fact.</p>'
  },
  "5": {
    "1": '<p><strong>pas gar archiereus ex anthrōpōn lambanomenos hyper anthrōpōn kathistatai ta pros ton theon</strong> — "for every high priest chosen from among men is appointed to act on behalf of men in relation to God" (<em>ex anthrōpōn lambanomenos</em>: taken from among human beings — the high priest\'s humanity is a qualification, not a limitation): <em>ta pros ton theon</em> (things toward God — the priestly representative function): the preposition <em>pros</em> indicates directional orientation; the priest stands between human beings and God, facing toward God on their behalf. The two qualifications (v1: chosen from humans; v4: called by God) define the legitimate priesthood.</p>',
    "2": '<p><strong>metriopathein dynatos tois agnoousin kai planōmenois, epei kai autos perikeitai astheneian</strong> — "he can deal gently with the ignorant and wayward, since he himself is beset with weakness" (<em>metriopathein</em>: to moderate one\'s feelings, to deal with measured emotion — a Stoic philosophical term for the appropriate emotional response between apathy and passion): the high priest\'s capacity for gentle response (<em>metriopathein</em>) is grounded in his own weakness-experience. The contrast with the Son\'s sympathy (4:15) is instructive: the Levitical priest sympathizes because he is himself weak; the Son sympathizes because he has been tested.</p>',
    "7": '<p><strong>hos en tais hēmerais tēs sarkos autou deēseis te kai hiketerias pros ton dynamenon sōzein auton ek thanatou meta kraugēs ischyras kai dakryōn prosenenkas kai eisakoustheis apo tēs eulabeias</strong> — "in the days of his flesh, Jesus offered up prayers and supplications, with loud cries and tears, to him who was able to save him from death, and he was heard because of his reverence" (<em>hiketerias</em>: supplications, olive-branch petitions — the formal term for desperate appeal to a superior; the word is used in Gk papyri for formal petition): the Gethsemane prayer is described without being cited. <em>Eisakoustheis apo tēs eulabeias</em> — "heard because of his reverence" (<em>eulabeia</em>: godly fear, reverent awe — not anxiety but the reverent-careful posture before God): the prayer was heard — not by removal of death but by resurrection through death.</p>',
    "8": '<p><strong>kaiper ōn huios, emathen aph\' hōn epathen tēn hypakoēn</strong> — "although he was a Son, he learned obedience through what he suffered" (<em>emathen aph\' hōn epathen</em>: learned from/out of what he suffered — the deliberate Greek wordplay on <em>emathen</em> [learned, aorist of <em>manthanō</em>] and <em>epathen</em> [suffered, aorist of <em>paschō</em>]; the rhyme and etymology emphasize the connection between suffering and learning): the learning is not correcting a moral deficiency but the vocational acquisition of lived obedience — the Son did not know obedience by abstract divine knowledge but through the experiential path of incarnate life. <em>Kaiper ōn huios</em> (although being Son): the divine sonship does not exempt from the learning-through-suffering path; it is the Son who walks this path.</p>',
    "9": '<p><strong>kai teleiōtheis egeneto pasin tois hypakouousin autō aitios sōtērias aiōniou</strong> — "and being made perfect, he became the source of eternal salvation to all who obey him" (<em>teleiōtheis</em>: having been made perfect/complete/brought to the goal — aorist passive participle): the perfection (<em>teleiōsis</em>) through suffering and obedience is the high-priestly qualification. <em>Aitios sōtērias aiōniou</em> (cause/source/author of eternal salvation) — the <em>aitios</em> (cause, responsible party) is a philosophical and legal term; the Son is the efficient cause of the salvation that is <em>aiōnios</em> (eternal, age-spanning — not merely long-lasting but of the quality of the coming age).</p>',
    "11": '<p><strong>peri hou polys hēmin ho logos kai dysermēneutos legein, epei nōthroi gegonate tais akoais</strong> — "about this we have much to say, and it is hard to explain, since you have become dull of hearing" (<em>nōthroi tais akoais</em>: dull in the ears/hearing — <em>nōthros</em>: sluggish, slow; the same word in 6:12 for sluggishness in faith): the pedagogical self-interruption — the author acknowledges difficulty in communicating and attributes it to the community\'s spiritual torpor, not the topic\'s intrinsic inaccessibility. The Melchizedek exposition that follows is difficult not because the truth is obscure but because the community lacks the spiritual attentiveness to receive it.</p>'
  }
}

def main():
    existing = load_comm('mkt-original', 'hebrews')
    merge_comm(existing, HEBREWS)
    save_comm('mkt-original', 'hebrews', existing)
    total = sum(len(v) for v in existing.values())
    print(f'Hebrews mkt-original: {len(existing)} chapters, {total} verses written.')

if __name__ == '__main__':
    main()
