"""
MKT Original Commentary — Ezra chapters 1–3
Run: python3 scripts/zc-original-ezra-1-3.py

Key decisions:
- Ch1: hēʿîr + rûaḥ = YHWH's arousing of Cyrus's inner disposition, not external compulsion;
  Sheshbazzar as nāśîʾ (hereditary prince) vs pāḥāh (appointed governor);
  vessel list in vv9-11 uses technical cult terminology
- Ch2: bᵉnê vs ʾanšê section markers; extensive Ezra/Neh 7 numerical variants noted;
  Nethinim as nᵉtûnîm (dedicated gift-persons); tiršātāʾ as Persian loanword for governor
- Ch3: yaḥad (together-as-one) as covenant assembly formula; altar-on-base precedes
  foundation (cult before construction); kabbāsîs (base/platform) vs ʾadāmāh;
  antiphonal tôḏāh formula v11; mingled-response vv12-13 as typological frame
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(layer, book):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    return json.loads(p.read_text()) if p.exists() else {}

def save_comm(layer, book, data):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

ORIG = {
  "1": {
    "1": "<p><em>Bišnat ʾaḥat lᵉḵôreš</em> — 'In the first year of Cyrus': the regnal-year formula anchors the return in Persian administrative time. Cyrus II conquered Babylon in 539 BCE; his first regnal year by the Babylonian system was 538 BCE. The explanatory clause 'so that the word of YHWH through Jeremiah might be fulfilled' (<em>lᵉḵallôt dᵉḇar-YHWH mippî yirmᵉyāhû</em>) cites Jer 25:11-12 and 29:10 (70 years of exile); the verb <em>klh</em> in Piel = to complete/bring to completion, framing the return as divine word accomplishing its purpose. The key verb of the verse is <em>hēʿîr YHWH ʾet-rûaḥ kôreš</em>: 'YHWH stirred up the spirit of Cyrus.' <em>ʿûr</em> Hiphil = to rouse, arouse from sleep or inertia; the same verb describes YHWH rousing Cyrus in Isa 41:2 and 45:13. The <em>rûaḥ</em> (spirit/inner disposition) of Cyrus is the object of YHWH's action — not external coercion but internal motivation. The Cyrus Cylinder (539 BCE) records Cyrus attributing his mandate to Marduk rather than YHWH; the author of Ezra reads the same historical event as YHWH's doing, consistent with Isa 44:28-45:1 (YHWH names Cyrus 'my shepherd' and 'his anointed').</p>",
    "2": "<p>Cyrus's proclamation (<em>kōh ʾāmar kôreš</em> = 'thus says Cyrus') follows the standard ancient Near Eastern royal proclamation formula, the same <em>kōh ʾāmar</em> used for prophetic oracle delivery — the king speaks with the same grammatical authority as a prophet. The content claim is remarkable: <em>kol-mamᵉlᵉḵôt hāʾāreṣ nātan-lî YHWH ʾĕlōhê haššāmāyim</em> — 'YHWH the God of heaven has given me all the kingdoms of the earth.' The title <em>ʾĕlōhê haššāmāyim</em> (God of heaven) is the standard late-Biblical and Persian-era designation for YHWH (appears in Neh 1:4-5; Dan 2:18-19; 2 Chr 36:23), reflecting the lingua franca of Persian imperial theology where the deity of a subject people is acknowledged as a cosmic power. Whether Cyrus actually used this title or the editor inserted it is debated; the Cyrus Cylinder uses 'Marduk, lord of the gods' in the same position. The commission <em>wayhûʾ pāqad ʿālay</em> ('he has charged/commissioned me') uses <em>pāqad</em> (to appoint, visit, commission) — the same verb used for YHWH's commissioning of Moses (Ex 3:16).</p>",
    "3": "<p>The invitation formula <em>mî-ḇāḵem mikkol-ʿammô</em> ('whoever among you from all his people') is deliberately inclusive — 'whoever' (<em>mî</em> = anyone) from among all YHWH's people, not limited to the Judahites. The blessing formula <em>yᵉhî ʾĕlōhāyw ʿimmô</em> ('may his God be with him') echoes the patriarchal covenant-presence formula (Gen 28:15 'I will be with you'; Deut 20:4 'YHWH your God is with you'). The command to go up (<em>yaʿal</em>) to Jerusalem uses the standard biblical verb for pilgrimage and return to the land — <em>ʿālāh</em> (to go up) is always the directional term for movement toward Jerusalem, whether from Egypt (Ex 1:10; 17:3), from the wilderness, or from Babylon. The description of Jerusalem as 'which is in Judah' (<em>ʾăšer bîhûdāh</em>) is a territorial identification for Persians unfamiliar with the specific city's location within the administrative province of Yehud.</p>",
    "4": "<p>The provision formula for those who remain (<em>kol-hannišʾār mikkol-hamᵉqōmôt ʾăšer hûʾ gār-šām</em>) — 'every survivor, wherever he sojourns' — uses <em>nišʾār</em> (the remaining/surviving ones), a term that in post-exilic context carries the weight of the prophetic remnant (<em>šᵉʾērît</em>, e.g., Isa 10:20-22; Mic 5:7). The provision list (silver, gold, goods, livestock, freewill offerings) mirrors the Exodus provisions: in Ex 12:35-36 the Israelites ask their Egyptian neighbors for silver and gold and clothing; here Persian neighbors assist the returning exiles. The parallel is deliberate: Ezra's theology of return patterns the new exodus on the Mosaic original. <em>nᵉdāḇōt</em> (freewill offerings) is the term for voluntary cultic gifts (Lev 7:16; Deut 12:6); the designation signals that the proceeds for Jerusalem will be channeled into the cult.</p>",
    "5": "<p>The response formula <em>wayyāqûmû</em> ('they rose up') describes the mobilization of the returnees. The leadership list — heads of fathers' houses of Judah and Benjamin, priests and Levites — represents the tripartite structure of the post-exilic community: tribal/lay leadership (Judah + Benjamin), priestly leadership, and Levitical support. The key phrase is <em>kōl ʾăšer hēʿîr hāʾĕlōhîm ʾet-rûḥô lāʿălôt</em> ('everyone whose spirit God had stirred up to go up'): the same <em>ʿûr</em> + <em>rûaḥ</em> construction from v1 is applied to the people — just as YHWH stirred Cyrus's spirit to make the decree, so YHWH stirs each individual returnee's spirit to respond. The divine arousal creates a coherent movement: the sovereign stirs the pagan king, and the same verb stirs the covenant people. The verb <em>lāʿălôt</em> (to go up) = pilgrimage-return vocabulary.</p>",
    "6": "<p>The neighbors' assistance — <em>kol-sᵉḇîḇōtêhem ḥizzᵉqû ḇîḏêhem</em> ('all their neighbors strengthened their hands') — uses the idiom <em>ḥizzēq yāḏ</em> (to strengthen the hand = to assist, support), which appears in Neh 2:18 for the community's response to Nehemiah's report. The list of gifts repeats the Exodus provision pattern from v4, adding <em>uḇimigdānôt</em> (precious/choice things, from <em>megādānôt</em> = precious objects, cf. Gen 24:53 for bridal gifts). The phrase <em>lᵉḇad ʿal kol-mitnaddēḇ</em> ('besides all that was voluntarily offered') emphasizes that the community gifts exceeded the official Persian provision — a double generosity, reminiscent of the wilderness tabernacle construction where the community gave so much Moses had to stop them (Ex 36:3-7).</p>",
    "7": "<p>The temple vessels (<em>kᵉlê bêt-YHWH</em>) that Nebuchadnezzar had taken from Jerusalem (2 Kgs 24:13; 2 Chr 36:7,10,18) and placed in the temple of his gods (<em>bêt ʾĕlōhāyw</em>) are now returned. The restoration of the cult vessels is a theological reversal: what conquest had transferred to the victor's temple, covenant faithfulness now restores to the original sanctuary. The irony of the term <em>bêt ʾĕlōhāyw</em> (house of his gods) — a pagan temple that temporarily held YHWH's sacred vessels — echoes Dan 1:2 (Nebuchadnezzar places the Jerusalem vessels 'in the house of his god'). The return of the vessels is a visible covenant restoration: the objects of YHWH's cult are returning to their proper home.</p>",
    "8": "<p><em>Mîṯrᵉdāt haggizzāḇār</em> — Mithredath the treasurer. The name Mithredath is Iranian, from Mithra (the Persian solar deity) + dāta (given) = 'given by Mithra'; it appears as a Persian court name in Ezra 4:7 as well. <em>Haggizzāḇār</em> is a Babylonian/Persian loanword (<em>ganzabara</em> = 'guardian of the treasury') — a technical administrative title for the imperial treasurer. The vessels are counted (<em>yispᵉrēm</em> = enumerate/count) and transferred to Sheshbazzar. <em>Šᵉšbaṣṣar nᵉśîʾ yᵉhûdāh</em> — Sheshbazzar the prince of Judah. <em>Nāśîʾ</em> is the hereditary/honorific term for tribal/dynastic prince (cf. Ezek 44-48 for the Davidic <em>nāśîʾ</em>); here it distinguishes Sheshbazzar's status as the Davidic representative from his role as Persian-appointed <em>pāḥāh</em> (governor, Ezra 5:14). Most scholars identify Sheshbazzar as Shenazzar, son of Jehoiachin (1 Chr 3:18), making him a Davidic prince and the uncle of Zerubbabel.</p>",
    "9": "<p>The vessel inventory begins with <em>ʾagarṭᵉlê</em> (basins/bowls): the Hebrew word is a loanword possibly from Persian or Babylonian — used only here in the OT. The thirty gold basins (<em>ʾagarṭᵉlê zāhāḇ šᵉlōšîm</em>) are large cultic vessels for temple service. One thousand silver basins (<em>ʾagarṭᵉlê kesep ʾelep</em>) follow. <em>Maḥălāpîm ʾešrîm-wᵉtišʿāh</em> — 29 knives/censers; <em>maḥălāpîm</em> may be a hapax (unique usage) possibly related to <em>ḥālap</em> (to pass through, change) — instruments for changing/rotating sacrificial items, or possibly for trimming wicks; the exact function is uncertain. The inventory functions both as administrative record and as theological marker: the number of vessels being returned corresponds to the original items taken, signaling complete restitution.</p>",
    "10": "<p><em>Kᵉfôrê zāhāḇ šᵉlōšîm</em> — thirty gold bowls. <em>Kāpôr</em> (bowl/basin) is a cultic vessel term that appears in the tabernacle/temple inventory (Ex 25:29; Num 7:13-86 for the dedication offerings). The 'silver bowls of a second kind' (<em>kᵉfôrê kesep mišnîm</em>) — <em>mišnîm</em> = of a second grade/type, implying the gold bowls are the superior grade and silver are second-tier. Four hundred and ten silver bowls second-grade is a large number. The thousand 'other vessels' (<em>kēlîm ʾăḥērîm ʾālep</em>) is a catch-all category at the end — the inventory has been exhaustive in the named categories but the residual thousand vessels resist exact classification. This matches standard ancient Near Eastern temple inventory practice, which would list named vessels individually and group miscellaneous items at the end.</p>",
    "11": "<p>The grand total: <em>kol-kēlîm lāzāhāḇ wᵉlakesep ḥămiššet ʾălāpîm wᵉʾarbaʿ mēʾôt</em> = 5,400 vessels of gold and silver. A mathematical problem is well-known: the specific items listed in vv9-10 sum to considerably less than 5,400 (the Septuagint and 1 Esdras have different numbers for individual items). The discrepancy may reflect lost text, rounding, or the inclusion of items not individually enumerated. The round-number summary 5,400 may function as the authoritative total in the official Persian record, with vv9-10 being selective highlights. <em>Šᵉšbaṣṣar heʿĕlāh ʾet-hakkōl bᵉhaʿălôt haggōlāh mibbāḇel lîrûšālaim</em> — Sheshbazzar brought all of it up when the exiles came up from Babylon to Jerusalem. The verb <em>heʿĕlāh</em> (brought up) echoes the earlier <em>yaʿal</em> (go up) of the pilgrimage-return vocabulary: the vessels go up to Jerusalem just as the people do — the cult objects participate in the exodus-return with the community.</p>"
  },
  "2": {
    "1": "<p><em>Wᵉʾēlleh bᵉnê hamᵉdînāh</em> — 'Now these are the people of the province' (<em>bᵉnê hamᵉdînāh</em> = 'sons/children of the province'). <em>Mᵉdînāh</em> is the Aramaic/Persian term for the administrative district of Yehud (Judah) within the satrapy of Abar-Nahara (Beyond the River). The same list appears in Neh 7:6-72 with many variant numbers, indicating the two texts use a common source (perhaps an official Persian administrative register) that was transmitted differently in each manuscript tradition. The introduction identifies the returnees as those Nebuchadnezzar had carried to Babylon (<em>šᵉlāḥam nᵉḇûḵaḏneṣṣar melek bāḇel lᵉḇāḇel wayyāšûḇû lîrûšālaim wîhûdāh</em>) — the return framed as exact reversal: same cities, same people, going back.</p>",
    "2": "<p>The eleven leaders who returned with Zerubbabel: <em>Zᵉrubbāḇel</em> (= Babylonian <em>Zēr-Bābili</em> = 'seed of Babylon' or 'offspring of Babylon') is the Davidic prince, grandson of Jehoiachin (1 Chr 3:19; cf. Matt 1:12). <em>Yēšûaʿ</em> (= 'YHWH saves' — the same name as Joshua/Jesus) is the high priest, son of Jozadak (the priest taken captive to Babylon, 1 Chr 6:15). These two — Zerubbabel (royal) and Jeshua (priestly) — are the twin leaders of the restoration, foreshadowing the priestly-royal partnership in Zechariah's visions (Zech 4:14 'two anointed ones'). Nehemiah here is not the later governor (who came much later); Seraiah, Mordecai, and others in the list appear in different forms between Ezra and Neh 7 (Neh 7:7 has 'Nahamani' instead of 'Nehemiah' in some readings). The total number of returned laypeople (<em>mispar ʾanšê ʿam yiśrāʾēl</em>) follows in the subsequent verses.</p>",
    "3": "<p><em>Bᵉnê pāròš</em> — descendants of Parosh, 2,172. Ezra 2 = 2,172; Neh 7:8 = 2,172 (agreement). <em>Pāròš</em> = 'flea' — an ironic family name (such names appear throughout the census). This is the largest single family in the lay list. The term <em>bᵉnê</em> (sons of) is the standard marker for the family-based (patrilineal) sections (vv3-20), as opposed to <em>ʾanšê</em> (men of, vv21-35) for the geography-based sections. The family-based section names ancestors by eponymous head; the totals represent households attached to that ancestral name.</p>",
    "4": "<p><em>Bᵉnê šᵉpaṭyāh</em> — descendants of Shephatiah, 372. Ezra = 372; Neh 7:9 = 372 (agreement). <em>Šᵉpaṭyāh</em> = 'YHWH has judged' — a theophoric name. The family appears in Neh 11:4 as part of the Jerusalem settlement list. The numbers in this verse and surrounding ones show that family sizes in the returnee list range from the very large (Parosh at 2,172) to the quite small (e.g., Ater at 98 in v16), reflecting the varied fortunes of Judean families in exile.</p>",
    "5": "<p><em>Bᵉnê āraḥ</em> — descendants of Arah, 775. Here a significant Ezra/Neh variant: Neh 7:10 reads 652 (not 775). The Arah discrepancy of 123 persons is one of the largest numerical differences between the parallel lists. No fully satisfactory explanation exists: suggested causes include scribal error in one tradition, intentional revision (perhaps reflecting a later updated count), or use of different counting methods (some may count heads of household while others count all family members). A descendant of Arah returns in Ezra 2:5 context as a family leader; in Neh 6:18 a daughter of Meshullam son of Berechiah is described as wife of a Tobiah, whose father-in-law is Shecaniah son of Arah — suggesting the family maintained prominence in the community.</p>",
    "6": "<p><em>Bᵉnê paḥaṯ-môʾāḇ</em> — descendants of Pahath-moab ('governor of Moab'), 2,812, through the clans of Jeshua and Joab. Neh 7:11 = 2,818 (difference of 6). Pahath-moab is an unusual family name suggesting an ancestor who held the office of governor over Moab, or who was associated with Moabite territory. This family is subdivided by clans (<em>mišpaḥôt</em>): Jeshua and Joab, indicating a large multi-clan family group. The family name reappears in Ezra 8:4 (among those who return with Ezra) and in Neh 3:11; 10:14 (in later community contexts), suggesting a prominent multi-generational family.</p>",
    "7": "<p><em>Bᵉnê ʿēlām</em> — descendants of Elam, 1,254. Neh 7:12 = 1,254 (agreement). Elam is a common personal name (cf. multiple Elamites in 1 Chr genealogies); this is the 'first Elam' (there is a 'second' or 'other Elam' in v31, also 1,254 — an unusual coincidence of identical numbers for different families). The name may reflect a Judahite ancestor associated with the region of Elam (modern SW Iran) or simply a common Semitic name.</p>",
    "8": "<p><em>Bᵉnê zaṯṯû</em> — descendants of Zattu, 945. Neh 7:13 = 845 (difference of 100). The Ezra/Neh difference here is exactly 100, which often indicates a place where a century was either accidentally added or omitted in transmission. Zattu appears in Neh 10:14 as a signatory of the covenant renewal under Nehemiah — the family head participates in the formal covenant reinstatement generations later.</p>",
    "9": "<p><em>Bᵉnê zakkay</em> — descendants of Zaccai, 760. Neh 7:14 = 760 (agreement). <em>Zakkay</em> is related to the root <em>zāḵāh</em> (to be clean, pure, acquitted) — a name meaning 'pure' or 'innocent.' The precise agreement between Ezra and Neh here, against many verses that differ, suggests this particular entry was transmitted carefully or that the number was memorable (760 is a round-ish number but not obviously round).</p>",
    "10": "<p><em>Bᵉnê bānî</em> — descendants of Bani, 642. Neh 7:15 reads 'Binnui' with 648 (both name and number differ). The Ezra/Neh variant <em>bānî</em> vs <em>binnûy</em> may reflect confusion between similar-looking names in the ancestral register. Bani is a very common name in post-exilic texts (appears in Ezra 10:29, 34, 38; Neh 3:17; 8:7; 10:13-14 etc.) — a frequent occurrence that makes distinguishing which Bani appears in which context an ongoing challenge.</p>",
    "11": "<p><em>Bᵉnê bēḇay</em> — descendants of Bebai, 623. Neh 7:16 = 628 (difference of 5). The name <em>Bēḇay</em> is likely a hypocoristic (shortened pet name) from a theophoric name; its exact etymology is unclear. The small Ezra/Neh difference of 5 may be a simple scribal transposition (3 → 8) in one transmission line.</p>",
    "12": "<p><em>Bᵉnê ʿazgaḏ</em> — descendants of Azgad, 1,222. Neh 7:17 = 2,322 (a very large difference of 1,100!). The discrepancy for Azgad is the largest in the list — over 1,000 persons different. Azgad appears in Ezra 8:12 with 110 returning with Ezra on the second return (a smaller subset), and in Neh 10:15. The extreme Ezra/Neh difference may reflect the family's actual growth between the first return (Ezra 2) and a later updated register, or a major scribal error in one tradition.</p>",
    "13": "<p><em>Bᵉnê ʾăḏônîqām</em> — descendants of Adonikam ('my lord has arisen'), 666. Neh 7:18 = 667 (difference of 1). The name Adonikam is theophoric with <em>ʾādôn</em> (lord/master). The number 666 draws later attention in Christian interpretation given Rev 13:18, but in context it is simply a census figure; the number appears without special significance in the ancient Near Eastern administrative record.</p>",
    "14": "<p><em>Bᵉnê ḇigway</em> — descendants of Bigvai, 2,056. Neh 7:19 = 2,067 (difference of 11). Bigvai is an Iranian name (cf. <em>Bagoi</em> = 'given by God/Baga') — indicating a family head who bore a Persian name, perhaps acquired during the exile. A Bigvai appears in Ezra 8:14 with 70 (plus 68) more returning with Ezra. The name appears also in the list of Zerubbabel's leading companions (v2).</p>",
    "15": "<p><em>Bᵉnê ʿāḏîn</em> — descendants of Adin ('voluptuous, delicate'), 454. Neh 7:20 = 655 (a difference of 201 — very large). The name <em>ʿāḏîn</em> derives from <em>ʿāḏan</em> (to be delicate, voluptuous). A significant Ezra/Neh discrepancy again; like Azgad, the difference suggests either a major scribal error or the use of different administrative sources. Adin appears in Ezra 8:6 (50 more returning with Ezra) and Neh 10:16.</p>",
    "16": "<p><em>Bᵉnê āṭēr lᵉḥizqiyyāh</em> — descendants of Ater through Hezekiah, 98. Neh 7:21 = 98 (agreement). The unusual phrase 'Ater through Hezekiah' (<em>lᵉḥizqiyyāh</em>) qualifies the family by its most famous member — Hezekiah, though likely not the king. The family is identified by this prominent ancestor within the Ater line. With only 98, this is one of the smallest lay families.</p>",
    "17": "<p><em>Bᵉnê ḇēṣay</em> — descendants of Bezai, 323. Neh 7:23 = 324 (difference of 1). A minor variant; the name Bezai is otherwise rare. The small difference (1 person) between Ezra and Neh for this family may reflect a later addition to the register or a single counting difference.</p>",
    "18": "<p><em>Bᵉnê yôrāh</em> — descendants of Jorah, 112. Neh 7:24 reads 'Hariph' with 112 (name differs, number agrees). The Ezra/Neh name variant (Jorah vs Hariph) with identical numbers is unusual — the same number assigned to two different names suggests either the ancestral name changed between traditions or one was a sobriquet of the other. <em>Yôrāh</em> = 'early rain' or possibly from <em>yārāh</em> (to throw/shoot); <em>ḥārîp</em> = 'autumn/sharp' — semantically unrelated names.</p>",
    "19": "<p><em>Bᵉnê ḥāšum</em> — descendants of Hashum, 223. Neh 7:22 = 328 (difference of 105). Another significant Ezra/Neh discrepancy. Hashum appears in Neh 8:4 (standing with Ezra at the Torah reading), 10:18. The family is active in community leadership across Ezra-Nehemiah contexts.</p>",
    "20": "<p><em>Bᵉnê gibbār</em> — descendants of Gibbar, 95. Neh 7:25 reads 'Gibeon' with 95 (name differs; number agrees). The Ezra <em>gibbār</em> ('mighty man') vs Neh 7 <em>giḇʿôn</em> ('Gibeon') with identical numbers strongly suggests a textual confusion between the personal name Gibbar and the place name Gibeon — they look similar in the Hebrew script. The Neh 7 tradition likely preserves the geographic reading (placing this entry in the transition toward the place-based section of v21+), while Ezra preserves a personal-name reading.</p>",
    "21": "<p><em>Bᵉnê bêt-leḥem</em> — men of Bethlehem, 123. With this verse the list transitions from <em>bᵉnê</em> (descendants = family-based) to <em>ʾanšê</em> (men of = place-based). Both Bethlehem and Netophah (v22) are villages near each other in the Judean highlands south of Jerusalem. Bethlehem as David's city carries dynastic significance; its returnees include those associated with the Davidic heartland. Neh 7:26 groups Bethlehem and Netophah together for a combined total of 188, whereas Ezra separates them (123 + 56 = 179 — a difference of 9).</p>",
    "22": "<p><em>Anšê nᵉṭōpāh</em> — men of Netophah, 56. Netophah appears in Jer 40:8 as the hometown of military captains who joined Gedaliah after the fall of Jerusalem. The Netophathites are mentioned in 2 Sam 23:28-29 as the hometown of two of David's mighty men — a village with Davidic military associations. Its returnees number only 56, a small village contingent.</p>",
    "23": "<p><em>Anšê ʿănātôt</em> — men of Anathoth, 128. Anathoth is the Levitical city in Benjamin where Jeremiah was from (Jer 1:1) — the prophet whose 70-year oracle (cited in Ezra 1:1) shaped the theology of the whole return. The returnees from Anathoth thus come from the very city associated with the prophet whose word the return fulfills. Neh 7:27 = 128 (agreement).</p>",
    "24": "<p><em>Bᵉnê azmāwet</em> — men/descendants of Azmaveth, 42. Neh 7:28 reads 'Beth-azmaveth' with 42 (number agrees; Neh adds 'Beth-' prefix indicating the village). Azmaveth is a village north of Jerusalem; the 'Beth-' in Neh clarifies it is the settlement rather than a personal name. The small number (42) indicates a tiny hamlet's returnees.</p>",
    "25": "<p><em>Bᵉnê qiryat-ʿārîm kᵉpîrāh ûḇᵉʾērôt</em> — men of Kiriath-arim, Chephirah, and Beeroth, 743. These are three Benjaminite cities grouped together (they appear as a Gibeonite-allied cluster in Josh 9:17). Kiriath-arim/Kiriath-jearim is where the ark of the covenant rested before David brought it to Jerusalem (1 Sam 7:1-2; 2 Sam 6:3). Grouping three towns for a single total is unusual in the list and may reflect that they shared a common administrative register or were treated as a single administrative unit. Neh 7:29 = 743 (agreement).</p>",
    "26": "<p><em>Bᵉnê hārāmāh wāgeḇaʿ</em> — men of Ramah and Geba, 621. Neh 7:30 = 621 (agreement). Ramah and Geba are Benjaminite border towns north of Jerusalem (cf. Isa 10:29 for the Assyrian advance through these settlements). Grouped as a pair, the two towns are treated as a single administrative unit with 621 returnees.</p>",
    "27": "<p><em>Anšê miḵmās</em> — men of Michmas, 122. Neh 7:31 = 122 (agreement). Michmas (Michmash) is the site of Jonathan's famous single-handed exploit against the Philistines (1 Sam 13-14). Its inclusion in the returnee list confirms the restoration of settlement across the Benjaminite highlands that the Babylonian deportation had depopulated. The number 122 reflects a moderate-sized settlement.</p>",
    "28": "<p><em>Anšê bêt-ʾēl wᵉhāʿay</em> — men of Bethel and Ai, 223. Neh 7:32 = 123 (a difference of 100 — exactly one century, suggesting scribal addition/omission). Bethel is the site of Jacob's vision (Gen 28) and later one of Jeroboam's golden-calf shrines (1 Kgs 12:29). Its inclusion without comment in the returnee list is notable — the city with northern kingdom idolatrous associations is resettled by returning Judahites. Ai (et-Tell) is the site of Joshua's conquest (Josh 7-8) — another conquest-era landmark being repopulated.</p>",
    "29": "<p><em>Bᵉnê nᵉḇô</em> — descendants of Nebo, 52. Neh 7:33 = 52 (agreement). Nebo is a Moabite/Transjordanian place name (Num 32:3; the mountain from which Moses viewed Canaan); here it designates a Judean village west of the Jordan, possibly a secondary settlement named after the original Transjordanian site. The small number (52) indicates a minor community.</p>",
    "30": "<p><em>Bᵉnê magbîš</em> — descendants of Magbish, 156. This entry has no parallel in Neh 7, which is one of several significant differences between the two lists. Magbish is otherwise unattested as a place or person name in the OT, making this a hapax toponym. Its absence from Neh 7 raises the question of whether Neh 7's list is later or earlier — if the community of Magbish had dissolved or been absorbed by Nehemiah's time, it might not appear in the later register.</p>",
    "31": "<p><em>Bᵉnê ʿēlām ʾaḥēr</em> — descendants of the other Elam, 1,254. The exact same number (1,254) as the 'first' Elam in v7 is remarkable — mathematical coincidence seems unlikely, and the repetition may reflect a scribal duplication, a textual problem, or the merging of two branches of the same family using the same total. Neh 7:34 = 1,254 (agreement). The qualifier <em>ʾaḥēr</em> (other/another) explicitly distinguishes this from v7's Elam.</p>",
    "32": "<p><em>Bᵉnê ḥārîm</em> — descendants of Harim, 320. Neh 7:35 = 320 (agreement). Harim (<em>ḥārîm</em> = 'snub-nosed' or 'devoted') is a priestly name in the list of 24 priestly divisions (1 Chr 24:8, the third division); this may be a lay family named after a priestly ancestor, or a separate lay family with the same name. A priestly Harim family appears in v39.</p>",
    "33": "<p><em>Bᵉnê lōḏ ḥāḏîḏ wᵉʾônô</em> — men of Lod, Hadid, and Ono, 725. Neh 7:37 = 721 (difference of 4). These three towns are in the Shephelah/coastal plain northwest of Jerusalem, near what is now the Tel Aviv area. Lod (Lydda) appears in Acts 9:32-38 as the site of Peter's healing ministry. The grouping of three towns with a combined total is the same pattern as Kiriath-arim/Chephirah/Beeroth (v25) — administrative clustering of associated settlements.</p>",
    "34": "<p><em>Bᵉnê yᵉrîḥô</em> — men of Jericho, 345. Neh 7:36 = 345 (agreement). Jericho, the 'City of Palms,' is the first city conquered in Joshua's campaign (Josh 6) — its repopulation in the returnee list signals the restoration of the Jordan Valley settlement. The Judean presence at Jericho would have been in the oasis zone east of Jerusalem; its returnees are part of the broader reoccupation of the historical Israelite territory.</p>",
    "35": "<p><em>Bᵉnê sᵉnāʾāh</em> — descendants of Senaah, 3,630. Neh 7:38 = 3,930 (difference of 300). With 3,630 returnees, Senaah is by far the largest group in the lay list — larger than even Parosh (2,172). The name Senaah is otherwise unknown as a person or place name; some scholars suggest it may be a variant of Magdalsenna or simply an unidentified village. The very large number suggests either a major settlement or a group designation that includes people from multiple origins.</p>",
    "36": "<p><em>Hakkōhănîm bᵉnê yᵉdaʿyāh lᵉḇêt yēšûaʿ</em> — the priests: the descendants of Jedaiah of the house of Jeshua, 973. With v36 the list transitions to the cultic personnel (priests, vv36-39; Levites, v40; singers, v41; gatekeepers, v42). Jedaiah is a priestly family name (appears in the 24 priestly divisions, 1 Chr 24:7); the qualifier 'of the house of Jeshua' connects them to the high-priestly family of Jeshua son of Jozadak (the high priest of the restoration). This is the most prominent priestly family — associated with the high priest himself. Neh 7:39 = 973 (agreement).</p>",
    "37": "<p><em>Bᵉnê ʾimmēr</em> — descendants of Immer, 1,052. Neh 7:40 = 1,052 (agreement). Immer is the priestly division that appears in 1 Chr 24:14 (the sixteenth division); the family is associated with the temple priesthood. In Jer 20:1 the chief officer (<em>pāqîḏ nāgîḏ</em>) of the temple is Pashhur son of Immer — suggesting the family held administrative authority in the pre-exilic temple. The 1,052 returning Immer priests constitute the second-largest priestly family in the list.</p>",
    "38": "<p><em>Bᵉnê pašḥûr</em> — descendants of Pashhur, 1,247. Neh 7:41 = 1,247 (agreement). Pashhur is the largest priestly family in the returnee list (1,247). The name Pashhur is associated with multiple temple officials in pre-exilic texts (Jer 20:1; 21:1; 38:1). The family appears in Ezra 10:22 as among those who had married foreign women — maintaining its prominence into the later post-exilic period.</p>",
    "39": "<p><em>Bᵉnê ḥārîm</em> — descendants of Harim, 1,017. Neh 7:42 = 1,017 (agreement). A priestly Harim distinct from the lay Harim of v32. Harim appears in the priestly rotation divisions (1 Chr 24:8). Four priestly families return in total (vv36-39): Jedaiah/Jeshua (973), Immer (1,052), Pashhur (1,247), and Harim (1,017) — a total of approximately 4,289 returning priests. The Levites (v40) by contrast number only 74 — a disproportionately small Levitical contingent that creates a clergy-imbalance in the early restoration community.</p>",
    "40": "<p><em>HalᵉwiyyiM bᵉnê yēšûaʿ wᵉqadmîʾēl lᵉḇᵉnê hôḏawyāh šiḇʿîm wᵉʾarbaʿāh</em> — the Levites: descendants of Jeshua and Kadmiel through Hodaviah, 74. Neh 7:43 = 74 (agreement). The striking fact is the disproportion: 4,289 priests but only 74 Levites returned. The Levitical shortage in the early restoration explains why Ezra 8:15-20 records Ezra's deliberate effort to recruit Levites for the second return (he found none and had to persuade specific individuals). The causes of Levitical reluctance to return are not stated; scholars suggest the Levites had lower status and fewer economic incentives in Babylon, or that Levitical families were more integrated into Babylonian life. The three Levitical families (Jeshua, Kadmiel, Hodaviah) may be sub-clans of the broader Levitical tribe.</p>",
    "41": "<p><em>Hamᵉšōrᵉrîm bᵉnê ʾāsāp mēʾāh ûšmōnāh wᵉʿešrîm</em> — the singers: descendants of Asaph, 128. Neh 7:44 = 148 (difference of 20). The singers (<em>mᵉšōrᵉrîm</em>) are listed separately from the Levites — in Chronicles they are a sub-group of Levites, but Ezra treats them as a distinct category. Asaph was David's chief musician (1 Chr 16:5; 2 Chr 5:12) and the head of one of the three Levitical singing guilds (Asaph, Heman, Jeduthun/Ethan). The 128 (or 148) returnees represent the Asaphite singing guild — the only one of the three guilds to return with the first wave, reflecting Asaph's prominence in the cult music tradition preserved through the exile.</p>",
    "42": "<p><em>Bᵉnê haššōʿărîm</em> — the gatekeepers: six families (Shallum, Ater, Talmon, Akkub, Hatita, Shobai), 139 total. Neh 7:45 = 138 (difference of 1). Gatekeepers (<em>šōʿărîm</em>) formed a distinct Levitical sub-group responsible for security and access control at the temple gates. The six families listed here correspond to gatekeeping clans documented in 1 Chr 26:1-19. In the post-exilic period the gatekeepers remained a distinct guilded group; Nehemiah 11:19 notes 172 gatekeepers in Jerusalem, showing their growth from the 139 who returned. The role of gatekeeper (<em>šōʿēr</em>) is etymologically related to the gate (<em>šaʿar</em>) — threshold guardians of the sanctuary.</p>",
    "43": "<p><em>Hannᵉtînîm</em> — the Nethinim (temple servants) begin here. <em>Nᵉtînîm</em> derives from <em>nātan</em> (to give) in the passive/Niphal sense = 'given/dedicated ones' — persons given or dedicated to temple service. The tradition in Num 31:40-47 traces temple-servant origins to the Midianite women and children given to the Levites after the Midian war; Ezra 8:20 says David and his officials had designated them for the Levites. Many Nethinim names in vv43-54 are foreign (non-Hebrew), suggesting their origins as captive/foreign servants integrated into the temple service over generations: Ziha (Egyptian?), Hasupha, Tabbaoth ('seal-ring' rings = Semitic).</p>",
    "44": "<p><em>Bᵉnê qērōs sîʿāh wᵉpāḏôn</em> — Keros, Siaha, and Padon. <em>Qērōs</em> may be related to a root meaning 'bent/curved'; <em>Sîʿāh</em> is possibly related to 'mud/slime'; <em>Pāḏôn</em> = 'redemption' (Hebrew root <em>pdh</em>) — a name suggesting a servant who was redeemed from slavery into temple service. The variety of etymological backgrounds in the Nethinim names reflects the diverse origins of this group over the centuries they served the temple.</p>",
    "45": "<p><em>Bᵉnê lᵉḇānāh ḥăgāḇāh wᵉʾakkûḇ</em> — Lebanah, Hagabah, and Akkub. <em>Lᵉḇānāh</em> = 'white/moon' (possibly connected to Lebanon); <em>Ḥăgāḇāh</em> = 'locust' (related to <em>ḥāgāḇ</em>, the locust species); <em>Akkûḇ</em> = possibly from Akkadian personal name. These are clearly names from diverse linguistic backgrounds, confirming the Nethinim's mixed heritage.</p>",
    "46": "<p><em>Bᵉnê ḥăgāḇ šalmay wᵉḥānān</em> — Hagab, Shalmai, and Hanan. <em>Ḥăgāḇ</em> = 'locust' (same root as Hagabah v45); <em>Šalmay</em> may be Aramaic or Persian; <em>Ḥānān</em> = 'gracious' (Hebrew) — showing that Hebrew theophoric names also appear among the Nethinim, those whose families had been integrated into the Israelite community over generations.</p>",
    "47": "<p><em>Bᵉnê giddēl gaḥar wᵉrᵉʾāyāh</em> — Giddel, Gahar, and Reaiah. <em>Giddēl</em> = 'greatly magnified' (Hebrew root <em>gāḏal</em>); <em>Gaḥar</em> may be foreign; <em>Rᵉʾāyāh</em> = 'YHWH has seen' (theophoric). The mix of names — Hebrew theophoric, Hebrew descriptive, and possibly foreign — in a single Nethinim group verse illustrates the ongoing process of naming-integration as families served in the temple community across generations.</p>",
    "48": "<p><em>Bᵉnê rᵉṣîn nᵉqôḏāʾ wᵉgazzām</em> — Rezin, Nekoda, and Gazzam. <em>Rᵉṣîn</em> is the name of the king of Damascus in the Syro-Ephraimite War (Isa 7:1) — whether this family took its name from an Aramean ancestor or the name is coincidental is unknown. <em>Nᵉqôḏāʾ</em> = 'spotted/distinctive' (related to <em>nāqōd</em> = speckled); <em>Gazzām</em> = 'locust, caterpillar' (one of several insect names in the Nethinim list — see Hagab v46, Hagabah v45).</p>",
    "49": "<p><em>Bᵉnê ʿuzzāʾ pāsēaḥ ûḇēsay</em> — Uzza, Paseah, and Besai. <em>ʿUzzāʾ</em> = 'strength' (same name as the man who died touching the ark, 2 Sam 6:7); <em>Pāsēaḥ</em> = 'limping' (possibly from a lame ancestor; cf. Mephibosheth's lameness); <em>Bēsay</em> = uncertain etymology. Paseah appears in Neh 3:6 as a repairman of the Old Gate — showing a Nethinim descendant taking an active role in the later community.</p>",
    "50": "<p><em>Bᵉnê ʾasnāh mᵉʿûnîm nᵉpîsîm</em> — Asnah, Meunim, and Nephisim. <em>Mᵉʿûnîm</em> is the name of the Meunites, a group from the Ma'an region near Petra (cf. 2 Chr 26:7) — a Nethinim family of south Arabian origin. <em>Nᵉpîsîm</em> may relate to Naphish, son of Ishmael (Gen 25:15; 1 Chr 1:31; cf. 1 Chr 5:19 where the Reubenites war against Hagrites including Nephish). These names point to the absorption of various conquered or subject peoples into the temple service system over the pre-exilic period.</p>",
    "51": "<p><em>Bᵉnê baqbûq ḥăqûpāʾ wᵉḥarḥûr</em> — Bakbuk, Hakupha, and Harhur. <em>Baqbûq</em> = 'bottle/flask' (onomatopoeic for the gurgling sound of an emptying bottle, cf. <em>baqbuq</em> in modern Hebrew); <em>Ḥăqûpāʾ</em> and <em>Ḥarḥûr</em> are names of uncertain etymology, possibly foreign. The sound-symbolism of some Nethinim names (like Bakbuk) may indicate they were descriptive nicknames given to foreign servants rather than formal genealogical names.</p>",
    "52": "<p><em>Bᵉnê baṣlût mᵉhîḏāʾ wᵉḥaršāʾ</em> — Bazluth, Mehida, and Harsha. <em>Bāṣlût</em> may be related to a root meaning 'in the shadow of'; <em>Mᵉhîḏāʾ</em> may be Aramaic; <em>Ḥaršāʾ</em> = 'artificer/craftsman' (from <em>ḥāraš</em>) — a surname indicating a family of craftsmen who entered temple service. The craftsman families (cf. Solomon's servants in vv55-57) represent skilled workers who served the temple in non-priestly roles.</p>",
    "53": "<p><em>Bᵉnê ḇarqôs sîsᵉrāʾ wᵉṯāmaḥ</em> — Barkos, Sisera, and Thamah. <em>Bārqôs</em> may relate to 'son of Kos' (Edomite deity) suggesting Edomite ancestry; <em>Sîsᵉrāʾ</em> is the name of the Canaanite general defeated by Deborah and Jael (Judg 4-5) — whether this family traced Canaanite ancestry to Sisera's clan or the name was coincidental is unknown. The inclusion of names associated with Israel's traditional enemies (Canaanites, Edomites) among the temple servants confirms the broad integration of conquered peoples into the cult service.</p>",
    "54": "<p><em>Bᵉnê nᵉṣîaḥ wᵉḥāṭîpāʾ</em> — Neziah and Hatipha. <em>Nᵉṣîaḥ</em> = 'preeminent/conspicuous' (Hebrew); <em>Ḥāṭîpāʾ</em> = possibly 'seized/taken' (from <em>ḥāṭap</em> = to snatch away), which could describe the origin of this family as captives taken in war and dedicated to temple service. This verse ends the Nethinim list proper (vv43-54 = 12 Nethinim groups).</p>",
    "55": "<p><em>Bᵉnê ʿaḇḏê šᵉlōmōh</em> — the descendants of Solomon's servants: a second category of temple servants, distinct from the Nethinim. Solomon's servants (<em>ʿaḇḏê šᵉlōmōh</em>) appear in 1 Kgs 9:20-21 — the remnant Canaanite peoples Solomon conscripted for forced labor (<em>mas-ʿōleh</em>), who were not enslaved but levied for permanent state service. Over generations these 'Solomon's servants' became a hereditary class associated with the temple. Sotai, Sophereth, and Peruda begin the list; <em>Sôṭay</em> may derive from Aramaic; <em>Sōpereṯ</em> = 'scribe-woman' (feminine participle of <em>sāpar</em> = to write/count) — perhaps the female ancestor of a scribal family who served Solomon.</p>",
    "56": "<p><em>Bᵉnê yaʿălāh darqôn wᵉgiddēl</em> — Jaalah, Darkon, and Giddel. <em>Yaʿălāh</em> = 'ibex/mountain goat' (same root as <em>yaʿēl</em>, the hero Jael's name); <em>Darqôn</em> = possibly from <em>dereq</em> or foreign; <em>Giddēl</em> = 'greatly magnified' (appears also in the Nethinim list, v47 — the same name in both Nethinim and Solomon's servants suggests name repetition in these lists, not family identity).</p>",
    "57": "<p><em>Bᵉnê šᵉpaṭyāh ḥaṭṭîl pōḵereṯ haṣṣᵉḇāyîm wᵉʾāmî</em> — Shephatiah, Hattil, Pochereth-hazzebaim, and Ami. <em>Pōḵereṯ-haṣṣᵉḇāyîm</em> = 'binder of the gazelles' — an evocative compound name suggesting an ancestor who hunted or managed gazelles for the royal court. The long compound name is unusual in the list and may preserve an occupational title that became hereditary. <em>Ami</em> (Neh 7:59 reads 'Amon') is a short form that could be a throne name or abbreviated theophoric.</p>",
    "58": "<p><em>Kol-hannᵉtînîm ûḇᵉnê ʿaḇḏê šᵉlōmōh šᵉlōš mēʾôt tišʿîm ûšnāyim</em> — all the Nethinim and Solomon's servants: 392 total. Neh 7:60 = 392 (agreement). The combined total (392) represents the full sub-temple-servant community. In Ezra 8:20, 220 Nethinim return with Ezra on the second return, showing the community's continued presence and modest growth. The combined Nethinim/Solomon's servants (392) plus the cultic staff (priests ~4,289; Levites 74; singers 128-148; gatekeepers 139) total roughly 4,000-4,600 cultic personnel returning with the first wave — a substantial religious infrastructure for the restored community.</p>",
    "59": "<p>The category of those who could not prove their ancestry (<em>wᵉʾēlleh hāʿōlîm mittᵉl-melaḥ tᵉl-ḥaršāʾ kᵉrûḇ ʾaddān wᵉʾimmēr</em>) — five Babylonian sites where uncertain-ancestry returnees originated. Tel-melah ('mound of salt'), Tel-harsha ('mound of the craftsman'), Cherub, Addan, and Immer are Babylonian locations; their names suggest geographic/topographic sites in the Babylonian exile territory where Judean communities had settled. <em>Lōʾ yāḵᵉlû lᵉhaggîḏ bêt-ʾăḇôtêhem wᵉzarʿām</em> = 'they could not declare/prove their ancestral house and their seed (descent).' The inability to prove ancestry is a crucial legal problem in the restoration community, where genealogy determined land-rights, priestly service eligibility, and covenant-community membership.</p>",
    "60": "<p><em>Bᵉnê dᵉlāyāh bᵉnê ṭôḇiyyāh bᵉnê nᵉqôḏāʾ</em> — Delaiah, Tobiah, and Nekoda, 652. Neh 7:62 = 642 (difference of 10). The name Tobiah ('YHWH is good') is the name of Nehemiah's primary antagonist (Neh 2:10, 19; 4:3, etc.) — a prominent post-exilic family. The Tobiah connection suggests the family of uncertain ancestry who returned may be ancestors of the later prominent Tobiad dynasty. These 652 returnees can participate in the community but their status is uncertain until genealogical verification is possible.</p>",
    "61": "<p>The priestly families of uncertain ancestry — Habaiah, Hakkoz, and Barzillai — present a more serious problem. <em>Habballyāh</em> (Habaiah), <em>haqqôṣ</em> (Hakkoz), and the descendants of Barzillai who 'took a wife from the daughters of Barzillai the Gileadite.' Barzillai the Gileadite was a supporter of David during Absalom's revolt (2 Sam 17:27-29; 19:31-39); his priestly descendant had taken a Gileadite wife and adopted the father-in-law's name, blurring the genealogical record. The Hakkoz family appears in 1 Chr 24:10 as the seventh priestly division — their descendants are deregistered for the restoration period but later rehabilitated: Neh 3:4 and 3:21 show Meremoth son of Uriah son of Hakkoz actively participating in wall-repair, suggesting the question was eventually resolved.</p>",
    "62": "<p><em>Wayᵉḇaqqᵉšû kᵉtāḇām hammityaḥᵉśîm wᵉlōʾ nimṣāʾû waygōʾălû min-hakkᵉhunnāh</em> — 'they sought their names in the genealogical register (<em>kᵉtāḇ hammityaḥᵉśîm</em>) but could not find them, and they were excluded (<em>waygōʾălû</em>) from the priesthood as unclean (<em>ṭāmēʾ</em>).' The term <em>kᵉtāḇ hammityaḥᵉśîm</em> (the genealogical register = the book of those who registered themselves by genealogy) is the official priestly census document. <em>Gāʾal</em> (to exclude as impure/unfit) is used here in the cultic sense of declaring someone ritually unclean for sacred service — not permanent excommunication but suspension pending resolution. The same root <em>gāʾal</em> in the land-redemption law (Lev 25) means the kinsman-redeemer; here its secondary sense of 'to treat as unclean/defile' is in play.</p>",
    "63": "<p><em>Haṯṯîrᵉšāṯāʾ</em> — the governor. <em>Tiršātāʾ</em> is a Persian loanword (from Old Persian <em>tarsāta</em> = 'the feared one/revered one') used as a title for the Persian-appointed governor. In Ezra it designates Sheshbazzar or Zerubbabel; in Neh 8:9 and 10:1 it designates Nehemiah. The use of a Persian administrative title for the community's leader reflects the post-exilic political reality: the governor operates within Persian imperial authority. The ruling that the excluded priestly families 'must not eat of the most sacred offerings until a priest stands with the Urim and Thummim' (<em>ʿōmēd kōhēn lᵉʾûrîm wᵉlᵉtummîm</em>) invokes the ancient oracular instrument for determining YHWH's judgment in disputed cases (Ex 28:30; Lev 8:8; Num 27:21). The Urim and Thummim had apparently ceased to function in the pre-exilic period (they are absent from later Second Temple descriptions); this ruling thus deferred the resolution to a future messianic priest — effectively suspending these families' priestly status indefinitely.</p>",
    "64": "<p><em>Kol-haqqāhāl kᵉʾeḥāḏ ʾarbaʿāh wᵉʾarbaʿîm ʾelep šᵉlōš mēʾôt wᵉšiššîm</em> — the whole assembly together, 42,360. This is the grand total: 42,360 for the whole assembly (<em>haqqāhāl kᵉʾeḥāḏ</em>). The problem is famous: if you add up all the individual family totals in Ezra 2 they sum to approximately 29,818; Neh 7 sums to approximately 31,089. Neither sum reaches 42,360. The same discrepancy appears in both books. Proposed explanations: (1) the individual totals are selective and do not cover all groups; (2) the grand total was transmitted from a different source that counted additional groups; (3) rounding errors accumulated. The grand total 42,360 is probably the authoritative official Persian census figure, with the detailed list being an incomplete extract from it.</p>",
    "65": "<p>The servants (<em>ʿăḇādîm wᵉšiprōtêhem</em>): 7,337 male and female servants, plus 200 male and female singers (<em>mᵉšōrᵉrîm ûmᵉšōrᵉrôt</em>). Neh 7:67 = 245 singers (difference of 45 from Ezra's 200). These are secular singers (entertainment musicians for the households), distinct from the cultic singers (descendants of Asaph, v41). The presence of 7,337 servants in addition to 42,360 free returnees indicates the returnees included a substantial enslaved/servant population — likely those brought into service during the exile or purchased as laborers for the return journey and resettlement.</p>",
    "66": "<p>Horses: 736. Neh 7:68 = 736 (agreement). Horses were expensive animals in the ancient Near East, primarily used for military and prestige transport — not for agricultural work (which used donkeys). The presence of 736 horses among the returnees indicates significant wealth and military capacity within the returnee community. Persian period administrative texts confirm horses as status markers in the province of Yehud.</p>",
    "67": "<p>Mules: 245; camels: 435; donkeys: 6,720. Neh 7:69 = mules 245; camels 435; donkeys 6,720 (agreement across all three). The large number of donkeys (6,720) reflects the primary beast of burden for transport across the Palestinian landscape. Camels (435) were used for long-distance desert/caravan transport — relevant for the journey from Babylon. The detailed livestock count functions as a wealth inventory and as logistics data for the Persian administration: this many animals implies significant fodder requirements and organizational capacity for the march from Babylon to Jerusalem.</p>",
    "68": "<p><em>Ûmirāʾšê hāʾāḇôt bᵉḇôʾām ʾel-bêt YHWH ʾăšer bîrûšālaim hittᵉnadᵉḇû lᵉḇêt hāʾĕlōhîm</em> — when the heads of the fathers' houses arrived at the house of YHWH in Jerusalem, they gave freewill offerings (<em>hittᵉnadᵉḇû</em>) toward rebuilding the house of God. The verb <em>nāḏaḇ</em> Hithpael = to volunteer oneself, to give spontaneously — the same root as <em>nᵉdāḇôt</em> (freewill offerings) in v5. The first act of the leaders upon arrival at the temple site is voluntary giving for reconstruction — before housing themselves, before administrative organization, before any civic activity. The priority of the cult over personal establishment is a theological statement.</p>",
    "69": "<p>The giving totals: 61,000 darics of gold (<em>darkᵉmônîm zāhāḇ šiššîm wᵉʾeḥāḏ ʾelep</em>), 5,000 minas of silver (<em>kaspā ḥamēšet ʾălāpîm</em>), and 100 priestly garments (<em>mᵉʾāh kuttōnôt kōhănîm</em>). <em>Darkᵉmônîm</em> is the Hebrew form of 'daric' — the Persian gold coin introduced by Darius I (522-486 BCE), appearing here and in 1 Chr 29:7 (anachronistically for David's era) and Neh 7:70-72. If the darics are genuinely from the Cyrus era (538 BCE), this represents the earliest attestation of the term; some scholars see the use of darics as evidence that Ezra was written or edited after Darius I's coinage. 61,000 darics is a very large amount (roughly 500-600 kg of gold). The inclusion of 100 priestly garments (<em>kuttōnôt</em>) alongside monetary gifts reflects the comprehensive provision for the cult: not just construction funds but the vestments required for priestly service once the temple is rebuilt.</p>",
    "70": "<p><em>Wayyēšᵉḇû hakkōhănîm wᵉhalᵉwiyyim ûmin-hāʿām wᵉhammᵉšōrᵉrîm wᵉhaššōʿărîm wᵉhannᵉtînîm bᵉʿārêhem wᵉḵol-yiśrāʾēl bᵉʿārêhem</em> — the priests, Levites, some of the people, the singers, the gatekeepers, and the temple servants settled in their towns, and all Israel in their towns. The settlement formula closes the census list: each social category is assigned to 'their towns' (<em>bᵉʿārêhem</em>) — the ancestral territorial holdings to which each family is entitled. The final phrase <em>wᵉḵol-yiśrāʾēl bᵉʿārêhem</em> (and all Israel in their towns) uses the comprehensive 'all Israel' formula, asserting that the returnee community constitutes the authentic continuation of the covenant people — not a remnant but 'all Israel' repatriated. The settlement narrative frames the census as completed: the return has landed, the people are distributed, and the community is positioned for the cult's restoration.</p>"
  },
  "3": {
    "1": "<p><em>Wayyiggaʿ haḥōdeš hašᵉḇîʿî</em> — 'when the seventh month came.' The seventh month (<em>tišrî</em>) is the most sacred month in the Israelite liturgical calendar: it contains the Feast of Trumpets (Num 29:1), the Day of Atonement (Lev 23:26-32), and the Feast of Tabernacles (Lev 23:33-43). The fact that the returning community's first cultic act — rebuilding the altar — occurs precisely in the seventh month is not coincidental. The Solomonic temple dedication also occurred in the seventh month (1 Kgs 8:2; 2 Chr 5:3). <em>Kᵉʾîš ʾeḥāḏ ʾel-yᵉrûšālaim</em> — 'together as one man to Jerusalem.' The phrase <em>kᵉʾîš ʾeḥāḏ</em> (as one man) is the covenant assembly formula for unified communal action (cf. Judg 20:1; Neh 8:1); the singular collective noun evokes the standing before God as one body. The assembly in the seventh month types the great covenant assembly before YHWH — the community reconstituted as a unified cultic entity before a single stone of the temple has been laid.</p>",
    "2": "<p><em>Wayyāqom yēšûaʿ ben-yôṣāḏāq wᵉʾeḥāyw hakkōhănîm ûzᵉrubbāḇel ben-šᵉʾaltîʾēl ûʾeḥāyw</em> — Jeshua son of Jozadak and his fellow priests, with Zerubbabel son of Shealtiel and his kinsmen. The dual leadership (priest + Davidic prince) is explicit from the first cultic act. Jeshua's patronymic traces to Jozadak (1 Chr 6:15), the last pre-exilic high priest taken captive — Jeshua's lineage provides Aaronic priestly legitimacy. Zerubbabel's patronymic: son of Shealtiel, who is son of Jehoiachin (Matt 1:12; Luke 3:27) — the Davidic royal line. The altar is built <em>kaḵātûḇ bᵉtôrat mōšeh ʾîš-hāʾĕlōhîm</em> — 'as written in the law of Moses the man of God.' The authority citation is the Mosaic Torah; the altar's construction follows the Pentateuchal specifications, particularly the prohibition on dressed stone (Ex 20:25; Deut 27:5-6) and the specifications for the burnt-offering altar (Ex 27:1-8).</p>",
    "3": "<p><em>Wayyākînû hammizBēaḥ ʿal-mᵉḵônōtāyw</em> — 'they set the altar on its base/stand.' <em>Mᵉḵônāh</em> (base, platform, stand) is the technical term for the altar's foundation platform (cf. 1 Kgs 7:27-29 for the bronze <em>mᵉḵônôt</em> in the Solomonic temple). The altar is set up <em>bᵉʾîmāh ʿălêhem mēʿammê hāʾărāṣôt</em> — 'in fear because of the peoples of the surrounding lands.' The phrase <em>bᵉʾîmāh</em> (in fear/dread) is not the normal word for fear (<em>yirʾāh</em>) but <em>ʾêmāh</em> (dread, terror) — a more acute and pressing fear. The community begins cultic activity under existential threat: the surrounding peoples are hostile (Samaritans, Ammonites, etc.), yet the altar is established before the temple foundation is laid, prioritizing the cult above security. Morning and evening burnt offerings (<em>ʿōlôt baboqer ûḇāʿereḇ</em>) follow the Mosaic <em>tāmîd</em> schedule (Ex 29:38-42; Num 28:3-8).</p>",
    "4": "<p><em>Wayyaʿăśû ʾet-ḥag hasSukkôt kaḵāṯûḇ</em> — 'they observed the Feast of Tabernacles as written.' <em>Sukkôt</em> (Feast of Booths/Tabernacles) is the harvest festival in the seventh month (Lev 23:33-43; Deut 16:13-15), the feast of the completed agricultural year and the community's memorial of wilderness dwelling. The feast of 'as written' (<em>kaḵāṯûḇ</em>) emphasis insists that the post-exilic Sukkot observance follows the Pentateuchal prescription exactly. The <em>mispar</em> (required number) of burnt offerings for each day follows Num 29:12-38, which specifies a decreasing sequence: 13 bulls on day 1, declining by one bull each day to 7 on day 7, with a final eighth day. The Feast of Tabernacles is also the feast at which the Solomonic temple was dedicated (1 Kgs 8:2), making its celebration the appropriate liturgical context for the altar's rededication.</p>",
    "5": "<p><em>Wᵉʾaḥărê kēn ʿōlat tāmîd</em> — 'and after that, the regular burnt offering.' Having completed the Sukkot sequence, the community establishes the regular (<em>tāmîd</em>) daily offering as the ongoing liturgical baseline. The <em>ʿōlat tāmîd</em> is the twice-daily burnt offering prescribed in Num 28:3-8 — the continuous (hence <em>tāmîd</em> = perpetual) offering that defines the cult's existence as uninterrupted service to YHWH. The community also restores offerings for <em>ḥoḏāšîm</em> (new moons) and all <em>môʿăḏê YHWH</em> (appointed feasts of YHWH) — the full liturgical calendar of Lev 23 and Num 28-29 is re-established in sequence. <em>Lᵉkol-mitnaddēḇ nᵉdāḇāh laYHWH</em> — freewill offerings are accepted from all volunteers, restoring the voluntary-gift mechanism alongside the prescribed requirements.</p>",
    "6": "<p><em>Miyyôm ʾeḥāḏ laḥōdeš haššᵉḇîʿî hēḥēllû lᵉhaʿălôt ʿōlôt laYHWH</em> — 'from the first day of the seventh month they began to offer burnt offerings to YHWH.' The first of Tishri is Rosh Hashanah (the Feast of Trumpets, Num 29:1) — the New Year's Day of the sacred calendar. Beginning the offering sequence on 1 Tishri anchors the restoration in the covenantal time structure. The parenthetical note <em>ûyᵉsôḏ hêḵal-YHWH lōʾ yussaḏ</em> — 'though the foundation of the temple of YHWH had not yet been laid' — is emphatic: the altar precedes the building. Cult precedes construction; the community worships before they have a sanctuary, just as Israel worshipped at the tabernacle before the temple existed.</p>",
    "7": "<p><em>Wayyittᵉnû kesep laḥōṣᵉḇîm ûlᵉḥārāšîm</em> — 'they gave silver to the stonecutters and carpenters.' The procurement of building materials mirrors the Solomonic temple construction: cedar logs from Lebanon via Sidon and Tyre, transported by sea to Joppa (1 Kgs 5:6, 9; 2 Chr 2:16). The authorization <em>kᵉrišyôn kôreš melek-pāras ʿălêhem</em> — 'according to the grant (authorization) that Cyrus king of Persia had given them' — invokes the imperial mandate as the legal basis for the construction. <em>Rišyôn</em> is an Aramaic loanword (from <em>rᵉšw</em> = permission/authorization) — a Persian administrative term appearing in Ezra 3:7; its use here reflects the integration of Persian imperial vocabulary into the post-exilic community's legal framework. The provision of food, drink, and oil to the Sidonian and Tyrian workers mirrors Solomon's arrangement with Hiram (1 Kgs 5:11).</p>",
    "8": "<p><em>Ûbišnat haššᵉnît lᵉbôʾām ʾel-bêt hāʾĕlōhîm lîrûšālaim</em> — 'in the second year after their arrival at the house of God in Jerusalem, in the second month.' The second year, second month is the precise time-stamp for the foundation-laying. The combination 'second year, second month' recalls that Solomon also began construction 'in the second month' (2 Chr 3:2) — the post-Passover month of Iyyar when the rains have ended and outdoor construction can begin. Zerubbabel and Jeshua lead the work with 'all the rest of their fellow Israelites' (<em>šᵉʾār ʾaḥêhem</em>). The age threshold for Levitical service: <em>lᵉḇen ʿeśrîm šānāh wāmāʿᵉlāh</em> — 'from twenty years old and upward.' Numbers 4 sets the Mosaic age for Levitical service at 30; David revised it to 20 (1 Chr 23:24-27) for the settled temple context. The post-exilic community follows David's revision — a Davidic rather than Mosaic standard for Levitical age eligibility.</p>",
    "9": "<p><em>Wayyaʿămoḏ yēšûaʿ bānāyw wᵉʾeḥāyw qadmîʾēl ûḇānāyw bᵉnê-yᵉhûdāh yaḥad lᵉnaṣṣēaḥ ʿal-ʿōśê hamᵉlāʾḵāh</em> — Jeshua, his sons and brothers, Kadmiel and his sons (Judahite Levites), and the sons of Henadad with their sons and brothers 'stood together to direct (<em>lᵉnaṣṣēaḥ</em>) the workmen on the house of God.' The verb <em>naṣṣēaḥ</em> (Piel of <em>nāṣaḥ</em>) = to oversee, to be the choirmaster or supervisor — the same term used for the Levitical choir directors in the Psalm superscriptions (<em>lammᵉnaṣṣēaḥ</em>). The building supervisors are designated by the same term used for worship leaders: the construction of the temple is itself a form of worship requiring the same dedicated oversight as the temple music.</p>",
    "10": "<p><em>Wayyassᵉḏû habbōnîm ʾet-hêḵal YHWH</em> — 'when the builders laid the foundation of the temple of YHWH.' The foundation-laying ceremony is a formal liturgical event. The priests take their stations in their vestments (<em>biḵlê hamᵉʿîl</em>) with trumpets (<em>baḥăṣōṣᵉrôt</em>); the Levites, specifically the sons of Asaph, take their stations with cymbals (<em>bimṣiltāyim</em>). The arrangement follows 'the directions of David king of Israel' (<em>ʿal yᵉḏê dāwîḏ melek yiśrāʾēl</em>) — the Davidic liturgical order. The trumpets are the Aaronic priestly instruments (Num 10:1-10); the cymbals are associated with the Levitical singing guilds (1 Chr 15:19). The combination of priestly trumpet and Levitical cymbal for the foundation ceremony follows the pattern of the Solomonic dedication (2 Chr 5:12-13).</p>",
    "11": "<p><em>Wayyaʿănû bᵉhallēl ûḇᵉhôḏōt laYHWH kî ṭôḇ kî lᵉʿôlām ḥasdô ʿal-yiśrāʾēl</em> — 'they sang antiphonally, praising and giving thanks to YHWH, for he is good, for his steadfast love toward Israel endures forever.' The antiphonal praise formula <em>kî ṭôḇ kî lᵉʿôlām ḥasdô</em> is the standard temple praise refrain (Ps 100:5; 106:1; 107:1; 118:1-4, 29; 136:1-26; 2 Chr 5:13; 7:3). The formula's repetition in this precise context is the Chronicler's signature liturgical anchor: this is the refrain sung at the Solomonic dedication (2 Chr 5:13) and again at Hezekiah's Passover (2 Chr 30:21) — now sung again at the second temple's foundation. The continuous refrain spanning three major cultic events expresses the theological claim that YHWH's <em>ḥesed</em> is the continuity linking the original covenant to its post-exilic renewal. <em>Wayyārîʿû kol-hāʿām tᵉrûʿāh gᵉḏôlāh</em> — all the people shouted with a great shout (<em>tᵉrûʿāh</em>): the covenant shout of celebration (cf. Num 23:21; 1 Sam 4:5; the Feast of Trumpets in Num 29:1 is the day of <em>tᵉrûʿāh</em>).</p>",
    "13": "<p><em>Wᵉʾên hāʿām maḵkîrîm qôl tᵉrûʿat haśśimḥāh lᵉqôl bᵉḵî hāʿām</em> — 'no one could distinguish the sound of the joyful shouting from the sound of the people's weeping, for the people raised such a great shout that the sound was heard far away.' The impossibility of distinguishing joy from grief is the final note of the chapter — a theologically resonant ambiguity. The sound that carries 'far away' (<em>mirrāḥôq</em>) is the mingled cry of restored hope and irretrievable loss. The weeping for the first temple represents authentic grief over what the exile destroyed; the joy over the new foundation represents authentic hope in YHWH's faithfulness. The Chronicler does not resolve the tension — the eschatological community holds both responses simultaneously, as the prophets anticipated: 'those who sow in tears shall reap with shouts of joy' (Ps 126:5); Zechariah will later rebuke those who treat the new temple as less worthy (Zech 4:10 — 'who has despised the day of small things?').</p>"
  }
}

def main():
    c = load_comm('mkt-original', 'ezra')
    merge_comm(c, ORIG)
    save_comm('mkt-original', 'ezra', c)
    count = sum(len(v) for v in ORIG.values())
    print(f'ezra mkt-original ch1-3: wrote {count} verses')

if __name__ == '__main__':
    main()
