"""
MKT Original Commentary — Exodus chapters 4–6
Run: python3 scripts/zc-original-exodus-4-6-fill.py

Source data used:
- data/interlinear/exodus.json
- data/translation/draft/mediating/exodus.json (MKT text)

Key decisions in this range:
- Exod 4:24-26 (the lodging-place attack): traditional reading — Moses had not circumcised
  his son; Zipporah acts as covenant agent; the blood of circumcision averts the death threat.
  'Chatan demim' (bridegroom of blood): noted that Aramaic 'chatan' means circumcised.
- Exod 6:2-3 ('by my name YHWH I was not known to them'): the 'yada' experiential reading —
  the patriarchs knew the name but had not experienced the full redemptive reality it encodes.
- The seven 'I will' declarations of 6:6-8: ga'al (redeem) is the kinsman-redeemer verb —
  YHWH acting as go'el for enslaved kin.
- 'Uncircumcised lips' (6:12, 30): technical metaphor for speech impediment or ritual
  unworthiness of speech, not a literal physical condition.
- The Levite genealogy (6:14-25): character-credentialing insert before the plagues; the
  Amram-Jochebed marriage (aunt) noted as pre-Sinaitic, before Lev 18:12 prohibition.
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

EXODUS = {
  "4": {
    "1": '<p>Moses\'s first objection (<em>hen lo ya\'aminu li</em>, "but they will not believe me") focuses on credibility, not capability. <em>Aman</em> (H539, believe/trust) — the same root as <em>amen</em>; his concern is that the nation will not extend covenantal trust to his claim of divine appointment. This is a practical objection, not theological rebellion: he has seen the bush but the elders have not; how does testimony without proof carry weight in a community that has been crushed into skepticism?</p>',
    "2": '<p><strong>What is in your hand?</strong> — YHWH\'s response begins not with an argument but with an inventory of what is already present. The <em>matteh</em> (H4294, staff/rod) is the shepherd\'s basic tool — for guiding, defending, testing terrain. YHWH consistently works with what the servant already has rather than providing entirely new instruments. The question redirects attention from the impossible ("they won\'t believe me") to the available ("what do you already hold?").</p>',
    "3": '<p><strong>Throw it on the ground</strong> — the staff becomes a <em>nachash</em> (H5175, serpent). The same word as the serpent of Eden (Gen 3:1); the wilderness is full of serpents (Num 21:6); the Egyptian deity Wadjet was depicted as a uraeus (cobra). In context, the sign has anti-Egyptian symbolic resonance: the serpent that threatens Israel (Egypt) can be grasped and controlled by the one who serves YHWH. Moses "ran from it" — appropriate fear, even from the instrument of his own wonder-working.</p>',
    "4": '<p><strong>Grab it by the tail</strong> — contrary to safe snake-handling, which requires grasping just behind the head. The command requires trust: Moses must grasp the snake where it can still bite him, relying on YHWH\'s protection rather than his own technique. The serpent becomes a staff again (<em>matteh</em>, H4294) "in his palm" — the instrument of power is restored by obedience to the dangerous command.</p>',
    "5": '<p>The purpose statement for the signs: "so that they may believe that YHWH the God of their fathers — the God of Abraham, Isaac, and Jacob — appeared to you." The signs are epistemological tools, not mere spectacle; they function to create the <em>emunah</em> (covenantal trust) that Moses feared would be absent. The covenantal name "God of Abraham, the God of Isaac, the God of Jacob" (cf. Exod 3:6) anchors the commission in the patriarchal covenant.</p>',
    "6": '<p><strong>Put your hand in your cloak</strong> — the second sign: the hand emerges leprous (<em>tsara\'at</em>, H6879). Leprosy in the OT was associated with divine judgment (Num 12:10, Miriam; 2 Kgs 5, Naaman; 2 Chr 26:19-20, Uzziah), but also with divine power to afflict and restore. The cloak (<em>cheq</em>, H2436, bosom/chest fold) is where valuables were kept — Moses puts his hand into the place of security and it emerges defiled; then back again and it is restored "like the rest of his flesh." The sign enacts the reversal of judgment.</p>',
    "7": '<p>The restoration of the leprous hand — "like the rest of his flesh" (<em>ke-besaro</em>) — demonstrates both the afflicting and healing power of the same God. The sign is not primarily about Egypt but about YHWH\'s absolute sovereignty over bodily integrity, which will later be demonstrated in the plagues (afflicting Egypt) and the wilderness healing (restoring Israel).</p>',
    "8": '<p>Three signs in escalating weight: the first (staff/serpent) may be dismissed as magic; the second (leprous hand) is harder to replicate; the third (Nile water→blood) touches the sacred heart of Egyptian religion (the Nile as Hapy, the inundation deity). The conditional structure — "if not the first, then the second; if not both, then the third" — grants Israel a graduated level of evidence before requiring faith, consistent with YHWH\'s pattern of meeting people where they are.</p>',
    "9": '<p><strong>Water from the Nile becomes blood on dry ground</strong> — a miniature preview of the first plague (Exod 7:20). <em>Ye\'or</em> (H2975, the Nile) is the Egyptian loanword for the great river, used throughout Exodus specifically for the Nile rather than the generic Hebrew <em>nahar</em> (river). The sign deliberately targets Egypt\'s most sacred resource.</p>',
    "10": '<p>The fourth objection — "I have never been eloquent (<em>lo ish devarim anokhi</em>)" — is the most specific: Moses is literally "not a man of words/speech." <em>Devarim</em> (H1697) is the plural of <em>davar</em> (word/matter), the same term used for "the ten commandments" (Deut 10:4, "ten words"). The qualification "neither in the past nor since you have spoken to me" acknowledges that even this divine encounter has not changed his speech capacity — he is describing an ongoing condition, not a temporary case of nerves.</p>',
    "11": '<p><strong>Who gave human beings their mouths?</strong> — YHWH\'s response is a series of rhetorical questions asserting his creative sovereignty over all speech capacities: "who makes them deaf (<em>cheresh</em>, H2795) or mute (<em>illem</em>, H483)? who gives sight or makes blind (<em>iver</em>, H5787)?" The answer is implicit: "Is it not I, YHWH?" The argument: the Creator of speech has more capacity to enable speech than the speaker has to claim incapacity. This is not a dismissal of Moses\'s limitation but a reframing of where the power lies.</p>',
    "12": '<p>"I will be with your mouth (<em>im-pikha</em>, literally with your mouth) and will teach you what to say." The divine commitment is specific: not to remove Moses\'s limitation but to accompany it and work through it. <em>Yara</em> (H3384, teach/instruct) — the same root as Torah; YHWH will continuously instruct Moses in real time what to say. This is not a prepared script but ongoing divine direction.</p>',
    "13": '<p><strong>Please send someone else</strong> — the fifth and final objection, most direct: <em>shelach na be-yad tishlach</em>, "send by the hand of [whoever] you will send." Moses does not name a substitute but gestures at anyone other than himself. This provokes YHWH\'s anger (<em>vayichar af YHWH</em>, H2734 + H639) — the only time in this extended commissioning that YHWH expresses anger. The objections have moved from legitimate concerns to outright reluctance.</p>',
    "14": '<p><strong>Aaron the Levite</strong> — the tribal identification "the Levite" is unusual when speaking of one\'s own brother; it may signal Aaron\'s priestly role before the Sinai legislation or distinguish him from other Aarons. "He can speak well" (<em>daber yedaber</em>, H1696 doubled — an infinitive absolute construction meaning "he can surely/fluently speak"); the intensive form emphasizes genuine eloquence. "He is already on his way to meet you" — Aaron\'s movement toward Moses is already in progress, a sign that YHWH prepared the solution before Moses raised the final objection.</p>',
    "15": '<p>YHWH promises to instruct both Moses and Aaron simultaneously: "I will help you both speak and will teach you what to do." The partnership of two speakers — one receiving the revelation, one articulating it — will become the model for the prophet-priest collaboration throughout Israel\'s history. Moses as the prophet who receives and transmits; Aaron as the priest who speaks to the assembly.</p>',
    "16": '<p><strong>"He will be as your mouth, and you will be as God to him"</strong> — <em>ve-hayah hu yih\'yeh-lekha le-feh ve-atah tih\'yeh-lo le-Elohim</em>. "As God to him" (<em>le-Elohim</em>, H430) is a remarkable designation: Moses functions as the divine representative to Aaron, who functions as his mouth to the people. The structure is: YHWH → Moses (revelation) → Aaron (articulation) → people (reception). This is the first explicit description of prophetic mediation as a chain of communication.</p>',
    "17": '<p>"The staff of God" (<em>matteh ha-Elohim</em>) — the shepherd\'s staff has been transformed by the commission: ordinary wood is now the instrument of divine signs. The naming of the staff as "God\'s staff" is the first of several renamings throughout Exodus that mark how ordinary objects are consecrated by covenant use.</p>',
    "18": '<p>Moses returns to Jethro and asks permission to leave — a notable act of covenantal courtesy toward his father-in-law. He does not reveal the full content of his divine commission but uses the more generic "to see whether my relatives are still alive." <em>Yeter</em> (Jethro\'s alternative name, H3503) appears here; the name <em>Yitro</em> (H3499) is used elsewhere — two forms of the same name, perhaps indicating two traditions merged in the final text.</p>',
    "19": '<p>YHWH\'s reassurance: "all those who wanted to kill you are dead" — referring to the Egyptians who sought Moses after the killing of the overseer (Exod 2:15). This addresses an unspoken fear Moses had not articulated in his five objections: the personal danger of returning. The phrase "all who sought your life are dead" reappears almost verbatim in 1 Kgs 19:10, 14 (Elijah\'s complaint) and Matt 2:20 (Joseph\'s dream about returning from Egypt), marking it as a standard form of divine reassurance.</p>',
    "20": '<p>Moses takes his wife Zipporah and sons (<em>banav</em>, H1121, his sons — more than one, though only one son is named previously) and begins the return journey. "The staff of God (<em>matteh ha-Elohim</em>) in his hand" — the phrase closes the bracket opened in v.17; Moses departs equipped as the divine agent.</p>',
    "21": '<p><strong>"I will harden Pharaoh\'s heart"</strong> — <em>ani achazzeq et-lev Par\'oh</em> (H2388, to harden/strengthen + H3820, heart). This is the first mention of the heart-hardening theme. Three different verbs are used throughout the plague narratives: <em>chazaq</em> (to strengthen/make stubborn, here), <em>kabed</em> (to make heavy, as a burden), and <em>qashah</em> (to make hard/severe). In the first five plagues Pharaoh hardens his own heart; in the last five YHWH hardens it. The theological tension (human responsibility vs. divine sovereignty) is part of the text\'s design, not its inconsistency.</p>',
    "22": '<p><strong>"Israel is my firstborn son"</strong> — <em>beni vekori Yisrael</em> (H1121 + H1060, my son my firstborn). The covenant sonship of Israel is here declared officially for the first time to Pharaoh. In the ancient world, the firstborn son holds the highest status in the family — rights, inheritance, authority. YHWH\'s designation of a nation of slaves as his firstborn son is the antithesis of their social status; covenantal reality inverts empirical standing.</p>',
    "23": '<p>The covenant logic of the tenth plague is stated before the plagues begin: "Let my son go... you refused... so I will kill your firstborn." The structure is covenantal: Pharaoh\'s refusal to release YHWH\'s firstborn will be repaid through the loss of Egypt\'s firstborn. This is not arbitrary retaliation but covenantal reciprocity — what is done to YHWH\'s son will be done to the oppressor\'s son.</p>',
    "24": '<p><strong>The lodging-place attack</strong> — "the LORD met him and sought to kill him" (<em>vayevaqesh hamito</em>). One of the most syntactically compressed and theologically mysterious passages in the Pentateuch. The subject of "kill him" is ambiguous — it could refer to Moses, though the traditional reading (and what makes Zipporah\'s response intelligible) assumes it is Moses. The divine agent is understood as the "angel of YHWH" (cf. Gen 32:24-30, Jacob\'s night wrestling). The crisis appears to be circumcision: Moses had not circumcised his son born in Midian, thereby leaving the covenant mark incomplete.</p>',
    "25": '<p><strong>Zipporah took a flint knife and cut off her son\'s foreskin</strong> — she acts as the covenant agent when Moses cannot. <em>Tzur</em> (H6697, flint) — stone knives were used for circumcision even when metal was available (Josh 5:2-3), preserving the archaic ritual. She "touched his feet (<em>raglayv</em>, H7272)" — in Hebrew, "feet" can be a euphemism for genitals (e.g., Ruth 3:7). The blood of circumcision (substituting for Moses\'s blood) averts the death threat. <strong>Bridegroom of blood</strong> (<em>chatan damim</em>, H2860 + H1818) — the Aramaic cognate of <em>chatan</em> (bridegroom) means "circumcised one"; the phrase may encode the covenant link between circumcision and marriage-covenant identity.</p>',
    "26": '<p>"The LORD let him alone" — the crisis passes with the circumcision completed. The parenthetical note "(she said \'bridegroom of blood\' in reference to circumcision)" is the narrator\'s gloss explaining the cryptic phrase. The passage is preserved in its irreducible difficulty — an encounter with divine judgment that is averted not by explanation but by covenant action (blood).</p>',
    "27": '<p>YHWH instructs Aaron to go into the wilderness to meet Moses; Aaron meets him "at the mountain of God" — Horeb, where the bush appeared. The reunion is divinely staged: the two brothers meet at the very site of Moses\'s commissioning, so that Aaron enters the commission-context before beginning his ministry. <em>Vayishaq lo</em> (he kissed him) — the covenant greeting, as between Jacob and Esau (Gen 33:4) and the father and the prodigal son (Luke 15:20).</p>',
    "28": '<p>Moses "told Aaron everything YHWH had commanded him to say and all the signs he had commanded." The transfer of the commission from Moses to Aaron is total and exact — Aaron is fully briefed, including the miracle-signs. The chain of communication (YHWH → Moses → Aaron, as described in 4:16) now operates for the first time.</p>',
    "29": '<p>Moses and Aaron assemble all the elders of Israel — a formal national gathering. The elders (<em>zeqenim</em>, H2205) are the representative heads of Israel\'s clan-based governance structure; convening them is equivalent to convening Israel\'s leadership in total.</p>',
    "30": '<p>Aaron speaks all the words and performs all the signs — precisely as the communication chain of vv.15-16 prescribed. The text is careful to have Aaron do both the speaking and the demonstrating; Moses is in the background, the unseen source. This division of labor will characterize their relationship throughout the Exodus narrative.</p>',
    "31": '<p><strong>They believed, and bowed their heads in worship</strong> — <em>vaya\'aminu</em> (H539, they believed/trusted) and <em>vayishtachavu</em> (H7812, they bowed down/worshipped). The community\'s response combines cognitive trust (<em>aman</em>) and physical reverence (prostration). The trigger for the worship: "YHWH was concerned about them (<em>paqad</em>, H6485 — visited/attended to) and had seen their misery (<em>ra\'ah et-aniyam</em>)." The knowledge that they had been seen and cared for — not forgotten — produces worship.</p>'
  },
  "5": {
    "1": '<p><strong>"Let my people go, so that they may hold a festival to me in the desert"</strong> — the first covenant demand to Pharaoh. <em>Chag</em> (H2282, festival/feast) — the pilgrimage feast requiring travel to the site of worship. The three annual pilgrimage feasts (Passover, Weeks, Tabernacles) are all <em>chagim</em>; the demand is for the freedom of worship, not yet permanent liberation. The narrative begins with a religious-freedom request before the total-exodus demand escalates through the plagues.</p>',
    "2": '<p><strong>"Who is YHWH (<em>mi YHWH</em>) that I should obey his voice?"</strong> — Pharaoh\'s response is the governing question of the entire book of Exodus. <em>Mi YHWH</em> (H4310 + H3068): the question challenges both the identity and the authority of Israel\'s God. "I do not know YHWH (<em>lo yada\'ti et-YHWH</em>)" — the verb <em>yada\'</em> (H3045) has the full covenantal sense of acknowledge/submit as well as merely know; Pharaoh refuses both intellectual acknowledgment and covenantal submission. The plagues will answer <em>mi YHWH</em> systematically.</p>',
    "3": '<p>"The God of the Hebrews" — <em>Elohei ha-ivrim</em> (H430 + H5680). <em>Ivri</em> (Hebrew) may connect to <em>ever</em> (crossing over), traditionally explaining "those who crossed the river" (Euphrates/Jordan), or to the Hapiru/Apiru, a social class of landless laborers documented in Egyptian records (the Amarna letters, 14th century BCE). The three-day journey request — <em>derekh shloshet yamim</em> — frames the worship as a practical, limited request, not yet a full departure from Egypt.</p>',
    "4": '<p>Pharaoh\'s accusation: "you are making them idle (<em>vatishbetu</em>, H7673 — rest/cease); root of <em>shabbat</em>)" — the irony is profound: the Israelites\' desire to observe a religious festival is labeled Sabbath-keeping (laziness) by the tyrant. The vocabulary of Sabbath-rest is used as an accusation against the enslaved people who have no rest.</p>',
    "5": '<p>"Numerous" (<em>rabbim</em>, H7227) — the same word used in Exod 1:7, 9, 12 for the population growth that originally triggered Pharaoh\'s oppression. His fear of their numbers has not diminished; now he uses their numbers as an excuse to intensify rather than relax control.</p>',
    "6": '<p>Pharaoh issues the new decree on "that same day" — immediate administrative response, not delayed reaction. The swiftness of the retaliatory decree shows that Pharaoh interpreted Moses\'s request as a labor disruption, not a religious claim, and responded within his administrative framework (production quotas and slave oversight).</p>',
    "7": '<p><strong>"No straw for bricks"</strong> — archaeological evidence from New Kingdom Egypt confirms that chopped straw was mixed into Nile mud for brick-making; the straw helped bind the clay and prevented cracking. The Papyrus Anastasi IV (13th century BCE) mentions administrators failing to meet brick quotas — an administrative structure consistent with Exodus\'s portrayal. Removing the straw while maintaining the quota is an economically precise cruelty: the physical material of production is removed while the productivity demand is unchanged.</p>',
    "8": '<p>"The same number of bricks as before — don\'t reduce the quota. They are lazy (<em>nirpim</em>, H7503 — to slacken/relax hands)" — <em>rafah</em> (slack hands) is precisely the opposite of <em>chazaq</em> (strong hands), the covenantal posture of readiness. Pharaoh\'s accusation of laziness redefines the workers\' desire for worship as a character defect, not a legitimate religious claim.</p>',
    "9": '<p>"Let the work be heavier (<em>tikhbad ha-avodah</em>, H3513 + H5656)" — the verb <em>kabad</em> (to be heavy/honored) is the same root as <em>kavod</em> (glory). The work that should glorify YHWH (the Israelites building YHWH\'s dwelling rather than Pharaoh\'s cities) is instead made a crushing burden. The "lies" (<em>divrei-shaqer</em>) that the workers should not attend to are Moses\'s words of liberation — what YHWH calls truth, Pharaoh calls falsehood.</p>',
    "10": '<p>Pharaoh\'s slave drivers (<em>nogesim</em>, H5065) and overseers (<em>shotrim</em>, H7860) relay the decree. <em>Nagash</em> (to urge/press/exact) is the term for the oppressive taskmaster; <em>shotrim</em> are the Israelite record-keepers and overseers who occupy the middle tier between Egyptian masters and Hebrew workers.</p>',
    "11": '<p>"Go and get straw yourself, wherever you can find it" — the demand is practical humiliation: the workers must spend time and energy foraging for the raw material of their own oppression. The word <em>kash</em> (H7179, stubble/chaff) — not the full straw, just the remnants left after harvest — indicates that even the available material is inferior.</p>',
    "12": '<p>The people "scattered throughout the land" (<em>vayafeitz ha-am... leqashot qash</em>) — <em>parats</em> (H6327, scatter/disperse) echoes the threat of scattering as a covenant curse (Deut 28:64; Lev 26:33). The enforced dispersal for stubble-gathering mirrors the curse of exile in miniature.</p>',
    "13": '<p>The slave drivers "kept pressing them" (<em>ha-nogesim atsim</em>, H213, pressing/urging) — the continuous aspect of the participle emphasizes relentless pressure. "Complete your daily quota (<em>davar yom be-yomo</em>, the matter of a day in its day)" — the day-by-day demand allows no accumulation, no preparation, no rest. The phrase <em>davar yom be-yomo</em> recurs in the manna narrative (Exod 16:4) as YHWH\'s instruction for gathering — the same daily-sufficiency framework, but given as grace rather than coercion.</p>',
    "14": '<p>The Israelite overseers (<em>shotrim</em>) are beaten (<em>yukku</em>, from H5221 <em>nakah</em>) — the violence falls on the intermediate tier, the Israelite officials who occupy the impossible position between Egyptian power and Hebrew need. "Why did you not complete your quota (<em>choq</em>, H2706, your allotment/statute)" — the same word used for YHWH\'s covenant statutes; Pharaoh\'s quota-demand uses covenantal vocabulary for oppressive ends.</p>',
    "15": '<p>The Israelite overseers appeal directly to Pharaoh — a desperate move that bypasses the administrative hierarchy. The appeal to the throne was a standard mechanism for redress in ancient Near Eastern bureaucratic systems (documented in Egyptian petitions), but here it produces not relief but accusation.</p>',
    "16": '<p>"No straw is given to us, yet they say \'make bricks\'" — the overseers articulate the logical impossibility of the demand. "The fault lies with your own people (<em>chatat ammekha</em>)" — attempting to redirect responsibility to the Egyptian supervisors. The phrase <em>chatat</em> (H2403, sin/fault) is the covenant word for transgression, used here in a secular complaint, indicating how deeply covenantal language shapes even non-religious speech.</p>',
    "17": '<p><strong>"Lazy (<em>nirpim</em>), that is what you are — lazy!"</strong> — Pharaoh doubles down; his interpretation of the situation is the mirror-opposite of Moses\'s. Where Moses says "YHWH has spoken," Pharaoh says "you are idle." The fundamental conflict of the Exodus is interpretive: who defines what is happening — YHWH or Pharaoh? The plagues will settle the hermeneutical dispute by making YHWH\'s interpretation the only viable one.</p>',
    "18": '<p>"Your full quota of bricks" — <em>matkonet levenah</em> (H4971 + H3843, the exact measure of bricks) — precision vocabulary for brick-manufacturing output; the standardization of production quotas in the ancient Near East is well-attested in administrative papyri. Pharaoh\'s system operates by measurement, record-keeping, and enforcement; YHWH\'s coming response will overwhelm all these systems.</p>',
    "19": '<p>The overseers "realized they were in serious trouble" (<em>be-ra vayu otam</em>) — literally "they saw that they were in evil/trouble." This moment of recognition, when the intermediate authorities see that their position is untenable, prepares for their accusation against Moses in v.21.</p>',
    "20": '<p>The overseers find Moses and Aaron "stationed/waiting (<em>nitzavim</em>, H5324)" to meet them — Moses and Aaron are described with the same root used for YHWH\'s messengers "standing" in divine attendance (Gen 18:2; Dan 10:11). Even the posture of meeting carries theological resonance.</p>',
    "21": '<p><strong>"May YHWH look on you and judge you"</strong> — the overseers\' accusation against Moses and Aaron is framed as a covenant-lawsuit prayer: appealing to YHWH as judge (<em>shaphat</em>, H8199) against his own messengers. The irony is complete: the oppressed pray against their liberators. "You have made us a stench (<em>hav\'ashtem et-reichenu</em>) in the eyes of Pharaoh" — <em>ba\'ash</em> (H887, to stink/be abhorrent) uses the strongest social-disgrace language: to stink in the nostrils of power is to be marked for destruction.</p>',
    "22": '<p><strong>Moses returned to YHWH</strong> and asks "Why? Is this why you sent me?" — the double <em>lamah</em> (H4100, why) is the structure of the biblical lament; cf. Ps 22:1 (the opening of the passion psalm). Moses\'s complaint has the same form as the Psalms of individual and communal lament: direct address, accusation, appeal for explanation. The complaint is not faithlessness but intimate engagement — Moses takes his confusion to YHWH rather than away from him.</p>',
    "23": '<p>"Ever since I went to Pharaoh to speak in your name, he has brought trouble on this people, and you have not rescued them at all." The Hebrew <em>vehatsil lo hitzalta</em> (H5337, and rescued not you-have-rescued) — the double negative with infinitive absolute: "you have absolutely not rescued them." Moses\'s distress is proportional to the gap between the commission ("I will deliver them") and the current reality (conditions have worsened). YHWH\'s answer will come in ch. 6.</p>'
  },
  "6": {
    "1": '<p><strong>"Now you will see"</strong> — YHWH\'s response to Moses\'s lament begins with a promise of witness: Moses will observe what YHWH will do. "By a strong hand (<em>beyad chazaqah</em>) he will let them go; by a strong hand he will drive them out" — the double use of <em>yad chazaqah</em> (strong hand) frames the Exodus as an act of divine force that overwhelms even Pharaoh\'s coercive power. The phrase becomes the theological shorthand for the Exodus throughout the OT (Deut 6:21; 26:8).</p>',
    "2": '<p><strong>"I am YHWH"</strong> — the covenant self-identification formula that anchors everything that follows. The declaration <em>ani YHWH</em> appears seven times in the seven "I will" passage of vv.2-8, functioning as the name-signature at both the opening and closing of the covenant formula. Every "I will" statement is grounded in the unshakeable identity of the speaker.</p>',
    "3": '<p><strong>"I appeared to Abraham, to Isaac, and to Jacob as El Shaddai, but by my name YHWH I was not known (<em>noda\'ti</em>) to them"</strong> — the key interpretive problem: the patriarchs used the name YHWH (Gen 12:8; 15:7), so in what sense was it "not known" to them? The key is the verb <em>yada\'</em> (H3045): in Hebrew, to "know" involves not merely familiarity but experiential relationship — to know by encounter. The patriarchs heard the name; the Exodus generation will know its meaning through the redemptive events about to unfold. <em>El Shaddai</em> (H410 + H7706) — "God Almighty" (LXX/Vg: <em>Pantokrator</em>/<em>Omnipotens</em>); the etymology is disputed: <em>shad</em> (breast, a nurturing epithet?), <em>shaddai</em> from Akkadian <em>shadu</em> (mountain), or from <em>shadad</em> (to overwhelm). The patriarchal name encoded provision and power; the exodus name will encode redemption and covenant fidelity.</p>',
    "4": '<p>The covenant with the patriarchs is recalled: "I established my covenant (<em>qumoti et-beriti</em>, H6965 + H1285 — I caused my covenant to stand)" — the hiphil of <em>qum</em> emphasizes YHWH\'s active agency in maintaining the covenant. The land of Canaan as "the land of their sojournings (<em>eretz megureihem</em>)" — the patriarchs were <em>gerim</em> (sojourners) in the land that was promised but not yet possessed.</p>',
    "5": '<p>"I have also heard the groaning (<em>ne\'aqat</em>, H5009) of the Israelites" — the same root as the "sighing and groaning" of Exod 2:24. <em>Na\'aq</em> is a cry of oppression, closer to a groan than a prayer; it is not yet liturgical intercession but the raw sound of suffering. "I have remembered (<em>zakar</em>, H2142) my covenant" — divine memory is not cognitive retrieval but covenantal activation; to "remember" a covenant is to act upon it.</p>',
    "6": '<p>The seven "I will" declarations begin: (1) "I will bring you out (<em>hotzeti</em>, H3318)" — the Exodus verb <em>yatza</em> (to go out) in its causative form; (2) "I will free you from being slaves (<em>hitzalti</em>, H5337)" — <em>natsal</em> (to snatch/rescue); (3) <strong>"I will redeem you (<em>ga\'alti</em>, H1350) with an outstretched arm" — <em>ga\'al</em> is the kinsman-redeemer verb, the obligation of the nearest male relative to buy back enslaved kin (Lev 25:47-49; Ruth 3:13). YHWH applies to himself the legal role of the <em>go\'el</em> — he has kinship obligations to Israel and will fulfill them even at cost. This is one of the most legally precise theological statements in the OT.</strong></p>',
    "7": '<p>(4) "I will take you as my own people (<em>laqachti etkem li le\'am</em>)" — the covenant-adoption formula; (5) "I will be your God (<em>vehayiti lakhem le-Elohim</em>)" — the bilateral covenant formula (cf. "you will be my people and I will be your God," Jer 30:22; Ezek 36:28). Then the epistemological purpose: "you will know (<em>yeda\'tem</em>) that I am YHWH your God who brought you out from under the yokes of Egypt." The <em>yada\'</em> that was denied to the patriarchs will now be granted to the Exodus generation through the redemptive events themselves.</p>',
    "8": '<p>(6) "I will bring you to the land" and (7) "I will give it to you as a possession (<em>morashah</em>, H4181, inheritance/possession)." <em>Morashah</em> appears only here and in Deut 33:4 ("the Torah is Moses\'s inheritance for the congregation of Jacob") in the Pentateuch; it is the legal term for heritable property. "I am YHWH" — the formula closes the seven-fold declaration, bracketing it with the divine name as its unshakeable foundation.</p>',
    "9": '<p>"They did not listen to Moses because of their discouragement (<em>qotser ruach</em>, H7114 + H7307 — shortness/exhaustion of spirit) and harsh labor (<em>avodah qashah</em>)." <em>Qotser ruach</em> is literally "shortness of breath" — the oppressed person who cannot breathe freely. The trauma of slavery impairs reception of hope: even the most liberating message cannot be received by a spirit that has been systematically crushed. This verse is a pastoral-theological observation: suffering can temporarily block the capacity for faith, without that block being a moral failure.</p>',
    "10": '<p>YHWH\'s instruction to Moses and the simple narrative marker "the LORD spoke to Moses, saying" — a formulaic introduction used repeatedly throughout Exodus and Leviticus. Its repetition creates the rhythm of continuous divine speech that structures the Pentateuch.</p>',
    "11": '<p>The commission is restated: "Go, tell Pharaoh king of Egypt to let the Israelites go out of his country." The simplicity of the command contrasts with the elaborate commissioning of chs. 3-4; after Moses\'s lament and YHWH\'s response, the mission is re-launched in its most elemental form.</p>',
    "12": '<p>Moses raises the objection again: "if the Israelites will not listen to me, why would Pharaoh listen to me, since I speak with <strong>uncircumcised lips (<em>aral sefatayim</em>)</strong>?" <em>Arel</em> (H6189, uncircumcised) when applied to non-physical features in Hebrew means "blocked, stopped up, ritually unready" (cf. uncircumcised heart, Deut 10:16; uncircumcised ear, Jer 6:10). Moses\'s "uncircumcised lips" are lips that are blocked from effective speech — not in need of literal circumcision but of covenant opening. The repetition of this objection (first in 4:10) frames it as a persistent self-perception that YHWH will eventually correct not through argument but through experience.</p>',
    "13": '<p>YHWH\'s response to Moses\'s renewed objection is to commission both Moses and Aaron together. The "charging" (<em>vaytsav</em>, H6680) of them both — a term used for formal official orders — authorizes the joint mission with full divine authority.</p>',
    "14": '<p>The genealogical register begins: Reuben\'s sons — Hanoch, Pallu, Hezron, and Carmi. This interruption of the narrative just before the plagues serves to anchor Moses and Aaron in their full tribal lineage. The genealogy moves quickly through Reuben and Simeon to reach Levi, the tribe that matters for the commission context.</p>',
    "15": '<p>Simeon\'s sons listed, including "Shaul the son of a Canaanite woman" — the ethnically mixed ancestry is noted without comment, consistent with the text\'s honest inclusion of narratives that complicate the purity of covenant lineage (cf. Judah and Tamar, Gen 38).</p>',
    "16": '<p><strong>Levi\'s three sons</strong> — Gershon, Kohath, and Merari — and his total lifespan of 137 years. The Levite genealogy is the point of the entire insert; Reuben and Simeon are listed to establish that the genealogy is ordered by birth sequence before arriving at Levi. Kohath (Moses\'s grandfather\'s line) gets the most detail.</p>',
    "17": '<p>Gershon\'s sons: Libni and Shimei — the priestly clans that will serve in the Kohathite-Gershonite-Merarite division of Levitical service (Num 3-4).</p>',
    "18": '<p>Kohath\'s sons: Amram, Izhar, Hebron, Uzziel. Kohath lived 133 years. <em>Amram</em> (H6019, "the people are exalted") — Moses and Aaron\'s father; his name connects the family to the collective identity of the people being liberated.</p>',
    "19": '<p>Merari\'s sons: Mahli and Mushi. The three clans of Levi are now established — Gershon, Kohath, Merari — each with their own sub-clans that will be assigned distinct roles in the tabernacle service.</p>',
    "20": '<p><strong>Amram married Jochebed (<em>Yocheved</em>, H3115, "YHWH is her glory") his father\'s sister</strong> — a marriage that Lev 18:12 will later prohibit ("do not have sexual relations with your father\'s sister"). The genealogy records the union without apology: the Sinai legislation had not yet been given; the patriarchal and early Mosaic periods precede the codification of these prohibitions. Jochebed is described as bearing "Aaron and Moses" — Aaron is named first, consistent with his role as elder brother (Exod 7:7).</p>',
    "21": '<p>Izhar\'s sons: Korah, Nepheg, Zichri. <strong>Korah</strong> (H7141) — the rebel whose challenge to Moses and Aaron will be narrated in Num 16-17; the genealogy introduces him without comment here, establishing him as Moses\'s first cousin before his rebellion is recorded.</p>',
    "22": '<p>Uzziel\'s sons: Mishael, Elzaphan, and Sithri. Elzaphan (Elizaphan) appears again in Num 3:30 as the leader of the Kohathite clan; his genealogical prominence here anticipates his later administrative role.</p>',
    "23": '<p><strong>Aaron married Elisheba</strong>, daughter of Amminadab and sister of Nahshon. Nahshon (H5177) was the prince of Judah (Num 1:7; 2:3) and a direct ancestor of David (Ruth 4:20) and of Jesus (Matt 1:4; Luke 3:32). Aaron\'s marriage connects the Levitical priesthood to the Davidic-Judahite line through the marriage of the first high priest.</p>',
    "24": '<p>The sons of Korah are listed — Assir, Elkanah, Abiasaph. These become the "Korahite" Levites; Num 16 records Korah\'s rebellion, but the Korahite clan persists in priestly service (1 Chr 9:19; Pss 42, 44-49, 84-85, 87-88 are "Psalms of the Sons of Korah"). The genealogical record includes without erasing even the lineage that produces rebellion.</p>',
    "25": '<p><strong>Eleazar son of Aaron married a daughter of Putiel</strong>, and she bore him Phinehas. Phinehas (H6372) will become the paradigm of covenant zeal (Num 25:7-11 — he acts decisively in the Baal-Peor incident and receives "the covenant of peace" and a "covenant of everlasting priesthood"). The genealogy is establishing the priestly lineage that will run through Eleazar and Phinehas, not through Nadab and Abihu who will die offering unauthorized fire (Lev 10:1-2).</p>',
    "26": '<p>"It was this same Aaron and Moses (<em>hu Aaron u-Moshe</em>) to whom the LORD said..." — the resumptive identification closes the genealogical bracket, re-anchoring the narrative to the two named protagonists. The genealogy has established their credentials; now the text can proceed. The reversal of order ("Aaron and Moses" instead of "Moses and Aaron") may signal Aaron\'s prominence as spokesman in the sequence that follows.</p>',
    "27": '<p>The same Moses and Aaron who appeared before Pharaoh are those who brought Israel out of Egypt — the genealogy has anchored them in the covenant lineage; now the narrative resumes with their commission confirmed and their identity established before the plague sequence begins.</p>',
    "28": '<p>The temporal marker "on the day the LORD spoke to Moses in Egypt" — a resumptive temporal clause that re-anchors the narrative timeline after the genealogical digression. The formal date-formula is used in Leviticus and Numbers to introduce divine-speech units (Lev 1:1, "called to Moses and spoke to him from the tent of meeting, saying").</p>',
    "29": '<p>"I am YHWH — tell Pharaoh king of Egypt everything I tell you." The commission is restated in its simplest form: the entire content of the message is "everything I tell you" — total obedience to the divine word, not selective transmission. The formula <em>ani YHWH</em> again: the commission is grounded in identity, not argument.</p>',
    "30": '<p><strong>"Since I speak with faltering lips, why would Pharaoh listen to me?"</strong> — Moses repeats the "uncircumcised lips" objection from v.12. The repetition (6:12, 6:30) creates a bracket around the genealogy: the same objection before and after the family credentials are established. Despite his genealogical legitimacy, Moses still distrusts his own speech. YHWH\'s response will not be to fix Moses\'s speech but to work through him anyway — the ultimate answer to the "faltering lips" objection is the plagues themselves.</p>'
  }
}

def main():
    existing = load_comm('mkt-original', 'exodus')
    merge_comm(existing, EXODUS)
    save_comm('mkt-original', 'exodus', existing)
    print('Exodus 4-6 mkt-original commentary written.')

if __name__ == '__main__':
    main()
