"""
MKT Original Commentary — Revelation chapters 12–16
Run: python3 scripts/zc-original-revelation-12-16-new.py

Source data used:
- data/interlinear/revelation.json
- data/translation/glossary-greek.json (therion, charagma, aparchē, hypomone, helkos)
- data/translation/draft/mediating/revelation.json (MKT text)
- Existing scripts: zc-original-revelation-1-5.py (style baseline), zc-original-revelation-21-22-full.py

Key decisions:
- Transliterated Greek in <strong> tags, following established Revelation original style
- The 144,000 (ch. 14) treated symbolically as the full redeemed community, not literal male celibates;
  parthenos read as spiritual purity (not defiled by beast-cult apostasy) per prophetic metaphor
- ἐδόθη (edothē, divine passive) throughout ch. 13 treated as theologically significant — noted at each instance
- Harmagedōn (16:16) given full Hebrew etymology and OT background
- 13:18 (666) is already in output file; including it here is harmless (merge_comm skips it)
- The three-herald angels (14:6-11) treated as sequential proclamations building toward the harvest
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

REVELATION = {
  "12": {
    "1": '<p><strong>sēmeion mega ōphthē en tō ouranō</strong>: "a great sign appeared in heaven." <em>Sēmeion</em> (sign, portent) signals that what follows is symbolic vision, not literal astronomy. Revelation has used <em>sēmeion</em> for its major symbolic visions (12:1, 3; 15:1). The woman clothed with sun, moon under her feet, and twelve stars: the imagery of Gen 37:9 (Joseph\'s dream — sun, moon, and eleven stars bowing to him) now applied to the covenant people as a cosmic figure. The twelve stars = twelve tribes of Israel, though in Revelation\'s typological reading, the woman is simultaneously OT Israel (through whom the Messiah came) and the NT church (the ongoing covenant community).</p>',

    "2": '<p><strong>ōdinousan kai basanizomenēn tekein</strong>: in labor pains (<em>ōdinousan</em>) and torment (<em>basanizomenēn</em>) to give birth. The birth-pang imagery activates Isa 66:7-8 (before she was in labor she gave birth; before her pain came upon her she delivered a son — the miraculous Zion-birth) and Mic 5:2-3 (she who is in labor will give birth, and the rest of his brothers will return). These OT texts describe Zion\'s eschatological birth of the Messiah. The pain signals that the birth is historical, not triumphalist — the covenant community suffers in bringing forth the Messiah.</p>',

    "3": '<p><strong>drakon megas pyrros</strong>: a great red dragon. <em>Drakon</em> in the LXX regularly translates Hebrew תַּנִּין (<em>tannin</em>), the sea-monster of primordial chaos (Ps 74:13-14; Isa 27:1; 51:9; Ezek 29:3). The seven heads and ten horns combine features from Daniel\'s four beasts (Dan 7:3-7 — lion, bear, leopard, terrible beast with ten horns) into one super-beast. The seven diadems (<em>hepta diademata</em>) are royal crowns — the dragon claims the sovereignty that belongs to God alone. The color red (<em>pyrros</em>) signals bloodshed and violence.</p>',

    "4": '<p><strong>hē oura autou syrei to triton tōn asterōn tou ouranou</strong>: his tail drags (<em>syrei</em>, drags along forcibly) a third of the stars and hurls them to earth. Stars in Revelation and Daniel can represent angelic beings (Dan 8:10; Job 38:7); the dragon\'s expulsion of a third of the heavenly host is the mythological background for the origin of demonic beings — the fallen angels who follow Satan\'s rebellion. The dragon\'s positioning (<em>hestēken</em>, standing, present tense: stationed himself) before the woman is the posture of the predator waiting to devour the newborn — echoing Pharaoh\'s infanticide (Exod 1:15-22) and Herod\'s (Matt 2:16).</p>',

    "5": '<p><strong>arsen</strong>: the masculine form emphasizing the child\'s gender identity as the Messiah-king. <em>Ho mellōn poimainein panta ta ethnē en rhabdō sidēra</em> (who is to rule all the nations with a rod of iron) — the direct citation of Ps 2:9, the royal enthronement psalm that speaks of the anointed king\'s dominion. The male child\'s destiny is established by psalm before he acts.</p><p><strong>hērpasthē pros ton theon</strong>: <em>hērpasthē</em> (aorist passive of <em>harpazō</em>) — was snatched up, caught away. The Ascension compressed into one violent verb: Christ\'s exaltation is not a peaceful gradual lifting but an eschatological rescue from the dragon\'s reach. The rapture of the child to God\'s throne (<em>pros ton theon kai pros ton thronon autou</em>) bypasses the entire earthly ministry to focus on the Incarnation-Death-Resurrection-Ascension as one act of deliverance.</p>',

    "6": '<p><strong>eis tēn erēmon</strong>: the wilderness — the Exodus typology. The protection of the woman in the wilderness echoes God\'s protection of Israel in the Sinai wilderness (Exod 19:4; Deut 32:10-12; Isa 40:3; Jer 31:2). The <em>erēmos</em> in Revelation is not desolation but the place of divine preparation and preservation. Ετοίμασεν (prepared) — God prepared the place, not circumstance: the community\'s protection is by divine provision, not human ingenuity.</p><p><strong>chilias diakosioi hexēkonta hēmerai</strong>: 1,260 days = 42 months = 3½ years = "a time, times, and half a time" (Dan 7:25; 12:7). This figure from Daniel represents the duration of the Antichrist\'s oppression — the eschatological half-week (half of Daniel\'s symbolic seven). In Revelation it frames the entire period between Christ\'s ascension and parousia as simultaneously the time of the beast\'s apparent triumph and the community\'s protected tribulation.</p>',

    "7": '<p><strong>Michaēl kai hoi angeloi autou</strong>: Michael and his angels. <em>Michaēl</em> = Hebrew מִיכָאֵל (<em>Mika\'el</em>, "who is like God?") — the archangel who is Israel\'s guardian prince in Dan 10:13, 21; 12:1, and in Jude 9 fights over Moses\' body. The war in heaven (<em>polemos en tō ouranō</em>) is not a cosmological event prior to creation but a consequence of the Messiah\'s ascension (v. 5): Christ\'s exaltation to God\'s throne triggers the expulsion of the accuser from the heavenly court. The timing is theologically precise: the war follows the coronation.</p>',

    "8": '<p><strong>ouk ischysen</strong>: he was not strong enough — a flat, unqualified statement of the dragon\'s defeat. <em>Ouk ischysen</em> (imperfect of <em>ischyō</em>: he kept not being strong enough, he proved insufficient). <em>Oude topos heurethē autois eti en tō ouranō</em>: no place (<em>topos</em>) was found for them any longer in heaven. The denial of <em>topos</em> is significant: in Job 1-2, Satan had ongoing access to the heavenly court. The Resurrection-Ascension removes this access permanently — the accuser is evicted from the divine courtroom where he prosecuted the saints.</p>',

    "9": '<p><strong>ho ophis ho archaios</strong>: the ancient (<em>archaios</em> = original, from the beginning) serpent — explicitly identifying the dragon with the Eden serpent of Gen 3. Revelation\'s interpretive key: the cosmic dragon behind world history is the same creature that deceived Eve. The three titles given: <em>diabolos</em> (devil = slanderer, false accuser), <em>Satanas</em> (from Hebrew שָׂטָן, <em>satan</em> = adversary, accuser), <em>ho planōn tēn oikoumenēn holēn</em> (the one who deceives the whole inhabited world — present participle: ongoing deception). The Greek <em>diabolos</em> and Hebrew <em>satan</em> are nearly synonymous: both mean adversarial accuser. Revelation gives both names to mark continuity across both testaments.</p>',

    "10": '<p><strong>katēgōr tōn adelphōn hēmōn</strong>: the accuser (<em>katēgōr</em>) of our brothers. <em>Katēgōr</em> is a rare form (also <em>katēgoros</em> elsewhere), possibly a Greek loan from Aramaic <em>katēgora</em>. The picture is legal: the dragon has been prosecuting the saints before God\'s court day and night (<em>hēmeras kai nyktos</em>). This matches the Job 1-2 and Zech 3:1 pattern where the adversary brings charges against God\'s people before the divine throne. The defeat announced: <em>eblēthē</em> (was thrown down, aorist: a completed expulsion) — the accuser has been permanently removed from his prosecutorial role.</p>',

    "11": '<p><strong>enikēsan auton dia to haima tou Arniou kai dia ton logon tēs martyrias autōn</strong>: they conquered him by two instruments — the blood of the Lamb (objective) and the word of their testimony (subjective). The Lamb\'s blood answers every charge the accuser can bring; the saints\' faithful testimony (even unto death) corroborates the verdict. <em>Ouk ēgapēsan tēn psychēn autōn achri thanatou</em>: they did not love their <em>psychē</em> (life-force, not just the immortal soul) to the point of death — the paradox of martyrdom: by losing their lives they win the war. The ψυχή they sacrifice is precisely what the dragon attacks.</p>',

    "12": '<p><strong>euphrainesthē hoi ouranoi</strong>: let the heavens rejoice — plural imperative addressed to the heavenly realm. The doubled response: rejoicing for heaven, <em>ouai</em> (woe) for the earth and sea. <em>Ouai</em> is the lament/woe cry used in prophetic oracles (Isa 5:8-23; Amos 5:18; Matt 23). The dragon\'s expulsion means heaven\'s peace but earth\'s intensified conflict: <em>katebē ho diabolos pros hymas echōn thymon megan eidōs hoti oligon kairon echei</em> (knowing he has a short time). <em>Thymos</em> (rage, fury — also the word for the wrath of God in the bowl judgments) now characterizes the defeated dragon: fury born from desperation, not power.</p>',

    "13": '<p><strong>ote eiden ho drakōn hoti eblēthē eis tēn gēn</strong>: when the dragon saw (<em>eidon</em>) that he was thrown to the earth, he pursued (<em>ediōxen</em>) the woman. The dragon\'s response to defeat is not repentance but intensified persecution — the knowledge of defeat does not produce humility but rage. The pursuit of the woman on earth = the historical persecution of the covenant community after Christ\'s ascension. The dragon can no longer access the heavenly court so redirects his hostility to earth.</p>',

    "14": '<p><strong>hai dyo pteryx tou aetou tou megalou</strong>: the two wings of the great eagle — directly quoting the Exodus deliverance language of Exod 19:4 (I bore you on eagles\' wings and brought you to myself) and Deut 32:11 (like an eagle that stirs up its nest, that hovers over its young, spreading out its wings, catching them, bearing them on its pinions). The eagle-wings = divine protection and transport through tribulation. The wilderness period (time, times, and half a time = 3½ years = the same duration as v. 6) repeats: the protected period is the entire church age, not a literal 3½ years.</p>',

    "15": '<p><strong>ebalen ho ophis ek tou stomatos autou opisō tēs gynaikos hydōr hōs potamon</strong>: the serpent poured water (<em>hydōr</em>) like a river from his mouth after the woman. The flood of persecution — the river (<em>potamos</em>) as weapon of destruction echoes Ps 18:4 (the torrents of destruction assailed me), Ps 124:4-5 (then the flood would have swept us away), and Isa 43:2 (when you pass through the rivers, they shall not overwhelm you). The serpent\'s flood = the overwhelming power of empire-backed persecution attempting to sweep away the covenant community.</p>',

    "16": '<p><strong>ēnoixen hē gē to stoma autēs kai katepien ton potamon</strong>: the earth opened its mouth and swallowed the river. <em>Katepien</em> (swallowed) — the same verb used in Num 16:30, 32, 34 for the earth swallowing Korah\'s company who rebelled against Moses. The earth, which could be a venue for persecution, here becomes the protector of the covenant community — creation itself defends the people of God. The subversion of the serpent\'s plot by the creature he had corrupted carries ironic theological weight.</p>',

    "17": '<p><strong>to loipon tou spermatos autēs</strong>: the rest of her offspring (<em>sperma</em> = seed). The seed (<em>sperma</em>) language deliberately echoes Gen 3:15 (I will put enmity between you and the woman, and between your seed and her seed). Revelation identifies the church as the woman\'s seed — those who keep the commandments of God and hold the testimony of Jesus (<em>echontōn tēn martyrian Iēsou</em>). The dragon\'s war against the rest of the seed is the ongoing conflict of Gen 3:15, now understood as the persecution of Christ\'s followers.</p>'
  },
  "13": {
    "1": '<p><strong>ek tēs thalassēs</strong>: from the sea. The sea (<em>thalassa</em>) as the source of evil and chaos is the OT background (Dan 7:3 — four great beasts come from the sea; Isa 57:20 — the wicked are like the tossing sea; Ps 74:13 — God crushing the sea-monster). Daniel\'s four beasts (lion, bear, leopard, terrible beast) represent successive empires; Revelation\'s single beast combines all four into the ultimate totalizing empire. Ten horns and seven heads with ten diadems: the beast\'s crown (<em>diadema</em> = royal crown, symbol of authority) count exceeds the dragon\'s seven (12:3), signaling that the beast surpasses the dragon in earthly political power.</p>',

    "2": '<p><strong>to thērion ho eidon ēn homoion pardali</strong>: the beast combines leopard, bear, and lion — precisely the animals of Dan 7:3-7 but in reverse order (Daniel: lion → bear → leopard → terrible beast; Revelation lists them in reverse). The reversal may be chronological: Revelation\'s beast is the final empire, incorporating all previous empires into itself. <em>Ho drakōn edōken autō tēn dynamin autou kai ton thronon autou kai exousian megalēn</em>: the dragon gave it his power, throne, and great authority. The beast\'s imperial power is explicitly derived — it is not autonomous but delegated from the dragon, who himself has only usurped power that belongs to God.</p>',

    "3": '<p><strong>hōs esphagmenēn eis thanaton</strong>: as if slaughtered to death — <em>esphagmenēn</em> is the same perfect passive participle used of the Lamb in 5:6 (<em>hōs esphagmenon</em>). The beast parodies the Lamb: slain-and-healed vs. slain-and-risen. The deadly wound healed (<em>hē plēgē tou thanatou autou etherapeuthe</em>) inverts the resurrection: the Lamb was killed and lives (1:18); the beast appears killed and revives. The Nero redivivus legend (Nero would return from death to reclaim power) likely underlies this imagery — Domitian as the second Nero, the beast revived. <em>Hē holē gē ethaumasen opisō tou thēriou</em>: the whole earth marveled and followed (<em>opisō</em>, behind, in the wake of) the beast — wonder as the basis for worship.</p>',

    "4": '<p><strong>Tis homoios tō thēriō kai tis dynatai polemēsai met autou</strong>: "Who is like the beast, and who can make war against him?" — a deliberate parody of the divine acclamation in Exod 15:11 (Who is like you among the gods, O LORD?) and Ps 89:6 (Who is like the LORD?). The beast\'s apparent invulnerability generates a pseudo-monotheism: if no one can defeat him, he must be divine. The Roman imperial cult operated precisely on this logic — Caesar\'s universal power as evidence of divine status. Revelation unmasks this as dragon-worship (<em>tō drakōnti prosekunēsan</em>).</p>',

    "5": '<p><strong>stoma laloun megala kai blasphēmias</strong>: a mouth speaking great things and blasphemies — the exact description of Daniel\'s little horn in Dan 7:8, 11, 20. The beast is identified as the Daniel-beast. <em>Edothē autō exousia poiēsai mēnas tesserakonta [kai] dyo</em>: authority was given (<em>edothē</em> — divine passive throughout ch. 13) for 42 months. The divine passive (<em>edothē</em> = it was given by God) is theologically critical: even the beast\'s authority is divinely permitted, not self-generated. God governs even the dragon\'s agents. 42 months = the same period as 12:6, 14 — the whole era of the beast\'s dominion is within God\'s sovereign time-frame.</p>',

    "6": '<p><strong>blasphēmein to onoma autou kai tēn skēnēn autou</strong>: to blaspheme his name and his dwelling (<em>skēnē</em>). In Roman imperial theology, Domitian\'s title <em>Dominus et Deus</em> (Lord and God) directly appropriated the divine name. The blasphemy against God\'s <em>skēnē</em> (tabernacle/dwelling) and those who dwell in heaven targets the whole heavenly order: both the divine presence and the heavenly community. The beast\'s speech is the inversion of the Trisagion (4:8): where the heavenly creatures cry "Holy, holy, holy," the beast blasphemes.</p>',

    "7": '<p><strong>edothē autō poiēsai polemon meta tōn hagiōn kai nikēsai autous</strong>: it was given to him (<em>edothē</em> — divine passive again) to make war on the saints and conquer (<em>nikēsai</em>) them. The apparent paradox: the beast conquers the saints, yet the saints conquer the beast (12:11). The resolution: the beast conquers physically (martyrdom) while the saints conquer spiritually (faith through death). The divine passive confirms that even the beast\'s persecution of the saints is within God\'s sovereign permission — a pastoral word to persecuted believers. <em>Edothē autō exousia epi pasan phylēn kai laon kai glōssan kai ethnos</em>: universal authority — the fourfold formula (tribe, people, tongue, nation) that in Revelation marks the scope of either the gospel (14:6) or the beast\'s dominion.</p>',

    "8": '<p><strong>hou ou gegraptai to onoma autou en tō bibliō tēs zōēs tou Arniou tou esphagmenou apo katabolēs kosmou</strong>: everyone will worship whose name was not written in the book of life of the Lamb slain from the foundation of the world. The phrase "from the foundation of the world" is grammatically ambiguous: it can modify "slain" (the Lamb\'s sacrifice is eternal in God\'s plan, before creation) or "written" (election before creation). Both readings are theologically defensible and both are affirmed in Scripture (1 Pet 1:19-20 supports the former; Eph 1:4 and Rev 17:8 support the latter). The book of life belongs to the Lamb: election and atonement are inseparable — those written are those covered by the slain Lamb\'s blood.</p>',

    "9": '<p><strong>ei tis echei ous akousatō</strong>: "If anyone has an ear, let him hear." The verbatim refrain of the seven letters (2:7, 11, 17, 29; 3:6, 13, 22) — each letter ends with this call to attend to the Spirit\'s word. Its insertion here signals that the vision of the beast is not mere symbolic spectacle but a pastoral word addressed to the churches. What the Seer sees in vision is what the churches experience historically: persecution, economic pressure, the demand for beast-cult worship. The call to hear is a call to discern their own situation in the prophetic vision.</p>',

    "10": '<p><strong>ei tis eis aichmalōsian eis aichmalōsian hypagei</strong>: if anyone is for captivity, into captivity he goes. The saying mirrors Jer 15:2 (those for captivity, to captivity; those for the sword, to the sword). The application in context: those appointed for tribulation must endure it (<em>hōde estin hē hypomone kai hē pistis tōn hagiōn</em> = here is the patient endurance and faith of the saints). <em>Hypomone</em> (patient endurance, steadfast perseverance) is the key virtue of the Apocalypse — appearing at 1:9; 2:2-3, 19; 3:10; 13:10; 14:12. It is not passive resignation but active faithfulness maintained under eschatological pressure.</p>',

    "11": '<p><strong>allo thērion ek tēs gēs</strong>: another beast, from the earth (not the sea). The second beast (later called the false prophet: 16:13; 19:20; 20:10). <em>Dyo kerata homoia arniō</em> (two horns like a lamb): a wolf in lamb\'s clothing — its appearance mimics the Lamb of ch. 5, but <em>elalei hōs drakōn</em> (it spoke like a dragon). The mouth reveals the nature: Jesus warned that false prophets come in sheep\'s clothing (Matt 7:15). The false prophet\'s two horns may evoke prophetic authority (horns = power); its lamb-like appearance = religious legitimacy.</p>',

    "12": '<p><strong>poiei tēn gēn kai tous en autē katoikountas hina proskunēsousin to thērion to prōton</strong>: it causes the earth to worship the first beast. The false prophet\'s function is entirely doxological — it redirects worship. This is the demonic inversion of the Holy Spirit\'s role, who glorifies Christ (John 16:14): the false prophet glorifies the beast. <em>Hē plēgē tou thanatou autou etherapeuthe</em>: the healed death-wound again — the false prophet uses this miracle as the basis for coercion to worship.</p>',

    "13": '<p><strong>semeia megala</strong>: great signs (<em>sēmeia</em>). The false prophet makes fire come down from heaven (<em>ek tou ouranou katababainein</em>) in front of everyone — echoing Elijah calling down fire on the prophets of Baal (1 Kgs 18:38) and on soldiers of Ahaziah (2 Kgs 1:10-12). The false prophet mimics the greatest OT prophetic miracle to legitimize the beast-cult. Jesus warned that false christs and false prophets will perform great signs and wonders to deceive even the elect (Matt 24:24; Mark 13:22) — Revelation shows this happening with the beast\'s prophet.</p>',

    "14": '<p><strong>plana tous katoikountas epi tēs gēs dia ta sēmeia</strong>: it deceives (<em>planaō</em> — leads astray) those who dwell on the earth by means of the signs. <em>Planaō</em> is the core deception verb in Revelation — the dragon is "the one who leads the whole world astray" (12:9). The false prophet extends this deception through miraculous authentication. <em>Legōn tois katoikousin epi tēs gēs poiēsai eikona tō thēriō</em>: telling those who dwell on the earth to make an <em>eikōn</em> (image) of the beast. Roman emperor worship included statues of the emperor receiving divine honors — the <em>eikōn</em> is the cultus statue that becomes the focus of imperial worship.</p>',

    "15": '<p><strong>dounai pneuma tē eikoni tou thēriou</strong>: to give <em>pneuma</em> (breath/spirit) to the image. <em>Pneuma</em> here = breath or life-spirit. The false prophet animates the idol — whether through ventriloquism, priestly manipulation, or demonic agency. This action parodies God breathing life into Adam (Gen 2:7: <em>enephysēsen eis to prosōpon autou pnoēn zōēs</em>). The idolatrous image receives a counterfeit <em>pneuma</em> from the false prophet rather than the life-breath that the true God alone can give. <em>Hina hosoi ean mē proskunēsōsin tē eikoni tou thēriou apokanthōsin</em>: those who refuse to worship the image are killed — the ultimate expression of the beast-cult\'s totalitarian claim.</p>',

    "16": '<p><strong>poiē pantas</strong>: it causes all — the fourfold social spectrum (small and great, rich and poor, free and slave) is exhaustive: no social category is exempt from the economic-religious pressure. <em>Charagma</em> (mark, brand) — the technical Greek term for an official stamp, seal, or brand used on imperial documents, coins, and animals/slaves. The imperial seal on commercial documents and the use of coins bearing the emperor\'s image (with divine titles) made economic participation in Roman society a constant low-grade act of emperor acknowledgment. Revelation\'s <em>charagma</em> intensifies this to a formal religious mark — the satanic parody of the seal of God on the foreheads of the 144,000 (7:3; 9:4; 14:1).</p>',

    "17": '<p><strong>hina mē tis dynētai agorasai ē pōlēsai ei mē ho echōn to charagma</strong>: that no one can buy (<em>agorasai</em>) or sell (<em>pōlēsai</em>) without the mark. Economic exclusion as persecution — the beast\'s economic control makes daily survival contingent on beast-cult participation. The verb <em>agorazō</em> (to buy) is theologically loaded in Revelation: it is also the redemption verb — the Lamb purchased (<em>ēgorasas</em>) the saints (5:9; 14:3-4). Those who refuse to be economically "bought" by the beast have been already "bought" by the Lamb. The two purchases are mutually exclusive.</p>',

    "18": '<p><strong>de estin sophia ho echōn noun psēphisatō ton arithmon tou thēriou arithmos gar anthrōpou estin kai ho arithmos autou hexakosioi hexēkonta hex</strong>: \'666\' — the number of the beast. <em>Arithmos anthrōpou</em> (number of a human/humanity) — the beast\'s number is not cosmic but human, not transcendent but sub-divine. <em>Gematria</em> (assigning numerical values to letters) was a common Greco-Roman literary technique. The best-attested solution: NERON KAISER in Hebrew letters (nun=50 + resh=200 + vav=6 + nun=50 + qoph=100 + samek=60 + resh=200 = 666). Nero Caesar as the prototype of the beast — the first Roman persecutor of Christians — makes the political-historical reference legible to John\'s seven churches (ca. 90-95 CE, under Domitian, the \'second Nero\').</p>'
  },
  "14": {
    "1": '<p><strong>to Arnion hestōs epi to oros Siōn</strong>: the Lamb standing (<em>hestōs</em> — perfect participle, standing in the resurrection state, same as 5:6) on Mount Zion. The contrast with 13:1 (beast from the sea) is deliberate: where the beast rises from the chaos of the sea, the Lamb stands on Zion — the OT eschatological locus of divine deliverance (Ps 2:6; 48:2; Isa 4:5; Joel 2:32; Obad 17, 21; Mic 4:7). Zion was the place where God enthroned his king (Ps 2:6); now the Lamb stands there as the enthroned conqueror. The 144,000 with the Lamb bear <em>to onoma autou kai to onoma tou patros autou</em> (his name and his Father\'s name) on their foreheads — the seal of divine ownership contrasting with the beast\'s mark.</p>',

    "2": '<p><strong>phōnēn ek tou ouranou hōs phōnēn hydatōn pollōn kai hōs phōnēn brontēs megalēs</strong>: "like the sound of many waters and of loud thunder." This triple simile for the heavenly song echoes Ezek 1:24 (the sound of many waters, like the voice of the Almighty, when they moved). The sound is described before the singers are identified, emphasizing the overwhelming auditory reality of the heavenly worship. <em>Hōs kitharōdōn kitharizontōn en tais kitharais autōn</em>: like harpers harping — the harp (<em>kithara</em>) is the instrument of praise (Ps 33:2; 150:3).</p>',

    "3": '<p><strong>ōdēn kainēn</strong>: a new song. The "new song" (<em>ōdē kainē</em>) in the Psalter (Ps 33:3; 40:3; 96:1; 98:1; 144:9; 149:1; Isa 42:10) always celebrates a new act of divine salvation — a song specific to this redemption, not a recycled doxology. <em>Oudeis edynato mathein tēn ōdēn</em>: no one could learn (<em>manthanō</em>, to learn by study and practice) the song except the 144,000 — because the song expresses their specific experience. Redemption gives knowledge that cannot be acquired otherwise; only the redeemed-through-tribulation can sing the redeemed-through-tribulation song.</p>',

    "4": '<p><strong>houtoi eisin hoi meta gynaikōn ouk emolynthēsan parthenoi gar eisin</strong>: these are those who have not defiled themselves with women, for they are virgins. The <em>porneia</em>/purity language in Revelation is consistently used for spiritual apostasy and idolatry (the great prostitute of ch. 17; Jezebel in 2:20-22; Babylon making all nations drink the wine of her sexual immorality). The 144,000\'s virgin purity (<em>parthenoi</em>) = they have not committed spiritual adultery with the beast-cult. In prophetic literature, idolatry is consistently framed as harlotry (Hos 1-3; Ezek 16; 23; Jer 2-3). Literal celibacy is possible but less consistent with Revelation\'s symbolic register.</p><p><strong>aparchē</strong>: firstfruits — the 144,000 are the firstfruits (<em>aparchē</em>) of God\'s great harvest. The harvest metaphor unites the 144,000 (firstfruits, v. 4) with the great grain and grape harvest of vv. 14-20: they are the beginning of the full redeemed humanity.</p>',

    "5": '<p><strong>en tō stomati autōn ouch heurethē pseudos</strong>: in their mouth no lie was found. <em>Pseudos</em> (falsehood, lie) is the defining characteristic of the beast\'s false prophet (13:14: <em>plana</em>) and of those excluded from the new Jerusalem (21:27; 22:15). The 144,000\'s freedom from falsehood marks them as authentic witnesses — their testimony (<em>martyria</em>) is truthful because they have not compromised with the beast\'s deceptions. <em>Amōmoi</em>: blameless, without blemish — the same word used for the unblemished sacrificial animal (Num 19:2 LXX; Heb 9:14; 1 Pet 1:19). The 144,000 are themselves the spotless offering — they are both worshippers and the sacrifice.</p>',

    "6": '<p><strong>euangelion aiōnion</strong>: the eternal gospel (<em>euangelion aiōnion</em>) — the only occurrence of this phrase in the NT. <em>Aiōnios</em> (eternal, age-spanning) qualifies the gospel as transcending any particular historical moment: the good news of God\'s reign is not time-conditioned. The angel proclaims it to <em>epi panta ethnē kai phylas kai glōssas kai laous</em> (every nation, tribe, tongue, and people) — the fourfold universal formula from Dan 3:7 LXX, marking the complete universality of the proclamation. The scope of the gospel matches the scope of the beast\'s dominion (13:7) — every people group hears.</p>',

    "7": '<p><strong>phobēthēte ton theon kai dote autō doxan</strong>: Fear God and give him glory — two imperatives establishing the fundamental posture of true worship. <em>Phobeomai</em> (reverential awe, not mere terror) and <em>didōmi doxan</em> (give glory, attribute honour) are both explicitly commanded in contrast to the earth-dwellers\' reflexive glorification of the beast (13:4). <em>Hoti ēlthen hē hōra tēs kriseōs autou</em>: the hour of his judgment has come — <em>ēlthen</em> aorist: it has arrived. The eschatological hour is here, not impending. The gospel call goes out precisely because judgment is imminent: the <em>euangelion</em> and the <em>krisis</em> are simultaneous.</p>',

    "8": '<p><strong>Epesen, epesen Babulōn hē megalē</strong>: "Fallen, fallen is Babylon the great" — the doubled <em>epesen</em> (fell, fell) reproduces exactly the LXX form of Isa 21:9 (fallen is Babylon; and all the carved images of her gods he has shattered to the ground) and Jer 51:8 (suddenly Babylon has fallen and been broken). The prophetic perfect: the fall is announced as already accomplished from the heavenly perspective before it is historically described in chs. 17-18. <em>Hē ek tou oinou tou thymou tēs porneias autēs pepotiken panta ta ethnē</em>: the wine of the passion of her sexual immorality — Babylon\'s seduction is economic and religious intoxication that makes resistance seem impossible.</p>',

    "9": '<p><strong>ei tis proskunei to thērion kai tēn eikona autou</strong>: if anyone worships the beast and its image — the condition for receiving God\'s wrath. The three-part object (beast, image, mark) = the full apparatus of the beast-cult: the political power (beast), the religious apparatus (image), and the economic integration (mark). Worship of any one implies the full system. The third angel\'s proclamation (vv. 9-11) is the most severe warning in Revelation, matching the severity of the beast\'s claim.</p>',

    "10": '<p><strong>pinei ek tou oinou tou thymou tou theou tou kekerasmenou akratou</strong>: he will drink the wine of God\'s wrath poured full strength (<em>akraton</em> = unmixed, undiluted — wine was normally diluted with water; undiluted wine = maximum potency). The cup of divine wrath from Ps 75:8; Isa 51:17; Jer 25:15-17 is here poured <em>akraton</em> — no dilution, no mitigation. <em>En pyri kai theiō</em>: with fire and sulfur — the Sodom judgment formula (Gen 19:24; Ezek 38:22). The torment is not incidental but the just response to beast-worship.</p>',

    "11": '<p><strong>ho kapnos tou basanismou autōn eis aiōnas aiōnōn anabainei</strong>: the smoke of their torment ascends forever and ever. This echoes Isa 34:10 (Edom\'s judgment: its smoke shall go up forever; from generation to generation it shall lie waste) applied now to those who worship the beast at the final judgment. <em>Ouk echousin anapausin hēmeras kai nyktos</em>: they have no rest (<em>anapausis</em>) day or night — the permanent inversion of the Sabbath rest promised to the faithful (14:13). The eternal persistence of judgment is stated here with the strongest language in the NT.</p>',

    "12": '<p><strong>hōde hē hypomonē tōn hagiōn estin</strong>: here (<em>hōde</em>) is the patient endurance of the saints. <em>Hypomonē</em> (steadfast endurance, active perseverance under pressure) is the virtue that connects 14:9-11 to 14:12: the eternal severity of judgment on beast-worshippers is the theological ground for the saints\' endurance. Knowing what beast-worship costs (eternally) makes the temporal cost of refusal bearable. <em>Hoi tērountes tas entolas tou theou kai tēn pistin Iēsou</em>: those who keep God\'s commandments and the faith of Jesus — both commitments define the saint who endures.</p>',

    "13": '<p><strong>Makarioi hoi nekroi hoi en Kyriō apothnēskontes ap\' arti</strong>: "Blessed are the dead who die in the Lord from now on." The third beatitude in Revelation (1:3; 14:13; 16:15; 19:9; 20:6; 22:7, 14). <em>Ap\' arti</em> (from now on) — specifically the martyrs of the eschatological tribulation. <em>Nai, legei to Pneuma</em>: Yes, says the Spirit — the Spirit authenticates the beatitude with divine affirmation. <em>Hina anapausontai ek tōn kopōn autōn</em>: they rest (<em>anapauō</em>) from their labors — the same rest denied to beast-worshippers (v. 11). The two destinies: rest for the faithful dead, no rest for beast-worshippers.</p>',

    "14": '<p><strong>homoion hyion anthrōpou</strong>: one like a son of man — the Danielic figure of Dan 7:13 (one like a son of man came with the clouds of heaven and came to the Ancient of Days) now enthroned on a white cloud. The golden crown (<em>stephanos chrysous</em>) signals royal authority; the sharp sickle (<em>drepanon oxy</em>) is the harvest tool. The figure is Christ himself — combining Dan 7\'s Son of Man with Joel 3:13 (put in the sickle, for the harvest is ripe). The harvest image from the Parable of the Weeds (Matt 13:39-43) is here expanded to cosmic scale.</p>',

    "15": '<p><strong>ēlthen hē hōra therisai</strong>: the hour to reap has come — <em>ēlthen</em> aorist: arrived. <em>Exēranthē ho therismos tēs gēs</em>: the harvest of the earth is ripe/dried out. <em>Xērainō</em> (to dry, wither) applied to grain means it has reached full maturity and is ready to harvest — not rotting but fully ripe. The harvest language echoes Isa 17:5 (the gleanings of the grain), Joel 3:13 (the harvest is ripe, go in and tread, for the winepress is full), and Matt 13:39-43. This grain harvest (vv. 15-16) represents the gathering of the righteous.</p>',

    "16": '<p><strong>ebalen ho kathēmenos epi tēs nephelēs to drepanon autou epi tēn gēn</strong>: the one seated on the cloud swung (<em>ebalon</em>) his sickle over the earth, and the earth was reaped (<em>etheristhē</em>). The brevity of the description signals the sovereignty and efficiency of divine judgment: a single act, worldwide scope, instantaneous completion. <em>Etheristhē</em> — the harvest passive: the earth is harvested as the object, not the agent. The great reaping of history comes to completion in one decisive act.</p>',

    "17": '<p><strong>allos angelos exēlthen ek tou naou tou en tō ouranō</strong>: another angel came out of the temple (<em>naos</em>) in heaven. The grape harvest angel (vv. 17-20) is distinct from the one-like-a-son-of-man (vv. 14-16), and both come from the heavenly temple — the source of the eschatological harvest is divine, authorized from the heavenly sanctuary. The <em>naos</em> (inner sanctuary) houses the divine presence; these angels emerge from the place of God\'s holiness to execute the harvest of judgment.</p>',

    "18": '<p><strong>allos angelos ek tou thusiastēriou</strong>: another angel from the altar (<em>thusiastērion</em>). This is the altar that holds the souls of the martyred (6:9-10) — those who cried out for justice. The angel who has authority over fire (<em>exousian epi tou pyros</em>) calls for the grape harvest. The fire-angel from the altar of incense (8:3-5) earlier hurled fire to earth as divine judgment; now the altar-angel summons the grape harvest of wrath. The martyrs\' cry for justice (6:10: "How long?") is being answered.</p>',

    "19": '<p><strong>tēn lēnon tou thymou tou theou ton megan</strong>: the great winepress of the fury (<em>thymos</em>) of God — the OT winepress of judgment from Isa 63:3 (I have trodden the winepress alone; from the peoples no one was with me) and Joel 3:13 (tread, for the winepress is full). The one who treads the winepress in Isa 63 is YHWH himself, the divine warrior; in Rev 19:15 Christ treads the winepress. The judgment is not impersonal force but the direct action of the holy God against evil.</p>',

    "20": '<p><strong>exō tēs poleōs</strong>: outside the city. In Isa 63:1-6, the divine warrior comes from Edom, outside Jerusalem. More significantly, Christ was crucified outside the city walls (John 19:20; Heb 13:12-13) — the blood of Calvary shed outside Jerusalem prefigures the blood of divine judgment poured out outside. <em>Haima ek tēs lēnou achri tōn chalinōn tōn hippōn apo stadiōn chiliadōn hexakosiōn deka tessarōn</em>: blood up to the horses\' bridles for 1,600 stadia. 1,600 = 4 × 4 × 100 — the number four (four corners of the earth) squared and magnified a hundredfold: universal, complete, maximal judgment.</p>'
  },
  "15": {
    "1": '<p><strong>sēmeion allo en tō ouranō mega kai thaumaston</strong>: another great and marvelous sign in heaven. <em>Thaumaston</em> (marvelous, wonderful) — the same word used for the works of God in v. 3. The seven last plagues complete (<em>etelesthē</em> — aorist passive, proleptic announcement: it stands completed) the wrath of God. <em>Etelesthē</em> is the same root as Jesus\' <em>tetelestai</em> ("it is finished," John 19:30) — the completion of wrath corresponds to the completion of atonement. The seven bowls are the final expression of divine judgment, bookending history with the cross.</p>',

    "2": '<p><strong>thalassan hyalinēn memigmenēn pyri</strong>: a sea of glass (<em>thalassa hyalinē</em>, 4:6) now mixed with fire (<em>memigmenēn pyri</em>). In 4:6 the sea of glass was crystal-clear, before the throne, symbolizing divine transcendence and purity. Now mixed with fire — the community of overcomers stands on it, having passed through the fire of tribulation. <em>Kithāras tou theou</em>: harps of God — instruments of praise (Ps 33:2; 150:3; 1 Chr 25:6). The victors stand (<em>hestōtas</em>) in triumph with the instrument of worship.</p>',

    "3": '<p><strong>ōdēn Mōyseōs tou doulou tou theou kai tēn ōdēn tou Arniou</strong>: the song of Moses the servant of God and the song of the Lamb — a unified song, not two songs. The Song of Moses (Exod 15) celebrated Israel\'s deliverance through the Red Sea; the Song of the Lamb celebrates the new exodus through the great tribulation. Both deliverances are celebrated as one: the same God who split the sea saves his people from every beast. The content is a mosaic of OT texts: <em>Megala kai thaumasta ta erga sou, Kyrie ho theos ho Pantokratōr</em> (Ps 111:2; 139:14) — <em>Dikaiai kai alēthinai hai hodoi sou</em> (Deut 32:4; Ps 145:17).</p>',

    "4": '<p><strong>Tis ou mē phobēthē, Kyrie, kai doxasei to onoma sou</strong>: "Who will not fear you, O Lord, and glorify your name?" — the rhetorical question from Jer 10:7 (Who would not fear you, O King of the nations? For this is your due). <em>Hoti monos hosios</em>: for you alone are holy (<em>monos hosios</em>) — a claim that none of the beast\'s divine titles can match. <em>Panta ta ethnē hēxousin kai proskunēsousin enōpion sou</em>: all nations will come and worship before you — the eschatological universalism of Ps 86:9; Isa 66:23; Zeph 2:11. The song anticipates the fulfillment before the bowls that will bring it about.</p>',

    "5": '<p><strong>ho naos tēs skēnēs tou martyriou en tō ouranō ēnoigē</strong>: the temple of the tabernacle of testimony in heaven was opened. <em>Skēnē tou martyriou</em> is specifically the wilderness tabernacle — the tent of meeting that housed the ark of the covenant with the tablets of the law (testimony). The opening of the heavenly tabernacle reveals its contents: the seven angels with the seven plagues emerge from inside. The judgment proceeds from within the holy place — from the law\'s demands being met by the wrath that the law prescribes for covenant violation.</p>',

    "6": '<p><strong>endedymenoi linon katharon lampron kai periezōsmenoi peri ta stēthē zōnas chrysas</strong>: clothed in pure bright linen with golden sashes. The priestly garments echo Dan 10:5 (the heavenly man clothed in linen with a belt of fine gold). The seven angels are priest-warriors: they come from the temple (v. 6) dressed in priestly regalia to pour out judgment. The phialai (bowls) they carry are themselves priestly vessels — wide, shallow libation bowls used in temple worship. The judgment has a liturgical character: it is the divine worship service of holy war.</p>',

    "7": '<p><strong>phialas chrysas gemas tou thymou tou theou tou zōntos eis tous aiōnas tōn aiōnōn</strong>: golden bowls (<em>phialai</em>) full of the wrath (<em>thymos</em>) of the God who lives forever and ever. <em>Phialē</em> is a wide, shallow bowl used for libations — the shape signals that the contents will be poured quickly and completely, not slowly dispensed. The wrath belongs to the living God (<em>tou zōntos eis tous aiōnas</em>) — in contrast to the dead idols of the beast-cult. The living God\'s wrath is executed by the living God: it has eschatological permanence and moral authority.</p>',

    "8": '<p><strong>eplēsthē ho naos kapnou ek tēs doxēs tou theou kai ek tēs dynameōs autou</strong>: the temple was filled with smoke from the glory of God and from his power. This is the smoke-of-Theophany from Isa 6:4 (the house was filled with smoke at YHWH\'s appearance) and Exod 40:34-35 (Moses was unable to enter the tent of meeting because the cloud settled on it and the glory of the LORD filled the tabernacle). The divine presence overwhelms the temple — making it inaccessible. <em>Oudeis edynato eiselthein eis ton naon</em>: no one could enter until the seven plagues were completed. The theology of holy war: God fights alone; no human intercession is possible or needed during the final judgment. The closed temple = the completion of the age of intercession.</p>'
  },
  "16": {
    "1": '<p><strong>megalēs ek tou naou legousēs tois hepta angelois</strong>: a loud voice from the temple commanding the seven angels. The voice from the temple (<em>ek tou naou</em>) — the divine command originates from the inaccessible sanctuary of 15:8. The seven bowls are poured at explicit divine command, not on the angels\' initiative. The bowl judgments are the most direct expression of divine wrath in Revelation: no human or angelic mediating action, just the direct pouring of God\'s fury onto the earth.</p>',

    "2": '<p><strong>helkos kakon kai ponēron</strong>: ugly and painful sores (<em>helkos</em>). The Greek word <em>helkos</em> is used in the LXX for the boils of the sixth Egyptian plague (Exod 9:9-11: <em>helkē phlyktidēs</em>, sores of blisters) — the direct connection to the exodus plagues is explicit. The first bowl targets those who have the mark of the beast and worship its image — the judgment is specific and just: those who aligned themselves with the beast system receive the first plague. The Egyptian plagues distinguished between Israel and Egypt (Exod 8:22-23); the bowls distinguish between beast-worshippers and the sealed.</p>',

    "3": '<p><strong>hōs nekrou</strong>: like blood of a dead person — <em>nekros</em> (corpse) modifies the blood: not fresh arterial blood but the thick, dark, clotted blood of a corpse. Echoes the first Egyptian plague (Exod 7:17-21) but amplified: not just one river but the entire sea. <em>Pasa psychē zōēs apethanen</em>: every living soul (<em>psychē zōēs</em> — the Hebraic phrase <em>nefesh chayyah</em> from Gen 1:20-21, 24; 2:7) died. The universal mortality of marine life signals that the old creation\'s life-sustaining systems are failing under divine judgment.</p>',

    "4": '<p><strong>egenonto haima</strong>: they became blood. The third bowl turns rivers and springs to blood — now the fresh water supply joins the salt water. The escalation from sea to rivers to springs makes the judgment total: no water source is unaffected. Taken together with the second bowl, the entire hydrological system of the planet becomes the instrument of judgment — the waters that sustain life become the blood that witnesses to death.</p>',

    "5": '<p><strong>dikaios ei, ho ōn kai ho ēn, ho hosios</strong>: "You are just, the one who is and who was, the Holy One" — the angel of the waters affirms divine justice using the Revelation formula for God\'s eternal being (1:4, 8; 4:8). <em>Hosios</em> (holy, set apart for God) applied to God himself — the only being who is intrinsically holy. <em>Hoti tauta ekrinas</em>: because you judged these things — the judgment is legally grounded (<em>krinō</em>), not arbitrary revenge. The angel of the waters (<em>ho angelos tōn hydatōn</em>) testifies from within the judgment he experiences: even the created order acknowledges the justice of its own transformation into blood.</p>',

    "6": '<p><strong>hoti haima hagiōn kai prophētōn execheran kai haima autois dedōkas pein</strong>: "for they poured out the blood of saints and prophets, and you have given them blood to drink — they deserve it." <em>Axios eisin</em>: they are worthy/deserving — the same <em>axios</em> used of the Lamb\'s worthiness to receive worship (5:12) now applied to the persecutors\' worthiness to receive judgment. The lex talionis operates at cosmic scale: those who shed blood receive blood. The rivers-to-blood judgment is the precise inversion of their crime.</p>',

    "7": '<p><strong>ēkousa tou thusiastēriou legontos</strong>: I heard the altar (<em>thusiastērion</em>) saying. The altar speaks — the altar that held the souls of the martyrs (6:9-10) who cried "How long?" now responds. The altar\'s voice affirms: <em>Nai, Kyrie ho theos ho Pantokratōr, alēthinai kai dikaiai hai kriseis sou</em> (Yes, Lord God Almighty, true and righteous are your judgments). The martyred souls have been answered: the God of justice has acted. The altar\'s response closes the loop opened in 6:9-10.</p>',

    "8": '<p><strong>edothē autō kaumatisai tous anthrōpous en pyri</strong>: it was given to the sun to scorch people with fire. <em>Edothē</em> — the divine passive again: the fourth plague is divinely authorized. The sun, which sustains life, becomes the instrument of judgment — creation\'s benevolent functions inverted. <em>Kauma mega</em>: intense heat — a judgment that cannot be hidden from or escaped; it falls on all exposed to it.</p>',

    "9": '<p><strong>eblasphēmēsan to onoma tou theou tou echontos tēn exousian epi tas plēgas tautas kai ou metenoesan dounai autō doxan</strong>: they blasphemed the name of God who has authority over these plagues, and they refused to repent to give him glory. The response to judgment is the diagnostic: repentance or hardening. The plague-recipients know the source of the plagues (<em>tou echontos tēn exousian</em> = God) and choose blasphemy over worship. This is Pharaoh\'s hardening under the Egyptian plagues (Exod 7:3; 9:12; 10:1) reproduced at cosmic scale — the final plagues confirm the final hardening of those who will not repent.</p>',

    "10": '<p><strong>ton thronon tou thēriou</strong>: the throne of the beast — the political power center attacked directly. <em>Egeneto hē basileia autou eskotōmenē</em>: its kingdom was plunged into darkness (<em>skotizō</em>). The ninth Egyptian plague was three days of darkness (Exod 10:21-23); here the darkness falls on the beast\'s entire kingdom. <em>Emasōnto tas glōssas autōn ek tou ponou</em>: they gnawed their tongues from the pain — an image of anguish with no remedy. The darkness does not produce reflection but intensified suffering.</p>',

    "11": '<p><strong>eblasphēmēsan ton theon tou ouranou ek tōn ponōn autōn kai ek tōn helkōn autōn kai ou metenoesan ek tōn ergōn autōn</strong>: they blasphemed the God of heaven because of their pain and sores, and refused to repent of what they had done. The refusal to repent is repeated (cf. v. 9) as the defining response. <em>Ek tōn ergōn autōn</em>: from their works — repentance would require acknowledging that their works were wrong. The beast-worshippers are defined by the works they have chosen; repentance would mean abandoning the entire framework of identity they have built around the beast-cult. Final judgment hardens rather than softens.</p>',

    "12": '<p><strong>ton potamon ton megan ton Euphratēn</strong>: the great river Euphrates. The drying of the Euphrates to prepare the way for the kings from the east echoes multiple OT passages: Isa 41:2, 25 (the one from the east whom YHWH has raised up); Isa 44:28-45:1 (Cyrus from the east who dries the rivers); the crossing of the Red Sea (Exod 14) and Jordan (Josh 3-4). <em>Hina hetoimasthē hē hodos tōn basileōn tōn apo anatolēs hēliou</em>: the way is prepared for the kings from the rising of the sun. The irony: the drying of the Euphrates (the boundary of the empire) allows the assault that will destroy Babylon.</p>',

    "13": '<p><strong>pneumata tria akatharta homoia batrachois</strong>: three impure spirits like frogs. The frog plague is the second Egyptian plague (Exod 8:1-15) — the unclean animal associated in Jewish thought with impurity and noise. The three frog-spirits emerge from the unholy trinity: the dragon, the beast, and the false prophet. This demonic triad parodies the Holy Trinity — as the Spirit proceeds from the Father and the Son, these spirits proceed from the dragon\'s unholy delegation. <em>Ekporeuomena ek tou stomatos</em>: proceeding from the mouths — from speech, propaganda, and deceptive proclamation rather than from power.</p>',

    "14": '<p><strong>pneumata daimoniōn poiountas sēmeia</strong>: spirits of demons performing signs (<em>sēmeia</em>). The miraculous signs authenticate the false assembly call — just as the false prophet performed signs to compel beast-worship (13:13-14). The target: <em>tous basileis tēs oikoumenēs holēs</em> (the kings of the whole inhabited world) — assembled for battle (<em>polemon</em>) on the great day of God Almighty (<em>tēs hēmeras tēs megalēs tou theou tou Pantokratoros</em>). The cosmic battle is not fought by human forces but assembled by demonic deception — the kings think they are gathering for conquest but are being gathered for their own destruction.</p>',

    "15": '<p><strong>Idou erchomai hōs kleptēs</strong>: "Look, I come like a thief" — a parenthetical interruption of Christ in the narrative. The same image as 1 Thess 5:2; 2 Pet 3:10; Matt 24:43-44: the thief\'s coming is sudden and unannounced. <em>Makarios ho grēgorōn kai tērōn ta himatia autou</em>: blessed is the one who stays awake and keeps his garments — the sixth beatitude in Revelation. Keeping garments (<em>himatia</em>) = spiritual alertness and prepared readiness. The naked shame (<em>gymnos</em>) that follows is Adam\'s shame (Gen 3:7) and the Laodiceans\' (3:18): spiritual unprepared exposure. The beatitude is addressed directly to readers in the churches: the battle of Armageddon is the background, the call to watchfulness is the pastoral word.</p>',

    "16": '<p><strong>ton topon ton kaloumenon Ebraisti Harmagedōn</strong>: the place called in Hebrew Harmagedōn. The Greek transliterates Hebrew הַר מְגִדּוֹ (<em>Har Megiddo</em>) = Mount of Megiddo. Megiddo in the Valley of Jezreel (Esdraelon) was the site of decisive historical battles: Deborah and Barak defeated Sisera near Megiddo (Judg 5:19); the good king Josiah died at Megiddo (2 Kgs 23:29). Zech 12:11 speaks of the great mourning of Megiddo as a figure for eschatological lamentation. Revelation uses the name as a symbolic assembly point — the place of decisive battle becomes the world-stage for the final conflict between the Lamb and the beast.</p>',

    "17": '<p><strong>Gegonen</strong>: "It is done!" — the perfect of <em>ginomai</em>: it has happened and stands accomplished. The same announcement formula as 21:6 at the completion of the new creation, here marking the completion of the bowl judgments. The voice from the throne, from the temple (<em>apo tou naou apo tou thronou</em>) — the divine sanctuary is the source of both the command (v. 1) and this completion announcement. <em>Apo tou thronou</em>: from the throne where God and the Lamb are enthroned (22:1, 3) — the completion of judgment is declared from the seat of sovereign authority.</p>',

    "18": '<p><strong>seismos megas oios ouk egeneto aph\' hou anthrōpos egeneto epi tēs gēs</strong>: an earthquake (<em>seismos</em>) such as has never occurred since humans were on the earth. The superlative earthquake — exceeding all previous seismic events in human history — marks the eschatological finality of the seventh bowl. <em>Tēlikoutos seismos houtōs megas</em>: so great an earthquake. The earthquake as divine theophany (Exod 19:18; Ps 68:8; Isa 29:6; Ezek 38:19-20) here reaches its ultimate expression — the entire geophysical order disrupted by the presence of God\'s final judgment.</p>',

    "19": '<p><strong>hē polis hē megalē eis tria merē</strong>: the great city split into three parts. The great city (<em>hē polis hē megalē</em>) = Babylon/Rome (16:19 confirms: <em>Babulōn hē megalē</em>). The tripartite division signals total structural collapse — not damage but disintegration. <em>Emnēsthē Babulōn hē megalē enōpion tou theou dounai autē to potērion tou oinou tou thymou tēs orgēs autou</em>: God remembered Babylon — <em>emnēsthē</em> (remembered) is the divine memory that is coextensive with judgment: when God remembers an evil, he acts against it. The cup of wrath (<em>potērion tou oinou tou thymou</em>) that Babylon forced others to drink (14:8; 17:2; 18:3) is now given to her.</p>',

    "20": '<p><strong>pasa nēsos ephugen kai orē ouch heurethēsan</strong>: every island fled and the mountains could not be found. The disappearance of the geological features — islands and mountains — signals the dissolution of the physical order that has provided hiding places and boundaries. Compare 6:14 (every mountain and island was removed from its place) — the sixth seal previewed what the seventh bowl completes. The mountains and islands that the kings of the earth had retreated to for refuge (6:15-16) are no longer available. The creation\'s landmarks are erased.</p>',

    "21": '<p><strong>chalaza megalē hōs talentiaia katabainen ek tou ouranou epi tous anthrōpous</strong>: great hailstones, about a talent\'s weight (<em>talentiaia</em>), falling from heaven on people. A talent = approximately 75-130 pounds. The seventh Egyptian plague was hail (Exod 9:23-25) — here magnified to catastrophic weight. <em>Eblasphēmēsan hoi anthrōpoi ton theon ek tēs plēgēs tēs chalazēs</em>: people blasphemed God because of the plague of hail. The final response to the final plague is still blasphemy — the hardening is complete. The bowl judgment cycle ends where it began (v. 9): with people who know the source of the plagues and curse rather than worship. No repentance occurs under the bowls; this is the judgment, not the call to repentance.</p>'
  }
}

def main():
    existing = load_comm('mkt-original', 'revelation')
    merge_comm(existing, REVELATION)
    save_comm('mkt-original', 'revelation', existing)
    print('Revelation 12–16 mkt-original written.')

if __name__ == '__main__':
    main()
