"""
original | Isaiah | 33-36 | python3 scripts/zc-original-isaiah-33-36.py

Key translation decisions:
- Isa 33:7: shalom='peace' -- the envoys of shalom weeping; peace as covenantal wholeness, not just absence of war
- Isa 33:8: berit='covenant' -- the treaty/covenant broken; the word carries OT legal-relational weight
- Isa 33:14: olam='everlasting' in 'everlasting burnings' -- the absolute temporal sense maintained
- Isa 33:22: YHWH as judge/lawgiver/king -- three titles for the same divine person, anticipating 1-king eschatology
- Isa 34:10: olam='forever' in 'smoke rises forever' -- permanent divine judgment
- Isa 34:16: ruach='Spirit' -- the Spirit who gathers the animals fulfills the divine word (mouth-command link)
- Isa 35:2: kavod='glory' x2 -- the glory of Lebanon/Carmel given to the desert, anticipating the new-creation glory
- Isa 35:4-5: Elohim -- 'your God will come'; the healing miracles cited by Jesus (Matt 11:5; Luke 7:22)
- Isa 35:8: qodesh='Holiness' -- Way of Holiness is the consecrated highway of return
- Isa 36: melek repeated -- the great king vs the King of Zion; the political-theological test of the chapter
"""
import json, pathlib
ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

ISAIAH = {
"33": {
"1": "<p>The woe-oracle (<em>hoy</em>) targets the anonymous destroyer and betrayer -- likely Assyria, which has used other nations and will be discarded. The oracle operates on a law-of-retaliation principle: when you finish destroying, you will be destroyed; when you stop betraying, you will be betrayed. The MKT preserves the passive-future forms that make the reversal feel structural rather than merely retributive.</p>",
"2": "<p>YHWH is flagged -- the direct address to the covenant God: <em>LORD, be gracious to us; we wait for you.</em> The <em>arm of strength every morning</em> is a daily-renewal image of divine help; not a crisis intervention but a covenantal sustenance renewed each day. The waiting (<em>qivvinu</em>) is active expectation, not passive resignation -- the same word for hope used in Isa 40:31 (those who wait on the LORD).</p>",
"3": "<p>At the sound of the LORD's voice the peoples flee -- a theophanic motif where the divine voice itself causes panic and scattering. The distinction between the voice (which causes flight) and the rising (which causes scattering) is a two-stage theophany: first auditory, then visible. The nations' flight at divine speech anticipates the NT pattern of demons fleeing at Jesus' word.</p>",
"4": "<p>The spoil is gathered like locusts stripping a field -- the simile runs both ways. The victor gathers the Assyrian's abandoned spoil as efficiently as a locust swarm strips crops: nothing is left. The locusts and grasshoppers evoke the plague imagery -- as Egypt was stripped by locusts (Exod 10:14-15), Assyria will be stripped by a similar comprehensive plundering.</p>",
"5": "<p>YHWH is flagged; <em>tsedaqah</em> (righteousness, disp 3) is flagged -- <em>he has filled Zion with justice and righteousness.</em> The MKT renders <em>tsedaqah</em> as <em>righteousness</em> alongside <em>mishpat</em> (justice). The filling of Zion with these qualities is an act of the exalted LORD dwelling on high -- divine attributes descend into the city from the transcendent LORD. The MKT's pairing preserves both the social-legal (mishpat) and the moral-relational (tsedaqah) dimensions.</p>",
"6": "<p>YHWH is flagged -- <em>the fear of the LORD is Zion's treasure.</em> The stability of times is an unusual phrase -- <em>emunat ittekha</em>: the faithfulness/steadiness of your times. The MKT's <em>stability of your times</em> renders <em>emunah</em> as stability, capturing the firmness and reliability of the covenantal era. The list of treasures -- salvation, wisdom, knowledge, fear of the LORD -- is comprehensive; the fear of the LORD (the beginning of wisdom, Prov 9:10) is listed last as the crown of the sequence.</p>",
"7": "<p><em>Shalom</em> (peace, disp 2) is flagged -- <em>the envoys of peace are weeping bitterly.</em> The MKT renders <em>shalom</em> as <em>peace</em> -- the covenant-wholeness word. The envoys of peace represent whatever diplomatic and negotiating process Judah attempted with Assyria; they failed. The <em>brave warriors</em> (<em>erelam</em>) crying out and the peace-envoys weeping mark the total failure of both military and diplomatic options, driving the people to the prayer of v2.</p>",
"8": "<p><em>Berit</em> (covenant, disp 3) is flagged -- <em>he has broken the covenant.</em> The covenant broken is likely the treaty between Hezekiah and Sennacherib (2 Kings 18:14-17). The MKT's <em>covenant</em> carries the full OT legal-relational weight: this is not merely a violated political agreement but a sworn commitment that creates legal and moral obligations. The cities despised and men regarded as nothing -- the comprehensive destruction of civil society by the Assyrian advance.</p>",
"9": "<p>The earth mourning (<em>avlah</em>) is a double entendre: the land fades/mourns as if in grief. Lebanon, Sharon, Bashan, and Carmel -- the four most fertile and productive regions of the land -- are listed as the regions now shaking off and wilting. These are not arbitrary place-names; they are the places of greatest natural abundance, now described as dried up (shaken off as in harvest). The MKT's <em>shakes off</em> for Carmel captures the image of a vine stripped bare.</p>",
"10": "<p>YHWH is flagged -- the divine self-declaration of rising (<em>equm</em>) and being exalted (<em>eromam</em>) and lifted up (<em>etnasse</em>): three synonymous verbs of divine elevation corresponding to the Assyrian's arrogance of v8. The Assyrian despised everyone; now the LORD declares his counter-elevation. The triple rise-declaration is the structural inversion of the triple woe (v1).</p>",
"11": "<p><em>Ruach</em> is flagged (disp 4) -- <em>your own breath, like fire, will consume you.</em> The Assyrian's breath/spirit that has powered his pride will become the fire that destroys him. The MKT's <em>breath</em> captures the Hebrew <em>ruach</em> in its wind/breath sense here -- not the Spirit of God but the Assyrian's own vital force turned against him. Chaff and stubble are the Assyrian's works; fire is the Assyrian's own spirit.</p>",
"12": "<p>The peoples burned like limestone -- the image is of thorough calcination: limestone burned until it becomes quicklime, destroyed to its chemical structure. Thornbushes set ablaze -- the briefest and most complete combustion. The two images together (rock reduced to powder, thornbush gone in a flash) represent comprehensive judgment that leaves nothing behind, working on both the enduring and the ephemeral.</p>",
"13": "<p>YHWH is flagged (<em>yada</em>, know, disp 2) -- <em>acknowledge my power.</em> The call goes to both the far and the near: those who are distant witnesses and those who have seen the events close up. The MKT's <em>acknowledge</em> translates <em>yada</em> in its acknowledgment sense: not merely recognizing facts but giving appropriate recognition to divine power. The covenantal knowing-acknowledgment is the expected response to YHWH's acts.</p>",
"14": "<p><em>Olam</em> (everlasting, disp 3) is flagged -- <em>who among us can live with the devouring fire? Who among us can dwell with everlasting burnings?</em> The sinners in Zion ask the question that v15-16 will answer. <em>Olam</em> is rendered <em>everlasting</em> -- absolute rather than age-long -- because the consuming fire of divine holiness is being described in its eternal, unchanging quality. The terror of Zion's sinners before the holy God in their midst is the starting point for the righteous-path description that follows.</p>",
"15": "<p><em>Tsedaqah</em> (righteousness, disp 3) is flagged -- <em>the one who walks righteously.</em> The answer to v14's question: the person who walks <em>tsedaqot</em> (righteousness-paths) and speaks <em>mesharim</em> (uprightly). The MKT's <em>righteously</em> and <em>honestly</em> cover both the moral and the verbal dimensions. The list of negatives (refusing unjust gain, shaking hands free of bribes, stopping ears against murder-plots, closing eyes against evil) delineates righteousness by what it refuses.</p>",
"16": "<p><em>Aman</em> (believe/reliable, disp 2) is flagged -- rendered in the phrase <em>his bread will be provided</em> (<em>nitan</em>: given/provided) and <em>his water will be reliable</em> (<em>ne'emanim</em>: faithful/sure). The righteous person dwells on the heights in a fortress of rock -- both images of security beyond the reach of siege and famine. <em>Ne'emanim</em> is the adjective from the <em>aman</em> root: reliable, trustworthy water that does not dry up or fail. The MKT's <em>reliable</em> is a good rendering of this faithfulness-dimension.</p>",
"17": "<p><em>Melek</em> (king, disp 2) is flagged -- <em>your eyes will see the king in his beauty.</em> The eyes that were closed against evil (v15) will now see the king. The king in his beauty is the eschatological king -- the righteous ruler of ch 9 and 11 revealed in his full glory. The MKT's <em>in his beauty</em> is literal: <em>beyofi</em> means in his loveliness/handsomeness. The land stretching far away extends the vision beyond the siege-compressed walls of Jerusalem to a spacious future.</p>",
"18": "<p>The heart will <em>meditate on the terror</em> -- looking back from the eschatological peace to remember how threatening the Assyrian bureaucracy was. The questions -- where is the scribe, the tribute-tallier, the tower-counter? -- are the questions of relief: all those oppressive mechanisms of empire are gone. The MKT's <em>tallied the tribute</em> is a vivid rendering of the Assyrian fiscal administration that demanded payment from conquered peoples.</p>",
"19": "<p>The fierce people with incomprehensible speech -- the Assyrian administrators whose language (Akkadian) was foreign and whose contemptuous tone was alien. The <em>deep speech</em> and <em>strange tongue</em> describe a language too guttural to understand, used by people who mocked and dominated (<em>scorned</em>) those they controlled. The MKT's <em>too deep to make out</em> is a good rendering of the unintelligibility -- not just different but deliberately opaque.</p>",
"20": "<p>Zion as the city of appointed festivals (<em>moed</em>) -- the three annual pilgrimage feasts of Israel. The festival-city becomes the stable tent: not one of its pegs will be pulled out, not one of its ropes broken. The tent-metaphor is striking for a permanent city -- Jerusalem is imagined as the ideal dwelling, combining the stability of a city with the intimate presence of a tent. The MKT's <em>dwelling at peace</em> captures <em>naveh shanan</em>: a peaceful pasture-home.</p>",
"21": "<p>YHWH is flagged -- <em>the LORD in his glory will be for us a place of broad rivers and streams.</em> The divine name himself is the river -- YHWH replacing the geographical feature. Instead of the Nile giving Egypt its fertility or the Euphrates giving Babylon its wealth, the LORD himself will be the river of life for Jerusalem. No galley or warship can sail these rivers -- they are beyond the reach of military power. The MKT's <em>in his glory</em> preserves the kavod dimension of the LORD's presence as Jerusalem's waterway.</p>",
"22": "<p>YHWH is flagged three times; <em>melek</em> (king, disp 2) is flagged; <em>shaphat</em> (judge, disp 2) is flagged. The triple identification -- <em>the LORD is our judge, the LORD is our lawgiver, the LORD is our king</em> -- is the eschatological fulfillment of Israel's governance structure. All three offices (judicial, legislative, executive) are held by the single divine person, the LORD. The MKT preserves all three divine titles applied to the same subject. <em>He will save us</em> -- the savior-role implicit in all three offices is made explicit.</p>",
"23": "<p>The rigging metaphor -- applied to the Assyrian war-machine described as a ship (or to Jerusalem's enemies) -- suggests a vessel unable to sail: slack ropes, unstable mast, no sail. In the context of v21 (no warship on the LORD's rivers), the slack-rigged enemy ship cannot even float on the divine river. Then the plunder will be so great that even the lame will share in it -- no one will be excluded from the eschatological bounty.</p>",
"24": "<p>No inhabitant of Zion will say <em>I am sick</em> -- the physical healing of the city's people accompanies the spiritual healing: the iniquity of the people who dwell there will be forgiven (<em>nissa avon</em>: lifted/carried, using the Servant's bearing-language of 53:4,12). The pair of healing -- bodily sickness removed, guilt lifted -- anticipates Jesus' question in Mark 2:9 (<em>which is easier, to forgive sins or to heal?</em>) by showing that the eschatological state has both as simultaneous gifts.</p>",
},
"34": {
"1": "<p>The summons to the nations (<em>goyim</em>) and peoples (<em>leumim</em>) is a universal call to witness -- <em>come near and hear</em>. The scope expands: not just nations but <em>the earth and everything in it, the world and all that comes from it</em>. The four concentric expansions (nations, peoples, earth, world) make the oracle explicitly universal in its audience even before the specific target (Edom, v5) is named. This is divine judgment that the entire creation must witness.</p>",
"2": "<p>YHWH is flagged -- <em>the LORD is enraged against all the nations.</em> The divine wrath is directed at all (<em>kol</em>) nations and all their armies -- the universality matched by the comprehensive judgment: he has devoted them to destruction (<em>heherimam</em>: placed them under the ban of holy war), given them over to slaughter. The <em>cherem</em> (devoted to destruction) is the most absolute form of divine judgment -- everything under cherem is given entirely to the LORD and cannot be retained.</p>",
"3": "<p>The physical consequences of <em>cherem</em>: the slain cast out unburied, the stench of decomposing corpses rising, the mountains soaked with blood. The scale of judgment is matched by the scale of the physical aftermath. The mountains drinking blood is a hyperbole that captures the comprehensive character of the slaughter -- even the landscape is saturated with the results of divine judgment.</p>",
"4": "<p>The cosmic-dissolution language: all the host of heaven dissolving, the heavens rolled up like a scroll, the stars falling like leaves or figs. Rev 6:13-14 echoes this exactly: stars falling, sky rolling back like a scroll. The MKT's <em>rolled up like a scroll</em> preserves the exact image that Revelation cites. The creaturely heavens (not the divine throne) are described as temporary -- the cosmos can be un-created as decisively as it was created.</p>",
"5": "<p>YHWH's sword bathed in heaven -- the divine sword is described as already prepared in the heavenly realm before it descends on Edom. The people devoted to destruction (<em>cherem</em>) are specifically identified as Edom. The sword descending from heaven to earth for judgment is the pattern NT apocalyptic uses for Christ's return with the sword from his mouth (Rev 19:15). The MKT's <em>bathed in heaven</em> is literal -- the sword is dripping from its heavenly preparation.</p>",
"6": "<p>YHWH is flagged twice -- the sword is the LORD's, filled with blood from Edomite sacrificial animals. The sacrifice imagery (lambs, goats, rams, fat, kidneys) makes the Edomite slaughter a divine sacrifice on a massive scale -- as if Edom were being offered to the LORD in the same way Israel offered sacrifices. The LORD has a sacrifice in Bozrah (the Edomite capital). This sacrificial-slaughter language recurs in Rev 19:17-18 for the eschatological battle.</p>",
"7": "<p>Wild oxen, young bulls, and mighty bulls falling alongside the Edom armies -- the wild animals of the land participate in the judgment, soaked with blood along with the human armies. The fertility of the land (fat and rich soil) is inverted: instead of grain from productive soil, blood is absorbed into the soil. The MKT's <em>soaked with blood</em> and <em>enriched with fat</em> follow the Hebrew's agricultural inversion.</p>",
"8": "<p>YHWH is flagged -- <em>the LORD has a day of vengeance, a year of recompense for the cause of Zion.</em> The double time-span (day, year) indicates both the decisive moment and the extended period of the LORD's judgment. <em>Cause of Zion</em> (<em>riv Tzion</em>: the legal case/quarrel of Zion) introduces the forensic dimension: this is not arbitrary violence but legal retribution for what was done to Zion. The LORD acts as Zion's legal advocate and enforcer.</p>",
"9": "<p>The environmental transformation of Edom's territory -- streams become tar, soil becomes sulfur, land becomes burning pitch. The Sodom-and-Gomorrah pattern (fire and sulfur, Gen 19:24-25) is applied to Edom, making Edom's judgment a second Sodom. The MKT's <em>tar</em> and <em>burning pitch</em> preserve the combustible-liquid imagery that makes the land itself flammable and permanently hostile to life.</p>",
"10": "<p><em>Olam</em> (everlasting, disp 3) is flagged -- <em>its smoke will rise forever.</em> The MKT renders <em>olam</em> as <em>forever</em> -- absolute permanent duration. Rev 14:11 applies this exactly to the smoke of torment rising forever and ever for those who worship the beast. The permanent desolation of Edom -- <em>from generation to generation it will lie desolate</em> -- functions in Revelation as the type for permanent eschatological judgment.</p>",
"11": "<p>YHWH is flagged -- the LORD stretches over Edom the measuring line of <em>tohu</em> (formlessness) and the plumb line of <em>bohu</em> (emptiness). These are the exact words of Gen 1:2 (the earth was <em>tohu vabohu</em> -- formless and void) before creation. The LORD is un-creating Edom, measuring it out with the tools of Genesis but using them to produce pre-creation chaos rather than ordered creation. The MKT's <em>measuring line of chaos and plumb line of desolation</em> captures this de-creation inversion.</p>",
"12": "<p><em>They will call it No Kingdom There, and all its princes will come to nothing.</em> The renaming of the land as <em>No Kingdom There</em> is the linguistic embodiment of the un-creation: the political reality (kingdom, princes) is declared non-existent. The nothingness (<em>efes</em>) that characterizes the princes is the same word for zero/nothing used for the idols and nations in chs 40-41.</p>",
"13": "<p>Thorns overtaking citadels, nettles and brambles in fortresses -- the reversal of human architectural achievement by wild vegetation. Haunt for jackals and home for owls: the wilderness animals that inhabit desolate places replace the human inhabitants. The citadels and fortresses that were Edom's pride become nesting grounds for scavengers.</p>",
"14": "<p>The night owl (<em>lilit</em>) will settle there and find herself a resting place. The <em>lilit</em> is a creature of the desert and desolation -- variously rendered as screech owl, night creature, or (in later tradition) a demonic figure. The MKT's <em>night owl</em> is consistent with the surrounding list of desert animals and is a defensible naturalistic rendering. The settling and finding of rest is ironic: the desolate land provides rest for the creatures of desolation.</p>",
"15": "<p>The great owl makes her nest, lays eggs, hatches, gathers young -- the complete reproductive cycle happening in the former citadel. The arrows-gather metaphor (<em>dayyah</em>, possibly a falcon or kite) gathering her kind adds another predatory bird. The thoroughness of the animal colonization -- nesting, breeding, gathering -- shows that the desolation is not temporary but has become the permanent habitat of wilderness creatures.</p>",
"16": "<p>YHWH is flagged; <em>ruach</em> (Spirit, disp 4) is flagged -- <em>for my mouth has commanded it, and his Spirit has gathered them.</em> The book of the LORD is searched for verification that each animal of vv11-15 is present -- not one will be absent, not one will lack its mate. <em>His Spirit gathered them</em> connects the creative-gathering work of the Spirit (Gen 1:2) to the de-creative gathering of desolation-animals. The same Spirit who gathered creation now gathers the un-creation. The MKT capitalizes Spirit here, reflecting the divine agent.</p>",
"17": "<p><em>Olam</em> (everlasting, disp 3) is flagged twice -- <em>they will possess it forever; from generation to generation they will dwell in it.</em> The animals' permanent possession of the desolated land is expressed with two time-spanning phrases. The MKT's <em>forever</em> and <em>from generation to generation</em> follow the Hebrew's paired temporal expressions. The lot-casting and measuring-line division (v17) mirrors the conquest-era land distribution of Israel -- but now used for the permanent allotment of wilderness to wilderness-creatures.</p>",
},
"35": {
"1": "<p>The dramatic reversal of ch 34's desolation: <em>the wilderness and the dry land will rejoice; the desert will exult and blossom like the crocus.</em> The same creation-vocabulary used for de-creation in ch 34 is now used for re-creation: the dry land (<em>tziyah</em>) and desert (<em>aravah</em>) that were places of desolation are now the subjects of joy and blossoming. The crocus (<em>chavatzelet</em>) is a spring flower -- the image of new growth in the most barren place.</p>",
"2": "<p><em>Kavod</em> (glory, disp 2) is flagged twice; <em>Elohim</em> and YHWH are flagged -- <em>The glory of Lebanon will be given to it, the splendor of Carmel and Sharon. They will see the glory of the LORD, the splendor of our God.</em> Two occurrences of <em>kavod</em>: first the glory of Lebanon/Carmel/Sharon given to the desert; then the glory of the LORD and the splendor of Elohim seen by the new-creation inhabitants. The MKT's <em>glory</em> is consistent -- the kavod that was Lebanon's is transferred to the wilderness, and the kavod that is the LORD's is then seen directly.</p>",
"3": "<p><em>Strengthen the weak hands, and steady the shaking knees.</em> The pastoral-exhortation embedded in the eschatological vision: before the final revelation of glory, the discouraged people must be strengthened. Heb 12:12 quotes this verse directly: <em>strengthen the feeble arms and weak knees</em> -- applied to the Christian who is running with endurance, encouraged by the example of Jesus who endured the cross for the coming joy.</p>",
"4": "<p><em>Elohim</em> is flagged twice -- <em>your God will come with vengeance; God will come with divine retribution -- he will come and save you.</em> The three-part divine-coming announcement: (1) with vengeance (<em>naqam</em>), (2) with retribution (<em>gemul Elohim</em>: the recompense of God), (3) to save (<em>yishakhem</em>). The first two are toward enemies; the third is toward God's people. Jesus begins to fulfill this in his healing ministry (vv5-6), while the full vengeance-retribution aspect awaits the second coming.</p>",
"5": "<p>The eyes of the blind opened and the ears of the deaf unstopped -- the two sensory-healing miracles that mark the arrival of the eschatological age. Matt 11:5 and Luke 7:22 list these exactly when Jesus answers John's question (<em>are you the one who is to come?</em>): <em>the blind receive sight, the deaf hear, the lame walk, the mute speak.</em> The MKT's rendering is close to the LXX form that the NT Gospels cite, which is important for the connection to Jesus' answer to John.</p>",
"6": "<p>The lame leaping like a deer and the mute tongue bursting into song -- the kinetic and vocal miracles. The waters breaking out in the wilderness connects the physical healing to the landscape transformation of v1-2: as the desert blossoms, so the wilderness acquires streams. The healing of the human body and the healing of the land are presented as parallel acts of the same divine restoration. The MKT's <em>burst into song</em> is vivid for the Hebrew <em>teranen</em>: shout/sing with joy.</p>",
"7": "<p>The burning sand becoming a pool and thirsty ground becoming springs -- the inversion of the desert's drought. The haunt of jackals (where only scavengers lived, cf. 34:13) becomes a place of grass, reeds, and papyrus. The reed and papyrus are specifically writing-material plants -- the association may be with the book of the LORD (34:16) being fulfilled. The MKT's <em>burning sand</em> for <em>sharav</em> is the correct identification of the desert mirage-sand.</p>",
"8": "<p><em>Qodesh</em> (holiness, disp 2) is flagged -- <em>a highway will be there, called the Way of Holiness.</em> The Way of Holiness (<em>derech haqodesh</em>) is the consecrated road of the returning exiles. The unclean will not travel on it -- the holy way is protected from defilement. <em>It is for those who walk on that Way; fools will not wander onto it</em> -- the protective exclusivity of the holy highway. The MKT's <em>Way of Holiness</em> is the standard rendering; the highway links back to 11:16 (highway from Assyria) and forward to 40:3 (prepare the way of the LORD).</p>",
"9": "<p>No lion on the Way -- the predator-free road for the redeemed. The lions absent from the highway contrast with the lions of 34:7 (wild oxen alongside Edom's armies) and recall the peaceful coexistence of 11:6-9 (lion lying down with the lamb). But the <em>redeemed</em> (<em>geulim</em>) walk there -- they are specifically the ones this road is for. The exclusion of the lion (predator) and the inclusion of the redeemed walker is the shape of the new-creation safety.</p>",
"10": "<p>YHWH is flagged; <em>olam</em> (everlasting, disp 3) is flagged -- <em>the ransomed of the LORD will return; they will come to Zion with singing, with everlasting joy on their heads.</em> The <em>geulim</em> (ransomed/redeemed, from the kinsman-redeemer root <em>goel</em>) come back with singing and <em>simchat olam</em> (everlasting/age-long joy) on their heads. The MKT's <em>everlasting joy</em> renders <em>olam</em> in the absolute sense, not the age-long sense -- the joy is permanent, not merely long-lasting. This verse is quoted in Isaiah 51:11 almost verbatim, making it an Isaianic refrain of the return-promise.</p>",
},
"36": {
"1": "<p><em>Melek</em> (king, disp 2) is flagged twice -- <em>King Hezekiah</em> and <em>Sennacherib king of Assyria.</em> The historical narrative begins with a precise date (fourteenth year of Hezekiah = 701 BC) and two kings placed in deliberate contrast. Chapter 36 is nearly verbatim from 2 Kings 18:13-37 -- the narrative appears in both books, with minor variations. The MKT follows the Isaiah version. The <em>great king</em> title that Rabshakeh uses for Sennacherib (v4) contrasts with the LORD as the true king (33:22).</p>",
"2": "<p><em>Melek</em> is flagged twice -- <em>the king of Assyria</em> sending Rabshakeh and <em>King Hezekiah</em> receiving the challenge. Rabshakeh (the field commander / title, not personal name) arrives at the conduit of the Upper Pool on the fuller's field road -- the exact location where Isaiah had earlier confronted Ahaz (7:3). The geography is significant: the crisis point of the Assyrian confrontation is the same location as the earlier Syro-Ephraimite crisis, creating a structural echo across Isaiah's career.</p>",
"3": "<p>Eliakim son of Hilkiah -- the steward installed in Shebna's place (22:20-22) -- comes out to meet Rabshakeh alongside Shebna (now the secretary, having been demoted) and Joah. The dramatic irony is visible: Shebna, against whom the woe-oracle was pronounced in ch 22, is still present but reduced to a secondary role. The cast of characters makes explicit the connection between the oracle against Shebna and the historical crisis now unfolding.</p>",
"4": "<p><em>Melek</em> is flagged twice -- the Assyrian self-designation <em>the great king, the king of Assyria</em> is Sennacherib's formal imperial title, contrasted with Hezekiah addressed simply as <em>Hezekiah</em> without royal title. The rhetorical stripping of Hezekiah's royal title while inflating Sennacherib's is deliberate diplomacy-as-domination. The question -- <em>what confidence is this in which you trust?</em> -- frames the entire speech as an interrogation of Judah's source of security.</p>",
"5": "<p>The Rabshakeh's argument: words without military strategy or battle strength are empty. The translation issue: the Assyrian is mocking the Judeans' verbal confidence (perhaps their recitation of the LORD's promises) as inadequate substitute for actual military capacity. The MKT's <em>mere words are not strategy or battle strength</em> captures the reductio ad militarem -- the Assyrian worldview that reduces all confidence to military calculation.</p>",
"6": "<p><em>Melek</em> is flagged -- <em>the king of Assyria</em> in the Rabshakeh's mouth. Egypt as a cracked and broken staff of reed -- if you lean on it, it pierces your hand. The Egypt-as-useless-ally taunt is historically accurate: Egypt had proved unable or unwilling to help Israel and Judah against Assyria (cf. 30:1-5). The MKT's <em>cracked and broken reed</em> is vivid for the Hebrew <em>kaneh haratsuts</em>: the split/cracked stick of a reed.</p>",
"7": "<p><em>Elohim</em> and YHWH are flagged -- the Rabshakeh's twisted argument: even if Judah trusts the LORD their God, hasn't Hezekiah just removed his high places and altars? The Assyrian misunderstands Hezekiah's reform (2 Kings 18:4) as impiety against the LORD, when in fact removing the high places was covenantal fidelity. The argument exposes how foreign the Assyrian framework is: he cannot distinguish between multiplying worship sites and faithful centralized worship.</p>",
"8": "<p><em>Melek</em> is flagged -- <em>my master the king of Assyria</em>. The wager of two thousand horses -- even if Sennacherib gives Judah cavalry, they cannot find enough riders. The taunt reveals the military asymmetry: Judah is not even capable of fielding the horses that Assyria could give them. The MKT's <em>make a wager</em> is a good idiomatic rendering of the Hebrew <em>hitarev-na</em>: engage/bet with my master.</p>",
"9": "<p>The rhetorical escalation: not even one of the least of Sennacherib's junior officers could be resisted by Judah with Egyptian cavalry. The argument moves from the impossible (Judah can't use horses, v8) to the absurd (yet Judah relies on Egypt for chariots and cavalry). The MKT's <em>junior officers</em> is accurate for the Hebrew <em>pechot</em>: governors/deputies, the lowest level of Assyrian command.</p>",
"10": "<p>YHWH is flagged twice -- the Rabshakeh's most audacious claim: <em>The LORD himself said to me: Go up against this land and destroy it.</em> Whether the Rabshakeh genuinely believed this (based on the Isaianic oracles about Assyria as the LORD's instrument, ch 10) or was purely bluffing, the claim uses YHWH's own name to authorize the invasion. It is both theologically perceptive (Assyria was the LORD's instrument) and spiritually presumptuous (assuming that instrument-status meant permission for this specific act).</p>",
"11": "<p>Eliakim, Shebna, and Joah ask Rabshakeh to switch to Aramaic (the diplomatic lingua franca) rather than Hebrew, which the general population on the wall can understand. The request for Aramaic is a containment strategy: keep the demoralizing speech from the ears of the people who might panic or defect. The three officials demonstrate awareness of the psychological warfare dimension of Rabshakeh's speech.</p>",
"12": "<p>Rabshakeh refuses and escalates: the speech is precisely for the people on the wall, to whom it is now addressed directly. The graphic description of famine conditions -- eating their own dung and drinking their own urine -- is the Rabshakeh's depiction of what a siege will bring. The graphic content is an attempt to break the people's will before the siege begins. The MKT preserves the graphic language as the text requires.</p>",
"13": "<p><em>Melek</em> is flagged twice -- the Rabshakeh stands up and calls in Hebrew at full volume to the people on the wall. The public proclamation using the covenant people's own language is a deliberate move to bypass the official channels and appeal directly to the population. <em>Hear the words of the great king, the king of Assyria</em> -- the imperial title repeated as rhetorical thunder.</p>",
"14": "<p><em>Melek</em> is flagged -- <em>this is the king's word.</em> The Rabshakeh attributes the speech to Sennacherib himself: <em>do not let Hezekiah mislead you -- he is not able to deliver you.</em> The word <em>deliver</em> (<em>natsil</em>) is the key word of the chapter: Rabshakeh is disputing Hezekiah's claim that the LORD will deliver, by substituting the Assyrian king as the only effective agency. The theological claim embedded in the political speech is the real confrontation.</p>",
"15": "<p>YHWH is flagged twice -- <em>do not let Hezekiah lead you to trust in the LORD by saying, The LORD will certainly deliver us -- this city will not be handed over to the king of Assyria.</em> The Rabshakeh quotes what Hezekiah is presumably saying to the people -- the Isaianic promise-formula that the city is under the LORD's protection. The Rabshakeh frames this faith as a deception. <em>Melek</em> is flagged -- the contest is between Hezekiah's LORD and Sennacherib's claim. <em>The king of Assyria</em> is used as a title of overwhelming power that the LORD cannot resist.</p>",
"16": "<p><em>Melek</em> is flagged -- the Rabshakeh speaks on behalf of <em>the king of Assyria</em>. The offer of terms -- make terms with me and surrender, eat from your own vine and fig tree -- is a parody of the Solomonic peace-picture (1 Kings 4:25; Micah 4:4). The good land promised (a land of grain, new wine, bread, vineyards, olive oil, honey) echoes the Deuteronomic promised-land formula (Deut 8:8) -- Sennacherib is offering an alternative promised land in deportation. The MKT's <em>make terms with me and surrender</em> preserves the condition of surrender embedded in the offer.</p>",
"17": "<p>The promised deportation land is described in terms deliberately echoing the Promised Land -- <em>grain and new wine, bread and vineyards</em>. The Rabshakeh is rhetorically reversing the Exodus narrative: instead of the LORD bringing Israel out of Egypt into the Promised Land, Sennacherib offers to bring them out of Jerusalem into a replacement promised land in Assyria. The MKT preserves the agricultural abundance vocabulary that makes the parallel to the Promised Land explicit.</p>",
"18": "<p><em>Elohim</em>, YHWH, and <em>melek</em> are flagged -- <em>Has any god of the nations ever delivered his land from my power? What makes you think the LORD will deliver Jerusalem?</em> The Rabshakeh's comparative-religion argument: the gods of the nations (Hamath, Arpad, Sepharvaim) could not deliver their cities from Assyria. The argument treats YHWH as one deity among others, subject to the same evaluation by military track record. The flaw in the argument is precisely its comparatist framework: the LORD is not one deity among comparable deities.</p>",
"19": "<p><em>Elohim</em> is flagged twice -- <em>where are the gods of Hamath and Arpad? Where are the gods of Sepharvaim? Did they deliver Samaria from my power?</em> The historical examples are accurate: Hamath, Arpad, and Sepharvaim had all fallen to Assyria. Samaria (the northern kingdom) had fallen in 722 BC -- within living memory of the Judeans hearing Rabshakeh's speech. The inclusion of Samaria is the most painful point: Israel's fall was supposed to be a warning to Judah, and Rabshakeh turns it into a threat.</p>",
"20": "<p><em>Elohim</em> and YHWH are flagged -- <em>Which of all the gods of these lands has ever delivered his land from my power? What makes you think the LORD will deliver Jerusalem?</em> The speech closes with the summary argument: universal Assyrian supremacy over all the gods of all the nations. The Rabshakeh's theological claim is that divine power is measurable by military outcome -- and by that measure, Sennacherib wins. The flaw is the measure, not the data. The LORD's answer will be not a battle but an angel (37:36).</p>",
"21": "<p><em>Melek</em> is flagged -- the people's silence: they did not answer the Rabshakeh a word, for the king (Hezekiah) had commanded, <em>do not answer him.</em> The silence is disciplined obedience, not defeat. Hezekiah's command not to engage with Rabshakeh's speech reflects wisdom: engaging the speech on its own terms would be to accept its framework. Silence withdraws the legitimacy that a response would confer. The MKT's <em>remained silent and said nothing in reply</em> preserves the completeness of the non-engagement.</p>",
"22": "<p>The three officials -- Eliakim the administrator, Shebna the secretary, Joah the recorder -- return to Hezekiah with their clothes torn in the sign of mourning and grief. The torn clothes are the appropriate response to blasphemous speech against the LORD: the same response Caiaphas will make at Jesus' claim to be the Son of Man (Matt 26:65). The officials' report to the king completes the chapter's narrative arc from Rabshakeh's challenge to the delegation's return -- and prepares for Hezekiah's response in ch 37.</p>",
},
}

def main():
    data = load_comm('mkt-original', 'isaiah')
    merge_comm(data, ISAIAH)
    chs = sorted(data.keys(), key=lambda x: int(x))
    total_v = sum(len(data[c]) for c in chs)
    print(f'Isaiah original: {len(chs)} chapters, {total_v} verses')
    save_comm('mkt-original', 'isaiah', data)

if __name__ == '__main__':
    main()
