"""
MKT Original Language Commentary — John chapters 1–2
Run: python3 scripts/zc-original-john-1-2.py

Source data used:
- data/interlinear/john.json
- data/translation/glossary-greek.json (logos G3056 dl=3, sarx G4561 dl=4, charis G5485 dl=2, pneuma G4151 dl=3, zoe G2222 dl=2)
- data/translation/draft/mediating/john.json (MKT text for quoting)
- data/commentary/ellicott/john.json (philological reference)

Key decisions in this range:
- logos (G3056): rendered "Word" throughout; the full semantic dispute (reason/word/cosmic principle) is noted in 1:1
- sarx (G4561): in 1:14 marks full humanity, not sinful nature; the dispute level 4 warrants explicit treatment
- monogenēs (G3439): "only-begotten" preferred over "unique"; the relational weight of the father-son bond is the argument
- 1:18 textual variant: monogenēs theos (ℵ* B) vs. monogenēs huios — noted but not resolved dogmatically
- 2:19 lysat naon: aorist imperative read as conditional ("if you destroy") not as Jesus commanding destruction
- hieron vs. naos distinction (2:14 vs. 2:19): consistently noted; they refer to different physical spaces
- charin anti charitos (1:16): anti read as succession/replacement ("grace in place of grace") not mere accumulation
- John's semeion vocabulary: he uses "signs" not "miracles" or "mighty works"; noted at 2:11
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html


JOHN = {
  "1": {
    "1": '<p><strong>ἐν ἀρχῇ ἦν ὁ λόγος</strong> — The imperfect <em>ēn</em> (was) is deliberate: it asserts pre-existence, not origin. Gen 1:1 opens "in the beginning God created" — John opens "in the beginning [the Word] already was." The Logos (<em>G3056</em>) is a high-dispute term (dispute level 3): its semantic range spans spoken word, reason, cosmic principle, and divine utterance. The Evangelist draws on all these registers while pressing beyond them.</p><p><strong>καὶ θεὸς ἦν ὁ λόγος</strong> — The predicate nominative <em>theos</em> appears without the article. This is not a diminishing of the claim ("a god") but a grammatical consequence of predicate position (Colwell\'s rule): the anarthrous predicate precedes the verb and emphasizes quality — the Word was of the divine nature. The three clauses of v.1 assert distinct propositions: (1) the Word pre-existed all creation; (2) he was in personal relation with God (<em>pros ton theon</em>, "with God" — a directional preposition implying face-to-face orientation); (3) he shared the divine nature.</p>',
    "2": '<p><strong>οὗτος ἦν ἐν ἀρχῇ πρὸς τὸν θεόν</strong> — The demonstrative <em>houtos</em> ("this one") gathers all three assertions of v.1 into a single referent before the Evangelist moves to creation. The repetition is not redundant: from the vantage point that the Word is God, the prior statements that he was with God and pre-existent are now seen together as the full portrait of the pre-incarnate Son.</p>',
    "3": '<p><strong>πάντα δι᾽ αὐτοῦ ἐγένετο</strong> — The verb <em>egeneto</em> (came to be, G1096) marks created things: they began to exist. The contrast with <em>ēn</em> (was) in v.1 is exact. The Word was; all things came to be through him. The preposition <em>dia</em> (through) marks instrumental agency — he is the agent through whom the Father creates.</p><p><strong>χωρὶς αὐτοῦ ἐγένετο οὐδὲ ἕν</strong> — The negative statement does not merely repeat the positive; it closes off every exception. <em>Ouden</em> (nothing) reinforced by <em>hen</em> (one) — not even one thing — leaves no category of created being outside his scope. The Evangelist states the same truth from both directions to prevent any reader from limiting the Word\'s creative role.</p>',
    "4": '<p><strong>ἐν αὐτῷ ζωὴ ἦν</strong> — <em>Zōē</em> (G2222, dispute level 2) in John consistently refers to divine life — the life that belongs to God as opposed to merely biological existence (<em>bios</em>). The preposition <em>en autō</em> marks the life as intrinsic to the Logos, not borrowed or bestowed.</p><p><strong>καὶ ἡ ζωὴ ἦν τὸ φῶς τῶν ἀνθρώπων</strong> — The life of the Logos becomes the light of humans: <em>phōs</em> (G5457) carries the sense of illumination, revelation, and moral clarity. John does not explain the mechanism; he asserts the equation. The light is for humans (<em>tōn anthrōpōn</em>), not a cosmic abstraction.</p>',
    "5": '<p><strong>καὶ τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει</strong> — The present tense <em>phainei</em> (shines) is not historical: it describes the ongoing state of the light. The Prologue speaks in timeless register here — before and after the Incarnation, the light shines.</p><p><strong>καὶ ἡ σκοτία αὐτὸ οὐ κατέλαβεν</strong> — <em>Katelaben</em> is an aorist of <em>katalambanō</em> (G2638), a verb that carries two distinct meanings: (1) to seize/overcome, (2) to comprehend/apprehend. Both may be in play simultaneously. The darkness has not overpowered the light and has not grasped or understood it. The aorist reaches back across the whole prior history of darkness encountering the light.</p>',
    "6": '<p><strong>ἐγένετο ἄνθρωπος ἀπεσταλμένος παρὰ θεοῦ</strong> — The shift from timeless metaphysical statement to historical narrative is marked by <em>egeneto</em> (there came/arose). John the Baptist is introduced as a sent human: <em>apestalmenos</em> (having been sent, divine passive) places him firmly in the category of commissioned agent, not self-appointed prophet. <em>Onoma autō Iōannēs</em> — the Hebrew idiom "name to him was John" signals a figure of designated role.</p>',
    "7": '<p><strong>οὗτος ἦλθεν εἰς μαρτυρίαν</strong> — <em>Martyria</em> (G3141) and its cognates dominate the first chapter. The word belongs to legal and courtroom registers: testimony before judges. John\'s role is formally evidentiary. The purpose clause <em>hina martyrēsē peri tou phōtos</em> makes his testimony instrumental: so that through him (<em>di᾽ autou</em>) all might believe.</p>',
    "8": '<p><strong>οὐκ ἦν ἐκεῖνος τὸ φῶς</strong> — The emphatic pronoun <em>ekeinos</em> (that one) and the negation <em>ouk ēn</em> together rule out John\'s identification with the light absolutely. The Evangelist states what John was not before stating what he was, ensuring no reader conflates the Witness with the Thing witnessed. This negation will recur at 1:20 when John himself denies being the Messiah.</p>',
    "9": '<p><strong>ἦν τὸ φῶς τὸ ἀληθινόν</strong> — <em>Alēthinos</em> (G228, "genuine/real") differs from <em>alēthēs</em> (factually true). The claim is not merely that this light is truthful but that it is the genuine article, the archetype of which all other illumination is derivative. <em>Phōtizei panta anthrōpon</em> — lights every person (not "all men" in a gender-exclusive sense; <em>anthrōpon</em> is generic human).</p><p>The participle <em>erchomenon</em> (coming) is syntactically ambiguous: it may modify <em>phōs</em> (the light coming into the world) or <em>anthrōpon</em> (every person coming into the world). Most interpreters attach it to the light, since John\'s Gospel consistently describes Jesus as "the one coming" into the world.</p>',
    "10": '<p><strong>ἐν τῷ κόσμῳ ἦν</strong> — The word <em>kosmos</em> appears three times in this verse, carrying three slightly different senses: (1) the created order where the Word was present, (2) the created order he made, (3) the human world that failed to recognize him. The repetition creates an ironic ladder: he made what he was in; what he made did not know its maker.</p><p><strong>καὶ ὁ κόσμος αὐτὸν οὐκ ἔγνω</strong> — <em>Egnō</em> (aorist of <em>ginōskō</em>, G1097) means to recognize, to come to know through experience. The world did not recognize him — not merely cognitive failure but relational non-reception.</p>',
    "11": '<p><strong>εἰς τὰ ἴδια ἦλθεν</strong> — <em>Idia</em> (neuter plural) denotes his own domain, his own things — the creation, and specifically Israel as his covenantal inheritance. <strong>οἱ ἴδιοι αὐτὸν οὐ παρέλαβον</strong> — <em>Idioi</em> (masculine plural) shifts to his own people. The verb <em>paralabein</em> means to receive alongside, to take to oneself. The failure is not ignorance but rejection — they encountered him and did not take him in.</p>',
    "12": '<p><strong>ἔδωκεν αὐτοῖς ἐξουσίαν</strong> — <em>Exousia</em> (G1849) is authority or right conferred, not merely ability. The right to become children of God is a granted status, not a latent potential. <em>Teknon</em> (G5043, child) is used throughout John rather than <em>huios</em> (son), which is reserved for Christ. The distinction preserves the uniqueness of the Son\'s relationship.</p><p><strong>τοῖς πιστεύουσιν εἰς τὸ ὄνομα αὐτοῦ</strong> — The present participle <em>pisteuousin</em> describes ongoing believing. <em>Eis to onoma</em> — believing into his name — is directional: not merely believing about him but directing trust toward him as a person.</p>',
    "13": '<p><strong>οἳ οὐκ ἐξ αἱμάτων οὐδὲ ἐκ θελήματος σαρκὸς οὐδὲ ἐκ θελήματος ἀνδρὸς ἀλλ᾽ ἐκ θεοῦ ἐγεννήθησαν</strong> — Three negations pile up before the positive statement. <em>Haimaton</em> (blood, plural in Greek — the mingling of parental bloods as ancient biology conceived generation); <em>thelēmatos sarkos</em> (desire of the flesh — physical reproductive drive); <em>thelēmatos andros</em> (will of a husband — the decisional act of a male head of household). The passive <em>egennēthēsan</em> (were born) marks divine initiative: the subject of the action is God, not the believer. New birth is not self-generated.</p>',
    "14": '<p><strong>ὁ λόγος σὰρξ ἐγένετο</strong> — <em>Sarx</em> (G4561, dispute level 4) is the highest-contested term in the Johannine vocabulary. Here it does not carry the Pauline sense of sinful nature but denotes the full human condition: mortal, embodied, subject to weakness and death. The choice of <em>sarx</em> over <em>anthrōpos</em> (human) or <em>sōma</em> (body) presses the point of genuine material humanity as far as language allows.</p><p><strong>καὶ ἐσκήνωσεν ἐν ἡμῖν</strong> — <em>Eskēnōsen</em> (tabernacled, from <em>skēnē</em> = tent) is a Septuagint resonance: the divine <em>Shekinah</em> dwelling in the tabernacle. The Evangelist presents the Incarnation as the climactic divine dwelling — not in curtained fabric but in flesh.</p><p><strong>μονογενοῦς παρὰ πατρός</strong> — <em>Monogenēs</em> (G3439, only-begotten) carries both uniqueness (one of a kind) and relational weight (the bond between father and only son). Both senses are needed: the gift costs what only an only son costs. <em>Plērēs charitos kai alētheias</em> — full of grace and truth — may echo the LXX pairing of <em>hesed</em> and <em>emet</em> (covenant faithfulness and reliability), the covenant character of God in Exod 34:6.</p>',
    "15": '<p><strong>Ἰωάννης μαρτυρεῖ περὶ αὐτοῦ</strong> — The present tense <em>martyrei</em> (testifies) treats John\'s historical testimony as standing testimony: it still witnesses. <strong>κέκραγεν</strong> is a perfect of <em>krazō</em> (to cry out): John has cried out and that cry stands on record.</p><p><strong>ὀπίσω μου ἐρχόμενος ἔμπροσθέν μου γέγονεν</strong> — The temporal inversion is deliberate: "the one coming after me has come to rank before me." The explanation follows: <em>hoti prōtos mou ēn</em> — because he was before me (in existence). The one who arrives later in history existed first in eternity. <em>Prōtos</em> here is temporal, not merely positional.</p>',
    "16": '<p><strong>ἐκ τοῦ πληρώματος αὐτοῦ</strong> — <em>Plērōma</em> (G4138, fullness) is not simply "abundance" but the complete totality of divine grace residing in the Logos. The preposition <em>ek</em> (from/out of) marks derivation: what believers receive is drawn from his inexhaustible supply.</p><p><strong>χάριν ἀντὶ χάριτος</strong> — The preposition <em>anti</em> is the exegetical crux. It most naturally means "in place of" or "instead of" — one grace replaced by another, grace succeeding grace in sequence (as the Mosaic covenant\'s grace is superseded by the grace of Christ, developed in v.17). Less likely is the reading "grace upon grace" (accumulation), which requires <em>anti</em> to function like <em>epi</em>.</p>',
    "17": '<p><strong>ὅτι ὁ νόμος διὰ Μωϋσέως ἐδόθη</strong> — The law was given (<em>edothē</em>, aorist passive): it came through Moses as instrument, divinely bestowed, complete in the past. <strong>ἡ χάρις καὶ ἡ ἀλήθεια διὰ Ἰησοῦ Χριστοῦ ἐγένετο</strong> — Grace and truth came to be (<em>egeneto</em>, aorist of <em>ginomai</em>): they arrived through a person, in an event. This is the first use of "Jesus Christ" by name in the Gospel — the full messianic title at the moment of introducing what surpasses Moses.</p>',
    "18": '<p><strong>θεὸν οὐδεὶς ἑώρακεν πώποτε</strong> — The perfect <em>heōraken</em> (has seen) covers all history to the present: no one at any point has had a direct vision of God. The claim grounds what follows.</p><p><strong>μονογενὴς θεός</strong> — The preferred reading of the earliest manuscripts (ℵ* and B) has <em>monogenēs theos</em> (only-begotten God) rather than <em>monogenēs huios</em> (only-begotten Son). The harder reading is textually stronger; copyists were more likely to harmonize toward "Son" (the familiar title) than to introduce "God." Both readings assert the same Christological claim; the difference is terminological, not doctrinal.</p><p><strong>ὁ ὢν εἰς τὸν κόλπον τοῦ πατρός</strong> — <em>Ho ōn</em> (the one who is/being, present participle) asserts ongoing intimate relation: the Son is continually in the Father\'s bosom/side (<em>kolpos</em> — the position of reclining proximity at a meal, cf. 13:23). <em>Exēgēsato</em> — he has narrated, disclosed, explained: the source of the English "exegesis." The Son who is at the Father\'s side is the authoritative expounder of the Father\'s character.</p>',
    "19": '<p><strong>καὶ αὕτη ἐστὶν ἡ μαρτυρία τοῦ Ἰωάννου</strong> — The formal testimony section begins: <em>martyria</em> (G3141) frames what follows as legal evidence. The <em>Ioudaioi</em> — here rendered "Jewish leaders" — sent a delegation of priests and Levites (<em>hiereis kai Leuitas</em>), the credentialed religious authorities, to conduct the inquiry.</p>',
    "20": '<p><strong>ὡμολόγησεν καὶ οὐκ ἠρνήσατο</strong> — The double statement — "he confessed AND did not deny" — is emphatic beyond normal rhetoric. <em>Homologein</em> (to confess publicly, G3670) and <em>arneomai</em> (to deny, G720) form polar opposites; stating both positive and negative reinforces the completeness of John\'s unambiguous declaration. <strong>ὅτι οὐκ εἰμὶ ἐγὼ ὁ χριστός</strong> — The word order places <em>egō</em> (I) after the verb for emphasis: "I am not — I — the Christ."</p>',
    "21": '<p><strong>Ἠλίας εἶ σύ</strong> — The questions move through eschatological categories: Elijah (expected to return before the Day of the Lord, Mal 4:5), then "the Prophet" (the Mosaic prophet of Deut 18:15). John denies all three identities. The Synoptic tradition (Matt 11:14) has Jesus identify John as Elijah "in the spirit"; John\'s Gospel records John\'s own denial, and both can be true: John is not Elijah literally returned but fulfills Elijah\'s role.</p>',
    "22": '<p>The interrogators have exhausted their categories and need a reportable answer. The question <em>tis ei</em> (who are you?) with the demand for a self-definition for those who sent them reflects the bureaucratic obligation of official emissaries to return with usable intelligence.</p>',
    "23": '<p><strong>ἐγὼ φωνὴ βοῶντος ἐν τῇ ἐρήμῳ</strong> — John identifies himself as "a voice" (<em>phōnē</em>) not a name, a person, or a title. The citation is from Isa 40:3 (LXX): a disembodied voice, instrumental and self-effacing. <em>Euthynate tēn hodon Kyriou</em> — make straight the way of the Lord. The Evangelist applies the LXX <em>Kyriou</em> (of the Lord) to Jesus, a significant Christological move.</p>',
    "24": '<p>A parenthetical note: among those sent were Pharisees (<em>ek tōn Pharisaiōn</em>). This explains the sharper follow-up question in v.25 — Pharisees were particularly concerned with unauthorized ritual innovation.</p>',
    "25": '<p><strong>τί οὖν βαπτίζεις εἰ σὺ οὐκ εἶ ὁ χριστός</strong> — The logical issue: baptism as a ritual of purification and initiation was understood in Second Temple Judaism as connected to eschatological authority. If John is none of the expected end-time figures, by what authority does he administer a new rite? The question anticipates the sign-demand in 2:18.</p>',
    "26": '<p><strong>ἐγὼ βαπτίζω ἐν ὕδατι</strong> — <em>En hydati</em> (in/with water, dative of instrument). John\'s baptism is plainly stated as water-only and therefore limited. <strong>μέσος ὑμῶν ἕστηκεν ὃν ὑμεῖς οὐκ οἴδατε</strong> — The verb <em>hestēken</em> is a perfect of <em>histēmi</em> — "has taken his stand and stands." The one they do not know is already present among them, not a future arrival. The contrast between John\'s visible water-rite and the unrecognized standing one is sharp.</p>',
    "27": '<p><strong>οὗ οὐκ εἰμὶ ἄξιος ἵνα λύσω αὐτοῦ τὸν ἱμάντα τοῦ ὑποδήματος</strong> — Loosening a sandal strap was considered below the dignity of a disciple in relation to his teacher (the Talmud forbade disciples from performing this service for their own rabbi). John places himself below even that level — not a disciple unworthy of the menial task, but one who claims no standing to perform it at all. <em>Axios</em> (G514) = worthy, deserving.</p>',
    "28": '<p><strong>ἐν Βηθανίᾳ ἐγένετο πέραν τοῦ Ἰορδάνου</strong> — The Evangelist specifies Bethany beyond the Jordan — not the Bethany near Jerusalem where Lazarus lived (11:1). The geographic precision serves as eyewitness warrant and distinguishes the two locations.</p>',
    "29": '<p><strong>ἴδε ὁ ἀμνὸς τοῦ θεοῦ ὁ αἴρων τὴν ἁμαρτίαν τοῦ κόσμου</strong> — <em>Amnos</em> (G286, lamb) is the rare LXX word used in Isa 53:7 for the Servant led to slaughter. John does not use the more common <em>arnion</em>; <em>amnos</em> carries sacrificial weight. <em>Airōn</em> is a present participle — ongoing taking away, not a single completed act. <em>Hamartian</em> is singular (the sin, not "sins"): the cosmic condition of humanity before God, not merely individual offenses. <em>Tou kosmou</em> — of the world — extends the scope beyond Israel.</p>',
    "30": '<p>John repeats his earlier paradox (cf. v.15): the one coming temporally after him has surpassed him because he pre-existed him (<em>prōtos mou ēn</em>). The repetition is not redundant — it recurs now that Jesus is visible, giving the identification claim a definite referent.</p>',
    "31": '<p><strong>κἀγὼ οὐκ ᾔδειν αὐτόν</strong> — The pluperfect <em>ēdein</em> (I had not known him) is significant: John\'s prior ignorance underscores the divine revelation in v.33. His recognition of Jesus was not prior acquaintance but divine disclosure. The purpose of his water-baptism ministry was that Jesus might be revealed (<em>phanerōthē</em>) to Israel — an apostolic purpose, not a personal one.</p>',
    "32": '<p><strong>ὅτι τεθέαμαι τὸ πνεῦμα καταβαῖνον ὡς περιστερὰν ἐξ οὐρανοῦ</strong> — The perfect <em>tetheamai</em> (I have seen and the seeing stands) makes this eyewitness testimony in the strong sense: John\'s vision remains his standing evidence. <em>Memenēken ep᾽ auton</em> — the Spirit has remained on him (perfect): a permanent indwelling, not a prophetic visitation that departs. This distinguishes Jesus from OT prophets on whom the Spirit came and went; the dove\'s resting is the sign.</p>',
    "33": '<p><strong>οὗτός ἐστιν ὁ βαπτίζων ἐν πνεύματι ἁγίῳ</strong> — The identification formula <em>houtos estin</em> (this is the one) formally designates Jesus. The contrast is complete: John with water (<em>en hydati</em>, v.31), Jesus with Holy Spirit (<em>en pneumati hagiō</em>). <em>Pneuma</em> (G4151, dispute level 3) is here unambiguous: the divine Spirit (Holy Spirit, not wind or human spirit), identified by the article and <em>hagion</em>.</p>',
    "34": '<p><strong>κἀγὼ ἑώρακα καὶ μεμαρτύρηκα ὅτι οὗτός ἐστιν ὁ υἱὸς τοῦ θεοῦ</strong> — Both verbs are perfect: <em>heōraka</em> (I have seen) and <em>memartyrēka</em> (I have testified) — John\'s sight and testimony both stand. The formal declaration <em>huios tou theou</em> (Son of God) closes the Baptist\'s witness, anticipating Nathanael\'s confession in v.49 and the Gospel\'s climactic purpose statement at 20:31.</p>',
    "35": '<p>A brief transitional verse: <em>tē epaurion</em> (the following day) marks the Evangelist\'s careful day-by-day structure in ch.1. John is present again with two disciples (<em>duo ek tōn mathētōn autou</em>) — unnamed at this point; one will be identified as Andrew in v.40.</p>',
    "36": '<p><strong>ἴδε ὁ ἀμνὸς τοῦ θεοῦ</strong> — John repeats his identification of Jesus as the Lamb of God, now without the extended clause about taking away sin. In context the compressed repetition functions as a signal to his disciples: look at him. The aorist <em>emblepsas</em> (having fixed his gaze) marks the deliberate, directed attention.</p>',
    "37": '<p><strong>καὶ ἠκολούθησαν τῷ Ἰησοῦ</strong> — The two disciples heard (<em>ēkousan</em>) and followed (<em>ēkolouthēsan</em>). Both are aorists: they heard, they followed. The chain of testimony — John points, disciples follow — is the pattern for the spread of belief throughout ch.1.</p>',
    "38": '<p><strong>τί ζητεῖτε</strong> — The first words Jesus speaks in this Gospel: "What do you seek?" The question recurs thematically at the arrest (18:4, 7). <em>Rhabbi</em> (G4461) is transliterated from Aramaic and then translated: <em>didaskalos</em> (teacher). The parenthetical translations (<em>hermēneuetai</em>) throughout ch.1 signal an audience unfamiliar with Palestinian Jewish terminology. <em>Pou meneis</em> — "where do you stay/abide?" — <em>menō</em> (abide, remain) is a key Johannine verb that will carry enormous theological weight in chs. 14–15.</p>',
    "39": '<p><strong>ἔρχεσθε καὶ ὄψεσθε</strong> — Imperative and future: "Come and you will see." The invitation pattern repeats at v.46. <em>Tēn hēmeran ekeinēn emeinen</em> — they stayed with him that day. The hour notation — <em>hōra ēn hōs dekatē</em> — is approximately 4:00 p.m. by Roman reckoning (the tenth hour of daylight from 6 a.m.) or 10:00 a.m. by Jewish reckoning. The Evangelist\'s precision may reflect eyewitness memory.</p>',
    "40": '<p><strong>Ἀνδρέας ὁ ἀδελφὸς Σίμωνος Πέτρου</strong> — Andrew is identified as Simon Peter\'s brother — a reversal of what a reader might expect, since Peter will be the more prominent figure. The Evangelist names Andrew first precisely because he is the one present in this scene. The other disciple (likely the Evangelist himself, though unnamed) is left anonymous.</p>',
    "41": '<p><strong>εὑρίσκει οὗτος πρῶτον τὸν ἀδελφὸν τὸν ἴδιον Σίμωνα</strong> — <em>Prōton</em> (first, perhaps "the first thing he did") — Andrew immediately seeks his own brother. <em>Heuriskeō</em> (find) becomes a structural verb in the call narratives of this chapter. <strong>Εὑρήκαμεν τὸν Μεσσίαν</strong> — The perfect <em>heurēkamen</em> (we have found!) marks a discovery that stands. <em>Messias</em> is transliterated from Hebrew/Aramaic and interpreted as <em>Christos</em> — both mean "Anointed One."</p>',
    "42": '<p><strong>σὺ κληθήσῃ Κηφᾶς</strong> — The name-change is a future passive: you will be called Cephas. <em>Kēphas</em> is Aramaic for rock; <em>Petros</em> is the Greek equivalent. The parenthetical note <em>ho hermēneuetai Petros</em> again signals the non-Palestinian audience. Jesus gives Simon a new identity on first meeting, before any discipleship is established — a sovereign act of naming, recalling the divine name-changes of Abram/Abraham and Jacob/Israel.</p>',
    "43": '<p><strong>ἀκολούθει μοι</strong> — The only place in ch.1 where Jesus himself initiates a call with the direct imperative "Follow me." Philip is found (<em>heuriskei</em>) by Jesus, not the other way around. The brevity of the exchange — command only, no dialogue — is characteristic of Jesus\'s authority in the call narratives.</p>',
    "44": '<p>The geographic note — Bethsaida as home of Philip, Andrew, and Peter — is historically specific and serves both narrative (Philip would have known Andrew) and topographic purposes for an audience mapping the early discipleship community.</p>',
    "45": '<p><strong>εὑρίσκει Φίλιππος τὸν Ναθαναήλ</strong> — Philip continues the chain: found → tells → invites. His summary of what they have found is notably comprehensive: <em>hon egrapsen Mōysēs en tō nomō kai hoi prophētai</em> — the one Moses wrote about in the Law and the prophets also wrote about. He identifies Jesus by Torah and prophetic witness before naming him: "Jesus of Nazareth, son of Joseph" — a fully human identification.</p>',
    "46": '<p><strong>ἐκ Ναζαρὲτ δύναταί τι ἀγαθὸν εἶναι</strong> — Nathanael\'s response is a proverb or rhetorical question, not personal hostility. Nazareth appears nowhere in OT prophecy; it was an obscure village in Galilee, itself looked down upon by Judeans. Philip\'s response — <em>erchou kai ide</em> (come and see) — does not argue but invites direct encounter, paralleling Jesus\'s own invitation in v.39.</p>',
    "47": '<p><strong>ἴδε ἀληθῶς Ἰσραηλίτης ἐν ᾧ δόλος οὐκ ἔστιν</strong> — <em>Alēthōs</em> (truly, genuinely); <em>Israēlitēs</em> — an Israelite in the full covenantal sense; <em>dolos</em> (guile, deceit, G1388) absent from him. The description echoes Ps 32:2 (no guile in his spirit) and implicitly contrasts Nathanael with Jacob/Israel, the original deceiver whose name he bears — a "true Israel" whose heart has no Jacob in it.</p>',
    "48": '<p><strong>πρὸ τοῦ σε Φίλιππον φωνῆσαι ὄντα ὑπὸ τὴν συκῆν εἶδόν σε</strong> — The temporal marker <em>pro tou</em> + infinitive: before Philip called you, while you were under the fig tree, I saw you. The aorist <em>eidon</em> asserts a specific past vision. What Jesus saw under the fig tree is not explained; the significance is the knowledge itself — supernatural insight into a private moment. Fig trees could serve as places of study and prayer in rabbinic culture.</p>',
    "49": '<p><strong>Ῥαββί, σὺ εἶ ὁ υἱὸς τοῦ θεοῦ, σὺ βασιλεὺς εἶ τοῦ Ἰσραήλ</strong> — Nathanael\'s confession doubles: <em>huios tou theou</em> (Son of God) and <em>basileus tou Israēl</em> (King of Israel). The pairing is messianic rather than ontological at this stage — "Son of God" in Ps 2:7 and 2 Sam 7:14 is a royal covenant title for the Davidic king. Both titles will gain deeper content as the Gospel unfolds.</p>',
    "50": '<p><strong>ὅτι εἶπόν σοι ὅτι εἶδόν σε ὑποκάτω τῆς συκῆς, πιστεύεις</strong> — Jesus acknowledges that Nathanael believes on the basis of a single sign (the fig-tree knowledge). The future <em>opsē</em> (you will see, singular) promises greater things: the plural of disciples in v.51 anticipates that Nathanael\'s seeing will be shared. Faith based on a single supernatural disclosure will grow to sight of heaven opened.</p>',
    "51": '<p><strong>ἀμὴν ἀμὴν λέγω ὑμῖν</strong> — The double <em>amēn</em> is a distinctive Johannine marker: it appears 25 times in this Gospel (always doubled), compared to the single <em>amēn</em> in the Synoptics. The doubling intensifies the solemn authority: what follows is not speculative.</p><p><strong>τοὺς ἀγγέλους τοῦ θεοῦ ἀναβαίνοντας καὶ καταβαίνοντας ἐπὶ τὸν υἱὸν τοῦ ἀνθρώπου</strong> — The vision echoes Jacob\'s ladder at Bethel (Gen 28:12), where angels ascended and descended <em>on it</em> (or "on him" in some readings). John applies the movement to the Son of Man: Jesus is the locus of divine-human traffic, the new Bethel ("house of God"), the place where heaven opens to earth. <em>Huios tou anthrōpou</em> (Son of Man) appears here for the first time in the Gospel; it will carry an eschatological and exaltation trajectory throughout.</p>'
  },
  "2": {
    "1": '<p><strong>τῇ ἡμέρᾳ τῇ τρίτῃ</strong> — Counting from the "next day" of 1:43, this is the third day of that sequence, giving the opening week of Jesus\'s ministry a structured seven-day shape in the Evangelist\'s narration. The phrase carries no explicit resurrection symbolism here, but the Evangelist is rarely casual about numerology. <em>Gamos</em> (G1062) is the wedding feast, not merely the ceremony; <em>Kanā tēs Galilaias</em> is specified to distinguish it from a Cana in the Phoenician region.</p>',
    "2": '<p><strong>ἐκλήθη δὲ καὶ ὁ Ἰησοῦς</strong> — The passive <em>eklēthē</em> (was invited) places Jesus in the position of a guest, not the host. The inclusion of his disciples suggests that by this point Jesus was understood to travel with a retinue — the social convention of a teacher and his students dining together as a group was recognized and accommodated.</p>',
    "3": '<p><strong>ὑστερήσαντος οἴνου</strong> — The aorist participle <em>hysterēsantos</em> (having fallen short/run out) indicates the wine supply is already exhausted when Mary speaks. Her statement <em>οἶνον οὐκ ἔχουσιν</em> (they have no wine) is factual but functions as an implicit appeal — she reports the situation to one she expects can act. The Evangelist records no explicit request.</p>',
    "4": '<p><strong>τί ἐμοὶ καὶ σοί, γύναι</strong> — <em>Gynai</em> (G1135, Woman) is a vocative used by Jesus also at 19:26 (to Mary at the cross) and 20:15 (to Mary Magdalene); it is not dismissive in Greek convention but a respectful address. The idiom <em>ti emoi kai soi</em> — "what to me and to you" — appears in OT contexts (Judg 11:12; 2 Sam 16:10; 1 Kgs 17:18) as a distancing formula marking that two parties have different concerns about a situation, not hostility.</p><p><strong>οὔπω ἥκει ἡ ὥρα μου</strong> — <em>Hōra</em> (G5610, hour) is theologically loaded in the Fourth Gospel: it refers to the appointed moment of Jesus\'s glorification through death (7:30; 8:20; 12:23; 13:1; 17:1). "My hour has not yet come" signals that the wedding miracle is not the decisive hour; that moment will come in chs. 12–19. The "not yet" (<em>oupō</em>) implies it is coming.</p>',
    "5": '<p><strong>ὅ τι ἂν λέγῃ ὑμῖν ποιήσατε</strong> — Mary\'s instruction to the servants (<em>diakonois</em>) uses an aorist imperative <em>poiēsate</em> with an indefinite relative clause (<em>hoti an legē</em> — whatever he says): unconditional and comprehensive obedience is called for. Her response to the rebuff in v.4 is neither resentment nor collapse; she proceeds in confidence.</p>',
    "6": '<p><strong>λίθιναι ὑδρίαι ἕξ</strong> — Stone (<em>lithinos</em>, G3035) water jars are specified because stone vessels could not contract ritual impurity under Levitical law (Lev 11:33 governs clay vessels; stone is exempt). Jewish households that observed <em>toharāh</em> (purity) law kept stone vessels for precisely this reason. Six jars — not seven (the complete number) — may indicate an incomplete state, though the Evangelist does not press this point. The quantity (20–30 gallons each; the Greek <em>metrētas duo ē treis</em>) gives a total of roughly 120–180 gallons: a striking excess of provision.</p>',
    "7": '<p><strong>γεμίσατε τὰς ὑδρίας ὕδατος</strong> — The command is to fill the jars with water, not wine: the servants act in ordinary faith with ordinary water. <em>Heōs anō</em> — to the brim, to the top — signals their complete obedience. No gap or reservation is left for adding anything else; the transformation, when it occurs, cannot be attributed to an adulteration of the water.</p>',
    "8": '<p><strong>ἀρχιτρικλίνῳ</strong> — The compound <em>architriklinos</em> (G755) appears nowhere else in the Bible and rarely in classical literature. It combines <em>archi-</em> (chief/head) and <em>triklinos</em> (three-couch dining room, the standard formal dining arrangement). The role was roughly that of a master of ceremonies, chosen from the guests, who regulated the dinner, tasted the wine, and managed the pace of drinking. He would have professional expertise in judging wine quality.</p>',
    "9": '<p><strong>ὡς δὲ ἐγεύσατο ὁ ἀρχιτρίκλινος τὸ ὕδωρ οἶνον γεγενημένον</strong> — The perfect participle <em>gegenēmenon</em> (having become wine) marks a transformation already completed by the time of tasting: the water has become wine and remains wine. At what moment the transformation occurred the text does not say; the Evangelist locates it between the filling and the drawing-out, keeping attention on the result rather than the process.</p>',
    "10": '<p><strong>πᾶς ἄνθρωπος πρῶτον τὸν καλὸν οἶνον τίθησιν</strong> — The master of the feast states a universal social convention: good wine (<em>kalon oinon</em>) comes first, inferior wine (<em>elassō</em>, the lesser) comes when guests are less discerning. <em>Methysthōsin</em> (when they have become drunk, G3184) is the word used without euphemism in the Synoptics and Pauline letters for drunkenness; the master of the feast describes normal banquet practice. <em>Tetērēkas</em> (you have kept, perfect): the good wine has been kept and kept available — a permanent state of provision.</p>',
    "11": '<p><strong>Ταύτην ἐποίησεν ἀρχὴν τῶν σημείων ὁ Ἰησοῦς</strong> — The Evangelist marks this formally as the <em>archēn tōn sēmeiōn</em> (beginning of the signs). <em>Sēmeion</em> (G4592, sign) is John\'s consistent vocabulary for Jesus\'s miracles: he never uses <em>teras</em> (wonder/portent) or <em>dynamis</em> (power/mighty work), the Synoptic terms. A sign points beyond itself to what it signifies — in this case, the glory (<em>doxa</em>, G1391) of Jesus. The disciples believed (<em>episteusan</em>) as a result: faith follows the revelation of glory.</p>',
    "12": '<p><strong>κατέβη εἰς Καφαρναούμ</strong> — The verb <em>katebē</em> (went down) is geographically accurate: Cana sits in the hills of Galilee while Capernaum is on the shore of the Sea of Galilee, at a lower elevation. The mention of <em>hoi adelphoi autou</em> (his brothers) alongside his mother and disciples is a matter-of-fact family reference; the relationship of Jesus\'s brothers to the discipleship community will become complex later (7:5).</p>',
    "13": '<p><strong>ἤγγιζεν τὸ πάσχα τῶν Ἰουδαίων</strong> — <em>Pascha</em> (G3957, Passover) is the first of three Passovers in John\'s Gospel (also 6:4 and 11:55/19:14), giving the ministry a three-year framework. <em>Anebē eis Ierosolyma</em> — went up to Jerusalem: the verb <em>anabainō</em> is used for pilgrimage precisely because Jerusalem is geographically elevated (at ~750 m) and theologically the place of ascent.</p>',
    "14": '<p><strong>ἐν τῷ ἱερῷ τοὺς πωλοῦντας βόας καὶ πρόβατα καὶ περιστεράς</strong> — The Evangelist uses <em>hieron</em> (G2411, the entire temple precincts including the Court of the Gentiles) not <em>naos</em> (G3485, the inner sanctuary). The commerce was in the outer courts, theologically the space designated for Gentile worship. The money changers (<em>kollybistai</em>) exchanged foreign currency for the Tyrian shekel required for temple tax — a necessary function, but one that had moved from the Mount of Olives into the sacred courts.</p>',
    "15": '<p><strong>φραγέλλιον ἐκ σχοινίων</strong> — <em>Phragellion</em> (G5416) is a Latinism — from <em>flagellum</em> — indicating the Evangelist\'s familiarity with Roman terminology. The scourge was made from cords (<em>scholniōn</em>), likely the rope used to tether animals. <em>Execheen</em> (poured out) the money — the coins were scattered; <em>anetrepsen</em> (overturned) the tables; <em>exebalen</em> (drove out) the traders. Three distinct actions, three different verbs: the act is described with eyewitness specificity.</p>',
    "16": '<p><strong>μὴ ποιεῖτε τὸν οἶκον τοῦ πατρός μου οἶκον ἐμπορίου</strong> — The contrast is between <em>oikos tou patros mou</em> (house of my Father — temple as divine dwelling) and <em>oikos emporiou</em> (market house — temple as commercial venue). The possessive <em>patros mou</em> (my Father\'s) is a Christological claim: Jesus speaks of the temple as his Father\'s house with a filial authority that positions him above even the legitimate temple authorities.</p>',
    "17": '<p><strong>ὁ ζῆλος τοῦ οἴκου σου καταφάγεταί με</strong> — The Evangelist notes that the disciples <em>remembered</em> Ps 69:9 — but with a significant difference: the LXX of Ps 69:9 reads <em>katephagen</em> (aorist — consumed), whereas the disciples\' citation uses the future <em>kataphagetai</em> (will consume). The future tense projects the cost of Jesus\'s temple zeal forward — anticipating what his action will ultimately cost him. <em>Zēlos</em> (G2205, zeal) connotes passionate, consuming devotion.</p>',
    "18": '<p><strong>τί σημεῖον δεικνύεις ἡμῖν</strong> — The authorities respond to a prophetic action by demanding a legitimating sign. <em>Sēmeion</em> again: the request for a credential-miracle to authorize an extraordinary claim. The irony, developed across the Gospel, is that Jesus has been performing signs, and they will continue to demand signs while rejecting them. <em>Exousian</em> (authority, G1849) is the underlying issue: by what right does he act?</p>',
    "19": '<p><strong>λύσατε τὸν ναὸν τοῦτον</strong> — The verb is aorist imperative: <em>lysate</em> (destroy!). This is not Jesus commanding the temple\'s destruction but framing a conditional: "If you destroy this temple, I will raise it in three days." The word is <em>naos</em> (G3485) — the inner sanctuary, the most sacred space — not the broader <em>hieron</em> of v.14. Jesus deliberately raises the stakes. <em>Egerō</em> (I will raise, future active) has Jesus as the agent of resurrection — a claim his opponents will not grasp and the disciples will only understand retrospectively (v.22).</p>',
    "20": '<p><strong>τεσσεράκοντα καὶ ἕξ ἔτεσιν οἰκοδομήθη ὁ ναὸς οὗτος</strong> — The 46-year figure is historically useful: Herod\'s temple renovation began ca. 20/19 BC (Josephus, Ant. 15.380). Forty-six years later places this exchange approximately AD 26–27, consistent with the chronology deduced from Luke 3:1. The authorities\' response demonstrates literal misunderstanding — they hear "this temple" as the Herodian building, not a body. <em>Sy egerei</em> — you (emphatic) will raise it?</p>',
    "21": '<p><strong>ἐκεῖνος δὲ ἔλεγεν περὶ τοῦ ναοῦ τοῦ σώματος αὐτοῦ</strong> — The Evangelist inserts his editorial clarification: <em>ekeinos de elegen</em> (but that one was speaking) — a retrospective explanation impossible to the original hearers, possible only from the post-resurrection vantage point. <em>Sōma</em> (G4983) is the word the Evangelist chooses for the body — not <em>sarx</em> (flesh) or <em>anthrōpos</em> — marking it as the physical body that will die and rise.</p>',
    "22": '<p><strong>ὅτε οὖν ἠγέρθη ἐκ νεκρῶν ἐμνήσθησαν</strong> — The resurrection (<em>ēgerthē ek nekrōn</em>) is the interpretive key the disciples lacked during the ministry. <em>Emnēsthēsan</em> (they remembered, aorist): a specific, time-bounded act of retrospective understanding. <em>Episteusan tē graphē kai tō logō hon eipen ho Iēsous</em> — they believed the scripture and the word Jesus had spoken: two objects of faith, both confirmed by the resurrection event.</p>',
    "23": '<p><strong>ἐπίστευσαν εἰς τὸ ὄνομα αὐτοῦ θεωροῦντες αὐτοῦ τὰ σημεῖα</strong> — The crowd in Jerusalem believes (<em>episteusan eis to onoma</em> — the same formulation as 1:12) on the basis of witnessing signs. The following verses will distinguish this sign-based crowd-faith from the deeper trust that Jesus does not reciprocate.</p>',
    "24": '<p><strong>αὐτὸς δὲ Ἰησοῦς οὐκ ἐπίστευεν ἑαυτὸν αὐτοῖς</strong> — A precise wordplay: the crowd believed in him (<em>episteusan</em>, v.23) but he did not entrust himself (<em>episteuein heauton</em>) to them. The same verb (<em>pisteuō</em>) applies to both: their faith in him and his trust of himself to them. <em>Dia to auton ginōskein pantas</em> — because he himself knew all people: the present infinitive <em>ginōskein</em> marks his ongoing knowledge of human nature as the ground for his caution.</p>',
    "25": '<p><strong>οὐ χρείαν εἶχεν ἵνα τις μαρτυρήσῃ περὶ τοῦ ἀνθρώπου</strong> — He had no need of anyone to testify to him about humanity: <em>martyria</em> (testimony) here reverses its usual direction — instead of human witnesses testifying about Jesus, he has no need of human witnesses testifying about humans to him. <em>Autos gar eginōsken ti ēn en tō anthrōpō</em> — for he himself knew what was in the person. The imperfect <em>eginōsken</em> (was knowing, ongoing) marks a characteristic and continuous divine insight into human interiority.</p>'
  }
}


def main():
    existing = load_comm('mkt-original', 'john')
    merge_comm(existing, JOHN)
    save_comm('mkt-original', 'john', existing)
    print('John 1–2 mkt-original written.')

if __name__ == '__main__':
    main()
