"""
MKT Original Commentary — 1 Chronicles chapters 27–28 (fill)
Run: python3 scripts/zc-original-1chronicles-27-28-fill.py

Source data used:
- data/interlinear/1chronicles.json
- data/translation/draft/mediating/1chronicles.json (MKT text)
- data/commentary/mkt-original/1chronicles.json (existing: v23 in ch27; v9, v19 in ch28)

Key decisions in this range:
- maḥᵃlōqet ("division/course") treated as technical administrative-liturgical term
  shared with priestly courses (ch24) — military and cultic organization are parallel
- tabnît ("pattern/plan") in ch28 traced to Exod 25:9,40 — David as second Moses
- kissēʾ malkût YHWH (28:5) — Solomon sits on YHWH's throne, not David's
- ḥᵃzaq wᵉʾᵉmāṣ formula traced: Deut 31:6 → Josh 1:5-9 → here (28:20)
- Conditionality in 28:7 (ʾim, "if") held in tension with perpetuity of 2 Sam 7:16
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(source, book):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_comm(source, book, data):
    p = ROOT / 'data' / 'commentary' / source / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    """Merge new_data into existing without overwriting present entries."""
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

CHRON1 = {
    "27": {
        "1": '<p>This verse introduces the entire rotation system with a triple administrative heading: <em>r&#257;&#702;&#353;&#234; h&#257;&#702;&#257;&#7687;&#244;&#7789;</em> (&ldquo;heads of the fathers&rdquo;) signals kinship-based leadership; <em>&#347;&#257;r&#234; h&#257;&#702;&#259;l&#257;p&#238;m w&#601;hamm&#275;&#702;&#244;&#7789;</em> (&ldquo;commanders of thousands and hundreds&rdquo;) signals military hierarchy; <em>hamm&#601;&#353;&#257;r&#601;&#7789;&#238;m &#702;et hammelek</em> (&ldquo;those serving the king&rdquo;) uses the verb <em>&#353;&#257;rat</em>, the same term for priestly and Levitical cultic service (see ch24&ndash;26). That the military-administrative system is described with the vocabulary of priestly service is characteristic of the Chronicler: covenant service pervades every domain of Israelite life, not only the sanctuary.</p>',
        "2": '<p><em>Y&#257;&#353;&#244;&#7687;&#702;&#257;m ben Zabd&#238;&#702;&#275;l</em> commands the first division for the first month with 24,000 men. The <em>maḥᵃl&#333;q&#244;t</em> (&ldquo;divisions/courses&rdquo;) system distributes 288,000 men across twelve months, ensuring that the full military capacity of Israel is maintained without massing armed power permanently in one place. The same principle governs the priestly and Levitical courses (ch24&ndash;25): institutional rotation is the Chronicler&rsquo;s model for sustainable and just administration.</p>',
        "3": '<p><em>mibb&#601;n&#234; Per&#233;&#7779;</em> (&ldquo;from the sons of Perez&rdquo;) &mdash; Jashobeam&rsquo;s lineage links the first military commander to the royal Judahite line from which David himself descended (2:4; Ruth 4:12, 18&ndash;22). The first slot in David&rsquo;s military rotation is held by someone from the messianic lineage, subtly grounding military organization within the larger narrative of covenant election running through Judah and its descendants.</p>',
        "4": '<p><em>mi&#353;neh</em> (&ldquo;second, deputy&rdquo;) &mdash; the second commander has a named officer Mikloth as his <em>mi&#353;neh</em>, a term drawn from the broader Hebrew administrative vocabulary for a second-in-command (cf. Esth 10:3 for Mordecai as second to the king). The Chronicler specifies the chain of command within each division, not just the commanding officer: accountability and succession are built into the structure.</p>',
        "5": '<p><em>B&#601;n&#257;y&#257;h&#251; ben Y&#601;h&#244;y&#257;d&#257;&#702; hakk&#333;h&#275;n</em> (&ldquo;Benaiah son of Jehoiada the priest&rdquo;) commands the third division. The assignment of a priest&rsquo;s son to military command &mdash; and his explicit identification by his priestly lineage &mdash; signals the interpenetration of cultic and martial leadership in the Davidic administration. The same Benaiah appears in the Solomonic succession narrative (1 Kgs 1&ndash;2) as the military executor of David&rsquo;s final instructions, making him a pivot figure between the two reigns.</p>',
        "6": '<p><em>h&#251;&#702; B&#601;n&#257;y&#257;h&#251; haggib&#244;r bi&#353;l&#333;&#353;&#238;m w&#601;&#702;al ha&#353;l&#333;&#353;&#238;m</em> (&ldquo;this was Benaiah the mighty man among the thirty and above the thirty&rdquo;) &mdash; the catalog formula from 11:25 is embedded here, connecting the administrative record to the heroic roster. <em>ûmaḥl&#251;qt&#244; &#702;Amm&#238;z&#257;&#7687;&#257;&#7687; b&#601;n&#244;</em> (&ldquo;his division under his son Ammizabad&rdquo;) &mdash; son succeeds father; the division-level command has dynastic continuity, just as the priesthood and the monarchy do.</p>',
        "7": '<p><em>&#702;&#259;&#347;&#257;h&#275;&#702;l &#702;&#259;ḥî Y&#244;&#702;&#257;&#7687;</em> (&ldquo;Asahel brother of Joab&rdquo;) &mdash; Asahel died early in David&rsquo;s career pursuing Abner (2 Sam 2:23), yet his son Zebadiah holds his place in the mature administrative roster. The system preserves family-unit command across generations: a man&rsquo;s military legacy survives his death through his lineage, giving the entire institution a longer memory than any individual&rsquo;s life.</p>',
        "8": '<p><em>&#352;amhût hayyizr&#257;ḥ</em> (&ldquo;Shamhuth the Izrahite&rdquo;) &mdash; fifth month. The term <em>yizr&#257;ḥ&#238;</em> may be a variant spelling of <em>zer&#257;ḥ&#238;</em> (Zerahite), connecting this commander to Zerah son of Judah (2:4, 6). The alternation of commanders from different Judahite sub-clans distributes military prestige across the families of the covenant tribe, preventing the concentration of military honor in a single house within Judah.</p>',
        "9": '<p><em>&#702;&#206;r&#257;&#702; ben &#702;Iqqe&#353; hatt&#601;q&#244;&#702;&#238;</em> (&ldquo;Ira son of Ikkesh the Tekoite&rdquo;) &mdash; sixth month. Tekoa, a Judahite town in the southern hills, later became the hometown of Amos (Amos 1:1) and the source of the &ldquo;wise woman&rdquo; whom Joab sent to David (2 Sam 14:2). Its presence in the military roster shows that southern Judean communities were fully integrated into the Davidic administrative system from its inception.</p>',
        "10": '<p><em>&#7716;ele&#7779; happ&#601;l&#244;n&#238;</em> (&ldquo;Helez the Pelonite&rdquo;) &mdash; seventh month; <em>mibb&#601;n&#234; &#702;Eprayim</em> (&ldquo;from the sons of Ephraim&rdquo;). A northern tribe provides one of the twelve commanders, explicitly identified by tribal affiliation. The Chronicler&rsquo;s pan-Israelite vision of the united kingdom is enacted here: military leadership is not a monopoly of Judah but is distributed across the covenant community, including the dominant northern tribe.</p>',
        "11": '<p><em>Sibb&#601;kay ha&#7717;&#251;&#353;&#257;t&#238;</em> (&ldquo;Sibbecai the Hushathite&rdquo;) &mdash; eighth month; <em>lazzar&#7717;&#238;</em> (&ldquo;of the Zerahite line&rdquo;). Sibbecai appears in the battle narrative against the Philistine giant at Gezer (20:4), where he killed Sippai. The inclusion of a hero from the Philistine giant wars in the administrative rotation integrates military valor into institutional order: the exceptional becomes the routine through structured service.</p>',
        "12": '<p><em>&#702;&#259;&#7687;î&#702;ezer h&#257;&#702;ann&#601;t&#244;t&#238;</em> (&ldquo;Abiezer the Anetothite&rdquo;) &mdash; ninth month; <em>labiny&#257;m&#238;n&#238;</em> (&ldquo;from Benjamin&rdquo;). Anathoth was a Levitical city in Benjamin (Josh 21:18) and later the hometown of Jeremiah (Jer 1:1). The presence of an Anathothite in David&rsquo;s military roster places this prophetically significant location within the Davidic covenant structure from the beginning.</p>',
        "13": '<p><em>Maher&#257;y hanneto&#7761;&#257;t&#238;</em> (&ldquo;Maharai the Netophathite&rdquo;) &mdash; tenth month; <em>lazzar&#7717;&#238;</em> (&ldquo;Zerahite line&rdquo;). Netophah was a Judahite town near Bethlehem (2:54; Neh 7:26; Ezra 2:22). Its appearance here and in the post-exilic return lists creates a chronological bridge: the families in David&rsquo;s administration are the same families whose descendants return from exile, demonstrating institutional continuity across the catastrophe of the exile.</p>',
        "14": '<p><em>B&#601;n&#257;y&#257;h happirrᵉ&#702;&#257;t&#244;n&#238;</em> (&ldquo;Benaiah the Pirathonite&rdquo;) &mdash; eleventh month; <em>mibb&#601;n&#234; &#702;Eprayim</em> (&ldquo;from the sons of Ephraim&rdquo;). A second Ephraimite division commander (cf. v10) confirms that northern tribal representation in the military system is substantive, not merely a single token. The repeated Ephraimite presence makes the inclusion of the dominant northern tribe a structural feature, not an exception.</p>',
        "15": '<p><em>&#7716;eld&#257;y hanneto&#7761;&#257;t&#238;</em> (&ldquo;Heldai the Netophathite&rdquo;) &mdash; twelfth month; <em>l&#601;&#702;otn&#238;&#702;&#275;l</em> (&ldquo;from Othniel&rdquo;). Othniel was the first judge of Israel (Judg 3:9&ndash;11), a Calebite-Judahite deliverer who set the pattern for the entire era of judges. The final month&rsquo;s commander derives his lineage from Israel&rsquo;s inaugural deliverer, giving the twelve-month military roster a narrative arc that sweeps from the judges through the Davidic monarchy &mdash; covenant history encoded in administrative structure.</p>',
        "16": '<p>The tribal officer list opens with Reuben (<em>&#702;&#277;lî&#702;ezer ben Ziḵrî</em>) and Simeon (<em>&#352;&#601;pa&#7789;y&#257;h ben Ma&#702;&#259;ḵ&#257;h</em>). That Reuben appears &mdash; despite having forfeited the birthright (5:1&ndash;2) &mdash; reflects the Chronicler&rsquo;s principle that administrative recognition outlasts internal re-ranking; all tribes retain named representation within the covenant community regardless of their hierarchical standing. The <em>n&#257;g&#238;d</em> or <em>&#347;ar</em> title for each tribal officer marks them as the king&rsquo;s commissioned agents within their tribal domains.</p>',
        "17": '<p>For the Levites: <em>&#7716;&#259;&#353;aḇy&#257;h ben Q&#601;m&#251;&#702;&#275;l</em>; for Aaron: <em>&#7778;&#257;d&#244;q</em>. The Levites and Aaronides appear in the tribal list alongside secular tribes rather than in a separate cultic category, showing that the Chronicler treats priestly administration as continuous with civil administration. Zadok, who will oversee the ark&rsquo;s final installation (1 Kgs 8:4) and whose line will define legitimate priesthood through Ezekiel&rsquo;s vision (Ezek 44:15&ndash;16), already holds the Aaronide slot in David&rsquo;s administrative system.</p>',
        "18": '<p>For Judah: <em>&#702;&#277;lîh&#251; m&#275;&#702;aḥê D&#257;w&#238;&#7687;</em> (&ldquo;Elihu, one of David&rsquo;s brothers&rdquo;). The royal tribe&rsquo;s tribal officer is David&rsquo;s own brother &mdash; the royal family administers itself through its own kinship. This Elihu may be the brother called Eliab or a variant name for one of Jesse&rsquo;s sons (1 Sam 16:6). For Issachar: <em>&#702;Omrî ben Mîḵ&#257;&#702;&#275;l</em>. The assignment of a competent officer to each tribe means that David&rsquo;s authority extends through personal or trusted intermediaries to every part of the covenant community.</p>',
        "19": '<p>For Zebulun: <em>Yi&#353;maʿy&#257;h ben &#702;Oḇady&#257;h</em>; for Naphtali: <em>Y&#601;rîm&#244;t ben &#702;Azrî&#702;&#275;l</em>. These northern tribes &mdash; Zebulun and Naphtali &mdash; are the ones Isaiah would later name as the first to suffer Assyrian conquest and the first to see the &ldquo;great light&rdquo; (Isa 9:1&ndash;2; cf. Matt 4:15&ndash;16). Their presence in David&rsquo;s administrative system underscores that the entire covenant community was once integrated before the fracture of the exile.</p>',
        "20": '<p>For Ephraim: <em>H&#244;&#353;&#275;a&#702; ben &#702;Azazy&#257;h&#251;</em>; for the half-tribe of Manasseh: <em>Y&#244;&#702;&#275;l ben P&#601;d&#257;y&#257;h&#251;</em>. That Ephraim receives a civil tribal officer in addition to its military division commanders (vv10, 14) confirms the tribe&rsquo;s importance in David&rsquo;s administrative imagination. The northern tribes were never merely subordinate appendages in the Chronicler&rsquo;s vision of the united kingdom; they are full participants with their own administrative infrastructure.</p>',
        "21": '<p>For Gilead-Manasseh (the eastern half): <em>&#702;Idd&#244; ben Z&#601;ḵary&#257;h&#251;</em>; for Benjamin: <em>Y&#257;&#702;&#259;s&#238;&#702;&#275;l ben &#702;Abn&#275;r</em>. The inclusion of the Transjordanian Manassite half-tribe means that tribes living east of the Jordan &mdash; the most geographically vulnerable to absorption by neighboring powers &mdash; have formal administrative representation in the royal system. The covenant community is defined by covenant affiliation, not by geography.</p>',
        "22": '<p>For Dan: <em>&#702;Azaral ben Y&#601;r&#244;ḥ&#257;m</em>. <em>&#702;&#275;lleh &#347;&#257;r&#234; &#353;iḇ&#7789;&#234; yiśr&#257;&#702;&#275;l</em> (&ldquo;these were the princes of the tribes of Israel&rdquo;) &mdash; the concluding summary frames the entire tribal officer list as a comprehensive covenant register. Dan, despite its later associations with northern apostasy (Jeroboam&rsquo;s golden calves at Dan; Judg 18), is included without stigma. The Chronicler records the Davidic administration as it was at its finest moment, before the fractures that history would bring.</p>',
        "24": '<p><em>l&#333;&#702; &#353;ill&#275;m</em> (&ldquo;did not complete it&rdquo;) &mdash; the verb <em>&#353;ālem</em> also means &ldquo;to make whole, to pay, to make peace&rdquo;; the census was never &ldquo;paid off&rdquo; or reconciled. The result was <em>qe&#7779;ep</em> (&ldquo;wrath&rdquo;) on Israel &mdash; the technical term for divine anger at covenant violation. <em>w&#601;l&#333;&#702; &#702;&#257;l&#257;h hammisp&#257;r b&#601;s&#275;per dibr&#234; hayy&#257;m&#238;m lammelek D&#257;w&#238;&#7687;</em> (&ldquo;and the number did not come up into the king&rsquo;s book of chronicles&rdquo;) &mdash; the incomplete census was deliberately excluded from the official administrative record. The Chronicler records the non-recording, making the gap in the record itself a theological statement: what is tainted by sin does not enter the royal archives.</p>',
        "25": '<p><em>&#702;Azm&#257;we&#7789; ben &#702;&#259;d&#238;&#702;&#275;l</em> &mdash; over the royal storehouses; <em>Y&#601;h&#244;n&#257;&#7789;&#257;n ben &#702;Uzzy&#257;y&#251;</em> &mdash; over the country storehouses in cities, villages, and towers. The distinction between central court storage and distributed provincial storage reflects sophisticated administrative awareness of supply logistics. The term <em>&#702;&#333;&#7789;&#257;r</em> (&ldquo;storehouse, treasury&rdquo;) appears throughout the Psalms and wisdom literature as the vehicle of YHWH&rsquo;s providential abundance (cf. Ps 135:7; Prov 8:21; Deut 28:12).</p>',
        "26": '<p><em>&#702;Ezrî ben K&#601;l&#251;&#7687;</em> &mdash; over the agricultural workers who worked the ground (<em>ʿ&#257;&#7687;&#257;m&#257;h</em>). The verb <em>&#702;&#257;&#7687;a&#7687;</em> (&ldquo;to work, to serve&rdquo;) shares its root with <em>&#702;&#275;&#7687;&#275;&#7687;</em> (&ldquo;servant&rdquo;) and <em>&#702;&#259;&#7687;&#244;d&#257;h</em> (&ldquo;service, worship&rdquo;). The organization of agricultural labor under royal stewardship uses the same vocabulary as the organization of priestly service: working the land is a form of covenant service to YHWH, who gave the land and its fertility as a covenant blessing.</p>',
        "27": '<p><em>&#352;im&#702;î h&#257;r&#257;m&#257;t&#238;</em> &mdash; over the vineyards; <em>Zabd&#238; ha&#353;&#353;ip&#697;m&#238;</em> &mdash; over wine production and the wine cellars. The vineyard (<em>kerem</em>) as a covenant image pervades the prophetic tradition: Israel as YHWH&rsquo;s vineyard (Isa 5:1&ndash;7; Ps 80:8&ndash;16). The royal administration of vineyards thus operates within an already theologically charged agricultural vocabulary. That the wine cellar steward has a specific title and name demonstrates the institutional weight given to what might seem like a minor administrative role.</p>',
        "28": '<p><em>Ba&#702;al &#7716;&#257;n&#257;n hagg&#601;d&#275;r&#238;</em> &mdash; over olive trees and sycamore trees in the Shephelah (<em>&#353;&#601;p&#275;l&#257;h</em>, &ldquo;the lowland&rdquo;); <em>Y&#244;&#702;&#257;&#353;</em> &mdash; over the oil stores. The olive tree is a central symbol of covenant blessing in Deuteronomy (8:8; 28:40) and the prophets (Zech 4:3; Hab 3:17). The Shephelah, contested between Judah and the Philistines, was politically sensitive territory; its administrative officer represents both agricultural and strategic concerns. Royal control of olive production means control of Israel&rsquo;s primary cooking fat, lamp fuel, and ritual anointing oil.</p>',
        "29": '<p><em>&#352;i&#7789;ray ha&#353;&#353;&#257;r&#244;n&#238;</em> &mdash; over herds in the Sharon plain; <em>&#352;&#257;p&#257;&#7789; ben &#702;Adlay</em> &mdash; over valley herds. The Sharon plain, Israel&rsquo;s most fertile coastal region, was proverbial for its beauty and productivity (Isa 35:2; 65:10; Song 2:1). Royal management of Sharon herds represents oversight of Israel&rsquo;s prime pastureland. The valley herds would have been managed in the Jezreel and other lowland areas, similarly valuable for livestock production.</p>',
        "30": '<p><em>&#702;O&#7687;&#238;l hayyišm&#601;&#702;&#275;l&#238;</em> (&ldquo;Obil the Ishmaelite&rdquo;) &mdash; over the camels. The appointment of an Ishmaelite as chief camel handler is culturally precise: the Ishmaelites were renowned as camel traders in the ancient Near East (Gen 37:25; Judg 8:24). The royal administration employs non-Israelite expertise where expertise exists &mdash; the covenant community&rsquo;s stewardship of creation includes wisdom that crosses ethnic boundaries. <em>Y&#601;ḥd&#601;y&#257;h&#251; hamm&#275;r&#244;n&#244;t&#238;</em> &mdash; over the donkeys, the primary pack animal for agricultural and commercial transport.</p>',
        "31": '<p><em>Y&#257;z&#238;z hahag&#601;r&#238;</em> (&ldquo;Jaziz the Hagerite&rdquo;) &mdash; over the flocks. The Hagrites were a Transjordanian group against whom Reuben fought and prevailed (5:10, 18&ndash;22); the incorporation of a Hagrite officer into the royal administration transforms a former opponent into a royal servant &mdash; a miniature of the Davidic vision in which surrounding peoples come under Israel&rsquo;s administrative umbrella. <em>kol &#702;&#275;lleh &#347;&#257;r&#234; h&#257;r&#601;ḵ&#251;&#353;</em> (&ldquo;all these were princes of the property&rdquo;) &mdash; the comprehensive stewardship language (<em>r&#601;ḵ&#251;&#353;</em>, &ldquo;property, possessions&rdquo;) frames the entire list as an exercise of delegated dominion over the covenant land&rsquo;s resources.</p>',
        "32": '<p><em>Y&#601;h&#244;n&#257;&#7789;&#257;n d&#244;d D&#257;w&#238;&#7687;</em> (&ldquo;Jonathan the uncle of David&rdquo;) &mdash; a counselor; <em>sofer mevin</em> (&ldquo;a discerning scribe&rdquo;). The combination of scribal skill and discernment (<em>mevin</em>) for a royal advisor anticipates the wisdom tradition that will characterize Solomon&rsquo;s court. <em>Y&#601;hî&#702;&#275;l ben &#7716;aḵm&#244;n&#238;</em> was with the king&rsquo;s sons &mdash; the role of tutor or companion to the royal princes is an important court function; the next generation of Davidic leadership must be formed under wise guidance from within the court circle.</p>',
        "33": '<p><em>&#702;&#270;î&#7789;&#333;p&#275;l y&#244;&#702;&#275;&#7779; lammelek</em> (&ldquo;Ahithophel, the king&rsquo;s counselor&rdquo;) &mdash; listed without any mention of his subsequent betrayal (2 Sam 15&ndash;17); the Chronicler records the administrative structure as it stood before the narrative complications. <em>&#7716;&#251;&#353;ay h&#257;&#702;arka&#702;î r&#275;a&#702; hammelek</em> (&ldquo;Hushai the Archite, the king&rsquo;s friend&rdquo;) &mdash; <em>r&#275;a&#702;</em> (&ldquo;friend, companion&rdquo;) is a specific court title in ANE monarchies (cf. the Egyptian &ldquo;King&rsquo;s Friend&rdquo;), not merely an affectionate description. Hushai&rsquo;s counter-intelligence role against Ahithophel in 2 Sam 15&ndash;17 is the most dramatic episode in the history of this court position.</p>',
        "34": '<p>After Ahithophel, Jehoiada son of Benaiah and Abiathar served as counselors. <em>Y&#244;&#702;&#257;&#7687; &#347;ar &#7779;&#601;&#7687;&#257;&#702; hammelek</em> (&ldquo;Joab was the commander of the king&rsquo;s army&rdquo;) &mdash; the chapter closes with Joab, whose military command was the practical instrument through which everything else in this chapter operated. The final word of ch27 belongs to the man whose relationship with David was always complex yet indispensable: no administrative elegance could function without the force Joab commanded. The Chronicler acknowledges this without apology or comment.</p>'
    },
    "28": {
        "1": '<p><em>D&#257;w&#238;&#7687; hiqhîl</em> (&ldquo;David assembled&rdquo;) &mdash; the Hiphil of <em>q&#257;hal</em> (to assemble), the root of <em>q&#257;h&#257;l</em> (&ldquo;assembly, congregation&rdquo;). The comprehensive list of those summoned &mdash; tribal commanders, military division officers, stewards, royal sons, court officials, and mighty men &mdash; encapsulates the entire administrative structure of chs24&ndash;27. David convenes everything he has organized in a single final assembly; the bureaucratic investment of the preceding chapters exists for this moment of covenant transfer.</p>',
        "2": '<p><em>wayyāqom D&#257;w&#238;&#7687; hammelek &#702;al ragl&#257;yw</em> (&ldquo;King David stood on his feet&rdquo;) &mdash; the phrase implies effort from one who is old and enfeebled (29:1); David&rsquo;s standing is an act of royal dignity in the face of physical decline. <em>b&#234;t m&#257;n&#244;aḥ</em> (&ldquo;house of rest&rdquo;) &mdash; the temple envisioned as the permanent resting place (<em>m&#257;n&#244;aḥ</em>) for the ark; <em>m&#257;n&#244;aḥ</em> shares its root with <em>m&#601;n&#251;ḥ&#257;h</em> (&ldquo;rest&rdquo;), the word underlying Solomon&rsquo;s name in 22:9. The ark needs rest; Israel needs rest; the temple is the covenant community&rsquo;s rest made architectural.</p>',
        "3": '<p><em>&#702;att&#257;h l&#333;&#702; ṯiḇneh l&#238; habbayi&#7789;</em> (&ldquo;you shall not build me the house&rdquo;) &mdash; YHWH&rsquo;s direct refusal is stated plainly, without softening. <em>kî &#702;î&#353; milḥ&#257;m&#244;&#7789; &#702;att&#257;h w&#601;d&#257;m&#238;m &#353;&#257;paḵ&#8222;&#257;</em> (&ldquo;for you are a man of wars and have shed blood&rdquo;) &mdash; the Chronicler makes explicit what 2 Sam 7 left implicit: blood-guilt disqualifies a builder of the sanctuary. The principle is cultic: the holy space requires a builder with unstained hands (cf. Exod 20:25 on uncut stones for the altar; Num 19:11&ndash;22 on corpse impurity). David&rsquo;s wars were YHWH-commanded; yet the holiness logic of the sanctuary demands the distinction.</p>',
        "4": '<p><em>wayyiḇḥar YHWH &#702;&#283;l&#333;h&#234; yiśr&#257;&#702;&#275;l b&#238;</em> (&ldquo;yet YHWH the God of Israel chose me&rdquo;) &mdash; David pivots from prohibition to election. The verb <em>b&#257;ḥar</em> (&ldquo;chose&rdquo;) is the technical term of covenant-election theology (Deut 7:6; 14:2; Isa 41:8). The election sequence David narrates narrows: from all Israel&rsquo;s house &rarr; from all Judah&rsquo;s house &rarr; from Jesse&rsquo;s sons &rarr; David himself. This narrowing election mirrors the Genesis pattern (Abr &rarr; Isaac &rarr; Jacob &rarr; Judah &rarr; Perez &rarr; David): YHWH&rsquo;s purpose concentrates through increasingly specific choices.</p>',
        "5": '<p><em>kiss&#275;&#702; malkût YHWH &#702;al yiśr&#257;&#702;&#275;l</em> (&ldquo;the throne of the kingdom of YHWH over Israel&rdquo;) &mdash; David does not say &ldquo;my throne&rdquo; or &ldquo;the throne of Israel&rdquo; but <em>YHWH&rsquo;s throne</em>. The Davidic monarchy is explicitly identified as the earthly instantiation of divine kingship &mdash; a theme that appears again in 29:23 (&ldquo;Solomon sat on the throne of YHWH&rdquo;). This high claim about royal theology provides the Christological foundation: the one who inherits YHWH&rsquo;s throne permanently (Rev 3:21; 22:1) is the one in whom the Davidic promise reaches its ultimate referent.</p>',
        "6": '<p><em>&#352;&#601;l&#333;m&#333;h ḇin&#601;ḵ&#257; h&#251;&#702; yiḇneh b&#234;tî</em> (&ldquo;Solomon your son &mdash; he will build my house&rdquo;) &mdash; the emphatic <em>h&#251;&#702;</em> (&ldquo;he, himself&rdquo;) singles out Solomon as the uniquely designated builder. <em>kî ḇ&#257;ḥartî ḇô lî l&#601;ḇ&#275;n</em> (&ldquo;for I have chosen him to be my son&rdquo;) &mdash; the divine adoption formula (cf. Ps 2:7) is here given its historical application: David reports YHWH&rsquo;s completed choice (perfect <em>b&#257;ḥartî</em>). The son-of-God status is simultaneously a royal designation and a pattern pointing beyond its immediate holder to the one in whom divine sonship is not a granted title but an eternal reality.</p>',
        "7": '<p><em>wahᵃḵîn&#244;tî &#702;et malk&#251;t&#244; &#702;ad l&#601;&#702;&#244;l&#257;m</em> (&ldquo;I will establish his kingdom forever&rdquo;) &mdash; <em>&#702;im yeḥ&#601;zaq la&#702;&#259;&#347;&#244;t mi&#7779;w&#244;tay</em> (&ldquo;if he remains firm to do my commandments&rdquo;). The eternal promise (<em>&#702;ad l&#601;&#702;&#244;l&#257;m</em>) is coupled with a conditional clause (<em>&#702;im</em>). The Chronicler holds both: the Davidic promise is unconditional in its ultimate scope (2 Sam 7:16; Ps 89:28&ndash;37) but conditional in its specific historical instantiation through any particular Davidic king. The resolution the Chronicler implies: the dynasty&rsquo;s eternal dimension survives Solomon&rsquo;s failure through a future Davidic heir who will keep the commandments perfectly.</p>',
        "8": '<p><em>&#353;imr&#251; w&#601;diršû kol mi&#7779;w&#244;t YHWH &#702;&#283;l&#333;h&#234;ḵem</em> (&ldquo;keep and seek all the commandments of YHWH your God&rdquo;) &mdash; the pairing of <em>&#353;&#257;mar</em> (&ldquo;keep, guard&rdquo;) and <em>d&#257;ra&#353;</em> (&ldquo;seek, inquire&rdquo;) is the Chronicler&rsquo;s signature vocabulary for covenant faithfulness: keeping what is known and actively seeking what is not yet explicit. <em>l&#601;ma&#702;an tîr&#601;&#353;&#251; &#702;et h&#257;&#702;&#257;re&#7779;</em> (&ldquo;so that you may possess the land&rdquo;) and pass it as an inheritance to your sons forever &mdash; land-possession remains the sign of covenant blessing, and obedience remains its condition. The Abrahamic promise is still operative within the Davidic order.</p>',
        "10": '<p><em>da&#702; kî YHWH b&#257;ḥar b&#601;ḵ&#257;</em> (&ldquo;know that YHWH has chosen you&rdquo;) &mdash; the command to <em>know</em> (<em>d&#257;&#702;</em>) one&rsquo;s election precedes the command to act; identity grounds vocation. <em>liḇn&#244;t bayit lammiqdā&#353;</em> (&ldquo;to build a house for the sanctuary&rdquo;) &mdash; <em>hammiqdā&#353;</em> (&ldquo;the sanctuary&rdquo;) is the abstract noun from <em>q&#257;da&#353;</em> (&ldquo;to be holy&rdquo;); the building project is the spatial instantiation of holiness. <em>ḥ&#259;zaq wa&#702;&#259;&#347;&#275;h</em> (&ldquo;be strong and do it&rdquo;) &mdash; the shortest form of the Mosaic commissioning formula, which receives its fullest expression in v20.</p>',
        "11": '<p>David gives Solomon the <em>tabnît</em> &mdash; a word meaning &ldquo;pattern, plan, model, likeness&rdquo; (used in Exod 25:9, 40 for the heavenly tabernacle pattern shown to Moses; Deut 4:16&ndash;18 for idolatrous images; Ps 144:12 for the form of children). The architectural <em>tabnît</em> includes the <em>&#702;&#251;l&#257;m</em> (portico), its <em>b&#257;tt&#238;m</em> (house-chambers), <em>g&#601;n&#257;z&#257;yw</em> (storerooms), <em>&#702;aly&#244;t&#257;yw</em> (upper rooms), <em>h&#259;d&#257;r&#257;yw happin&#238;m&#238;m</em> (inner chambers), and <em>q&#333;de&#353; haqqo&#7723;&#257;&#353;&#238;m</em> (Holy of Holies). The enumeration moves from outer to inner, mapping the graduated approach from public to sacred that structures the entire sanctuary system.</p>',
        "12": '<p><em>hakkōl b&#257;r&#251;aḥ &#702;imm&#244;</em> (&ldquo;all of it by the Spirit with him&rdquo;) &mdash; the architectural plan came through the divine Spirit (<em>r&#251;aḥ</em>). The same Spirit that hovered over creation&rsquo;s waters (Gen 1:2), equipped Bezalel for tabernacle craftsmanship (Exod 31:3), rested on Israel&rsquo;s leaders and prophets, now gives David the temple&rsquo;s design. The courts of the LORD&rsquo;s house, the surrounding chambers, the treasury storerooms, the upper rooms and inner rooms, the place for the ark &mdash; all of this was Spirit-given, not architecturally devised. The temple is a Spirit-authored space.</p>',
        "13": '<p><em>maḥᵃlōq&#244;t hakk&#333;han&#238;m w&#601;hall&#601;wiyy&#238;m</em> (&ldquo;the divisions of priests and Levites&rdquo;) are included in the <em>tabnît</em> &mdash; the architectural plan encompasses the personnel system. The same term <em>maḥᵃlōq&#244;t</em> (&ldquo;divisions, courses&rdquo;) used for the military rotation in ch27 now describes the priestly rotation; military and cultic administration are organized by the same structural principle. <em>ḥᵃluqqat h&#257;&#702;ᵃḇ&#244;d&#257;h</em> (&ldquo;the division of service&rdquo;) means the blueprint David gives is not just for a building but for a complete institutional system &mdash; architecture and personnel are a single integrated plan.</p>',
        "14": '<p>The weights (<em>mi&#353;q&#257;l</em>) of gold for the gold vessels and silver for the silver vessels are specified <em>l&#601;ḵol k&#601;l&#234; &#702;&#259;ḇ&#244;d&#257;h w&#257;&#702;&#259;ḇ&#244;d&#257;h</em> (&ldquo;for every vessel of each kind of service&rdquo;). The precision of weights for sacred objects follows the pattern of Moses at Sinai, where every tabernacle vessel was specified in exact weight and material (Exod 25&ndash;31). That David can hand Solomon a plan with specific weights means the heavenly prototype has been translated into concrete provisioning &mdash; the divine instruction has already been worked out in material terms.</p>',
        "15": '<p>Gold for the lampstands (<em>m&#601;n&#244;r&#244;t</em>) and their lamps, with the specified weight of each lampstand and each lamp; silver for the silver lampstands by weight. The <em>m&#601;n&#244;r&#257;h</em> (&ldquo;lampstand&rdquo;) was the symbol of YHWH&rsquo;s light in the tabernacle (Exod 25:31&ndash;40; Num 8:1&ndash;4). Zechariah&rsquo;s vision of the golden lampstand (Zech 4:2&ndash;10) identifies it with YHWH&rsquo;s eyes scanning the whole earth. That David&rsquo;s plan specifies not one but multiple lampstands for the temple represents the expansion of divine light into the new and larger space of covenant dwelling.</p>',
        "16": '<p>Gold for the showbread tables (<em>&#353;ulḥān</em> plural <em>&#353;ulḥān&#244;t</em>) and silver for the silver tables. The <em>&#353;ulḥān</em> (&ldquo;table&rdquo;) carried the <em>leḥem p&#257;n&#238;m</em> (&ldquo;bread of the face/presence&rdquo;) &mdash; twelve loaves renewed weekly, representing the twelve tribes permanently before YHWH (Lev 24:5&ndash;9). The temple&rsquo;s showbread table continues a practice established in the tabernacle (Exod 25:23&ndash;30): the covenant community is permanently presented as an offering before the divine Presence, tribe by tribe, loaf by loaf.</p>',
        "17": '<p>Gold for the forks (<em>mizl&#257;g&#244;t</em>), sprinkling bowls (<em>mizr&#257;q&#244;t</em>), and cups (<em>q&#600;&#353;&#257;w&#244;t</em>); and the weight of each golden bowl and silver bowl. Every implement of the priestly liturgical system is specified by weight and material. The <em>mizr&#257;q</em> (&ldquo;sprinkling bowl&rdquo;) was used for the presentation and sprinkling of sacrificial blood &mdash; the central act of covenant atonement. That its weight and material are divinely specified confirms that the atonement mechanism itself is a heavenly institution, not a human invention.</p>',
        "18": '<p>Refined gold for the incense altar (<em>mizbaḥ haqq&#601;&#7789;&#244;ret</em>) by weight; and gold for the model (<em>tabnît</em>) of the chariot-throne of the cherubim (<em>k&#601;r&#251;&#7687;&#238;m p&#244;r&#601;&#347;&#234; k&#601;n&#257;payim</em>, &ldquo;cherubim spreading their wings&rdquo;) that covered the ark. The cherub-throne is not merely an architectural element but a cosmic image: YHWH enthroned above the cherubim is a royal title throughout the Psalms and prophets (Ps 80:1; 99:1; 2 Kgs 19:15; Isa 37:16). The final element of the <em>tabnît</em> that David transmits to Solomon is not a floor plan but the image of the divine throne &mdash; the ultimate purpose of the entire building is to be the earthly footstool of the heavenly King.</p>',
        "20": '<p><em>ḥ&#259;zaq w&#601;&#702;&#275;m&#257;&#7779; wa&#702;&#259;&#347;&#275;h</em> (&ldquo;be strong and courageous and do it&rdquo;) &mdash; the fullest form of the Mosaic commissioning formula, traceable through Deut 31:6&ndash;7 (Moses to Israel and Joshua), Josh 1:6, 9 (YHWH to Joshua), and now David to Solomon. The three-verb sequence (strength + courage + action) is the complete commissioning structure. <em>&#702;al tîr&#257;&#702; w&#601;&#702;al t&#275;ḥāt</em> (&ldquo;do not fear and do not be dismayed&rdquo;) &mdash; the prohibition of <em>y&#257;r&#275;&#702;</em> (fear) and <em>ḥātat</em> (dismay) covers both the emotional and volitional domains. <em>kî YHWH &#702;&#283;l&#333;h&#238;m &#702;&#283;l&#333;hay &#702;imm&#257;ḵ&#257;</em> (&ldquo;for YHWH God, my God, is with you&rdquo;) &mdash; the covenant-presence formula (<em>ʿimm&#257;ḵ&#257;</em>) transmitted through David to Solomon: the presence that was with Moses (Exod 3:12), promised to Joshua (Josh 1:5), is now spoken by David&rsquo;s lips as a gift to his son. <em>l&#333;&#702; yarpeḵ&#257; w&#601;l&#333;&#702; ya&#702;az&#7687;ekkā</em> (&ldquo;he will not let you down and will not forsake you&rdquo;) &mdash; the double negated abandonment verb, the covenant&rsquo;s ultimate promise.</p>',
        "21": '<p>The final verse describes total preparedness: the priestly and Levitical courses (<em>maḥᵃlōq&#244;t</em>) are ready for every act of service; all willing and skilled craftsmen (<em>n&#257;d&#238;&#7687; b&#601;ḵol melaḵ&#257;h</em>) for every aspect of the work. <em>w&#601;ḵol h&#257;&#702;&#257;m l&#601;ḵol d&#601;ḇ&#257;reḵ&#257;</em> (&ldquo;and all the people are at your every word&rdquo;) &mdash; Solomon has everything: divinely given plan, organized personnel, accumulated materials (22:14; 29:2&ndash;5), and the entire nation&rsquo;s obedience. The chapter ends not with a command but with a gift: everything necessary for the building is already in place. The only remaining question is whether Solomon will execute it &mdash; and the answer to that question will define the entire subsequent history of the covenant people.</p>'
    }
}

def main():
    existing = load_comm('mkt-original', '1chronicles')
    merge_comm(existing, CHRON1)
    save_comm('mkt-original', '1chronicles', existing)
    for ch in ['27', '28']:
        print(f'  ch{ch}: {len(existing.get(ch, {}))} verses')

if __name__ == '__main__':
    main()
