"""
MKT Original Commentary — 2 Kings chapters 21–23
Run: python3 scripts/zc-original-2kings-21-23.py

Ch21: Manasseh — 55-year reign; worst apostasy in Judah's history; prophetic oracle of doom
Ch22: Josiah discovers the Book of the Law; Huldah's oracle — inevitable judgment, personal peace
Ch23: Josiah's systematic reform; Passover; nevertheless-clause; Megiddo; rapid post-Josiah collapse

Key translation decisions:
- 'detestable practices' (21:2): tôʿăḇōt — the standard term for abominations; retained as 'detestable'
- 'measuring line' / 'plumb line' (21:13): qaw / mišqelet — architectural inspection terms used for demolition
- 'Book of the Law' (22:8): sēfer hattôrāh — identified with core Deuteronomy in critical scholarship
- 'humbled himself' (22:19): wayyikkānēʿ — same root as 1 Kgs 21:29 (Ahab); key repentance term
- 'with all his heart, soul, and might' (23:25): bəkol-libbô, napšô, mᵉʾōḏô — Shema (Deut 6:5) language
- 'Topheth' (23:10): tōpet — the fire-altar site in the Valley of Ben-Hinnom (gê ben-hinnōm → Gehenna)
"""

import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

def load_comm(layer, book):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    return json.loads(p.read_text()) if p.exists() else {}

def save_comm(layer, book, data):
    p = ROOT / 'data' / 'commentary' / layer / f'{book}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=None))
    print(f'  wrote {p.relative_to(ROOT)}')

def merge_comm(existing, new_data):
    for ch, verses in new_data.items():
        if ch not in existing:
            existing[ch] = {}
        for v, html in verses.items():
            if v not in existing[ch]:
                existing[ch][v] = html

ORIGINAL = {
  "21": {
    "1": "<p>Manasseh was twelve years old at his accession and reigned fifty-five years — the longest reign in the Judean monarchy. The extreme length is theologically loaded: the Deuteronomistic History frames it as evidence that YHWH&rsquo;s patience is not indifference. <em>Ḥizqiyyāhû</em> (Hezekiah) and <em>Mᵉnaššeh</em> (Manasseh) are placed in immediate succession: the son of the most faithful Judean king becomes the most faithless. The name <em>Mᵉnaššeh</em> means &ldquo;one who causes to forget&rdquo; — a name the narrative validates, as he forgets everything his father restored.</p>",
    "2": "<p>&ldquo;He did what was evil in the sight of YHWH, following the <em>tôʿăḇōt</em> (detestable practices) of the nations YHWH had driven out.&rdquo; The <em>tôʿăḇôt</em> (singular <em>tôʿēḇāh</em>) is the standard Deuteronomic/Levitical term for cultic abomination — actions structurally incompatible with covenant holiness (Deut 12:31; 18:9-12; Lev 18:22-30). The comparison is inverted from the usual formula: normally Manasseh is judged against David; here he is measured against the Canaanites whom YHWH expelled. &ldquo;More evil than the nations YHWH had destroyed before Israel&rdquo; (v9) will sharpen this reversal. The one who held covenant land must not replicate the practices that made the previous occupants forfeit it.</p>",
    "3": "<p>Manasseh &ldquo;rebuilt the high places his father Hezekiah had demolished.&rdquo; The verb <em>bānāh</em> (built/rebuilt) echoes ironically against Hezekiah&rsquo;s <em>hēsîr</em> (removed) in 18:4. What Hezekiah tore down, Manasseh rebuilds; what Hezekiah threw out, Manasseh sets up. The pairing with &ldquo;as Ahab king of Israel had done&rdquo; is the Deuteronomistic History&rsquo;s harshest condemnation of a Judean king: he is measured not against the bad kings of Judah but against the worst of the northern dynasty. The <em>ʾăšērāh</em> pole returns — the cult object of the fertility goddess Asherah, the consort of El/Baal in Canaanite religion, whose presence in Judah was a direct violation of the first two commandments.</p>",
    "4": "<p>&ldquo;He built altars in the house of YHWH, of which YHWH had said, &lsquo;In Jerusalem I will put my Name.&rsquo;&rdquo; The phrase &ldquo;put my Name&rdquo; (<em>lāśûm šᵉmî</em>) is the Deuteronomic formula for YHWH&rsquo;s unique dwelling choice (Deut 12:5, 11, 21; 14:23-24; 1 Kgs 8:29). To erect pagan altars in the Name&rsquo;s specific dwelling is not merely syncretism but a direct assault on the covenantal address-point of YHWH&rsquo;s presence. The temple altars to Baal occupy the space consecrated to the Name.</p>",
    "5": "<p>&ldquo;In both courts of the house of YHWH he built altars to all the starry hosts.&rdquo; <em>Ṣeḇāʾ haššāmayim</em> — &ldquo;host of heaven/starry hosts&rdquo; — refers to the astral cult of Mesopotamian origin: worship of sun, moon, planets, and stars as deities or divine intermediaries. Deut 4:19 explicitly warns against being &ldquo;drawn away to bow down to them and worship them.&rdquo; Mesopotamian astral religion had penetrated the Levant through Assyrian cultural pressure during the 7th century; Manasseh&rsquo;s reign (697-642 BCE) coincided with the height of Neo-Assyrian dominance, and his astral cult may reflect political as well as religious conformity to the overlord.</p>",
    "6": "<p>The catalogue of Manasseh&rsquo;s abominations reaches its peak: &ldquo;He sacrificed his son in the fire (<em>heʿĕḇîr ʾet bᵉnô bāʾēš</em>), practiced divination (<em>ʿônēn</em>), sought omens (<em>niḥēš</em>), and consulted mediums (<em>ʾōḇôt</em>) and spiritists (<em>yiddᵉʿōnîm</em>).&rdquo; The verb <em>heʿĕḇîr bāʾēš</em> — &ldquo;passed through fire&rdquo; — is the standard idiom for child sacrifice to Molech (Lev 18:21; 20:2-5; Deut 18:10). <em>ʿōnēn</em> (cloud-reading/soothsaying), <em>nāḥaš</em> (divination by omens/serpents), <em>ʾōḇ</em> (medium/ghost-consulter), and <em>yiddᵉʿōnî</em> (spiritist/one with a familiar spirit) — this list precisely matches the prohibitions of Deut 18:10-11. Manasseh does not miss a single item on the Deuteronomic list of forbidden practices.</p>",
    "7": "<p>The carved Asherah pole (<em>pesel hāʾăšērāh</em>) is placed inside the temple itself — the holy of holies&rsquo; antechamber. The specific violation: Deut 16:21 explicitly prohibits planting an Asherah &ldquo;beside the altar of YHWH your God.&rdquo; The divine word quoted — &ldquo;In this house and in Jerusalem, which I have chosen out of all the tribes of Israel, I will put my Name forever&rdquo; — is the election formula at its most emphatic: &ldquo;forever&rdquo; (<em>lᵉʿôlām</em>). The permanence of YHWH&rsquo;s election is the standard against which Manasseh&rsquo;s desecration is measured. The idol stands in the place of the Name.</p>",
    "8": "<p>The conditional promise: &ldquo;I will no longer make Israel&rsquo;s feet wander from the land I gave their ancestors — only if they carefully observe everything I commanded them, all the law my servant Moses commanded.&rdquo; The <em>raq</em> (&ldquo;only if&rdquo;) introduces the condition; <em>šmr</em> in the infinitive absolute construction (<em>šāmᵉrû lāʿăśôt</em>) — &ldquo;diligently observing to do&rdquo; — expresses the intensity required. This conditional promise is quoted at the moment of Manasseh&rsquo;s maximum violation to make the contrast explicit: the promise existed; the condition was not met; the consequence will follow.</p>",
    "9": "<p>&ldquo;But they did not listen, and Manasseh led them astray (<em>wayyatʿēm</em>) so that they did more evil than the nations YHWH had destroyed before Israel.&rdquo; <em>Tāʿāh</em> (causative: to cause to err/wander) is the same root used of the false prophet who &ldquo;leads you astray&rdquo; in Deut 13:5. Manasseh functions as a false prophet in royal office — he is the king as the anti-Moses. The comparison to &ldquo;the nations YHWH had destroyed&rdquo; is the strongest possible indictment: Israel has descended below the covenant-free pagans who preceded them. Greater privilege = greater accountability (cf. Amos 3:2).</p>",
    "10": "<p>&ldquo;The LORD said through his servants the prophets&rdquo; — the plural marks that this is not an isolated oracle but the sustained prophetic witness of the period (Isaiah, Micah, and the unnamed prophets of the Assyrian era all preached in this context). The indirect delivery — the narrator summarizes rather than quoting individual oracles — is the Deuteronomistic History&rsquo;s way of showing that the prophetic word was pervasive and unavoidable. The disaster that follows is not unforeseen; it was announced.</p>",
    "11": "<p>The prophetic indictment names three grounds: (1) <em>ḥiqqûṣîm</em> — &ldquo;detestable acts&rdquo; (from <em>šāqaṣ</em>, to abhor/detest — a stronger term than <em>tôʿēḇāh</em>); (2) &ldquo;more evil than the Amorites before him&rdquo; — the comparison restated; (3) &ldquo;made Judah sin with his idols (<em>gillûlîm</em>).&rdquo; <em>Gillûlîm</em> — a deliberately contemptuous term for idols, likely derived from <em>gēl</em> (dung-pellets) — is Ezekiel&rsquo;s characteristic pejorative for pagan cult objects (used 39 times in Ezekiel). Its use here links Manasseh&rsquo;s idols to the language of the exile prophets who interpreted the destruction Manasseh brought on.</p>",
    "12": "<p>&ldquo;I am going to bring such disaster on Jerusalem and Judah that the ears of everyone who hears about it will tingle.&rdquo; <em>Wəṣilᵉlāh šᵉtê ʾoznāyw</em> — &ldquo;both his ears will tingle/ring.&rdquo; The formula occurs in 1 Sam 3:11 (Eli&rsquo;s house) and Jer 19:3 (Jerusalem&rsquo;s destruction) — it marks an event so catastrophic that merely hearing about it produces a physical sensation of shock. The oracle announces what will become the Babylonian exile without yet naming the agent.</p>",
    "13": "<p>&ldquo;I will stretch over Jerusalem the measuring line used against Samaria and the plumb line used against the house of Ahab.&rdquo; <em>Qaw šōmᵉrôn</em> (Samaria&rsquo;s measuring line) and <em>mišqelet bêt ʾaḥʾāḇ</em> (Ahab&rsquo;s plumb line) are the architect&rsquo;s instruments — used here as demolition tools. When a builder stretches a line and drops a plumb, he is measuring whether the wall is true; here YHWH is measuring Jerusalem against the same standard he applied to Samaria (destroyed 722 BCE) and Ahab&rsquo;s house (destroyed within a generation). The image continues: &ldquo;I will wipe Jerusalem as one wipes a dish, wiping it and turning it upside down&rdquo; — the ordinary household act of cleaning becomes an image of total erasure.</p>",
    "14": "<p>&ldquo;I will abandon the remnant of my inheritance (<em>šᵉʾērît naḥălātî</em>) and hand them over to their enemies.&rdquo; <em>Naḥălāh</em> (inheritance/portion) is the covenantal term for Israel as YHWH&rsquo;s share among the nations (Deut 4:20; 9:26, 29; 32:9). YHWH&rsquo;s &ldquo;abandoning&rdquo; (<em>nāṭaš</em>) his inheritance is the sharpest possible reversal of the covenant: the God who &ldquo;does not forsake his people&rdquo; (1 Sam 12:22; Ps 94:14) announces that covenant forsaking has been so complete on Israel&rsquo;s side that the relationship is structurally terminated. The <em>šᵉʾērît</em> (remnant) had been the language of hope; here it is the object of abandonment.</p>",
    "15": "<p>The reason for the abandonment is rooted in the Exodus itself: &ldquo;from the day their ancestors came out of Egypt until this day.&rdquo; The rebellion is not a recent development but a lifelong pattern — the Deuteronomistic History&rsquo;s most comprehensive statement of Israel&rsquo;s chronic covenant failure. The phrase &ldquo;provoking my anger&rdquo; (<em>makhʿîsîm ʾōtî</em>) — causing YHWH grief/anger — is the emotional register of divine relationship: the abandoned covenant partner.</p>",
    "16": "<p>&ldquo;Moreover, Manasseh shed so much innocent blood (<em>dām nāqî</em>) that he filled Jerusalem from end to end.&rdquo; <em>Dām nāqî</em> — &ldquo;innocent blood&rdquo; — is the specific term for judicial murder and extrajudicial killing (Gen 9:6; Deut 19:10; Jer 7:6; 22:3). The Targum and rabbinic tradition identify Manasseh&rsquo;s killing of prophets, specifically Isaiah, as among these acts. The &ldquo;from end to end&rdquo; (<em>peh ʾel peh</em> — literally &ldquo;mouth to mouth&rdquo;) is a measure of completeness: the innocent blood saturated the city. The shedding of innocent blood is identified in the Deuteronomistic History as the sin that ultimately could not be atoned (24:4).</p>",
    "17": "<p>The regnal summary formula: acts and sins recorded in the annals. The notation &ldquo;including the sin he committed&rdquo; (<em>wəḥaṭṭāʾtô ʾăšer ḥāṭāʾ</em>) — &ldquo;his sin which he sinned&rdquo; — is an unusually redundant phrasing that the narrator uses to underscore that the annals contain incriminating material, not merely administrative record.</p>",
    "18": "<p>Manasseh is buried in the garden of his palace — <em>gān ʿuzzāʾ</em>, the Garden of Uzza — not in the City of David where the covenant kings were buried. The location of burial outside the royal tombs is theologically significant in Kings: the kings buried in the city of David are implicitly within the covenant succession; those buried elsewhere are distanced from it. Amon will be buried in the same garden (v26).</p>",
    "19": "<p>Amon: twenty-two years old, reigned two years. The brevity of his reign — two years — stands in stark contrast to his father&rsquo;s fifty-five. The short reign is both historical fact and literary comment: Manasseh&rsquo;s dynasty could not sustain itself. The mother&rsquo;s name, Meshullemeth daughter of Haruz of Jotbah, is preserved — the Deuteronomistic History maintains the maternal genealogy for all Judean kings.</p>",
    "20": "<p>&ldquo;He did what was evil in the sight of YHWH, as his father Manasseh had done.&rdquo; The evaluative formula for Amon is the simplest possible: he repeated his father&rsquo;s pattern without variation. The interesting contrast with Manasseh is that Amon receives no extended prophetic oracle and no attention to specific sins — his reign is too brief to establish independent theological significance. He is the continuation of Manasseh&rsquo;s trajectory without Manasseh&rsquo;s length.</p>",
    "21": "<p>&ldquo;He walked in all the way his father walked, worshipping the idols (<em>gillûlîm</em>) his father had worshipped and bowing down to them.&rdquo; <em>Hālak bəderek</em> — &ldquo;to walk in the way of&rdquo; — is the Deuteronomistic History&rsquo;s standard moral evaluation formula. The negative form (&ldquo;did not walk in the way of David&rdquo;) is the condemnation; the positive form (&ldquo;walked in all the way of his father&rdquo;) — when the father is Manasseh — is equally damning. The <em>gillûlîm</em> recurs from v11: Amon inherits both the idols and the contempt they deserve.</p>",
    "22": "<p>&ldquo;He abandoned (<em>ʿāzaḇ</em>) YHWH, the God of his ancestors, and did not walk in the way of YHWH.&rdquo; <em>ʿāzaḇ</em> — &ldquo;to abandon/forsake&rdquo; — is the covenantal term for covenant desertion (Deut 28:20; 31:16; Jer 1:16). The contrast with Josiah&rsquo;s mother&rsquo;s name in 22:1 (<em>Yᵉḏîḏāh</em> — &ldquo;beloved of YHWH&rdquo;) is the narrator&rsquo;s subtle marker of what is coming: out of Amon&rsquo;s house comes the beloved king.</p>",
    "23": "<p>Amon&rsquo;s officials (<em>ʿăḇādāyw</em> — his servants/courtiers) conspire and assassinate him in his palace. The conspiracy is palace-internal — not a popular revolt but a court coup. The motive is not stated; later scholarship has proposed anti-Assyrian or pro-reform factions, but the text does not explain. The narrator is interested in the theological, not the political, mechanism.</p>",
    "24": "<p>&ldquo;The people of the land (<em>ʿam hāʾāreṣ</em>) killed all who had conspired against King Amon and made his son Josiah king in his place.&rdquo; The <em>ʿam hāʾāreṣ</em> — &ldquo;people of the land&rdquo; — is a recurring political actor in Kings: the free landowning citizenry who function as a constitutional check on palace coups (cf. 11:14, 18-20; 14:21; 16:15). They punish the assassins and install the legitimate heir. Their action here protects the Davidic succession that YHWH promised to preserve and ensures that Josiah, not a usurper, occupies the throne.</p>",
    "25": "<p>Standard negative regnal summary for Amon. The brevity of the notice matches the brevity of the reign.</p>",
    "26": "<p>Amon buried in the Garden of Uzza — the same location as Manasseh (v18). Father and son share the garden burial, both excluded from the City of David&rsquo;s covenant tombs. The dynasty resumes with Josiah, the great-grandson of Manasseh, who will reverse everything his ancestor set up.</p>"
  },
  "22": {
    "1": "<p>Josiah was eight years old at his accession — the second child-king after Joash (2 Kgs 11:21), who also acceded to the throne after an assassination. The eight-year-old king will grow into the most faithful king of the Davidic line. The regnal length — thirty-one years — is the middle length, neither the extreme of Manasseh&rsquo;s fifty-five nor the brevity of Amon&rsquo;s two. Josiah&rsquo;s mother&rsquo;s name, <em>Yᵉḏîḏāh</em> (&ldquo;beloved of YHWH&rdquo;), is programmatic: the beloved king&rsquo;s mother carries the divine epithet.</p>",
    "2": "<p>&ldquo;He did what was right in the sight of YHWH and followed completely the way of his ancestor David, not turning aside to the right or to the left.&rdquo; The phrase &ldquo;not turning aside right or left&rdquo; (<em>lōʾ sār yāmîn ûśmōʾl</em>) is the Deuteronomic formula for perfect covenant fidelity (Deut 5:32; 17:20; Josh 1:7). It is applied only to David and Josiah in the entire Deuteronomistic History — the two kings who fully embody covenant faithfulness. The comparison is to &ldquo;his ancestor David&rdquo; (<em>kᵉkol derek dāwîḏ ʾāḇîyw</em>) — not merely &ldquo;as David did&rdquo; but &ldquo;in the complete way of David.&rdquo;</p>",
    "3": "<p>In Josiah&rsquo;s eighteenth year he sends Shaphan to the temple for the repair. The eighteenth year (621 BCE) is the theological pivot of the narrative — the year of the book&rsquo;s discovery. Shaphan (<em>šāpān</em> — rock hyrax) becomes one of the most important figures in the late monarchic period: he and his family (Ahikam, Gedaliah) repeatedly protect prophets and reformers (Jer 26:24; 36:10-12; 40:5-6). The <em>sōpēr</em> (secretary/scribe) was a senior state official with both administrative and literary responsibilities.</p>",
    "4": "<p>Hilkiah the high priest (<em>hakkōhēn haggādôl</em>) is to count the money brought to the temple — temple income from donors channeled through doorkeepers. The administrative machinery of Josiah&rsquo;s reform is organized: money gathered, supervisors appointed, workers paid. The repair of the temple is the physical analog to the spiritual repair Josiah will undertake — both require systematic attention to what has been neglected.</p>",
    "5": "<p>The repair supervisors (<em>pəqûḏê habbayit</em>) are to pay the workers. The temple workers are <em>ʿōśê hāmᵉlāʾkāh</em> — &ldquo;those who do the work&rdquo; — the same phrase used for the craftsmen of the Mosaic tabernacle (Exod 36:2, 4, 8). The terminology links Josiah&rsquo;s temple repair to the original construction of Israel&rsquo;s sacred dwelling.</p>",
    "6": "<p>Carpenters (<em>ḥārāšîm</em>), builders (<em>bōnîm</em>), stonemasons (<em>gōdᵉrê ḥômaʿ</em>), timber (<em>ʿēṣ</em>), and dressed stone (<em>ʾabnê māḥṣēḇ</em>). The listing of specific building trades and materials reflects the administrative precision of the reform project. The Deuteronomistic historian includes the detail to establish that the temple repair was real and systematic, not a symbolic gesture.</p>",
    "7": "<p>&ldquo;They were not required to keep accounts for the money entrusted to them, because they were acting honestly (<em>ʾĕmet</em>).&rdquo; <em>ʾĔmet</em> — faithfulness/reliability/truth — is the term for covenantal integrity (Exod 18:21; Ps 15:2). The workers&rsquo; <em>ʾĕmet</em> is what makes accounting unnecessary: where there is faithfulness, there is no need for oversight. The same principle operated in the earlier temple repair of Joash (2 Kgs 12:15). The exemption from accounting is a literary marker of moral integrity.</p>",
    "8": "<p>Hilkiah announces to Shaphan: &ldquo;I have found the <em>sēfer hattôrāh</em> — the Book of the Law — in the house of YHWH.&rdquo; This is the most significant textual discovery in the OT narrative. The <em>sēfer hattôrāh</em> is widely identified in scholarship as some form of Deuteronomy, given that the subsequent reform precisely targets Deuteronomy&rsquo;s prohibitions. The verb <em>māṣāʾ</em> — &ldquo;found&rdquo; — carries the covenantal resonance of &ldquo;discovering what was lost.&rdquo; Hilkiah gives the book to Shaphan; Shaphan reads it; then reads it to the king.</p>",
    "9": "<p>Shaphan&rsquo;s report to the king covers two items: (1) the money has been disbursed to the supervisors and workers, and (2) Hilkiah has given him a book. The administrative item first, then the potentially explosive textual item — the sequence mirrors the administrative context in which the discovery was embedded. Temple repair finances led to the Torah&rsquo;s rediscovery: the material act of restoration and the textual act are linked.</p>",
    "10": "<p>Shaphan reads the book aloud to the king — <em>wayyiqrāʾhû ʿal pᵉnê hammelek</em>, &ldquo;read it before the face of the king.&rdquo; The oral reading is the primary mode of Torah reception (Deut 31:11-13; Neh 8:1-8): the king must hear the law, not merely possess it. The Torah is not a private text but a public, oral covenant document. The reading before the king anticipates the covenant-reading before all Israel in ch23.</p>",
    "11": "<p>&ldquo;When the king heard the words of the Book of the Law, he tore his clothes (<em>wayyiqraʿ ʾet bᵉgādāyw</em>).&rdquo; The tearing of garments is the physical expression of grief and crisis: Jacob at Joseph&rsquo;s supposed death (Gen 37:34), David at Saul&rsquo;s death (2 Sam 1:11), Hezekiah at Sennacherib&rsquo;s ultimatum (19:1). For Josiah, the grief is specifically covenantal: the hearing of the Torah&rsquo;s curses in light of Israel&rsquo;s manifest non-compliance produces the grief of a king who understands what the book means for his people.</p>",
    "12": "<p>Josiah dispatches a five-person delegation to &ldquo;inquire of YHWH&rdquo; (<em>dərəšû ʾet YHWH</em>) — the technical term for prophetic consultation (1 Kgs 22:5, 8; Jer 21:2). The delegation includes the high priest, a court official, the secretary, and the king&rsquo;s attendant — senior representatives of temple, court, and administration. The fact that Josiah sends others rather than going himself is not evasion but protocol: the king sends delegations for oracular consultation.</p>",
    "13": "<p>&ldquo;Inquire of YHWH for me, for the people, and for all Judah about what is written in this book that has been found. Great is YHWH&rsquo;s anger that burns against us because our ancestors did not obey (<em>šāmᵉʿû</em>) the words of this book, to do according to everything written for us.&rdquo; Josiah&rsquo;s framing of the inquiry is remarkable: he immediately reads the book as a word of judgment already in process, not as a future threat. The &ldquo;for us&rdquo; (<em>ʿālênû</em>) shows that he identifies with his ancestors&rsquo; failure, not as a spectator. The <em>šmʿ</em>-failure (not obeying/listening) is the exact reverse of the <em>šmʿ</em>-command that Deuteronomy begins with: &ldquo;Hear (<em>šᵉmaʿ</em>), O Israel.&rdquo;</p>",
    "14": "<p>The delegation goes to Huldah the prophetess — <em>hûlḏāh hannᵉḇîʾāh</em> — wife of Shallum, keeper of the wardrobe, living in the Second District of Jerusalem. The choice of Huldah over the contemporary prophets Jeremiah (active from 627 BCE) and Zephaniah (active under Josiah) has generated scholarly discussion; the narrative offers no explanation. Huldah is one of four named female prophets in the OT (Miriam, Deborah, Huldah, Noadiah — Noadiah is a false prophet). Her oracle authenticates the book and determines Judah&rsquo;s response to it. The &ldquo;keeper of the wardrobe&rdquo; (<em>šōmēr habbᵉgādîm</em>) — her husband&rsquo;s title — indicates an inner-court official position.</p>",
    "15": "<p>&ldquo;This is what YHWH, the God of Israel, says: Tell the man who sent you to me&rdquo; — the standard prophetic messenger formula (<em>kōh ʾāmar YHWH</em>), indicating that Huldah speaks as YHWH&rsquo;s authorized messenger. She does not speak in her own name but transmits the divine word. The referential &ldquo;the man who sent you&rdquo; (not &ldquo;the king&rdquo;) may reflect the formal distance of prophetic address or a deliberate de-emphasizing of royal status.</p>",
    "16": "<p>&ldquo;I am going to bring disaster on this place and its people, according to everything written in the book the king of Judah has read.&rdquo; Huldah confirms two things: (1) the book is authentic — it is YHWH&rsquo;s word; (2) the judgment it announces is certain and will come. The &ldquo;book the king of Judah has read&rdquo; is the standard by which history is being measured, and the measurement finds the people wanting. Josiah&rsquo;s reform, no matter how thorough, will not reverse the verdict — it will only determine the timing.</p>",
    "17": "<p>&ldquo;Because they have abandoned me (<em>ʿāzᵉḇûnî</em>) and burned incense to other gods, provoking my anger (<em>lᵉmaʿan hakhʿîsēnî</em>) through everything their hands have done, my anger (<em>ḥărātî</em>) will burn against this place and will not be quenched (<em>lōʾ tiḵbeh</em>).&rdquo; The <em>ʿāzaḇ</em>-<em>ḥārāh</em>-<em>lōʾ tiḵbeh</em> sequence — abandonment leading to anger that cannot be extinguished — is the covenant-curse vocabulary of Deuteronomy (Deut 29:20). The fire of divine anger echoes Elijah&rsquo;s fire at Carmel, but this is the fire of judgment, not vindication.</p>",
    "18": "<p>The oracle pivots to address Josiah specifically: &ldquo;As for the king of Judah who sent you to inquire of YHWH — say this to him.&rdquo; The personal oracle for Josiah is separated from the national oracle by the structural marker &ldquo;say this to him.&rdquo; The distinction is crucial: collective judgment and individual exception occupy the same prophetic word simultaneously.</p>",
    "19": "<p>&ldquo;Because your heart was responsive (<em>wayyikkānēʿ lᵉḇāḇᵉkā</em>) and you humbled yourself before YHWH when you heard what I spoke against this place and its people.&rdquo; <em>Kānāʿ</em> — to humble/subdue — is used only twice in the Deuteronomistic History in this self-humbling sense: 1 Kgs 21:29 of Ahab, and here of Josiah. Both humiliations temporarily defer divine judgment. The term carries the sense of a high thing brought low — the king who lowers himself before the word earns the word&rsquo;s mercy. YHWH specifies what he heard: (1) tearing garments; (2) weeping before him. The physical acts of grief are the evidence of the heart&rsquo;s response.</p>",
    "20": "<p>&ldquo;Therefore I will gather you to your ancestors, and you will be buried in peace (<em>bəšālôm</em>). Your eyes will not see all the disaster I am going to bring on this place.&rdquo; The promise of a peaceful death is the personal reward for Josiah&rsquo;s humility. The word <em>šālôm</em> — wholeness/peace — is the opposite of the curse. Josiah will be gathered to his ancestors before the catastrophe. The irony that follows in 23:29-30 is sharp: Josiah dies in battle at Megiddo, which seems inconsistent with &ldquo;buried in peace.&rdquo; The rabbinic and Christian interpretation is that &ldquo;in peace&rdquo; means before the exile — he does not live to see Jerusalem fall, which is the peace promised.</p>"
  },
  "23": {
    "1": "<p>Josiah &ldquo;summoned all the elders of Judah and Jerusalem&rdquo; — the political assembly precedes the covenantal assembly. The gathering of the elders (<em>ziqnê</em>) as covenant witnesses is the Mosaic pattern: Moses summoned the elders for the Passover institution (Exod 12:21) and covenant ratification (Exod 24:1). The covenantal event requires representative witnesses.</p>",
    "2": "<p>The king goes to the house of YHWH with all the men of Judah, all the inhabitants of Jerusalem, the priests, the prophets, and all the people from the least to the greatest — <em>lᵉmiqāṭōn wəʿad gādôl</em>. The universality formula marks this as a covenant assembly, not merely a royal ceremony. The king reads &ldquo;in their ears all the words of the Book of the Covenant&rdquo; (<em>sēfer habbᵉrît</em>) — the public oral reading of the covenant text, the renewal of the Sinai scene. The reading is loud enough to enter their ears: covenant hearing precedes covenant commitment.</p>",
    "3": "<p>&ldquo;The king stood beside the pillar (<em>ʿāmad ʿal hāʿammûḏ</em>) and renewed the covenant before YHWH.&rdquo; The pillar/column was the royal standing place in the temple (cf. 11:14; 2 Chr 34:31). Josiah&rsquo;s renewed covenant includes three Deuteronomic elements: (1) <em>lālek ʾaḥar YHWH</em> — to follow/walk after YHWH; (2) <em>lišmōr miṣwōtāyw</em> — to keep his commandments; (3) <em>bəkol lēḇ ûḇəkol nepeš</em> — with all heart and all soul. The last phrase is the beginning of the Shema (Deut 6:5) applied covenantally. &ldquo;All the people entered the covenant&rdquo; (<em>wayyaʿămōḏ kol hāʿām babbᵉrît</em>) — the covenant is not imposed but collectively ratified.</p>",
    "4": "<p>The systematic purge begins: all vessels made for Baal, Asherah, and the starry hosts are removed from the temple and burned at the Kidron Valley — the valley east of Jerusalem that served as the city&rsquo;s ritual dump site (cf. 1 Kgs 15:13; 2 Kgs 23:6, 12). The ash is then carried to Bethel — sending the ash of Judah&rsquo;s idols to the epicenter of Israel&rsquo;s apostasy. The <em>ʾidolatrous priests</em> (<em>kᵉmārîm</em>) — a word used only for illegitimate cult personnel — are named for dismissal.</p>",
    "5": "<p>The <em>kᵉmārîm</em> — a contemptuous term for pagan priests — who burned incense (<em>wayyaqqēṭer</em>) at the high places in Judah&rsquo;s towns are dismissed. The targets include the cults of the sun, moon, constellations (<em>mazzālôt</em>), and all the starry hosts — the full Mesopotamian astral pantheon Manasseh had introduced. <em>Bāmôt</em> (high places) from Jerusalem&rsquo;s surroundings to Geba in the north and Beersheba in the south are defiled.</p>",
    "6": "<p>The Asherah pole is removed from the house of YHWH — the object Manasseh had placed inside the temple (21:7) — taken to the Kidron Valley, burned, ground to dust, and the dust scattered over the graves of common people. The five-step destruction sequence (remove, burn, grind to dust, scatter on graves) is the most thorough possible desecration of the cult object: the graves of the common people, being ritually defiling, contaminate whatever is scattered on them.</p>",
    "7": "<p>The quarters of the <em>qᵉḏēšîm</em> (<em>weˀet-bāttê haqqᵉḏēšîm</em>) are torn down — the male shrine prostitutes (<em>qādēš</em>, masculine of <em>qᵉḏēšāh</em>) whose quarters were inside the temple complex, where women wove hangings (<em>bāttîm</em>) for the Asherah. The combination of male cult prostitution and the Asherah weaving lodge in the temple precinct indicates how thoroughly the Solomonic temple had been converted to syncretistic use during Manasseh&rsquo;s reign.</p>",
    "8": "<p>Josiah brings all the priests from the cities of Judah to Jerusalem and defiles (<em>wayᵉṭammēʾ</em>) the high places from Geba to Beersheba. The defilement is ritual: by bringing human bones or other impurity into contact with the high places, they are rendered unusable for worship. The centralization of the priesthood in Jerusalem follows Deut 12:5-7: all sacrifice is to happen at the single chosen place, not at local high places.</p>",
    "9": "<p>The priests from the defiled high places are not permitted to serve at the Jerusalem altar — there is a hierarchy of cultic purity even within the reform. They may eat unleavened bread among their priestly brothers but not serve at the altar. The <em>matzot</em> (unleavened bread) here likely refers to the priestly portion of offerings; the high-place priests are maintained but their altar service is permanently restricted. This nuanced approach — not executing them but restricting them — is a pastoral accommodation of existing cultic personnel.</p>",
    "10": "<p>&ldquo;He desecrated (<em>waytammēʾ</em>) Topheth, which is in the Valley of Ben-Hinnom (<em>gê ben hinnōm</em>), so that no one could sacrifice his son or daughter in the fire to Molech.&rdquo; <em>Tōpet</em> — the fire-altar site in the valley south of Jerusalem — was the location of child sacrifice to Molech, practiced by Manasseh (21:6) and apparently by many in Jerusalem (Jer 7:31-32; 19:5-6). The <em>gê ben hinnōm</em> (Valley of Ben-Hinnom) will contract in later Hebrew to <em>gêhinnōm</em> — &ldquo;Gehenna&rdquo; — and become the NT&rsquo;s primary term for the place of eschatological fire (Matt 5:22, 29-30). Josiah&rsquo;s defilement of the site is the historical action behind the name; the valley that was the site of infant burning becomes the image of divine judgment.</p>",
    "11": "<p>The horses dedicated to the sun (<em>hassûsîm ʾăšer nātᵉnû malkê yᵉhûḏāh lāšemeš</em>) — sun-worship in ANE religion involved ritual horse processions dedicated to the sun deity — are removed from the temple entrance and their solar chariots are burned. The astral cults involved elaborate cultic paraphernalia; the Assyrian sun-worship that Manasseh promoted included horse and chariot dedications documented in both biblical and extra-biblical texts.</p>",
    "12": "<p>Josiah pulls down the roof altars built by Ahaz (the <em>ʿăliyyōt ʾāḥāz</em>) and the altars built by Manasseh in the two courts of the temple. The accumulated idolatry of two previous kings is systematically demolished. The ashes are cast into the Kidron — the ritual dumping ground. The temple is being stripped back to its original Solomonic configuration.</p>",
    "13": "<p>&ldquo;The king desecrated the high places that were east of Jerusalem on the south side of the Mount of Corruption (<em>har hammašḥît</em>) — the shrines Solomon king of Israel had built for Ashtoreth the detestable god of the Sidonians, for Chemosh the detestable god of Moab, and for Milcom the detestable god of the Ammonites.&rdquo; The &ldquo;Mount of Corruption&rdquo; is the south ridge of the Mount of Olives — called <em>har hammišḥāh</em> (&ldquo;mount of anointing&rdquo;) in 11:7, now <em>har hammašḥît</em> (&ldquo;mount of corruption/destruction&rdquo;) — a wordplay that marks Solomon&rsquo;s idolatrous high places as the corruption of what should have been a place of anointing. These shrines had stood for over 300 years since Solomon built them (1 Kgs 11:7-8).</p>",
    "14": "<p>The sacred stones (<em>maṣṣēḇôt</em>) are smashed — the standing stones that functioned as Canaanite cultic markers, prohibited by Deut 12:3 and Exod 23:24. The Asherah poles (<em>ʾăšērîm</em>) are cut down. The sites are covered with human bones (<em>ʿaṣāmôt</em>) — the most powerful available defiling agent (Num 19:16). The systematic use of human bones to defile cultic sites is a form of permanent disqualification: a site covered with bones can never again be used for sacrifice.</p>",
    "15": "<p>Even the Bethel altar — the oldest and most symbolically powerful site of the northern apostasy, built by Jeroboam son of Nebat (1 Kgs 12:28-29) — is demolished, burned, ground to dust, and the Asherah burned. The prophecy of the unnamed man of God from Judah (1 Kgs 13:2) — who foretold that &ldquo;a son named Josiah will be born to the house of David and will burn human bones on you&rdquo; — is here fulfilled, approximately 300 years after it was spoken. The fulfillment demonstrates that YHWH&rsquo;s prophetic word is not merely predictive but historically executive.</p>",
    "16": "<p>Josiah notices the tombs on the hillside and has bones taken from them and burned on the Bethel altar — defiling it with human bones exactly as the man of God had prophesied (&ldquo;bones burned on it,&rdquo; 1 Kgs 13:2). The 300-year gap between prophecy and fulfillment is the narrator&rsquo;s implicit argument for the reliability of the prophetic word: no human planner could have staged this.</p>",
    "17": "<p>Josiah inquires about a particular monument and is told it is the tomb of &ldquo;the man of God who came from Judah and predicted these things which you have done against the altar at Bethel.&rdquo; The irony is layered: the man of God whose bones were buried at Bethel was the prophet whose disobedience on the return journey led to his death (1 Kgs 13:11-32), yet his prophecy was entirely accurate. The accuracy of the prophecy transcended the prophet&rsquo;s personal failure — the word YHWH gave him was true regardless of his subsequent disobedience.</p>",
    "18": "<p>&ldquo;Leave him alone; let no one disturb his bones.&rdquo; Josiah preserves both the man of God&rsquo;s tomb and the tomb of the Samarian prophet who buried him (1 Kgs 13:31) — the two are protected together. The preservation honors the prophetic word that has just been fulfilled; the man of God&rsquo;s bones are the prophetic marker of what has happened.</p>",
    "19": "<p>Josiah extends the reform to Samaria — the former northern kingdom now under Assyrian provincial administration — removing the shrines at the high places and doing &ldquo;everything he had done at Bethel.&rdquo; The reach of Josiah&rsquo;s reform into the former northern territory is possible because Assyrian power is waning (Assyria falls to Babylon in 612 BCE); Josiah fills the political vacuum with the reform. The inclusion of Samarian high places represents the implicit reunification of Israel and Judah under the covenant standard.</p>",
    "20": "<p>Josiah slaughters all the priests of the northern high places on their own altars and burns human bones on them. The parallel to the 1 Kgs 13:2 prophecy is now fully enacted. The slaughter of the high-place priests in Samaria is more severe than the treatment of Judean high-place priests (v9: those were restricted but not killed) — the northern apostasy, being longer and more entrenched, receives harsher treatment.</p>",
    "21": "<p>&ldquo;The king commanded all the people: Celebrate the Passover to YHWH your God, as it is written in this Book of the Covenant.&rdquo; The Passover command closes the reform cycle: the book was found (ch22), the covenant was renewed (23:1-3), the cultic apparatus of apostasy was dismantled (23:4-20), and now the foundational festival is restored. Passover is the feast that defines Israel as the redeemed people of YHWH (Exod 12:14); its restoration after a long lapse is the resumption of the foundational covenantal identity.</p>",
    "22": "<p>&ldquo;Not since the days of the judges who led Israel, nor throughout the entire period of the kings of Israel and the kings of Judah, had any such Passover been celebrated.&rdquo; The scope of the comparison is extraordinary: from the Judges through the entire united and divided monarchy, no Passover of this magnitude had been kept. The superlative marks Josiah&rsquo;s Passover as the culmination of the covenant renewal — the most complete single act of covenant restoration in Israel&rsquo;s history.</p>",
    "23": "<p>The specification: &ldquo;in the eighteenth year of King Josiah.&rdquo; The eighteenth year is the year of the book&rsquo;s discovery (22:3) — the covenant renewal and the Passover restoration are accomplished in the same year. The eighteenth year is the theological center of the entire Josiah narrative: it is the year in which YHWH&rsquo;s Torah is recovered and Israel&rsquo;s foundational festival is restored.</p>",
    "24": "<p>Josiah removes the mediums, spiritists, household gods (<em>ṭərāpîm</em>), idols (<em>gillûlîm</em>), and all detestable things seen in Judah and Jerusalem — completing the list from Manasseh&rsquo;s reign (21:6). The <em>ṭərāpîm</em> (household gods) are among the oldest and most persistent forms of Israelite syncretism (Gen 31:19-35; Judg 17:5; 1 Sam 19:13; Ezek 21:21). The comprehensiveness of the list signals that Josiah has reversed everything Manasseh instituted, matching item for item.</p>",
    "25": "<p>&ldquo;Neither before nor after Josiah was there a king like him who turned to YHWH with all his heart (<em>bəkol lᵉḇāḇô</em>), with all his soul (<em>bəkol napšô</em>), and with all his might (<em>ûḇəkol mᵉʾōḏô</em>), in accordance with all the Law of Moses.&rdquo; The three-part phrase is the Shema (Deut 6:5) applied to covenantal faithfulness. The superlative is total: Josiah is the king who most fully embodied the Shema. The comparison includes &ldquo;before&rdquo; — Josiah exceeds even David. Yet the following verse begins with the devastating <em>ʾak</em> — &ldquo;nevertheless.&rdquo;</p>",
    "26": "<p>&ldquo;Nevertheless (<em>ʾak</em>), YHWH did not turn away from the burning of his great anger, which blazed against Judah because of all that Manasseh had done to provoke him.&rdquo; The <em>ʾak</em> is the most devastating single word in the Josiah narrative: after the superlative praise of v25, it introduces the irreversibility of the divine judgment. Manasseh&rsquo;s sin was not merely great but structurally final — it set in motion a judgment that even the best subsequent king could not reverse. The innocent blood of v21:16 is specifically named in 24:4 as the sin that YHWH &ldquo;was not willing to pardon.&rdquo;</p>",
    "27": "<p>&ldquo;So YHWH said, &lsquo;I will remove Judah from my sight as I removed Israel. I will reject Jerusalem, the city I chose, and this temple, about which I said, &ldquo;There shall my Name be.&rdquo;&rsquo;&rdquo; The divine speech cancels the election promise explicitly: the city chosen, the temple named — both will be rejected. The <em>māʾas</em> (reject) applied to Jerusalem echoes the rejection of Saul (1 Sam 15:23, 26; 16:1) and Israel (2 Kgs 17:20). YHWH&rsquo;s <em>māʾas</em> is always the consequence of the covenant partner&rsquo;s prior abandonment of the relationship.</p>",
    "28": "<p>Josiah&rsquo;s regnal summary and reference to the annals. The standard closing formula marks the end of the Josiah account. The disaster of Megiddo (v29-30) falls outside the formal regnal summary, indicating it is epilogic rather than central to the narrator&rsquo;s theological evaluation.</p>",
    "29": "<p>Pharaoh Necho of Egypt marches to the Euphrates to support Assyria against the rising Babylonian empire. Josiah goes to intercept him at Megiddo — why is unstated. The possibilities: pro-Babylonian strategy, territorial defense, or misguided messianic zeal. Necho kills him at Megiddo. The terseness of the Hebrew — <em>wayyᵉmîtēhû ḇᵉmegiddô kᵉrᵉʾōtô</em>, &ldquo;he killed him at Megiddo when he encountered him&rdquo; — is stark: the greatest covenant king dies in three words. Megiddo (later <em>Harmāgᵉdôn</em> in Rev 16:16) is the place where Canaan&rsquo;s forces were defeated by Deborah and Barak (Judg 5:19) and where Ahaziah died (9:27); it accumulates military-eschatological significance.</p>",
    "30": "<p>Josiah&rsquo;s body is brought from Megiddo to Jerusalem by his servants in a chariot and buried in his own tomb. The <em>ʿam hāʾāreṣ</em> — the people of the land, who had made him king after Amon&rsquo;s assassination — anoint his son Jehoahaz. The same constitutional actors who preserved the Davidic line after Amon&rsquo;s coup (21:24) now install the new king after Josiah&rsquo;s unexpected death. The burial in Jerusalem, in his own tomb, fulfills Huldah&rsquo;s oracle: &ldquo;you will be gathered to your ancestors&rdquo; (22:20) — he dies before the exile.</p>",
    "31": "<p>Jehoahaz, twenty-three years old, reigns three months. The brevity — the same as Amon&rsquo;s — signals the rapid unraveling of everything Josiah built. His mother Hamutal, daughter of Jeremiah of Libnah, is noted — a different Jeremiah from the prophet. The maternal genealogy is maintained even in the post-Josiah collapse.</p>",
    "32": "<p>&ldquo;He did what was evil in the sight of YHWH, just as his predecessors had done.&rdquo; The formula reverts to the pre-Josiah standard, applied after a single verse of introduction. Josiah&rsquo;s reform has not taken root in his sons. The covenantal inheritance depends on the heart, not the institution; Josiah&rsquo;s personal Shema-faithfulness did not transmit to his heirs.</p>",
    "33": "<p>Pharaoh Necho imprisons Jehoahaz at Riblah in Hamath and imposes a tribute of one hundred talents of silver and a talent of gold on the land. Riblah in Hamath will become the place of judgment for the last Judean kings (25:6, 20-21). Egypt asserts tributary control over Judah; the political independence of the Davidic monarchy is functionally over.</p>",
    "34": "<p>Necho installs Eliakim son of Josiah as king and renames him Jehoiakim. The name-change (<em>ʿāzaḇ... wayyāśem</em>) from <em>ʾElyāqîm</em> (&ldquo;God establishes&rdquo;) to <em>Yəhôyāqîm</em> (&ldquo;YHWH establishes&rdquo;) is a marker of Egyptian authority over the divine naming of Judah&rsquo;s king: Necho substitutes the divine name in the king&rsquo;s name as an act of ownership. The exiling of Jehoahaz to Egypt, where he dies (Jer 22:11-12), removes the <em>ʿam hāʾāreṣ</em>&rsquo;s chosen king permanently.</p>",
    "35": "<p>Jehoiakim taxes the land to pay Necho&rsquo;s tribute — requiring each person to contribute according to their assessed wealth (<em>kᵉʿerkô</em>). The tribute system (100 talents silver, 1 talent gold) is extracted from the population rather than from the royal treasury, shifting the burden of imperial vassalage to the people. The same administrative extraction that Solomon used (1 Kgs 4:7) returns under Egyptian compulsion.</p>",
    "36": "<p>Jehoiakim&rsquo;s regnal notice: twenty-five years old, eleven-year reign. The eleven years spans the transition from Egyptian to Babylonian dominance (605 BCE: Battle of Carchemish). His mother Zebidah daughter of Pedaiah of Rumah is noted — the maternal genealogy continues.</p>",
    "37": "<p>&ldquo;He did what was evil in the sight of YHWH, just as his predecessors had done.&rdquo; The final verse of chapter 23 closes the chapter on the same formula that opened Jehoahaz&rsquo;s brief reign. The post-Josiah collapse is complete: the two sons who follow him both receive the standard condemnation. The last word of chapter 23 in Hebrew is <em>ʾăḇōtāyw</em> — &ldquo;his fathers&rdquo; — the kings who preceded him. Josiah&rsquo;s reform has left no successor; the &ldquo;fathers&rdquo; have triumphed over the son.</p>"
  }
}

def main():
    existing = load_comm('mkt-original', '2kings')
    merge_comm(existing, ORIGINAL)
    save_comm('mkt-original', '2kings', existing)
    print('2 Kings 21-23 original commentary written.')

if __name__ == '__main__':
    main()
